### ISSUE TITLE
Error when using HNSWLib/MemoryVectorStore

### ISSUE THREAD

**Issue by masasso** [langchain-ai/langchainjs#1019]
I am trying to use HNSWLib for the code below.
`
import { HNSWLib } from "langchain/vectorstores/hnswlib";
import { OpenAIEmbeddings } from "langchain/embeddings/openai";
console.log("Start HNSWLib vectorstore");
        
        const vectorStore = await HNSWLib.fromTexts(
            ["Hello world", "Bye bye", "hello nice world"],
            [{ id: 2 }, { id: 1 }, { id: 3 }],
            new OpenAIEmbeddings()
        );
        console.log("HNSWLib similaritySearch");
        const resultOne = await vectorStore.similaritySearch("hello world", 1);
        console.log("My result");
        console.log(resultOne);`

This is the error I am getting:

`
rejected promise not handled within 1 second: ReferenceError: Headers is not defined
extensionHostProcess.js:102
stack trace: ReferenceError: Headers is not defined
    at createRequest (/home/matheus/<package>/dist/extension.js:29734:21)
    at fetchAdapter (/home/matheus/<package>/dist/extension.js:29655:21)
    at dispatchRequest (/home/matheus/<package>/dist/extension.js:27012:10)
    at Axios.request (/home/matheus/Projects/<package>/dist/extension.js:26769:15)
    at Function.wrap [as request] (/home/matheus/<package>n/dist/extension.js:26652:15)
    at /home/matheus/Projects/<package>/dist/extension.js:28819:22
    at /home/matheus/Projects/<package>/dist/extension.js:25955:123
    at async RetryOperation._fn (/home/matheus/Projects/<package>/dist/extension.js:30236:12)
`

I did the same test for MemoryVectorStore and the same error is happening.

**Comment by cavillo** [comment]
Are you using Node v18? Switching to 18 did it for me.

thx to @LarchLiu in https://github.com/hwchase17/langchainjs/issues/747#issuecomment-1504487312 for pointing it out.

**Comment by masasso** [comment]
I am using Node v18.15.0 and npm v9.6.5
I also tested with node v19 and v20 but I get the exact same error on both.

**Comment by masasso** [comment]
I did a node js app here and it worked!
However, the problem persists inside the vscode extension application I am developing.

**Comment by kamalkech** [comment]
for me i get the error bellow and until now cannot found solution to fixe it:

```Error: Timeout was reached```

**Comment by kamalkech** [comment]
@masasso i am using node v18.16.0 i send request and i get any thing, i increase timeout still nothing
