### ISSUE TITLE
token from handleLLMNewToken return a stringified object for initializeAgentExecutorWithOptions

### ISSUE THREAD

**Issue by waptik** [langchain-ai/langchainjs#1048]
Hi. So i'm using the `chat-conversational-react-description`agent type of `initializeAgentExecutorWithOptions` while enabling streaming in openai's model. Whenu using the `handleLLMNewToken`callback handler, the value of token parameter is in the form of 
```sh
handleLLMNewToken { token: "" }
handleLLMNewToken { token: "{\n" }
handleLLMNewToken { token: "   " }
handleLLMNewToken { token: ' "' }
handleLLMNewToken { token: "action" }
handleLLMNewToken { token: '":' }
handleLLMNewToken { token: ' "' }
handleLLMNewToken { token: "Final" }
handleLLMNewToken { token: " Answer" }
handleLLMNewToken { token: '",\n' }
handleLLMNewToken { token: "   " }
handleLLMNewToken { token: ' "' }
handleLLMNewToken { token: "action" }
handleLLMNewToken { token: "_input" }
handleLLMNewToken { token: '":' }
handleLLMNewToken { token: ' "' }
handleLLMNewToken { token: "Hello" }
handleLLMNewToken { token: "!" }
handleLLMNewToken { token: " How" }
handleLLMNewToken { token: " can" }
handleLLMNewToken { token: " I" }
handleLLMNewToken { token: " assist" }
handleLLMNewToken { token: " you" }
handleLLMNewToken { token: " today" }
handleLLMNewToken { token: '?"\n' }
handleLLMNewToken { token: "}" }
handleLLMNewToken { token: "" }
```

instead of this 
```sh
handleLLMNewToken { token: "Hello" }
handleLLMNewToken { token: "!" }
handleLLMNewToken { token: " How" }
handleLLMNewToken { token: " can" }
handleLLMNewToken { token: " I" }
handleLLMNewToken { token: " assist" }
handleLLMNewToken { token: " you" }
handleLLMNewToken { token: " today" }
handleLLMNewToken { token: '?"\n' }
handleLLMNewToken { token: "" }
```

It doesn't matter whether i use `import { ChatOpenAI } from "langchain/chat_models/openai";` or `import { OpenAI } from "langchain/llms/openai";
`

Here's a simpliefied version of the source code: https://gist.github.com/waptik/191e2a38da8dd08bce55f42705f0b1a4

Original discord thread: https://discord.com/channels/1038097195422978059/1076182741374214285/1101815107337605140

**Comment by waptik** [comment]
So looking at the source code, i found out that output is because of how `FORMAT_INSTRUCTIONS` instructs the model to format its response. 
Is there a way to get the value of `action_input` when `"action": "Final Answer"` returned in `handleLLMNewToken`?

**Comment by RalissonMattias** [comment]
Same here, I tried some cases, but without success

**Comment by waptik** [comment]
> Same here, I tried some cases, but without success

Okay. Good to know i'm not the only person facing this issue. For now, i've disabled streaming until something positive happens in here

**Comment by RalissonMattias** [comment]
I need to use this because without it the response time is slow. Then I do some validations to make it work the way it is

**Comment by waptik** [comment]
I get your point. But you've got no choice but to disable streaming for now until you find a solution for it. One quick way to solving this is maybe request for consultation from the maker or top contributors to langchain if only they provide that service.
