### ISSUE TITLE
Storing vectors for multiple documents in supabase

### ISSUE THREAD

**Issue by haritiruna** [langchain-ai/langchainjs#1081]
I've successfully ingested a document into my supabase vector store and have been getting good results using `SupabaseHybridSearch` to chat with it. 

However, my use case is that I want to ingest multiple documents and I want to create a seperate chatbot for each document. 

I want to know how this would work in terms of storing vectors in supabase and accessing it through the frontend.

Do I create a seperate document vectors table for each document? Or add another id column to the table that I can filter on while doing the search?

The current `SupabaseHybridSearch` doesn't allow filters so I'm a bit stuck as to how to go about it. In Pinecone, I can use a single index and a namespace to reference difference documents to search from. How would this approach translate to Supabase?

**Comment by Tmeister** [comment]
I'm here looking for the same answer.

**Comment by Tmeister** [comment]
Following this, a [filter feature was added a few days ago](https://github.com/hwchase17/langchainjs/pull/905); I'm able to filter the Supabase vector store using metadata.
