### ISSUE TITLE
Error: SentenceSimilarityInputsCheck

### ISSUE THREAD

**Issue by mrcashcash** [langchain-ai/langchainjs#1083]
this error accrues while using HuggingFaceInferenceEmbeddings with NOT default model.

error - unhandledRejection: Error: SentenceSimilarityInputsCheck expected dict not list: `__root__` in `parameters`
    at HfInference.request (file:///C:/Users/USER/Documents/GitHub/chatbot-ui/node_modules/@huggingface/inference/dist/index.mjs:425:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async HfInference.featureExtraction (file:///C:/Users/USER/Documents/GitHub/chatbot-ui/node_modules/@huggingface/inference/dist/index.mjs:264:17)
    at async RetryOperation._fn (C:\Users\USER\Documents\GitHub\chatbot-ui\node_modules\p-retry\index.js:50:12) {
  attemptNumber: 7,
  retriesLeft: 0
}

all working fine if i use OpenAI embedding or HuggingFace default model

**Comment by matbee-eth** [comment]
I have this same issue

**Comment by ascrazy** [comment]
I've tried several `sentence-transformers/*` models and each outputs this error for me

**Comment by MitchellMonaghan** [comment]
same issue here

**Comment by markusleh** [comment]
It seems that you need to use models that have the `feature-extraction` API available.

See: https://discuss.huggingface.co/t/sentencesimilarityinputscheck-expected-dict-not-list-root-in-parameters/39715/2

**Comment by mbklein** [comment]
I'm getting this same error, and the model I'm attempting to use _does_ have the `feature-extraction` flag.

**Comment by ryendu** [comment]
having same issue here

**Comment by gins0023** [comment]
+1

**Comment by LinasKo** [comment]
+1

**Comment by 15rhema** [comment]
+1

**Comment by orchardc** [comment]
**Same bug here, with the latest "Microsoft.SemanticKernel.Connectors.AI.HuggingFace" Version="0.24.230918.1-preview"**
Almost 5 months since the bug has been raised ..

**Comment by blackge** [comment]
Same issue here.
