### ISSUE TITLE
Can't install hnswlib-node on windows without VSCode build tools installed

### ISSUE THREAD

**Issue by blozixdextr** [langchain-ai/langchainjs#113]
Please help to install...
![image](https://user-images.githubusercontent.com/2786905/220913305-cf266264-dbcf-4d08-be6d-5d6b6375ad64.png)

**Comment by sullivan-sean** [comment]
We're using `yarn workspaces` to manage the multiple packages in this repo. Here the dependency format `workspace:*` is not being properly recognized by `npm`. I think installing with `yarn add hnswlib-node` should work

**Comment by blozixdextr** [comment]
> We're using `yarn workspaces` to manage the multiple packages in this repo. Here the dependency format `workspace:*` is not being properly recognized by `npm`. I think installing with `yarn add hnswlib-node` should work
Thank you for assistant, I tried different ways , but got the same:

➤ YN0001: │ Error: langchain@workspace:^: Workspace not found (langchain@workspace:^)
    at je.getWorkspaceByDescriptor (C:\JS\langchainjs\.yarn\releases\yarn-3.4.1.cjs:439:3230)
    at $d.getCandidates (C:\JS\langchainjs\.yarn\releases\yarn-3.4.1.cjs:390:29582)
    at yf.getCandidates (C:\JS\langchainjs\.yarn\releases\yarn-3.4.1.cjs:391:1264)
    at yf.getCandidates (C:\JS\langchainjs\.yarn\releases\yarn-3.4.1.cjs:391:1264)
    at C:\GPTsalesBot\JS\langchainjs\.yarn\releases\yarn-3.4.1.cjs:439:7693
    at of (C:\JS\langchainjs\.yarn\releases\yarn-3.4.1.cjs:390:11070)
    at ge (C:\JS\langchainjs\.yarn\releases\yarn-3.4.1.cjs:439:7673)
➤ YN0000: └ Completed
➤ YN0000: Failed with errors in 0s 109ms

**Comment by nfcampos** [comment]
How did you install the langchain library @blozixdextr ? From npm or from GitHub?

**Comment by blozixdextr** [comment]
I have made git clone  (also tried on my local PC Win11  and remote host on Ubuntu 22 -- got the same problem)

**Comment by mayooear** [comment]
I have tested various versions of the library on a fresh repo and the error persists. I believe it is an issue with VS code installations and `node-pyb`

**Comment by nfcampos** [comment]
Do you have this issue when installing the library from npm/yarn? `npm install langchain` or `yarn add langchain`

**Comment by mayooear** [comment]
Yes I tried `yarn add  hnswlib-node` on windows and get the error below. I assume installing `Visual Studio` is required.

```
Command: node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@9.3.1
gyp info using node@18.14.2 | win32 | x64
gyp info find Python using Python version 3.10.10 found at
gyp ERR! find VS
gyp ERR! find VS msvs_version not set from command line or npm config        
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt      
gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio     
gyp ERR! find VS including the "Desktop development with C++" workload.      
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use 
gyp ERR! cwd C:\Users\MOshin\Desktop\langchain-test\node_modules\hnswlib-nodegyp ERR! node -v v18.14.2
gyp ERR! node-gyp -v v9.3.1
gyp ERR! not ok
```

**Comment by nfcampos** [comment]
Yes I'd assume so

**Comment by nfcampos** [comment]
Would be good to add to the docs page for hnswlib the bit about needing Vscode if installing on windows, something like here https://github.com/cocktailpeanut/dalai#step-1-install-visual-studio

**Comment by kwkr** [comment]
> Would be good to add to the docs page for hnswlib the bit about needing Vscode if installing on windows, something like here https://github.com/cocktailpeanut/dalai#step-1-install-visual-studio

I added a hint [here](https://github.com/hwchase17/langchainjs/pull/1036). Let me know if this needs some more in-depth dive.
