### ISSUE TITLE
Add Filtering Support for Milvus VectorDB in LangChainJS

### ISSUE THREAD

**Issue by pnutmath** [langchain-ai/langchainjs#1131]
I would like to request the implementation of filtering support for Milvus VectorDB in LangChainJS. This feature should allow users to perform complex filtering operations based on specific attributes or conditions, improving the search functionality and overall user experience when working with vector data.

**Comment by Harbon** [comment]
I need milvus filtering support too

**Comment by Sain11111** [comment]
+1111

**Comment by Sain11111** [comment]
I need milvus filtering support too +1
