### ISSUE TITLE
pgvector without Prisma

### ISSUE THREAD

**Issue by maxfurman** [langchain-ai/langchainjs#1188]
Hello, I'm trying to set up a project that uses LangChain to (among other things) store document embeddings in a vector column in our postgreSQL database. I'm not in love with the way Prisma handles things; is there a more direct way to get a VectorDataStore that connects to postgres?

**Comment by dqbd** [comment]
Hi @maxfurman!

Understandable, #1436 done by @MaximeThoonsen will introduce an alternative vector store based on `TypeORM`, which could be more interesting for you..

**Comment by MaximeThoonsen** [comment]
Hey @maxfurman, FYI the PR has been merged
