### ISSUE TITLE
Helper utilities to use Custom Embeddings

### ISSUE THREAD

**Issue by Glavin001** [langchain-ai/langchainjs#126]
Related to: https://github.com/hwchase17/langchain/issues/1260

## Problem

The default embeddings (e.g. Ada-002 from OpenAI, etc) are great **_generalists_**. However, they are not **_tailored_** for **your** specific use-case.

### Use Case

Write a full-stack TypeScript application which uses custom embeddings and could support Edge Runtimes with limited features ([1](https://nextjs.org/docs/messages/node-module-in-edge-runtime), [2](https://nextjs.org/docs/api-reference/edge-runtime))

## Proposed Solution

**_🎉 Customizing Embeddings!_**

> ℹ️  See [my tutorial / lessons learned](https://twitter.com/GlavinW/status/1627657346225676288?s=20) if you're interested in learning more, step-by-step, with screenshots and tips.

<img src="https://user-images.githubusercontent.com/1885333/221033175-de90a47d-d66c-489e-a360-c0386cbd36f4.png" width="auto" height="300" />

#### Embedding

```mermaid
flowchart LR

    subgraph "Similarity Search"
        direction LR

        CustomMatrix["Custom Embedding Matrix\n(e.g. custom-embedding.npy)"]
        Multiply["(Original Embedding) x (Matrix)"]
        CustomMatrix --> Multiply

        Text1["Original Texts #1, #2, #3..."]
        Raw1'["Original Embeddings #1, #2, #3, ..."]
        Custom1["Custom Embeddings #1, #2, #3, ..."]
        Text1-->Raw1'
        Raw1' --> Multiply
        Multiply --> Custom1

        DB["Vector Database"]
        Custom1 -->|Upsert| DB

        Search["Search Query"]
        EmbedSearch["Original Embedding for Search Query"]
        CustomEmbedSearch["Custom Embedding for Search Query"]

        Search-->EmbedSearch
        EmbedSearch-->Multiply
        Multiply-->CustomEmbedSearch

        SimilarFound["Similar Embeddings Found"]
        CustomEmbedSearch -->|Search| DB
        DB-->|Search Results|SimilarFound
    end
```

### Out of scope
- Training the custom embedding matrix, since it would require many other Python libraries. [Pre-train using Lanchain and store the matrix as a Numpy `.npy` file](https://github.com/hwchase17/langchain/issues/1260).

### Example

```typescript
import { CustomizeEmbeddings, OpenAIEmbeddings } from "langchain/embeddings";

/* === Generalized Embeddings === */
/* Embed queries */
const embeddings = new OpenAIEmbeddings();
const res = await embeddings.embedQuery("Hello world");

/* Embed documents */
const documentRes = await embeddings.embedDocuments(["Hello world", "Bye bye"]);

/* === Training Customized Embeddings === */
// Not supported in JavaScript/TypeScript. Use Langchain for Python: https://github.com/hwchase17/langchain/issues/1260

/* === Loading Customized Embeddings === */
const customEmbeddings = new CustomizeEmbeddings(embeddings);
customEmbeddings.load("custom-embedding.npy")

/* Embed queries */
const customRes = await customEmbeddings.embedQuery("Hello world");

/* Embed documents */
const customDocumentRes = await customEmbeddings.embedDocuments(["Hello world", "Bye bye"]);
```

## Recommended Reading

- [My tutorial / lessons learned](https://twitter.com/GlavinW/status/1627657346225676288?s=20)
- [Customizing embeddings from OpenAI Cookbook](https://github.com/openai/openai-cookbook/blob/main/examples/Customizing_embeddings.ipynb)
- @pullerz 's [blog post on lessons learned](https://twitter.com/AlistairPullen/status/1628557761352204288?s=20)

---

_P.S. I'd love to personally contribute this to the Langchain repo and community! Please let me know if you think it is a valuable idea and any feedback on the proposed solution. Thank you!_

**Comment by rikuthinks** [comment]
Thanks for bringing this up as an issue! +1

This would be an extremely valuable contribution to optimize for domain-specific use cases at scale, which is important when you're planning to have a high volume of queries. I would personally use this.

Here's one startup's feedback on why they decided to use custom embeddings: https://www.buildt.ai/blog/viral-ripout

**Comment by Glavin001** [comment]
Thanks, @rikuthinks ! Yes, I also highly recommend the Built blog post by @ Pullerz, I had included it in `Recommended Reading` above along with others I wrote/read -- check them out.

I'm hoping to find some time this or next week to contribute a Pull Request 🤞
