### ISSUE TITLE
When the API KEY expires  interface status code is 429

### ISSUE THREAD

**Issue by geekros** [langchain-ai/langchainjs#1278]
When the API KEY expires, the callback event fails to capture the relevant error information, and the interface status code is 429.

LangChain Version: 0.0.75

**Comment by nfcampos** [comment]
Hi, which callback event are you referring to?

**Comment by geekros** [comment]
handleLLMError or handleChainError will facilitate our handling of relevant error messages in the user interface.

> Hi, which callback event are you referring to?

**Comment by nfcampos** [comment]
What are you receiving inn handleLLMError?
