### ISSUE TITLE
Calling abortController.abort() does not stop the token stream.

### ISSUE THREAD

**Issue by phoenixz0024** [langchain-ai/langchainjs#1279]
Even when im always trying to abort my request from the API it is still streaming tokens

export default async function handler(req: NextRequest, context:NextFetchEvent
  ) {

    const abortController = new AbortController();

    abortController.abort();

   // call chain etc 

}

**Comment by miyauchiakira** [comment]
I could stop streaming by following this document.
https://js.langchain.com/docs/modules/models/chat/additional_functionality#cancelling-requests

It didn't work when I was using langchain v0.0.71, but it worked after updating to v0.0.84.

I hope it helps

**Comment by theogravity** [comment]
How would you do it using an agent executor?

**Comment by theogravity** [comment]
Looks like the info got updated, this did work for me

https://js.langchain.com/docs/modules/agents/additional_functionality
