### ISSUE TITLE
Convention Agent with Memory (vectorDB) caused error for get type

### ISSUE THREAD

**Issue by baobo5625** [langchain-ai/langchainjs#1281]
since MessagesPlaceholder will be converted in string format, but it was now casted as BaseMessage type

**Comment by baobo5625** [comment]
https://github.com/hwchase17/langchainjs/blob/bb60f4775e39b613284c1c9e9b7503d24ec97651/langchain/src/prompts/chat.ts#L65

From here, it would be better to have a message type called historical messages,  to explicitly tell gpt this is history context

like the prompt for conversation Agent etc

**Comment by Joshua-Shepherd** [comment]
Nice find!
