### ISSUE TITLE
add example of memory to agent

### ISSUE THREAD

**Issue by hwchase17** [langchain-ai/langchainjs#131]

**Comment by dantheman0207** [comment]
Second this! I would like to either have a chain that can use tools, or an agent that has memory, or some way to combine the two but I can't find an example of how that would work. If there is existing documentation for the python package I'm happy to translate it to javascript.

**Comment by matthieu-beteille** [comment]
+1

**Comment by iloukou** [comment]
This is areal p

> _No description provided._

This is a real problem. Do you find the solution?

**Comment by iloukou** [comment]
> I am going to attempt to add this functionality and update the documentation. I would like to assign this issue to me (unless you are already working on it @hwchase17 ).

Did you find the solution. It a real problem and no exemple anywhere

**Comment by deonvisser44** [comment]
Also having an issue with this. The agent works fine without memory, but when I add memory to the executor the expected output is logged, but never returned. Keep getting timeouts.

**Comment by ChanChar** [comment]
@deonvisser44 that executor [already sets up memory internally](https://github.com/hwchase17/langchainjs/blob/71d44743e17e9a6acd397eb19d28fcc2f98d1b39/langchain/src/agents/initialize.ts#L110-L125)

If you'd like to use custom memory, you can pass the memory as part of the options when using that initializer:

```typescript
const customMemory = new BufferMemory({
  chatHistory: new ChatMessageHistory(history),
  memoryKey: 'chat_history',
  returnMessages: true,
});

const executor = await initializeAgentExecutorWithOptions(tools, model, {
  agentType: 'chat-conversational-react-description',
  memory: customMemory,
  verbose: true,
});

const res = await executor.call({
  input: userMessage,
});
```

For tools that require memory, I found that adding the memory to the tool's constructor works. This is a similar pattern to how the  `ConversationChain` works. Expanding on the example above w/ a tool with memory:

```typescript
export class ToolWithMemory extends Tool {
  constructor(memory: <MemoryType>) {
    super();
    this.memory = memory
  }

  async _call(input: string) {
    // Do something with memory
    // this.memory.something

    return some_process(input)
  }
}


const customMemory = new BufferMemory({
  chatHistory: new ChatMessageHistory(history),
  memoryKey: 'chat_history',
  returnMessages: true,
});

// Use the same memory as the agent or you can also setup a separate one specific to holding "context" outside of the "chatHistory".
tools = [ToolWithMemory(memory: customMemory)]

const executor = await initializeAgentExecutorWithOptions(tools, model, {
  agentType: 'chat-conversational-react-description',
  memory: customMemory,
  verbose: true,
});

const res = await executor.call({
  input: userMessage,
});
```

**Comment by Boopalanoptisol** [comment]
@ChanChar how can we add the memory to   agentType: "chat-zero-shot-react-description", 

Could u please give any sample to understand

**Comment by Boopalanoptisol** [comment]
@jacoblee93  how can we add Memory to the **dynamic tool** by **using  agentType: "zero-shot-react-description",**.
So that in the chatbot if the user ask question related to the previous question, it will give correct response.

import { OpenAI } from "langchain/llms/openai";
import { initializeAgentExecutorWithOptions } from "langchain/agents";
import { DynamicTool } from "langchain/tools";

export const run = async () => {
  const model = new OpenAI({ temperature: 0 });
  const tools = [
    new DynamicTool({
      name: "FOO",
      description:
        "call this to get the value of foo. input should be an empty string.",
      func: async () => "baz",
    }),
    new DynamicTool({
      name: "BAR",
      description:
        "call this to get the value of bar. input should be an empty string.",
      func: async () => "baz1",
    }),
  ];

  const executor = await initializeAgentExecutorWithOptions(tools, model, {
    agentType: "zero-shot-react-description",
  });

  console.log("Loaded agent.");

  const input = `What is the value of foo?`;

  console.log(`Executing with input "${input}"...`);

  const result = await executor.call({ input });

  console.log(`Got output ${result.output}`);
};

**Comment by KeenanFernandes2000** [comment]
> @jacoblee93 how can we add Memory to the **dynamic tool** by **using agentType: "zero-shot-react-description",**. So that in the chatbot if the user ask question related to the previous question, it will give correct response.
> 
> import { OpenAI } from "langchain/llms/openai"; import { initializeAgentExecutorWithOptions } from "langchain/agents"; import { DynamicTool } from "langchain/tools";
> 
> export const run = async () => { const model = new OpenAI({ temperature: 0 }); const tools = [ new DynamicTool({ name: "FOO", description: "call this to get the value of foo. input should be an empty string.", func: async () => "baz", }), new DynamicTool({ name: "BAR", description: "call this to get the value of bar. input should be an empty string.", func: async () => "baz1", }), ];
> 
> const executor = await initializeAgentExecutorWithOptions(tools, model, { agentType: "zero-shot-react-description", });
> 
> console.log("Loaded agent.");
> 
> const input = `What is the value of foo?`;
> 
> console.log(`Executing with input "${input}"...`);
> 
> const result = await executor.call({ input });
> 
> console.log(`Got output ${result.output}`); };

Is there an answer for this as I too require something similar
