### ISSUE TITLE
TypeError: this.createTimeout is not a function

### ISSUE THREAD

**Issue by leason-wan** [langchain-ai/langchainjs#1310]
work on dev, not work on prod, i think the promblem is p-tetry: https://github.com/tim-kos/node-retry/issues/83

**Comment by leason-wan** [comment]
https://github.com/tim-kos/node-retry/pull/85
this is work for me

**Comment by jacoblee93** [comment]
What environment/setup are you using? Would love to be able to repro and fix this!

**Comment by leason-wan** [comment]
@jacoblee93 
parcel build with ts

**Comment by leason-wan** [comment]
i slove this problem with my repo which is frok: https://github.com/leason-wan/node-retry-l

**Comment by leason-wan** [comment]
> @jacoblee93 parcel build with ts

i need run in chrome extensions
