### ISSUE TITLE
GPT4All Support for langchain.js

### ISSUE THREAD

**Issue by timgerstel** [langchain-ai/langchainjs#1341]
As a developer of an TypeScript application, I would like support for a GPT4All model in the javascript version of LangChain.

**Comment by cborchert** [comment]
There's a discussion in this PR concerning this topic https://github.com/hwchase17/langchainjs/pull/1204

**Comment by jacoblee93** [comment]
Yes this would be awesome! I believe there's a community package linked in that PR, but otherwise it looks like they're starting to put some resources into it and it may be available soon :)

https://github.com/nomic-ai/gpt4all/tree/main/gpt4all-bindings/typescript
