### ISSUE TITLE
Agent: With capabilities to run actions in the front end

### ISSUE THREAD

**Issue by nesbtesh** [langchain-ai/langchainjs#1361]
Hello,

I have a question regarding the creation of an Agent with versatile capabilities. I'm interested in developing an Agent that can effectively utilize both backend and frontend tools. For instance, I would like the Agent to be able to retrieve the current client's available credit using backend functionality. However, when it comes to searching for products, I want the Agent to initiate a frontend action by displaying a search input for the search API. Because I want the search results to be viewed in the front end

I would appreciate any guidance or insights you can provide on this matter.

Thank you!

**Comment by cdiddy77** [comment]
I am curious why displaying search results on the front end requires you to do the query on the front end. Seems you could do the query on the backend and return the results to the FE for rendering?
