### ISSUE TITLE
SupabaseVectorStore - allow reading/writing other columns

### ISSUE THREAD

**Issue by dstoyanoff** [langchain-ai/langchainjs#1373]
Hello,
I've noticed that the reading of data from the SupabaseVector store only returns the page content and the metadata. Is there a possibility to return all fields that are returned by the function? I would like to be able to add more business-specific columns that follow general relational databases principles and not having to put them in the metadata object. I see that the document type extends from `Record<string, any>`, but the fields are then hard-cut on the reading side.

Thanks

**Comment by MaximeThoonsen** [comment]
hey @dstoyanoff ,

You can change the match_documents so that it return more information in the select like

```
select
    id,
    content,
    metadata,
    1 - (documents.embedding <=> query_embedding) as similarity
  from documents
  where metadata @> filter
  order by documents.embedding <=> query_embedding
  limit match_count;
  ```
  
You can do :
```
select
    id,
    content,
    metadata,
    YOURCOLUMN,
    1 - (documents.embedding <=> query_embedding) as similarity
  from documents
  where metadata @> filter
  order by documents.embedding <=> query_embedding
  limit match_count;
  ```
  
  I wrote also on how to extend it to add other [columns here](https://www.maximeai.com/blog/scale-your-embeddings-with-langchain)
  
 You can have a other exemple of one [sql query here](https://github.com/hwchase17/langchainjs/pull/1436/files)

**Comment by dstoyanoff** [comment]
Hello @MaximeThoonsen,
I did try that from the start, but this piece of code here constructs the document with just the content and the metadata, ignoring the rest of the response:
https://github.com/hwchase17/langchainjs/blob/0c9db115439be04e690efd788ba581cf39c848c7/langchain/src/vectorstores/supabase.ts#L108

**Comment by MaximeThoonsen** [comment]
hey @dstoyanoff ,

Yes, the easiest way is to extend the supabase class with your own and overwrite the `similaritySearchVectorWithScore` method with your own.

**Comment by cdiddy77** [comment]
@dstoyanoff where would you want the money xtra columns to go, if not the metadata? Would you append their text to the document text?

**Comment by dstoyanoff** [comment]
@cdiddy77, supabase is based on Postgres, which is a relational database. As such, I would like it to be able to add different columns in the database with their foreign keys, indexes and etc and this to be returned alongside with the document/metadata.

Giving you a recent example that I had. I have a table that has documents, which are already processed and have their vector written.

There is an option for the user to vote about a particular document. That means I need to have a counter and also (in another related table), to have a foreign key to the user id who voted. How would you do this?

**Comment by MaximeThoonsen** [comment]
Hey @dstoyanoff ,

Did you have a look at [this link](https://www.maximeai.com/blog/scale-your-embeddings-with-langchain) it gives you some example on how to extend the class.
Also my PR to use [typeorm in addition of supabase](https://github.com/hwchase17/langchainjs/pull/1436/files) has been merged. So maybe it will work with this new vectorstore. 

Anyway you need to create a new document class + extend the method from the vectorstore class to make it work like you want. 
(I may work on enabling the addition of columns in PG in the futur but not soon)
