### ISSUE TITLE
Request failed with status code 429

### ISSUE THREAD

**Issue by Vasile-Peste** [langchain-ai/langchainjs#1433]
Hello, I just copied the documentation examples and generated an OpenAI API key for the first time

```js
import "dotenv/config.js";
import { ChatOpenAI } from "langchain/chat_models/openai";
import { HumanChatMessage } from "langchain/schema";

export const run = async () => {
    const chat = new ChatOpenAI();
    console.log("Call");
    // Pass in a list of messages to `call` to start a conversation. In this simple example, we only pass in one message.
    const response = await chat.call([
        new HumanChatMessage(
            "What is a good name for a company that makes colorful socks?"
        ),
    ]);
    console.log("Response");
    console.log(response);
    // AIChatMessage { text: '\n\nRainbow Sox Co.' }
};

run();
```

I keep getting `Request failed with status code 429`

**Comment by jacoblee93** [comment]
That one means you're getting rate limited:

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429

Nobody else is using your key or anything like that right?

**Comment by Vasile-Peste** [comment]
> That one means you're getting rate limited:
> 
> https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429
> 
> Nobody else is using your key or anything like that right?

I just created it for the first time and never used it. Maybe under the hood this library makes more than one request and triggers the rate limit?

**Comment by jacoblee93** [comment]
There is a retry mechanism for certain failures (like rate limits), but it should backoff and not repeatedly trigger OpenAI's rate limits. 

Do you have other keys in use at the moment?

**Comment by lylest** [comment]
Facing same thing with newly created APIs
