### ISSUE TITLE
ChatOpenAI doesn't support custom cache providers

### ISSUE THREAD

**Issue by mohamedcherifmo** [langchain-ai/langchainjs#1482]
The following produces an error 
`
const accurateModel = new ChatOpenAI({
        modelName: "gpt-4",
        streaming,
        callbacks: [handler],
        cache:cache
      });
` 
type is not assignable to type boolean where as
`
const accurateModel = new **OpenAI**({
        streaming,
        callbacks: [handler],
        cache:cache
      });
`
works correctly

Both should allow a custom cache as input

**Comment by rodrigo-clickup** [comment]
Please fix this!!!

**Comment by mohamedcherifmo** [comment]
I did a quick check and seems to have been resolved...
