### ISSUE TITLE
Add Document to existing Index - RedisVectorStore

### ISSUE THREAD

**Issue by lopezpedres** [langchain-ai/langchainjs#1529]
Right now it's possible to create an Index with the given documents, by using `fromDocuments` but If I want to update the index by adding more documents it overwrites the Index with the most recent document. Currently, redisRearch does not have a command to update the index either. `FT.ALTER` allows you to add more attributes to the schema but not fields to the index. 
One solution could be to get all the documents from the index, add the new document and then create the index again, but I am not sure if this is the most efficient way to achieve it, especially if the index is going to be updating all the time. Any ideas on how to work around it?

**Comment by monkeytroy** [comment]
Yes, I am seeing the same thing and have not been able to figure out how to make it work. Seems terribly inefficient to have to recreate the index. I've been able to add docs using other vector stores but not Redis.

**Comment by adam101** [comment]
This issue has been fixed in version [0.0.136](https://github.com/hwchase17/langchainjs/releases/tag/0.0.136):

> Fix: Allow Redis addDocuments without overriding existing keys by @Haim763 in https://github.com/hwchase17/langchainjs/pull/1555
