### ISSUE TITLE
Remove Documents/Embeddings from Vector Store

### ISSUE THREAD

**Issue by naveensky** [langchain-ai/langchainjs#1536]
I am trying to use Postgres as a vector store for my embeddings. The docs are at https://js.langchain.com/docs/modules/indexes/vector_stores/integrations/typeorm

I am wondering if there is a way to remove embeddings/documents from the store which are no longer valid and should not be included in the similarity search.

**Comment by dkarlovi** [comment]
I do this with Opensearch one by deleting all OS index documents which are related to the document I'm embedding. I do it manually before ingesting the new one.

**Comment by borel** [comment]
looks like there is nothing ready to use directly in `TypeORMVectorStore` but it looks quite easy to do .

if i get some time , i will implement a deletion by metadata or something like that
