### ISSUE TITLE
QA tools used by agents perform worse than self-query retrievers. How can we improve it?

### ISSUE THREAD

**Issue by hiroshinishio** [langchain-ai/langchainjs#1538]
I am now using both agent and retriever. If my user has multiple tools enabled, the agent is called, and if only the Pine Cone Search tool is enabled, the retriever is called.

However, when the agent searches the same PDF, for example, the results are not good. Or, in some cases, the agent does not even answer the question. How can I improve this?

Probably the cause seems to be a difference in query. In the case of the agent, the query is a few words extracted from the input, while in the case of the retriever, the query is the whole conversation. The results are better with the latter.

Here is the source of the agent's QA tool.

```javascript
const qaTool = (
  model: ChatOpenAI | OpenAI,
  vectorStore: VectorStore,
  userLocale: string
) => {
  const localeObject = getLocaleObject(userLocale);
  const chain = VectorDBQAChain.fromLLM(model, vectorStore, {
    k: Number(process.env.PINECONE_TOP_K),
    returnSourceDocuments: false, // TODO: Should be true but it's not working with this error "Error: return values have multiple keys, `run` only supported when one key currently"
    // inputKey,
    // callbacks,
  });
  const tool = new ChainTool({
    name: localeObject.tools.qaTool.name,
    description: localeObject.tools.qaTool.description,
    chain,
    returnDirect: false, // Set true if you intend to use the agent as a router and just want to directly return the result of the VectorDBQAChain.
  });
  return tool;
};
```

**Comment by jacoblee93** [comment]
You can always use a DynamicTool and wrap a self-query retriever:

https://js.langchain.com/docs/modules/agents/tools/dynamic
