### ISSUE TITLE
Support for ChatPromptTemplate in MultiPromptChain

### ISSUE THREAD

**Issue by ps48** [langchain-ai/langchainjs#1558]
## Add ChatPromptTemplate as supported input for MultiPromptChain

MultiPromptChain implements a very useful mechanism of selecting a prompt based on user's question. Today's implementation is restricted to set of strings or PromptTemplates. This is pretty useful when working with regular LLMs chain and agents. 

It would be great to see this working with Chat/Conversation agents. This would need support for `ChatPromptTemplate` in the lines below: 

Chain input
https://github.com/hwchase17/langchainjs/blob/62d78dd79e207ae39f8a894a266bb96dc7728cd5/langchain/src/chains/router/multi_prompt.ts#L48

Chain implementation
https://github.com/hwchase17/langchainjs/blob/62d78dd79e207ae39f8a894a266bb96dc7728cd5/langchain/src/chains/router/multi_prompt.ts#L92-L113

**Comment by mauriciocirelli** [comment]
Hi!

Have you fond a workaround for this?
