### ISSUE TITLE
Extending the document class for SQL (move columns out of metadata)?

### ISSUE THREAD

**Issue by jacoblee93** [langchain-ai/langchainjs#1562]
Opening discussion here @MaximeThoonsen!

> Hey @jacoblee93,
>
> To finish this one, I see two decisions:

> 1 - what do we do with the Document class?

> we extend the Document class (my recommendation but I agree we need to agree with the python implem)
> we create a new EnrichedDocument class
> other option?
> I don't want to put everything into metadata for few reasons:

> It's a easier for dev to understand columns rather than property inside a JSON object
> it's easier to manipulate the data in columns than in a JSON
> it will be easier for dev to enforce indexes on columns
> SQL visualization tools work out of the box for columns but some of them won't work as fine for Json object

**Comment by jacoblee93** [comment]
Could we use like a `metadataMapping` function or something similar to map SQL fields to metadata fields and back? The actual interface in LangChain doesn't actually need to match up with what's stored in SQL.

My worry with adding extra fields to the base class would be reimplementing it for all the providers we have.

**Comment by MaximeThoonsen** [comment]
Hey @jacoblee93,
>Could we use like a metadataMapping function or something similar within the subclassed vector store to map SQL fields to metadata fields and back? The actual interface in LangChain presents a developer doesn't actually need to match up with what's stored in SQL.

I like this idea, it can work. My worry is that we would need to tranform it both ways it makes it a bit more complicated. 

>My worry with adding extra fields to the base class would be reimplementing it for all the providers we have, and not all of them would support it well.

If we add extra field and make them optionnal it shouldn't break anything right ?


Anyway if you prefer you suggestion (which makes sense 😂), I'll do a PR with this in mind
