### ISSUE TITLE
Allow caching/upserting of vectors

### ISSUE THREAD

**Issue by jacoblee93** [langchain-ai/langchainjs#1563]
@MaximeThoonsen opening this for the other issue:

> 2 - how do we introduce the upsert mechnism with the hash?

> we update the addVectors method (this PR)
> I create an upsertVectors method so we don't do any break change (new idea)
> What do you think?

> Thanks again for your help on this,

> Maxime

**Comment by jacoblee93** [comment]
It would just search on the hash in the Document or in the metadata right? 

I don't think all providers would support this well yet (not all even have metadata filtering at the moment) but for your TypeORM one I think it'd make sense to add an `upsert: true` flag in the options?

**Comment by MaximeThoonsen** [comment]
Hey @jacoblee93,

- Ok we can store the hash in the metadata
- we can add a upsert: true flag. Would you put it in the constructor of the class or at the method level or both ?

**Comment by jacoblee93** [comment]
This is rolled out to a few providers at the moment.
