### ISSUE TITLE
Opensearch store does not support object in metadata and fail silently

### ISSUE THREAD

**Issue by yeouchien** [langchain-ai/langchainjs#1589]
Opensearch bulk indexing is failing silently due to default index mapping

https://github.com/hwchase17/langchainjs/blob/61e89dbaec07b4b50a55efe0f74faec5b2e701fd/langchain/src/vectorstores/opensearch.ts#L177-L186

### Code to repro:
```
  const loader = new PDFLoader('/tmp/pdfloader.pdf');
  const docs = await loader.loadAndSplit(new RecursiveCharacterTextSplitter());
  await OpenSearchVectorStore.fromDocuments(docs, new OpenAIEmbeddings(), {
    client
  });
```
code above will create the index but unable to index the documents because of the metadata created from `RecursiveCharacterTextSplitter` 
`metadata: { source: '/tmp/pdfloader.pdf', pdf: [Object], loc: [Object] }` 

### Workaround for this issue:
delete the object in metadata
```
  docs.forEach((d) => {
    d.metadata.source = basename(d.metadata.source);
    delete d.metadata.pdf;
    delete d.metadata.loc;
  });
```

### Potential solution:
1. do not support object in metadata, like pinecone
https://github.com/hwchase17/langchainjs/blob/61e89dbaec07b4b50a55efe0f74faec5b2e701fd/langchain/src/vectorstores/pinecone.ts#L59
2. throw appropriate error so that client know what's wrong.
https://github.com/opensearch-project/opensearch-js/blob/main/guides/bulk.md#handling-errors

**Comment by raymondfeng** [comment]
Yes, we ran into the same issue with github document loader.
