### ISSUE TITLE
The "token" in handleLLMNewToken(token) is not the actual answer.

### ISSUE THREAD

**Issue by Eventidus** [langchain-ai/langchainjs#1606]
**Hello, I am using RetrievalQAChain. I found that the result obtained after calling chain.call() method is different from the token in handleLLMNewToken(token), and sometimes the token has nothing to do with the original question. This may not be the streaming response we want.**

![image](https://github.com/hwchase17/langchainjs/assets/49816387/4c28c146-bab4-4e80-b946-1df6aca097b4)

**Comment by Iambihua** [comment]
我用ConversationalRetrievalQAChain也是一样的结果！

![image](https://github.com/hwchase17/langchainjs/assets/49816387/20257eff-bef0-4335-b0ca-490dd9698504)

**Comment by Iambihua** [comment]
ConversationalRetrievalQAChain has the same issue!
![image](https://github.com/hwchase17/langchainjs/assets/49816387/e713c103-484d-4056-917d-6a66a67ed79d)

**Comment by josharsh** [comment]
@hwchase17 are we picking this up?

**Comment by ms-mousa** [comment]
Hey guys, 
I'm facing the same issue. When using this `handleLLMNewToken` callback on the chain I see the internal thought process of the chain as well not the output I would like to show to the user. I'm using this chain `ConversationalRetrievalQAChain` 

Is there a different callback method to use where we can stream only like the output results to the user?

**Comment by Eventidus** [comment]
In fact, when you change the type to "stuff", you will get the desired result. However, its response speed will be very slow. But if you change the type to "reduce" or "map-reduce", the response speed will be very fast, but the results may not meet expectations. The reduce or map-reduce mode may even return two different results! I think this is a problem that needs to be urgently addressed. @hwchase17 @ms-mousa @josharsh

**Comment by simon-lighthouse** [comment]
+1 for this issue

**Comment by FrankDaze** [comment]
I still see the same behavoir. If you use a chain, then the callback handleLLMNewToken has no effect. Even if you use a stuff chain:

```
const model = new OpenAI({
      openAIApiKey: process.env.OPENAI_KEY,
      verbose: true,
      modelName: "discolm6q",
      stream: true,
      maxTokens: 2048,
      top_p: 0.1,
      top_k: 2,
      stop: "</s>",
      configuration: {
        baseURL: process.env.BASE_API_URL,
      },
      callbackManager: {
        handleLLMNewToken(token) {
          console.log("token", token);
        },
      },
    });

const chain = new RetrievalQAChain({
      combineDocumentsChain: loadQAStuffChain(model, {prompt: QA_CHAIN_PROMPT}),
      retriever,
      inputKey: "question",
    });
    
    ```
