### ISSUE TITLE
Azure OpenAI call results in 400 error because best_of parameter is set in axios request

### ISSUE THREAD

**Issue by machupicchu27** [langchain-ai/langchainjs#1611]
When using an Azure **gpt-35-turbo** deployment, logprobs, best_of, and echo parameters are not supported. https://learn.microsoft.com/en-us/azure/cognitive-services/openai/reference

It looks like 
 
``` javascript   
   const model = new OpenAI({
      temperature: 0,
      azureOpenAIApiKey: this.configService.get('OPEN_AI.AZURE.API_KEY'),
      azureOpenAIApiInstanceName: this.configService.get(
        'OPEN_AI.AZURE.INSTANCE_NAME',
      ),
      azureOpenAIApiDeploymentName: this.configService.get(
        'OPEN_AI.AZURE.DEPLOYMENT_NAME',
      ),
      azureOpenAIApiVersion: this.configService.get('OPEN_AI.AZURE.VERSION'),
    });

   await model.call('Say this is a test')
```

sets the best_of parameter by default in the axios request body to the Azure REST API, causing it to fail with error 400. "logprobs, best_of and echo parameters are not available on gpt-35-turbo model. Please remove the parameter and try again. For more details, see https://go.microsoft.com/fwlink/?linkid=2227346."

**Comment by machupicchu27** [comment]
Temporary workaround: 

```javascript
    delete model.bestOf;
```
After initializing new OpenAI

**Comment by Eventidus** [comment]
#1371 Look here.
