### ISSUE TITLE
How to pass some custom variables values to Dynamic tool from executor 

### ISSUE THREAD

**Issue by ShashankSirmour** [langchain-ai/langchainjs#1614]
hi all, 
thanks for the great library, I am experimenting with this using custom DynamicTool but I am unable to figure out how to pass custom variables like id or request related meta info from the executor to DynamicTool

**Comment by borel** [comment]
a tool has a single text as input .
but you can play with DynamicStructuredTool ( https://js.langchain.com/docs/modules/agents/agents/action/structured_chat ) , if you are able to identify your variables in the prompt then you can extract them and do some action with it

**Comment by ShashankSirmour** [comment]
> a tool has a single text as input . but you can play with DynamicStructuredTool ( https://js.langchain.com/docs/modules/agents/agents/action/structured_chat ) , if you are able to identify your variables in the prompt then you can extract them and do some action with it

What if I want to pass some object, i am building express app and i wanted to pass req object from executor to tool based on sentiment and later inside tool i wanted to fetch user detail and run seprate model executor to get results
