### ISSUE TITLE
`handleLLMNewToken` called with empty tokens when using function calling

### ISSUE THREAD

**Issue by gramliu** [langchain-ai/langchainjs#1640]
When calling `ChatOpenAI.predictMessages` with an OpenAI function call specified, the `handleLLMNewToken` callback is repeatedly called with empty tokens. This is likely because when OpenAI pushes new chunks to the HTTP event-stream, the structure of the response data is slightly different.

For normal text responses, the schema of a `choice` follows:
```
{
  "delta": { "content": string },
  "index": number,
   "finish_reason: null
}
```

With function calling, however, it now looks like:
```
{
  "delta": {
    "function_call": {
       "name": string,
       "arguments": string
    }
  },
  "index": number,
  "finish_reason": null
}
```

Edit: This does seem to be the case: [see](https://github.com/hwchase17/langchainjs/blob/c538b228098ee96aed180a1b049cac3f56defb0d/langchain/src/chat_models/openai.ts#L406-L410)

**Comment by vladgolubev** [comment]
Here are some of the ideas:

## Single callback
```ts
callbacks: [
    {
      handleLLMNewFunctionCall(function_call: {name: string;args:string}) {
        /*
        function_call = {
          name: "xxx",
          args: 'yyy'
        }
         */
      },
    }
  ]
```

## Separate callbacks for function name and argument

```ts
callbacks: [
    {
      handleLLMNewFunctionCallName(function_call_name: string) {
        /*
        function_call_name = "xxx"
         */
      },
      handleLLMNewFunctionCallArgs(function_call_args: string) {
        /*
        function_call_args = "yyy"
         */
      }
    }
  ]
```

From my observations, looks like OpenAI always emits `function_name` in stream as a single distinct chunk. So probably second option makes more sense.

**Comment by vladgolubev** [comment]
Looks like a PR was submitted https://github.com/hwchase17/langchainjs/pull/1964
