### ISSUE TITLE
CustomPromptTemplate._getPromptType - error Not implemented

### ISSUE THREAD

**Issue by rossanodr** [langchain-ai/langchainjs#1654]
CustomPromptTemplate._getPromptType
- error Not implemented
Ways to reproduce:
 "langchain": "^0.0.95",
 and followed the exactly example: https://js.langchain.com/docs/modules/agents/agents/custom/custom_agent_chat
 It was working fine before. I just updated because of the new openAi models and then it started to happen

**Comment by rossanodr** [comment]
Works on  "langchain": "0.0.91",
But if I try to use gpt-4-0613, gpt-3.5-turbo-16k or gpt-3.5-turbo-0613 I get the error 
` Chain run errored with error: "Invalid stopping method: generate"
- error node_modules\langchain\dist\agents\agent.js (36:0) @ LLMSingleActionAgent.returnStoppedResponse
- error Invalid stopping method: generate`
const executor = new AgentExecutor({
      agent,
      tools,
      earlyStoppingMethod: "generate",
      maxIterations: 5,
      verbose: true,
    });
    
   I case I remove the earlyStoppingMethod the error is: `Got output Agent stopped due to max iterations.`

**Comment by RalissonMattias** [comment]
I have the same problem
