### ISSUE TITLE
Inconsistent arguments for CreatePromptArgs between agents

### ISSUE THREAD

**Issue by dmlazaro** [langchain-ai/langchainjs#1683]
I am currently working with the `openai-functions` agent and I'd like to specify a custom `systemMessage`, `humanMessage`, and `inputVariables` like I can with `chat-conversational-react-description`. However, the `openai-functions` agent only takes a `prefix` argument.

Would it be possible to make the prompt arguments more similar? It would make my use case a lot easier to implement.

**Comment by axrj** [comment]
+1
I was looking for a way to do this as well but seems it's not possible with the current functionality.
I can either make a zero shot agent with memory, and prompt but no openai-functions or an openai-functions agent with memory but no custom prompt.
Alternative is to provide a way to build an agent from a Chain which can take memory, llm, and prompt.

It would be great if this can be supported.

**Comment by axrj** [comment]
Just figured out that Agent constructors do accept Chain object so my concern is invalid.
