### ISSUE TITLE
Why does setting AZURE_OPENAI_API_KEY env variable preclude ever using OPENAI_API_KEY?

### ISSUE THREAD

**Issue by swiecki** [langchain-ai/langchainjs#1687]
Hi, I want to use my azure deployments for some LLMs and my openAI key for some others. However this isn't possible if I set the environment variable. I got around this by renaming the environment variable to something else and only passing it in manually when I want to use it, but this seems like an odd default?

**Comment by shanurrahman** [comment]
Faced the same issue yesterday +1

**Comment by danny-avila** [comment]
+1 This was a tricky one for me to debug and glad I'm not the only one
