### ISSUE TITLE
pdf-parse.d.ts not found when using PDFLoader

### ISSUE THREAD

**Issue by RitvikShandilya** [langchain-ai/langchainjs#1711]
Reproduction
When "npm run dev" is executed, I get an error saying node_modules/langchain/dist/document_loaders/fs/pdf.d.ts:1:22 - error TS6053: /node_modules/langchain/src/types/pdf-parse.d.ts' not found.

///

This error comes when I try to import { PDFLoader } from "langchain/document_loaders/fs/pdf";

tsconfig:
{
"compilerOptions": {
"module": "NodeNext",
"esModuleInterop": true,
"target": "es6",
"moduleResolution": "nodenext",
"sourceMap": true,
"outDir": "dist",
"resolveJsonModule": true,
"allowJs": true
},
"lib": ["es2015"]
}

Expected behavior
no error is expected as pdf-parse is already installed, similar issue with pdfjs-dist

package.json
{
"name": "server-chatgpt",
"version": "1.0.0",
"description": "",
"type": "module",
"main": "dist/app.js",
"scripts": {
"start": "tsc & node dist/app.js",
"dev": "tsc -w & nodemon -x 'node dist/app.js || touch dist/app.js'",
"dev2": "tsc -w & pm2 start dist/app.js --watch",
"log": "pm2 log",
"stop": "pm2 stop app",
"lint": "eslint . --ext .ts",
"test": "echo "Error: no test specified" && exit 1"
},
"author": "",
"license": "ISC",
"devDependencies": {
"@types/cors": "^2.8.13",
"@types/express": "^4.17.17",
"@typescript-eslint/eslint-plugin": "^5.59.6",
"@typescript-eslint/parser": "^5.59.6",
"eslint": "^8.41.0",
"nodemon": "^2.0.22",
"pm2": "^5.3.0",
"ts-node": "^10.9.1",
"typescript": "^5.0.4"
},
"dependencies": {
"@types/node": "^20.3.1",
"@types/pdf-parse": "^1.1.1",
"body-parser": "^1.20.2",
"chatgpt": "^5.2.4",
"chromadb": "^1.5.2",
"cors": "^2.8.5",
"dotenv": "^16.0.3",
"express": "^4.18.2",
"hnswlib-node": "^1.4.2",
"langchain": "^0.0.95",
"openai": "^3.2.1",
"pdfjs-dist": "^3.7.107",
"pg": "^8.11.0",
"typeorm": "^0.3.16",
"uuid": "^9.0.0"
}
}

**Comment by Huayu-Qin** [comment]
> I created `pdf-parse.d.ts` in my `types` folder:
> 
> ```ts
> declare module "pdf-parse/lib/pdf-parse.js" {
>   import pdf from "pdf-parse";
> 
>   export default pdf;
> }
> ```

Hey, where have you build it and solve it?
I still got error
```
../../../node_modules/langchain/dist/document_loaders/fs/buffer.d.ts:1:23 - error TS1452: 'resolution-mode' assertions are only supported when `moduleResolution` is `node16` or `nodenext`.

1 /// <reference types="node" resolution-mode="require"/>
                        ~~~~

../../../node_modules/langchain/dist/document_loaders/fs/buffer.d.ts:2:23 - error TS1452: 'resolution-mode' assertions are only supported when `moduleResolution` is `node16` or `nodenext`.

2 /// <reference types="node" resolution-mode="require"/>
                        ~~~~

../../../node_modules/langchain/dist/document_loaders/fs/pdf.d.ts:1:22 - error TS6053: File '/Users/huayuqin/repos/intreface.omnie.chatbot.backend/node_modules/langchain/src/types/pdf-parse.d.ts' not found.

1 /// <reference path="../../../src/types/pdf-parse.d.ts" />
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../../../node_modules/langchain/dist/document_loaders/fs/pdf.d.ts:2:23 - error TS1452: 'resolution-mode' assertions are only supported when `moduleResolution` is `node16` or `nodenext`.

2 /// <reference types="node" resolution-mode="require"/>
                        ~~~~

../../../node_modules/openai/core.d.ts:179:3 - error TS18028: Private identifiers are only available when targeting ECMAScript 2015 and higher.

179   #private;
      ~~~~~~~~


Found 5 errors in 3 files.

Errors  Files
     2  ../../../node_modules/langchain/dist/document_loaders/fs/buffer.d.ts:1
     2  ../../../node_modules/langchain/dist/document_loaders/fs/pdf.d.ts:1
     1  ../../../node_modules/openai/core.d.ts:179
```

**Comment by aar2dee2** [comment]
@Huayu-Qin
I was using a much earlier version of Langchain. What version are you on?

**Comment by Huayu-Qin** [comment]
@aar2dee2  I tried on 0.0.13x and updated to the latest version, both got error. Which version do you use?

**Comment by aar2dee2** [comment]
@Huayu-Qin 
I have langchain `^0.0.96` and pdf-parse `^1.1.1`

**Comment by Huayu-Qin** [comment]
@aar2dee2 right. Temporarily comment type annotation for this module and it works.
