### ISSUE TITLE
Zilliz in Langchain is unable to return data fields with @zilliz/milvus2-sdk-node@2.2.7+

### ISSUE THREAD

**Issue by yongyi520** [langchain-ai/langchainjs#1719]
I am currently using node client version:
"@zilliz/milvus2-sdk-node": "^2.2.18",

However, when I do the search function, it returns only the ids of the search result and not the field.

I double checked, the output_fields were sent in but somehow still nothing.

**Here is my sample code. Attached picture is the result.**
<img width="625" alt="Screenshot 2023-06-21 at 20 47 39" src="https://github.com/hwchase17/langchainjs/assets/10789851/b0d7cf0d-cce9-4c25-97b7-07e87b9319c5">

`export const searchZillizVectorStore = async (query: string) => {
  const client = await getZillizClient();
  const collectionName = "testHMO";
  const embeddings = new OpenAIEmbeddings();
  const queryVector = await embeddings.embedQuery(query)
  const searchResp = await client.search({
    collection_name: "testHMO",
    // collection_name: "test_collection",
    // expr: "word_count <= 11000",
    vectors: [queryVector],
    // vector: queryVector,
    search_params: {
      anns_field: "langchain_vector",
      topk: "2",
      metric_type: "L2",
      params: '{"ef":64}',
    },
    // vector_type: 101, // DataType.FloatVector,
  });
  console.log("searchResp", searchResp);
};`

**Result I got:**
- It only contains score and id but nothing else

<img width="795" alt="Screenshot 2023-06-21 at 19 30 14" src="https://github.com/hwchase17/langchainjs/assets/10789851/5e13945d-fcbc-4119-906f-a37117a0fa75">
- search promise query comes from the file:
/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/grpc/Data.js
<img width="1053" alt="Screenshot 2023-06-21 at 19 31 50" src="https://github.com/hwchase17/langchainjs/assets/10789851/4db301ea-3d28-4ae2-a04d-49b14cd63622">

Questions:
1. Have anyone encountered this issue?
2. Should I downgrade to lower version?

**Comment by disflyer** [comment]
same issue, have you find a way to resovle?
