### ISSUE TITLE
Make it possible to turn off follow-up input rephrasing 

### ISSUE THREAD

**Issue by jasan-s** [langchain-ai/langchainjs#1727]
When it works it works, but many times the rephrasing leads to failures e,g

> input_1_raw: what is the name of this game? 
> input_1_rephrased: what is the name game? 
> 
> output 1: The name of the game is life
> 
> input_2_raw: xxxxxxxxxxxxx 
> input_2_rephrased: what is the name game? 
> output 2: The name of the game is life

currently Im modifying `questionGeneratorTemplate`  but i feel this step should be optional. 

```
		const chain = ConversationalRetrievalQAChain.fromLLM(
			streamingModel,
			vectorStore.asRetriever(3),
			{
				memory,
				returnSourceDocuments: false,
				questionGeneratorChainOptions: {
					llm: nonStreamingModel,
					template: questionGeneratorTemplate,
				},
				qaChainOptions: {
					type: 'stuff',
					prompt,
				},
				verbose: true,
			}
		)
```
Anyone else seeing this issue?

**Comment by ashbuilds** [comment]
Im having a same issue, and would like to have an option to turn off rephrasing as well. 

<img width="2500" alt="Screenshot 2023-07-05 at 11 08 24" src="https://github.com/hwchase17/langchainjs/assets/2686288/442e4a27-0ecc-45c4-a6e9-5d509c5e6dd8">

**Comment by manuel-84** [comment]
i would  like to have this option and also to know in `initializeAgentExecutorWithOptions` how do you pass in custom `questionGeneratorChainOptions.template`
