### ISSUE TITLE
Error with multiple input variable prompt templates when using BufferMemory

### ISSUE THREAD

**Issue by borisivnc** [langchain-ai/langchainjs#1734]
Hi!
As I was trying to run a `ConversationalChain` using `BufferMemory`, it ran fine when using a prompt template with one input variable, but when trying to use more than one the call to the chain fails and returns the following error:

> Error: input values have 2 keys, you must specify an input key or pass only 1 key as input
>     at getInputValue (.../node_modules/langchain/dist/memory/base.cjs:21:11)
>     at BufferMemory.saveContext (.../node_project/node_modules/langchain/dist/memory/chat_memory.cjs:42:75)
>     at ConversationChain.call (.../node_project/node_modules/langchain/dist/chains/base.cjs:76:31)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    
As a reference, this is the code snippet I ran to encounter this issue:
https://pastebin.com/iQR2XK9Y

**Comment by danielwii** [comment]
same issue, im using `BufferWindowMemory` for now.
