### ISSUE TITLE
Support Drizzle ORM for Vector Stores

### ISSUE THREAD

**Issue by AprilNEA** [langchain-ai/langchainjs#1743]
I noticed that Prisma and TypeORM have been added to Vector Stores' integration support for ORM, and Drizzle is also a very popular TypeScript ORM. it is also Serverless friendly, which facilitates front-end deployments.

**Comment by AprilNEA** [comment]
Is there anyone who can give me some ideas on how I can try to do PR?

**Comment by danielsims** [comment]
I'd love to see this functionality added, it's exactly what I'm looking for at the moment. Would be looking to use it as an alternative for the Prisma vector store, however in api endpoints using the edge runtime.

**Comment by avanderbergh** [comment]
The creator of the `pgvector` postgres extension has already [added support for drizzle](https://github.com/pgvector/pgvector-node#drizzle-orm).

There still seems to be an issue with adding support for using **pgvector's** `vector(n)` data type to `drizzle-kit` so we can add the number of dimensions (1536) used by OpenAI embeddings.

There's an issue for that [here](https://github.com/drizzle-team/drizzle-kit-mirror/issues/115)

**Comment by avanderbergh** [comment]
The current workaround is to patch the `drizzle-kit` package to recognize the `vector` type.

We are waiting for the maintainers of `drizzle-kit` to open source it, so this can be added upstream.

**Comment by avanderbergh** [comment]
dosubot gone rogue?

**Comment by jacoblee93** [comment]
We would like to do this!

**Comment by medic-code** [comment]
@jacoblee93 i'd like to work on this. Gathering some thoughts based upon above and current ORM integrations. 

Any additional context would be most helpful - i'll open up an early PR once i've got my head round the tasks required/complexity.

**Comment by avanderbergh** [comment]
@medic-code 

Please check here for developments so far: https://github.com/drizzle-team/drizzle-kit-mirror/issues/115

I've patched the package for now...

**Comment by medic-code** [comment]
Sounds like it’s better to wait then, will circle back if this still isn’t resolved.

**Comment by jacoblee93** [comment]
Thank you for offering @medic-code! But yes the above sounds like it might be blocking 😕

**Comment by medic-code** [comment]
No worries, it allowed me to get more familiar with Drizzle which is no bad thing.

**Comment by smashah** [comment]
what blocker does `https://github.com/drizzle-team/drizzle-kit-mirror/issues/115` reference exactly? it's 404-ing.
