### ISSUE TITLE
[ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/text_splitter' is not defined by "exports"

### ISSUE THREAD

**Issue by ymansurozer** [langchain-ai/langchainjs#1759]
I am trying to use `RecursiveCharacterTextSplitter` and am getting this error whenever I try to create an instance of it:

```
[ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/text_splitter' is not defined by "exports" in C:\Repos\DocuChatv2\job-queue\node_modules\langchain\package.json
```

I've reviewed #185 where it is said Langchain now supports CJS but I am still getting this error.

My `tsconfig.json`:
```
{
    "compilerOptions": {
        "target": "ES2015",
        "module": "commonjs",
        "lib": ["es2018"],
        "outDir": "./dist",
        "rootDir": "./src",
        "moduleResolution": "node",
        "esModuleInterop": true,
        "resolveJsonModule": true,
        "sourceMap": true,
        "baseUrl": "./",
        "paths": {
            "@/*": ["src/*"]
        },
        "types": ["node", "cross-fetch"],
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true
    },
    "include": ["src/**/*"],
    "exclude": ["node_modules", "**/*.spec.ts"]
}
```

**Comment by jacoblee93** [comment]
Apologies for the late response - is this still an issue with the latest version of LangChain?

**Comment by jon-ressio** [comment]
I've got a different import but similar error about missing modules under /dist in langchain package.  langchain 0.0.104,  Next app:

```
Module not found: Package path ./dist/schema is not exported from package /code/my-app/node_modules/langchain (see exports field in /code/my-app/node_modules/langchain/package.json)
  5 | import { ChatOpenAI } from "langchain/chat_models/openai";
> 6 | import { HumanMessage, SystemMessage } from "langchain/dist/schema";
  8 | import { EstimateService } from "../contractorPortal/estimate/service";
  9 |
```

tsconfig:

```
{
    "compilerOptions": {
        "target": "ES6",
        "lib": ["dom", "dom.iterable", "esnext"],
        "types": ["node", "reflect-metadata"],
        "allowJs": true,
        "skipLibCheck": true,
        "strict": true,
        "forceConsistentCasingInFileNames": true,
        "noEmit": true,
        "esModuleInterop": true,
        "module": "esnext",
        "moduleResolution": "node",
        "resolveJsonModule": true,
        "isolatedModules": true,
        "downlevelIteration": true,
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "jsx": "preserve",
        "incremental": true,
        "noUncheckedIndexedAccess": true,
        "baseUrl": ".",
        "plugins": [
            {
                "name": "next"
            }
        ],
        "paths": {
            "@/*": ["./src/*"],
            "@/public/*": ["./public/*"]
        }
    },
    "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
    "exclude": ["node_modules", "cypress", "**/*.mock.ts"]
}
```

**Comment by jacoblee93** [comment]
> I've got a different import but similar error about missing modules under /dist in langchain package. langchain 0.0.104, Next app:
> 
> ```
> Module not found: Package path ./dist/schema is not exported from package /code/my-app/node_modules/langchain (see exports field in /code/my-app/node_modules/langchain/package.json)
>   5 | import { ChatOpenAI } from "langchain/chat_models/openai";
> > 6 | import { HumanMessage, SystemMessage } from "langchain/dist/schema";
>   8 | import { EstimateService } from "../contractorPortal/estimate/service";
>   9 |
> ```
> 
> tsconfig:
> 
> ```
> {
>     "compilerOptions": {
>         "target": "ES6",
>         "lib": ["dom", "dom.iterable", "esnext"],
>         "types": ["node", "reflect-metadata"],
>         "allowJs": true,
>         "skipLibCheck": true,
>         "strict": true,
>         "forceConsistentCasingInFileNames": true,
>         "noEmit": true,
>         "esModuleInterop": true,
>         "module": "esnext",
>         "moduleResolution": "node",
>         "resolveJsonModule": true,
>         "isolatedModules": true,
>         "downlevelIteration": true,
>         "experimentalDecorators": true,
>         "emitDecoratorMetadata": true,
>         "jsx": "preserve",
>         "incremental": true,
>         "noUncheckedIndexedAccess": true,
>         "baseUrl": ".",
>         "plugins": [
>             {
>                 "name": "next"
>             }
>         ],
>         "paths": {
>             "@/*": ["./src/*"],
>             "@/public/*": ["./public/*"]
>         }
>     },
>     "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
>     "exclude": ["node_modules", "cypress", "**/*.mock.ts"]
> }
> ```

For this one, import it as just `langchain/schema`.

**Comment by jon-ressio** [comment]
That fixed it, thanks for that.

FWIW, VS Code is not suggesting or finding the ChatOpenAI export at all, I have to add it by hand.  And VS Code only finds and suggests the Chat Messages from "langchain/dist/schema".

**Comment by jelling** [comment]
To summarize, VSCode is autocompleting the import like this:

```
import { HumanMessage, SystemMessage } from "langchain/dist/schema";
```

When it should be like this:
```
// note: no dist
import { HumanMessage, SystemMessage } from "langchain/schema"; 
```

**Comment by garrytrinder** [comment]
Thanks @jelling, just hit this issue and your fix solved it for me 👍

**Comment by jacoblee93** [comment]
Gotcha, will leave this open and try to figure out what's going on.
