### ISSUE TITLE
Agent with chat history

### ISSUE THREAD

**Issue by finom** [langchain-ai/langchainjs#1763]
I want my agent to know the history of the conversation and to make it extract actions from the context.

- Who played Neo in the Matrix?
- Keanu Reeves
- What's his last movie?
- [Serp Tool] 
- ...

I tried the following code:

```ts
history.push(
      ...messages.map((message) => {
        if (message.userType === ChatMessageUserType.HUMAN) {
          return new HumanChatMessage(message.content);
        } else if (message.userType === ChatMessageUserType.AI) {
          return new AIChatMessage(message.content);
        }

        throw new Error('Unknown message type');
      })
    );

    const executor = await initializeAgentExecutorWithOptions([new Calculator()], llm, {
      agentType: "zero-shot-react-description",
      verbose: true,
    });

    return (await executor.call(history)) as { text: string };
```

I have enabled Calculator only for now but langchain gives me the following error: 

> Chain run errored with error: "Missing value for input input"

If I do `executor.call({ input: history })` it doesn't seem to understand `This input is not clear and does not make sense as a question. Final Answer: N/A`. 

![image](https://github.com/hwchase17/langchainjs/assets/1082083/90dc0b10-3549-40b8-a976-ce53094f3fe8)

Obviously langchain don't support array of messages as an input. But what would be a workaround then? Build my own prompt from scratch for `input`? If yes, can you please help me to extract resulting prompt from the regular `llm.call(history)` so I can mimic Langchain behaviour? Would you recommend to switch to OpenAI function calling?

**Comment by anthonycoded** [comment]
I believe input should be a string. I ran into this issue twice. In my code I pass the history array in separate from the input. I hope this helps.

    const botResponse = await executor.call({
      input: input,
      chatHistory: chatHistory,
    });
