### ISSUE TITLE
Do we have a version of FinalStreamingStdOutCallbackHandler for Javascript?

### ISSUE THREAD

**Issue by RobertHH-IS** [langchain-ai/langchainjs#1775]
I am playing around with Vercel ai and chat repos.  Agents currently output the entire thought action stream.  Is there a callback handler similar to FinalStreamingStdOutCallbackHandler to avoid the thoughts going to front end.  returnIntermediateSteps set to false still streams the intermediate steps.

**Comment by tjhoo** [comment]
Yes, I'm looking [FinalStreamingStdOutCallbackHandler](https://python.langchain.com/docs/modules/agents/how_to/streaming_stdout_final_only) in LangChain JavaScript too.

**Comment by demattosanthony** [comment]
Looking for this as well. Even if the callbacks for for handling streaming responses in agents
