### ISSUE TITLE
ConversationalRetrievalQAChain + Streaming fails with Chat History

### ISSUE THREAD

**Issue by satpalsr** [langchain-ai/langchainjs#1781]
From this [doc](https://js.langchain.com/docs/modules/chains/index_related_chains/conversational_retrieval#externally-managed-memory)

This fails with streaming
```
const chain = ConversationalRetrievalQAChain.fromLLM(
        llm,
        vectorStore.asRetriever()
    );

chat_history = [] // This works     
chat_history="What is time? time is a precious resource." // This fails
chain.call({ question, chat_history: chat_history });
```

Gives error
```
Error in handler Handler, handleLLMNewToken: TypeError: The stream is closing or closed and cannot be written to
Error in handler Handler, handleLLMNewToken: TypeError: The stream is closing or closed and cannot be written to
Error in handler Handler, handleLLMNewToken: TypeError: The stream is closing or closed and cannot be written to
Error in handler Handler, handleLLMNewToken: TypeError: The stream is closing or closed and cannot be written to
```

**Comment by EmilioJD** [comment]
Can you provide a bit more context? Seems like the error is happening in your handleLLMNewToken function, could be useful to include your model declaration. 

I have ConversationalRetrievalQAChain working with streaming and memory but I had to pass the history in as type ChatMessageHistory() which consist of HumanChatMessage and AIChatMessage

**Comment by satpalsr** [comment]
Yeah I figured out that, from
https://github.com/hwchase17/langchainjs/issues/1607#issuecomment-1590971348
but responses are not good now.

**Comment by joaopcm** [comment]
If you share your implementation, we can help you better

**Comment by joaopcm** [comment]
take a look at this issue (and its PR): https://github.com/hwchase17/langchainjs/issues/1800

I've added an example to the docs which works pretty good.
