### ISSUE TITLE
Store the creation timestamp for each chat history message

### ISSUE THREAD

**Issue by joaopcm** [langchain-ai/langchainjs#1799]
When using `UpstashRedisChatMessageHistory` (or other chat history), it stores a list of all the chat history, including the type (`ai` or `human`) and the content, which is the message sent/answered. It would be really helpful if we started storing the timestamp too. This would allow customers to use the history (stored in any external database such as Upstash, Redis, DynamoDB, etc.) and read the exact timestamp a message was sent.

With a `created_at` field, we can render the entire chat history, including all the timestamps that represent when each message was sent.

**Comment by jacoblee93** [comment]
More generally perhaps a metadata field?

**Comment by joaopcm** [comment]
Actually, this is not needed since there are multiple other ways to keep track of the creation date. Closing this issue. Thanks!
