### ISSUE TITLE
Stream only the final answer when using an agent

### ISSUE THREAD

**Issue by dogfootruler-kr** [langchain-ai/langchainjs#1820]
I am using an agent and I would like to be able to stream only the final answer just like this [question ](https://github.com/hwchase17/langchain/issues/2483) for the python lib that was resolved by creating this specific [callback](https://github.com/hwchase17/langchain/pull/4630).

Is that also possible using the JS library?

Thank you very much!

**Comment by dogfootruler-kr** [comment]
I found my solution here https://js.langchain.com/docs/modules/chains/index_related_chains/conversational_retrieval#streaming

I'm closing this issue.

**Comment by rdroste** [comment]
@dogfootruler-kr I don't see an implementation of a callback with functionality similar to the [Python callback](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/callbacks/streaming_stdout_final_only.py) you linked under the link you provided as your solution. I believe that such a callback is missing in JS LangChain. Please consider re-opening the issue.

**Comment by dogfootruler-kr** [comment]
@rdroste @alexgitENI Indeed the callback is still missing and the link I shared did not work for me. I'll reopen this issue but I don't really care about it now. You can always make a PR to add this callback.

**Comment by Alexmhack** [comment]
is this implemented or anyone has a custom solution?
