### ISSUE TITLE
What are the parameters you can pass to `chain.call` to modify the original prompt sent to a model?

### ISSUE THREAD

**Issue by deemeetree** [langchain-ai/langchainjs#1841]
I'm using the example from the docs, running the following code:

```
       const vectorStore = await HNSWLib.fromDocuments(
		docs,
		new OpenAIEmbeddings({ stripNewLines: false })
	);

        const chain = VectorDBQAChain.fromLLM(model, vectorStore);

	const res = await chain.call({
		input_documents: docs,
		query:
			"What is this about? ",
	});

```

I understand that `chain.call` feeds the documents found in the vector store to the OpenAI prompt and adds something at the beginning to make the model answer the question. 

But how can I actually edit the original prompt sent and add a few statements to it?  For instance, what if I want to add some general context about all the documents that might be found? Or what if I don't want it to answer a question but to, say, challenge the user's input?

Couldn't find it in the documentation, maybe you can direct me to the right place or suggest which parameters / functions could be used to achieve that?

**Comment by brerdem** [comment]
I'm trying to do same thing

**Comment by deemeetree** [comment]
Ok, no answer from the community, so figured it out myself. 

First, you need to replace the deprecated `VectorDBQAChain` with the newer `RetrievalQAChain`, which basically does the same thing.

Then, when you initiate the chain, you need to add the `verbose: true` parameter to the options of the model like this:

```
const chain = RetrievalQAChain.fromLLM(model, vectorStore.asRetriever(), {
		verbose: true,
	});
```

Mind you, because `langchain.js` works badly for any node below version 16 you need node version 16+ for the `verbose` option to work, otherwise it throws an error on `Object.hasOwn` code. But once you upgrade to node 16 (use nvm to do that, so you can switch back and forth), then you'll be able to see what langchagin is actually sending to the model in the backend and what prompts it's using.

**Comment by deemeetree** [comment]
And, by the way, the prompt that is used is 

```
Use the following pieces of context to answer the question at the end. If you don't know the answer, just say that you don't know, don't try to make up an answer.

your_pieces_of_content

Question: your_question

Helpful answer: 
```

Now the question is if you can actually change the original prompt used above or not and how to do that.

For now, I found that one option is to retrieve the search results using

```
const results = await vectorStore.similaritySearch("meditation");
```

And then make a manual query to the model. But there must be a better way to do that. 

Anyone has an idea how?

**Comment by deemeetree** [comment]
Ok, found a solution to change the prompt sent to a model. This can be useful if you want to create your own prompts (e.g. not only answering questions, but coming up with ideas or translating the prompts to other languages) while maintaining the chain logic.

First, I had to look into 
`https://github.com/hwchase17/langchainjs/blob/53b6cb4fd9365e26b21c5e40ed2ddd8077562fdb/langchain/src/chains/question_answering/load.ts#L48` 
and 
`https://github.com/hwchase17/langchainjs/blob/53b6cb4fd9365e26b21c5e40ed2ddd8077562fdb/langchain/src/chains/chat_vector_db_chain.ts#L21` 
to understand what parameters can be passed to the `fromLLM` function of `RetrievalQAChain`. 

I found out that you can simply pass the `prompt` option when calling the model, which should contain the prompt function that modifies the original prompt. 

So I added the following variables to my script modifying the original prompt: 

```
    const template = `Use the following pieces of context to come up with an interesting response to the statement at the end. If you don't know what to say, just say that you don't know, don't try to make up an answer.

    {context}
    
    Statement: {question}
    Innovative Response:`;

	const prompt = new PromptTemplate({
		template: template,
		inputVariables: ["context", "question"],
	});

```

Then I added the following code to the `chain` call:

```
const chain = RetrievalQAChain.fromLLM(model, vectorStore.asRetriever(), {
		// returnSourceDocuments: true,
		// verbose: true,
		prompt: prompt,
	});
```

Now it is using my prompt instead of the default one.

**Comment by mattgardner70** [comment]
How do you pass the values of context and question in the above example to the prompt template that is passed into the QAChain? Do we just pass them to chain.call?

My code is structured a little differently.
`
    let documents = await vectorStore.similaritySearch(userSubmittedQuestion);
    let inputPrompt: StuffQAChainParams = {
        prompt: new PromptTemplate({
            inputVariables: ["chat_history", "question", "context"],
            template: "Say {chat_history} Question: {question} Context: {context}",
          })
    };
    const model = new OpenAI({ openAIApiKey: config.OPENAI_API_KEY, temperature: 0, maxTokens: 2000});
    const chain = loadQAStuffChain(model, inputPrompt);
    const response = await chain.call({ question: userSubmittedQuestion, input_documents: documents});`
