### ISSUE TITLE
feat: embedDocuments to support progress callback

### ISSUE THREAD

**Issue by glorat** [langchain-ai/langchainjs#1861]
https://github.com/hwchase17/langchainjs/blob/f4b146471f967faa95071337caaf22658e90346e/langchain/src/embeddings/base.ts#L16

Would be useful for Embeddings.embedDocuments to have a second optional argument `progress?: (p:number)=>void` to signal the proportion of documents whose embed results have arrived. This would then be used for UI reporting in case there are many documents that take time to progress so a progress bar can be displayed.

If a maintainer thinks this is a good idea, I can contribute a PR for this

**Comment by jacoblee93** [comment]
CC @ppramesi would this fit in with your changes?

**Comment by ppramesi** [comment]
Yeah I think it can fit the current embedding callback pull request. I can create something called handleEmbeddingProgress function or something like that in the callback handler/manager. @nfcampos thoughts on this?

**Comment by nfcampos** [comment]
How about a more generic `handleProgress({current: number, total: number}, ...)` which can be used now by embeddings and in future by some of the other run types?

**Comment by ppramesi** [comment]
You mean like adding handleProgress in callback handler/manager that can be called from other run types?

**Comment by nfcampos** [comment]
Yes I agree it should be a separate PR
