### ISSUE TITLE
How to custom llm in langchainjs?

### ISSUE THREAD

**Issue by xiaobaiha** [langchain-ai/langchainjs#1864]
compared to py version: https://python.langchain.com/docs/modules/model_io/models/llms/how_to/custom_llm

How can I custom llm in js version?

**Comment by jacoblee93** [comment]
We should definitely add docs for this!

**Comment by ansarizafar** [comment]
I also need this. Is there any update?

**Comment by jacoblee93** [comment]
The above is accurate @ansarizafar. Will leave this open until we have a guide ready but that should be enough to get started!

**Comment by itgoldman** [comment]
Here's my example. It's a little simple. It also demonstrates calling an API to retrieve answer.
```js
import { LLM } from 'langchain/llms/base'

export default class MyLLM extends LLM {

  constructor() {
    super({})
  }

  async _llmType() {
    return 'My LLM'
  }

  async _call(text) {

    const url = process.env.LLM_API_URL
    const data = {
      prompt: text,
      max_new_tokens: 250,
      temperature: 0.7,
    }

    const response = await fetch(url, {
      method: 'POST',
      body: JSON.stringify(data),
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json'
      }
    })

    const obj = await response.json()

    return obj['results'][0]['text']
  }

}
```
And usage:
```js
const llm = new MyLLM();
```

**Comment by aehlke** [comment]
Does this work well with other langchainjs features such as Tools?

**Comment by cken21** [comment]
Can it be used with streaming as well?

**Comment by jacoblee93** [comment]
We've added a guide for this:

https://js.langchain.com/docs/guides/extending_langchain

Thanks for the enthusiasm!

**Comment by dxLu** [comment]
> We've added a guide for this:
> 
> https://js.langchain.com/docs/guides/extending_langchain
> 
> Thanks for the enthusiasm!

how set the API_KEY and URL, could you show a case ?
