### ISSUE TITLE
VSCODE extensions program development, using LangChain will report an error, it is recommended that LangChain TS does not directly use the API provided in VSCODE, it may not work.

### ISSUE THREAD

**Issue by mqbojee** [langchain-ai/langchainjs#1884]
The error message is as follows:
1. Headers is not defined
2. Request is not defined
3. Fetch is not defined
4. stream.getReader() is not function

The following fix is recommended:
1. introduce the node-fetch dependency
```
npm install --save @types/node-fetch
```
2. import the following package in axios-fetch-adapter.js
```
import fetch, { Headers, Request } from 'node-fetch';
```
3. adjust the event-source-parse.ts method to
```
async function getBytes(stream, onChunk) {
    stream.on('data', (chunk) => {
        onChunk(chunk);
    });

    stream.on('end', () => {
        onChunk(new Uint8Array(), true);
    });
}
```

**Comment by jacoblee93** [comment]
What environment are you running? For Node, we only support 18+: https://github.com/hwchase17/langchainjs#supported-environments

**Comment by mqbojee** [comment]
The environment is NodeJS 18. It runs fine directly with NodeJS, but when I plug the code into the VSCODE plugin, the Headers, Request, Fetch, etc. in axios-fetch-adapter.js are reported as undefined. Have you guys ever encountered this? Have you encountered anything like this when running in the VSCODE plugin? Or what environment settings should be adjusted for VSCODE?

**Comment by mattorp** [comment]
This fixed it for me, thanks @mqbojee !

I also had to add the following to `src/extension.ts`

```ts
import { ReadableStream } from 'web-streams-polyfill'
global.ReadableStream = ReadableStream
```

This fixed `ReadableStream is not defined` when importing `ChatOpenAI`

```ts
import { ChatOpenAI } from 'langchain/chat_models'
```
