### ISSUE TITLE
Can't initialize a GoogleCustomSearch instance

### ISSUE THREAD

**Issue by sblbl** [langchain-ai/langchainjs#1886]
Hello! I'm trying to create an agent that retrieves information through the Google Search API. However, I'm not able to correctly initialize a GoogleCustomSearch instance and I didn't find any example in the docs. I'm developing in sveltekit, and my code is in a +server.js file in a subdirectory of api/.
The error I get is "Google API key not set. You can set it as "GOOGLE_API_KEY" in your environment variables." even if I have a variable for the API key. 

This is essentially how I initialize the custom search.
```
import { json } from '@sveltejs/kit'
import { OPENAI_KEY, GOOGLE_CSE_ID, GOOGLE_API_KEY } from '$env/static/private'
import { initializeAgentExecutorWithOptions } from 'langchain/agents'
import { GoogleCustomSearch } from 'langchain/tools'
import { OpenAI } from 'langchain/llms/openai'

// I console logged the API keys and they are correct

const tools = [
	new GoogleCustomSearch(GOOGLE_API_KEY, GOOGLE_CSE_ID)
]

const agent = await initializeAgentExecutorWithOptions(tools, model, {
    agentType: 'zero-shot-react-description',
    verbose: true,
})

const askGoogleSearch = async question => {
	results = await agent.searchQuery( question )
	return results
}
```

What I was trying to do is adapting the [gkamradt's](https://github.com/gkamradt/langchain-tutorials/blob/main/LangChain%20Cookbook%20Part%202%20-%20Use%20Cases.ipynb) code and make it work in the js version of Langchain.

Here is a brief sample of the python code.

```
# Helpers
import os
import json

from langchain.llms import OpenAI

# Agent imports
from langchain.agents import load_tools
from langchain.agents import initialize_agent

# Tool imports
from langchain.agents import Tool
from langchain.utilities import GoogleSearchAPIWrapper
from langchain.utilities import TextRequestsWrapper

GOOGLE_CSE_ID = os.getenv('GOOGLE_CSE_ID', 'api_key')
GOOGLE_API_KEY = os.getenv('GOOGLE_API_KEY', 'api_key')
llm = OpenAI(temperature=0, openai_api_key=openai_api_key)

search = GoogleSearchAPIWrapper(google_api_key=GOOGLE_API_KEY, google_cse_id=GOOGLE_CSE_ID)
requests = TextRequestsWrapper()

toolkit = [
    Tool(
        name = "Search",
        func=search.run,
        description="useful for when you need to search to answer questions about current events inside ilPost.it"
    ),
    Tool(
        name = "Requests",
        func=requests.get,
        description="Useful for when you to make a request to a URL"
    ),
]

agent = initialize_agent(toolkit, llm, agent="zero-shot-react-description", verbose=True, return_intermediate_steps=True)

response = agent({"input":"a_question"})
response['output']
```

I'm a new langchain user, so please be patient if I missed something 🥲. Thank you in advance

**Comment by brerdem** [comment]
What model are you using? Also you may want to use `call` method of executor not `searchQuery`

**Comment by sblbl** [comment]
Hello! I'm using gpt-4. I'll try the searchQuery method, but the error I'm getting ("Google API key not set. You can set it as "GOOGLE_API_KEY" in your environment variables.") is triggered when I set search = GoogleSearchAPIWrapper. I think Langchain isn't finding the API keys. 

Thank you!

**Comment by patnorris** [comment]
Hi @sblbl ,
this worked for me:
const tools = [new GoogleCustomSearch({apiKey: GOOGLE_API_KEY, googleCSEId: GOOGLE_CSE_ID})];
