### ISSUE TITLE
Use of private properties instead of protected

### ISSUE THREAD

**Issue by tiagoefreitas** [langchain-ai/langchainjs#1892]
Hi @nfcampos I was trying to extend PlanAndExecuteAgentExecutor to make my own modified version but its impossible because all the properties are private, so I had to copy everything.

In the python version they are not, so I recommend making them protected everywhere in langchainjs so we can extend as needed.

Or is there a good reason not to?

Thanks

**Comment by jacoblee93** [comment]
Feel free to open a PR changing that!
