### ISSUE TITLE
error TypeError: chatMessage._getType is not a function. node_modules/langchain/dist/chains/conversational_retrieval_chain.js:67:33

### ISSUE THREAD

**Issue by aristhinkmatch** [langchain-ai/langchainjs#1896]
I got this error from this function: ConversationalRetrievalQAChain.fromLLM

**Comment by iPanchalShubham** [comment]
Could you provide additional context about how you're using the "ConversationalRetrievalQAChain.fromLLM" function? Understanding the flow of your code and the context in which this function is called will greatly help in diagnosing and resolving the issue.
