### ISSUE TITLE
Passing a new systemMessage to the agentArgs seems to break the execution agent.

### ISSUE THREAD

**Issue by jrcapicua** [langchain-ai/langchainjs#1919]
Passing a new systemMessage to the agentArgs seems to break the execution agent.
I am not sure if this is the correct way to do this but I have not found examples in the documentation.
How can I overwrite only the system message (DEFAULT_PREFIX) when creating an agent executor of type "chat-conversational-react-description"?
I tried passing it only a systemMessage inside agentArgs for the initializeAgentExecutorWithOptions options but that causes the agent to stop working correctly.
I am using the js/ts version.

<img width="941" alt="Captura de pantalla 2023-07-10 a la(s) 16 11 01" src="https://github.com/hwchase17/langchainjs/assets/46796968/b21df22c-b59b-47aa-b811-4d63db7e2baa">

**Comment by jacoblee93** [comment]
This looks correct and should result in an agent with a system message equivalent to the default system message - can you share your full code and say exactly what the change in behavior is?

Note that agents can be a bit inherently unreliable. You may also want to turn the temperature of the LLM down to 0 if it isn't already, or check out the functions model agent: https://js.langchain.com/docs/modules/agents/agents/action/openai
