### ISSUE TITLE
Create VectorStore from embeddings

### ISSUE THREAD

**Issue by satpalsr** [langchain-ai/langchainjs#1924]
We can create vectorStore from embeddings, but what if I already created embedding & then want to create vectorStore from it?
```
const vectorStore = await Chroma.fromDocuments(docs, new OpenAIEmbeddings(), {
  collectionName: "a-test-collection",
});
```

I want to break this code into two steps:
1. Create embeddings & save it at some place
2. Use those embeddings to create vectorStore

**Comment by satpalsr** [comment]
yeah I checked out source code and implemented.
But I tried this [example from langchain docs](https://js.langchain.com/docs/modules/indexes/vector_stores/integrations/chroma#usage-index-and-query-documents)

I get `Error: Chroma getOrCreateCollection error: Error: TypeError: fetch failed` for 
```
const vectorStore = await Chroma.fromDocuments(docs, new OpenAIEmbeddings(), {
  collectionName: "a-test-collection",
});
```

**Comment by jacoblee93** [comment]
> yeah I checked out source code and implemented. But I tried this [example from langchain docs](https://js.langchain.com/docs/modules/indexes/vector_stores/integrations/chroma#usage-index-and-query-documents)
> 
> I get `Error: Chroma getOrCreateCollection error: Error: TypeError: fetch failed` for
> 
> ```
> const vectorStore = await Chroma.fromDocuments(docs, new OpenAIEmbeddings(), {
>   collectionName: "a-test-collection",
> });
> ```

What version of Chroma are you using?

**Comment by satpalsr** [comment]
"langchain": "^0.0.96",
"chromadb": "^1.5.3",

**Comment by jacoblee93** [comment]
Maybe try updating LangChain to latest? And can you double check the url and port you're running Chroma on?

You can pass a url in directly as an option: https://github.com/hwchase17/langchainjs/blob/a900b209392e6791bc8dc00bc0ec76d8221d0908/langchain/src/vectorstores/chroma.ts#L51

**Comment by ddanielcruz** [comment]
I'm having the same issue using Chroma latest version. If it helps, I'm running Chroma with docker-compose, using its [example docker-compose file](https://github.com/chroma-core/chroma/blob/main/docker-compose.server.example.yml).
