### ISSUE TITLE
How do I set axios forward proxy?

### ISSUE THREAD

**Issue by Cayincc** [langchain-ai/langchainjs#1925]
```javascript
const llm = new ChatOpenAI(
  {
    streaming: true,
    openAIApiKey: this.configService.get<string>('OPENAI_API_KEY', ''),
    temperature: 0.7,
    timeout: 20000,
    maxRetries: 0,
  },
  {
    baseOptions: {
      proxy: {
        protocol: 'http',
        host: '172.31.160.1',
        port: 7890,
      },
    },
  },
);
```
```log
[llm/error] [1:chain:ConversationChain > 2:llm:ChatOpenAI] [12.30s] LLM run errored with error: "Network Error"
[chain/error] [1:chain:ConversationChain] [12.31s] Chain run errored with error: "Network Error"
```
#### That is not working, I'm sure my proxy is working. below code working fine.
```javascript
axios.default
      .request({
        method: 'POST',
        url: 'https://api.openai.com/v1/chat/completions',
        proxy: {
          protocol: 'http',
          host: '172.31.160.1',
          port: 7890,
        },
        headers: {
          'Content-Type': 'application/json',
          'User-Agent': 'OpenAI/NodeJS/3.3.0',
          Authorization:
            'Bearer ' + this.configService.get<string>('OPENAI_API_KEY', ''),
        },
        data: {
          model: 'gpt-3.5-turbo',
          temperature: 0.7,
          top_p: 1,
          frequency_penalty: 0,
          presence_penalty: 0,
          n: 1,
          stream: true,
          messages: [
            {
              role: 'system',
              content:
                'You're a therapist who helps people with mental health issues.',
            },
            { role: 'user', content: 'hi' },
          ],
        },
      })
      .then((res: axios.AxiosResponse) => {
        this.logger.debug(res.status);
        let str = '';
        for (const data of res.data.split('\n\n')) {
          try {
            const json_str = data.replace('data: ', '');
            if (json_str.length > 0) {
              const obj = JSON.parse(json_str);
              if (obj.hasOwnProperty('choices')) {
                if (obj.choices[0].finish_reason === 'stop') {
                  break;
                }
                str += obj.choices[0].delta.content;
              }
            }
          } catch (error) {
            this.logger.error(error.message, error);
          }
        }
        return str;
      })
      .catch((err: axios.AxiosError) => {
        this.logger.error(err.message, err);
        return err.message;
      });
```

#### Version
```
chatbot@0.0.1 /
├── @nestjs/cli@10.1.7
├── @nestjs/common@10.0.5
├── @nestjs/config@3.0.0
├── @nestjs/core@10.0.5
├── @nestjs/devtools-integration@0.1.5
├── @nestjs/platform-express@10.0.5
├── @nestjs/platform-socket.io@10.0.5
├── @nestjs/schematics@10.0.1
├── @nestjs/testing@10.0.5
├── @nestjs/websockets@10.0.5
├── @socket.io/redis-adapter@8.2.1
├── @types/express@4.17.17
├── @types/jest@29.5.3
├── @types/node@20.4.1
├── @types/supertest@2.0.12
├── @typescript-eslint/eslint-plugin@5.62.0
├── @typescript-eslint/parser@5.62.0
├── eslint-config-prettier@8.8.0
├── eslint-plugin-prettier@4.2.1
├── eslint@8.44.0
├── https-proxy-agent@7.0.1
├── i@0.3.7
├── jest@29.6.1
├── langchain@0.0.106
├── npm@9.8.0
├── prettier@2.8.8
├── redis@4.6.7
├── reflect-metadata@0.1.13
├── rxjs@7.8.1
├── source-map-support@0.5.21
├── supertest@6.3.3
├── ts-jest@29.1.1
├── ts-loader@9.4.4
├── ts-node@10.9.1
├── tsconfig-paths@4.2.0
└── typescript@5.1.6
```

**Comment by Cayincc** [comment]
![1689297674773](https://github.com/hwchase17/langchainjs/assets/28941664/6fd70cb8-7ed1-4fd0-bc36-4ca7ca881c0d)
clientConfig is undefined

**Comment by Mrxyy** [comment]
export function getOpenAi() {
  return new OpenAI(
    {
      modelName: modelName,
      openAIApiKey: openAIApiKey,
      temperature: 0,
    },
    {
      basePath: basePath,
    },
  );
}

**Comment by Cayincc** [comment]
> export function getOpenAi() { return new OpenAI( { modelName: modelName, openAIApiKey: openAIApiKey, temperature: 0, }, { basePath: basePath, }, ); }

Thank your answer. I want to set forward proxy, not reverse proxy.

**Comment by patst** [comment]
I have the same issue. 

It is working fine, when disabling the streaming and passing a httpsAgent inside the `baseOptions` configuration (somehow what is "explained" here: https://github.com/hwchase17/langchainjs/issues/739#issuecomment-1537163517 )

With streaming enabled the custom implementation using `fetch` inside of langchain seems to be used (https://github.com/hwchase17/langchainjs/blob/main/langchain/src/util/axios-fetch-adapter.js) which ignores proxy settings.

Would be great so see a streaming example which allows to use a forward proxy.

**Comment by cnshsliu** [comment]
> I have the same issue.
> 
> It is working fine, when disabling the streaming and passing a httpsAgent inside the `baseOptions` configuration (somehow what is "explained" here: [#739 (comment)](https://github.com/hwchase17/langchainjs/issues/739#issuecomment-1537163517) )
> 
> With streaming enabled the custom implementation using `fetch` inside of langchain seems to be used (https://github.com/hwchase17/langchainjs/blob/main/langchain/src/util/axios-fetch-adapter.js) which ignores proxy settings.
> 
> Would be great so see a streaming example which allows to use a forward proxy.

I have the same issue. 

I have two files "tst-normal.ts" and "tst-stream.ts".     In an environment which I could access OpenAI API directly. both programs run ok. however, in another network in which I have to connect to OpenAI API via a forward proxy. only "ts-node tst-normal.ts" works, while "ts-node tst-stream.ts" failed, stuck in middle.

## ts-stream.ts
```
import { ChatOpenAI } from "langchain/chat_models/openai";
import { HumanMessage } from "langchain/schema";

(async () => {
  const chat = new ChatOpenAI({
    maxTokens: 25,
    streaming: true,
  });

  const response = await chat.call([new HumanMessage("Tell me a joke.")], {
    callbacks: [
      {
        handleLLMNewToken(token: string) {
          console.log({ token });
        },
      },
    ],
  });

  console.log(response);
})();
```

## tst-normal.ts
```
import { ChatOpenAI } from "langchain/chat_models/openai";
import { HumanMessage } from "langchain/schema";

(async () => {
  const chat = new ChatOpenAI({
    maxTokens: 25,
  });

  const response = await chat.call([new HumanMessage("Tell me a joke.")]);

  console.log(response);
})();
```

Like @patst says, would be great to see how to make streaming behind a proxy works, thanks in advance.

**Comment by lamoglia** [comment]
Same here.

When working from behind a proxy, I get  a `ConnectTimeoutError` when calling `TokenTextSplitter` `createDocuments` method.

I dug in and it boils down to the `fetch` call to download the model encoding from an external url (such as `https://tiktoken.pages.dev/js/gpt2.json`)

It seems to ignore my proxy settings (`http_proxy` env var)

**Comment by lamoglia** [comment]
As I needed a quick workaround, I managed to do it changing the [tiktokenk.ts](https://github.com/langchain-ai/langchainjs/blob/main/langchain/src/util/tiktoken.ts) file. 

Instead of using `AsyncCaller` to fetch the encoding file (as it is relies on the `fetch` function from the [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) - with no support to proxying), I've replaced it with the `node-fetch` `fetch` call, in which I can set `HttpsProxyAgent` and get my request trough the proxy.

I've lost the retry logic but at least now I can move forward.

**Comment by yzqzy** [comment]
> ```js
> const llm = new ChatOpenAI(
>   {
>     streaming: true,
>     openAIApiKey: this.configService.get<string>('OPENAI_API_KEY', ''),
>     temperature: 0.7,
>     timeout: 20000,
>     maxRetries: 0,
>   },
>   {
>     baseOptions: {
>       proxy: {
>         protocol: 'http',
>         host: '172.31.160.1',
>         port: 7890,
>       },
>     },
>   },
> );
> ```
> 
> ```
> [llm/error] [1:chain:ConversationChain > 2:llm:ChatOpenAI] [12.30s] LLM run errored with error: "Network Error"
> [chain/error] [1:chain:ConversationChain] [12.31s] Chain run errored with error: "Network Error"
> ```
> 
> #### That is not working, I'm sure my proxy is working. below code working fine.
> ```js
> axios.default
>       .request({
>         method: 'POST',
>         url: 'https://api.openai.com/v1/chat/completions',
>         proxy: {
>           protocol: 'http',
>           host: '172.31.160.1',
>           port: 7890,
>         },
>         headers: {
>           'Content-Type': 'application/json',
>           'User-Agent': 'OpenAI/NodeJS/3.3.0',
>           Authorization:
>             'Bearer ' + this.configService.get<string>('OPENAI_API_KEY', ''),
>         },
>         data: {
>           model: 'gpt-3.5-turbo',
>           temperature: 0.7,
>           top_p: 1,
>           frequency_penalty: 0,
>           presence_penalty: 0,
>           n: 1,
>           stream: true,
>           messages: [
>             {
>               role: 'system',
>               content:
>                 'You're a therapist who helps people with mental health issues.',
>             },
>             { role: 'user', content: 'hi' },
>           ],
>         },
>       })
>       .then((res: axios.AxiosResponse) => {
>         this.logger.debug(res.status);
>         let str = '';
>         for (const data of res.data.split('\n\n')) {
>           try {
>             const json_str = data.replace('data: ', '');
>             if (json_str.length > 0) {
>               const obj = JSON.parse(json_str);
>               if (obj.hasOwnProperty('choices')) {
>                 if (obj.choices[0].finish_reason === 'stop') {
>                   break;
>                 }
>                 str += obj.choices[0].delta.content;
>               }
>             }
>           } catch (error) {
>             this.logger.error(error.message, error);
>           }
>         }
>         return str;
>       })
>       .catch((err: axios.AxiosError) => {
>         this.logger.error(err.message, err);
>         return err.message;
>       });
> ```
> 
> #### Version
> ```
> chatbot@0.0.1 /
> ├── @nestjs/cli@10.1.7
> ├── @nestjs/common@10.0.5
> ├── @nestjs/config@3.0.0
> ├── @nestjs/core@10.0.5
> ├── @nestjs/devtools-integration@0.1.5
> ├── @nestjs/platform-express@10.0.5
> ├── @nestjs/platform-socket.io@10.0.5
> ├── @nestjs/schematics@10.0.1
> ├── @nestjs/testing@10.0.5
> ├── @nestjs/websockets@10.0.5
> ├── @socket.io/redis-adapter@8.2.1
> ├── @types/express@4.17.17
> ├── @types/jest@29.5.3
> ├── @types/node@20.4.1
> ├── @types/supertest@2.0.12
> ├── @typescript-eslint/eslint-plugin@5.62.0
> ├── @typescript-eslint/parser@5.62.0
> ├── eslint-config-prettier@8.8.0
> ├── eslint-plugin-prettier@4.2.1
> ├── eslint@8.44.0
> ├── https-proxy-agent@7.0.1
> ├── i@0.3.7
> ├── jest@29.6.1
> ├── langchain@0.0.106
> ├── npm@9.8.0
> ├── prettier@2.8.8
> ├── redis@4.6.7
> ├── reflect-metadata@0.1.13
> ├── rxjs@7.8.1
> ├── source-map-support@0.5.21
> ├── supertest@6.3.3
> ├── ts-jest@29.1.1
> ├── ts-loader@9.4.4
> ├── ts-node@10.9.1
> ├── tsconfig-paths@4.2.0
> └── typescript@5.1.6
> ```

[https://www.npmjs.com/package/proxy-agent](https://www.npmjs.com/package/proxy-agent)

```
import { ProxyAgent } from 'proxy-agent';

const model = new ChatOpenAI(
  {
    streaming: true,
  },
  {
    httpAgent: new ProxyAgent(),
  },
);
```
