### ISSUE TITLE
SupabaseVectoreStore Error: Error searching for documents: 57014 canceling statement due to statement timeout null

### ISSUE THREAD

**Issue by DanielhCarranza** [langchain-ai/langchainjs#1935]
I did all the steps from how to integrate SupbaseVectorStore, I uploaded a big amount of vectors 100k+, but now I'm getting a timeout problem.

```
/.../node_modules/langchain/dist/vectorstores/supabase.cjs:93
            throw new Error(`Error searching for documents: ${error.code} ${error.message} ${error.details}`);
                  ^

Error: Error searching for documents: 57014 canceling statement due to statement timeout null
    at SupabaseVectorStore.similaritySearchVectorWithScore (/home/danielhcarranza/projects/webapps/eliza-chat/node_modules/langchain/dist/vectorstores/supabase.cjs:93:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SupabaseVectorStore.similaritySearch (/home/danielhcarranza/projects/webapps/eliza-chat/node_modules/langchain/dist/vectorstores/base.cjs:55:25)
    at main (/home/danielhcarranza/projects/webapps/eliza-chat/scripts/similar_patients.ts:255:21)
```

I use this function to initialized the vectore store:
```
const client = createClient(url, supabaseKey)
  const vectorStore = await SupabaseVectorStore.fromExistingIndex(
    new OpenAIEmbeddings(),
    {
      client,
      tableName: 'documents',
      queryName: 'match_documents',
    }
 ```
 
 I'm using langchainjs 0.0.106

**Comment by jacoblee93** [comment]
Can you share the entire code? Just want to rule out a potential very high `k` value and/or a complex filter.

**Comment by Sharvin26** [comment]
Hello I face the same issue on version "0.0.166". This is latest version as per npm registry ( https://www.npmjs.com/package/langchain )

My code and sql is similar to what @DanielhCarranza has mentioned.

**Comment by Jakisundays** [comment]
Im having the same issue

**Comment by Jakisundays** [comment]
Hey there,

I've figured out what's going on. It seems that the PostgreSQL `statement_timeout` is set too short for searching through a large number of documents. To address this, I ran the following query in the Supabase SQL editor:

```sql
ALTER ROLE anon
SET statement_timeout = '60s';

NOTIFY pgrst,
'reload config';
```

### More info
https://supabase.com/blog/postgrest-11-1-release

**Comment by jacoblee93** [comment]
Good catch! Should we add it to the setup instructions?

**Comment by Jakisundays** [comment]
Absolutely, we should add it to the setup instructions. However, it's important to clarify that the code is specifically for a Supabase vector store without row-level security, which enables anonymous users to modify the data. This distinction will help users implement it correctly. Thank you for considering this addition!
