### ISSUE TITLE
OpenAIEmbeddings() does not handle embedding long inputs on fromDocuments()

### ISSUE THREAD

**Issue by yongyi520** [langchain-ai/langchainjs#1963]
Is there any existing solution to do openai's long inputs like python's version below?

https://github.com/openai/openai-cookbook/blob/main/examples/Embedding_long_inputs.ipynb

I ran into this issue when the input document text length is over 200k in characters and seems like there's no javascript implementation of it

**Comment by kerkkoh** [comment]
OAI Embeddings API can only take in X many tokens (nb. `tokens != characters`).

In this case, the best way would be for you to use [TextSplitter](https://js.langchain.com/docs/modules/indexes/text_splitters/). See the examples on that page, and under it the examples for more specific types of splitters, like splitting based on the length of characters or the length of maximum tokens, such as the maximum token amount that you can feed into the OAI Embeddings API.

TextSplitters will then create several documents (i.e. pieces of text) that you can embed separately. You'll get several embeddings back as a result for each piece of the document embedded. You can add overlap to the documents in the TextSplitter parameters, which may help with recognizing these embeddings as being from the same document if you insert them into a vector store as separate documents.

If you want a single embedding vector for the entire document, you can do the average trick that the end of the notebook does. That portion doesn't use any specific LC functions AFAIK, so you should be rather easily able to find JS/TS implementations of those numpy functions.

**Comment by yongyi520** [comment]
@kerkkoh thank you for the reply

My implementation code does in fact have text splitters in them. None of the parsed documents have more than 1k tokens in it

**The issue:**
1. Issue is even with text splitters, openai.js will embed all the text-split documents into 1 big text to get embedding
Below is the openai.js source code:
<img width="872" alt="Screenshot 2023-07-16 at 09 31 11" src="https://github.com/hwchase17/langchainjs/assets/10789851/f394282b-e4e5-4c33-850c-c1cf43c83591">

Test input for openai.js embedDocument function:
1. Download the already text split document with the text splitter: https://lexy.b-cdn.net/testing/pagedoc.json
2. Run this code:
const readJSONTextFile = async (fileName: string) => {
      const publicFolder = getPublicFolder();
      const filePath = `${publicFolder}/${fileName}`;
      const data = await fs.promises.readFile(filePath, "utf8");
      const jsonData = JSON.parse(data);
      return jsonData;
    };
    pageDocs = await readJSONTextFile("pagedoc.json")
    const embedding = new OpenAIEmbeddings()
    embedding.embedDocuments(pageDocs)
 
<img width="480" alt="Screenshot 2023-07-16 at 09 38 24" src="https://github.com/hwchase17/langchainjs/assets/10789851/b34b7bfa-a40a-4c6a-9f4f-2a383a2e573c">
