### ISSUE TITLE
Agents and tools that work with document chunks and not with string / chat inputs?

### ISSUE THREAD

**Issue by deemeetree** [langchain-ai/langchainjs#1965]
Most of the agents and tools I see in Langchain doc work with simple string or chat inputs. 

However, what if I want to make an agent or a tool that would take a set of documents as input, process it, and only then send it to an LLM model?

For instance, I want to propose another method of reducing dimensionality of a text document before it gets sent to the summarization function. And I don't want to use `map_reduce` or `refine`, but, rather, an external service that would extract the most relevant parts of this text for me and then feed them to the model. 

Are there any agents and tools that work like that? What would be the best way to integrate it into Langchain?

So far, I only see Summarization and AnalyzeDocument chains, but they seem to be fully integrated into core modules and not offered as external tools / agents that would need an API key to function.

**Comment by jacoblee93** [comment]
Interesting - yeah I think creating your own subclass of `AnalyzeDocument` chain would be the closest way to do it at the moment. 

I could also see a case for expanding that chain to accept an array of [document transformers](https://js.langchain.com/docs/modules/indexes/document_transformers/) that operate on the input documents? And then the "external service" would just be an instance of a document transformer.

**Comment by kerkkoh** [comment]
You can always make a new `DynamicTool` (or a structured variant of this if you want the LMM to be able to give it other kinds of input than just a string) for your agent to use, with a function that fetches the documents (based on the inputs), processes them (in your case with an external tool or API or whatever it is), and gives them to the LMM back in a string format? I'm just spitballing here, and am not sure if this answers your question that well.
