### ISSUE TITLE
Make calculateMaxTokens respect OpenAI Functions

### ISSUE THREAD

**Issue by vladholubiev** [langchain-ai/langchainjs#1991]
Right now, `import {calculateMaxTokens} from 'langchain/base_language';` does not count functions in tokens consumption which leads to tokens usage overflow.

> Under the hood, functions are injected into the system message in a syntax the model has been trained on. This means functions count against the model’s context limit and are billed as input tokens. 

Some reference implementation could be borrowed from here: https://community.openai.com/t/how-to-calculate-the-tokens-when-using-function-call/266573/19

**Comment by vladholubiev** [comment]
Yes, this is still relevant.

**Comment by vladholubiev** [comment]
Yes, this is still relevant.

**Comment by jacoblee93** [comment]
Sorry for the delay! I think this was added a while back and should now be accounted for here:

https://github.com/langchain-ai/langchainjs/blob/main/libs/langchain-openai/src/chat_models.ts#L625
