### ISSUE TITLE
Add Support for Raycast AI API

### ISSUE THREAD

**Issue by Alireza29675** [langchain-ai/langchainjs#2016]
I propose adding support for the Raycast LLM API to the langchain JavaScript package so we can use langchain agents within the Raycast environment. Raycast AI API includes a function named `AI.ask(prompt)` that generates a completion.

For more information you may check: https://developers.raycast.com/api-reference/ai

@nfcampos Is it acceptable to have such integration in langchainjs?

**Comment by jacoblee93** [comment]
Would be great and we'd welcome a PR!

**Comment by Alireza29675** [comment]
For sure! @jacoblee93 How can I assign the issue to myself as suggested in contribution guideline?

**Comment by jacoblee93** [comment]
Assigned! Thank you

**Comment by Alireza29675** [comment]
@jacoblee93 This is ready for your review!:)
