### ISSUE TITLE
Token usage for OpenAI is not supported in streaming mode

### ISSUE THREAD

**Issue by CWXDEV** [langchain-ai/langchainjs#2024]
Heya,
I'm having some issues getting the Token usage, i found an old thread saying to use the `handleLLMEnd` callback and i should get an object called `llmOutput` in the but im getting undefined all the time, any ideas what im missing?

im using `OpenAI` llm with the `ConversationalRetrievalQAChain` and doing:

```
response = await chain.call({question, chat_history, [ handleLLMEnd(x) { console.log(x)};

//log:
// { generations: [ [ [Object] ] ], llmOutput: undefined }
```

is there a way to get the output on the call?

**Comment by jacoblee93** [comment]
This is unfortunately not currently supported for streaming requests natively by OpenAI: 
https://community.openai.com/t/how-to-determine-the-token-usage-for-a-session-when-using-stream-true/188089

I think it's something we could manually add - will keep this open.

**Comment by yhmjSky** [comment]
You can calculate the token usage of prompt in handleLLMStart,
and the token usage of result in handleLLMEnd
```typescript
   async handleLLMStart(llm, prompts) {
         console.log({ promptToken: await new ChatOpenAI({}).getNumTokens(prompts[0])+5 });
         //  if you are using the ChatPromptTemplate in combineDocumentsChain， it is prompts[0])+2
   },
   async handleLLMEnd(output: LLMResult) {
         // console.log(`Token usage: ${JSON.stringify(output.llmOutput?.tokenUsage)}`); //Only works in non-streaming 
         const resText = output.generations[0][0].text
         const completionTokens = await aChain.qaModel.getNumTokens(resText)
         console.log({completionTokens});
   }
```

**Comment by benedictbihl** [comment]
Would be happy to take a look at this. Feel free to assign it to me.

**Comment by CWXDEV** [comment]
I have not seen any features being added for this, personally would think this would be handy to have also,
But I have not been keeping up to date so if someone does see this and it's now in, please close it.

**Comment by jacoblee93** [comment]
This was added for `ChatOpenAI`, not yet for standard text completion models though.

**Comment by Penggeor** [comment]
@jacoblee93  Is it also not supported in JSON mode?
