### ISSUE TITLE
message._getType is not a function

### ISSUE THREAD

**Issue by jonstelly** [langchain-ai/langchainjs#2033]
I'm getting this error trying to use chat history similar to #1661 or #1573 but I am using the langchain message types.  I first tried creating an array of the messages (constructed correctly) and passing the array to ChatMessageHistory constructor, then tried the code below calling `history.addAIChatMessage(...)` which looks like it's creating instancesof the HumanMessage and AIMessage as expected/required.

The original error was slim on details.  I was able to get a stack trace running against a local build of langchain (this is v0.0.114 or git sha d7832fb78b4698f5e7c99c0697b0fcc9ada55bf2).  I'm trying to debug this a bit more but in case I don't make any progress or someone knows what my problem is...  I'm roughly doing:

EDIT: I just tested this trying to only create an empty BufferMemory instance and not passing any chat history or messages to it and I get the same error.

```
    const history = new ChatMessageHistory();
    for (const message of messages) {
      if (message.type == AIMessageType.AI) await history.addAIChatMessage(message.content);
      else await history.addUserMessage(message.content);
    }
    initializeAgentExecutorWithOptions([new WebBrowser(), new Calculator()], new ChatOpenAI(...), {
      agentType: "chat-conversational-react-description",
      memory: new BufferMemory({
            memoryKey: "chat_history",
            chatHistory: history,
          })
    });
```

```
- error TypeError: message._getType is not a function
    at eval (../langchainjs/langchain/dist/chat_models/openai.js:298:55)
    at Array.map (<anonymous>)
    at ChatOpenAI._generate (../langchainjs/langchain/dist/chat_models/openai.js:297:41)
    at eval (../langchainjs/langchain/dist/chat_models/base.js:59:86)
    at Array.map (<anonymous>)
    at ChatOpenAI.generate (../langchainjs/langchain/dist/chat_models/base.js:59:59)
    at async LLMChain._call (../langchainjs/langchain/dist/chains/llm_chain.js:123:33)
    at async LLMChain.call (../langchainjs/langchain/dist/chains/base.js:98:28)
    at async LLMChain.predict (../langchainjs/langchain/dist/chains/llm_chain.js:142:24)
    at async ChatConversationalAgent._plan (../langchainjs/langchain/dist/agents/agent.js:208:24)
    at async AgentExecutor._call (../langchainjs/langchain/dist/agents/executor.js:99:28)
    at async AgentExecutor.call (../langchainjs/langchain/dist/chains/base.js:98:28)
    at async eval (./src/app/ai/actions.ts:53:22)
303 |         const params = this.invocationParams(options);
304 |         const messagesMapped = messages.map((message) => ({
> 305 |             role: messageTypeToOpenAIRole(message._getType()),
      |                                                  ^
306 |             content: message.content,
307 |             name: message.name,
308 |             function_call: message.additional_kwargs    
```

**Comment by jonstelly** [comment]
Found the problem.  I had to look into the `initializeAgentExecutorWithOptions(...)` function.  The docs for that function mentioned that a memory buffer will be created for "chat-conversational-react-description" if the caller doesn't provide one.  I noticed in there the BufferMemory has inputKey, outputKey and retunMessages: true set.  Above, I was just setting memoryKey and the chatHistory.  If I set the other properties on BufferMemory's options then everything works.

Going to leave this open for a bit for visibility, feels like an area that could use some documentation or validation on the buffer if provided?

```
      memory: history
        ? new BufferMemory({
            returnMessages: true,
            memoryKey: "chat_history",
            inputKey: "input",
            outputKey: "output",
            chatHistory: history,
          })
        : undefined,
```

**Comment by jacoblee93** [comment]
Yes, the `returnMessages` thing gets people - a lot of the chat models use prompts that inject messages directly into the prompt, necessitating `returnMessages: true`.

We have it here: https://js.langchain.com/docs/modules/memory/integrations/buffer_memory_chat

Do you have ideas on how we can surface this better?

**Comment by jon-ressio** [comment]
From my limited understanding of why it's needed, just a couple thoughts:

1. It seems like it's invalid to pass a BufferMemory without `returnMessages: true` to initializeAgentExecutorWithOptions for "chat-conversational-react-description" agentType.  Would it be possible/reasonable to do some input validation in initializeAgentExecutorWithOptions?  I see the no-instanceof eslint rule but something logically like:
```
    case "chat-conversational-react-description": {
      const { agentArgs, memory, tags, ...rest } = options;
      if (memory && memory instanceof BufferMemory && !memory.returnMessages) {
        throw new Error(
          "BufferMemory must have returnMessages set to true to support chat-conversational-react-description"
        );
      }
```
2. For documentation, maybe a bit about the importance/reasoning?
> The key thing to notice is that setting returnMessages: true makes the memory return a list of chat messages instead of a string.  This is required to support generating the JSON format passed to the underlying model

or whatever better description could go there.  I saw that line but I don't think I understood the significance of what I was reading and for whatever reason I didn't connect the dots between the error and that line in the docs.
