### ISSUE TITLE
Retain links when extracting text using PDFLoader

### ISSUE THREAD

**Issue by ahm750** [langchain-ai/langchainjs#2064]
Langchain version: 0.0.105

I'm using PDFLoader to embed PDF documents using OpenAI, and I've noticed that the extracted documents do not retain the hyperlinks that were present in the files.

Is there a way to retain them? I couldn't find it in the docs or the PDFLoader class.

For example, a text containing a hyperlink could be extracted like this: "My favorite search engine is [Duck Duck Go] (https://duckduckgo.com)."

**Comment by Myoungs** [comment]
I wanna know too

**Comment by tejasborse23** [comment]
I want to know the same
