### ISSUE TITLE
How to use custom template for ConversationChain, in the style of llama-2

### ISSUE THREAD

**Issue by itgoldman** [langchain-ai/langchainjs#2097]
I understand that current default template is something like:
```
You are an AI assistant bla bla

Current conversation
{history}
Human: {input}
AI assistant: 
```

However I would like to know how to implement it to use something like this:
```
[INST] <<SYS>>
System_Message_Here
<</SYS>>
User_Msg_1 [/INST] Asst_Msg_1 [INST] User_Msg_2 [/INST] Asst_Msg_2 [INST] User_Msg_3 [/INST]
```
Example is from https://huggingface.co/TheBloke/Llama-2-13B-chat-GPTQ/discussions/5#64b8395b8c12f0008b7fa282

**Comment by rhamnett** [comment]
Hi. Did you figure this out?
