### ISSUE TITLE
Adding finish_reason in the response 

### ISSUE THREAD

**Issue by maxpaleo** [langchain-ai/langchainjs#2099]
Hi guys, would it be possible to add the finish_reason returned from the OpenAI api in the response? 
It was added to the Python repository recently: [Python](https://github.com/langchain-ai/langchain/issues/2702)

It's quite an important value to get in the response, as it states if a response was completed in full or not.

**Comment by sarthak212** [comment]
I think it's availabe in llm but not in chat model can it be possible to add finish_reason in chatModel generation response.

**Comment by baloodevil** [comment]
Can someone provide an example of how to get `GenerationInfo` which holds the `finish_reason`?  I thought it would be part of `ChainValues`, but apparently not.  I am using something like...

```javascript
  const model = new OpenAI({...});
  const chain = new LLMChain({ llm: model, prompt: promptTemplate });
  const response: ChainValues = await chain.call({ mytext, prompt });
```

I know this is a closed issue and probably not a great place for this question.  But I've tried using Discord but no one has responded with the correct answer and it is really close to what this issue addresses.
