### ISSUE TITLE
JS/TS vs python comparsion page

### ISSUE THREAD

**Issue by aDingil** [langchain-ai/langchainjs#2111]
Hey,

thx for your awesome awesome work.
Is it possible to generate some sort of comparison between the two implementations.
It´s very hard (in the beginning) to assess this.

**Comment by aDingil** [comment]
Also which implementation has a large importance to you

**Comment by jacoblee93** [comment]
Yes would love to have this!

At a high level we want all the major abstractions and modules to be in both versions. We expect individual integrations to vary and be more language specific.

**Comment by niron1** [comment]
The JS version is way less maintained than its python counterpart. I've produced a list of the tools provided in either version, and the python version's list is almost double in size:

JS version tools:

`IFTTTWebhook
aiplugin
aws_lambda
aws_sfn
base
bingserpapi
brave_search
calculator
chain
convert_to_openai
dadjokeapi
dataforseo_api_search
dynamic
fs
google_custom_search
index
json
requests
searxng_search
serpapi
serper
sql
vectorstore
webbrowser
wikipedia_query_run
zapier
`

Python version tools:

`amadeus
arxiv
azure_cognitive_services
bing_search
brave_search
dataforseo_api_search
ddg_search
file_management
github
gmail
golden_query
google_places
google_search
google_serper
graphql
human
interaction
jira
json
metaphor_search
multion
nuclia
office365
openapi
openweathermap
playwright
powerbi
pubmed
python
requests
scenexplain
searx_search
shell
sleep
spark_sql
sql_database
steamship_image_generation
vectorstore
wikipedia
wolfram_alpha
youtube
zapier
`

**Comment by niron1** [comment]
JS version document loaders:
`apify_dataset
azure_blob_storage_container
azure_blob_storage_file
buffer
cheerio
college_confidential
confluence
csv
directory
docx
epub
figma
gitbook
github
hn
imsdb
json
notion
notionapi
notiondb
pdf
playwright
puppeteer
s3
serpapi
sonix_audio
sort_xyz_blockchain
srt
text
unstructured
`

Python version document loaders:
`acreom
airbyte_json
airtable
apify_dataset
arxiv
async_html
azlyrics
azure_blob_storage_container
azure_blob_storage_file
base
bibtex
bigquery
bilibili
blackboard
blockchain
brave_search
browserless
chatgpt
college_confidential
concurrent
confluence
conllu
csv_loader
cube_semantic
datadog_logs
dataframe
diffbot
directory
discord
docugami
dropbox
duckdb_loader
email
embaas
epub
etherscan
evernote
excel
facebook_chat
fauna
figma
file_system
gcs_directory
gcs_file
generic
geodataframe
git
gitbook
github
googledrive
gutenberg
helpers
hn
html
html_bs
hugging_face_dataset
ifixit
image
image_captions
imsdb
iugu
joplin
json_loader
larksuite
markdown
mastodon
max_compute
mediawikidump
merge
mhtml
modern_treasury
news
notebook
notion
notiondb
nuclia
obs_directory
obs_file
obsidian
odt
onedrive
onedrive_file
open_city_data
org_mode
pdf
powerpoint
psychic
pyspark_dataframe
python
readthedocs
recursive_url_loader
reddit
roam
rocksetdb
rss
rst
rtf
s3_directory
s3_file
schema
sitemap
slack_directory
snowflake_loader
spreedly
srt
stripe
telegram
tencent_cos_directory
tencent_cos_file
text
tomarkdown
toml
trello
tsv
twitter
unstructured
url
url_playwright
url_selenium
weather
web_base
whatsapp_chat
wikipedia
word_document
xml
xorbits
youtube
youtube_audio
`

**Comment by aDingil** [comment]
It would be very useful, maybe i will create it myself
