### ISSUE TITLE
Incorrect number of document lines returned when slicing a document

### ISSUE THREAD

**Issue by Woodii1998** [langchain-ai/langchainjs#2131]
langchain/text_splitter's RecursiveCharacterTextSplitter class shows the wrong number of document lines in metadata.loc after splitting documents with splitDocuments function if chunkOverlap is not 0.

I wrote a demo to reproduce the issue:
[demo](https://github.com/Woodii1998/langchainjs-example)

Run the demo via `npm run split`

<img width="2445" alt="image" src="https://github.com/hwchase17/langchainjs/assets/33593572/86b41030-ee47-42e5-a489-693ea7a5b0bc">

The result shows that the text is in lines 508-515 of the document, but the actual text is in lines 453-460 of the document.

<img width="2606" alt="image" src="https://github.com/hwchase17/langchainjs/assets/33593572/28b95d2d-acb4-4491-9868-21c3acd03b13">

Is this a bug or is my understanding of this part of the functionality wrong

**Comment by tonisives** [comment]
https://github.com/langchain-ai/langchainjs/pull/1977

**Comment by Woodii1998** [comment]
> @Woodii1998 Should be fix on Langchain 0.0.161, can you confirm ?

I've verified that 0.0.161 has fixed the problem perfectly, thanks guys!
