### ISSUE TITLE
Faiss - merge multiple vectors

### ISSUE THREAD

**Issue by gregorym** [langchain-ai/langchainjs#2136]
I am trying to merge multiple faiss vectors together using langchain js. This is supported on the Python library but the same API isn't available in node.

Reference: https://api.python.langchain.com/en/latest/_modules/langchain/vectorstores/faiss.html#FAISS.merge_from

**Comment by jacoblee93** [comment]
@ewfian would this be something that could be added?

**Comment by ewfian** [comment]
Thanks to @neebdev for adding support for mergeFrom in faiss-node side, and the new version [v0.3.0](https://github.com/ewfian/faiss-node/releases/tag/v0.3.0) has been released.
