### ISSUE TITLE
Prisma vectorStorage addModels not working with id column type uuid 

### ISSUE THREAD

**Issue by icelic** [langchain-ai/langchainjs#2160]
Hi,

I have table called Article with id being UUID type. When I try to insert models I get the following error:

```
Raw query failed. Code: `42883`. Message: `db error: ERROR: operator does not exist: uuid = text
```

Caused by this here https://github.com/hwchase17/langchainjs/blob/1c1274d/langchain/src/vectorstores/prisma.ts#L276C1-L276C1

I think we need to always cast id field to text via ::text so that the comparison works.

```typescript
const vectorStore = PrismaVectorStore.withModel<Article>(prisma).create(new OpenAIEmbeddings(), {
  prisma: Prisma,
  tableName: 'article',
  vectorColumnName: 'vector',
  columns: {
    id: PrismaVectorStore.IdColumn,
    content: PrismaVectorStore.ContentColumn,
  },
});
```

I don't see a way to bypass this without fixing the source code.

I am using "langchain": "^0.0.122"  and "prisma": "^5.1.1",

**Comment by jacoblee93** [comment]
Would appreciate a PR!
