### ISSUE TITLE
ConversationalRetrievalChain doesn't return score with sources

### ISSUE THREAD

**Issue by sdellama** [langchain-ai/langchainjs#2191]
When Retriever is calling `_getRelevantDocuments` by default the `vectorStore.similaritySearch`  is invoked. 
The score values will be filtered out from the result docs.

`    async _getRelevantDocuments(query, runManager) {
        if (this.searchType === "mmr") {
            if (typeof this.vectorStore.maxMarginalRelevanceSearch !== "function") {
                [...]
            }
            return this.vectorStore.maxMarginalRelevanceSearch(query, {
                k: this.k,
                filter: this.filter,
                ...this.searchKwargs,
            }, runManager?.getChild("vectorstore"));
        }
        return this.vectorStore.similaritySearch(query, this.k, this.filter, runManager?.getChild("vectorstore"));
    }` 

`    async similaritySearch(query, k = 4, filter = undefined, _callbacks = undefined // implement passing to embedQuery later
    ) {
        const results = await this.similaritySearchVectorWithScore(await this.embeddings.embedQuery(query), k, filter);
        return results.map((result) => result[0]);
    }`

A way to call `similaritySearchVectorWithScore` through the Retriever is needed (a flag like maxMarginalRelevanceSearch is doing?) -> see https://github.com/hwchase17/langchainjs/blob/main/langchain/src/vectorstores/base.ts 

same of Python version see here-> https://github.com/langchain-ai/langchain/issues/5067

**Comment by sdellama** [comment]
can assign to me

**Comment by jacoblee93** [comment]
See

**Comment by prasoons075** [comment]
Can we also integrate the code so that we can use for the FAISS vector store as well or any other vector stores
