### ISSUE TITLE
Failed to calculate number of tokens, falling back to approximate count

### ISSUE THREAD

**Issue by john930d** [langchain-ai/langchainjs#2198]
Hi guys, I wanted to ask you does anyone know where is the problem with this because Im getting an error on my Express Js backend: (Failed to calculate number of tokens, falling back to approximate count) after trying to make a request to open ai by using langchain and sql database connection. On the request I can see that there is a property with max_tokens: 256, is there a problem with the api key or pricing plan or anything related to the database size?

The version of langchain library that Im using is "langchain": "0.0.110",

**Comment by john930d** [comment]
> _Answer generated by a 🤖_
> 
> ## Answer
> Hi there,
> 
> The error "Failed to calculate number of tokens, falling back to approximate count" could be due to the combination of your database structure and the question being too large for the model to handle. This is determined in the `verifyNumberOfTokens` method in the `SqlDatabaseChain` class.
> 
> In the `verifyNumberOfTokens` method, the total number of tokens is calculated using the `calculateMaxTokens` function. This function takes the string that is sent to the model (which includes the input text, the prompt template, and the table info) and the model name as parameters. If the calculated maximum number of tokens is less than the maximum number of tokens that the model can handle (`llm.maxTokens`), an error is thrown.
> 
> Here is the relevant code:
> 
> ```ts
> private async verifyNumberOfTokens(
>     inputText: string,
>     tableinfo: string
>   ): Promise<void> {
>     // We verify it only for OpenAI for the moment
>     if (this.llm._llmType() !== "openai") {
>       return;
>     }
>     const llm = this.llm as OpenAI;
>     const promptTemplate = this.prompt.template;
>     const stringWeSend = `${inputText}${promptTemplate}${tableinfo}`;
> 
>     const maxToken = await calculateMaxTokens({
>       prompt: stringWeSend,
>       // Cast here to allow for other models that may not fit the union
>       modelName: llm.modelName as TiktokenModel,
>     });
> 
>     if (maxToken < llm.maxTokens) {
>       throw new Error(`The combination of the database structure and your question is too big for the model ${
>         llm.modelName
>       } which can compute only a max tokens of ${getModelContextSize(
>         llm.modelName
>       )}.
>       We suggest you to use the includeTables parameters when creating the SqlDatabase object to select only a subset of the tables. You can also use a model which can handle more tokens.`);
>     }
>   }
> }
> ```
> 
> The error message suggests using the `includeTables` parameter when creating the `SqlDatabase` object to select only a subset of the tables, or using a model that can handle more tokens.
> 
> In the context shared, the `calculateMaxTokens` function in the `count_tokens.ts` file tries to calculate the number of tokens using the `encodingForModel` function. If it fails, it falls back to an approximate calculation by dividing the length of the prompt by 4. This could be another reason for the error. If the approximate calculation is not accurate, it could result in a number of tokens that exceeds the model's maximum token limit.
> 
> In the new context shared, the `OpenAI` class in the `openai.ts` file has a `maxTokens` property that is set to 256 by default. This property is used in the `invocationParams` method to set the `max_tokens` parameter for the OpenAI API request. If the `maxTokens` property is set to a value that is less than the number of tokens in the input string, the OpenAI API will return an error. You can try increasing the `maxTokens` property or reducing the size of the input string to resolve the error.
> 
> As for the changes made in the LangChain library after version 0.0.110, I wasn't able to find any specific changes that could potentially resolve this error. However, it's always a good idea to update to the latest version of the library, which is currently 0.0.124, as it may contain other improvements or bug fixes that could help.
> 
> I hope this helps! Let me know if you have any other questions.
> 
> ## Sources
> * [langchain/src/chains/sql_db/sql_db_chain.ts](https://github.com/hwchase17/langchainjs/blob/-/langchain/src/chains/sql_db/sql_db_chain.ts)
> * [langchain/src/base_language/count_tokens.ts](https://github.com/hwchase17/langchainjs/blob/-/langchain/src/base_language/count_tokens.ts)
> * [langchain/src/llms/openai.ts](https://github.com/hwchase17/langchainjs/blob/-/langchain/src/llms/openai.ts)
> 
> This response is meant to be useful, save you time, and share context. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.

I tried to make a request by using a simple database strucutre also including just 1 table with 6 rows and it is taking so much time to get a response from the open ai using langchain and sql database chain, Im not very sure if there is the problem with the pricing plan because Im confused why even if I have a simple database it is taking so much time to get a response.

**Comment by jacoblee93** [comment]
Can you paste your code? Shouldn't be seeing that with a base config and OpenAI

**Comment by john930d** [comment]
> Can you paste your code? Shouldn't be seeing that with a base config and OpenAI
@jacoblee93 Here is the code that Im using,
import { OpenAI } from "langchain/llms/openai";
import { SqlDatabase } from "langchain/sql_db";
import { SqlDatabaseChain } from "langchain/chains/sql_db";
import { DataSource } from "typeorm";

const langchainController = async () => {
  const datasource = new DataSource({
    type: "postgres",
    url: "my db url",
    logging: false,
    synchronize: true,
    extra: {
      ssl: {
        rejectUnauthorized: false,
      },
    },
  });

  const db = await SqlDatabase.fromDataSourceParams({
    appDataSource: datasource,
  });

  const chain = new SqlDatabaseChain({
    llm: new OpenAI({
      temperature: 0,
      openAIApiKey: "my api key",
    }),
    database: db,
  });

  const res = await chain.run("How many products are available now?");
  console.log(res);
};
export { langchainController };

**Comment by john930d** [comment]
> > Can you paste your code? Shouldn't be seeing that with a base config and OpenAI
> > @jacoblee93 Here is the code that Im using, the problem here is that after doing a request to the open ai, it is taking so much time to return a response (around 2 minutes) and at the end a correct answer is returned but there is showing me the error (Failed to calculate number of tokens, falling back to approximate count).
> 
> Currently there are 2 problems:
> 
> 1. time to get the response from open ai
> 2. the error: Failed to calculate number of tokens, falling back to approximate count
> 
> ```
> import { OpenAI } from "langchain/llms/openai";
> import { SqlDatabase } from "langchain/sql_db";
> import { SqlDatabaseChain } from "langchain/chains/sql_db";
> import { DataSource } from "typeorm";
> 
> const langchainController = async () => {
>   const datasource = new DataSource({
>     type: "postgres",
>     url: "my db url",
>     logging: false,
>     synchronize: true,
>     extra: {
>       ssl: {
>         rejectUnauthorized: false,
>       },
>     },
>   });
> 
>   const db = await SqlDatabase.fromDataSourceParams({
>     appDataSource: datasource,
>   });
> 
>   const chain = new SqlDatabaseChain({
>     llm: new OpenAI({
>       temperature: 0,
>       openAIApiKey: "my api key",
>     }),
>     database: db,
>   });
> 
>   const res = await chain.run("How many products are available now?");
>   console.log(res);
> };
> export { langchainController };
> ```

@jacoblee93 can you help me on this issue?

**Comment by IemProg** [comment]
Hi @john930d ,

Did you solve this issue ? if so, can you please share the solution with us ?

Thanks !
