### ISSUE TITLE
elasticSearch knn query error 

### ISSUE THREAD

**Issue by kiraraty** [langchain-ai/langchainjs#2202]
/Users/caoyingxu/Desktop/langchain/elasticSearch-langchain/node_modules/@elastic/transport/lib/Transport.js:479
                    throw new errors_1.ResponseError(result);
                          ^

ResponseError: search_phase_execution_exception
        Root causes:
                query_shard_exception: failed to create query: [knn] queries are only supported on [dense_vector] fields

**Comment by jacoblee93** [comment]
CC @ezimuel - do you have any thoughts here?

**Comment by ezimuel** [comment]
@kiraraty can you paste the code that you are using with langchainjs and Elasticsearch vectorstore? It seems Elasticsearch is complaining that the field is not a [dense_vector](https://www.elastic.co/guide/en/elasticsearch/reference/current/dense-vector.html) type. In the langchainjs Elaticsarch integration we use only `embeddings` field as `dense_vector` [here](https://github.com/hwchase17/langchainjs/blob/main/langchain/src/vectorstores/elasticsearch.ts#L195). Thanks!
