### ISSUE TITLE
TypeScript error: Cannot find module './import_type.js'

### ISSUE THREAD

**Issue by sinedied** [langchain-ai/langchainjs#2228]
Using langchain `0.0.125`, if I try to use this import:

```ts
import { load } from "langchain/load";
```

I get a TS compilation error:
```
node_modules/langchain/dist/load/index.d.ts:1:46 - error TS2307: Cannot find module './import_type.js' or its corresponding type declarations.

1 import { OptionalImportMap, SecretMap } from "./import_type.js";
                                               ~~~~~~~~~~~~~~~~~~
```

The `import_type.js` file doesn't seem to exists?

Or is there another function I should use to deserialize data?
Thanks

**Comment by jacoblee93** [comment]
Looks like a bug - will have a look tomorrow!

**Comment by jacoblee93** [comment]
Hey sorry for the delay - just tried with the latest version and it worked fine. Can you give me any other info on your setup?
