### ISSUE TITLE
UnstructuredURLLoader feature is not availble

### ISSUE THREAD

**Issue by apurvjha123** [langchain-ai/langchainjs#2251]
Due to this issue I have to use cherrio, html-to-text which is given in documentation , there are some cons of this. When I asked RetrivalQA then It return css properties, URLs and javascript as well , because they are involved init.

Can please some one suggest what is the alternate of **### UnstructuredURLLoader** in javascript langchain Please .****

**Comment by apurvjha123** [comment]
i used these but not worked !

**Comment by apurvjha123** [comment]
the data diffrence between python and js is too diffrent 
'using python'

[Document(page_content="Explore STCET\n\nSt. Thomas' College of Engineering & Technlogy\n\nAICTE Approved, MAKAUT affiliated, with NBA Accredited Programmes\n\nApproved By AICTE\n\nAffiliated to MAKAUT, WB\n\nNBA Accredited Programmes Available\n\nAbout Us\n\nVision\n\nTo evolve as an industry oriented, research based Institution for creative solutions in various engineering domains, with an ultimate objective of meeting technological challenges faced by the Nation and the Society.

and when i use js the data comes something like this:-

using html-to-text :- 


'Document {
    pageContent: ' Skip to contentOnline FeesNIRFCareer in STCETOnline FeesNIRFCareer in STCET/*! elementor - v3.15.0 - 02-08-2023 */\n' +
      '.elementor-widget-image{text-align:center}.elementor-widget-image a{display:inline-block}.elementor-widget-image a img[src$=".svg"]{width:48px}.elementor-widget-image img{vertical-align:middle;display:inline-block}  /*! elementor - v3.15.0 - 02-08-2023 */\n' +
      ".elementor-heading-title{padding:0;margin:0;line-height:1}.elementor-widget-heading .elementor-heading-title[class*=elementor-size-]>a{color:inherit;font-size:inherit;line-height:inherit}.elementor-widget-heading .elementor-heading-title.elementor-size-small{font-size:15px}.elementor-widget-heading .elementor-heading-title.elementor-size-medium{font-size:19px}.elementor-widget-heading .elementor-heading-title.elementor-size-large{font-size:29px}.elementor-widget-heading .elementor-heading-title.elementor-size-xl{font-size:39px}.elementor-widget-heading .elementor-heading-title.elementor-size-xxl{font-size:59px}St. Thomas' Collegeof Engineering & Technology     B.Tech / M.Tech admissions 2023-2024 - 8017993801 Online FeesNIRFCareer in STCETOnline FeesNIRFCareer in STCET       Menu       Home    About Us       Achievements       Placements       Departments        Facilities        Admission        Contact Us         Home    About Us     Brief HistoryCollege TrustGovernanceOrganizational ChartAcademic AdministrationInstitute Cells & ClubsAcademic PerformanceRules & RegulationsCollege TimingMiscellaneous Information College Brochure  Download   Achievements     University Rank HoldersCollege ToppersSuccess Stories of GATESummer Internship ProgrammePublicationsHigher StudiesMOOCS  Placements     Placement OverviewVisiting Companies  Departments     Computer Science and EngineeringUG CoursesComputer Science and EngineeringArtificial Intelligence & Machine LearningPG CoursesArtificial Intelligence & Data ScienceElectronics & Communication EngineeringUG CoursesElectronics & Communication EngineeringPG CoursesInternet of ThingsInformation TechnologyUG CoursesInformation TechnologyElectrical EngineeringUG CoursesElectrical EngineeringBasic Science & HumanitiesFoundation CoursesBasic Science & Humanities   Facilities      Central Computer CenterCentral LibraryInternet & IntranetLanguage Practice LaboratoryRecreation  Admission     Admission NoticeApproval, Affiliation & AccreditationAdmission ProcedureIntake CapacityFee StructureScholarships   Contact Us   St. Thomas' Collegeof Engineering & Technology  .elementor-nav-menu__container{\n" +      
      'top:0px!important;\n' +
      '}\n' +'


I want data like python in javascript .

**Comment by Greasen** [comment]
UnstructuredLoader 功能依然不可用，在js版本中。提示错误
