### ISSUE TITLE
HuggingFaceInference Support for hosted endpoints

### ISSUE THREAD

**Issue by chasemcdo** [langchain-ai/langchainjs#2275]
With the rise of larger models such as Meta's Llama 2 many organization/individuals are becoming increasingly interested in using larger models and supporting [Hosted Inference Endpoints](https://huggingface.co/inference-endpoints) is a great way to enable that

**Comment by chasemcdo** [comment]
Support was added in HFInference V2, so no action is required on the LangChain end

**Comment by chasemcdo** [comment]
Some examples would be useful though

**Comment by gaord** [comment]
> Support was added in [HFInference V2](https://github.com/huggingface/huggingface.js/releases/tag/inference-v2.0.0), so no action is required on the LangChain end

langchainjs is using HFInference V1.5.1. So it need an upgrade to have that functionality in.

**Comment by chasemcdo** [comment]
Issue was fully resolved in #3104
