### ISSUE TITLE
How to sum up several chats?

### ISSUE THREAD

**Issue by andriibodryi** [langchain-ai/langchainjs#2283]
I have a chat bot to provide answers for some specific question. I need to sum up all chats to get some analytics, for example, "what questions were asked the most?". Each chat can be really close to tokens limit, so it's not possible just to upload all chats at once. Tried this one https://js.langchain.com/docs/modules/chains/popular/summarize, but that's not for me. Any idea how it can be handled in best way?

**Comment by jacoblee93** [comment]
Why is it "not for you"?

You could try a map reduce chain as well
