### ISSUE TITLE
Together AI wrapper for LangChain

### ISSUE THREAD

**Issue by joaopcm** [langchain-ai/langchainjs#2284]
Together AI is allowing any company to host their own instance of LLM, giving access to a diverse and vast library of models. This allows anyone to create enterprise-ready solutions, prioritizing privacy and security, and avoiding private information passing through companies like OpenAI.

I am willing to create a wrapper for LangChain so that anyone can easily use Together AI with LangChain.

cc @jacoblee93 @Austex @ivoneijr

**Comment by jacoblee93** [comment]
Sounds awesome!

**Comment by joaopcm** [comment]
@jacoblee93 
> Sounds awesome! Let me know if I can help.

I'm already working on it:
![image](https://github.com/hwchase17/langchainjs/assets/58827242/a4952967-f634-480a-913e-6e3dfe36d8ac)

I'll ask you for your code review once the PR is opened :)

**Comment by jamesmurdza** [comment]
Hi, any progress on this?

**Comment by joaopcm** [comment]
@jamesmurdza 
> Hi, any progress on this?

Not yet. I needed to pause my efforts on it because other high-priority demands have emerged. I'm gonna get back to it this week, though.

**Comment by LeventeNagy** [comment]
I made a super basic wraper just for basic stuff as I don't have much time to do a proper one as I am working long hours of my job

**TogetherLLM.py**

```
import together

from pydantic import Field
from typing import List, Optional
from langchain.callbacks.manager import CallbackManagerForLLMRun
from langchain.llms.base import LLM

import os
from dotenv import load_dotenv

load_dotenv()

together.api_key = os.getenv('TOGETHER_API_KEY')

class TogetherAI(LLM):
    
    """ Model: required, default="llama 2 13b chat" """
    model: str = Field(default="togethercomputer/llama-2-13b-chat", alias="model")
    
    temperture: Optional[float] = 0.0

    max_tokens: Optional[int] = 512

    top_k: Optional[int] = 90

    top_p: Optional[float] = 0.8

    repetition_penalty: Optional[float] = 1.1

    stop: Optional[List[str]] = None

    @property
    def _llm_type(self) -> str:
        return "togetherLLM"

    def _call(self, prompt, stop: stop, run_manager: Optional[CallbackManagerForLLMRun] = None):
        # Custom logic to generate response
        response = together.Complete.create(
            prompt=prompt, 
            model=self.model, 
            temperature=self.temperture,
            max_tokens=self.max_tokens,
            top_k=self.top_k,
            top_p=self.top_p,
            repetition_penalty=self.repetition_penalty,
            stop=self.stop
        )
        print(response)
        return response["output"]["choices"][0]["text"]

    @property
    def _identufying_params(self):
        return {}
```

Make sure your create an .env and place your api ky there

`TOGETHER_API_KEY=xxx`

You can call the LLM warper as such

```
from TogetherLLM import TogetherAI

llm = TogetherAI()
```

The default model is togethercomputer/llama-2-13b-chat

but if you need a different model just call

`llm = TogetherAI(model=" togethercomputer/llama-2-70b-chat")`

Only tested with basic Chat functions, but works well when it comes to basic conversations, it is a super basic start, I will make modifications and improve it later on.

**Comment by kevinfealey** [comment]
Any updates on this? Wanted to voice my desire for this wrapper too - together.ai has been awesome to use, but I'd like to use LangChain to interact with it since I use it for all other LLMs.

**Comment by jamesmurdza** [comment]
Would be cool! Could be very similar to this?

https://github.com/langchain-ai/langchain/blob/116cc7998cac563894bdf0037259db767882b55c/libs/langchain/langchain/chat_models/anyscale.py#L30

**Comment by PaulLockett** [comment]
I'm also very interested in a wrapper for this. 

I will be implementing it manually till this feature is done.

**Comment by joaopcm** [comment]
Hi all,

I understand and appreciate the excitement and anticipation around this feature. Your interest and feedback fuel our community and innovation. 

Regretfully, I want to inform you that, due to other high-priority commitments that require my immediate attention, I might not be able to contribute to this specific task as soon as you might expect. I know this news might be disappointing, and I apologize for any delay this might cause.

Please be assured though, this is a temporary situation. It is my wish and intent to return and work on this feature as soon as my other obligations allow. Your patience, understanding, and constant support through this time are deeply appreciated. 

Feel free to discuss or take forward any aspects of the issue. Any insights or contributions you can make in the interim will be extremely valuable.

Thank you for your understanding!

**Comment by daltunay** [comment]
Hi, do you have any idea when the Together wrapper will be available?

I can see it is already in the development version (`LangChain 0.0.339rc1`):
https://api.python.langchain.com/en/latest/_modules/langchain/llms/together.html#Together

Thanks!

**Comment by PaulLockett** [comment]
Hi all THis has been implemented: https://python.langchain.com/docs/integrations/llms/together

@joaopcm please close this issue

**Comment by joaopcm** [comment]
> Hi all This has been implemented: https://python.langchain.com/docs/integrations/llms/together
> 
> @joaopcm please close this issue

The link you provided is for the Python version, not for the JavaScript one. That being said, I don't think this issue should be closed unless there's a Together AI interface for the JS version.

**Comment by jacoblee93** [comment]
Yes, they're available in JS too in `@langchain/community`, e.g.: https://js.langchain.com/docs/integrations/chat/togetherai

**Comment by cheald** [comment]
This wrapper accepts but does not consume modelKwargs. Together [provides support for the OpenAI-like json response_format](https://docs.together.ai/docs/json-mode), but there doesn't currently appear to be any way to invoke it, as modelKwargs gets silently swallowed. Simply saving `this.modelKwargs = inputs.modelKwargs` in the constructor and then splatting it into the body in `constructBody` should be sufficient.
