### ISSUE TITLE
Support AWS OpenSearch Serverless

### ISSUE THREAD

**Issue by annassommer** [langchain-ai/langchainjs#2302]
Hi, I have been trying to use the OpenSearch Vector Store together with AWS OpenSearch Serverless, however I have run into a couple of issues there. The refresh call when creating the Vector Store and adding vectors is not supported by AWS OpenSearch Serverless.
<img width="933" alt="Screenshot 2023-08-16 at 10 51 01" src="https://github.com/hwchase17/langchainjs/assets/49270767/6762e3ed-9453-4340-912e-e276d7f733d7">
It therefore throws a 404 Error when called. I spoke with someone from AWS OpenSearch Serverless, and they told me that for AOSS the refresh call was not supported, but also not needed and could simply be removed. 
Querying for Data did also not work, since the body of the request is different in AOSS: 
<img width="689" alt="Screenshot 2023-08-16 at 10 54 44" src="https://github.com/hwchase17/langchainjs/assets/49270767/223596e3-3953-4099-b6ab-3aedb33eccc2">

 And AOSI (AWS OpenSearch Ingestion):
<img width="706" alt="Screenshot 2023-08-16 at 10 55 34" src="https://github.com/hwchase17/langchainjs/assets/49270767/5b475c17-f616-4263-960e-7393944de1b8">

I saw that AOSS is already supported in langchain python: https://github.com/langchain-ai/langchain/pull/8256
It would be a great help if you could also add AOSS support for langchain js. 
Thank you in advance for any help here.

**Comment by mirodrr** [comment]
Any updates on this?
