### ISSUE TITLE
Type instantiation is excessively deep and possibly infinite.

### ISSUE THREAD

**Issue by fer112233** [langchain-ai/langchainjs#2310]
When I use any of the new openai-function functionality in langchain, I get many kinds of errors on typescript and eslint also takes over 30 seconds to run.
Specifically, when using the DynamicStructuredTool with this zod schema:
```javascript
    z.object({
      query: z
        .string()
        .describe("The actual text or keywords to search for on the database."),
      search_type: z
        .number()
        .describe(
          "This parameter determines the type of search that will be performed.",
        ),
    }),
```
This seems like a simple schema but somehow I get the error `Type instantiation is excessively deep and possibly infinite.

Additionally, it is also giving me this error `Types have separate declarations of a private property  _cached`

**Comment by jacoblee93** [comment]
Zod is pretty complex - what's your hardware setup?

**Comment by fer112233** [comment]
I am using a Macbook Pro M1 Max 64GB Ram
That should not be an issue whatsoever, the schema is pretty simple, I use zod in many other parts of the project with very complex schemas and I have no issues. It is only when used with the DynamicStructuredTool.

**Comment by jacoblee93** [comment]
Hmm... any other hints you can give me to help repro

**Comment by nicolas-angelo** [comment]
I'm having the same exact issue - as soon as I used DynamicStructuredTool & zod, my project takes over 30 seconds for type checking to work.
My Zod schema in this tool is pretty simple as well, only 3 properties:

```
schema: z.object({
  taskId: z.string(),
  agentName: z.string(),
  status: z.nativeEnum([
    TaskStatus.IN_PROGRESS,
    TaskStatus.NEEDS_REVIEW,
    TaskStatus.BLOCKED,
  ]),
  message: z.string(),
}),
```


Errors:
 `Type instantiation is excessively deep and possibly infinite.`
`Types have separate declarations of a private property  _cached`

**Comment by jacoblee93** [comment]
Very odd - `_cached` shows up only once in the code base under `TensorFlowEmbeddings`.

Maybe share the zod and LangChain versions you're using?

**Comment by nicolas-angelo** [comment]
@jacoblee93 

"typescript": "^5.1.6
"langchain": "^0.0.129",
"zod": "^3.22.1

**Comment by fmonper1** [comment]
Having the same issuse with the following versions:

```
    "langchain": "0.0.129",
    "zod": "3.21.1",
    "typescript": "4.9.5"
```

**Comment by jacoblee93** [comment]
I'm still not able to repro:

https://codesandbox.io/s/typescript-playground-export-forked-f42stg?file=/index.ts

Am I doing anything differently in the above sandbox than people are here?

Can we also check whether there's some other TypeScript version installed globally?

**Comment by fmonper1** [comment]
If i copy and past my code into the sandbox I can use it without a problem:

My schema is the following:

```
     schema: z.object({
            query: z
                .string()
                .describe("The actual text or keywords to search for on the database."),
            search_type: z
                .number()
                .describe(
                    "This parameter determines the type of search that will be performed. The value can be any number between 0 and 1.",
                ),
        }),
```

<img width="664" alt="CleanShot 2023-08-28 at 21 09 31@2x" src="https://github.com/hwchase17/langchainjs/assets/16008141/c331b4c9-7fb3-420f-b165-431dfa6740ec">

**Comment by MrRhodes** [comment]
what i found was that the versions of zod that langchain used was different to the version of zod i installed, so you get conflicts with comparison checking it is doing ...

I was having the same issues as mentioned here, i simply removed zod from the root of my project and it just started working... (i know, this isn't a proper fix, but it allowed me to get work done!)

**Comment by jacoblee93** [comment]
Ah very interesting! Thank you for digging in @MrRhodes!

Did you have a more recent or less recent version of zod? I'm not exactly sure what the best resolution would be but if it's more recent we can at least bump our version.

**Comment by JTCorrin** [comment]
Leaving a comment to say I had the exact same problem:

> as soon as I used DynamicStructuredTool & zod, my project also takes over 30 seconds for nodemon refreshes, type checking, etc to work.

I had zod v3.22.2 in my project. I've updated to match the langchain version of 3.22.3 and that has solved my problem

**Comment by johannbuscail** [comment]
Hey, has someone found the solution ?

**Comment by jacoblee93** [comment]
Seems like it's a zod version mismatch as best I can tell.

**Comment by mobob** [comment]
Just here to say, same exact issue, same fix. When i started playing with the langchain samples i just "added zod" via pnpm and for it installed a 3.21 version...  possibly because i was using that in a different project in my monorepo 🤔. 

Fixing to 3.22.4 which is the version referenced all over the place for use by langchain in my lock file immediately resolved the issue.

**Comment by ZimneJonas** [comment]
Same issue downgraded to "@langchain/core": "0.3.43", fixes it as well. 
Updating to zod.dev/v4 might also work.

**Comment by thundernet8** [comment]
I fixed it by this, ensure using only one version of zod
```json
{
  "resolutions": {
    "zod": "xxx"
  }
}
```

**Comment by Qbason** [comment]
Installed the newest versions of @langchain/community,@langchain/core, @langchain/langgraph, and I got the same issue

**Comment by bnek** [comment]
@Qbason  I worked around it by installing zod@3.25.67 

`npm install zod@3.25.67 --save-exact`

**Comment by max-carey** [comment]
I wish I found this thread sooner! Wasted a couple of hours on this: `npm install zod@3.25.67 --save-exact` worked for me ~

**Comment by githero20** [comment]
<img width="733" height="458" alt="Image" src="https://github.com/user-attachments/assets/c8eab0f3-a7ec-4484-ad9f-4977197f28d3" />

getting the same error and npm install zod@3.25.67 --save-exact worked for me

**Comment by itsahmadawais** [comment]
> I wish I found this thread sooner! Wasted a couple of hours on this: `npm install zod@3.25.67 --save-exact` worked for me ~

It worked for me! Thanks.

**Comment by guarito47** [comment]
overriding works for me, in a similiar situation, but this post gave me the path for my solution thanks
"overrides": {
    "@langchain/community":{
      "zod": "3.25.67"
    }
  }

**Comment by wasadigi** [comment]
I found the related issue in the `zod` repo: https://github.com/colinhacks/zod/issues/4984.

In my setup, I replaced:

`
import { z } from "zod";
`

with

`
import { z } from "zod/v3";
`

This seems to work, also for `zod` versions > 3.25.67. I am on `3.25.76`.

**Comment by danLeBrown** [comment]
For me, the solution that worked was:

- run `npm why zod` to get the version of zod langchain uses as a peer dependency and then install that, ie, `npm install zod@<version>`
- import { z } from 'zod/v3'; use this when using zod features, especially for the langchain-related bits

**Comment by Refrezsh** [comment]
If you have decided to update langchain dependencies to the latest version and previously used the pinned version of zod: `3.25.67` You will encounter **Type instantiation** problem again. At the same time, it will not be possible to update the Zod version to `4` because `@langchain/comunity` still requires version `3`.

So if you are switching from
```
    "@langchain/core": "0.3.78",
     ...otherlangchainLibs,
     "zod": "3.25.67"
```

to 

```
    "@langchain/core": "1.1.24",
     ...otherNewlangchainLibs,
     "zod": "3.25.67"
```

Change zod ipmorts to `import { z } from "zod/v4";`
