### ISSUE TITLE
Structured output parser prompt has invalid json examples

### ISSUE THREAD

**Issue by hjr3** [langchain-ai/langchainjs#2316]
At https://js.langchain.com/docs/modules/model_io/output_parsers/structured the prompt has double `{` and `}` brackets. 

```
Extract the last north american phone number from the text below.

You must format your output as a JSON value that adheres to a given "JSON Schema" instance.

"JSON Schema" is a declarative language that allows you to annotate and validate JSON documents.

For example, the example "JSON Schema" instance {{"properties": {{"foo": {{"description": "a list of test words", "type": "array", "items": {{"type": "string"}}}}}}, "required": ["foo"]}}}} would match an object with one required property, "foo". The "type" property specifies "foo" must be an "array", and the "description" property semantically describes it as "a list of test words". The items within "foo" must be strings. Thus, the object {{"foo": ["bar", "baz"]}} is a well-formatted instance of this example "JSON Schema". The object {{"properties": {{"foo": ["bar", "baz"]}}}} is not well-formatted.

Your output will be parsed and type-checked according to the provided schema instance, so make sure all fields in your output match the schema exactly and there are no trailing commas!

Here is the JSON Schema instance your output must adhere to. Include the enclosing markdown codeblock:
```json
{"type":"object","properties":{"phoneNumber":{"type":"string"}},"required":["phoneNumber"],"additionalProperties":false,"$schema":"http://json-schema.org/draft-07/schema#"}

Text: xxxxxxxxxx
JSON:
```

This works well for the most part, but every once in a while the output has double brackets. The parser then returns this error:

```
 OutputParserException [Error]: Failed to parse. Text: "{{"phoneNumber": "xxxxxxxxxx"}}". Error: SyntaxError: Unexpected token { in JSON at position 1
```

The output is: `'{{"phoneNumber": "xxxxxxxxxx"}}'`

Note: `xxxxxxxxxx` is the redacted phone number.

If I remove the double brackets from the prompt, my failure rate drops.

**Comment by hjr3** [comment]
I am happy to open a PR to fix this if folks agree that this is a bug.

**Comment by jacoblee93** [comment]
Interesting - might be an extra escape character somewhere. Would welcome a PR although generally we funnel people towards using OpenAI Functions for structured data like this:

https://js.langchain.com/docs/modules/chains/popular/structured_output
https://js.langchain.com/docs/modules/model_io/models/chat/how_to/function_calling

**Comment by hjr3** [comment]
> if you use a single bracket, we assume it's an input variable slot

I may be missing something, but the format instructions do not appear to be part of the template string itself:

```js
const formatInstructions = parser.getFormatInstructions();

const prompt = new PromptTemplate({
  template:
    "Answer the users question as best as possible.\n{format_instructions}\n{question}",
  inputVariables: ["question"],
  partialVariables: {
    format_instructions: formatInstructions, // <---- formatInstructions is a variable to the template and cannot accept variables
  },
});
```

> we funnel people towards using OpenAI Functions for structured data like this

The OpenAI support is nice, but I am not able to use OpenAI for my work.

**Comment by hjr3** [comment]
@dosubot I just checked and https://github.com/langchain-ai/langchainjs/blob/d2ec312f48f07fd900a9e8ceb2790eea2c740476/langchain/src/output_parsers/structured.ts#L82 still has double brackets.
