### ISSUE TITLE
Errors when run from a network that blocks https://tiktoken.pages.dev

### ISSUE THREAD

**Issue by jorupp** [langchain-ai/langchainjs#2326]
My work network is blocking <https://tiktoken.pages.dev/> (I'm guessing it's an over-zealous rule to block tiktok), which is causing this error (though I'm not sure exactly what code is throwing it):

```
Failed to calculate number of tokens, falling back to approximate count SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:6662:19)
    at successSteps (node:internal/deps/undici/undici:6636:27)
    at node:internal/deps/undici/undici:1236:60
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Could alternative approaches to populate `cache` from `langchain/src/util/tiktoken.ts` be exposed so I can add the encodings I know I need?  ie. a `cacheEncoding(encoding: TiktoenEncoding, bpe: TiktokenBPE)` method?

This could also be useful for other environments that want to minimize the calls made to external URLs at runtime.

**Comment by jacoblee93** [comment]
Yeah would be good to fix - at the very least it's just warning you and not throwing an error right?

**Comment by jorupp** [comment]
Sorry, I should have clarified - it appears to still be working, and I haven't had a chance to drill into the side effects of having an imprecise count of the tokens.  So it's possible it's more of a minor issue, so long as the outgoing network call doesn't get considered to be a security issue.

**Comment by jorupp** [comment]
Yes, I'm still getting this error on the latest version of the code.  I get that this may not be a priority for anyone though, so I get marking it stale :)

If I get the time later to do so, I'm hoping to write up the code to do it and submit a PR (since I don't want to have to maintain a fork myself just for our app).
