### ISSUE TITLE
Cannot get final name for export 'PromptTemplate' of ./node_modules/langchain/dist/prompts/index.js

### ISSUE THREAD

**Issue by TheOrcDev** [langchain-ai/langchainjs#2335]
When building a project in Next.js version 13.4, getting this error:

**UPDATE**: Next.js 14.0 same error

Cannot get final name for export 'PromptTemplate' of ./node_modules/langchain/dist/prompts/index.js

It's breaking the build, and not able to deploy it to Vercel.

**Comment by TribalKing** [comment]
It's not solving it, also tried this one:

`const nextConfig = {
  webpack: (config, { isServer }) => {
    if (!isServer) {
      config.resolve.fullySpecified = false;
    }

    config.module.rules.push({
      test: /node_modules\/langchain/,
      resolve: {
        fullySpecified: false,
      },
    });

    return config;
  },
};`

**Comment by TribalKing** [comment]
Bug is coming because of this part:

```
experimental: {
    serverActions: true,
},
```

When `serverActions` is removed, it's compiling fine.

**Comment by hnykda** [comment]
It happened to me on NextJS 14.1 where the server actions should be stable... It was caused by importing a _type_ for something totally unrelated to langchain.

**Comment by TribalKing** [comment]
> It happened to me on NextJS 14.1 where the server actions should be stable... It was caused by importing a _type_ for something totally unrelated to langchain. I gave up on trying to figure what it was, it's dark magic.

Haven't tested it yet, I thought new Next.js 14.0 is going to fix it. Better luck next time! 😃

**Comment by guidsen** [comment]
I also have this issue. Does anybody have a fix already?

**Comment by connorblack** [comment]
Also having this issue

**Comment by ochmanski** [comment]
I have this issue but for a different lib. Upvoting here so it gains traction

**Comment by KarloAldrete** [comment]
Not the solution you want but... 
![langchain](https://github.com/langchain-ai/langchainjs/assets/66887635/fdd6c129-61c6-4345-9b82-8fd6decfa7aa)
![image](https://github.com/langchain-ai/langchainjs/assets/66887635/047aefcc-2f32-4469-9632-afc66f1e1197)

**Comment by BhaveshKumarSharma** [comment]
This works, 
<img width="617" alt="image" src="https://github.com/langchain-ai/langchainjs/assets/88853430/0dc6d2f1-4f60-48d9-a77c-59c29150d917">
Thanks @KarloAldrete

**Comment by TribalKing** [comment]
> Not the solution you want but... ![langchain](https://private-user-images.githubusercontent.com/66887635/283623633-fdd6c129-61c6-4345-9b82-8fd6decfa7aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0NzI1ODMsIm5iZiI6MTcwMTQ3MjI4MywicGF0aCI6Ii82Njg4NzYzNS8yODM2MjM2MzMtZmRkNmMxMjktNjFjNi00MzQ1LTliODItOGZkNmRlY2ZhN2FhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDIzMTEyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1OTZjYWUwNTI1Y2IwODVjNTI4YjY2N2I0YjcwODUxMjMxMjY0MmZjMGJlODNiNWJmYTM5YmZjNzRhMTQ4NjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AWWwi9saLoiL-0Xaeoifk4ZsRrkZLEpLvsNhkos4s2Y) ![image](https://private-user-images.githubusercontent.com/66887635/283623668-047aefcc-2f32-4469-9632-afc66f1e1197.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0NzI1ODMsIm5iZiI6MTcwMTQ3MjI4MywicGF0aCI6Ii82Njg4NzYzNS8yODM2MjM2NjgtMDQ3YWVmY2MtMmYzMi00NDY5LTk2MzItYWZjNjZmMWUxMTk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDIzMTEyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiMzg3NzhkZWI2ZWMxNmI3ZWQzN2M5ZWQ0YTAxNzNhNjJkNGU2NzEyNDcwYWJlN2UxYmI1OWQ0ZWYyYzdjNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UpDg8cbrlZjZ9VNS0ggC6NHOSx_rc1iafAVmgoHUeEU)

Just tried it out! Working!

**Comment by hnykda** [comment]
My eyes hurt, but it really works.

**Comment by TheOrcDev** [comment]
Hi! Like @hnykda said it's still happening on [#5235](https://github.com/langchain-ai/langchainjs/issues/5235)

That's the same bug happening on latest Next.js version. We can leave one issue on GitHub until it's fixed.

**Comment by respectmashego** [comment]
expercing same issue when trying to deploy next js langachin app .Cannot get final name for export 'BaseMemory' of ./node_modules/@langchain/core/memory.js. im trying the solution above but i experience same issue
