### ISSUE TITLE
How to pass custom functions to initializeAgentExecutorWithOptions

### ISSUE THREAD

**Issue by LeoMartinDev** [langchain-ai/langchainjs#2338]
Following this documentation https://js.langchain.com/docs/modules/agents/agent_types/openai_functions_agent it's not clear how I am supposed to pass a custom open ai function.
I'm trying to make my agent output in JSON following a specific JSON Schema

**Comment by vpctorr** [comment]
You should pass tools defined like such.

```js
const tool = new DynamicStructuredTool({
  name: '…',
  description: '…',
  schema: z.object({…}),
  func: async (input, callbacks) => {…}
})
```

The Zod schema will be converted to a JSON schema that will be used in the function call.
