### ISSUE TITLE
Streaming does not work if run behind a proxy server

### ISSUE THREAD

**Issue by cnshsliu** [langchain-ai/langchainjs#2339]
> I have the same issue.
> 
> It is working fine, when disabling the streaming and passing a httpsAgent inside the `baseOptions` configuration (somehow what is "explained" here: [#739 (comment)](https://github.com/hwchase17/langchainjs/issues/739#issuecomment-1537163517) )
> 
> With streaming enabled the custom implementation using `fetch` inside of langchain seems to be used (https://github.com/hwchase17/langchainjs/blob/main/langchain/src/util/axios-fetch-adapter.js) which ignores proxy settings.
> 
> Would be great so see a streaming example which allows to use a forward proxy.

I have the same issue. 

I have two files "tst-normal.ts" and "tst-stream.ts".     In an network environment which I could access OpenAI API directly. both programs run ok. 

however, in another network in which I have to connect to OpenAI API via a forward proxy. only "ts-node tst-normal.ts" works, while "ts-node tst-stream.ts" fails, stuck in middle.

## ts-stream.ts
```
import { ChatOpenAI } from "langchain/chat_models/openai";
import { HumanMessage } from "langchain/schema";

(async () => {
  const chat = new ChatOpenAI({
    maxTokens: 25,
    streaming: true,
  });

  const response = await chat.call([new HumanMessage("Tell me a joke.")], {
    callbacks: [
      {
        handleLLMNewToken(token: string) {
          console.log({ token });
        },
      },
    ],
  });

  console.log(response);
})();
```

## tst-normal.ts
```
import { ChatOpenAI } from "langchain/chat_models/openai";
import { HumanMessage } from "langchain/schema";

(async () => {
  const chat = new ChatOpenAI({
    maxTokens: 25,
  });

  const response = await chat.call([new HumanMessage("Tell me a joke.")]);

  console.log(response);
})();
```

Like @patst says, would be great to see how to make streaming behind a proxy works, thanks in advance.

_Originally posted by @cnshsliu in https://github.com/hwchase17/langchainjs/issues/1925#issuecomment-1685374294_

**Comment by cnshsliu** [comment]
BTW,  I could confirm the original ChatGPT conversation API does support Streaming via proxy.
I have another project in which I use OpenAI API directly (without langchain) and steaming is just perfect.

since it's a somehow large project, I can not paste all codes of it. just some segments FYR.

...
	proxyAgent = new HttpsProxyAgent(process.env.https_proxy);
...

		const body = {
			model: "gpt-3.5-turbo",
			// messages: [{ role: "user", content: "写三句中文诗" }],
			messages: messages,
			stream: true,
		};
		const requestInit: RequestInit = {
			method: "POST",
			headers: {
				"Content-Type": "application/json",
				Authorization: `Bearer ${this.apiKey}`,
			},
			body: JSON.stringify(body),
			agent: proxyAgent,
			json: true,
			signal: controller.signal,
		};
		const response = await fetch(this.apiUrl, requestInit);
....
const reader = response.body;
for await (const chunk of reader) {
	let str = chunk.toString();
	console.log(str);
}
...

**Comment by jacoblee93** [comment]
We'll be upgrading to OpenAI's new v4 SDK soon - I think that may fix this!

**Comment by miomio-xiao** [comment]
Upgrade to version 0.0.142 to resolve, refer to the code:

```
import { ProxyAgent } from 'proxy-agent';

const model = new ChatOpenAI(
  {
    streaming: true,
  },
  {
    httpAgent: new ProxyAgent(),
  },
);
```
