### ISSUE TITLE
Langchain S3 Loader - Changing Chunk Size

### ISSUE THREAD

**Issue by codasana** [langchain-ai/langchainjs#2343]
I used Langchain S3 loader that makes use of unstructured.

However the problem is that the document got split into really small chunks.

It’s a two page document, when I used Langchain’s PDFLoader it split it into 8 documents.

However, when I use S3Loader, it split it into 61 documents each document being very small. Is there a way to change this?

Here is the Langchain’s S3Loader that I used:

https://js.langchain.com/docs/modules/data_connection/document_loaders/integrations/web_loaders/s3

**Comment by msahajwani** [comment]
This is the code I've used.

`			const loader = new S3Loader({
				bucket: "bucketid",
				key: fileName,
				s3Config: {
				  region: process.env.AWS_REGION,
				  credentials: {
					accessKeyId: process.env.AWS_ACCESS_KEY_ID,
					secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
				  },
				},
				unstructuredAPIURL: "https://api.unstructured.io/general/v0/general",
				unstructuredAPIKey: "myapikey",
			  });
				const docs = await loader.load();`
				
I don't know where I can specify the TextSplitter or the chunk settings.

**Comment by donxepe** [comment]
I found a way to change the parameters, you need to extend the UnstructuredLoader class and then change the parameter of your interest, here I waned to change the strategy from "hi_res" to "fast":

```
class fastUnstructuredLoader extends UnstructuredLoader {
  constructor(filePathOrLegacyApiUrl, optionsOrLegacyFilePath) {
    super(filePathOrLegacyApiUrl, {
      ...optionsOrLegacyFilePath,
      // you can change any of the options here
      strategy: "fast",
    });
  }
}

const loader = new S3Loader({
            bucket,
            key,
            unstructuredAPIURL: UNSTRUCTURED_URL,
            unstructuredAPIKey: UNSTRUCTURED_API_KEY,
            UnstructuredLoader: fastUnstructuredLoader,
          });
          return loader.load();
```
