### ISSUE TITLE
Azure Cognitive Search

### ISSUE THREAD

**Issue by tsmithanika** [langchain-ai/langchainjs#2349]
Is there plans to integrate Azure Cognitive Search as vector store?

**Comment by ladrians** [comment]
+1 to the question, found that this [PR](https://github.com/langchain-ai/langchainjs/pull/2396) may be the starting point?

**Comment by ladrians** [comment]
Tested part of [PR2396](https://github.com/langchain-ai/langchainjs/pull/2396) manually and the basics worked.
Could not figure out a way to use filters, when usint a `{}` empty reference I could reproduce the following, hope it helps

````
Error "searchRequest.filter with value "[object Object]" must be of type string." occurred in serializing the payload - undefined
```

**Comment by ladrians** [comment]
Another issue detected, the Dimensions is fixed for 1536. It would be nice to be optional to change so as to be used with another embedding.

**Comment by lucasbuges** [comment]
Azure Cognitive Search its the most important integration for enterprise data use cases. How can i help here? All community flowise is waiting for this. 

Thanks @ladrians
