### ISSUE TITLE
IBM WatsonX Integration

### ISSUE THREAD

**Issue by chasemcdo** [langchain-ai/langchainjs#2378]
With IBM's recent release of [WatsonX.ai](https://www.ibm.com/products/watsonx-ai) you can now host LLMs through IBM Cloud and perform completion via their API.
I am working on an integration for LangChainJS, but have some questions with regards to best practices from the LangChain side.

As of this moment there is no JS package which wraps the endpoints, so the present integration would serve as said wrapper.

The existing integrations within LangChain all seem to use a package for managing endpoints, but for this use case would we be open to having the LangChain integration serve as said package?

**Comment by chasemcdo** [comment]
@dosu-bot unfortunately, the WatsonX API doesn't share the same structure as OpenAI's chat completion. ie ignoring the base path OpenAI's is: `/chat/completions`, while WatsonX uses: `/generation/text`.

Can this be used to also change the endpoint posted to?

**Comment by Vishakan** [comment]
My colleagues and I would be interested in working on this issue.

**Comment by chasemcdo** [comment]
Hey @Vishakan main blocker that existed when I opened this (it has been a while) was finding a JS library maintained by IBM to use for API interactions. There were several available, but they all targeted pre-release APIs

**Comment by Vishakan** [comment]
Oh ok. Thanks for letting me know! 😊@chasemcdo

**Comment by chasemcdo** [comment]
The alternative I was considering is simply having LangChain wrap those endpoints, but in the last couple months I wouldn't be surprised if something has been made to make that part easier. At the time I was working at IBM and planning to build something out for this, but have since left the team I was on.

So I'd recommend seeing if any production wrappers are available now, since that'd allow more flexible endpoints as the WatsonX ecosystem develops. My old team would surely appreciate this item being closed :)

**Comment by psycho-baller** [comment]
@chasemcdo We are back at it with the Tai migration😂 There is a watsonx integration w the python langchain but not js so we're kinda stuck with Tai using python for now

**Comment by chasemcdo** [comment]
> @chasemcdo We are back at it with the Tai migration😂 There is a watsonx integration w the python langchain but not js so we're kinda stuck with Tai using python for now

@psycho-baller Haha, I think my branch was mostly complete outside of WatsonX. Has Tai been moved over from OpenAI?
I'll likely be wrapping up this issue in the next few weeks, so can ping y'all once I have finished added WatsonX to JS

**Comment by psycho-baller** [comment]
I, and the whole of IBM salute you for taking the time to work on that🫡. I'm willing to collaborate if you'd like me to speed things up

**Comment by chasemcdo** [comment]
@psycho-baller @bsteinfeld enjoy 😉
