### ISSUE TITLE
Is someone already working on a MultiQueryRetriever?

### ISSUE THREAD

**Issue by willemmulder** [langchain-ai/langchainjs#2382]
Hi all, is someone possibly already working on a MultiQueryRetriever? 

It already exists on the [Python side of things](https://python.langchain.com/docs/modules/data_connection/retrievers/MultiQueryRetriever).
If not, maybe I could work on it or work with someone on it.

Let me know!

**Comment by jacoblee93** [comment]
Would be awesome!

**Comment by willemmulder** [comment]
Small update: will send in a PR for this feature this week!
