### ISSUE TITLE
[Question] Graph DB QA chain for JS

### ISSUE THREAD

**Issue by ali-habibzadeh** [langchain-ai/langchainjs#2383]
I don't seem to be able to find the Graph DB QA chain in the ts version of the library. Is it Python only?

**Comment by jacoblee93** [comment]
At the moment yes - would love a PR though!

**Comment by ali-habibzadeh** [comment]
Unfortunately I am way too busy to take it on. Isn't this project separate from the main langchain company? I thought some of the $10m will help this project too.

**Comment by jacoblee93** [comment]
Alright, sounds good!

**Comment by gkorland** [comment]
We would love to work on a PR, any guidance?

**Comment by gkorland** [comment]
@jacoblee93 just pushed a very early draft PR (copied most of it from the VectorStore), just to see that you're OK with the structure.

**Comment by jacoblee93** [comment]
Excellent! Will look as soon as I can.

**Comment by gkorland** [comment]
It's far from ready, just wanted to verify that this is the architecture that works for you

**Comment by gkorland** [comment]
The the Graph database has to implement `getSchema()`
