### ISSUE TITLE
Multi version of node module

### ISSUE THREAD

**Issue by BitVoyagerMan** [langchain-ai/langchainjs#2391]
I was trying to integrate my custom LLM.
In my code, I have to use axios@1.14.0
And in Openai llm code which is already exists, it uses axios@0.26.1
So multi version of axios module is needed.
So I fixed **langchain/package.json** file like this.
```
"devDependencies": {
...
"axios" : "^0.26.0",
"axios-bittensor": "npm:axios@^1.4.0"
...
}
```
Almost tests, I passed but at **Environment tests**, I failed.
`Cannot find package 'axios-bittensor' imported from /app/node_modules/langchain/dist/llms/bittensor.js`

How can I solve this issue?
Here's my PR.
[PR for my custom llm integration which has got errors](https://github.com/hwchase17/langchainjs/pull/1267)

**Comment by jacoblee93** [comment]
We'll be removing the Axios dependence from OpenAI soon (watch #2353) which should fix this!
