### ISSUE TITLE
JavaScript LangChain Qdrant semantic search results: pageContent in each Document is undefined

### ISSUE THREAD

**Issue by amrohendawi** [langchain-ai/langchainjs#2408]
### System Info

- LangChain version: 0.0.105
- Platform: Macbook Pro M1 - Mac OS Ventura
- Node.js version: v18.17.1
- qdrant/js-client-rest: 1.4.0

### Who can help?

@hwchase17 
@agola11 

### Information

- [ ] The official example notebooks/scripts
- [X] My own modified scripts

### Related Components

- [ ] LLMs/Chat Models
- [ ] Embedding Models
- [ ] Prompts / Prompt Templates / Prompt Selectors
- [ ] Output Parsers
- [ ] Document Loaders
- [X] Vector Stores / Retrievers
- [ ] Memory
- [ ] Agents / Agent Executors
- [ ] Tools / Toolkits
- [ ] Chains
- [ ] Callbacks/Tracing
- [ ] Async

### Reproduction

**Related Components:**
- Vector Stores / Retrievers
- JavaScript LangChain Qdrant Wrapper

**Information:**
The issue arises when attempting to perform a semantic search using the Qdrant wrapper in LangChain through JavaScript. The provided code snippet is as follows:

```javascript
const embeddings = new OpenAIEmbeddings({ openAIApiKey: process.env.OPENAI_API_KEY })

const vectorStore = await QdrantVectorStore.fromExistingCollection(
  embeddings,
  {
    url: process.env.QDRANT_URL,
    collectionName: process.env.QDRANT_COLLECTION_NAME
  })

const results = await vectorStore.similaritySearch("some query", 4)
```

The problem is that the `results` list of Documents contains undefined `pageContent`, while the metadata is fetched correctly. Strangely, when performing the same operation using the Python LangChain Qdrant wrapper, the `page_content` and `metadata` are both retrieved from the same Qdrant vectorstore correctly.

**Reproduction:**
To reproduce the issue, follow these steps:

1. Use the provided code snippet to perform a semantically search using the JavaScript LangChain Qdrant wrapper.
2. Examine the `results` list of Documents and observe that the `pageContent` property is undefined.
3. Compare the results with the results from the python equivalent code snippet:
```python
from langchain.embeddings import OpenAIEmbeddings
from langchain.vectorstores import Qdrant
from qdrant_client import QdrantClient

    qdrant_client = QdrantClient(
        api_key=os.getenv("QDRANT_API_KEY"),
        url=os.getenv("QDRANT_URL")
    )
    # get existing Qdrant vectorstore
    vectorstore = Qdrant(
        embeddings=openai_embeddings,
        client=qdrant_client,
        collection_name=os.getenv("QDRANT_COLLECTION_NAME"),
    )
vectorstore.similarity_search(query='some query', k=4)
```

Please assist in resolving this discrepancy in the behavior between the two wrappers.

### Expected behavior

The expected behavior is that when performing a semantically search using the JavaScript LangChain Qdrant wrapper, the `results` list of Documents should contain valid `pageContent` along with correct metadata, similar to the behavior in the Python LangChain Qdrant wrapper.

Expected result (works with the python Qdrant wrapper):

```bash
[Document(page_content='\n Some content of a document ', metadata={'source': 'https://some.source.com', 'title': 'some title'})
...
]

```

Actual result:

```bash
[Document(page_content=undefined, metadata={'source': 'https://some.source.com', 'title': 'some title'})
...
]
```

The problem doesn't arrise when I use the javascript Qdrant official client (not the langchain wrapper).

Example code snippet:

```javascript
import { OpenAIEmbeddings } from "langchain/embeddings/openai"
import { QdrantClient } from "@qdrant/js-client-rest"

  const embeddings = new OpenAIEmbeddings({ openAIApiKey: process.env.OPENAI_API_KEY })

  const query = "some query"
  const queryEmbedding = await embeddings.embedQuery(query)
  const resultsQdrant = await client.search(
    process.env.QDRANT_COLLECTION_NAME,
    {
      vector: queryEmbedding,
      limit: 4
    }
  )
  ```

Example output:

```bash
Array(4) [Object({
  "id": "09acff81-8c06-4813-b85f-efde39751390",
  "version": 55,
  "score": 0.8476821,
  "payload": {
    "metadata": {
      "source": "some source",
      "title": "some title"
    },
    "page_content": "some page content"
  },
  "vector": null
})
]

```

**Comment by amrohendawi** [comment]
I fixed the issue by creating a custom Qdrant wrapper where the results from the Qdrant client are converted into Documents while making sure `pageContent` is fetched as `page_content`:


```js

import { Document } from "langchain/document"
import { OpenAIEmbeddings } from "langchain/embeddings/openai"
import { QdrantClient } from "@qdrant/js-client-rest"

class CustomQdrant {
  private embeddings: OpenAIEmbeddings;
  private client: QdrantClient;
  private collectionName: string;

  constructor(embeddings: OpenAIEmbeddings, url: string, apiKey: string, collectionName: string) {
    this.embeddings = embeddings;
    this.client = new QdrantClient({
        url: url,
        apiKey: apiKey
      }
    )
    this.collectionName = collectionName
  }

  async similaritySearch(query: string, k: number): Promise<Document[]> {
    const queryEmbedding = await this.embeddings.embedQuery(query);
    const resultsQdrant = await this.client.search(this.collectionName, {
      vector: queryEmbedding,
      limit: k,
    });

    // convert the resultsQdrant to list of Documents with pageContent and metadata
    return resultsQdrant.map((result: any) => {
      return new Document({
        pageContent: result.payload.page_content,
        metadata: result.payload.metadata,
      });
    });
  }
}

export { CustomQdrant };
```


The main point in the fix is by replacing `C` with underscore `_`:

```js

return new Document({
        pageContent: result.payload.page_content,
        metadata: result.payload.metadata,
      });
```

**Comment by neebdev** [comment]
If you are populating the collection using Langchain python library then obviously it will not be retrievable by the JavaScript version. Why are you expecting them to be interchangeable. Python lib populates the page content as `page_content` while js looks for `pageContent`.

**Comment by amrohendawi** [comment]
> If you are populating the collection using Langchain python library then obviously it will not be retrievable by the JavaScript version. Why are you expecting them to be interchangeable. Python lib populates the page content as `page_content` while js looks for `pageContent`.

Fair question.

I didn't have this issue with pinecone pushing to the vector database from python and retrieving with javascript.
Most developers will use the python library for preprocessing the dataset and pushing it to the vector database, and they would only use the javascript library for inference reasons.
That's why it should be interchangeable and it is so with other vector database solutions.

Furthermore, since I am using the Document class to encapsulate the dataset before pushing it to the vector database, then retrieving data should be interoperable and language-agnostic.

**Comment by abdulmansour** [comment]
Has this issue been addressed? At least have parameter that allows the developer to specify the "page_content" field to be either "page_content" or "pageContent"

**Comment by abdulmansour** [comment]
I've identified a fix for this issue:

can simply set the

**Comment by abdulmansour** [comment]
I've found a fix for this issue by setting the `content_payload_key="pageContent"`

```
Qdrant.from_documents(
  docs,
  embeddings,
  url=os.getenv('QDRANT_URL'),
  prefer_grpc=True,
  api_key=os.getenv('QDRANT_API_KEY'),
  collection_name=self.vectorstore_name,
  content_payload_key="pageContent"
)
```

This will save your content with key of pageContent instead of page_content

**Comment by maguru-louis** [comment]
Has this issue been resolved?

**Comment by 1951FDG** [comment]
Just ran into this now, this issue has not been solved, please re-open!

**Comment by 1951FDG** [comment]
similaritySearchVectorWithScore seems to use `payload.content` instead of `payload.page_content`, what a mess...

https://github.com/langchain-ai/langchainjs/blob/8262ae91553b1ac478c1bd1ee4c7561237d081f5/libs/langchain-community/src/vectorstores/qdrant.ts#L185C22-L185C25

**Comment by 1951FDG** [comment]
There is another workaround, if you haven't yet created the collections or can create them again from scratch;

In Python code specify,

```python
CONTENT_KEY = "content"
METADATA_KEY = "metadata"
```

Specify payload keys parameters for all invocations of Qdrant e.g., `Qdrant(`, `Qdrant.from_texts(`, `Qdrant.from_documents(`

```python
content_payload_key=CONTENT_KEY,
metadata_payload_key=METADATA_KEY
```

https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/vectorstores/qdrant.py

**Comment by jstjoe** [comment]
> If you are populating the collection using Langchain python library then obviously it will not be retrievable by the JavaScript version. Why are you expecting them to be interchangeable. Python lib populates the page content as page_content while js looks for pageContent.

From an outsider's perspective this issue seems like a very strange design decision for a cross-platform library. The whole reason I want to use Langchain is modularity. I want to be able to run experiments and build pipelines in Python and then use them from TypeScript. So I went to find the library / SDK with the best support across both and the most integrations so I don't paint myself into a corner.

But now you're saying it's unreasonable to assume that content - _not applications or APIs but content_ - created from Langchain in one runtime is compatible with content created from Langchain from another runtime? Is that right?

**@neebdev Could you or someone from the project please confirm if that is a principle of this project that is durable?** It would help us users make an informed decision about the tooling we choose. 

I hope you can see how this as a principle will significantly diminish the value of LangChain to many of us who have come to love the framework and contribute our time to trying to help improve it however we can, despite some of its idiosyncrasies.

Thank you as always. I understand if that's the direction Langchain chooses to go, but I would like to know.

**Comment by jacoblee93** [comment]
This should be fixed and work across the Python and JS libs.

**Comment by epicshardz** [comment]
FYI, this is how I got it to work for me
`    const vectorStore = await QdrantVectorStore.fromExistingCollection(
        new OpenAIEmbeddings(),
        {
            url: process.env.QDRANT_HOST,
            apiKey: process.env.QDRANT_API_KEY,
            collectionName: "mycollection",
            contentPayloadKey: 'page_content'
        }
    );`
