### ISSUE TITLE
Preview the output prompt

### ISSUE THREAD

**Issue by jcheese1** [langchain-ai/langchainjs#241]
Is there a way to preview the last output prompt before actually calling the LLM?

**Comment by jacobrosenthal** [comment]
Not sure if this is what you want, but have you seen the callbackManager? it allows you to to see log or do something with the prompt.

```
  const callbackManager = CallbackManager.fromHandlers({
    async handleLLMStart(_llm: { name: string }, prompts: string[]) {
        console.log(JSON.stringify(prompts, null, 2))
    },
  })

  const model = new OpenAI({
    openAIApiKey: process.env.OPEN_API_KEY,
    temperature: 0,
    verbose: !isProd,
    callbackManager: callbackManager,
  })
```

You cant hook or change it there. For youd have to fork a chain or agent or whatever and then can hook something like `_call` usually that way
