### ISSUE TITLE
Inconsistent format of $JSON_BLOB  

### ISSUE THREAD

**Issue by patrickcmbooth** [langchain-ai/langchainjs#2455]
Sometimes the json blob works as expected  
``` 
{
  "action": "search",
  "action_input": "current weather in NYC"
}
```
Remaining text .....

But oftentimes it comes out like this

``` 
{
  "action": "search",
  "action_input": "current weather in NYC"
}
```Remaining text .....

Which mess up the rendering on the client side when using with react markdown. Any remedy?

**Comment by jacoblee93** [comment]
Would you be able to use the OpenAI functions agent instead?

https://js.langchain.com/docs/modules/agents/agent_types/openai_functions_agent
