### ISSUE TITLE
Possible mistake in the documentation | Document Transformers | Mozilla Readability

### ISSUE THREAD

**Issue by chris-miaskowski** [langchain-ai/langchainjs#2467]
Hi folks, I've been playing with the framework, and while following the [documentation on retrievers](https://js.langchain.com/docs/modules/data_connection/document_transformers/integrations/mozilla_readability) I found the following case.

You mention in the docs to first load the page with `cheerio`:

```typescript
const loader = new CheerioWebBaseLoader(
  "https://news.ycombinator.com/item?id=34817881"
);

const docs = await loader.load();

const splitter = RecursiveCharacterTextSplitter.fromLanguage("html");
const transformer = new MozillaReadabilityTransformer();

const sequence = splitter.pipe(transformer);

const newDocuments = await sequence.invoke(docs);

console.log(newDocuments);
```

However, your implementation of the `CheerioWebBaseLoader` takes the page content and turns it into text (therefore stripping HTML tags)

```typescript
 async load() {
        const $ = await this.scrape();
        const text = $(this.selector).text();
        const metadata = { source: this.webPath };
        return [new Document({ pageContent: text, metadata })];
    }
```

I wonder if this is indeed what you've intended to do and from the code in the documentation, I figured it might not be.

You are using `const transformer = new MozillaReadabilityTransformer();` to later retrieve the page's content, but Mozilla readability requires access to the HTML structure (e.g. `article` tag). However, given that the previous step stripped all HTML the reader won't be able to function properly.

I found that writing a custom loader that extends yours helps a bit. Here is the class I use:

```typescript
class CustomCheerioWebBaseLoader extends CheerioWebBaseLoader {
  /**
   * Extracts the text content from the loaded document using the selector
   * and creates a Document instance with the extracted text and metadata.
   * It returns an array of Document instances.
   * @returns A Promise that resolves to an array of Document instances.
   */
  async loadHtml(): Promise<Document[]> {
    const $ = await this.scrape();
    const html = $(this.selector).html() || "";
    const metadata = { source: this.webPath };
    return [new Document({ pageContent: html, metadata })];
  }
}
```

However, I think the code in the documentation will still produce suboptimal results. The code uses `const splitter = RecursiveCharacterTextSplitter.fromLanguage("html");` and the order of processing the document is:
1. Split
2. Process with readability

But when the split happens first it leaves a lot of noise (HTML data irrelevant to the actual loaded article content). Also, it means that readability will try to analyze chunks of HTML and I found it doesn't handle this well.

Hope those thoughts will be useful, cheers!

**Comment by jacoblee93** [comment]
Ah interesting. Likely an oversight, thanks!
