### ISSUE TITLE
PGVector integration for Langchain JS similar to Python library

### ISSUE THREAD

**Issue by rahulnyk** [langchain-ai/langchainjs#2478]
Hey Guys, 
Any roadmap for support PGVector integration for the javascript lib similar to the Python lib.
Lack of this integration is quite annoying. 

One workaround is to use Supabase vector store, but frankly the Supabase integration is quite hackie. It is a considerable deviation from the python version of the PG Vector store even in terms of the table structure. It take quite a bit of work to move from python PGVector to Supabase client. 

In my opinion, the Supabase integration doesn't work well even with Python library. 

Moreover if I don't want to use Supabase, I don't see a good workaround. 

Would be grateful if this can be supported soon. 

Thanks :)

**Comment by rahulnyk** [comment]
Would really appreciate if this can be expedited. 
Dealing with PGVector with langchain is proving to be hell. 
The python version of the PGvector follows a certain table schema. I populated my vector store using python. So my embedding table follows this schema. 
The Supabase client integration works with a different embedding table schema, and it is quite difficult to set it up with the python version of the embedding table schema (at least I am not able to do it)
The typeORM adapter for JS library tries to follow yet another schema different from any of the above. Here you can't even specify the column names without some serious hacking. 

It would be very helpful if the embedding table schema can be maintained the same for better portability. 
Also can you support custom schema definition with the TypeORM adapter.

**Comment by bracesproul** [comment]
Taking this one on!

**Comment by rahulnyk** [comment]
Thanks @bracesproul
