### ISSUE TITLE
Feature: Set SupabaseVectorStore Schema

### ISSUE THREAD

**Issue by garysm** [langchain-ai/langchainjs#2517]
When creating a SupabaseClient from a custom schema:

```ts
const supabaseAdminClient = createClient<DocsDatabase>(
    SUPABASE_URL,
    SUPABASE_SERVICE_ROLE_KEY,
    {
      db: { schema: "docs" },
    },
  );
```

I am unable to create a `SupabaseVectorStore` from LangChain:

```ts
const supabaseVectorStore = new SupabaseVectorStore(embeddings, {
    client: supabaseAdminClient,
    tableName: "documents",
  });
```
Error: 

`Type "SupabaseClient<DocsDatabase, "docs", { Tables: ... " is not assignable to type 'SupabaseClient<any, "public", any>.
  Type "docs" is not assignable to type '"public" `

I would like to have the ability to specify a schema other than "public" for the Supabase Client.  This is important for Security/Customization purposes.

**Comment by jacoblee93** [comment]
That's odd - we type it as just SupabaseClient. If you cast it to `any` does it work? (of course long-term we'd want to fix)

**Comment by garysm** [comment]
Yes, this issue is still relevant to the current version.
