### ISSUE TITLE
Cannot read properties of undefined (reading 'query') while trying to use ConversationalRetrievalQAChain 

### ISSUE THREAD

**Issue by berkingurcan** [langchain-ai/langchainjs#2526]
Hello, I am encountering an issue while using the ConversationalRetrievalQAChain. When attempting to retrieve an answer with Conversational Retrieval QA Chain, I am encountering the following error:

```
error Error [TypeError]: Cannot read properties of undefined (reading 'query')
    at PineconeStore.similaritySearchVectorWithScore (webpack-internal:///(sc_server)/./node_modules/.pnpm/langchain@0.0.141_@pinecone-database+pinecone@0.1.6/node_modules/langchain/dist/vectorstores/pinecone.js:154:50)
```

Here is my code:
```ts
const model = new ChatOpenAI({
    temperature: 0.8
  })

const pinecone = new PineconeClient();      
await pinecone.init({      
	environment: process.env.PINECONE_ENVIRONMENT as string,      
	apiKey: process.env.PINECONE_API_KEY as string,      
});      
  
const index = pinecone.Index("mango");
const indexStats = await index.describeIndexStats({
  describeIndexStatsRequest: {
    filter: {},
  },
});

const embedding = new OpenAIEmbeddings({
    openAIApiKey: process.env.OPENAI_API_KEY
})

const queryEmbedding = await embedding.embedQuery(currentMessageContent)

const vectorStore = await PineconeStore.fromExistingIndex(
    embedding,
    {index}
)

if (3>1) {
  const chain = ConversationalRetrievalQAChain.fromLLM(
    model,
    vectorStore.asRetriever(),
  );

  const res = await chain.stream({ 
    question: currentMessageContent,
    chat_history: formattedPreviousMessages.join('\n'),
  });
  console.log(res)

  return new StreamingTextResponse(res)
}
```

I have also looked [this issue](https://github.com/hwchase17/langchainjs/issues/2304) but no bueno.

**Steps to Reproduce:**
You can run the project from [here](https://github.com/berkingurcan/eip-uzmani-client). It is also template from [this repo](https://github.com/vercel-labs/ai-chatbot). However you need your own Pinecone index.

**Expected Behavior:**
Retrieve related answer from the index.

**Actual Behavior:**
Getting this error:
```
error Error [TypeError]: Cannot read properties of undefined (reading 'query')
    at PineconeStore.similaritySearchVectorWithScore (webpack-internal:///(sc_server)/./node_modules/.pnpm/langchain@0.0.141_@pinecone-database+pinecone@0.1.6/node_modules/langchain/dist/vectorstores/pinecone.js:154:50)
```

Thank you for your assistance in resolving this issue.

**Comment by berkingurcan** [comment]
@dosu-bot

It can be related to initialization of the ```PineconeStore```. However when I log index and index stats like this:

```
const index = pinecone.Index("mango");
  const indexStats = await index.describeIndexStats({
    describeIndexStatsRequest: {
      filter: {},
    },
  });
  ```

It successfully logs index info. So, I am almost sure about I initialized ```PineconeStore```successfully.

**Comment by berkingurcan** [comment]
@dosu-bot

Still same error. It does not help.

**Comment by EthanDev** [comment]
I looks like the implementation of the Langchain ConversationalRetrievalQAChain is not correct and needs to accept a query parameter.

**Comment by EthanDev** [comment]
@berkingurcan were you able to resolve this in any way. I am going through the same issues as you.

**Comment by berkingurcan** [comment]
> @berkingurcan were you able to resolve this in any way. I am going through the same issues as you.

Unfortunately, I could not.
