### ISSUE TITLE
 langchain 's huggerfaceTransformer  support local model deployment instead of depending on huggerface's API

### ISSUE THREAD

**Issue by helxsz** [langchain-ai/langchainjs#2527]
huggerFace transformer is depending on "@xenova/transformers", @xenova/transformers's current implementation mainly is based on huggerface 's API.

however the connection to huggerface is always interrupted, so there is another way to deploy the model locally.   

```
import { pipeline, env } from '@xenova/transformers';
env.localModelPath = 'local model path';
env.allowRemoteModels = false;
env.backends.onnx.wasm.wasmPaths = '';
```

so wondering can langchain 's API extend more to support local model deployment

**Comment by jacoblee93** [comment]
Yes this would be great - will try to get to it this week!
