### ISSUE TITLE
Breaking change between 0.0.112 and 0.0.144 "TypeError: this._vectorstoreType is not a function"

### ISSUE THREAD

**Issue by titocosta** [langchain-ai/langchainjs#2533]
So many breaking changes every time I try to upgrade...

How could I start addressing this error that popped up or what is the last version that didn't introduce breaking changes in vector stores?

**Comment by jacoblee93** [comment]
Hey sorry you're running into this - can you share your code? `_vectorstoreType` wasn't removed or anything like that.
