### ISSUE TITLE
Implement Cloudflare Workers KV as a BaseCache

### ISSUE THREAD

**Issue by EvanPiro** [langchain-ai/langchainjs#2535]
To support caching on Cloudflare, implement Cloudflare Workers KV to extend `BaseCache` wrapping a `KVNamespace` instance and exposing the required functions.

**Comment by jacoblee93** [comment]
This might be nice to add as a `BaseStore`:

https://github.com/hwchase17/langchainjs/blob/main/langchain/src/schema/storage.ts#L6
