### ISSUE TITLE
How to pass a password for encrypted PDF files

### ISSUE THREAD

**Issue by amitkarn** [langchain-ai/langchainjs#2552]
When trying to load a PDF file using `PDFLoader` throws an error `PasswordException: No password given`.
I wonder there is any way right now to pass `password` as additional parameter

**Comment by shashankshrivastava1** [comment]
You can use PyPDFLoader

`from langchain.document_loaders import PyPDFLoader
loader = PyPDFLoader(file_path="path/to/file",password="your password")
file = loader.load()`

**Comment by shashankshrivastava1** [comment]
You can use PyPDFLoader

```
from langchain.document_loaders import PyPDFLoader
loader = PyPDFLoader(file_path="path/to/file",password="your password")
file = loader.load()
```
