### ISSUE TITLE
OpenAI import fails in Vercel deployment `Cannot find module '/var/task/node_modules/openai/_shims/agent-node.mjs'` 

### ISSUE THREAD

**Issue by raphaelmsr** [langchain-ai/langchainjs#2558]
Using NextJS 13 without appDir, I just installed LangchainJS for use in my tRPC back-end
In local everything works like a charm.

After deploying on Vercel as a Serverless function, I have this strange error 

`Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/var/task/node_modules/openai/_shims/agent-node.mjs' imported from /var/task/node_modules/openai/core.mjs
    at new NodeError (node:internal/errors:405:5)
    at finalizeResolution (node:internal/modules/esm/resolve:329:11)
    at moduleResolve (node:internal/modules/esm/resolve:992:10)
    at moduleResolveWithNodePath (node:internal/modules/esm/resolve:936:12)
    at defaultResolve (node:internal/modules/esm/resolve:1178:79)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:835:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}`

I couldn't find any issue mentioning this error anywhere, hope this is the right place to open an issue !
Thanks in advance

**Comment by jacoblee93** [comment]
Hey @raphaelmsr, we recently upgraded to OpenAI's v4 SDK under the hood - does downgrading to 0.0.140 fix it?

https://github.com/hwchase17/langchainjs/releases/tag/0.0.140

Also, in the short term, things should work in Next.js apps WITH the app directory if that's an option for you:

https://github.com/langchain-ai/langchain-nextjs-template/blob/main/package.json

**Comment by raphaelmsr** [comment]
Hey @jacoblee93 ! thanks for the quick reply; will try downgrading !
I am using the T3 stack framework which is not compatible with appDir for now, but looking forward to it tho 😊 

EDIT : IT WORKED 😱 Can't believe I spent the day on this haha Thanks a million for such a quick reply
I have a few questions 
1. what do I miss with OpenAI v4's SDK ?
2. what do I miss with Langchain > 0.0.140
3. What's happening 😭 What is this bug even about
Thanks again!!

**Comment by jacoblee93** [comment]
Glad to hear it! 

1. The transition to OpenAI v4 should have been invisible, so you're not missing any additional functionality there
2. A few nice features - I'll open an issue with OpenAI to try to get to the root of why this is happening so that you can upgrade!
3. Will investigate and report back but it appears to be from here:

https://github.com/openai/openai-node/blob/331eb4e27615cc83a23596f2b74ec2721453938f/src/_shims/agent-node.ts#L4

**Comment by jacoblee93** [comment]
Opened an issue on OpenAI as I was able to repro with their SDK alone. Will leave this open until it's patched there.

Thanks again for the report!

**Comment by raphaelmsr** [comment]
Thanks for following up and opening tickets on the OpenAI repo! Will follow so I can finally update 😊

**Comment by jacoblee93** [comment]
@raphaelmsr I downgraded the OpenAI version in 0.0.146 so you should be able to upgrade to that. 

Closing this for now but reopen if you encounter trouble again.

**Comment by raphaelmsr** [comment]
Thanks for the update !
