### ISSUE TITLE
Add support for Vertex AI Model Garden / Custom Models

### ISSUE THREAD

**Issue by afirstenberg** [langchain-ai/langchainjs#2562]
See langchain-ai/langchain#8850 and langchain-ai/langchain#9367 and will talk to @lkuligin about their implementation.

The general idea will be to provide a standard way to either access instances of these models at a designated endpoint directly, or create a subclass that can do so. (The request and response format have a standard, but it is a vague standard in some places.)

**Comment by jacoblee93** [comment]
Would be great - I think this would likely look similar to SageMaker with an adapter class for different models?

https://github.com/langchain-ai/langchainjs/blob/main/langchain/src/llms/sagemaker_endpoint.ts#L35

**Comment by afirstenberg** [comment]
Yup, that's along the lines of what I was thinking (possibly with some specific subclasses for popular or well-advertised models).

**Comment by afirstenberg** [comment]
This should be left open. The issue is still valid and we'll be evaluating the state of things once we see what changes Gemini brings.

**Comment by AInoob** [comment]
Hi @afirstenberg, [Gemini API](https://cloud.google.com/blog/products/ai-machine-learning/gemini-support-on-vertex-ai) is out, any estimate on when langchainjs will support Gemini?

**Comment by afirstenberg** [comment]
> Hi @afirstenberg, [Gemini API](https://cloud.google.com/blog/products/ai-machine-learning/gemini-support-on-vertex-ai) is out, any estimate on when langchainjs will support Gemini?

#3621 Added integration for the Google AI Studio version of Gemini and that will be in the next release. (Thanks to @alx13 for that work!)

We're currently discussing the best way to implement it for Vertex AI. If I'm working on it, It'll be this weekend.

**Comment by Storkki** [comment]
@jacoblee93 Is there some news about how to use ChatVertexAI (or maybe VertexAI) for models on custom endpoint or for models that has other publisher than 'google'

**Comment by afirstenberg** [comment]
The most accurate news I can share at the moment is "I'm actively working on it". {:
Hoping to have a branch for folks to at least start looking at by the end of the week.

You specified two requirements here - exactly which models are you looking to use, those available with the "Model-as-a-Service" that Vertex is offering for Claude and Llama and some others? Or those from your model registry that you've deployed to your own endpoint?

**Comment by Storkki** [comment]
To be clearly, i need to use models that are available in my gcp project (using endpoints or publisher url). For example, i want to use LLaMa (which is on endpointId) and Claude (claude-3-5-sonnet@20240620) in Langchain VertexAI.

Endpoints that i use for api calls:
```js
`projects/${projectId}/locations/${location}/endpoints/${endpointId}`
`projects/${projectId}/locations/${location}/publishers/${publisher}/models/${model}`;
```

**Comment by afirstenberg** [comment]
Got it. Thanks.
I'm focusing on the `projects.locations.publishers.models` first and then `projects.locations.endpoints`.
My goal, however, is to make it relatively easy to add more once some are in place.

Still hoping to be able to show something by end of week.

**Comment by Storkki** [comment]
Thank you! Good luck)

**Comment by Storkki** [comment]
@afirstenberg Hi, are there any updates?

**Comment by afirstenberg** [comment]
@Storkki - This is still very much work in progress, but you can see roughly where this will be going with #6999 

Hopefully I can get anthropic, at least, completed and tested in short order and we can get this merged. And then move on to the next model to support. {:

**Comment by Storkki** [comment]
@afirstenberg Thank you for your fantastic work! 

Maybe you know Is there any plan to support self-hosted models through endpoints/modelEndpointId?

**Comment by afirstenberg** [comment]
@Storkki - That is the plan! The changes put in place for this should make Vertex endpoints easier to support.
