### ISSUE TITLE
Design Question: feasibility of other prompt loaders? (Specifically for Google's Maker Suite)

### ISSUE THREAD

**Issue by afirstenberg** [langchain-ai/langchainjs#2564]
Google's Maker Suite allows you to build prompt templates (including model details and prompt variables) and save them to Google Drive. It would be useful to be able to load these files directly.

The `loadPrompt()` function, however, only seems to support the LangChain hub and the local file system. And it only seems to load the template itself. Are there thoughts about reasonable ways to extend this loader? Or would it make sense to have a specialty loader that can return the template, return a new model, or return a new LLMChain with both of these?

Thoughts, @jacoblee93?

**Comment by jacoblee93** [comment]
We've actually deprecated the `loadPrompt` method in favor of a new hub:

https://docs.smith.langchain.com/category/hub

We could certainly have other options though that serialize to LangChain prompts!

**Comment by afirstenberg** [comment]
Given how specific it is, would it make sense to include it as part of LangChain (and, if so, under what module? Since it clearly doesn't make sense at the top level like `hub` is), or as a completely separate package which has methods with a similar signature?

And the FAQ for hubs says "Hub currently only supports LangChain prompt objects. We are working on adding support for more!" Are the plans to include other configuration information (model used, temp, etc), or something else?

**Comment by afirstenberg** [comment]
This was implemented in #2733 and merged. Closing
