### ISSUE TITLE
ConversationalRetrievalQAChain vs loadQAStuffChain

### ISSUE THREAD

**Issue by codasana** [langchain-ai/langchainjs#2566]
I'm creating a QnA chat with a document. Can you explain the difference between ConversationalRetrievalQAChain vs loadQAStuffChain?

**Comment by seyfer** [comment]
btw, I am looking for
`from langchain.chains.qa_with_sources import load_qa_with_sources_chain`

that does exist in Python lib but does not exist in the Node version yet.

The list of existing Node chains is there: https://js.langchain.com/docs/api/chains/
The closest I have found is `loadQAChain` https://js.langchain.com/docs/api/chains/functions/loadQAChain
but it does not output sources.

is it planned to add `loadQAWithSourcesChain` present in Python to Node vestion as well?

**Comment by seyfer** [comment]
I have found an example here https://js.langchain.com/docs/modules/chains/popular/vector_db_qa/#return-source-documents

that is an example
```
const chain = RetrievalQAChain.fromLLM(model, vectorStore.asRetriever(), {
  returnSourceDocuments: true, // Can also be passed into the constructor
});
```

but it is not the same as `load_qa_with_sources_chain`

**Comment by seyfer** [comment]
if `loadQAWithSourcesChain` was added to the Node version, this is great, thanks!
