### ISSUE TITLE
Can not access vectors inserted by python library

### ISSUE THREAD

**Issue by coralexbadea** [langchain-ai/langchainjs#2574]
I added vectors inside my pinecone DB and I can retrieve them in python the entries are the basic Document type from python langchain.schema.document :
```
 class Document(Serializable):
    """Class for storing a piece of text and associated metadata."""

    page_content: str
    """String text."""
    metadata: dict = Field(default_factory=dict)
    """Arbitrary metadata about the page content (e.g., source, relationships to other
        documents, etc.).
    """
```
I can not retrieve them with JS framework.
I tried the following:
```
    const vectorStore = await PineconeStore.fromExistingIndex(embeddings, {
      pineconeIndex: index,
      textKey: "pageContent",
      namespace: env.PINECONE_NAME_SPACE,
    });

    console.log(await vectorStore.similaritySearch("search here",10))

```

What do I do wrong? Is it even possible? Thank you in advance :)

**Comment by jacoblee93** [comment]
What is the error you're getting?

**Comment by coralexbadea** [comment]
it simply does not find the vectors stored by the python framework, there is not error. I suspect that the Document class is different by the "page_content" field in python and "pageContent" in javascript. If I search in JS framework the vectors inserted by JS framework it works. 
It is a cross language functionality that I assumed between the two frameworks. I don't know if it is the case.

**Comment by jacoblee93** [comment]
What happens if you set `textKey: "page_content",`?

**Comment by coralexbadea** [comment]
Still didn't work, if you find a solution please post it here.
