### ISSUE TITLE
Error: Invalid _type: undefined

### ISSUE THREAD

**Issue by EhsanKey** [langchain-ai/langchainjs#2583]
Hello friends
I in my code. I get the following error

```
Error: Invalid _type: undefined
    at loadQAChain (/home/ehsan/dev /unichat-server/node_modules/langchain/dist/chains/question_answering/load.cjs:20:11)
    at Function.fromLLM (/home/ehsan/dev /unichat-server/node_modules/langchain/dist/chains/conversational_retrieval_chain.cjs:181:51)
    at /home/ehsan/dev /unichat-server/src/ai/docs/index.ts:117:50
    at Generator.next (<anonymous>)
    at fulfilled (/home/ehsan/dev /unichat-server/src/ai/docs/index.ts:5:58)
[nodemon] app crashed - waiting for file changes before starting...
```

 ```
   const memory = new BufferMemory({
      chatHistory: new RedisChatMessageHistory({
        sessionId: "test",
        sessionTTL: 300,
        url: "redis://localhost:6379",
      }),
    });

    const humanTemplate = "{input}";
    const humanMessagePrompt =
      HumanMessagePromptTemplate.fromTemplate(humanTemplate);
    const aiMessagePrompt = AIMessagePromptTemplate.fromTemplate(
"i'm chat bot"
    );
  
    const chatPrompt = ChatPromptTemplate.fromPromptMessages([
      aiMessagePrompt,
      humanMessagePrompt,
    ]);
  

    const chain = ConversationalRetrievalQAChain.fromLLM(
      model,
      vectorStore.asRetriever(),{
        memory,
        qaChainOptions: {
          prompt: chatPrompt,
        },
      }
    )
    const res = await chain.call({input: question});
```

**Comment by jacoblee93** [comment]
See this section of the docs:

https://js.langchain.com/docs/modules/chains/popular/chat_vector_db#built-in-memory

**Comment by EhsanKey** [comment]
> _🤖_
> 
> Hello,
> 
> The error "Invalid _type: undefined" you're encountering is likely due to the `ConversationalRetrievalQAChain.fromLLM` method expecting an instance of a language model (LLM) as its first argument, but it's receiving an instance of `ChatOpenAI` instead.
> 
> In your code, you're calling `ConversationalRetrievalQAChain.fromLLM` with `model` as the first argument. If `model` is an instance of `ChatOpenAI`, it will cause the "Invalid _type: undefined" error because `ChatOpenAI` is not a subclass of `BaseLanguageModel`.
> 
> To fix this issue, you should replace the `ChatOpenAI` instances with instances of a language model class that is a subclass of `BaseLanguageModel`. For example, you can create an instance of `OpenAI` like this: `const model = new OpenAI({ modelName: "text-ada-001" });` and then pass this instance to the `ConversationalRetrievalQAChain.fromLLM` method.
> 
> Here is the corrected code:
> 
> ```js
> const model = new OpenAI({ modelName: "text-ada-001" });
> 
> const chain = ConversationalRetrievalQAChain.fromLLM(
>   model,
>   vectorStore.asRetriever(),{
>     memory,
>     qaChainOptions: {
>       prompt: chatPrompt,
>     },
>   }
> )
> const res = await chain.call({input: question});
> ```
> 
> For more information, you can refer to the following sources:
> 
> * [examples/src/chains/conversational_qa_built_in_memory.ts](https://github.com/langchain-ai/langchainjs/blob/-/examples/src/chains/conversational_qa_built_in_memory.ts)
> * [langchain/src/chains/tests/conversational_retrieval_chain.int.test.ts](https://github.com/langchain-ai/langchainjs/blob/-/langchain/src/chains/tests/conversational_retrieval_chain.int.test.ts)
> * [langchain/src/chains/conversational_retrieval_chain.ts](https://github.com/langchain-ai/langchainjs/blob/-/langchain/src/chains/conversational_retrieval_chain.ts)
> 
> I hope this helps! Let me know if you have any other questions.
> 
> ## Sources
> * [[ERROR] : Invalid _type: undefined](https://github.com/langchain-ai/langchainjs/issues/1355)
> * [Conversational Retrieval Agents | TypeError: llm._modelType is not a function](https://github.com/langchain-ai/langchainjs/issues/2171)
> * [New version lacks backwards compatibility for externally passing chat_history to conversational retrieval chain](https://github.com/langchain-ai/langchainjs/issues/2029)
> * [examples/src/chains/conversational_qa_built_in_memory.ts](https://github.com/langchain-ai/langchainjs/blob/-/examples/src/chains/conversational_qa_built_in_memory.ts)
> * [langchain/src/chains/tests/conversational_retrieval_chain.int.test.ts](https://github.com/langchain-ai/langchainjs/blob/-/langchain/src/chains/tests/conversational_retrieval_chain.int.test.ts)
> * [langchain/src/chains/conversational_retrieval_chain.ts](https://github.com/langchain-ai/langchainjs/blob/-/langchain/src/chains/conversational_retrieval_chain.ts)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

I think my code is fine from this perspective, but my issue hasn't been resolved yet.

**Comment by EhsanKey** [comment]
> See this section of the docs:
> 
> https://js.langchain.com/docs/modules/chains/popular/chat_vector_db#built-in-memory

It still gives an error... 😅🫠

**Comment by jacoblee93** [comment]
What did you try?

**Comment by EhsanKey** [comment]
> What did you try?

I have documented the actions I've taken in the following file. I would appreciate it if you could take a look.

[GitHub File Link](https://github.com/EhsanKey/langchain__/blob/main/index.tsx)

**Comment by Julian-AT** [comment]
Cheers. I'm facing the same issue. Has this been resolved yet?

**Comment by Julian-AT** [comment]
Hi again. Sorry for the short timespan of comments ^^

I think I found the answer to this issue if you are still interested.

```const chain = ConversationalRetrievalQAChain.fromLLM(
      model,
      vectorStore.asRetriever(),
      {
        returnSourceDocuments: false,
        verbose: true,
        memory: memory,
        qaChainOptions: {
          type: 'stuff',
          prompt
        }
      }
    )
```
    
Setting the `type` property in `qaChainOptions` seems to fix this issue.

You can choose multiple values for this field but I do not know what they do

<img width="465" alt="image" src="https://github.com/langchain-ai/langchainjs/assets/70039325/0ef7519c-6f83-4524-9e31-3a9c50a5362a">

Hope this helps someone :)

**Comment by EhsanKey** [comment]
Thanks, bro!
Thanks for the guidance and for sharing your comment.
