### ISSUE TITLE
After updating to version 0.0.146, it's not working on AWS Lambda and is throwing an error.

### ISSUE THREAD

**Issue by Ehzuiq** [langchain-ai/langchainjs#2588]
After updating to version 0.0.146, it's not working on AWS Lambda and is throwing an error.

`{
  "errorType": "Error",
  "errorMessage": "ENOENT: no such file or directory, open './package.json'",
  "trace": [
    "Error: ENOENT: no such file or directory, open './package.json'",
    "    at Object.openSync (node:fs:603:3)",
    "    at Object.readFileSync (node:fs:471:35)",
    "    at Object.<anonymous> (/opt/node_modules/@pinecone-database/pinecone/dist/utils/user-agent.js:29:33)",
    "    at Module._compile (node:internal/modules/cjs/loader:1256:14)",
    "    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)",
    "    at Module.load (node:internal/modules/cjs/loader:1119:32)",
    "    at Module._load (node:internal/modules/cjs/loader:960:12)",
    "    at Module.require (node:internal/modules/cjs/loader:1143:19)",
    "    at require (node:internal/modules/cjs/helpers:121:18)",
    "    at Object.<anonymous> (/opt/node_modules/@pinecone-database/pinecone/dist/utils/index.js:8:20)"
  ]
}`

**Comment by jacoblee93** [comment]
Can you share how you're importing LangChain in your code?

We removed the default entrypoint (it had a logged deprecation notice since 0.0.52)

**Comment by Ehzuiq** [comment]
The problem was caused by upgrading Pinecone. Reverting to version '0.1.6' fixed the problem.

**Comment by jacoblee93** [comment]
Odd - might be good to open an issue on them with the version you updated to?
