### ISSUE TITLE
Add support for Vertex AI Generative AI streaming response

### ISSUE THREAD

**Issue by afirstenberg** [langchain-ai/langchainjs#2594]
REST responses can now provide a stream tokens as they are generated. (See https://cloud.google.com/vertex-ai/docs/generative-ai/learn/streaming#text)

This involves:
- A JSON reply with the contents of the response being in an array, and the objects in this array streamed out
- We will need something that can take the streamed JSON and process the relevant objects as they come in
  - Perhaps something like https://www.npmjs.com/package/stream-json
  - However... this means another (optionally) dependent package

**Comment by jacoblee93** [comment]
Yes this would be great! 

Happy to have a look this week.

**Comment by iamvishnusankar** [comment]
Any updates on this?
