### ISSUE TITLE
ConversationalRetrievalQAChain cannot use the ChatBaiduWenxin model, will it consider compatibility in the future?

### ISSUE THREAD

**Issue by zandko** [langchain-ai/langchainjs#2597]
<img width="1917" alt="IMG-2023-09-11-14 20 20@2x" src="https://github.com/langchain-ai/langchainjs/assets/37948383/a1e525dc-0eb1-4a57-a86a-661d71e65d60">

**Comment by jacoblee93** [comment]
Hey @zandko, you can recreate the same functionality with runnables:

https://js.langchain.com/docs/expression_language/cookbook#conversational-retrieval-chain

You can see where to pass in/modify the prompt. We'll be prioritizing this approach going forwards.
