### ISSUE TITLE
'Missing value for input input' error when using MultiRetrievalQAChain.fromLLMAndRetrievers

### ISSUE THREAD

**Issue by evenfrost** [langchain-ai/langchainjs#2611]
Hello,

My `langchain` version is `0.0.147`.

I'm using a `MultiRetrievalQAChain` chain's `fromLLMAndRetrievers` method with an LLM model, multiple retrievers, and multiple prompts with context for them.

I keep getting the 'Missing value for input input' error however the `input` variable is provided both in templates and as a parameter for the `chain.call` method.

This is the code I'm using that gives the error (all the strings here are replaced with the lorem ipsum data but the actual code is the same):

```ts
import { MultiRetrievalQAChain } from 'langchain/chains';
import { OpenAIEmbeddings } from 'langchain/embeddings/openai';
import { PromptTemplate } from 'langchain/prompts';
import { WeaviateStore } from 'langchain/vectorstores/weaviate';

import { model } from '@/providers/openai';
import { weaviateClient } from '@/providers/weaviate';

const getFirstRetriever = async () => {
  const zendeskTicketStore = await WeaviateStore.fromExistingIndex(new OpenAIEmbeddings(), {
    client: weaviateClient,
    indexName: 'FirstClass',
    textKey: 'text',
  });

  return zendeskTicketStore.asRetriever();
};

const getSecondRetriever = async () => {
  const zendeskTicketStore = await WeaviateStore.fromExistingIndex(new OpenAIEmbeddings(), {
    client: weaviateClient,
    indexName: 'SecondClass',
    textKey: 'text',
  });

  return zendeskTicketStore.asRetriever();
};

const getFirstPrompt = () => {
  const template = `Answer the question given the following contxt:

{context}

Question: {input}`;

  return PromptTemplate.fromTemplate(template);
};

const getSecondPrompt = () => {
  const template = `Answer the question given the following context

{context}

Question: {input}`;

  return PromptTemplate.fromTemplate(template);
};

const run = async (): Promise<void> => {
  const firstRetriever = await getFirstRetriever();
  const secondRetriever = await getSecondRetriever();

  const firstPrompt = getFirstPrompt();
  const secondPrompt = getSecondPrompt();

  const retrieverNames = ['First', 'Second'];

  const retrieverDescriptions = [
    'Good for answering the questions',
    'Good for answering the questions',
  ];

  const retrievers = [
    firstRetriever,
    secondRetriever,
  ];

  const retrieverPrompts = [
    firstPrompt,
    secondPrompt,
  ];

  const chain = MultiRetrievalQAChain.fromLLMAndRetrievers(model, {
    retrievers,
    retrieverNames,
    retrieverDescriptions,
    retrieverPrompts,
  });

  const input = 'What is the weather today?';

  const res = await chain.call({
    input,
  });
};

```

But when I replace the `{input}` placeholder in the templates to e.g. `{query}` and then call the chain with:

```ts
  const res = await chain.call({
    input,
    query: input,
  });
```

it works.

So I wonder if I'm doing something wrong here like messing with/misunderstanding placeholder variables for this chain.

**Comment by jacoblee93** [comment]
It's a bit of an older chain that could use a bit of love - can you pass in `verbose: true` and show the logs that appear?

If you're using LangSmith, a public trace would be helpful too.

My high-level guess without any other information is that you could try changing your custom prompts to use `{question}` as an input variable.

**Comment by evenfrost** [comment]
Hi again,

Sorry for the late reply, but I just retested everything with the `verbose: true` parameter and realized that this is working now with just the `input` placeholder (`query` is not needed anymore). Thanks for the suggestions. I'm closing the issue.
