### ISSUE TITLE
Dependency issues even with 0.0.111 version

### ISSUE THREAD

**Issue by ghostenginesio** [langchain-ai/langchainjs#2616]
"npm install" is working fine without langchain. This is happening for past 3-5 days. 
When I add langchain - 0.0.111 it is breaking. This was working fine earlier. 
I even tried with the latest version 0.0.148 still the same issue. Please help me out. Thanks!

--------------------------------------------------------------------------------------------
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: api@1.0.0
npm ERR! Found: cohere-ai@6.2.2
npm ERR! node_modules/cohere-ai
npm ERR!   peerOptional cohere-ai@"^6.0.0" from chromadb@1.5.8
npm ERR!   node_modules/chromadb
npm ERR!     chromadb@"^1.5.5" from the root project
npm ERR!     peerOptional chromadb@"^1.5.3" from langchain@0.0.111
npm ERR!     node_modules/langchain
npm ERR!       langchain@"^0.0.111" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peerOptional cohere-ai@"^5.0.2" from langchain@0.0.111
npm ERR! node_modules/langchain
npm ERR!   langchain@"^0.0.111" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
--------------------------------------------------------------------------------------------

**Comment by jacoblee93** [comment]
Hey @ghostenginesio, can you try running with `npm install --legacy-peer-deps` for now? We'll aim to resolve this and push a release shortly.

**Comment by jacoblee93** [comment]
Actually, just tried from a fresh project and it looked like `npm install -S langchain` worked for me. Can you try clearing any build caches?

**Comment by ghostenginesio** [comment]
Works fine now. Thanks!
