### ISSUE TITLE
`npm install langchain chromadb openai` not working

### ISSUE THREAD

**Issue by ghostenginesio** [langchain-ai/langchainjs#2617]
[Nodejs App]

Below command is not working
### npm install langchain chromadb openai

```
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: api@1.0.0
npm WARN Found: openai@4.6.0
npm WARN node_modules/openai
npm WARN   openai@"*" from the root project
npm WARN
npm WARN Could not resolve dependency:
npm WARN peerOptional openai@"^3.0.0 | ^4.0.0" from chromadb@1.5.8
npm WARN node_modules/chromadb
npm WARN   chromadb@"*" from the root project
npm WARN   1 more (langchain)
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: api@1.0.0
npm WARN Found: openai@4.6.0
npm WARN node_modules/openai
npm WARN   openai@"*" from the root project
npm WARN
npm WARN Could not resolve dependency:
npm WARN peerOptional openai@"^3.0.0 | ^4.0.0" from chromadb@1.5.8
npm WARN node_modules/chromadb
npm WARN   chromadb@"*" from the root project
npm WARN   1 more (langchain)
npm ERR! code ETARGET
npm ERR! notarget No matching version found for openai@^3.0.0 | ^4.0.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

Thanks for helping out!

**Comment by leetharris** [comment]
Same problem. I have tried every version of OpenAI dependency. There's a fundamental issue with ChromaDB, OpenAI, Cohere, and langchain dependencies.

**Comment by jacoblee93** [comment]
Yeah `openai@"^3.0.0 | ^4.0.0"` isn't a valid resolution for `npm` 

CC @jeffchuber could we patch this? It's been causing issues for some folks. You can use `>=3.0.0` instead.

<img width="1425" alt="Screenshot 2023-09-13 at 10 08 37 AM" src="https://github.com/langchain-ai/langchainjs/assets/6952323/eddb77ad-e676-4cc3-adbd-617dbc3e7bb9">

**Comment by jeffchuber** [comment]
@jacoblee93 yes, fire away

**Comment by jacoblee93** [comment]
Opened https://github.com/chroma-core/chroma/pull/1142 which should fix this longer-term when live!
