### ISSUE TITLE
Support token usage reporting for streaming calls

### ISSUE THREAD

**Issue by giaphiep** [langchain-ai/langchainjs#2623]
```javacript
export const getAnswer = async (input) => {
  const {  question } = input

  const controller = new AbortController();
  
  const streamingModel = new ChatOpenAI({
    modelName: 'gpt-3.5-turbo',
    openAIApiKey: decryptData(openAIApiKey),
    streaming: true,
    maxRetries: 10,
    maxConcurrency: 10,
    callbacks: [
      {
        handleLLMNewToken(token) {
          // send to client        
        },
        handleLLMEnd: async (output) => {
          console.log(output.llmOutput.tokenUsage); <-- Problem: get empty {}
        },
        handleLLMError: async (err) => {
          console.error(err);
        },
      },
    ],
  });

  const vectorStore = await vectorStoreByChatbot();

   const prompt = ChatPromptTemplate.fromPromptMessages([
     SystemMessagePromptTemplate.fromTemplate(
       'The following is a friendly conversation between a human and an AI. The AI is talkative and provides lots of specific details from its context. If the AI does not know the answer to a question, it truthfully says it does not know.'
     ),
     new MessagesPlaceholder('history'),
     HumanMessagePromptTemplate.fromTemplate('{input}'),
   ]);

  
  const memory = new ConversationSummaryBufferMemory({
    llm: streamingModel,
    maxTokenLimit: 1024,
    returnMessages: true,
    memoryKey: 'chat_history',
    outputKey: 'text',
    humanPrefix: 'Customer',
  });
 
  const chain = ConversationalRetrievalQAChain.fromLLM(
    streamingModel,
    vectorStore.asRetriever(),
    {
      memory: memory,
      returnSourceDocuments: true,
      prompt: prompt,
    }
  );

  try {
     await chain.call({
      question: question,
      signal: controller.signal,
    });
  } catch (error) {
    console.log('Ask failed: ' + error);
  }
};
```
above is my code. could u help me check i cant get tokenUsage inside the function handleLLMEnd. i checked log get empty {}

**Comment by jacoblee93** [comment]
Token usage isn't supported like that for streaming requests at the moment - you'd have to use something like https://github.com/openai/tiktoken. 

Will leave this open as a feature request!

**Comment by wlyh514** [comment]
Hello! We are a group of developers that are currently looking into this issue, we're trying to integrate tictoken for token calculation in streaming calls. If you have additional details feel free to post them here!

**Comment by wlyh514** [comment]
Hello @jacoblee93, we are working on this issue and succeeded in implementing token usage support for the ChatOpenAI chat model. We would like to know the scope of this issue, more specifically:
1. Should we add usage report for openai function calling?
2. The OpenAIChat class under llms does not seem to support token counting at all (even for non-streaming calls), should we add token usage support for it?
3. Are there other llms or chat models lacking token usage report functionalities? Should we look into them or delegate them to their maintainers?

**Comment by jacoblee93** [comment]
Wow thank you! Really looking forward to it.

1. Function calling would be nice yes!
2. No worries about `OpenAIChat` - it's soft-deprecated for now
3. If you're willing and able yes folks would appreciate it! But would say it's probably out of scope for this PR, and only to do it if it would help you/people you know about directly.

**Comment by snlamm** [comment]
@wlyh514 was there a regression by any chance recently for runnables?  it seems that when using a runnable `chain.stream()` call, the `handleLLMEnd` output does not include the `llmOutput` object.

**Comment by wlyh514** [comment]
Hi, sorry for the delay, I will look into this issue shortly.

**Comment by wlyh514** [comment]
> @wlyh514 does this work by any chance for runnables? it seems that when using a runnable `chain.stream()` call, the `handleLLMEnd` output does not include the `llmOutput` object.

Hi, according to [this page](https://js.langchain.com/docs/modules/model_io/llms/streaming_llm#using-a-callback-handler), if you want to use callback with stream mode, you should set `streaming: true` when calling the LLM constructor and call `.invoke()` on the chain. 

Like this: 
```typescript
  const prompt = ChatPromptTemplate.fromMessages([
    "human", "Hello!"
  ]);
  const model = new ChatOpenAI({
    streaming: true,
    callbacks: [{
      handleLLMEnd(...args) {console.log(args[0].llmOutput)}  
    }]
  });
  const stringParser = new StringOutputParser();
  const chain = prompt.pipe(model).pipe(stringParser);
  await chain.invoke({});
// {
//    estimatedTokenUsage: { promptTokens: 14, completionTokens: 9, totalTokens: 23 }
//  }
```

Hope this helps!

**Comment by nickwinder** [comment]
@wlyh514 I'm not sure that's true. 
I've been trying `streaming: true` with `invoke()`, but it does not report and usage. 

Reading through the doc, it says that usage reporting is disabled if `streaming` is enabled. 

https://api.js.langchain.com/classes/langchain_openai.OpenAI.html#streaming

**Comment by wlyh514** [comment]
@nickwinder Hi, streaming token counting is currently only implemented for the `ChatOpenAI` chat model, not the `OpenAI` base model.

**Comment by nickwinder** [comment]
@wlyh514 Apologies for the incorrect link. But it seems `ChatOpenAI` is documented with the same limitations. 
https://api.js.langchain.com/classes/langchain_openai.ChatOpenAI.html#streaming

**Comment by wlyh514** [comment]
@nickwinder The documentation for `ChatOpenAI` is not updated, but the code I included above does actually work. I will open a PR to update the documentation later on. Apologies for the confusion.

**Comment by nickwinder** [comment]
Ok thanks. I'll keep digging.
