### ISSUE TITLE
SQL Agent Toolkit without typeorm ?

### ISSUE THREAD

**Issue by aymeric75** [langchain-ai/langchainjs#2636]
Hello,

I am developing a CMS plugin based on VueJS but where Node.js cannot be an option (because it must be all client side), when I use the code from the [basic example](https://js.langchain.com/docs/modules/agents/toolkits/sql) I get an error in the console:
```

Uncaught (in promise) TypeError: connection.driver.options is undefined
create webpack://dev/../../../node_modules/typeorm/browser/entity-manager/EntityManagerFactory.js?:19

```
So, is there a way to create a "datasource" object without using the DataSource class from typeorm?

Thanks

**Comment by aymeric75** [comment]
Thanks for you answer, indeed hard to find an example

**Comment by mauriciocirelli** [comment]
Could be related to #2274

**Comment by aymeric75** [comment]
> Could be related to #2274

Thanks Mauricio, but could you give a minimal example on how you use a custom SqlDatabase (speciaficaly I am not familiar with the Interface "method" that you use). Cheers!

**Comment by mauriciocirelli** [comment]
Hi @aymeric75 

Unfortunately, I could not find a solution without chaning LangChain code.
I had to create custom Agents and toolkits to use another DB driver, instead of typeorm.

**Comment by aymeric75** [comment]
I see, if you could show all the changes you have made to the different file, it would be very useful, also for the community. Thanks

**Comment by mauriciocirelli** [comment]
Hi @aymeric75 

I have not made any changes to LangChain code.
I have just created a new Agent, with a new Prompt and new set of Tools.
