### ISSUE TITLE
Bedrock - ai21.j2-ultra - 400 Bad Request: The model is unsupported for streaming 🐛 

### ISSUE THREAD

**Issue by MironMihnea14** [langchain-ai/langchainjs#2645]
![image](https://github.com/langchain-ai/langchainjs/assets/72500577/f36dcd5b-07f5-4387-9ded-a18bbc168b7d)

Models which do not support streaming are not working. I think this might be caused by the url being hardcoded with '/invoke-with-response-stream'. The endpointUrl field is not helping since it has no effect on the '/invoke-with-response-stream' part of the url. Is there another way to get these models working?

<img width="937" alt="image" src="https://github.com/langchain-ai/langchainjs/assets/72500577/151fa0e2-6dab-4917-bab1-00359146d0ca">

**Comment by MironMihnea14** [comment]
@dosu-bot this just results in the same error as calling .stream()

**Comment by jacoblee93** [comment]
Ah shoot. Yeah we'll have to rework this to have two different implementations then.

Can look this week, thanks for flagging.

**Comment by jacoblee93** [comment]
This is live in 0.0.156!

https://js.langchain.com/docs/modules/model_io/models/llms/integrations/bedrock

Note that some of the peer deps have changed in the latest version - we're no longer using the deprecated ones.
