### ISSUE TITLE
Support Neo4j GraphChainQA and Vector Store

### ISSUE THREAD

**Issue by mcclown** [langchain-ai/langchainjs#2655]
Mainly adding this here as a placeholder, for myself and anyone else who is interested to track. I may be able to find time to work on this but I'm waiting to see how this PR progresses first (https://github.com/langchain-ai/langchainjs/pull/2514), then I'll replicate a similar approach to whatever the accepted approach is.

**Comment by jacoblee93** [comment]
Yes will sort that soon! Apologies for the delay.

**Comment by mcclown** [comment]
As far as I'm aware this has been implemented now. I'll go ahead an close this.
