### ISSUE TITLE
DynamoDBChatMessageHistory not working with initializeAgentExecutorWithOptions

### ISSUE THREAD

**Issue by roshie548** [langchain-ai/langchainjs#2664]
I am getting the following error:

`"output values have 2 keys, you must specify an output key or pass only 1 key as output"`

Code:

```
  const memory = new BufferMemory({
    chatHistory: new DynamoDBChatMessageHistory({
      tableName: "SessionTable",
      partitionKey: "SessionId",
      sessionId: "1233444",
      config: {
        region: "us-west-2",
      },
    }),
    memoryKey: "chat_history",
    returnMessages: true,
  });

  const model = new ChatOpenAI({
    modelName: "gpt-3.5-turbo-0613",
    temperature: 0,
  });

...
  const executor = await initializeAgentExecutorWithOptions(tools, model, {
    agentArgs: {
      prefix: `(Prefix text here).`,
    },
    agentType: "openai-functions",
    returnIntermediateSteps: true,
    verbose: true,
    memory,
  });

  const result = await executor.call({ input: receivedMessage });
```

I have tried specifying `outputKey: 'text'` as well when creating the BufferMemory object, this didn't seem to make a difference though.

**Comment by jacoblee93** [comment]
Removing `returnIntermediateSteps: true,` should fix it, or try setting `outputKey: "output"` which I believe is the default in this case.

Going forwards, we'll be moving docs to show a more compositional and clear approach and deprecate this method. Please reopen if the above doesn't fix the issue.

**Comment by roshie548** [comment]
That worked. Thanks!
