### ISSUE TITLE
Unable to use model `gpt-3.5-turbo-instruct-0914`

### ISSUE THREAD

**Issue by Prince-Mendiratta** [langchain-ai/langchainjs#2669]
Hello team!

I'm unable to use the `gpt-3.5-turbo-instruct-0914` model. This is indeed the latest model for `gpt-3.5-turbo-instruct` but this would have issues with backward compatibility in the future.

Code:
```
import { OpenAI } from "langchain/llms/openai";

export async function instructTest() {
  let gpt3Instruct = new OpenAI({
    temperature: 0.69,
    openAIApiKey: process.env.API_KEY,
    modelName: "gpt-3.5-turbo-instruct-0914",
    topP: 1,
  });

  return await gpt3Instruct.predict("Tell me why is 1+1 = 3?");
}
```

I believe the root cause lies here:
https://github.com/langchain-ai/langchainjs/blob/983135a87c5badc86bb968872c818fce6fa01313/langchain/src/llms/openai.ts#L140-L145

I'd be happy to send in a PR to fix this up!

**Comment by jacoblee93** [comment]
Ah, thank you!
