### ISSUE TITLE
Cannot install latest langchain js package

### ISSUE THREAD

**Issue by drobnikj** [langchain-ai/langchainjs#2673]
I cannot install the latest version because of the dependency tree.

`npm install langchain`

ends up with the error

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: langchain-js-temp@0.0.1
npm ERR! Found: cohere-ai@5.1.0
npm ERR! node_modules/cohere-ai
npm ERR!   peerOptional cohere-ai@"^5.1.0" from chromadb@1.5.10
npm ERR!   node_modules/chromadb
npm ERR!     peerOptional chromadb@"*" from langchain@0.0.151
npm ERR!     node_modules/langchain
npm ERR!       langchain@"*" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peerOptional cohere-ai@">=6.0.0" from langchain@0.0.151
npm ERR! node_modules/langchain
npm ERR!   langchain@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
```

node js: 
v18.15.0
npm:
9.5.0

**Comment by drobnikj** [comment]
This commit breaks https://github.com/chroma-core/chroma/commit/9e05cb372a05b87a6c890e43ee5ebe05c0f20fe6

Can you check @tazarov it here?

**Comment by drobnikj** [comment]
I found the fix is on the way https://github.com/chroma-core/chroma/pull/1156 👍

**Comment by Santy1422** [comment]
> @drobnikj, sorry, I was working late last night, and I did intend to include Cohere 6.x, but for some reason, that slipped. Apologies for the inconvenience :). We're working on a set of tests to validate ecosystem impacts, so hopefully, this is the "last" of these problems :)

Please, with each update the same thing happens, what version of Langchain should we put now?

**Comment by tazarov** [comment]
@jacoblee93, new version's up, mind giving it a go? https://www.npmjs.com/package/chromadb

**Comment by jacoblee93** [comment]
Seems good, thank you!

Hopefully this will be the last time this pops up.
