### ISSUE TITLE
Can you give more support to BaiduWenxin?

### ISSUE THREAD

**Issue by zandko** [langchain-ai/langchainjs#2677]

**Comment by jacoblee93** [comment]
Hey @zandko, what kind of support are you looking for?

CC @ysnows can I assign this to you?

**Comment by ysnows** [comment]
I'd be glad to assist~

**Comment by zandko** [comment]
Practical methods such as function calls

**Comment by cola1158868816** [comment]
> Hey @zandko, what kind of support are you looking for?
> 
> CC @ysnows can I assign this to you?



> Hey @zandko, what kind of support are you looking for?
> 
> CC @ysnows can I assign this to you?

such as wenxinembeddings
