### ISSUE TITLE
ConversationalRetrievalQAChain Templates

### ISSUE THREAD

**Issue by codasana** [langchain-ai/langchainjs#2695]
Consider this code:

```
ConversationalRetrievalQAChain.fromLLM(
    model,
    vectorStore.asRetriever(),
    {
      qaTemplate: QA_PROMPT,
      questionGeneratorChainOptions: { template: CONDENSE_PROMPT },
      returnSourceDocuments: true, // optional
    }
  );
```

Why do we have two templates? qaTemplate and questionGeneratorChainOptions template?

Can you explain the purpose of these two different templates, when and where they are used, along with some examples?

**Comment by msahajwani** [comment]
What is standalone question generation chain and what is QAChain, and what is the difference? Can you explain these terminologies and the reason behind calling them so?

**Comment by msahajwani** [comment]
@dosu-bot 

What is standalone question generation chain and what is QAChain, and what is the difference? Can you explain these terminologies and the reason behind calling them so?
