### ISSUE TITLE
Enhancement Request: Upgrade Filter Functionality in VectorStore Wrapping Elasticsearch

### ISSUE THREAD

**Issue by shotaro427** [langchain-ai/langchainjs#2699]
## Issue Description:
I would like to propose an upgrade to the filter functionality in the VectorStore that wraps Elasticsearch. Specifically, I'd like to make it as flexible as the Python package langchain in terms of filtering capabilities.

## Current State:
Currently, the filtering is limited to using only the "term" operator. This is handled in the function buildMetadataTerms located in src/vectorstores/elasticsearch.ts.

## Requested Feature:
I'd like to request an enhancement that would allow for more flexible filtering options, similar to what is available in the langchain Python package.

## Additional Context:
Is there a specific reason that we are limited to using only the "term" operator? Any context or historical reasons for this limitation would be appreciated as it could inform the development of this feature.

## Next Steps:
If specific implementation strategies are required, please feel free to propose them in the discussion.

**Comment by shotaro427** [comment]
When will this feature be released?
If you are looking for my own commitments, can you give me the contributor rules?

**Comment by dqbd** [comment]
Hey @shotaro427!

Contributions are more than welcome here! Feel free to check out the contributing guidelines here: https://github.com/langchain-ai/langchainjs/blob/main/CONTRIBUTING.md
