### ISSUE TITLE
NextJS fs module not found when using vectorstore chroma

### ISSUE THREAD

**Issue by dsws** [langchain-ai/langchainjs#2701]
NextJS fs module not found when using vectorstore chroma. If anyone knows about it more info here 

Added here for more visibility, copy of https://github.com/langchain-ai/langchain-nextjs-template/issues/5

I'm trying to use the langchain/vectorstores/chroma as a vector store in the POST handler app/api/chat/retrieval/route.ts

 Keep getting this error
 
 error ./node_modules/@visheratin/tokenizers-node/tokenizers_wasm.js:367:14 **Module not found: Can't resolve 'fs'** https://nextjs.org/docs/messages/module-not-found Import trace for requested module: ./node_modules/@visheratin/web-ai-node/node/tokenizer.js ./node_modules/@visheratin/web-ai-node/node/tokenizerLoader.js ./node_modules/@visheratin/web-ai-node/node/index.js ./node_modules/@visheratin/web-ai-node/index.js ./node_modules/chromadb/dist/module/embeddings/WebAIEmbeddingFunction.js ./node_modules/chromadb/dist/module/index.js ./node_modules/langchain/dist/vectorstores/chroma.cjs ./node_modules/langchain/vectorstores/chroma.cjs
 
 
 I tried to load it like this but no luck... keeps throwing this error. Thoughts?
 
    if(typeof window === "undefined") {
      const {Chroma} = require("langchain/vectorstores/chroma");
    }

**Comment by dsws** [comment]
AI answer is not really applicable ... any humans lol?

**Comment by jacoblee93** [comment]
Looks like Chroma is not supported in Edge environments - can you open an issue on them?
