### ISSUE TITLE
Can I add support for closevector-web and closevector-node (a modified version of hnswlib-node)?

### ISSUE THREAD

**Issue by jo32** [langchain-ai/langchainjs#2702]
@jacoblee93 

Hi, I am the author of [CloseVector](https://closevector-docs.getmegaportal.com/blog/release). It's a vector database that runs on a user's device. Users can create, save, and load an index on both the browser and node.js. I'm planning to make a pull request to add support for it.

However, my work is based on hnswlib-node, which you've already supported. I modified hnswlib-node because the underlying C code isn't emscripten and node-gyp compatible (the files cannot be loaded interchangeably).

I have no intention of stealing anyone's work. I am seeking your advice on whether it's suitable to add support for CloseVector in Langchain.JS.

**Comment by jacoblee93** [comment]
Hi! Hnswlib is Apache-2.0 licensed, so as long as you are respecting those terms, that sounds awesome to me!

**Comment by jo32** [comment]
> Hi! Hnswlib is Apache-2.0 licensed, so as long as you are respecting those terms, that sounds awesome to me!

Thank you. Terms will be respected. 🤜🤛

**Comment by ycjcl868** [comment]
Watching!

**Comment by jo32** [comment]
A pull request has been made: https://github.com/langchain-ai/langchainjs/pull/2832
