### ISSUE TITLE
How do you delete Pinecone similaritySearch results? 

### ISSUE THREAD

**Issue by stevenmilstein** [langchain-ai/langchainjs#2704]
Is it possible to delete Pinecone vectors by their auto-generated IDs?

![image](https://github.com/langchain-ai/langchainjs/assets/66161/a98706fa-a86b-4a9e-99bb-b538b95d9cea)

1. [JavaScript Pinecone Delete document]( https://js.langchain.com/docs/modules/data_connection/vectorstores/integrations/pinecone#delete-docs)
The sample code demonstrates how to delete vectors based on the `addDocuments` returned `ids` . The  `similaritySearch` results for `foo:bar` are the first two elements in the `ids`.  If you change the query for a unique value, then those first two `ids` will still be deleted.

2. [Tests](https://github.com/langchain-ai/langchainjs/blob/6e1a112934c2bbeb0bcc610c1a8a5cd2c685c1c7/langchain/src/vectorstores/tests/pinecone.int.test.ts#L86)
The test demonstrates how to delete by a metadata filter but fails because `ids.slice(0, 1)` is undefined. As in the case above, the `id` is known before the delete operation.

3. `k` parameter
Changing the `k` value to another value, for example, 10, results in an array of 10, even if the query is for a unique value. Even after the delete

4.  [Python Indexing](https://python.langchain.com/docs/modules/data_connection/indexing) 
Does all this go away once the Indexing API is available in JavaScript?

Ideally, I'd like to search the vector store with a query string and/or a metadata filter so I can delete the result set. 

Your time is greatly appreciated!
Thanks in advance

**Comment by stevenmilstein** [comment]
Sorry @dosu-beta but the response doesn't work because `id` is not a key in the results - which is the problem.

**Comment by stevenmilstein** [comment]
doc.metadata.id does not resolve the issue. I've since moved to Supabase where I can query for the generated Id.

**Comment by shaojun** [comment]
I think this is the issue in `langchain_core.documents.Document` that it didn't have a property of `id`, thus the `PineconeVectorStore` can't set the queried id from db record when return to user code.
actually here can see `PineconeVectorStore` already can read the id from db record:
```
def similarity_search_by_vector_with_score(
        self,
        embedding: List[float],
        *,
        k: int = 4,
        filter: Optional[dict] = None,
        namespace: Optional[str] = None,
    ) -> List[Tuple[Document, float]]:
        """Return pinecone documents most similar to embedding, along with scores."""

        if namespace is None:
            namespace = self._namespace
        docs = []
        results = self._index.query(
            vector=embedding,
            top_k=k,
            include_metadata=True,
            namespace=namespace,
            filter=filter,
        )
#the results has a id property
...
...
...
```
