### ISSUE TITLE
I want to filter the search in my Pinecone Index with the last mod metadata.

### ISSUE THREAD

**Issue by DonTizi** [langchain-ai/langchainjs#2705]
Hi , I want to filter the Pinecone retrieval for my chain to retrieve only lastmod metada to 2023. I have an index of documents from a website from 2021 to 2023 and I want to retrieve only 2023 lastmod. here is my code , how can I do it please? 
`
import {OpenAI} from "langchain/llms/openai";
import {pinecone} from "@/utils/pinecone-client";
import {PineconeStore} from "langchain/vectorstores/pinecone";
import {OpenAIEmbeddings} from "langchain/embeddings/openai";
import {ConversationalRetrievalQAChain} from "langchain/chains";
import { ChatOpenAI } from "langchain/chat_models/openai";
import { PromptTemplate } from "langchain/prompts";

async function initChain() {
    const model = new ChatOpenAI({
        modelName: "gpt-3.5-turbo",
        temperature: 0,
      });    
    const pineconeIndex = pinecone.Index('canada');

    const vectorStore = await PineconeStore.fromExistingIndex(
        new OpenAIEmbeddings({}),
        {
            pineconeIndex: pineconeIndex,
            textKey: 'text',
            
        },
    );
    return ConversationalRetrievalQAChain.fromLLM(
        model,
        vectorStore.asRetriever(),
        {returnSourceDocuments: true,
        },
    );
}

export const chain = await initChain()`

**Comment by RayaneMelDz** [comment]
> ```ts
> const vectorStore = await PineconeStore.fromExistingIndex(
>     new OpenAIEmbeddings({}),
>     {
>         pineconeIndex: pineconeIndex,
>         textKey: 'text',
>         searchParams: {
>             filter: {
>                 lastmod: {
>                     $eq: 2023,
>                 }
>             },
>             mergeFiltersOperator: "and",
>         }
>     },
> );
> ```

I have this error with the code you provided , it does not define the searchParams:
Argument of type '{ pineconeIndex: VectorOperationsApi; textKey: string; searchParams: { filter: { lastmod: { $eq: number; }; }; mergeFiltersOperator: string; }; }' is not assignable to parameter of type 'PineconeLibArgs'.
  Object literal may only specify known properties, and 'searchParams' does not exist in type 'PineconeLibArgs'.ts(2345)

**Comment by RayaneMelDz** [comment]
@dosu-bot , 
I have this error with the code you provided , it does not define the searchParams:
Argument of type '{ pineconeIndex: VectorOperationsApi; textKey: string; searchParams: { filter: { lastmod: { $eq: number; }; }; mergeFiltersOperator: string; }; }' is not assignable to parameter of type 'PineconeLibArgs'.
Object literal may only specify known properties, and 'searchParams' does not exist in type 'PineconeLibArgs'.ts(2345)

**Comment by RayaneMelDz** [comment]
@dosu-bot

I have Index with Website pages not documents , is there a process with this? I've indexed a website with the Sitemap loader.
