### ISSUE TITLE
I want my retriever to search in the vector store for each question asked.

### ISSUE THREAD

**Issue by DonTizi** [langchain-ai/langchainjs#2708]
Hi, I'm using the ConversationalQARetriever as part of a chain to answer questions from my Pinecone vector store index. The problem is that when I first ask it a question, it searches in the vector store for the answer. However, after this first answer, it does not search in the Pinecone vector store again, and I want it to retrieve information from the vector store for each question. How can I achieve this, please?
Here is my chain.ts:
`import {OpenAI} from "langchain/llms/openai";
import {pinecone} from "@/utils/pinecone-client";
import {PineconeStore} from "langchain/vectorstores/pinecone";
import {OpenAIEmbeddings} from "langchain/embeddings/openai";
import {ConversationalRetrievalQAChain} from "langchain/chains";

async function initChain() {
    const model = new OpenAI({});
    const pineconeIndex = pinecone.Index('canada');

    const vectorStore = await PineconeStore.fromExistingIndex(
        new OpenAIEmbeddings({}),
        {
            pineconeIndex: pineconeIndex,
            textKey: 'text',
            
        },
    );

    

    return ConversationalRetrievalQAChain.fromLLM(
        model,
        vectorStore.asRetriever(),
        {returnSourceDocuments: true,}

            
        
    );
}

export const chain = await initChain()`

And here is my route.tsx:
`import { NextResponse } from 'next/server';
import {chain} from "@/utils/chain";
import {Message} from "@/types/message";

export async function POST(request: Request) {

    const body = await request.json();
    const question: string = body.query;
    const history: Message[] = body.history ?? []

    const res = await chain.call({
            question: question,
            chat_history: history.map(h => h.content).join("\n"),
        });

    console.log(res.sourceDocuments)

    const links: string[] = Array.from(new Set(res.sourceDocuments.map((document: {metadata: {source: string}}) => document.metadata.source)))
    return NextResponse.json({role: "assistant", content: res.text, links: links})
}
`

**Comment by RayaneMelDz** [comment]
@dosu-bot

I have this message in const chain = await initChain()
Cannot find name 'initChain'.ts(2304)
