### ISSUE TITLE
FaissStore.fromDocuments - Error: connect ETIMEDOUT 104.18.6.192:443

### ISSUE THREAD

**Issue by JOUNHO** [langchain-ai/langchainjs#2709]
Hello, in order to use the langchain API in an environment without internet, I set the URL address "https://api.openai.com" to be accessible.

I would like to contact you because an error occurred while using langchain's FaissStore for efficient similarity search and clustering of dense vectors.

Below is the source code I used.

------------------------------------Start---------------------------------
`
import express from "express";

const router = express.Router();

import { PuppeteerWebBaseLoader } from "langchain/document_loaders/web/puppeteer";

import puppeteer from "puppeteer";

import { ChatOpenAI } from "langchain/chat_models/openai";

import  {RecursiveCharacterTextSplitter}  from "langchain/text_splitter";

import {OpenAIEmbeddings} from "langchain/embeddings/openai";

import {FaissStore} from "langchain/vectorstores/faiss"; 

import { Document } from "langchain/document";

const OPEN_AI_API_KEY = "sk-~~~";

const openAI = new ChatOpenAI({

    openAIApiKey: OPEN_AI_API_KEY,

    temperature: 0,

    modelName: 'gpt-3.5-turbo-0613',

})

let vectorDB;

router.get("/", async () => {

    try {

        console.log("setting 실행");

        const urlList = [

            "https://uno-gaebal.tistory.com/55",

        ]

        //3.청크화때 사용

        const splitter = new RecursiveCharacterTextSplitter({

            chunkSize: 1500,

            chunkOverlap: 200,

            //length_function :countTokens,

        })

        let chunks = [];

        console.log("1",splitter);

        for (const url of urlList) {

            //1.WebLoader

            const loader = new PuppeteerWebBaseLoader(url);

            const docs = await loader.load();

            const pageContent = docs[0].pageContent;

            const pageMetaData = docs[0].metadata;

            //3.split(청크화)

            const tempChunks = await splitter.splitDocuments([

                new Document({

                    pageContent: pageContent,

                    metadata: pageMetaData,

                })

            ]);

            chunks = chunks.concat(tempChunks);

        }

        console.log("2",chunks);

        const embeddings = new OpenAIEmbeddings({

            timeout: 30000,

            openAIApiKey: OPEN_AI_API_KEY,

        });

        console.log("3",embeddings);

       // Error
        vectorDB = await FaissStore.fromDocuments(

            chunks,

            embeddings

          );

        console.log(vectorDB);

        console.log("success");

        //(chunks && vectorDB) ? res.json({message:"success"}) : res.json({message:"fail"});

    } catch (e) {

        console.log("실패", e);

    }

});`
------------------------------------End---------------------------------

But this source code
"vectorDB = await FaissStore.fromDocuments(

            chunks,

            embeddings

          );"
The following error occurs in that part.
Error: connect ETIMEDOUT 104.18.6.192:443
or
Error: connect ETIMEDOUT 104.18.7.192:443

May I know how to solve the above? and
Can I know the URL or IP information needed when using langchain?

**Comment by jacoblee93** [comment]
The `Faiss.fromDocuments()` method is shorthand for also calling the OpenAI embeddings endpoint, which creates vector representations of your documents. It may not be a FAISS problem, but a problem with your firewall.

Can you try calling just the basic model call in isolation?

```typescript
import { OpenAI } from "langchain/llms/openai";

const llm = new OpenAI({});
console.log(await llm.invoke("Hi there"));
```

and:

```typescript
import { OpenAIEmbeddings } from "langchain/embeddings/openai";

const embeddings = new OpenAIEmbeddings();

const res = await embeddings.embedQuery("Hello world");
console.log(res);
```
