### ISSUE TITLE
chromadb similaritySearchWithScore score inconsistency

### ISSUE THREAD

**Issue by imsamurai** [langchain-ai/langchainjs#2723]
hi! 
chroma similaritySearchWithScore returns near 0 value for best match, 
while memory vectorstore returns near 1 for best match.

Because of this i can't use ScoreThresholdRetriever and generally can't replace memory with chroma without code changes.

Do we need to invert score in cromadb for compatability? (1-score)

**Comment by jacoblee93** [comment]
Hey @imsamurai, the score is unfortunately a provider-dependent metric and we can't guarantee anything about it. You'll need to tune it differently via code changes when switching providers, yes.

**Comment by imsamurai** [comment]
maybe this should be in docs?

**Comment by jacoblee93** [comment]
Would be good to add yeah! Will do today.
