### ISSUE TITLE
Bedrock class always uses "invoke-with-response-stream" endpoint. Breaks AI21 and anthropic models

### ISSUE THREAD

**Issue by jacobewen** [langchain-ai/langchainjs#2731]
As stated in the title. There is currently no option to call without streaming, and the only model I can get to work is Amazon Titan.
Anthropic models fail due to missing event-type header
AI21 models fail due to "400 Bad Request: {"message":"The model is unsupported for streaming"}"

**Comment by MironMihnea14** [comment]
Anthropic also works with streaming, but you have to format your prompt like this: ""\n\nHuman:  <<prompt>> \n\nAssistant:"

**Comment by jacoblee93** [comment]
We've added a chat model version too!

https://js.langchain.com/docs/modules/model_io/models/chat/integrations/bedrock

Note that some of the peer deps have changed in the latest version - we're no longer using the deprecated ones.
