### ISSUE TITLE
TimeoutError: The operation timed out

### ISSUE THREAD

**Issue by LeoMartinDev** [langchain-ai/langchainjs#2743]
When using Ollama llm with document based chains, I receive a `TimeoutError: The operation timed out` after about 60 seconds.
Any way to increase the timeout value ? I tried with something like that but without success:

```javascript
const response = await chain.call({
  input_documents: documents,
  timeout: 1000 * 60 * 10, // 10 minutes
});
```

**Comment by jacoblee93** [comment]
CC @jmorganca?
