### ISSUE TITLE
Support Bedrock as chat_models

### ISSUE THREAD

**Issue by mats16** [langchain-ai/langchainjs#2744]
Langchain for python supports Amazon Bedrock as chat_models.
https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/chat_models/bedrock.py

It is better if this is supported in langchainjs (JavaScript).

**Comment by mats16** [comment]
I'll close the issue because it's a duplicate issue.

**Comment by khanzzirfan** [comment]
Can you also support Sagemaker as ChatModel? In the sameway. for Javascript? That would be really helpful.
