### ISSUE TITLE
Return additional data from tools to agent executor

### ISSUE THREAD

**Issue by ashbuilds** [langchain-ai/langchainjs#2752]
Hi, I noticed that tools return type is set to `string` but it actually accepts JSON object as well, which will allow it to pass additional data down to main executor and you can use it like below: 

```
// tools.ts
	public async _call(data) {
		const extractChain = await createExtractionChainFromZod(this.schema, getChatGPTModel())
		const extractedData = await extractChain.call({ query: data })

		return  {
			content: "can be gpt output text, if any",
			name: this.name,
			additional_kwargs: {
				myTool:{ extractedData }
			}
	}
```

```
// agent.ts
	const kwargs = intermediateSteps.flatMap((step) => {
			const { observation } = step;
			const { additional_kwargs: kwargs } = observation || {};

			return kwargs;
		});

		return new AIMessage(output, {
			metadata: { parameters: usedParameters, toolsOutput: kwargs }, // <---  
		});
```

Now my question is am I doing this right? Or if there are any other better way to achieve this? If not, is it possible if we can fix the return type of tools/dynamicTools to accept object? Thanks 🙏

**Comment by chenyang-zhang-ck** [comment]
The tool default is expecting a string result https://github.com/langchain-ai/langchainjs/blob/main/langchain/src/tools/base.ts#L75, if you want you have to override call() instead of _call()
