### ISSUE TITLE
Feat: add ConversationTokenBufferMemory

### ISSUE THREAD

**Issue by danny-avila** [langchain-ai/langchainjs#2753]
Been running into needing this, from Python counterpart: https://python.langchain.com/docs/modules/memory/types/token_buffer

Maybe I can put in a PR for this as it's simple enough looking at the other memory classes.

**Comment by ychen5601** [comment]
Hi! I would like to work on this issue. I will take this on later this week. Thanks in advance!

**Comment by danny-avila** [comment]
> Hi! I would like to work on this issue. I will take this on later this week. Thanks in advance!

Great! If I had more time, I would've started already but this remains to be seen for the week. Will be on the lookout for your PR.

**Comment by ychen5601** [comment]
@danny-avila after taking a look into the ticket, I noticed that method `llm.get_num_tokens_from_messages` from Python is not implemented in the JavaScript repo. I'm looking into a workaround for this but expect a modest delay to the pull request!

This is my first PR in an open-source repository so thank you in advance for your patience, and any advice is greatly appreciated!
