### ISSUE TITLE
TemplateFormat 'jinja-2' not working

### ISSUE THREAD

**Issue by NikoLandgraf** [langchain-ai/langchainjs#2775]
according to the documentation's **PromptTemplateInput** the variable TemplateFormat takes the options 'f-string' or 'jinja-2'.

Using "jinja-2" in the following example:

```
const template = "Hallo {{ name }}";
const templatePrompt = new PromptTemplate({
  template: template,
  templateFormat: "jinja-2",
  inputVariables: ["name"],
});

console.log(await templatePrompt.format({ name: "world" }));
```

yields this error: `Uncaught Error: Invalid template format. Got `jinja-2`; should be one of f-string,jinja2`.

Changing the above example to:

```
const template = "Hallo {{ name }}";
const templatePrompt = new PromptTemplate({
  template: template,
  templateFormat: "jinja2",
  inputVariables: ["name"],
});

console.log(await templatePrompt.format({ name: "world" }));
```
yields an "undefined" formatted output.

**Comment by jacoblee93** [comment]
This is unsupported, I will remove from the docs.
