### ISSUE TITLE
provide a way to tweak xml agent system message

### ISSUE THREAD

**Issue by trashhalo** [langchain-ai/langchainjs#2778]
We needed to add a bit more instructions to the system message but it's not possible with the xml agent. I tried to manually construct the agent instead of using the helper function but the Xml agent class is prohibited from being accessed directly outside the module.

I ultimately worked around it by copying the agent/Xml file into our code ase and just changing it.

It looks like the openai agent already has the ability to add extra system instructions

**Comment by jacoblee93** [comment]
Thanks, yes we should support this!
