### ISSUE TITLE
VectorStoreRetrieverMemory doesn't work with ChatGooglePaLM in a standard ConversationChain

### ISSUE THREAD

**Issue by ElMehdiBouamama** [langchain-ai/langchainjs#2780]
Here is the code: `

    private static llm = new ChatGooglePaLM({ apiKey: "" });

    private static memory = new VectorStoreRetrieverMemory({
        vectorStoreRetriever: new MemoryVectorStore(new GooglePaLMEmbeddings({ apiKey: "" })).asRetriever(1),
        memoryKey: "history",
    });

    private static prompt = ChatPromptTemplate.fromMessages([
        SystemMessagePromptTemplate.fromTemplate("The following is a friendly conversation between a human and an AI. The AI is talkative and provides lots of specific details from its context. If the AI does not know the answer to a question, it truthfully says it does not know."),
        new MessagesPlaceholder("history"),
        HumanMessagePromptTemplate.fromTemplate("{input}"),
    ]);
    private static chain = new ConversationChain({
        //memory: new BufferMemory({ returnMessages: true, memoryKey: "history" }),
        memory: computroniumLLM.memory,
        prompt: computroniumLLM.prompt,
        llm: computroniumLLM.llm,
        verbose: false
    });

    // Model Inference
    static async exec(query: string): Promise<string> {
        const res = await this.chain.call({ input: query });
        return res.response;
    }`

Here is the error message: 
`Google PaLM requires alternate messages between authors`

Problem:
The template should be able to work normally, without cherry picking prompt boilerplates.

**Comment by langchain-infra** [comment]
Hi @ElMehdiBouamama looks like you have leaked a Google API Key starting with `AIzaSyAxD`. We highly encourage revoking this api key as it is visible to the public in our git history.

**Comment by ElMehdiBouamama** [comment]
Ae you sure? 😂
