### ISSUE TITLE
Issue with Self Query Retrieval from Supabase DB in Langchain JS when No Metadata Filter is Set

### ISSUE THREAD

**Issue by felri** [langchain-ai/langchainjs#2794]
**Description:**

I am encountering an issue with Langchain JS when querying a Supabase database for a specific term. The database has a column named embeddings and another column for the metadata that contains: 

{ "year", "month", "day" }

When I query with the term "**nextjs jobs**", the retrieval fails to return any results as no year is specified. However, when I specify the year in the query like "**nextjs jobs in 2020**", the retrieval works perfectly fine. According to the debug information, it seems that the prompt is instructing the LLM to return filter: 'NO_FILTER' when no year is specified and this is causing the problem?

Here's the relevant code snippet for the query execution:

```ts
export async function queryVectorStore(text: string): Promise<any> {
  const vectorStore = await SupabaseVectorStore.fromExistingIndex(embeddings, {
    client: supabaseAdmin,
    tableName: "comments",
    queryName: "match_documents",
  });

  const selfQueryRetriever = await SelfQueryRetriever.fromLLM({
    llm,
    vectorStore,
    verbose: true,
    documentContents,
    attributeInfo,
    structuredQueryTranslator: new SupabaseTranslator(),
  });
  ...
  const results = await selfQueryRetriever.getRelevantDocuments(text);
  console.log(results);
  return results;
}
```

And the PostgreSQL function match_documents that is being utilized for retrieval:

```sql
create function match_documents (
  query_embedding vector(1536),
  match_count int DEFAULT null,
  filter jsonb DEFAULT '{}'
) returns table (
  id bigint,
  content text,
  metadata jsonb,
  similarity float
)
language plpgsql
as $$
#variable_conflict use_column
begin
  return query
  select
    id,
    content,
    metadata,
    1 - (documents.embedding <=> query_embedding) as similarity
  from documents
  where metadata @> filter
  order by documents.embedding <=> query_embedding
  limit match_count;
end;
$$;
```

Additional Details:

It appears that a filter is necessary for a self-query request to function properly. Without a specified filter, passing only the embeddings of the user input results in zero results being returned. This behavior seems to be tied to the absence of a year in the query. Any insights or workarounds to address this issue would be greatly appreciated.

**Comment by felri** [comment]
The answer does not make sense, my problem is with the query created by the LLM, if the query has 

`filter: 'NO_FILTER'`

I think the problem is there, because if I add a filter into the user query like: 

`any python jobs from 2022 `

the LLM correctly creates a filter for the metadata and it works perfectly, my problem is when the user input has nothing for the filter and only for the semantic search, the response is empty: 

`any python jobs from any year`

**Comment by felri** [comment]
Still not working, and by using SupabaseFilterRPCCall I'm going to lose the option to use self query correct? Here is the relevant output dump: 

```bash
[retriever/start] [1:retriever:SelfQueryRetriever] Entering Retriever run with input: {
  "query": "next js jobs in 2020"
}
[chain/start] [1:retriever:SelfQueryRetriever > 2:chain:LLMChain] Entering Chain run with input: {
  "query": "next js jobs in 2020"
}
[llm/start] [1:retriever:SelfQueryRetriever > 2:chain:LLMChain > 3:llm:OpenAI] Entering LLM run with input: {
  "prompts": [
    "Your goal is to structure the user's query to match the request schema provided below.\n\n<< Structured Request Schema >>\nWhen responding use a markdown code snippet with a JSON object formatted in the following schema:\n\n```json\n{\n    \"query\": string \\ text string to compare to document contents\n    \"filter\": string \\ logical condition statement for filtering documents\n}\n```\n\nThe query string should contain only text that is expected to match the contents of documents. Any conditions in the filter should not be mentioned in the query as well.\n\nA logical condition statement is composed of one or more comparison and logical operation statements.\n\nA comparison statement takes the form: `comp(attr, val)`:\n- `comp` (eq | ne | gt | gte | lt | lte): comparator\n- `attr` (string):  name of attribute to apply the comparison to\n- `val` (string): is the comparison value\n\nA logical operation statement takes the form `op(statement1, statement2, ...)`:\n- `op` (and | or): logical operator\n- `statement1`, `statement2`, ... (comparison statements or logical operation statements): one or more statements to apply the operation to\n\nMake sure that you only use the comparators and logical operators listed above and no others.\nMake sure that filters only refer to attributes that exist in the data source.\nMake sure that filters only use the attributed names with its function names if there are functions applied on them.\nMake sure that filters only use format `YYYY-MM-DD` when handling timestamp data typed values.\nMake sure that filters take into account the descriptions of attributes and only make comparisons that are feasible given the type of data being stored.\nMake sure that filters are only used as needed. If there are no filters that should be applied return \"NO_FILTER\" for the filter value......"
  ]
}
[llm/end] [1:retriever:SelfQueryRetriever > 2:chain:LLMChain > 3:llm:OpenAI] [1.91s] Exiting LLM run with output: {
  "generations": [
    [
      {
        "text": "```json\n{\n    \"query\": \"next js\",\n    \"filter\": \"and(eq(\\\"year\\\", 2020))\"\n}\n```",
        "generationInfo": {
          "finishReason": "stop",
          "logprobs": null
        }
      }
    ]
  ],
  "llmOutput": {
    "tokenUsage": {
      "completionTokens": 35,
      "promptTokens": 996,
      "totalTokens": 1031
    }
  }
}
[chain/end] [1:retriever:SelfQueryRetriever > 2:chain:LLMChain] [1.97s] Exiting Chain run with output: {
  "text": {
    "query": "next js",
    "filter": {
      "operator": "and",
      "args": [
        {
          "comparator": "eq",
          "attribute": "year",
          "value": 2020,
          "exprName": "Comparison"
        }
      ],
      "exprName": "Operation"
    },
    "exprName": "StructuredQuery"
  }
}
```


the above is working fine, the below is the bug, no filters no results: 

```bash
[llm/end] [1:retriever:SelfQueryRetriever > 2:chain:LLMChain > 3:llm:OpenAI] [1.19s] Exiting LLM run with output: {
  "generations": [
    [
      {
        "text": "```json\n{\n    \"query\": \"next js\",\n    \"filter\": \"NO_FILTER\"\n}\n```",
        "generationInfo": {
          "finishReason": "stop",
          "logprobs": null
        }
      }
    ]
  ],
  "llmOutput": {
    "tokenUsage": {
      "completionTokens": 30,
      "promptTokens": 995,
      "totalTokens": 1025
    }
  }
}
[chain/end] [1:retriever:SelfQueryRetriever > 2:chain:LLMChain] [1.20s] Exiting Chain run with output: {
  "text": {
    "query": "next js",
    "exprName": "StructuredQuery"
  }
}
[retriever/end] [1:retriever:SelfQueryRetriever] [1.20s] Exiting Retriever run with output: {
  "documents": []
}
```

**Comment by felri** [comment]
@dosu-bot

So the second idea is to reimplement: 

```ts
  const selfQueryRetriever = await SelfQueryRetriever.fromLLM({
    llm,
    vectorStore,
    verbose: true,
    documentContents,
    attributeInfo,
    structuredQueryTranslator: new SupabaseTranslator(),
  });

  const results = await selfQueryRetriever.getRelevantDocuments(
    text,
  );
```

But in steps, so it would be: 
1 - User sends input
2 - LLM with the right prompt returns the query with filters
3 - Translate with SupabaseTranslator
4 - Get relevant documents? 

Do you know about an example I can take a look at? Or could you provide an example code of how to change it?

**Comment by jacoblee93** [comment]
Hey @felri, I fear the bot may have sent you on a wild goose chase - sorry about that. Will have a look, also CC @ppramesi

**Comment by ppramesi** [comment]
Okay so I think there's a way to do what you want, but it's kinda arcane. Maybe try:

```
const selfQueryRetriever = await SelfQueryRetriever.fromLLM({
  llm,
  vectorStore,
  verbose: true,
  documentContents,
  attributeInfo,
  structuredQueryTranslator: new SupabaseTranslator(),
  searchParams: {
    filter: (rpcCall: SupabaseFilter) => rpcCall,
    mergeFiltersOperator: "and"
  }
});
```

The reason it's like this is because we can't tell what the intention of the original prompt actually is. In most cases, it's better for self-query chain to return nothing if it can't construct a filter based on the attribute info and the query (i.e. if the query is pretty much every other irrelevant string). Otherwise it would be leaky (i.e. always returning everything) when there's actually nothing to fetch. We can add another option on searchParams to default to fetching everything if no filter can be created, though.

**Comment by depombo** [comment]
I'm running on this issue today

> Okay so I think there's a way to do what you want, but it's kinda arcane. Maybe try:
> 
> ```
> const selfQueryRetriever = await SelfQueryRetriever.fromLLM({
>   llm,
>   vectorStore,
>   verbose: true,
>   documentContents,
>   attributeInfo,
>   structuredQueryTranslator: new SupabaseTranslator(),
>   searchParams: {
>     filter: (rpcCall: SupabaseFilter) => rpcCall,
>     mergeFiltersOperator: "and"
>   }
> });
> ```
> 
> The reason it's like this is because we can't tell what the intention of the original prompt actually is. In most cases, it's better for self-query chain to return nothing if it can't construct a filter based on the attribute info and the query (i.e. if the query is pretty much every other irrelevant string). Otherwise it would be leaky (i.e. always returning everything) when there's actually nothing to fetch. We can add another option on searchParams to default to fetching everything if no filter can be created, though.

Unfortunately, this didn't work for me

**Comment by djaffer** [comment]
The filter doesn't trigger?
