### ISSUE TITLE
Issue with SageMakerEndpoint with initializeAgentExecutor

### ISSUE THREAD

**Issue by katieringg** [langchain-ai/langchainjs#2801]
When using SageMakerEndpoint to create a model and then using it with the "initializeAgentExecutorWithOptions" to call "executor.call({ input })", I ultimately get the following errors and cannot get a response.

TypeError: Cannot read properties of undefined (reading 'includes')
    at ZeroShotAgentOutputParser.parse (/var/task/node_modules/langchain/dist/agents/mrkl/outputParser.cjs:36:18)
    at ZeroShotAgent._plan (/var/task/node_modules/langchain/dist/agents/agent.cjs:238:34)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async AgentExecutor._call (/var/task/node_modules/langchain/dist/agents/executor.cjs:144:26)
    at async AgentExecutor.call (/var/task/node_modules/langchain/dist/chains/base.cjs:104:28)

However, the sagemaker endpoint works fine on its own without an executor. Trying to add tools to it, so the executor is needed.

Below this is a code snippet that causes errors:

const model = new SageMakerEndpoint({
        endpointName: SAGEMAKER_ENDPOINT,
        modelKwargs: body.parameters,
        contentHandler,
        clientOptions: {
            region: AWS_REGION
        },
        endpointKwargs: { CustomAttributes: 'accept_eula=true' }
});
const tools = [];
const executor = await initializeAgentExecutorWithOptions(tools, model, {
        agentType: 'zero-shot-react-description',
        verbose: true
});
const result = await executor.call({ input: question });

**Comment by katieringg** [comment]
@dosu-bot This is the content handler we're using:
`class ContentHandler {
    contentType = "application/json";
    accepts = "application/json";

    async transformInput(prompt, modelKwargs: Record<string, unknown>) {
        const inputString = JSON.stringify({
            inputs: [
                [
	        {
                        "role": "user",
                        "content": prompt
                 }
               ]
             ],
            parameters: modelKwargs
        });
        return Buffer.from(inputString);
    }

    async transformOutput(output: Uint8Array) {
        const responseJson = JSON.parse(Buffer.from(output).toString("utf-8"));
        return responseJson.generation;
    }
}`

And here are the parameters being passed in to the SageMakerEndpoint as modelKwargs:
  {
    "max_new_tokens": 100,
    "top_p": 0.9,
    "temperature": 0.6
  }

Does it appear that my ContentHandler is outputting in the expected format?

**Comment by katieringg** [comment]
@dosu-bot My model returns undefined, this may be related to my overarching issue.
const model = new SageMakerEndpoint({
endpointName: SAGEMAKER_ENDPOINT,
modelKwargs: body.parameters,
contentHandler,
clientOptions: {
region: AWS_REGION
},
endpointKwargs: { CustomAttributes: 'accept_eula=true' }
});
const result = await model.call("What is AWS SageMaker?");

The variable "result" is undefined after this code snippet runs. Any suggestions on how to get that model to return data?

**Comment by jacoblee93** [comment]
Most agents will only work with OpenAI models at the moment as they require fairly strict outputs unfortunately :(
