### ISSUE TITLE
Use similaritySearchWithScore instead of similaritySearch on _getRelevantDocuments

### ISSUE THREAD

**Issue by ladrians** [langchain-ai/langchainjs#2811]
I am using different chains and when returning the document list to the client, always need to report on the chunks retrieved.

There is the `similaritySearchWithScore` to do it, but when running the chain I've noticed the `_getRelevantDocuments` from `VectorStoreRetriever` uses `similaritySearch`. 

It would be nice to return with each document an element with the associated score. So far it includes the `metadata` and `pageContent`, could it be added there?.

Are there any option to get this information without the need to explicitly call again the `similaritySearchWithScore`?

**Comment by ladrians** [comment]
What I would like is that the score be automatically returned for each document (as optional if you wish), this is valuable information for the caller.

**Comment by jacoblee93** [comment]
What if we returned it in the metadata as an additional field?
