### ISSUE TITLE
Can not get answer from Amazon Titan Text Express

### ISSUE THREAD

**Issue by Kirchen99** [langchain-ai/langchainjs#2812]
I followed this documentation: https://js.langchain.com/docs/modules/model_io/models/llms/integrations/bedrock and created the following code:

```javascript
import { Bedrock } from "langchain/llms/bedrock";

const model = new Bedrock({
    model: "amazon.titan-text-express-v1",
    region: "us-east-1",
});
  
const res = await model.invoke("Tell me a joke");
console.log(res);
```

And the `res` I received is `undefined`.

Compare to the javascript version, the code in python works fine:
```python
from langchain.llms import Bedrock

llm = Bedrock(
    credentials_profile_name="default",
    model_id="amazon.titan-text-express-v1"
)

from langchain.chains import ConversationChain
from langchain.memory import ConversationBufferMemory

conversation = ConversationChain(
    llm=llm, verbose=True, memory=ConversationBufferMemory()
)

result = conversation.predict(input="What is the most exciting question you can ask an LLM?")
print(result)
```

Did I miss something in my javascript code?

**Comment by jacoblee93** [comment]
Thanks for the report, will have a look!

**Comment by jacoblee93** [comment]
I actually don't have access to this one, perhaps @cwoolum can help?

**Comment by cwoolum** [comment]
I'll take a look and see what's up

**Comment by cwoolum** [comment]
@Kirchen99, can you please confirm this resolves your issue?

**Comment by Kirchen99** [comment]
> @Kirchen99, can you please confirm this resolves your issue?

It works! Thank you very much!

**Comment by jacoblee93** [comment]
Awesome!

Thank you again @cwoolum!
