### ISSUE TITLE
Readablestream not defined 

### ISSUE THREAD

**Issue by hammad-rb** [langchain-ai/langchainjs#2815]
When importing `RecursiveCharacterTextSplitter` and using it with vscode extension getting this error `ReadableStream not defined`
```
import { RecursiveCharacterTextSplitter } from "langchain/text_splitter";
const splitter = RecursiveCharacterTextSplitter.fromLanguage("js", {
			chunkSize: 32,
			chunkOverlap: 0,
		});
```
nodejs: `v18.18.0`

**Comment by jacoblee93** [comment]
Please see: https://js.langchain.com/docs/get_started/installation#unsupported-nodejs-16

**Comment by OhMyGhann** [comment]
good job
