### ISSUE TITLE
Hybrid search and reranking

### ISSUE THREAD

**Issue by AndyMik90** [langchain-ai/langchainjs#2819]
Hi, will there be support in the js version for Pinecone hybrid search and Cohere Reranker? We got this running on Python but would love to move to Vercel AI SDK with this functionality.

**Comment by ali-habibzadeh** [comment]
Would be great to see how to use pinecone hybrid search with the js framework

**Comment by ladrians** [comment]
+1 to this request!

**Comment by karol-f** [comment]
You can try to implement it like this https://cookbook.openai.com/examples/question_answering_using_a_search_api

**Comment by karol-f** [comment]
Hi, Cohere reranking (for Parent Retriever) is in PR

**Comment by sugarforever** [comment]
> Hi, Cohere reranking (for Parent Retriever) is in PR - #4738

@karol-f Is there any localized solution for reranking with langchain.js? I'm working on a 100% local knowledge base, so looking for a production ready and 100% local solution for reranking, in order to improve the RAG quality. Thanks.

**Comment by karol-f** [comment]
@sugarforever Yes! There is my PR https://github.com/langchain-ai/langchainjs/pull/4738 for that. I'm already using this in my app using "Patch Package" NPM library

**Comment by sugarforever** [comment]
> @sugarforever Yes! There is my PR #4738 for that. I'm already using this in my app using "Patch Package" NPM library

Cool. What's the BaseDocumentCompressor you use?

**Comment by karol-f** [comment]
Cohere (with v2 reranking model, didn't check v3) as it is cheap and fast and gives good results. My chain - https://www.reddit.com/r/LangChain/s/xWiBObjS1z

**Comment by sugarforever** [comment]
> Cohere (with v2 reranking model, didn't check v3) as it is cheap and fast and gives good results. My chain - https://www.reddit.com/r/LangChain/s/xWiBObjS1z

I see. If Cohere is used, it means the data goes out to Cohere via API, if I understand correctly. Is there any alternative that can be run locally? for example open source alternatives

**Comment by karol-f** [comment]
There are for sure os reranking models like BERT, but didn't check that

**Comment by sugarforever** [comment]
> There are for sure os reranking models like BERT, but didn't check that

Thanks. I had a quick search on HF. Looks https://huggingface.co/amberoad/bert-multilingual-passage-reranking-msmarco can do the job. Any example on how to integrate it with LangChain.js?

**Comment by zivni** [comment]
@sugarforever did you find a solution?
