### ISSUE TITLE
Bedrock Embeddings ThrottlingException

### ISSUE THREAD

**Issue by Jtewen** [langchain-ai/langchainjs#2905]
When attempting to generate a vector store using the ```fromDocuments``` method  on approximately 10,000 documents (specifically on the ```HNSWLib``` class) , it reaches the rate limit quickly. Most likely due to the ```BedrockEmbeddings.embedDocuments``` method just being a simple ```Promise.all``` on every document at once.

**Comment by jacoblee93** [comment]
I'll look into fixing this to better use concurrency, thank you for opening this!

**Comment by bracesproul** [comment]
@Jtewen [fix](https://github.com/langchain-ai/langchainjs/pull/2908) should be merged soon!
