### ISSUE TITLE
ChatOpenAI does not use perfixMessages in constructor params

### ISSUE THREAD

**Issue by glenchao** [langchain-ai/langchainjs#2913]
`ChatOpenAI` class that's supposed to replace `OpenAIChat` does not use the `prefixMessages` in constructor params

**Comment by jacoblee93** [comment]
Hi @glenchao,

You should instead use our ChatPromptTemplate class:

https://js.langchain.com/docs/modules/model_io/prompts/prompt_templates/#chat-prompt-template
