### ISSUE TITLE
ConversationSummaryBufferMemory doesn't flush the memory at maxTokenLimit

### ISSUE THREAD

**Issue by juandavidGF** [langchain-ai/langchainjs#2917]
I'm using `ConversationSummaryBufferMemory`, with maxTokens let's say 40, but It doesn't flush the conversation at '40 tokens' like is supposed, so It ends up getting the 'max_lenght err'. 

I was wondering if I was doing something wrong, but after trying in python it worked well. So maybe It's a bug?, Someone have the same problem?

In other hand, in the js documentation I don't see the `ConversationTokenBuffer` like in Python, so maybe It's related ...

**Comment by bracesproul** [comment]
Hey @juandavidGF could you reply with the error message you're getting and a code snippet on how you're initializing the `ConversationSummaryBufferMemory` class?

**Comment by Burry** [comment]
Seeing this same issue trying to use `ConversationSummaryBufferMemory` with `UpstashRedisChatMessageHistory` + `ConversationChain`.

Error from OpenAI:

```
400 This model's maximum context length is 8192 tokens. However, your messages resulted in 8265 tokens. Please reduce the length of the messages.
```

Code sample:

```ts
const chatPrompt = ChatPromptTemplate.fromMessages<{
  chat_history: string;
  input: string;
}>(...);

const chain = new ConversationChain({
  llm: new ChatOpenAI(...),
  memory: new ConversationTokenBufferMemory({
    maxTokenLimit: 4096,
    memoryKey: "chat_history",
    chatHistory: new UpstashRedisChatMessageHistory({
      sessionId,
      client,
    }),
    returnMessages: true,
  }),
  prompt: chatPrompt,
  outputParser: new StringOutputParser(),
});

const { response } = await chain.invoke({ input });
```

**Comment by mingxin-yang** [comment]
@Burry @bracesproul @juandavidGF I also face this problem, how did you solve it?

**Comment by flipace** [comment]
The issue appears to be related to the fact that

1) the summary buffer is only stored in memory, so it's never persisted to the redis chat message history.
2) when the "old" messages are `shift`ed from the returned `getMessages()` array, the data in redis is not updated at all, so they stay

This seems to be more of a core issue with `BaseChatMessageHistory`/`BaseListChatMessageHistory`, which do not provide any functionality to actually remove messages when using anything other than the "in memory" memory.

The `prune` call merely calls `.shift()` on the value returned from `chatHistory.getMessages()`, which in case of any of the async memory providers won't do anything, but on the in-memory variant, the messages array is modified as expected...

**Comment by dmanresa-saes** [comment]
Hi @juandavidGF! I wanted to let you know that the error you reported is no longer occurring. Thank you!

**Comment by flipace** [comment]
> Hi @juandavidGF! I wanted to let you know that the error you reported is no longer occurring. Thank you!

While I didn't try it now (we implemented our own memory/summary class) - the issue described by me and @Burry is probably still open - I don't see any of the required changes in https://github.com/langchain-ai/langchainjs/blob/b9d86b16bd0788144f8f27cf5d18960c43da49af/langchain/src/memory/summary_buffer.ts#L144 (the `.shift()` will only work for an in-memory history.

Should a new issue be opened for this?
