### ISSUE TITLE
Add Document Loader for Google Drive

### ISSUE THREAD

**Issue by saminkhan1** [langchain-ai/langchainjs#2922]
In reference to this issue in the python repo: https://github.com/langchain-ai/langchain/issues/9783, I would like to create a issue to add document loader for Google Drive in langchainjs. I would like to be assigned and work on this issue.

**Comment by bracesproul** [comment]
Hey @saminkhan1 that would be much appreciated! This can be the issue used to track it, so just put up a pull request with the improvement and add the line `Fixes #2922`

**Comment by afirstenberg** [comment]
This sounds great!

Note that there was some similar work done as part of the MakerSuite integration that you may wish to leverage.

See the DriveFileReadConnection in experimental/hubs/makersuite/googlemakersuitehub.ts and ping me if you have questions or thoughts.
