### ISSUE TITLE
MongoDB Vector Store Error :  $vectorSearch is not allowed or the syntax is incorrect, see the Atlas documentation for more information

### ISSUE THREAD

**Issue by vinodkiran** [langchain-ai/langchainjs#2940]
MongoDB Vector Store Search works with Langchain version 0.0.157, but fails when used with version 0.0.165

This has been reported on the Mondo DB forums as well [vectorsearch-is-not-allowed](https://www.mongodb.com/community/forums/t/vectorsearch-is-not-allowed/248934)

My Test Case:

[mongodb-vectorestore-query.ts](https://gist.github.com/vinodkiran/b4795a8be49b97b2c409c7eaab804196#file-mongodb-vectorestore-query-ts)

**Comment by bracesproul** [comment]
Hey @vinodkiran looks like it's an issue on the MongoDB side, not us. See [this response](https://www.mongodb.com/community/forums/t/vectorsearch-is-not-allowed/248934/11) from a MongoDB employee
```
Hello all, apologies for the error and for the delayed response. To clarify, the error that you’re seeing here “$vectorSearch is not allowed or the syntax is incorrect, see the Atlas documentation for more information” is due to an issue in M0-M5 Clusters which will be resolved after our deployment tomorrow, it is not related to LangChain.
```
Closing this issue now
