### ISSUE TITLE
Add Gmail Toolkit

### ISSUE THREAD

**Issue by 1239uth** [langchain-ai/langchainjs#2946]
## Feature request
We suggest implementing the Gmail Toolkit for LangchainJS to integrate with agent functionality.

## Motivation
The Python version of Langchain contains the Gmail Toolkit already, but this feature doesn't exist in langchainJS, so we wish to bring parity between the two for this feature.

## Your contribution
Our team is willing to submit a PR for this once complete. 

We would love some guidance on how to approach this issue.

**Comment by bracesproul** [comment]
hey @1239uth it would be great to have that integration! A good place to start could be using the [langchain translator](https://langchain-translator.vercel.app/) to get a quick starting point for your JS implementation.

**Comment by pythagoras-yamamoto** [comment]
I believe I could contribute effectively to resolving this issue.
I'll give it a try!

**Comment by 1239uth** [comment]
Hey @pythagoras-yamamoto, our team has already started working on this and should be making a PR soon.

**Comment by alexleventer** [comment]
Hey @jacoblee93 - have you been able to get the gmail toolkit to work? I'm having issues with auth

**Comment by jacoblee93** [comment]
Will give it a look tomorrow 🙏

**Comment by 1239uth** [comment]
> I'm having issues with auth

To test Gmail auth you need a Google Workspace Account from what we learned. Thats the only way the JWT auth works I believe.

**Comment by alexleventer** [comment]
I was able to pretty much immediately get things working with the Google Node SDK and a custom dynamic tool.
