### ISSUE TITLE
`ChatCloudflareWorkersAI` Chat Model Integration configuration

### ISSUE THREAD

**Issue by demosjarco** [langchain-ai/langchainjs#2960]
I see `baseUrl` as a configuration object, but not being used anywhere in the code. This feature is necessary to be able to run requests through [Cloudflare's AI Gateway](https://developers.cloudflare.com/ai-gateway/providers/workersai/)

[`langchain/src/chat_models/cloudflare_workersai.ts`](https://github.com/langchain-ai/langchainjs/blob/main/langchain/src/chat_models/cloudflare_workersai.ts)
On line 35 it's declared and line 47 the value is set
But on line 122, it's not being used at all

**Comment by jacoblee93** [comment]
Hi @demosjarco, thanks for the heads up - will push a fix today and let you know here!
