### ISSUE TITLE
Need more types exported from langchain/memory

### ISSUE THREAD

**Issue by curthipster** [langchain-ai/langchainjs#2975]
The `BaseMemory` class references several types that are not exported from the package: `InputValues`, `OutputValues`, and `MemoryVariables`.

Can you export them so that we can reference them in our memory implementations?

**Comment by curthipster** [comment]
@dosu-bot That didn't exactly make it work, but I was able to get it to compile using `import { InputValues, OutputValues, MemoryVariables } from 'langchain/dist/memory/base'`.

**Comment by curthipster** [comment]
My project is TypeScript. Perhaps the issue is my typescript config.

This technique is working for me, but I don't like that I have to import from deep within the package. It would be great if the types were actually exported from the module so that we don't have to deeply import from subfolders.

**Comment by jacoblee93** [comment]
Can you try `langchain/memory/base`?

**Comment by jacoblee93** [comment]
We can do this, yes.

**Comment by jacoblee93** [comment]
Merged in #2993, will be in the next release
