### ISSUE TITLE
Adding gradient.ai LLM and Embeddings

### ISSUE THREAD

**Issue by michaelfeil** [langchain-ai/langchainjs#3007]
### Feature request

I propose to add the gradient-ts/js client of gradient.ai as a `LLM` and `Embedding`, similar to the Python implementation in https://python.langchain.com/docs/integrations/providers/gradient .

### Motivation

Gradient.ai offers fine-tuning and inference of models without paying for the server costs. 

I fine-tuned a model with a specific RAG template based on llama2 on gradient.ai, now i want to use it from Langchain, also in ts/js.

**Comment by chasemcdo** [comment]
Last couple PRs were made this morning which should wrap up this issue.

ie adapter and embedding support
