### ISSUE TITLE
More support for Google Vertex AI Vector Store and Embedding on Edge

### ISSUE THREAD

**Issue by kevsjh** [langchain-ai/langchainjs#3021]
The current implementation of the following Google Vertex AI is limited to pure NodeJS runtime only which depends on google-auth-library
  - Text Embedding/Google Vertex AI
  - Vector Store/Google Vertex AI Matching Engine

With this pure nodejs implementation, adding service account is limited to file-based service account instead of environment based is not ideal.

However, I did notice that the following Google Vertex AI langchainjs already has edge/web implementation with web-auth-library which allows users to leverage service account as env variable
  - ChatModel/ChatGoogleVertexAI
  - LLM/Google Vertex AI
  
 
Will the same edge/web implementation be extended over to GCP Vertex AI text embedding and Vector store since it seems pretty similar in implementation as shown #2579

**Comment by jacoblee93** [comment]
I think we could figure this out yeah!
