### ISSUE TITLE
Google Vertex AI Vector Store indexEndpoint in other project

### ISSUE THREAD

**Issue by TJMaria** [langchain-ai/langchainjs#3023]
I'm running into an issues using:
- Text Embedding/Google Vertex AI
- Vector Store/Google Vertex AI Matching Engine

I am deploying a NodeJs app in Google cloud, which should have the right service account and premissions.
Let's say my NodeJs app is deployed in project A.

My indexEndpoint is deployed in a different project, project B.

I can't seem to find a way to force the MatchingEngine to look for the indexEndpoint in project B.
Only place i can pass the projectId is through the authOptions, but that doesn't seem to work.

**Comment by TJMaria** [comment]
Ok, so I **HAVE TO** pass the service account key file?

And the index and indexEndpoint are only the ID's correct? Not the entire path including projectID?
The service account should be default use the correct project?

**Comment by TJMaria** [comment]
@dosu-bot.
Ok, so I HAVE TO pass the service account key file?

And the index and indexEndpoint are only the ID's correct? Not the entire path including projectID?
The service account should be default use the correct project?

**Comment by kevsjh** [comment]
AFAIK, Vertex AI store in langchainjs is a pure Node.js implementation, which means that it depends on the google-auth-library package.
By default, the google-auth-library package uses the service account for the resource that the Node.js application is deployed on.

There are two ways to override the default service account:

1. Set the GOOGLE_APPLICATION_CREDENTIALS environment variable as described in langhchainjs documentation. This variable should point to the path of the JSON file that contains the credentials for the service account that you want to use.
2. Grant cross-account service access to the service account from project A. This will allow the service account to access resources in project B. To do this, you need to grant the vertex ai user role to the service account from project A in project B.

**Comment by TJMaria** [comment]
@kevsjh 
Thank for your input, I also spotted your issue.

When working locally I was using the gcloud cli to authenticate (using my own acount):
`gcloud auth application-default login`

But now that I'm struggling to get it working in the deployed App, i decided to try it locally with a keyfile from the service account of project B (where the indexEndpoint is located). But I also can't seem to get that to work.

I'm using a json keyfile path in GOOGLE_APPLICATION_CREDENTIALS.

I get a 401 error, even if the service account is has the role of owner:
```error: {
        code: 401,
        message: 'Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.',
        errors: [
          {
            message: 'Invalid Credentials',
            domain: 'global',
            reason: 'authError',
            location: 'Authorization',
            locationType: 'header'
          }
        ],
        status: 'UNAUTHENTICATED'
      }
```

Only when passing a keyfile from my personal account, generated by `gcloud auth application-default login` does GOOGLE_APPLICATION_CREDENTIALS work for me.

**Comment by TJMaria** [comment]
@kevsjh  
When i try using the cross-account approach, the request is done in the wrong project.
So then i get a 403 because the resource doesn't exist

**Comment by TJMaria** [comment]
As far is I can see, the authOptions are not being passed to the indexEndpointClient from the MatchingEngine constructor:
https://github.com/langchain-ai/langchainjs/blob/4f56cf7ceb7f1abfc3f903c9d8a9bdb0c3d5b176/langchain/src/vectorstores/googlevertexai.ts#L389

That creates a client with new (empty) authOptions:
https://github.com/langchain-ai/langchainjs/blob/4f56cf7ceb7f1abfc3f903c9d8a9bdb0c3d5b176/langchain/src/vectorstores/googlevertexai.ts#L65

**Comment by kevsjh** [comment]
It seems that in the updated version, google auth is passed in to the class correctly but both google auth docs and langchainjs doc on vertex ai authentication seems a little lacking. 

The below should be the correct parameters to pass in.


`    const engine = new MatchingEngine(embeddings, {
      index: process.env.GOOGLE_VERTEXAI_MATCHINGENGINE_INDEX!,
      indexEndpoint: process.env.GOOGLE_VERTEXAI_MATCHINGENGINE_INDEXENDPOINT!,
      apiVersion: "v1beta1",
      docstore: store,
      location: 'us-central1',
      authOptions: {
        scopes: ['https://www.googleapis.com/auth/cloud-platform'],
        projectId: process.env.GOOGLE_APPLICATION_PROJECT_ID,
        credentials: {
          type: 'service_account',
          "client_email": process.env.GOOGLE_APPLICATION_CLIENT_EMAIL,
          "private_key": process.env.GOOGLE_APPLICATION_PRIVATE_KEY
        }
      },
    });`
    
I have tested the above in nextjs-14 api app router on my local machine with both gcloud auth logout, and also gcloud auth logged in but set to different project-id to validate this to ensure the service account impersonation is invoked, so this should work in production as well by setting the correct env.
 
Another important note was that for private_key environment var, it should be encapsulated in double quote "" instead of single quote ''.  You will get an error `Error: error:1E08010C:DECODER routines::unsupported` if the env is single quoted.
 
 So the correct env is 
 
 GOOGLE_APPLICATION_PRIVATE_KEY="-----BEGIN PRIVATE KEY .... -----END PRIVATE KEY-----\n"

**Comment by TJMaria** [comment]
I ended up stepping away from LangchainJs and implementing it myself.
@kevsjh Thanks for taking a look but it can't confirm if this would solve the issues i had.
