### ISSUE TITLE
Package.json import issues

### ISSUE THREAD

**Issue by rotichbryant** [langchain-ai/langchainjs#3041]
I have tried to import some classes from the package but I get this error

Error: Package subpath './dist/schema/output_parser' is not defined by "exports" in {project directory}\node_modules\langchain\package.json

I was trying to import RunnableSequence, RunnablePassthrough  but it doesn't work

**Comment by bracesproul** [comment]
Hey @rotichbryant, are you importing `RunnableSequence` and `RunnableMap` like this? Trying to import from `/dist` is not recommended.
`import { RunnableSequence, RunnablePassthrough } from "langchain/schema/runnable";`

**Comment by jacoblee93** [comment]
Closed but please reopen if the above doesn't fix.
