### ISSUE TITLE
Delete some messages from history

### ISSUE THREAD

**Issue by iuadastra** [langchain-ai/langchainjs#3042]
It would be useful to be able to delete some messages from the history that are no more important. That can dramatically reduce token count in longer conversations.
For example delete filter like this would be useful:

```js
memory.delete((message) => message.additional_kwargs.my_metadata == true)
```

**Comment by jacoblee93** [comment]
You can do this by manipulating/reinitializing the underlying `ChatMessageHistory` object:

```typescript
import { BufferMemory, ChatMessageHistory } from "langchain/memory";
import { HumanMessage, AIMessage } from "langchain/schema";

const pastMessages = [
  new HumanMessage("My name's Jonas"),
  new AIMessage("Nice to meet you, Jonas!"),
];

const memory = new BufferMemory({
  chatHistory: new ChatMessageHistory(pastMessages),
});
```

https://js.langchain.com/docs/modules/memory/how_to/buffer
