### ISSUE TITLE
Passing credentials from service account in other project not working for Google Vertex AI Matching Engine

### ISSUE THREAD

**Issue by TJMaria** [langchain-ai/langchainjs#3044]
I'm running into an issues using:

- Text Embedding/Google Vertex AI
- Vector Store/Google Vertex AI Matching Engine

I'm passing a keyfile and scope as auth options, from a service account in a different project (the project with the Vector store indexEndpoint)

As far is I can see, the authOptions are not being passed to the indexEndpointClient from the MatchingEngine constructor:
https://github.com/langchain-ai/langchainjs/blob/4f56cf7ceb7f1abfc3f903c9d8a9bdb0c3d5b176/langchain/src/vectorstores/googlevertexai.ts#L389

That creates a client with new (empty) authOptions:
https://github.com/langchain-ai/langchainjs/blob/4f56cf7ceb7f1abfc3f903c9d8a9bdb0c3d5b176/langchain/src/vectorstores/googlevertexai.ts#L65

The same seems to be the case with multiple other connections.

This results in the core/default service account credentials and projectId being used when sending a request to the indexEndpoint.

**Comment by jacoblee93** [comment]
@afirstenberg would you be able to shed some light on this one?

**Comment by afirstenberg** [comment]
I think I'm following. @TJMaria - Can you post code illustrating exactly how you're creating the MatchingEngine object with the auth args so I can duplicate and test it?

**Comment by TJMaria** [comment]
```
const authOptions =  {
    keyFile: process.env.GCREDENTIALS, // Path to the service account json key file
    scopes: ['https://www.googleapis.com/auth/cloud-platform'], // Scopes for the service account
}

const config = {
    index: process.env.MATCHINGENGINE_INDEX,
    indexEndpoint: process.env.MATCHINGENGINE_INDEXENDPOINT,
    apiVersion: 'v1beta1',
    docstore,
    authOptions
} as MatchingEngineArgs;

const embeddings = new GoogleVertexAIEmbeddings({
    model: 'textembedding-gecko',
    authOptions
});
const matchingEngine = new MatchingEngine(embeddings, config);
```

My App is running in a different GCP project then my Vector store.
The keyfile passed to the matching engine is for a Service account from the Vector store project with the correct credentials.

I tried multiple ways of overriding the projectId for the resulting clients.

**Comment by afirstenberg** [comment]
Got it, and thanks for the detailed example!

**Comment by TJMaria** [comment]
Partly due to these issues, I was forced to implement this without langchain. As I don't have this code anymore, i can't confirm this is still an issue.

Closing it
