### ISSUE TITLE
PGVector's `addDocuments` fails if number of documents > chunkSize

### ISSUE THREAD

**Issue by phof** [langchain-ai/langchainjs#3045]
PGVector's `addDocuments` fails if `documents.length` is bigger than [`chunkSize`](https://github.com/langchain-ai/langchainjs/blob/4f56cf7ceb7f1abfc3f903c9d8a9bdb0c3d5b176/langchain/src/vectorstores/pgvector.ts#L172C11-L172C20).

The PG error is: `error: could not determine data type of parameter $1`

To reproduce:

```js
import { OpenAIEmbeddings } from 'langchain/embeddings/openai'
import { PGVectorStore } from 'langchain/vectorstores/pgvector'

const connectionString = process.env.DATABASE_URL
const config = {
  postgresConnectionOptions: connectionString,
  tableName: 'testlangchain',
  columns: {
    idColumnName: 'id',
    vectorColumnName: 'vector',
    contentColumnName: 'content',
    metadataColumnName: 'metadata',
  },
}

const embeddings = new OpenAIEmbeddings()
const pgvectorStore = await PGVectorStore.initialize(embeddings, config)

try {
  const docsToGenerate = 501
  const documents = []
  for (let i = 1; i <= docsToGenerate; i++) {
    documents.push({ pageContent: 'Lorem Ipsum', metadata: { a: i } })
  }

  await pgvectorStore.addDocuments(documents)
  await pgvectorStore.end()
} catch (e) {
  console.log(e.message)
}
```

Note `docsToGenerate` is set to 501, which is bigger than the default [`chunkSize`](https://github.com/langchain-ai/langchainjs/blob/4f56cf7ceb7f1abfc3f903c9d8a9bdb0c3d5b176/langchain/src/vectorstores/pgvector.ts#L172C11-L172C20). If changed to a value smaller than 500, the operation is successful.

**Comment by phof** [comment]
cc/ @bracesproul and @jacoblee93

**Comment by omarestrella** [comment]
Also experiencing this, and noticed that when processing the next chunk, the insert query starts the parameters at `chunkSize + 1`, so you end up with parameters in a query like `... VALUES ($501, $502), ($503, $504) ...`. They should always start at `$1`.

If chunkIndex here: https://github.com/langchain-ai/langchainjs/blob/main/langchain/src/vectorstores/pgvector.ts#L135, is set to `0`, you can see the insertion work when the number of documents is > 500 because the parameters will start at `$1`.

**Comment by bracesproul** [comment]
Thanks for pointing this out, I'll investigate a solution today

**Comment by jacoblee93** [comment]
Oof, thanks for the catch and report!

**Comment by bracesproul** [comment]
Hey @phof @omarestrella a fix has been pushed and should be deployed next time we cut a release (likely sometime today/tmro)!
