### ISSUE TITLE
Add Streaming mechanism for `ChatBedrock` Class

### ISSUE THREAD

**Issue by ServerlessSam** [langchain-ai/langchainjs#3062]
`ChatBedrock` currently implements `_streamResponseChunks` however the `_call` function always calls `_signedFetch` and I don't see how `_streamResponseChunks` is used anywhere.

This is a feature request to allow `ChatBedrock` to be configurable for streamed or non-streamed responses (in the same way the `streaming` parameter is used in ChatOpenAI) and use _streamResponseChunks/_signedFetch accordingly.

Happy to assist if you like

**Comment by bracesproul** [comment]
Hey @ServerlessSam, you should be able to call the `.stream()` method on `ChatBedrock`.
The `*_streamResponseChunks` method is called inside a parent class of `ChatBedrock`. If you go into `BaseChatModel` class and search `*_streamResponseChunks` you'll see it's called by `*_streamIterator` which is in turn called by `stream`

**Comment by ServerlessSam** [comment]
@bracesproul 

```
Hey [@ServerlessSam](https://github.com/ServerlessSam), you should be able to call the .stream() method on ChatBedrock.
The *_streamResponseChunks method is called inside a parent class of ChatBedrock. If you go into BaseChatModel class and search *_streamResponseChunks you'll see it's called by *_streamIterator which is in turn called by stream
```

Thanks for the response (did you delete it btw? Not sure why it's not here?).

I see `*_streamIterator` in the `BaseChatModel` but not `stream` that is calling it.

For clarity my use case is to pass `ChatBedrock` into a `ConversationChain` so I can also provide the `memory` argument to keep the conversation's context. I'm then calling `ConversationChain.stream` and I can see the HTTP request to AWS is for the `invoke` method and not `invoke-with-response-stream` because we are calling `ChatBedrock._call` which calls `ChatBedrock._signedFetch` with a hardcoded `bedrockMethod: "invoke"`.

Is there a way to provide `memory` to `ChatBedrock.stream`?

The docs (https://js.langchain.com/docs/api/chat_models_bedrock/classes/ChatBedrock) don't make it clear to me what args are accepted in `.stream`

**Comment by jacoblee93** [comment]
Hey @ServerlessSam, `_streamResponseChunks` is called from the base class here (has to do with some iterator vs. stream concerns): https://github.com/langchain-ai/langchainjs/blob/main/langchain/src/chat_models/base.ts#L134

It sounds like you're trying to use `ChatBedrock` in a `ConversationChain`? If so, you'll need to use our streaming method that works with legacy chains - the new `.stream()` method is currently just for expression language sequences:

https://js.langchain.com/docs/modules/chains/foundational/llm_chain#usage-in-streaming-mode

https://js.langchain.com/docs/expression_language/

**Comment by jacoblee93** [comment]
Closed but reopen if the above isn't the case

**Comment by YikaiHu** [comment]
Seems like this issue is still not fixed.
Here is my code,
```
  constructor(chatConfig: ChatBedrockConfig) {
    this.chatBedrock = new ChatBedrock({
      model: chatConfig.model || config.bedrockModelName,
      region: config.awsRegion,
      streaming: true,
      temperature: chatConfig.temperature || 0.6,
      maxTokens: chatConfig.maxTokens || parseInt(config.maxTokens.toString()),
    });

    this.chatPrompt = ChatPromptTemplate.fromMessages([
      [
        'system',
        'You are an assistant that answers questions based on text {text}.',
      ],
      ['human', '{prompt}'],
    ]);
  }

  async handleConversation(context: string, text: string): Promise<void> {
    const chain = new LLMChain({
      prompt: this.chatPrompt,
      llm: this.chatBedrock,
    });

    const stream = await chain.stream({
      text: context,
      prompt: text,
    });
    // TODO: send to websocket
    console.log('streaming started');
    for await (const chunk of stream) {
      console.log(chunk);
    }
  }
```
and the log is:

```
streaming started
{
  text: ' Here is one way to rewrite that text:\n' +
    '\n' +
    'My AI assistant has the remarkable capacity to swiftly analyze enormous amounts of patient data, including medical records and imaging results. This enables the AI to diagnose complex conditions in seconds, whereas it could take human doctors hours or even days to do the same. As a result, the AI facilitates earlier detection of conditions and prompt medical intervention, which can greatly improve patient health outcomes.'
}
```

you can see that the output is still not a streaming message.
