### ISSUE TITLE
createJsonAgent with private llm using ollama returns Could not parse LLM output

### ISSUE THREAD

**Issue by kaykhan** [langchain-ai/langchainjs#3068]
I am trying to use [createJsonAgent](https://js.langchain.com/docs/api/agents/functions/createJsonAgent) to answer questions about json data using ollama llama2. However i get the following error:

> Executing with input "What is the age of John Doe"...
> (node:2254025) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
> (Use `node --trace-warnings ...` to show where the warning was created)
> result error OutputParserException [Error]: Could not parse LLM output:
>     at ZeroShotAgentOutputParser.parse (/home/kay/checkpoint/acme-ai/node_modules/langchain/dist/agents/mrkl/outputParser.cjs:46:19)
>     at ZeroShotAgent._plan (/home/kay/checkpoint/acme-ai/node_modules/langchain/dist/agents/agent.cjs:286:34)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async AgentExecutor._call (/home/kay/checkpoint/acme-ai/node_modules/langchain/dist/agents/executor.cjs:153:26)
>     at AgentExecutor.call (/home/kay/checkpoint/acme-ai/node_modules/langchain/dist/chains/base.cjs:104:28)
>     at main (/home/kay/checkpoint/acme-ai/custom.ts:37:14) {
>   llmOutput: undefined,
>   observation: undefined,
>   sendToLLM: false
> }
> Got output undefined

**Code:**
```
import { JsonToolkit, createJsonAgent } from "langchain/agents";
import { Ollama } from "langchain/llms/ollama";
import { JsonObject, JsonSpec } from "langchain/tools";

async function main() {
  let data: JsonObject;
  try {
    data = {
      name: "John Doe",
      age: 30,
    };

    if (!data) {
      throw new Error("Failed to load");
    }
  } catch (e) {
    console.log("here");
    console.error(e);
    return;
  }

  const toolkit = new JsonToolkit(new JsonSpec(data));

  const model = new Ollama({
    baseUrl: "http://localhost:11434",
    model: "llama2",
  });

  const executor = createJsonAgent(model, toolkit);

  const input = `What is the age of John Doe?`;

  console.log(`Executing with input "${input}"...`);

  let result;
  try {
    result = await executor.call({ input });
  } catch (err) {
    console.error("result error", err);
  }

  console.log(`Got output ${result}`);
}

main();
```

If i use the openapi model it works, but my goal is to use a private llm for this task, how should i do that?

**resources:**
https://js.langchain.com/docs/modules/agents/toolkits/json
https://js.langchain.com/docs/use_cases/question_answering/local_retrieval_qa

**Comment by kaykhan** [comment]
Interestingly, i executed it a few times and eventually it gave me 

```
{
  output: 'Agent stopped due to max iterations.',
  intermediateSteps: [
    { action: [Object], observation: 'Error: Invalid JSON pointer.' },
    {
      action: [Object],
      observation: 'Error: Value at /key1/0/age is null or undefined.'
    },
    { action: [Object], observation: 'Error: Invalid JSON pointer.' },
    { action: [Object], observation: 'Error: Invalid JSON pointer.' },
    { action: [Object], observation: 'Error: Invalid JSON pointer.' },
    { action: [Object], observation: 'Error: Invalid JSON pointer.' },
    { action: [Object], observation: 'Error: Invalid JSON pointer.' },
    { action: [Object], observation: 'Error: Invalid JSON pointer.' },
    { action: [Object], observation: 'Error: Invalid JSON pointer.' },
    { action: [Object], observation: 'Error: Invalid JSON pointer.' },
    { action: [Object], observation: 'Error: Invalid JSON pointer.' },
    { action: [Object], observation: 'Error: Invalid JSON pointer.' },
    { action: [Object], observation: 'Error: Invalid JSON pointer.' },
    { action: [Object], observation: 'Error: Invalid JSON pointer.' },
    { action: [Object], observation: 'Error: Invalid JSON pointer.' }
  ]
}

```

I wonder whats happening here, why is llama to get the age given the json data? (it is able to with openapi model). Do i need to use a better llm?

**Comment by kaykhan** [comment]
hmm i dont think the model is the problem
![image](https://github.com/langchain-ai/langchainjs/assets/5202527/e10252b5-11e0-4041-9cc1-6339325c6969)

**Comment by jacoblee93** [comment]
It unfortunately might be that the 13b is too small and isn't great at formatting JSON - most of these agents were designed to work with OpenAI and require a fair amount of capability.
