### ISSUE TITLE
importing issues.

### ISSUE THREAD

**Issue by Talhary** [langchain-ai/langchainjs#3069]
import { RunnablePassthrough, RunnableSequence } from "langchain/schema"; these files are not importing.

**Comment by jacoblee93** [comment]
You want:

`import { RunnablePassthrough, RunnableSequence } from "langchain/schema/runnable";`

I think there's a good argument to have them importable from `langchain/schema` or `langchain/runnable` though.

**Comment by Talhary** [comment]
I copied it from official docs sir.

**Comment by jacoblee93** [comment]
Where?

**Comment by Talhary** [comment]
https://js.langchain.com/docs/modules/data_connection/retrievers
In this link. Also check other packages sir. They are also not importing.

**Comment by jacoblee93** [comment]
It says 
```
import {
  RunnablePassthrough,
  RunnableSequence,
} from "langchain/schema/runnable";
```

**Comment by Talhary** [comment]
Yes that's not working

**Comment by jacoblee93** [comment]
What version of LangChain are you on? Try updating to latest?

**Comment by Talhary** [comment]
Already latest. Just installed 2 days ago.

**Comment by jacoblee93** [comment]
Sorry not sure then - likely due to your local setup. Maybe try in an online environment?

**Comment by Talhary** [comment]
Sir I tried on local setup and on GitHub codespaces

**Comment by mabry1985** [comment]
I'm see this issue too, I can ignore the line and it works, but it's a typing issue for sure, it's happened to me for months at this point
