### ISSUE TITLE
GoogleCalendarCreateTool doesn't work

### ISSUE THREAD

**Issue by devRenatoRodrigues** [langchain-ai/langchainjs#3075]
Im receive this error when i tryng execute google calendar tool 

` [llm/error] [1:chain:AgentExecutor > 2:chain:LLMChain > 3:llm:BaseModel] [151ms] LLM run errored with error: "The completion operation does not work with the specified model, gpt-4. Please choose different model and try again. You can learn more about which models can be used with each operation here: https://go.microsoft.com/fwlink/?linkid=2197993."`

**Comment by devRenatoRodrigues** [comment]
@dosu-bot

`import {
  initializeAgentExecutorWithOptions
} from 'langchain/agents';
// import { OpenAI } from "langchain/llms/openai";
import { BaseModel } from '@cognum/llm';
import { Calculator } from 'langchain/tools/calculator';
import { GoogleCalendarCreateTool, GoogleCalendarViewTool } from 'langchain/tools/google_calendar';


  const googleCalendarParams = {
    credentials: {
      clientEmail: process.env.GOOGLE_CALENDAR_CLIENT_EMAIL,
      privateKey: process.env.GOOGLE_CALENDAR_PRIVATE_KEY,
      calendarId: process.env.GOOGLE_CALENDAR_CALENDAR_ID,
    },
    scopes: [
      'https://www.googleapis.com/auth/calendar',
      'https://www.googleapis.com/auth/calendar.events'
    ],
  }
  
  
  describe('Google Calendar tool test', () => {
    
      it('should create a calendar event', async () => {
        const model = new BaseModel();
        const tools = [
            new GoogleCalendarCreateTool(googleCalendarParams),
          ];
    
        const executor = await initializeAgentExecutorWithOptions(
            tools,
            model,
            {
              agentType: 'zero-shot-react-description',
              verbose: true,
            }
          );
          const result = await executor.call({ input: 'Create a new meting for tomorrow at 9am with the title best day in the world' });
          expect(result.output).toEqual('The event create successfully');
        })
  });`

**Comment by jacoblee93** [comment]
This looks like Azure OpenAI? What agent are you using/are you able to test with stock OpenAI?

If you're using the OpenAI functions agent, that relies on function calling capability and I'm not sure if Azure OpenAI supports that.
