### ISSUE TITLE
Module '"langchain/embeddings/openai"' has no exported member 'OpenAIEmbeddings'

### ISSUE THREAD

**Issue by bonnlei** [langchain-ai/langchainjs#3077]
I use langchain 0.0.174 by Typescript:
import {OpenAIEmbeddings} from "langchain/embeddings/openai";

**Comment by bonnlei** [comment]
i think you have to update openai package at first.

**Comment by jacoblee93** [comment]
Are you able to import other modules? Can you give more information about your setup?

**Comment by jacoblee93** [comment]
Unable to repro but feel free to reopen if you have more info.

**Comment by bonnlei** [comment]
"dependencies": {
    "@headlessui/react": "^1.7.17",
    "@supabase/supabase-js": "^2.38.4",
    "@tailwindcss/forms": "^0.5.6",
    "@vercel/analytics": "^1.1.1",
    "ai": "^2.2.20",
    "langchain": "^0.0.174",
    "next": "13.5.6",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },

**Comment by Santy1422** [comment]
"langchain": "git+https://github.com/Santy1422/lanchain-embeding.fix.git#main",

**Comment by jacoblee93** [comment]
Please open a PR if you are able to figure it out!
