### ISSUE TITLE
OpenAIEmbeddings configuration of baseURL is not possible

### ISSUE THREAD

**Issue by truedat101** [langchain-ai/langchainjs#3086]
Reviewing the source code and investigating the API docs: 
https://js.langchain.com/docs/api/embeddings_openai/classes/OpenAIEmbeddings

and the source:
https://github.com/langchain-ai/langchainjs/blob/0.0.175/langchain/src/embeddings/openai.ts

for OpenAIEmbeddings JS I was trying to understand how to provide my own baseURL and not use the default openai.com endpoint.  This seems not to be possible unless using Azure services.  But there are enough ambiguities in the docs that I wasn't willing to give up.

I asked the docs as I was confused as to why I can't set my own baseURL / apiUrldirectly (in case I am not using openAI.com).  I asked the chatbot directly:

Response was:

```  

const { OpenAIEmbeddings } = require('langchain');


• Create an instance of the OpenAIEmbeddings class, passing the necessary configuration options:

const embeddings = new OpenAIEmbeddings({
  apiKey: 'your-api-key',
  apiUrl: 'https://your-api-url',
  apiVersion: 'your-api-version',
  organizationId: 'your-organization-id',
  proxy: 'http://your-proxy-server',
  timeout: 5000,
});

```

If I run the above code, this doesn't do anything.  It still calls api.openai.com.  If I provide { configuration :  { come config } } I can provide an api key, but anything I put in there related to baseURL doesn't work.  To sort out the confusion, I looked through the source and say that it might be possibly if one can specify the OpenAI client.  But I cannot figure out how to pass in a client object (from the OpenAI module) without modifying the langchain source.

Seeking clarification on how to set the baseURL or ApiURL or OpenAI client for OpenAIEmbeddings js.

**Comment by jacoblee93** [comment]
Bot response is correct, closing for now although we should document better.

**Comment by truedat101** [comment]
Hmm, so apiUrl is correct to use and so is baseURL?  I will retest, and verify if this is indeed working.
