### ISSUE TITLE
ChatOpenAI breaks edge streaming on Vercel Edge functions.

### ISSUE THREAD

**Issue by altechzilla** [langchain-ai/langchainjs#3092]
ChatOpenAI breaks edge streaming on Vercel Edge functions.

**Error**:
```
../../node_modules/.pnpm/openai@4.4.0/node_modules/openai/core.mjs
A Node.js API is used (process.arch at line: 531) which is not supported in the Edge Runtime.
```

**Import trace for requested module:**
```
../../node_modules/.pnpm/openai@4.4.0/node_modules/openai/core.mjs
../../node_modules/.pnpm/openai@4.4.0/node_modules/openai/index.mjs
../../node_modules/.pnpm/langchain@0.0.175_axios@1.6.0_mammoth@1.6.0/node_modules/langchain/dist/chat_models/openai.js
../../node_modules/.pnpm/langchain@0.0.175_axios@1.6.0_mammoth@1.6.0/node_modules/langchain/chat_models/openai.js
```
...

**The import causing the error:**
`import { ChatOpenAI } from 'langchain/chat_models/openai';`

**Potential Solution:**
If the native OpenAI library doesn't support edge streaming / functions, then LangChain should implement that chat module via a native fetch.

**Comment by jacoblee93** [comment]
What bundler are you using?

Have noticed this warning in our tests but we use this live in production with Webpack + Next pretty frequently, so I assumed the bundler was smart enough to filter it out:

https://github.com/langchain-ai/langchain-nextjs-template

**Comment by jacoblee93** [comment]
CC @rattrayalex is it possible to remove references like this?

**Comment by rattrayalex** [comment]
Hey @jacoblee93 , thanks for the ping. We don't actually call that at runtime on that platform, so I'd consider it a bug/problem with the import tracer… but I can see if I can move that code into another file.

**Comment by rattrayalex** [comment]
Ah, I see the user is on `openai@4.4.0`, can you try with a later version? We've made improvements to related areas and I wonder if it'd be fixed. 

Also, I'm a bit surprised to see `.cjs` used in a Next build instead of `.mjs`, know what might be up with that?

**Comment by jacoblee93** [comment]
Yes, definitely a bundler/chunking issue.

Ok will try bumping the version! Thanks for the look.

**Comment by jacoblee93** [comment]
Please reopen if this persists past the next release
