### ISSUE TITLE
Style: Parts of the mendable AI popup are inaccessible on smaller devices.

### ISSUE THREAD

**Issue by Keith-Web3** [langchain-ai/langchainjs#3103]
My device has a `1366 x 768` display. The fixed position on one of the parents of the Mendable AI dialog causes it not to scroll to the bottom where the input box is. The only way I can scroll further is to zoom out on my screen.
Here's an image of where the scroll stopped when I tried scrolling to the bottom.
![Screenshot (319)](https://github.com/langchain-ai/langchainjs/assets/96974022/847805c7-e407-48bd-833d-624728782376)

**Comment by jacoblee93** [comment]
CC @nickscamara can you have a look?

**Comment by nickscamara** [comment]
@jacoblee93 yep! Just opened a ticket on our end.
