### ISSUE TITLE
ChatBaiduWenxin No response

### ISSUE THREAD

**Issue by zandko** [langchain-ai/langchainjs#3115]
Whether it is the direct use of the model or the chain, it is a direct response and fast. Generally speaking, it should not respond so quickly, and no error has been detected.

![IMG-2023-11-01-16 43 30@2x](https://github.com/langchain-ai/langchainjs/assets/37948383/4951ff35-f1f2-46bc-9b91-e91fe38864a1)
![IMG-2023-11-01-16 43 45@2x](https://github.com/langchain-ai/langchainjs/assets/37948383/d3027615-370e-4741-8717-2c8ccabbe038)

```ts
export type HubChatBaiduWenxinInput = Partial<BaiduWenxinChatInput> & BaseChatModelParams;

export class HubChatBaiduWenxin extends ChatBaiduWenxin {
  constructor(fields: HubChatBaiduWenxinInput) {
    super({
      baiduApiKey: BAIDU_API_KEY,
      baiduSecretKey: BAIDU_SECRET_KEY,
      temperature: 0.1,
      ...fields,
    });
  }
}
 const model = new HubChatBaiduWenxin({
      modelName: WenXinModel['ERNIE-Bot-4'],
      temperature: 0,
      callbacks: [
        {
          handleChainError(err) {
            console.log(err);
          },
          handleRetrieverError(err) {
            console.log(err, '======');
          },
        },
      ],
    });

    const messages = [new HumanMessage('Hello')];
    const res = await model.call(messages);
    console.log(res, '----->-----');
    const vectorStore = this.createVectorStore('knowledge');
    const relevantDocs = await vectorStore.similaritySearch(question);

    const chain = createLLMChain(QA_TEMPLATE, model);

    await chain
      .call(
        {
          context: relevantDocs.map((item) => item.pageContent).join('\n\n'),
          question,
          chatHistory: '',
        },
        [new ConsoleCallbackHandler()],
      )
      .then((res) => {
        console.log(res, '===========');
      })
      .catch((e) => {
        console.log(e, '-----');
      });
```

**Comment by jacoblee93** [comment]
CC @sunner can you have a look at this?

**Comment by sunner** [comment]
Goto https://console.bce.baidu.com/qianfan/chargemanage/list and click "开通付费" on ERNIE-Bot 4.0

Unfortunately, the API does return 200 status code with empty response under this situation. No error messages.

**Comment by zandko** [comment]
It will still be the same after paying, and it will still be the same with EB 3

**Comment by krelianhu** [comment]
> It will still be the same after paying, and it will still be the same with EB 3

hi, zandko, when you requested https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat/completions_pro, it just returned 200 status code with empty response body? Can you tell me how you use the ak/sk and can you give me a screenshot showing the original content returned by the server?

**Comment by zandko** [comment]
![IMG-2023-11-02-10 52 34@2x](https://github.com/langchain-ai/langchainjs/assets/37948383/bcd512e0-4220-4809-9382-b0ce0a464363)

**Comment by krelianhu** [comment]
> ![IMG-2023-11-02-10 52 34@2x](https://user-images.githubusercontent.com/37948383/279852478-bcd512e0-4220-4809-9382-b0ce0a464363.png)

It looks like the return from the server is Ok. I don't quite understand in which case the server returns empty response?

**Comment by zandko** [comment]
```ts
class HubChatBaiduWenxin extends ChatBaiduWenxin {
  constructor(fields: HubChatBaiduWenxinInput) {
    super({
      baiduApiKey: BAIDU_API_KEY,
      baiduSecretKey: BAIDU_SECRET_KEY,
      temperature: 0.1,
      ...fields,
    });
  }
}
  const chat = new HubChatBaiduWenxin({
      temperature: 0,
    });

    const resp = await chat.call([new HumanMessage('hi')]);

    console.log(resp, '------');
```
![IMG-2023-11-02-11 16 58@2x](https://github.com/langchain-ai/langchainjs/assets/37948383/2d1741cb-35d0-4cbe-8b81-bc6bafb97c31)


```ts
const chat = new HubChatBaiduWenxin({
      temperature: 0,
      modelName: WenXinModel['ERNIE-Bot-4'],
    });

    const resp = await chat.call([new HumanMessage('hi')]);

    console.log(resp, '------');
```
![IMG-2023-11-02-11 18 53@2x](https://github.com/langchain-ai/langchainjs/assets/37948383/4fdeeb7a-d58e-47fe-bcf7-2e8151eb2136)

**Comment by zandko** [comment]
I don't quite understand either.

**Comment by PeterPanZH** [comment]
I will check what's going wrong. Thanks for your reporting.

**Comment by PeterPanZH** [comment]
The problem is you set `temperature` as 0.
You can refer to the document [https://cloud.baidu.com/doc/WENXINWORKSHOP/s/clntwmv7t](https://cloud.baidu.com/doc/WENXINWORKSHOP/s/clntwmv7t) for more details.

![CleanShot 2023-11-02 at 14 18 49@2x](https://github.com/langchain-ai/langchainjs/assets/3366499/f3a1041d-b9b0-423d-9a1f-f62365d6c3e9)

We will return an error in a future version in this case. Again thank you for your report :)

**Comment by zandko** [comment]
Please note that the screenshot of the code I provided has been set to 0.

**Comment by weiexcelpro** [comment]
> Please note that the screenshot of the code I provided has been set to 0.

上面是说temperature不能为0, 如果temperature设成0就会出错(但不会报错, 未来会添加个报错给用户)
你的截图里看着temperature的确是0, 所以就出错, 同时没有报错.

**Comment by zandko** [comment]
OK, I misread it.

**Comment by PeterPanZH** [comment]
> Please note that the screenshot of the code I provided has been set to 0.

0 is not a legal value of temperature.
