### ISSUE TITLE
Token count interface not unified: estimatedTokenUsage (openai) vs tokenUsage (baiduwenxin)

### ISSUE THREAD

**Issue by lukywong** [langchain-ai/langchainjs#3116]
When i try to use token count of chat models on streaming mode, i found the llmOutput results are different for openai and baiduweixin
for openai i must use **estimatedTokenUsage** but **tokenUsage** for baiduwenxin instead, could we use the same interface
**tokenUsage** ?
- openai 
```json
{
    "generations": [],
    "llmOutput": {
        "estimatedTokenUsage": {
            "completionTokens": 5,
            "promptTokens": 296,
            "totalTokens": 524
        }
    }
}
```

- baiduwenxin
```json
{
    "generations": [],
    "llmOutput": {
        "tokenUsage": {
            "completionTokens": 5,
            "promptTokens": 296,
            "totalTokens": 524
        }
    }
}

**Comment by jacoblee93** [comment]
Hey @lukywong, OpenAI doesn't actually send usage back for streaming requests, so we've named it `estimatedTokenUsage` to emphasize that they may not be entirely accurate. Would prefer to leave it that way so people don't assume it's official.

**Comment by lukywong** [comment]
@jacoblee93 Thank you, it seems usage was not enabled by default on streaming mode for some reason, i've sent a request to official

<img width="813" alt="image" src="https://github.com/langchain-ai/langchainjs/assets/1433871/d227b67b-e5d9-4f2c-885c-3bdd8d381aea">


<img width="415" alt="image" src="https://github.com/langchain-ai/langchainjs/assets/1433871/b4687f81-c087-4ba3-bb2b-f5610fb445d9">
