### ISSUE TITLE
Add support for cohere-embed v3.0

### ISSUE THREAD

**Issue by ojpetar** [langchain-ai/langchainjs#3138]
The new cohere embed models have an additional mandatory parameter that needs to get passed when creating embeddings - would be awesome to get langchain support for this!

New embed endpoint docs + docs on additional parameters: https://txt.cohere.com/introducing-embed-v3/

**Comment by bracesproul** [comment]
Hey @ojpetar it looks like cohere's typescript SDK does not currently support it, however there is a PR up in their repo with an implementation. Once that PR is merged we'll add support here!

**Comment by squamos** [comment]
@bracesproul can you link to the open issue in cohere's typesccript sdk to follow? having the same issue

**Comment by bracesproul** [comment]
> @bracesproul can you link to the open issue in cohere's typesccript sdk to follow? having the same issue

There isn't an open issue however [this is the PR ](https://github.com/cohere-ai/cohere-typescript/pull/100)which added support in their repo

**Comment by squamos** [comment]
Thanks @bracesproul - how often do you publish npm version updates? Looking forward to trying this out!

**Comment by bracesproul** [comment]
> Thanks @bracesproul - how often do you publish npm version updates? Looking forward to trying this out!

We'll publish one tonight! Normally we do it at the end of business hours PST (ish).
