### ISSUE TITLE
SupabaseVectorStore: custom fields are omitted in addDocuments

### ISSUE THREAD

**Issue by tom-bywild** [langchain-ai/langchainjs#3155]
### Description

`addDocuments` in `SupabaseVectorStore` uses its `addVectors` to store data in Supabase, but `addVectors` removes all custom fields from the document. Only `content`, `embeddings`, `metadata` are kept.

In a somewhat more complex project, the DB-schema might include other fields as well (therefore extending the `Document`-interface from Langchain.js). Using the current implementation with Langchain.js doesn't allow storing those custom fields. A workaround would be to update the entities after `addVectors` has succeeded, which is not ideal (and could introduce consistency issues within the application).

### Potential solution

A fix would be to simply not filterout all non-`Document` related fields in [`addVectors`](https://github.com/langchain-ai/langchainjs/blob/24e5d65/langchain/src/vectorstores/supabase.ts#L106):

```diff
- const rows = vectors.map((embedding, idx) => ({
-   content: documents[idx].pageContent,
-   embedding,
-   metadata: documents[idx].metadata,
- }));

+ const rows = vectors.map((embedding, idx) => {
+   const { pageContent, ...rest } = documents[idx];
+   return {
+     embedding,
+     content: pageContent,
+     ...rest,
+    };
+ });
```

**Comment by sajas-nm** [comment]
wy is this issure closed ? i am still facing this issue

**Comment by sami-azzam** [comment]
Any news on this?
