### ISSUE TITLE
WebPDFLoader not working

### ISSUE THREAD

**Issue by pichlerpa** [langchain-ai/langchainjs#3164]
Hi, I am having problems with parsing PDF in the web/browser (no server/nodejs) which seem to be possbile according to the documentation: https://js.langchain.com/docs/integrations/document_loaders/web_loaders/pdf.

This is the code I am using, I also tried to use a custom pdf.js build which works in case of using it directly. However, when I try to use the WebPDFLoader I always get the error of missing the fs module, see screenshot below. Any idea?

```
import * as PDFLib from 'pdfjs-dist/build/pdf';
import { WebPDFLoader } from "langchain/document_loaders/web/pdf";
PDFLib.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${PDFLib.version}/pdf.worker.min.js`;
export async function handlePDFFile(selectedFile) {

  // Load PDF document into array buffer
  const arrayBuffer = await selectedFile.arrayBuffer();

  const loader = new WebPDFLoader(arrayBuffer, { splitPages: false });
  // const loader = new WebPDFLoader(arrayBuffer, {
  //   pdfjs: ()=>{ 
  //       PDFLib.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${PDFLib.version}/pdf.worker.min.js`;
  //       return PDFLib;
  //   },
  // });
  const pdfDocument = await loader.load();

  // // Load the PDF document using PDF.js natively
  // const arrayBufferUint8 = new Uint8Array(arrayBuffer);
  // const pdfDocument = await PDFLib.getDocument(arrayBufferUint8).promise;
  
  return pdfDocument
}
```

![image](https://github.com/langchain-ai/langchainjs/assets/35483858/2d3b882e-f382-44ca-8bd2-0f9103cde059)

PS: Unfortunately, I don't have access to the webpack.config.js in my case.

Thanks,
Patrick

**Comment by Ghack929309** [comment]
If you're using Next.js and you encounter this issue, you can follow these steps:

1-Create a folder in the root called mocks and create a file named fs.js. Add the following code:
```js 
module.exports = {};
```
2- open your next config  add this followind snippet:
```js
const path = require('path');
module.exports = {
  webpack: (config, { isServer }) => {
    if (!isServer) {
      // Fix for pdf-parse issue with 'fs' module on client-side
      config.resolve.alias['fs'] = path.resolve(__dirname, './mocks/fs.js');
    }
    return config;
  },
}`
 leave a 👍 if this is helpful and 👎 if it is irrelevant.

**Comment by jacoblee93** [comment]
Sorry for the late response - can you also try just using `yarn add pdf-parse` and not importing it? It might just be that pdf-parse build?

I've used it successfully here in a Next.js project:

https://github.com/jacoblee93/fully-local-pdf-chatbot/blob/main/app/worker.ts#L5

Please reopen if that doesn't fix it.
