### ISSUE TITLE
streaming is not working with titan model (amazon.titan-text-express-v1)

### ISSUE THREAD

**Issue by yadavPavan94** [langchain-ai/langchainjs#3179]
import { userHashedId } from "@/features/auth/helpers";
import { CosmosDBChatMessageHistory } from "@/features/langchain/memory/cosmosdb/cosmosdb";
import { ConversationChain } from "langchain/chains";
import { BufferWindowMemory } from "langchain/memory";
import {
  PromptTemplate,
} from "langchain/prompts";
import { Bedrock } from "langchain/llms/bedrock";
import { initAndGuardChatSession } from "../chat-services/chat-thread-service";
import { PromptGPTProps } from "../chat-services/models";
import { transformConversationStyleToTemperature } from "../chat-services/utils";
import { LangChainStream, StreamingTextResponse } from "ai";
const templates: { [key: string]: string } = {
  //gpt-4 titan gpt-3.5 claude
  "gpt-3.5": `\n\nHuman:The following is a conversation between a human and an AI.
  The AI is responsible to answer questions related to cpg,retail,industrial,mathematical,bfsi,analytical,finance,engineering,general knowledge,logical,reasoning,network, security,safety,companies etc.
  The AI is talkative, knowledgeable helpful assistant and provides lots of details from all the domains .
  The AI should provide information about anything you want.
  If the AI does not know the answer to a question, it truthfully says it does not know.
   
  Current conversation:
  {history}
  {input}\n\nAssistant:`,
  "gpt-4": `\n\nHuman:The following is a conversation between a human and an AI.
  The AI is talkative, knowledgeable helpful assistant and provides lots of details from all the domains .
  The AI should provide information about anything you want.
   
   
  Current conversation  :
  {history}
  {input}
  AI:\n\nAssistant:`
}
export const ChatSimple = async (props: PromptGPTProps) => {
  const { stream, handlers } = LangChainStream();
  const { lastHumanMessage, id, chatThread, model } =
    await initAndGuardChatSession(props);

  console.log("model", model);
  //const { stream, handlers } = LangChainStream();

  const userId = await userHashedId();

  const llm = new Bedrock({
    model:
      model == "gpt-4"
        ? process.env.BEDROCK_MODEL_TITAN
        : process.env.BEDROCK_MODEL_CLAUDE,
    region: process.env.BEDROCK_REGION ?? "",
    credentials: {
      accessKeyId: process.env.BEDROCK_AWS_ACCESS_KEY_ID ?? "",
      secretAccessKey: process.env.BEDROCK_AWS_SECRET_ACCESS_KEY ?? "",
    },
    temperature: transformConversationStyleToTemperature(
      chatThread.conversationstyle
    ),
    maxTokens: 800,
    streaming: true
  //  modelKwargs: getKwargs(model),
  });
  const memory = new BufferWindowMemory({
    k: 100,
    returnMessages: true,
    memoryKey: "history",
    chatHistory: new CosmosDBChatMessageHistory({
      sessionId: id,
      userId: userId,
    }),
  });
  

  const chatPrompt = new PromptTemplate({
    inputVariables: ["history", "input"],
    template: templates[model]
  })

  const chain = new ConversationChain({
    llm,
    memory,
    prompt: chatPrompt,
    verbose: false
  });

  //const result = await chain.call({ input: lastHumanMessage.content });
  chain.call({ input: lastHumanMessage.content }, [handlers]);
  // let answer = result["response"];
  // return new Response(answer);

  return new StreamingTextResponse(stream);
};

**Comment by jacoblee93** [comment]
Not all models support streaming in multiple chunks unfortunately - I believe Titan is currently one of them. Will leave open for now but can't fix until Bedrock supports it.

**Comment by ninjamaster1337** [comment]
Looks like on their docs, titan supports streaming through the invoke-with-response-stream method

https://docs.aws.amazon.com/bedrock/latest/APIReference/API_runtime_InvokeModelWithResponseStream.html

**Comment by gkgourav45** [comment]
I am also facing same issue. Streaming works fine with claude model but not with titan model. Tried directly using bedrock apis of titan streaming works fine.
