### ISSUE TITLE
Currently, rags is only working with titan model and not working with claude model (anthropic.claude-v2)  for ConversationalRetrievalQAChain

### ISSUE THREAD

**Issue by yadavPavan94** [langchain-ai/langchainjs#3180]
getting below error : 
[chain/error] [1:chain:ConversationalRetrievalQAChain] [8.60s] Chain run errored with error: "Error 400: Invalid prompt: prompt must start with \"\n\nHuman:\" turn, prompt must end with \"\n\nAssistant:\" turn"
Error: Error 400: Invalid prompt: prompt must start with "

Human:" turn, prompt must end with "

Assistant:" turn
    at Bedrock._call (webpack-internal:///(rsc)/./node_modules/langchain/dist/llms/bedrock.js:166:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)  
    at async Promise.all (index 0)
    at async Bedrock._generate (webpack-internal:///(rsc)/./node_modules/langchain/dist/llms/base.js:296:29)
    at async Bedrock._generateUncached (webpack-internal:///(rsc)/./node_modules/langchain/dist/llms/base.js:159:22)
    at async LLMChain._call (webpack-internal:///(rsc)/./node_modules/langchain/dist/chains/llm_chain.js:126:33)
    at async LLMChain.call (webpack-internal:///(rsc)/./node_modules/langchain/dist/chains/base.js:111:28)
    at async LLMChain.predict (webpack-internal:///(rsc)/./node_modules/langchain/dist/chains/llm_chain.js:145:24)
    at async RefineDocumentsChain._call (webpack-internal:///(rsc)/./node_modules/langchain/dist/chains/combine_docs_chain.js:375:19)
    at async RefineDocumentsChain.call (webpack-internal:///(rsc)/./node_modules/langchain/dist/chains/base.js:111:28)
    at async ConversationalRetrievalQAChain._call (webpack-internal:///(rsc)/./node_modules/langchain/dist/chains/conversational_retrieval_chain.js:145:24)
    at async ConversationalRetrievalQAChain.call (webpack-internal:///(rsc)/./node_modules/langchain/dist/chains/base.js:111:28)
    at async ChatSimpleWithContext (webpack-internal:///(rsc)/./features/chat/chat-context/chat-context-api.ts:98:24)
    at async PromptGPT (webpack-internal:///(rsc)/./features/chat/chat-services/chat-api.ts:14:20)
    at async POST (webpack-internal:///(rsc)/./app/api/chat/route.ts:9:12)
    at async eval (webpack-internal:///(rsc)/./node_modules/next/dist/server/future/route-modules/app-route/module.js:253:37)

-  ┌ POST /api/chat 500 in 18569ms
   │
   ├──── POST https://bedrock-runtime.../model/anthropic.claude-.. 200 in 3847ms (cache: MISS)

code below :
import { userHashedId } from "@/features/auth/helpers";
import { CosmosDBChatMessageHistory } from "@/features/langchain/memory/cosmosdb/cosmosdb";
 
import { NextResponse } from "next/server";
import { ConversationalRetrievalQAChain, LLMChain, loadQAChain } from "langchain/chains";
import { ChatOpenAI } from "langchain/chat_models/openai";
import { Bedrock } from "langchain/llms/bedrock";
import { OpenSearchVectorStore } from "langchain/vectorstores/opensearch";
import { Client } from "@opensearch-project/opensearch";
import { VectorDBQAChain } from "langchain/chains";
import { BedrockEmbeddings } from "langchain/embeddings/bedrock";
import { BufferWindowMemory } from "langchain/memory";
import {
  ChatPromptTemplate,
  HumanMessagePromptTemplate,
  PromptTemplate
} from "langchain/prompts";
//@ts-ignore
//@ts-ignore
import { initAndGuardChatSession } from "../chat-services/chat-thread-service";
import { PromptGPTProps } from "../chat-services/models";
import { transformConversationStyleToTemperature } from "../chat-services/utils";
 
 
// const getKwargs = function (model: string) {
//   if (model === "gpt-3.5") {
//     return { max_tokens_to_sample: 200 };
//   }
// };
 
export const ChatSimpleWithContext = async (props: PromptGPTProps) => {
  try {
    const { lastHumanMessage, id, chatThread, model } = await initAndGuardChatSession(
      props
    );
    const userId = await userHashedId();
    const BedrockChatllm = new Bedrock({
       model: model == "gpt-4" ? process.env.BEDROCK_MODEL_TITAN : process.env.BEDROCK_MODEL_CLAUDE,
     // model:process.env.BEDROCK_MODEL_TITAN,
      region: process.env.BEDROCK_REGION,
      credentials: {
        accessKeyId: process.env.BEDROCK_AWS_ACCESS_KEY_ID??'',
        secretAccessKey: process.env.BEDROCK_AWS_SECRET_ACCESS_KEY??''
      },
      temperature: transformConversationStyleToTemperature(
        chatThread.conversationstyle
      ),
      verbose: true,
      maxTokens: 800
    });
  
    const memory = new BufferWindowMemory({
      k: 2,
      returnMessages: true,
      memoryKey: "chat_history",
      chatHistory: new CosmosDBChatMessageHistory({
        sessionId: id,
        userId: userId,
      }),
    });
  const questionGenertor = new LLMChain({ llm: BedrockChatllm, prompt: condenseQuestionPrompt });
      const docChain = loadQAChain(BedrockChatllm, { type: "refine", refinePrompt: qaPrompt });

    const client = new Client({
        nodes: [process.env.OPEN_SEARCH_URL??''],
        ssl:{
          rejectUnauthorized: false
        }
      });
    const vectorStore = new OpenSearchVectorStore(
      new BedrockEmbeddings({
        model: "amazon.titan-embed-text-v1",
        region: process.env.BEDROCK_REGION,
        credentials: {
          accessKeyId: process.env.BEDROCK_AWS_ACCESS_KEY_ID??'',
          secretAccessKey: process.env.BEDROCK_AWS_SECRET_ACCESS_KEY??''
        },
      }),{
        client,
        indexName: process.env.OPENSEARCH_INDEX
      }
    );
    const cRetrieverchain = new ConversationalRetrievalQAChain(
      {
        memory: memory,
        combineDocumentsChain: docChain,
        questionGeneratorChain: questionGenertor,
        verbose: true,
        retriever: vectorStore.asRetriever({k:2}),
        returnSourceDocuments: false,
      });
    const result = await cRetrieverchain.call({ "question": lastHumanMessage.content })
    console.log("result", result);
    return new Response(result['output_text']);
  }catch(e: any) {
    console.log(e);
    return NextResponse.json({ error: e.message }, { status: 500 });
  }
 
}
const condenseQuestionTemplate = `Given the following conversation and a follow up question, rephrase the follow up question to be a standalone question, in its original language.

Chat History:
{chat_history}
Follow Up Input: {question}
Standalone question:`;
const qaTemplate = `As a helpful AI assistant, your task is to  provide answer by utilizing the available context and information to provide a more detailed response to the question.
If you lack knowledge on the topic, please respond with 'I don't know.' Do not attempt to fabricate an answer. 
In cases if the question is not related to the context, respond politely that your expertise is limited to answering context-relevant questions.

Only generate a proper answer for the given question based on the given context.Do not get answer from other sources.

Question: {question}
=========

{existing_answer}
{context}
=========`;
const condenseQuestionPrompt = new PromptTemplate({ inputVariables: ["chat_history", "question"], template: `\n\nHuman:${condenseQuestionTemplate}\n\nAssistant:` });
const qaPrompt = new PromptTemplate(
  {
    template: `\n\nHuman:${qaTemplate}\n\nAssistant:`,
    inputVariables: ["existing_answer", "context", "question"],
  });

**Comment by jacoblee93** [comment]
Anthropic has some more restrictive prompt requirements - we generally recommend people try the expression language version and customize the prompt in situations like this:

https://js.langchain.com/docs/expression_language/cookbook/retrieval#conversational-retrieval-chain

**Comment by thomasintl** [comment]
Might not be relevant  - but resolved this removing all leading newlines beforet he "Human: ..." 
All examples seen appears to have two line breaks initially - this does not work in my testing with AWS Bedrock
