### ISSUE TITLE
New update and error

### ISSUE THREAD

**Issue by Santy1422** [langchain-ai/langchainjs#3182]
`-----

> [stage-0 7/9] RUN --mount=type=cache,id=s/4a03b134-2200-4ef3-820e-858d0baf1751-/root/npm,target=/root/.npm npm i:

55.76 > whatsapp-botgpt@1.0.0 tsc

55.76 > tsc

55.76

65.23 node_modules/langchain/dist/base_language/index.d.ts(61,66): error TS2694: Namespace '"/app/node_modules/openai/resources/chat/completions".ChatCompletionCreateParams' has no exported member 'FunctionCallOption'.

65.32 npm ERR! code 2

65.32 npm ERR! path /app

65.32 npm ERR! command failed`

**Comment by Santy1422** [comment]
nothing, until yesterday's version it worked perfectly.

**Comment by jacoblee93** [comment]
Thanks for the heads up - I assume you're on `rc-0`?

**Comment by jacoblee93** [comment]
I think this may be because we allowed minor version OpenAI upgrades - if you haven't locked your deps and are on an older version, can you try upgrading to the latest?

**Comment by Santy1422** [comment]
i changed the import to require and it is working now thanks
