### ISSUE TITLE
node-llama-cpp chat streaming

### ISSUE THREAD

**Issue by kirankunigiri** [langchain-ai/langchainjs#3196]
[node-llama-cpp](https://github.com/withcatai/node-llama-cpp) supports chat response streaming [according to these docs](https://withcatai.github.io/node-llama-cpp/guide/chat-session#response-streaming). It would be great if this could be integrated with the langchain/llms/llama_cpp module. As mentioned in #2999, the streaming method was not implemented yet.

**Comment by jacoblee93** [comment]
@nigel-daniels are you up a stab at this?

**Comment by nigel-daniels** [comment]
I can take a look, I did think about it as I could see the node-llama-cpp offered streaming, but it returned chunks of tokens not promises, so I was not totally sure how to 'wrap it' appropriately.

**Comment by nigel-daniels** [comment]
Ok PR #3394 is in, this gets Llama2 streaming with the help from `node-llama-cpp` :)
