### ISSUE TITLE
claude model for ConversationalRetrievalQAChain with AWS Bedrock Embedding is not working but It is working with titan model very well..

### ISSUE THREAD

**Issue by yadavPavan94** [langchain-ai/langchainjs#3197]
> import { userHashedId } from "@/features/auth/helpers";
import { CosmosDBChatMessageHistory } from "@/features/langchain/memory/cosmosdb/cosmosdb";
 
import { NextResponse } from "next/server";
import { ConversationalRetrievalQAChain, LLMChain, loadQAChain } from "langchain/chains";
import { ChatOpenAI } from "langchain/chat_models/openai";
import { Bedrock } from "langchain/llms/bedrock";
import { OpenSearchVectorStore } from "langchain/vectorstores/opensearch";
import { Client } from "@opensearch-project/opensearch";
import { VectorDBQAChain } from "langchain/chains";
import { BedrockEmbeddings } from "langchain/embeddings/bedrock";
import { BufferWindowMemory } from "langchain/memory";
import {
  ChatPromptTemplate,
  HumanMessagePromptTemplate,
  PromptTemplate
} from "langchain/prompts";
//@ts-ignore
//@ts-ignore
import { initAndGuardChatSession } from "../chat-services/chat-thread-service";
import { PromptGPTProps } from "../chat-services/models";
import { transformConversationStyleToTemperature } from "../chat-services/utils";
 
 

 
export const ChatSimpleWithContext = async (props: PromptGPTProps) => {
  try {
    const { lastHumanMessage, id, chatThread, model } = await initAndGuardChatSession(
      props
    );
    console.log("inside chat-context-api.ts , model", model);
    const userId = await userHashedId();
    const BedrockChatllm = new Bedrock({
      **model: "anthropic.claude-v2",**
      region: process.env.BEDROCK_REGION,
      credentials: {
        accessKeyId: process.env.BEDROCK_AWS_ACCESS_KEY_ID??'',
        secretAccessKey: process.env.BEDROCK_AWS_SECRET_ACCESS_KEY??''
      },
      temperature: transformConversationStyleToTemperature(
        chatThread.conversationstyle
      ),
      verbose: true,
      maxTokens: 800
    });
  
    const memory = new BufferWindowMemory({
      k: 2,
      returnMessages: true,
      memoryKey: "chat_history",
      chatHistory: new CosmosDBChatMessageHistory({
        sessionId: id,
        userId: userId,
      }),
    });
  const questionGenertor = new LLMChain({ llm: BedrockChatllm, prompt: condenseQuestionPrompt });
      const docChain = loadQAChain(BedrockChatllm, { type: "refine", refinePrompt: qaPrompt });

    const client = new Client({
        nodes: [process.env.OPEN_SEARCH_URL??''],
        ssl:{
          rejectUnauthorized: false
        }
      });
    const vectorStore = new OpenSearchVectorStore(
      new BedrockEmbeddings({
        model: "amazon.titan-embed-text-v1",
        
        region: process.env.BEDROCK_REGION,
        credentials: {
          accessKeyId: process.env.BEDROCK_AWS_ACCESS_KEY_ID??'',
          secretAccessKey: process.env.BEDROCK_AWS_SECRET_ACCESS_KEY??''
        },
      }),{
        client,
        indexName: process.env.OPENSEARCH_INDEX
      }
    );
    const cRetrieverchain = new ConversationalRetrievalQAChain(
      {
        memory: memory,
        combineDocumentsChain: docChain,
        questionGeneratorChain: questionGenertor,
        verbose: true,
        retriever: vectorStore.asRetriever({k:2}),
        returnSourceDocuments: false,
      });
    const result = await cRetrieverchain.call({ "question": lastHumanMessage.content })
    console.log("result", result);
    return new Response(result['output_text']);
  }catch(e: any) {
    console.log(e);
    return NextResponse.json({ error: e.message }, { status: 500 });
  }
 
}
const condenseQuestionTemplate = `Given the following conversation and a follow up question, rephrase the follow up question to be a standalone question, in its original language.

Chat History:
{chat_history}
Follow Up Input: {question}
Standalone question:`;
const qaTemplate = `As a helpful AI assistant, your task is to  provide answer by utilizing the available context and information to provide a more detailed response to the question.
If you lack knowledge on the topic, please respond with 'I don't know.' Do not attempt to fabricate an answer. 
In cases if the question is not related to the context, respond politely that your expertise is limited to answering context-relevant questions.

Only generate a proper answer for the given question based on the given context.Do not get answer from other sources.

Question: {question}
=========

{existing_answer}
{context}
=========`;
const condenseQuestionPrompt = new PromptTemplate({ inputVariables: ["chat_history", "question"], template: `\n\nHuman:${condenseQuestionTemplate}\n\nAssistant:` });
const qaPrompt = new PromptTemplate(
  {
    template: `\n\nHuman:${qaTemplate}\n\nAssistant:`,
    inputVariables: ["existing_answer", "context", "question"],
  });

Note :
 In this code i am using AWS BEDROCK Embedding configuration for claude model. can give me answer claude model is suppoerted or not for embedding  model: "amazon.titan-embed-text-v1", which is working well with titan model (amazon.titan-text-express-v1). but not working with claude model.

**Comment by jacoblee93** [comment]
Sorry, I'm not exactly sure what you're asking - are you seeing an error with the above?

**Comment by yadavPavan94** [comment]
I am asking claude model is not working with AWS bedrock embedding but it working with tital model for same template.

**Comment by jacoblee93** [comment]
Define "not working"

**Comment by dqbd** [comment]
Hello @yadavPavan94! Looking at the provided code example, I can't seem to find anything egregious. Would it be possible to provide a reproducible example inside a repository?
