### ISSUE TITLE
LLM OS support

### ISSUE THREAD

**Issue by mujtabachang** [langchain-ai/langchainjs#3204]
LLM OS has been released.

It's amazing and free. For more details:
[https://github.com/llmOS/llmOS](https://github.com/llmOS/llmOS)

LLM OS can be integrated by using the following code in Python

```python
from langchain.chat_models import ChatOpenAI
from langchain.schema import AIMessage, HumanMessage, SystemMessage

chat = ChatOpenAI(temperature=0,
                    model="mistral-7b-instruct",
                    openai_api_base="https://api.llmos.dev/v1",
                    openai_api_key="YOUR_API_KEY_HERE"
                    )

messages = [
    SystemMessage(
        content="You are a helpful assistant that translates English to French."
    ),
    HumanMessage(
        content="Translate this sentence from English to French. I love programming."
    ),
]

result = chat(messages)

print(result)
```

However in LangChain JS, we do not have **`openai_api_base="https://api.llmos.dev/v1"`** param

Any plans to add this param in the JS version?

**Comment by mujtabachang** [comment]
I tested this out, although it seems to set the base URL correct, but when the fetch is called the URL is constructed incorrectly.  It is constructed as  **https://api.llmos.dev/v1/completions**, instead of  **https://api.llmos.dev/v1/chat/completions**

I tested without LangChainJS, and tried OpenAI's library. It works without any issues. It seems like LangChain's OpenAI's wrapper is not including "chat" in the URL

**Comment by jacoblee93** [comment]
Are you using the `ChatOpenAI` class?
