### ISSUE TITLE
[Feature Request] JS Client for LangServe: Browser only

### ISSUE THREAD

**Issue by pietz** [langchain-ai/langchainjs#3206]
I've started using `LangServe` to host my agents and chains. It was god-sent because it takes much of the hassle that I really don't want to deal with (async, streams, async + streams). I also saw that you provide a `RemoteRunnable` class to quickly embed the client in JavaScript but this **still requires a backend server**.

Would you consider building a small browser-only JS package that allows me to embed chains and agents hosted by langserve in a similiar way to:

```javascript
const chain = new RemoteRunnable({
  url: `http://localhost:8000/chain/invoke/`,
});
const result = await chain.invoke({
  topic: "cats",
});
```

I used some of your `fetchEventSource` code from the langserve playground but the more option I add, the uglier my code gets. I think there's a need here because you too needed to write this logic by hand when implementing the LangServe playground :)

What do you think?

**Comment by jacoblee93** [comment]
Will pass this along! Thanks for opening the issue.

**Comment by jacoblee93** [comment]
It's also worth noting that with bundle splitting LangChainJS is relatively small (O(10kb) gzipped I think?) - I should update the examples to emphasize that.

**Comment by jacoblee93** [comment]
See docs here: https://js.langchain.com/docs/ecosystem/langserve
