### ISSUE TITLE
help needed - how to modify output of each map chain before reduce step of a MapReduceDocumentsChain ?

### ISSUE THREAD

**Issue by stygmate** [langchain-ai/langchainjs#3214]
Everything is in the title,
I searched for hours...
anybody ?

**Comment by stygmate** [comment]
@dosu-bot in Python.

**Comment by bracesproul** [comment]
Hey @stygmate, for this you'll need to implement the chain using LCEL and from there you can modify its behavior however you'd wish!
An example of the map reduce chain in LCEL can be found [here](https://github.com/langchain-ai/langchain/blob/master/docs/docs/modules/chains/document/map_reduce.ipynb)
