### ISSUE TITLE
ChatOpenAI JSON Mode

### ISSUE THREAD

**Issue by ThomasDev28** [langchain-ai/langchainjs#3226]
Hello,

OpenAI recently released a new parameter ```response_format``` for Chat Completions called JSON Mode, to constrain the model to generate only strings that parse into valid JSON.
This mode was added because despite the instructions given in the prompt for a JSON output, the models sometimes generated an output that is not parsed as valid JSON.

It would be great to have this parameter in class ChatOpenAI !
See the documentation: https://platform.openai.com/docs/guides/text-generation/json-mode

**Comment by Systerr** [comment]
Are you looking for that ?

```js 
// Coerce response type with JSON mode.
// Requires "gpt-4-1106-preview" or later
const jsonModeModel = new ChatOpenAI({
  modelName: "gpt-4-1106-preview",
  maxTokens: 128,
}).bind({
  response_format: {
    type: "json_object",
  },
});
```

https://js.langchain.com/docs/integrations/chat/openai

**Comment by ThomasDev28** [comment]
Nice ! I did not see him...

**Comment by ThomasDev28** [comment]
> Are you looking for that ?
> 
> ```js
> // Coerce response type with JSON mode.
> // Requires "gpt-4-1106-preview" or later
> const jsonModeModel = new ChatOpenAI({
>   modelName: "gpt-4-1106-preview",
>   maxTokens: 128,
> }).bind({
>   response_format: {
>     type: "json_object",
>   },
> });
> ```
> 
> https://js.langchain.com/docs/integrations/chat/openai

Thank you, I hadn't seen it, but I get the following error: ```TypeError: this.llm.callKeys n'est pas itérable```

This references this piece of code:

```javascript
async _call(
    values: ChainValues & this["llm"]["CallOptions"],
    runManager?: CallbackManagerForChainRun
  ): Promise<ChainValues> {
    const valuesForPrompt = { ...values };
    const valuesForLLM: this["llm"]["CallOptions"] = {
      ...this.llmKwargs,
    };
    for (const key of this.llm.callKeys) {
      if (key in values) {
        valuesForLLM[key as keyof this["llm"]["CallOptions"]] = values[key];
        delete valuesForPrompt[key];
      }
    }
    const promptValue = await this.prompt.formatPromptValue(valuesForPrompt);
    const { generations } = await this.llm.generatePrompt(
      [promptValue],
      valuesForLLM,
      runManager?.getChild()
    );
    return {
      [this.outputKey]: await this._getFinalOutput(
        generations[0],
        promptValue,
        runManager
      ),
    };
  }

**Comment by jacoblee93** [comment]
If you're trying to pass it into a legacy LLM chain, we just merged #3200 which should support bound LLMs as inputs to LLMChain (CC @bracesproul). It's live in 0.0.186!

You can also pass call options (like `response_type`) as parameters directly (but it's a bit more magic):

```typescript
  const model = new ChatOpenAI({ modelName: "gpt-3.5-turbo-1106" });
  const prompt = new PromptTemplate({
    template: "Print {foo} as JSON",
    inputVariables: ["foo"],
  });
  const chain = new LLMChain({ prompt, llm: model });
  const res = await chain.call({ foo: "my favorite color", response_format: { type: "json_object" } });
  console.log({ res });
  ```

Please reopen if you continue to have trouble.

**Comment by ish-codes-magic** [comment]
Is there a similar python integration for the JSON mode? I am not able to find it.

**Comment by abhibeats95** [comment]
Any one know who to do this for python
