### ISSUE TITLE
OpenAI module not found/failed to load module in Supabase edge functions

### ISSUE THREAD

**Issue by j1philli** [langchain-ai/langchainjs#3242]
**Symptoms**
Getting this log output when running my edge functions in Supabase
`Failed to load module: "https://esm.sh/v133/openai@4.17.4/esnext/resources.js" - Import 'https://esm.sh/v133/openai@4.17.4/esnext/resources.js' failed, not found.`

VS Code is throwing an error this when caching dependencies
`Module not found "https://esm.sh/v133/openai@4.17.4/denonext/resources.js". at https://esm.sh/v133/openai@4.17.4/denonext/openai.mjs:7:13034`

**Looks like OpenAI isn't supporting esm.sh anymore for edge functions:**
https://github.com/openai/openai-node/issues/393#issuecomment-1797936535

Deno 1.38.1
Langchain .186

**Comment by jacoblee93** [comment]
For now, you can downgrade to 0.0.181, which should work - unfortunately not much we can do until the underlying SDK fixes it.

**Comment by j1philli** [comment]
@jacoblee93 the comment tagged in the issue sounds like they are not publishing to esm anymore

**Comment by jacoblee93** [comment]
Hopefully fixed by the above ^
