### ISSUE TITLE
`StructuredOutputParser` with OpenAI function calling?

### ISSUE THREAD

**Issue by Manouchehri** [langchain-ai/langchainjs#3249]
Is it possible to use `StructuredOutputParser` with OpenAI function calling, instead of `JsonOutputFunctionsParser`?

The issue with `JsonOutputFunctionsParser`, is that I can't provide it with a zod schema for type information.

**Comment by Manouchehri** [comment]
I've done this as a dirty workaround, but it's not pretty.

```typescript
const result = await model_az_oai_gpt4.invoke([new HumanMessage("What a beautiful day!")], {
  functions: [extractionFunctionSchema],
  function_call: { name: "extractor" }
});

const parser = StructuredOutputParser.fromZodSchema(mySchema);
const wat = await parser.invoke(result.additional_kwargs.function_call?.arguments!);
```

**Comment by jacoblee93** [comment]
You basically want it to verify that OpenAI's output matches the given schema?

**Comment by Manouchehri** [comment]
I assumed JsonOutputFunctionsParser was already doing that? 😅 

I just found a prettier way of doing it with `z.infer`... but am I making any unsafe assumptions here?

```typescript
// ...
const outputParser = new JsonOutputFunctionsParser();

const chain = prompt.pipe(functionCallingModel).pipe(outputParser);

const response = await chain.invoke({
  inputText: input_text,
}) as z.infer<typeof mySchema>;

// now I can do this:
console.log(response.tone); // .tone is an element in mySchema
```

**Comment by jacoblee93** [comment]
Yeah, it will not actually do any schema validation on output at the moment (since as you noted, you don't pass schema in).

OpenAI *should* be pretty good at it but yes I think this would be a nice addition (possibly with a retry mechanism?).

**Comment by Manouchehri** [comment]
Oh, that makes sense! I thought I was doing something wrong, didn't realize it wasn't a thing yet. 😅

This is more of a general question, but how do I have re-trying and caching play together nicely?

**Comment by jacoblee93** [comment]
We should have a more built-in flow but:

https://github.com/langchain-ai/langchainjs/blob/main/cookbook/basic_critique_revise.ipynb
