### ISSUE TITLE
Language Setting Issue in SummarizationChain: Korean Documents Summarized Only in English

### ISSUE THREAD

**Issue by drllr** [langchain-ai/langchainjs#3275]
## Issue Description
A problem has been identified with the SummarizationChain, where summaries are always generated in English regardless of the original document's language. For instance, when a Korean document is summarized using SummarizationChain, the resulting summary is produced only in English.

## Proposed Solution
I propose adding a 'target language' option in the config object when creating a SummarizationChain. This addition will enable users to generate summaries in their desired language. If the 'target language' is not specified, the summary should be created in the same language as the original document by default.

## Contribution Intent
I would like to contribute code to resolve this issue. I am prepared to implement the suggested solution to enhance the flexibility and usability of the SummarizationChain. I am also open to receiving and incorporating feedback and suggestions from the community.

Thank you.

**Comment by amellouki** [comment]
Hello @drllr,

I also would like a simple way to configure the language used by LangChain for its prompts, and it would be nice if we can configure that globally as well.

Currently If you're using [loadSummarizationChain](https://api.js.langchain.com/functions/chains.loadSummarizationChain.html) You can pass in your custom prompts in you're preferred language as part of the params, example creating a refined summarization:

```ts
const model = new OpenAI({ modelName: 'gpt-3.5-turbo' });

const params: SummarizationChainParams = {
  type: 'refine',
  refinePrompt: REFINE_PROMPT,
  questionPrompt: QUESTION_PROMPT,
};

const chain = loadSummarizationChain(model, params);
```

with the prompts being something like this:

```ts
const REFINE_PROMPT = new PromptTemplate({
  template:
    // in your language of choice
    'refine the following answer: {existing_answer} given the following text: {text} ANSWER:',
  inputVariables: ['existing_answer', 'text'],
});

const QUESTION_PROMPT = new PromptTemplate({
  // in your language of choice
  template: 'summarize the following text: {text} SUMMARY:',
  inputVariables: ['text'],
});
```

**Comment by jacoblee93** [comment]
Thanks @amellouki, yes you can customize the prompts there.

**Comment by drllr** [comment]
@amellouki thank you for your kind response!
