### ISSUE TITLE
'openai-functions' Agent is randomly stuck after a tool has completed its function

### ISSUE THREAD

**Issue by emmanuelvisage** [langchain-ai/langchainjs#3286]
We have an usual bug that is happening randomly. 
Sometimes our 'openai-functions' agent get stuck after a tool has finished to run. The next stage is never properly started and executed so eventually the agent times out. Every phase of the agent process seems to be working very fast but after a tool is called, the agent never takes over and it stays stuck until the timeout is reached.  

```
    const executor = await this.initializeAgentExecutorWithOptions(
      [
        new Tool1({
          foo
        }),
        new Tool2({
          bar,
        })
      ],
      new ChatOpenAI({
        openAIApiKey: <apiKey>,
        temperature: 0,
        streaming: true,
        modelName: 'gpt-4-1106-preview',
      }),
      {
        agentType: 'openai-functions',
        memory: new BufferWindowMemory({
          memoryKey: 'chat_history',
          inputKey: 'input',
          chatHistory: new RedisChatMessageHistory({
            sessionId: sessionId, 
            sessionTTL: 3000000,
            config: config.redis,
          }),
          returnMessages: true,
          k: 3,
        }),
        verbose: false,
        agentArgs: {
          prefix: prompt,
        },
      },
    );

    const response = await executor.call(
      {
        input: `${this.delimiter}\n${message}\n${this.delimiter}`,
        delimiter: this.delimiter,
        timeout: ONE_MINUTE,
        additional_context: JSON.stringify(additional_context_object),
      },
      [
        {
          handleLLMNewToken: onResponseToken, //send token to websocket
        },
      ],
    );
```

Do you know what could be causing this ?

**Comment by emmanuelvisage** [comment]
Irrelevant, like I said, when I look at the logs, the tools are executed just fine, and they aren't taking long. Whatever is stuck happens between when the tool has completed and send the output of the function to the agent.

**Comment by emmanuelvisage** [comment]
For the langchain team, here is a proof of that behavior shown in langsmith 
![Screenshot 2023-11-15 at 18 09 35](https://github.com/langchain-ai/langchainjs/assets/24440346/6329c033-60be-41e3-8c8b-1fef0773470a)
![Screenshot 2023-11-15 at 18 09 38](https://github.com/langchain-ai/langchainjs/assets/24440346/e4e82ebf-c189-42bb-873a-c3c71defc653)
![Screenshot 2023-11-15 at 21 51 12](https://github.com/langchain-ai/langchainjs/assets/24440346/0bb0656e-c0bb-474d-a532-6c03ed3c93fa)

**Comment by emmanuelvisage** [comment]
<img width="1662" alt="Screenshot 2023-11-16 at 00 28 19" src="https://github.com/langchain-ai/langchainjs/assets/24440346/b2c9e773-365c-4629-b669-078319a8ed90">
CPU is peaking really high while this issue is happening.

**Comment by emmanuelvisage** [comment]
Still no solution

**Comment by albcm-simetrik** [comment]
Same here

**Comment by jsfaber** [comment]
Same here

**Comment by tomaszstoryful** [comment]
same issue, agent getting stuck after retriever action complete + output returned
![Screenshot 2024-05-15 at 22 13 09](https://github.com/langchain-ai/langchainjs/assets/122275723/df363862-838a-4341-9f6c-36f94995019f)

**Comment by tpindred** [comment]
+1 to this issue.

**Comment by tpindred** [comment]
@emmanuelvisage were you able to find a way around this bug? I am encountering the exact same behavior in a langgraph agent. I'm considering getting some tokens at another LLM provider to see if this is just an issue with ChatOpenAI.
