### ISSUE TITLE
Support New Bedrock Embeddings (Cohere)

### ISSUE THREAD

**Issue by metaskills** [langchain-ai/langchainjs#3315]
New embedding are. Seems these use an `input_type` arg which I would like to use too.

* cohere.embed-english-v3
* cohere.embed-multilingual-v3

**Comment by BrianErikson** [comment]
As supplemental information that I found during my investigation, it appears that [embeddings/bedrock.ts#L88C15-L88C33](https://github.com/langchain-ai/langchainjs/blob/02ee2a0fa360b4ededaa51e956eda759f87ceb4c/langchain/src/embeddings/bedrock.ts#L88C15-L88C33) should be revised to accommodate the new cohere embedding schema on AWS Bedrock --
```
{
  "modelId": "cohere.embed-english-v3",
  "contentType": "application/json",
  "accept": "*/*",
  "body": {
    "texts": ["Hello world", "This is a test"],
    "input_type": "search_document"
 } 
}
```
[AWS Documentation on Cohere Embed input_type](https://docs.aws.amazon.com/bedrock/latest/userguide/model-parameters-cohere.html#model-parameters-embed)
Note that the existing schema still needs to be supported for existing Titan Embeddings users. 

Here's a sample of the current error:
`Error: An error occurred while embedding documents with Bedrock: Malformed input request: 3 schema violations found, please reformat your input and try again.`

**Comment by vishal-oogway** [comment]
I'd like to test cohere embeddings available on Bedrock and think this helper class would be really beneficial. Is it possible to get @BrianErikson 's contribution merged into community extensions ?

**Comment by KwangGan** [comment]
Is there any update on this ?
