### ISSUE TITLE
Example code for OpenAI functions agent seems wrong when using memory

### ISSUE THREAD

**Issue by humbertaco** [langchain-ai/langchainjs#3348]
Hi there! I noticed that the documentation for the OpenAI functions agent has recently been updated. I was checking it out and I noticed something that caught my attention.

[The section](https://js.langchain.com/docs/modules/agents/agent_types/openai_functions_agent#adding-memory) where the memory is added to the agent for previous iterations, the order of the messages seems to be wrong. The example code given in the documentation is the following:

```js
const prompt = ChatPromptTemplate.fromMessages([
  ["ai", "You are a helpful assistant"],
  ["human", "{input}"],
  new MessagesPlaceholder("agent_scratchpad"),
  new MessagesPlaceholder("chat_history"),
]);
```

Notice that the `chat_history` is added as the last element in this prompt.

The example can be inspected in LangSmith here: https://smith.langchain.com/public/2052d0d1-5640-44bc-9024-d443d46db2a4/r/87a1b796-5a70-46a9-bc57-016a3b6beee1. The image below shows the trace in LangSmith:

![image](https://github.com/langchain-ai/langchainjs/assets/6461554/107d2a97-5fcc-4782-b98c-5fb5d0993d26)

As can be seen in the image, the order of the messages that are passed as input to OpenAI is the following:

```
ai
You are a helpful assistant

human
Do I need a jacket?

human
What is the weather in New York?

ai
The current weather in New York is cloudy with a temperature of 58 degrees Fahrenheit. The humidity is at 72% with a wind speed of 8 mph. There's a 15% chance of precipitation.
```

However, I would expect the order to be this:

```
ai
You are a helpful assistant

human
What is the weather in New York?

ai
The current weather in New York is cloudy with a temperature of 58 degrees Fahrenheit. The humidity is at 72% with a wind speed of 8 mph. There's a 15% chance of precipitation.

human
Do I need a jacket?
```

This order would be consistent with the sequence of the questions asked by the human (first what is the weather in new york and then whether I need a jacket or not), it would also respect the human-ai sequence.

It seems to me that when creating the prompt, the code should be like this:

```js
const prompt = ChatPromptTemplate.fromMessages([
  ["ai", "You are a helpful assistant"],
  new MessagesPlaceholder("chat_history"),
  ["human", "{input}"],
  new MessagesPlaceholder("agent_scratchpad"),
]);
```

In this way, the chat history would appear first in the conversation, then the input, and finally the agent scratchpad to write down the observations by the agent when processing the human input.

Is this a typo when creating the documentation, or it is the intended behavior?

**Comment by humbertaco** [comment]
Then, that means that the documentation for OpenAI functions agent is wrong, doesn't it?

**Comment by jacoblee93** [comment]
Thanks for the ping!

@bracesproul I think @humbertaco is correct, can you fix?

**Comment by humbertaco** [comment]
Thanks for addressing this @jacoblee93, @bracesproul. By the way, I think both OpenAI agent's pages have this typo ([OpenAI functions](https://js.langchain.com/docs/modules/agents/agent_types/openai_functions_agent#adding-memory) and [OpenAI tool calling](https://js.langchain.com/docs/modules/agents/agent_types/openai_tools_agent#adding-memory)).

**Comment by rrichc** [comment]
Good catch, I was in the process of switching over from the conversational langchain agent to OpenAI tool calling, and was puzzled when the chain seemingly lost context after following the documentation. Switching the orders fixed my issue

**Comment by jacoblee93** [comment]
Will patch now, thanks

**Comment by rrichc** [comment]
Thanks @jacoblee93 !

**Comment by jacoblee93** [comment]
No thank you, really bad that this slipped through the cracks :(
