### ISSUE TITLE
MongoDB Vector Search not working with CohereEmbeddings

### ISSUE THREAD

**Issue by yaldram** [langchain-ai/langchainjs#3359]
I have the following code where I want to use MongoDB Atlas Vector Embeddings with CohereEmbeddings - 
```typescript
const vectorStore = new MongoDBAtlasVectorSearch(new CohereEmbeddings({
  apiKey: process.env.COHERE_API_KEY,
}), {
  collection: embeddingsCollection,
  indexName: "default", // The name of the Atlas search index. Defaults to "default"
  textKey: "text", // The name of the collection field containing the raw content. Defaults to "text"
  embeddingKey: "embedding", // The name of the collection field containing the embedded text. Defaults to "embedding"
});

const retriever = vectorStore.asRetriever({
    searchType: "mmr",
    searchKwargs: {
      fetchK: 20,
      lambda: 0.1,
    },
  });

const retrieverOutput = await retriever.getRelevantDocuments(question);
```

I am getting the following error - 
<img width="1620" alt="image" src="https://github.com/langchain-ai/langchainjs/assets/13429535/55a62881-633a-43bb-bdd9-5e16b97bf5f8">

Also how do I specify the new cohere embedding v3 options like `input_type` to the CohereEmbeddings.

**Comment by yaldram** [comment]
I did try the above, I am getting the same error, and its not about passing the `input_type` even this simple code is throwing the same error - 
```ts
const cohere = new CohereEmbeddings(process.env.COHERE_API_KEY);
```
Using CohereEmbeddings with MongoDB throws an error - 
```ts
const vectorStore = new MongoDBAtlasVectorSearch(cohereTwo, {
    collection: embeddingsCollection,
    indexName: "default", // The name of the Atlas search index. Defaults to "default"
    textKey: "text", // The name of the collection field containing the raw content. Defaults to "text"
    embeddingKey: "embedding", // The name of the collection field containing the embedded text. Defaults to "embedding"
  });

  const retriever = await vectorStore.asRetriever({
    searchType: "mmr",
    searchKwargs: {
      fetchK: 20,
      lambda: 0.1,
    },
  });

  const retrieverOutput = await retriever.getRelevantDocuments(question);

  console.log(retrieverOutput);
```

**Comment by jacoblee93** [comment]
V3 and the new Chroma SDK is not supported yet - there is a peer dependency conflict with @jeffchuber's Chroma.

CC @bracesproul

**Comment by jacoblee93** [comment]
We can also now split Chroma out, that actually might be a better approach.

**Comment by jeffchuber** [comment]
@jacoblee93 👋 hey-oh - what's going on and how can I help?

**Comment by jacoblee93** [comment]
Hey @jeffchuber! The Chroma.js peer dep on Cohere is behind the latest major version. Because of the restrictive way npm resolves peer deps, we can't upgrade until you do or we split out @langchain/chroma (which is better long term).
