### ISSUE TITLE
Getting `husky: not found` error on importing forked langchainjs

### ISSUE THREAD

**Issue by codenameakshay** [langchain-ai/langchainjs#3375]
I forked `langchainjs` and made some changes in it. Then I wanted to test it on my local project, so I imported it with the following line in my `package.json` -
```json
{
  "dependencies": {
    "langchain": "git+https://github.com/codenameakshay/langchainjs#5ecb788",
  },
}
```
Now when I run the command `yarn` I get the following output ->

![image](https://github.com/langchain-ai/langchainjs/assets/60510869/455c5200-1b4e-45d2-8ed9-270bcbb22fc9)

I get `husky: not found` error.

I tried importing the latest `0.0.196` version, and `yarn` command executes successfully.

**Comment by codenameakshay** [comment]
I added `"husky": "^7.0.4"` in the devDependencies, but I still get the error on running `yarn` command.

![image](https://github.com/langchain-ai/langchainjs/assets/60510869/4af5f86d-2000-4e27-8d53-84740f546e69)

**Comment by jacoblee93** [comment]
This was today?

**Comment by jacoblee93** [comment]
Dropped husky in #3383
