### ISSUE TITLE
Python Module's Indexing API Equivalent

### ISSUE THREAD

**Issue by MJDeligan** [langchain-ai/langchainjs#3390]
Hi,

I was previously working with langchain's python module, where I used the [Indexing API](https://python.langchain.com/docs/modules/data_connection/indexing) to upsert vectors into a postgres database.

I'm now working on a Javascript project and noticed that this API does not exist or is at least named differently. Is there an equivalent in the js-library?

Cheers

**Comment by MJDeligan** [comment]
The delete and add methods would enable the implementation of an indexing API à la python, but it's missing the storage of hashed documents in a separate DB. I'm pretty sure the bot is confusing the index of vector stores with the 'Indexing' API. Can anyone confirm that this functionality is not yet implemented?

**Comment by Leo310** [comment]
@MJDeligan how are you dealing with this problem now? Did you create your own indexing implementation?

**Comment by MJDeligan** [comment]
> @MJDeligan how are you dealing with this problem now? Did you create your own indexing implementation?

@Leo310  Yeah, since we use PgVector, I first implemented a wrapper around the vector store to implement the delete method and changed the add_* methods to accept ids. Then I translated the indexes api, including the Record Manager. I'd do a PR, but I can't get the repo to install locally, so I'll have to look into that. If I find the time, I can post the implementations that I currently have.

**Comment by Leo310** [comment]
@MJDeligan Ah ok nice. And I would really appreciate it if you could post the implementation or link me to it :)

**Comment by Leo310** [comment]
@MJDeligan do you think you will share your implementation? If not, no problem, I just need to know, because then I will have to create my own

**Comment by MJDeligan** [comment]
Hey @Leo310 , sorry for the delay! I put together a [gist](https://gist.github.com/MJDeligan/f01df6bd952a707fc20b8ed678782ac9) for reference. Beware that I just ripped this from the code base (with permission) and that it has not been used extensively, so I would definitely be careful. The HashedDocument, in our case, depends on an environment variable to get the namespace UUID, but you can also set a static one. Also the record manager uses the pg-format library, since I didn't wanna bother with writing templating functions to avoid SQL-Injections. 

Hope this helps and sorry for the messy code.

**Comment by Leo310** [comment]
@MJDeligan awesome, thanks a lot 👍

**Comment by MJDeligan** [comment]
Hey @jacoblee93 , are there currently any plans for this? I'd love to contribute.

**Comment by jacoblee93** [comment]
We'd love to do it but I haven't had the capacity yet 😢 would love a contribution if you're willing to take a run at it!

**Comment by MJDeligan** [comment]
Sure thing! Couple of questions:

The structure of this feature in the Python repo isn't quite clear to me (there's some duplication). I'm assuming the index function and RecordManager interface should be located under `/langchain/src/indexes` and implementations of the RecordManager under `/langchain-community/src/indexes`? Should both a RecordManagerInterface and an abstract RecordManager class extending Serializable be provided?

The Python version has a single SQLRecordManager which executes different code based on the database type, but only Postgres and Sqlite are supported. For the moment, I would rather implement a PostgresRecordManager and/or SQLiteRecordManager separetely, because it makes the implementation less complex and doesn't force the user to also install something like TypeORM. Of course a general implementation could be added later for users who are already using TypeORM for example. Does that seem reasonable?

**Comment by trulymittal** [comment]
@MJDeligan are there any updates, when ur going to create a PR

**Comment by Leo310** [comment]
Is there any progress on integrating indexing into langchainjs?

**Comment by jacoblee93** [comment]
Live in the next version!
