### ISSUE TITLE
Agent streaming - stream final output and steps

### ISSUE THREAD

**Issue by david1542** [langchain-ai/langchainjs#3398]
Hi everyone. I have 2 questions related to agents and streaming:

1. **Stream steps**
I'm trying to listen to my agent's actions in real time and notify the user about them in my UI. I noticed a [new PR](https://github.com/langchain-ai/langchainjs/pull/3365) with agent streaming capabilities has been merged to main in last couple of days, that allows consumers to receive agent's actions in real time.

This is my agent's code:
```ts
const memory = new BufferMemory({
  returnMessages: true,
  memoryKey: "history",
});
const model = new ChatOpenAI({
  modelName: "gpt-3.5-turbo-1106",
  temperature: 0,
  openAIApiKey: getConfigValue("openaiToken"),
  verbose: true,
}).bind({ tools: tools.map(formatToOpenAITool) });

const prompt = ChatPromptTemplate.fromMessages([
  ["ai", PREFIX],
  new MessagesPlaceholder("history"),
  ["human", "{input}"],
  new MessagesPlaceholder("agent_scratchpad"),
]);

const agent = RunnableSequence.from([
  {
    input: (i: { input: string; steps: ToolsAgentStep[] }) => i.input,
    agent_scratchpad: (i: { input: string; steps: ToolsAgentStep[] }) =>
      formatToOpenAIToolMessages(i.steps),
    history: () => memory.chatHistory.getMessages(),
  },
  prompt,
  model,
  new OpenAIToolsAgentOutputParser(),
]).withConfig({ runName: "OpenAIToolsAgent" });

const executor = AgentExecutor.fromAgentAndTools({
  agent,
  tools,
  memory,
});
```

And this is how I use it:
```ts
const response = await executor.stream(
  { input: prompt },
  {
    callbacks: [new VSCodeCallbacks()],
  }
);

let output;
for await (const chunk of response) {
  console.log(`Streamed chunk: ${JSON.stringify(chunk)}`);
  output = chunk.output;
}
```

However, when I look at the logs, the only time I see the console.log statement is when the agent finishes and provides the final answer. The intermediate steps (tool callings) are not given to me. This is the only log statement I see:

```
Streamed chunk: {"output":"some chatgpt response"}
```

I was wondering how can I achieve this kind of functionaliy. I know I can attach a callback manager to the `.call` and listen to `handleAgentAction` but I was wondering if there is a more neat way of doing that.

2. **Stream final output**
Is there a way to stream the final output in chunks? Sometimes, the final output is long, and I'd like to show it to the user chunk by chunk, like using the native OpenAI SDK. I noticed there is a solution in the [Python version](https://python.langchain.com/docs/modules/agents/how_to/streaming_stdout_final_only). Is there a solution in the JS version as well?

**Comment by Falven** [comment]
Yes, it seems like [OpenAI tool calling](https://js.langchain.com/docs/modules/agents/agent_types/openai_tools_agent) agent streaming is broken right now. The token callback manner of logging updates also does not work.

**Comment by jacoblee93** [comment]
Hey, apologies for missing this! Will have a look as soon as I can (hopefully within the next few days)!

**Comment by danny-avila** [comment]
> Hey, apologies for missing this! Will have a look as soon as I can (hopefully within the next few days)!

Thanks so much!

**Comment by kevsjh** [comment]
I notice this as well that agent streaming does not seems to work. But streamLog works ok

```
    const stream = await agentExecutor.streamLog({
      input: "what is the weather in SF and then LA",
      chatHistory: previousMessages,
    });

    for await (const chunk of stream) {
      console.log(JSON.stringify(chunk, null, 2));
      console.log("------");
    }
```

**Comment by bracesproul** [comment]
Hey @david1542 sorry for taking so long on this, unfortunately you can't use the `.stream` method to stream back chunks of the final response. This is because for agents we aren't able to tell what actually is the final response until the entire response has come in, and we can parse it. However, we do have a section in the docs which tries to account for this using `.streamLog`:

https://js.langchain.com/docs/modules/agents/how_to/streaming#:~:text=With%20some%20creative%20parsing%2C%20this%20can%20be%20useful%20for%20e.g.%20streaming%20back%20just%20the%20final%20response%20from%20the%20agent%3A

**Comment by jacoblee93** [comment]
Closing for now, we are working on a new and easier to use API for streaming these internal agent steps.

**Comment by IgorBialek** [comment]
@jacoblee93 Hi there! 👋 I was wondering if this new API has been released yet?
