### ISSUE TITLE
Not taking advantage of typescript template literals

### ISSUE THREAD

**Issue by BLamy** [langchain-ai/langchainjs#34]
Typescript has extremely powerful template literals. https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html. 

I'd imagine one of the goals of langchainjs is to keep a similar API to the python version so you could keep your API similar but infer what the arguments are suppose to be from the string.

https://www.typescriptlang.org/play?#code/C4TwDgpgBAymA2BLYAeGUIA9gQHYBMBnKQ4AJ0VwHMAaKAEQ2zyJPMqoD4oBeNi6kxwFiMAFBQoAfn4cA2gF0JUAFywhLYgHItymYuVr0WYawAGAEgDelAGYQyUACoBfa-Tc3c9xwFUXZnpQck50AHQRcEiovnT0nEqSanIwCgDcYmKgkFAAothkAIYAxsBOEAC2CIU4AAqFRRWEKE71wAAWGiKy1Nx8VspyANJQlLAIyC1t7XRaVlZanHK4AK4VAEYOClCFxCMmmlCWXj5QtS4X1qQCVAHKkjK196pQuBAAbltq1xwZLhliYoAe1wpCgODBfC05Xg8CgFWghSg8wAVkCANYQJzgCAXKBozFhLQA2wrXClRAgqBUPAOGoQFpdVg-XoACmUYDIQKqwDUoQ5DUKTTU+XIJTKlWqdUFTRanDEAEpkS5MjS3kUcKyIcA6FZwRBSGotKTcLgQFooC4FRk1XTNdrdfiMVicUaTWaLVaMkA

<img width="619" alt="image" src="https://user-images.githubusercontent.com/324928/219783872-6c940705-74fa-463c-bc37-f7fc903eb3f3.png">

```ts
type Split<S extends string, D extends string> = string extends S
  ? string[]
  : S extends ''
  ? []
  : S extends `${infer T}${D}${infer U}`
  ? [T, ...Split<U, D>]
  : [S];

type ExtractTemplateParams<TPath extends string> = {
  [K in Split<TPath, '{{'>[number] as K extends `${infer P}}}${string}`
    ? P
    : never]: string;
};


function createPromptTemplate<T extends string>(
  prompt: T,
  params: ExtractTemplateParams<T>
) {}

const prompt = 'Tell me a {{jokeType}} joke.';
createPromptTemplate(prompt, { jokeType: "test" })

createPromptTemplate(prompt, { test: 'asf' }); // <- Will throw a type error
```

---

This next example is easier to understand but is more of a departure from how python does things. It has a typed generate function that auto completes prompts and will throw an error if you pass in a prompt that isn't valid. The prompt creation helper functions also have autocomplete for their args and the possible options for those args.
https://www.typescriptlang.org/play?#code/MYewdgzgLgBA3jAwuAZgSwOYFcBOBDKNcAGhgHkAHAUzAEEBJWitGAXxgF4YcqBHLNDwAUAchDUweNCICUAbgBQC0JFgr02fIXCcYYKgHckqTLgJEwQuApgw8zANJUAngC4YFHCGBUIEAHQ0AG7+ZAAKAKIAcgwA+rRh9LEOEQCaxAqs8srg0DDiNFK6+kaUNAxMaELqploW2QpQztQwYSBUALa0OBgQughQ4mjA7iIANiBBVCIwAD4wIig4aDQAJhAAFmgUM-OLEwZUOBAzrIoqecA8BFRtnWFeHRSwXFYwg8zAbO53XT0QMk4AD4bDAAAYAdWWUCodg87Q6dgARiAsLAACRwD7DVj+MF2PoXKCKJotX4PEBPKAAFU6FDGN10ACUqFBcGBqc0qAAeUlUEAoGBXKg3cmPZ5AxSNLkwABSIAA1lRur1+jAAFaKqic6ijFBYMBgZy7BarLAdJEmkSrPCrU7nXJqa4w+VKilU3RvTVKnWw1juV3K-6Ajgg2xg2ljMYwDqwvAwTHe7Vc9hJvEEoWOkkywPu560p4MmHM1ns328rkCoXOqi58VQSVKfVgYDaMAwDA0I43ISeSnPH4IvM0ulF2HzOv9keFm6A6y2HhsnDtgqSND+YU3ZCF1kWKyg2wdECrKhjUYwgAeUAAtDagmgW2hrwAGZ8AZhEGQPMAA9D+YBskxHPkUw4B49ZUKs7wgDAEBULCUAbAhXIQN+fZUhkthZIorAKEAA

<img width="572" alt="image" src="https://user-images.githubusercontent.com/324928/219782087-047cfed0-8c60-401c-bcf4-44c63933524d.png">

**Comment by sullivan-sean** [comment]
This is really smart 👍

**Comment by BLamy** [comment]
This approach really shines when you validate user input with zod. 

https://stackblitz.com/edit/node-ycgnwj?file=app.ts

**Comment by nfcampos** [comment]
This is great, now a challenge would be how to make it work with prompts loaded from langchainhub 🤔

**Comment by sullivan-sean** [comment]
This is a great point -- when deserializing from (or serializing to) LangchainHub we'll need access to the input names so that things are compatible with any other languages that may load from LangchainHub

**Comment by BLamy** [comment]
Not currently possible to infer a string imported from json as const. 
https://github.com/microsoft/TypeScript/issues/32063

As a workaround you could probably create a CI pipeline that copies the json file to a `.ts` file and then prepends the file with `export default ` adds ` as const;` at the end. 

For node projects I think langchain hub would have to be published as packages on npm and installed using a package manager. However, I think a runtime like deno could give developers the experience you are looking for where langchain hub is mirrored on deno.land and then you can import type safe prompts with something like


```ts
import { serve } from "https://deno.land/std@0.91.0/http/server.ts";
import { z } from "https://deno.land/x/zod/mod.ts";
import { OpenAI } from 'https://deno.land/x/openai/mod.ts';

import { loadFromLCHub } from "https://deno.land/x/langchainjs/mod.ts";
import qaWithSources from "https://deno.land/x/langchain-hub/prompts/qa_with_sources/refine/basic.ts";

const instance = new OpenAI('YOUR_API_KEY');

const s = serve({ port: 8080 });

console.log("http://localhost:8080/");

for await (const req of s) {
  const prompt = loadFromLCHub(qaWithSources).format({
  });
  req.respond({ body: await instance.createCompletion(prompt) });
}
```

**Comment by Necmttn** [comment]
Before I noticed this whole library existed, I was hacking my way to create typesafe prompt templates.
![image](https://user-images.githubusercontent.com/5212808/219982891-a5818692-4a4f-4890-8141-71c33dcb7287.png)
https://github.com/Necmttn/langflow/blob/wip/packages/prompt/src/index.ts
here's the implementation. 

and some test cases I have created
https://github.com/Necmttn/langflow/blob/wip/packages/prompt/src/index.test.ts
