### ISSUE TITLE
No way to pass source documents to AgentExecutor

### ISSUE THREAD

**Issue by andreasjoensson** [langchain-ai/langchainjs#3404]
Hi i am looking to make a agent with access to a vector store and a couple of tools, but i can't seem to be able to return the source documents. In below example the source documents are available in the qaTool, but it is never forwarded to the response of the executor is there a way around this?
```

import { initializeAgentExecutorWithOptions } from 'langchain/agents'
import { Chroma } from 'langchain/vectorstores/chroma'
import { OpenAIEmbeddings } from 'langchain/embeddings/openai'
import { ChatOpenAI } from 'langchain/chat_models/openai'
import { OpenAIAgentTokenBufferMemory } from 'langchain/agents/toolkits'
import { HumanMessage, AIMessage } from 'langchain/schema'
import { ChatMessageHistory } from 'langchain/memory'
import { ChainTool } from 'langchain/tools'
import { Request, Response } from 'express'
import { RetrievalQAChain, loadQAStuffChain } from 'langchain/chains'
import { shippingTool } from './templates/Shipping'

export const runChatbot = async (
  input: string,
  chatbotID: string,
  company: string,
  previousMessages: (HumanMessage | AIMessage)[],
  res: Response,
  req: Request
) => {
  try {
    const vectorStore = await Chroma.fromExistingCollection(
      new OpenAIEmbeddings({
        azureOpenAIApiKey: process.env.AZURE_OPENAI_API_KEY,
        azureOpenAIApiVersion: process.env.AZURE_OPENAI_API_VERSION,
        azureOpenAIApiDeploymentName:
          process.env.AZURE_OPENAI_API_DEPLOYMENT_EMBEDDING_NAME,
        azureOpenAIApiInstanceName: process.env.AZURE_OPENAI_API_INSTANCE_NAME
      }),
      {
        collectionName: chatbotID,
        url: 'testurl'
      }
    )

    const retriever = vectorStore.asRetriever()

    const model = new ChatOpenAI({
      temperature: 0,
      azureOpenAIApiKey: process.env.AZURE_OPENAI_API_KEY,
      azureOpenAIApiVersion: process.env.AZURE_OPENAI_API_VERSION,
      azureOpenAIApiDeploymentName:
        process.env.AZURE_OPENAI_API_DEPLOYMENT_NAME,
      azureOpenAIApiInstanceName: process.env.AZURE_OPENAI_API_INSTANCE_NAME,
      streaming: true
    })

    const retrievalChain = new RetrievalQAChain({
      combineDocumentsChain: loadQAStuffChain(model),
      retriever,
      returnSourceDocuments: true
    })

    const chatHistory = new ChatMessageHistory(previousMessages)

    const memory = new OpenAIAgentTokenBufferMemory({
      llm: model,
      memoryKey: 'chat_history',
      outputKey: 'output',
      inputKey: 'input',
      chatHistory
    })

    const qaTool = new ChainTool({
      name: `state-of-${company}-qa`,
      description: `State of the ${company} QA - useful for when you need to ask questions about ${company}.`,
      chain: retrievalChain,
      returnDirect: true,
      verbose: true
    })

    const tools = [qaTool, shippingTool]

    const executor = await initializeAgentExecutorWithOptions(tools, model, {
      agentType: 'openai-functions',
      memory,
      returnIntermediateSteps: true,
      agentArgs: {
        prefix:
          'Du er en AI-Assistent for webshoppen Spacebox der sælger lys til gamere. Brug din viden om Spacebox og dets sortiment til at hjælpe kunderne. Du kan også bruge værktøjer til at finde nøjagtige oplysninger, hvis du er usikker. Hvis du ikke har svaret, bedes du undlade at give et svar på spørgsmålet.'
      }
    })

    await executor.call(
      {
        input: input
      },
      {
        callbacks: [
          {
            handleLLMNewToken(token: string) {
              res.write(token)
            }
          }
        ]
      }
    )

    res.end()
  } catch (error) {
    console.error('Error occurred:', error)
    // Handle the error as needed: log, throw, or respond gracefully.
    // Example: throw the error to propagate it to the caller
    throw error
  }
}

export default runChatbot
```

**Comment by andreasjoensson** [comment]
@dosu-bot just tried this solution but it is not compatible with "tools", the types are mismatching...

**Comment by andreasjoensson** [comment]
@dosu-bot i am still not able to make a working solution based on your help, do you have other examples of custom structured tools which would be similar?

**Comment by marius-ciocoiu** [comment]
Having the same problem and getting the following error in logs: `Tool run errored with error: "return values have multiple keys, `run` only supported when one key currently"` . It seems that this is an older issue: https://github.com/langchain-ai/langchainjs/issues/593 and it's not yet resolved. The problems come from the following line: ` returnSourceDocuments: true`.

**Comment by PaulSearcy** [comment]
> Hi i am looking to make a agent with access to a vector store and a couple of tools, but i can't seem to be able to return the source documents. In below example the source documents are available in the qaTool, but it is never forwarded to the response of the executor is there a way around this?
> 
> ```
> 
> import { initializeAgentExecutorWithOptions } from 'langchain/agents'
> import { Chroma } from 'langchain/vectorstores/chroma'
> import { OpenAIEmbeddings } from 'langchain/embeddings/openai'
> import { ChatOpenAI } from 'langchain/chat_models/openai'
> import { OpenAIAgentTokenBufferMemory } from 'langchain/agents/toolkits'
> import { HumanMessage, AIMessage } from 'langchain/schema'
> import { ChatMessageHistory } from 'langchain/memory'
> import { ChainTool } from 'langchain/tools'
> import { Request, Response } from 'express'
> import { RetrievalQAChain, loadQAStuffChain } from 'langchain/chains'
> import { shippingTool } from './templates/Shipping'
> 
> export const runChatbot = async (
>   input: string,
>   chatbotID: string,
>   company: string,
>   previousMessages: (HumanMessage | AIMessage)[],
>   res: Response,
>   req: Request
> ) => {
>   try {
>     const vectorStore = await Chroma.fromExistingCollection(
>       new OpenAIEmbeddings({
>         azureOpenAIApiKey: process.env.AZURE_OPENAI_API_KEY,
>         azureOpenAIApiVersion: process.env.AZURE_OPENAI_API_VERSION,
>         azureOpenAIApiDeploymentName:
>           process.env.AZURE_OPENAI_API_DEPLOYMENT_EMBEDDING_NAME,
>         azureOpenAIApiInstanceName: process.env.AZURE_OPENAI_API_INSTANCE_NAME
>       }),
>       {
>         collectionName: chatbotID,
>         url: 'testurl'
>       }
>     )
> 
>     const retriever = vectorStore.asRetriever()
> 
>     const model = new ChatOpenAI({
>       temperature: 0,
>       azureOpenAIApiKey: process.env.AZURE_OPENAI_API_KEY,
>       azureOpenAIApiVersion: process.env.AZURE_OPENAI_API_VERSION,
>       azureOpenAIApiDeploymentName:
>         process.env.AZURE_OPENAI_API_DEPLOYMENT_NAME,
>       azureOpenAIApiInstanceName: process.env.AZURE_OPENAI_API_INSTANCE_NAME,
>       streaming: true
>     })
> 
>     const retrievalChain = new RetrievalQAChain({
>       combineDocumentsChain: loadQAStuffChain(model),
>       retriever,
>       returnSourceDocuments: true
>     })
> 
>     const chatHistory = new ChatMessageHistory(previousMessages)
> 
>     const memory = new OpenAIAgentTokenBufferMemory({
>       llm: model,
>       memoryKey: 'chat_history',
>       outputKey: 'output',
>       inputKey: 'input',
>       chatHistory
>     })
> 
>     const qaTool = new ChainTool({
>       name: `state-of-${company}-qa`,
>       description: `State of the ${company} QA - useful for when you need to ask questions about ${company}.`,
>       chain: retrievalChain,
>       returnDirect: true,
>       verbose: true
>     })
> 
>     const tools = [qaTool, shippingTool]
> 
>     const executor = await initializeAgentExecutorWithOptions(tools, model, {
>       agentType: 'openai-functions',
>       memory,
>       returnIntermediateSteps: true,
>       agentArgs: {
>         prefix:
>           'Du er en AI-Assistent for webshoppen Spacebox der sælger lys til gamere. Brug din viden om Spacebox og dets sortiment til at hjælpe kunderne. Du kan også bruge værktøjer til at finde nøjagtige oplysninger, hvis du er usikker. Hvis du ikke har svaret, bedes du undlade at give et svar på spørgsmålet.'
>       }
>     })
> 
>     await executor.call(
>       {
>         input: input
>       },
>       {
>         callbacks: [
>           {
>             handleLLMNewToken(token: string) {
>               res.write(token)
>             }
>           }
>         ]
>       }
>     )
> 
>     res.end()
>   } catch (error) {
>     console.error('Error occurred:', error)
>     // Handle the error as needed: log, throw, or respond gracefully.
>     // Example: throw the error to propagate it to the caller
>     throw error
>   }
> }
> 
> export default runChatbot
> ```

If this is any help, you can use another LLM call inside your tool to do what you needed to do with the source documents and then return that response back to the agent.  

Langchain created an abstraction just for this. Though it's considered 'legacy' now. 
https://js.langchain.com/docs/modules/chains/popular/vector_db_qa_legacy
