### ISSUE TITLE
getBufferString is missing the "tool" type/role pair. 

### ISSUE THREAD

**Issue by PlasticLizard** [langchain-ai/langchainjs#3405]
I'm seeing this error when a ToolMessage is added. Offending code is in langchain-core/src/messages/index.ts

Error in handler CallbackHandler, handleLLMStart: Error: Got unsupported message type: [Object, Object]}

export function getBufferString(
  messages: BaseMessage[],
  humanPrefix = "Human",
  aiPrefix = "AI"
): string {
  const string_messages: string[] = [];
  for (const m of messages) {
    let role: string;
    if (m._getType() === "human") {
      role = humanPrefix;
    } else if (m._getType() === "ai") {
      role = aiPrefix;
    } else if (m._getType() === "system") {
      role = "System";
    } else if (m._getType() === "function") {
      role = "Function";
    } else if (m._getType() === "generic") {
      role = (m as ChatMessage).role;
    } else {
      throw new Error(`Got unsupported message type: ${m}`);
    }
    const nameStr = m.name ? `${m.name}, ` : "";
    string_messages.push(`${role}: ${nameStr}${m.content}`);
  }
  return string_messages.join("\n");
}

Adding 

else if (m._getType() === "tool") {
      role = "Tool";
    } 

clears this up. Also, this would make a better error message:     throw new Error(`Got unsupported message type: ${m._getType()}`);

**Comment by jacoblee93** [comment]
Thank you for reporting this!
