### ISSUE TITLE
ConversationalRetrievalChain.from_llm help

### ISSUE THREAD

**Issue by mikeblackk** [langchain-ai/langchainjs#3406]
Hi all,

I'm in the process of converting langchain python to js and having some issues.

When using in python
`
   qa = ConversationalRetrievalChain.from_llm(
        llm=llm, 
        retriever=retriever, 
        condense_question_prompt=standalone_question_prompt, 
        return_source_documents=True,
        combine_docs_chain_kwargs={"prompt": PROMPT},
        verbose=False
    )
`
    I use combine_docs_chain and condese_question_prompt.

But in the JS version for starters there is no ConversationalRetrievalChain but ConversationalRetrievalQAChain.

I really need some help in having a like for like or has anyone come across this and solved it?

Python code

`    bedrock_runtime = boto3.client(
    service_name="bedrock-runtime",
    region_name=region,
    
    )
    llm = Bedrock(
        region_name=region,
        model_kwargs={
            "max_tokens_to_sample": 300,
            "temperature": 1,
            "top_k": 250,
            "top_p": 0.999,
        },
        model_id=modelId,
        client=bedrock_runtime
    )
      
    retriever = AmazonKendraRetriever(
        index_id=kendraId,
        top_k=5,
        region_name=region,
        user_context={"Token": userToken}
    )

    prompt_template = """
    Human: This is a friendly conversation between a human and an AI. 
    The AI is talkative and provides specific details from its context but limits it to 240 tokens.
    If the AI does not know the answer to a question, it truthfully says it does not know.
    
    Assistant: OK, got it, I'll be a talkative truthful AI assistant.
    
    Human: Here are a few documents in <documents> tags:
    <documents>
    {context}
    </documents>
    Based on the above documents, provide a detailed answer for, {question} 
    Answer "don't know" if not present in the document. 
    
    Assistant:
    """
    PROMPT = PromptTemplate(
        template=prompt_template, 
        input_variables=["context", "question"]
    )

    condense_qa_template = """
    {chat_history}
    Human:
    Given the previous conversation and a follow-up question below, 
    rephrase the follow-up question to be a standalone question.
    
    Follow Up Question: {question}
    Standalone Question:
    
    Assistant:
    """
    standalone_question_prompt = PromptTemplate.from_template(condense_qa_template)

    qa = ConversationalRetrievalChain.from_llm(
        llm=llm, 
        retriever=retriever, 
        condense_question_prompt=standalone_question_prompt, 
        return_source_documents=True,
        combine_docs_chain_kwargs={"prompt": PROMPT},
        verbose=False
    )

    return qa
    
    async def run_chain(chain, prompt: str, history=[]):
    return chain({"question": prompt, "chat_history": history})
`
    
    My attempt at JS so far.
    ` const buildChain = async (region: string, modelId: string, kendraId: string): Promise<any> => {
    const llm = new Bedrock({
        modelKwargs: {
            max_tokens_to_sample: 300,
            temperature: 1,
            top_k: 250,
            top_p: 0.999,
        },
        model: modelId,
    });

    const retriever = new AmazonKendraRetriever({
        topK: 5,
        indexId: kendraId,
        region: region,
    });

    const promptTemplate = `
    Human: This is a friendly conversation between a human and an AI.
    The AI is talkative and provides specific details from its context but limits it to 240 tokens.
    If the AI does not know the answer to a question, it truthfully says it does not know.

    Assistant: OK, got it, I'll be a talkative truthful AI assistant.

    Human: Here are a few documents in <documents> tags:
    <documents>
    {context}
    </documents>
    Based on the above documents, provide a detailed answer for, {question}
    Answer "don't know" if not present in the document.

    Assistant:
    `;

    const prompt = new PromptTemplate({ template: promptTemplate, inputVariables: ["context", "question"] });

    const condense_qa_template = `
    {chat_history}
    Human:
    Given the previous conversation and a follow-up question below, 
    rephrase the follow-up question to be a standalone question.
    
    Follow Up Question: {question}
    Standalone Question:
    
    Assistant: `;

    const standalone_question_prompt = PromptTemplate.fromTemplate(condense_qa_template);

    const qaChain = ConversationalRetrievalQAChain.fromLLM(llm, retriever, {
        returnSourceDocuments: true,
        verbose: false,
    });

    return qaChain;
    
    const runChain = async (chain: any, prompt: string, history: any[] = []): Promise<any> => {
    return await chain.call({ question: prompt, chat_history: history });
};
};`

Any help please? I need access to the condese prompt for QA continuation

**Comment by jacoblee93** [comment]
This belongs on the Python repo.

**Comment by mikeblackk** [comment]
how? I'm asking for the JS equivalent ?

**Comment by jacoblee93** [comment]
Oh sorry, skimmed too quickly. Here is the API ref: 

https://api.js.langchain.com/classes/chains.ConversationalRetrievalQAChain.html#fromLLM

**Comment by mikeblackk** [comment]
Understood but The conversational retriever is missing components from the python version. Such as combine documents and kwargs. I literally have to write a custom class to even override and the options available are not as clear as the python one. I just find it interesting that ConversationalRetrievalQAChain was only provided and not ConversationalRetrieval anyways. I just think when developing this, should have the same features available to make language shifting easier.

**Comment by jacoblee93** [comment]
I think it's hidden in `qaChainOptions`

We are suggesting people use the expression language version for this reason:

https://js.langchain.com/docs/expression_language/cookbook/retrieval#conversational-retrieval-chain

**Comment by mikeblackk** [comment]
I just think that is too complicated? python is quick and easy and in JS we take this complicated route of piping etc. User experience isn't the best.

**Comment by jacoblee93** [comment]
Yeah, I hear you. Trying to strike a balance between customizability and easy import, but are generally finding that RAG isn't a one-size fits all solution.

For now, would suggest just copy/pasting it into a file and exporting it yourself like you would with `shadcn`.
