### ISSUE TITLE
Prisma vectorstore filter cannot handle uuid's

### ISSUE THREAD

**Issue by Knordy** [langchain-ai/langchainjs#3457]
Our `Prisma` schema defines a column of a table as: `someId String @db.Uuid`. We generate a uuid, which is a string and while adding data to the database using `addModels` the id is properly saved. However using the column as a filter when using the vectorstore we receive the following postgres error: `ERROR: operator does not exist: uuid = text`.

```
return PrismaVectorStore.withModel<Document>(prismaClient).create(
    new OpenAIEmbeddings({
      ...
    }),
    {
      prisma: Prisma,
      tableName: 'Document',
      vectorColumnName: 'vector',
      columns: {
        id: PrismaVectorStore.IdColumn,
        content: PrismaVectorStore.ContentColumn,
        someId: true,
      },
      filter: { someId: { equals: ${id}, }},
    },
```

How can we use `uuid` columns as a filter? Currently as a workaround we remove the `@db.Uuid`  from the schema.

**Comment by kpotter-m2** [comment]
good bot, this allowed us to modify the filter to pass custom SQL WHERE statements into our queries since our metadata is a JSON field.

**Comment by Magnuti** [comment]
Instead of 100 lines of code is it not possible to make LangChain support UUID?
