### ISSUE TITLE
Cohere LLM does not work for cohere-ai versions 7 and above ('cohere.init' is undefined)

### ISSUE THREAD

**Issue by amanape** [langchain-ai/langchainjs#3464]
`index.ts`
```ts
import { Cohere } from 'langchain/llms/cohere';

const llm = new Cohere({ apiKey: Bun.env.COHERE_API_KEY });

const text = "What would be a good name for a company that makes colourful socks?";
const llmResult = await llm.predict(text);
```

`package.json`
```json
{
  "name": "langchain",
  "module": "index.ts",
  "type": "module",
  "devDependencies": {
    "bun-types": "latest"
  },
  "peerDependencies": {
    "typescript": "^5.0.0"
  },
  "dependencies": {
    "cohere-ai": "^7.4.3",
    "langchain": "^0.0.198"
  }
}
```
**Full Error**
```
76 |         return "cohere";
77 |     }
78 |     /** @ignore */
79 |     async _call(prompt, options) {
80 |         const { cohere } = await Cohere.imports();
81 |         cohere.init(this.apiKey);
            ^
TypeError: cohere.init is not a function. (In 'cohere.init(this.apiKey)', 'cohere.init' is undefined)
```

A previous pull request has reverted the version support for `cohere-ai` but I could not find more information as to why that was. https://github.com/langchain-ai/langchainjs/pull/3277

**Comment by jacoblee93** [comment]
Hey @amanape,

Yes unfortunately Chroma (which we have as a peer dep) had Cohere as a peer dep locked to `5 || 6`. If we bumped to 7, it broke `npm`s default peer dependency resolution strategy.

We'll be looking into splitting integrations like Chroma out in the future to avoid this

**Comment by jacoblee93** [comment]
Opened https://github.com/chroma-core/chroma/issues/1445 but will also work on this.

**Comment by maornissan** [comment]
Thanks, [jacoblee93](https://github.com/jacoblee93) - it seems that chroma fixed the issue.
