### ISSUE TITLE
React Native Crash: `SyntaxError: Invalid RegExp: Invalid escape`

### ISSUE THREAD

**Issue by julian-hecker** [langchain-ai/langchainjs#3473]
Hey Langchain team, lovely project here!

I am working on integrating LangChain and OpenAI into a React Native application. I've faced many issues so far, but I'm almost there.

One issue I'm facing is once a response has been streamed from OpenAI, LangChain tries to count the tokens using TikToken. However, when encoding the tokens, TikToken tries to create a RegExp with a feature that appears to not be supported in Hermes, the Expo React Native runtime I'm using. I have already raised an [issue on the TikToken repo](https://github.com/dqbd/tiktoken/issues/82).

While we wait for that issue to be fixed, it may be prudent to wrap the call in a try/catch block, as is being done in some other places TikToken is used. The offending line in this case is here: [langchain-core/src/language_models/base](https://github.com/langchain-ai/langchainjs/blob/d82cfb84ac60367595d19e77175c7f1c596c247c/langchain-core/src/language_models/base.ts#L337). 

Hope I can be of some help to get this resolved :)

**Comment by julian-hecker** [comment]
Initializing an instance of TikToken isn't the issue, it's when you call the encode method. Wrapping the constructor with a try/catch won't do too much.

**Comment by jacoblee93** [comment]
Yes, good call. Will open a PR shortly!

**Comment by jacoblee93** [comment]
Would love to hear more about what you're building!
