### ISSUE TITLE
Issue with chroma on vercel production

### ISSUE THREAD

**Issue by moreno1123** [langchain-ai/langchainjs#3485]
"chromadb": "1.5.2", (in this version of chroma there is no warnings about module not found like https://github.com/langchain-ai/langchainjs/issues/346)
    "langchain": "0.0.198",
    "next": "13.5.4",

When I'm querying chroma on localhost it there is no issue, everything works like a charm but on production build on vercel it does not work for some reason. 
Also, code for making a collection works just fine on both builds and I am able to find the created collection on chroma directly from the docs.
There is no straight error, just not working with status 500

Code for querying (working only on localhost):
```typescript
export const runtime = 'edge';

export async function POST(req: Request){
  try {
    const body = await req.json()
    const messages = body.messages ?? [];
    const question = messages[messages.length - 1].content
    const { history, collectionId } = body

    const sanitizedQuestion = question.trim().replaceAll('\n', ' ');

    const { stream, handlers } = LangChainStream();
    
    const vectorStore = await Chroma.fromExistingCollection(
      new OpenAIEmbeddings(),
      {
        url: env.CHROMA_DB_SERVER,
        collectionName: collectionId,
      },
    );

    const chain = makeChain(vectorStore);

    chain.call({
      question: sanitizedQuestion,
      chat_history: history
    }, [handlers]);

    return new StreamingTextResponse(stream);
  } catch (error) {
    return NextResponse.json({message: "Internal error"}, {status: 500})
  }
}
```

Code for creating the collection (working both on localhost and prod):
```typescript
export async function POST(req: Request){
  try {
    const body = await req.formData()
    const file:any = body.get('file')
    const fileName:string = file.name
    const userId:any = body.get('userId')

    const collectionName = await prisma.collection.create({
      data: {
        fileName: fileName,
        userId: userId,
      }
    })

    const loader = new WebPDFLoader(file);
    const docs = await loader.load();

    const splitter = new RecursiveCharacterTextSplitter({
      chunkSize: 2000,
      chunkOverlap: 500,
    });

    const documents = await splitter.splitDocuments(docs);
    
    const vectorStore = await Chroma.fromDocuments(
      documents,
      new OpenAIEmbeddings(),
      { 
        url: env.CHROMA_DB_SERVER,
        collectionName: collectionName.id
      }
    );

    return NextResponse.json({message: "Embbed successfull!", collectionName: collectionName.id}, {status:200})
  } catch (error) {
    return NextResponse.json({message: "Internal error"}, {status: 500})
  }
}
```

**Comment by jacoblee93** [comment]
What's the value of `error` here?

```typescript
  } catch (error) {
    return NextResponse.json({message: "Internal error"}, {status: 500})
  }
```

**Comment by moreno1123** [comment]
This is the error:
Error: Chroma getOrCreateCollection error: Error: Unexpected token 'D', "Direct IP "... is not valid JSON

**Comment by jacoblee93** [comment]
CC @jeffchuber  do you have any idea?

**Comment by jeffchuber** [comment]
@andreasjoensson are you using latest `1.6.1` from https://www.npmjs.com/package/chromadb?

**Comment by jacoblee93** [comment]
Ah probably not supported on our end - will bump later and cut another release.

**Comment by andreasjoensson** [comment]
@jeffchuber yes i am using that version, i will try to downgrade and use another version in the meantime. Thanks for the quick support guys :)

**Comment by moreno1123** [comment]
Yeah, appreciate it. 🥇 
@andreasjoensson please share if you are able to get it working with downgrading.

**Comment by andreasjoensson** [comment]
@moreno1123 Will do i am right now trying to find which Langchain and ChromaDB versions matches, because when i use a older version of ChromaDB with Langchain i get `Error occurred: Error: Please install chromadb as a dependency with, e.g. `npm install -S chromadb``

Will reach back if i find a solution :)

**Comment by jacoblee93** [comment]
I can try later today as well - just to clarify it sounds like it's an issue with moving from a local deployment to a new cloud hosted version?

**Comment by moreno1123** [comment]
@jacoblee93 I used hosted Chroma on AWS EC2 in both cases, so it's not that...

**Comment by andreasjoensson** [comment]
@jacoblee93 Hey i'm also using a hosted Chroma on Render in my case, i tried to downgrade but could not seem to make it work. Everything has been working completely fine until yesterday, where suddenly my chatbot was not able to answer any questions based on the vector store and seemed to has lost all its knowledge. 

When checking the logs my ChromaDB returns 200 both on create and queries, and i have not changed anything so i'm a bit confused as to how this would happen.
![image](https://github.com/langchain-ai/langchainjs/assets/63600756/7ef0c985-a127-4d5d-81fd-1e4cc8483629)

I can provide you with my code, if that is of any help.

**Comment by andreasjoensson** [comment]
@jacoblee93 i figured it out it was a error on my end, i'm really sorry. I had accidentally made a change somewhere, so that the wrong collectionID was used. But thanks for the quick support appreaciate it, have a great weekend :)

**Comment by moreno1123** [comment]
It's not sorted on my end though....

**Comment by george-sagaiq** [comment]
@moreno1123 - Please see my comment here on how I worked around the missing chroma issue. Hope it helps - https://github.com/langchain-ai/langchainjs/issues/2637#issuecomment-2552735141
