### ISSUE TITLE
PGVectorStore: Error: different vector dimensions 4 and 1

### ISSUE THREAD

**Issue by iOnline247** [langchain-ai/langchainjs#3509]
I'm trying to use `PGVectorStore` to store embeddings in a `pgvector` instance. I'm having some difficulty figuring out how to fix it. I'm [following this example](https://js.langchain.com/docs/integrations/vectorstores/pgvector/), but would like to use the `LlamaCppEmbeddings` instead of the `OpenAIEmbeddings`.

This is how the table is created:
```sql
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TABLE IF NOT EXISTS tblvector(
  id uuid NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
  content text,
  metadata jsonb,
  embedding vector
);
```

```js
import { fileURLToPath } from "node:url";
import path from "node:path";

import { ChatLlamaCpp } from "langchain/chat_models/llama_cpp";
import { LlamaCppEmbeddings } from "langchain/embeddings/llama_cpp";
// import { OpenAIEmbeddings } from "langchain/embeddings/openai";
import { RecursiveCharacterTextSplitter } from "langchain/text_splitter";
import { PGVectorStore } from "langchain/vectorstores/pgvector";

const {
  MODEL_NAME = "mistral-7b-openorca.Q4_0.gguf",
  STORAGE_DIR = "./storage/app",
} = process.env;
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const modelPath = path.join(__dirname, "..", "LLMs", MODEL_NAME);

let vectorStore;

try {
  const model = new ChatLlamaCpp({
    modelPath,
    temperature: 0.1,
    verbose: true,
  });
  const embeddings = new LlamaCppEmbeddings({
    modelPath,
  });

  const config = {
    verbose: true,
    postgresConnectionOptions: {
      type: "postgres",
      database: "<DB_NAME>",
      user: "<USER_NAME>",
      password: "<PASSWORD>",
    },
    tableName: "tblvector",
    columns: {
      idColumnName: "id",
      vectorColumnName: "embedding",
      contentColumnName: "content",
      metadataColumnName: "metadata",
    },
  };

  vectorStore = await PGVectorStore.initialize(embeddings, config);

  await vectorStore.addDocuments([
    { pageContent: "what's this", metadata: { a: 2 } },
    { pageContent: "Cat drinks milk", metadata: { a: 1 } },
  ]);

  const similarDocs = await vectorStore.similaritySearchWithScore("water");

  console.log(similarDocs);
} catch (err) {
  console.error(err);
  debugger;
} finally {
  if (typeof vectorStore !== "undefined") {
    await vectorStore?.end();
  }
}

```

Stack trace:

```
error: different vector dimensions 4 and 1
    at <APP_DIR>\node_modules\pg-pool\index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PGVectorStore.similaritySearchVectorWithScore (file:///<APP_DIR>/node_modules/langchain/dist/vectorstores/pgvector.js:199:28) {
  length: 91,
  severity: 'ERROR',
  code: '22000',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'vector.c',
  line: '57',
  routine: 'CheckDims'
}
```

Here's what the rows in the DB:

![image](https://github.com/langchain-ai/langchainjs/assets/515152/e67c4d00-6979-47fa-93af-587728e03e4a)

**Comment by AnirudhaGohokar** [comment]
@iOnline247  Hi am also facing same issue when is pg vector DB along with LLama 2 with below error :

`Error processing the request: error: different vector dimensions 49 and 4`

Were you able to figure out the issue? Thank You

**Comment by iOnline247** [comment]
@dosubot @AnirudhaGohokar I haven't found a fix for this yet. I did find this article, but haven't completed the steps yet.

https://medium.com/@liusimao8/using-llama-2-models-for-text-embedding-with-langchain-79183350593d

**Comment by iOnline247** [comment]
@dosubot The array needs to be normalized prior to being saved to postgres. Are there any utilities built within langchain to do this? When I use the `OpenAIEmbeddings`, saving to postgres does work, but I want to use the `LlamaCppEmbeddings`

>    // TODO here we could optionally normalise the vectors to unit length
>    // so that dot product is equivalent to cosine similarity, like this
>    // https://github.com/nmslib/hnswlib/issues/384#issuecomment-1155737730
>    // While we only support OpenAI embeddings this isn't necessary

https://github.com/langchain-ai/langchainjs/blob/main/libs/langchain-community/src/vectorstores/hnswlib.ts#L121-L124
