### ISSUE TITLE
Supabase vector search improvements

### ISSUE THREAD

**Issue by mosnicholas** [langchain-ai/langchainjs#352]
Hey all -- love the work & support for Supabase. It seems that the vector search is only enabled across an entire table. It would be really helpful to query just a subset of the table based on input parameters (eg. specific ids).

**Comment by nfcampos** [comment]
Hi this makes sense, we should add filtering ability to each of the vector stores that supports it

**Comment by mz1979** [comment]
Filtering is already built in the base similaritySearch function which calls the Supabase similarityVectorWithScore function where the filter param is missing. I think it's just a matter of adding a filter object as parameter [https://github.com/hwchase17/langchainjs/blob/main/langchain/src/vectorstores/supabase.ts](here) (line 69). We could use a json object to list all filter criteria and feed it into the RPC match_document function as input parameter. Then the RPC function would just apply the filter as it matches document embeddings. This way we could filter by document name, type, and even user id!

**Comment by fletchertyler914** [comment]
@mz1979 I just ran into an issue where it would be so nice to be able to store documents with an associated user id. This would allow me to embed documents per user in the same table, instead of having to create a map table.

**Comment by ShantanuNair** [comment]
Continue discussion here?

https://github.com/hwchase17/langchainjs/issues/773

**Comment by mishkinf** [comment]
I added a PR for this https://github.com/hwchase17/langchainjs/pull/905
