### ISSUE TITLE
Cannot receive threadId if use OpenAI assistant as agent

### ISSUE THREAD

**Issue by dkhizhniakov** [langchain-ai/langchainjs#3520]
Hi,
I'm using the latest langchain version 0.0.200 with node 18.17.1 and I face an issue trying to make OpenAI assistant to memorize the context.
I want to make calls for the existing OpenAI assistant and track those within langsmith, but I can't get it to work.

So I tried 2 approaches - first using AgentExecutor

```
        const assistant = new OpenAIAssistantRunnable({
          assistantId: process.env.OPENAI_ASSISTANT_ID,
          asAgent: true,
        });
        
        const agentExecutor = AgentExecutor.fromAgentAndTools({
          agent: assistant,
          tools: [],
          verbose: true,
        });
        const assistantResponse = await agentExecutor.invoke(
          {
            content: req.body.message,
          },
          {
            metadata: {
              userId,
            },
          }
        );
```

In this case - I can see my request tracked in langsmith project (I have process.env set as per documentation), but I don't get `threadId` in the response and, therefore, assistant seem to not have a conversation context (I tried to ask it to remember a number and then tell it to me - works in OpenAI playground, but not in my implementation).

Another way I tried is to call directly like this:

```
        const assistant = new OpenAIAssistantRunnable({
          assistantId: process.env.OPENAI_ASSISTANT_ID,
          asAgent: true,
        });

        const assistantResponse = await assistant.invoke(
          {
            content: req.body.message,
          },
          {
            metadata: {
              userId,
            },
          }
        );
```

In this case I have `threadId` from `assistantResponse` and can use it just fine, but nothing shows up on langsmith (using the same process.env). I also tried to initialize tracking directly using langsmith/Client and LangChainTracer, but it didn't work either.

Small note: TS tells me that Client from langsmith package (0.0.49) isn't assignable to client property of LangChainTracer (from langchain/callbacks v.0.0.200): 
![image](https://github.com/langchain-ai/langchainjs/assets/25896054/2cce35d1-0bd4-4ae5-96fc-7db963ee5af1)

So is there a way to make requests to OpenAI assistant without losing the context and with having tracing in langsmith?

**Comment by AdelDima** [comment]
Do you find any solution?

**Comment by dkhizhniakov** [comment]
No, I ended up using OpenAI SDK directly + track into Langsmith using the client.
Maybe something has changed now
