### ISSUE TITLE
Make Retrieval QA return the exact documents used for answering the query

### ISSUE THREAD

**Issue by pi-curst** [langchain-ai/langchainjs#3534]
I'm creating a QA bot with RAG and aiming to provide the specific documents from which the answers are extracted. While Retrieval QA retrieves all source documents via the retriever, it uses only a subset to answer a question. How can I extract these specific documents from Retrieval QA? Is there a method for achieving this?

**Comment by jacoblee93** [comment]
Thanks @dosubot!

**Comment by pi-curst** [comment]
Retrieval QA uses k documents which are semantically similar to generate the answer. The answer need not be in all the k documents, how do we know which documents out of the k documents the answer is extracted from?

**Comment by KaanCL** [comment]
You are legend !!!
