### ISSUE TITLE
BufferMemory and ConversationalRetrievalQAChain Error: input values have 2 keys, you must specify an input key or pass only 1 key as input

### ISSUE THREAD

**Issue by RedouanAssakali** [langchain-ai/langchainjs#3539]
Error in chat route: Error: input values have 2 keys, you must specify an input key or pass only 1 key as input
    at getInputValue (/backend/node_modules/@langchain/core/dist/memory.cjs:31:15)

api/chat.js:
```   // Create a conversational chain
        const chain = makeChain(vectorStore);

        // Query the chain
        const response = await chain.call({

                question: sanitizedQuestion,
                chat_history: transformedHistory

        });

        // Send the response back to the client
        res.status(200).json(response);
    } catch (error) {
        console.error('Error in chat route:', error);
        res.status(500).json({ error: error.message || 'Something went wrong' });
    }
});
```

const makeChain = (vectorstore) => {
    // Initialize the FirestoreChatMessageHistory for chat history
    const chatHistory = new FirestoreChatMessageHistory(firestoreConfig);

    // Create a BufferMemory instance with FirestoreChatMessageHistory
    const memory = new BufferMemory({ chatHistory });

    const model = new OpenAI({
        temperature: 0.5,
        modelName: 'text-davinci-003',
    });

    return ConversationalRetrievalQAChain.fromLLM(
        model,
        vectorstore.asRetriever(),
        {
            qaTemplate: QA_PROMPT,
            questionGeneratorTemplate: CONDENSE_PROMPT,
            returnSourceDocuments: true,
            memory, // Add memory to the chain
        },
    );
};

module.exports = { makeChain };
```

**Comment by jacoblee93** [comment]
Thanks @dosubot!
