### ISSUE TITLE
Chat Model Steaming Mode Out of Memory

### ISSUE THREAD

**Issue by YukiDayDreamer** [langchain-ai/langchainjs#3544]
Under streaming mode, if we use OpenAI, then LangChain will estimate the token size. And there is problem in this code: https://github.com/langchain-ai/langchainjs/blob/main/libs/langchain-openai/src/chat_models.ts#L685.

If there are N messages come, then it will trigger N promises all and they have to resolve together. I tried to test locally with benchmark, and found that about 140 messages, it will eat up 3.5 GB memory which will can be a big problem.

Is possible to have an option to pause the token calculation so we can lower the memory usage?

**Comment by jacoblee93** [comment]
Yikes! What version of LangChain are you on?

Any chance this was fixed by #3519?

**Comment by YukiDayDreamer** [comment]
Hello! Yes, I think the fix resolved the problem! Thanks.
