### ISSUE TITLE
Pass another location to the Google Matching Engine

### ISSUE THREAD

**Issue by Seigneurhol** [langchain-ai/langchainjs#3547]
Hi,
I'm using a service account to log from the credential stored in GOOGLE_APPLICATION_CREDENTIALS. I have my index deployed on the location europe-west9. 

What should I pass to the matchingEngineconfig to use the europe-west9 location. Should I use the param endpoint or apiEndpoint or location or both ? Should I set the deployedIndexId ? And what should endpoint, apiEndpoint, location or deployedIndexId should look like ?

```
const index =
    'projects/{projectId}/locations/europe-west9/indexes/{indexId}';
  const indexEndpoint =
    'projects/{projectId}//locations/europe-west9/indexEndpoints/{indexEndpointsId}';

  const matchingEngineconfig = {
    index,
    indexEndpoint,
    apiVersion: 'v1beta1',
    docstore: store,
  };

  const googleVertexVectorStore = new MatchingEngine(
    embedder,
    matchingEngineconfig
  );
  const test = await googleVertexVectorStore.similaritySearch('medical');
```

**Comment by Seigneurhol** [comment]
I use this as the matchingEngineconfig config :  
```
const index = '{indexId}';
  const indexEndpoint = '{indexEndpoint}';

  const matchingEngineconfig = {
    index,
    indexEndpoint,
    apiVersion: 'v1beta1',
    endpoint: '{endpoint}', // The host to connect to for queries and upserts.
    // apiEndpoint: '{apiEndpoint}', // The API endpoint.
    location: '{location}', // The location.
    deployedIndexId: '{deployedIndexId}', // The id for the "deployed index".
    docstore: store,
  };
```
But I have this credential error :
```
{
"status": 401,
   "statusText": "Unauthorized",
   "request": {
   "responseURL": "{responseURL}"
  }
  },
  "status": 401,
  "code": 401,
  "errors": [
   {
    "message": "Invalid Credentials",
   "domain": "global",
   "reason": "authError",
    "location": "Authorization",
    "locationType": "header"
   }
  ],
 "attemptNumber": 1,
"retriesLeft": 6
 }
```
Which is weird since the credential for the service account is in the env variable : GOOGLE_APPLICATION_CREDENTIALS and I can access the google bucket and google vertex modeles.
What should I explore and how should matchingEngineconfig paramters looks like ?

**Comment by casbra13** [comment]
Hey, I have the same problem with the Matching Engine, I get the error of Invalid Credentials, even though I have a service account connected in my .env that should have all necessary roles.
