### ISSUE TITLE
Cannot using RecursiveCharacterTextSplitter on Express/nodejs

### ISSUE THREAD

**Issue by ZakaCoding** [langchain-ai/langchainjs#3566]
Hello, i've build project using nodejs.

when i read on langchain js [documentation](https://js.langchain.com/docs/modules/data_connection/document_transformers/text_splitters/recursive_text_splitter)
i cannot use that, and i don't know why?

my code looks like this

`
import { RecursiveCharacterTextSplitter  } from 'langchain';

    // get rawText from data pdf on react client
    const rawText = formData.files;
    // split with Recursive Character
    const splitter = new RecursiveCharacterTextSplitter({
        chunkSize: 100,
        chunkOverlap: 10
    });

    // Chunk output
    const textChunk = await splitter.createDocuments([text]);

    // Debug
    return textChunk;
`

that show error like this:
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in C:\www\next-ai\node_modules\langchain\package.json imported from C:\www\next-ai\models\trainModels.js

if you guys have same problem please comment

![image](https://github.com/langchain-ai/langchainjs/assets/22311050/446478a9-6071-410c-84c9-8717f8ccfeda)

**Comment by ZakaCoding** [comment]
> _🤖_
> 
> Hello @ZakaCoding,
> 
> Welcome to the langchainjs repository! I'm [Dosu](https://dosu.dev), a bot here to assist you while we're waiting for a human maintainer. I'm here to help you solve bugs, answer your questions, and guide you in becoming a contributor. Looking forward to helping you with your issue!
> 
> Based on the error message you're encountering, it seems like the issue is related to the package.json file of the langchainjs library not having a main field defined. The main field is the primary entry point to your program and is what Node.js will run when your package is imported by another application.
> 
> However, I noticed that you're using version 0.0.4 of langchainjs in your project. There have been similar issues reported in the langchainjs repository that were resolved by updating to version 0.0.49. This version includes a CommonJS (CJS) build which should fix the issue you're encountering.
> 
> Here are the similar issues for your reference:
> 
> * [Typescript not working](https://github.com/langchain-ai/langchainjs/issues/340)
> * [Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './text_splitter' is not defined by "exports" in /node_modules/langchain/package.json](https://github.com/langchain-ai/langchainjs/issues/240)
> * [Export missing. Version 0.22](https://github.com/langchain-ai/langchainjs/issues/216)
> 
> In these issues, the suggested solution was to update to the new version 0.0.49 of LangChainJS and ensure that you are explicitly stating `"type": "commonjs"` in package.json and `"module": "CommonJS"` in your tsconfig to use the CJS build.
> 
> Please try updating your langchainjs version to 0.0.49 and let me know if the issue persists. If it does, could you please provide the code where you're trying to import and use RecursiveCharacterTextSplitter? This will help me provide a more accurate solution.
> 
> I hope this helps! If you have any other questions, feel free to ask.
> 
> Best, [Dosu](https://dosu.dev)
> 
> ## Sources
> * [Typescript not working ](https://github.com/langchain-ai/langchainjs/issues/340)
> * [Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './text_splitter' is not defined by "exports" in /node_modules/langchain/package.json](https://github.com/langchain-ai/langchainjs/issues/240)
> * [Export missing. Version 0.22](https://github.com/langchain-ai/langchainjs/issues/216)
> * [environment_tests/test-exports-cjs/src/require.js](https://github.com/langchain-ai/langchainjs/blob/main/environment_tests/test-exports-cjs/src/require.js)
> * [package.json](https://github.com/langchain-ai/langchainjs/blob/main/package.json)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

Well if i use commonjs instead module system, my project will error. because i'm use express with module system.. any alternative ?

this my package.json files

`{
  "name": "next-ai",
  "version": "1.0.0",
  "description": "",
  "main": "app.js",
  "type": "commonjs",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "nodemon app.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "axios": "^1.6.2",
    "cors": "^2.8.5",
    "dotenv": "^16.3.1",
    "express": "^4.18.2",
    "firebase": "^10.7.0",
    "langchain": "^0.0.202",
    "openai": "^4.20.1",
    "pdf-parse": "^1.1.1"
  },
  "devDependencies": {
    "nodemon": "^3.0.2"
  }
}
`

**Comment by ZakaCoding** [comment]
i'm using js instead of typescript

**Comment by jacoblee93** [comment]
Import like this:

```
import {
  RecursiveCharacterTextSplitter,
} from "langchain/text_splitter";
```

Please reopen if that doesn't fix it!

**Comment by ZakaCoding** [comment]
> Import like this:
> 
> ```
> import {
>   RecursiveCharacterTextSplitter,
> } from "langchain/text_splitter";
> ```
> 
> Please reopen if that doesn't fix it!

I am already using that code, it still error. However when I just refactor my code from JavaScript into Typescript it **solved**

btw. If you guys can fix that on JavaScript with module system, it will be better
