### ISSUE TITLE
When I set the value of AZURE_OPENAI_BASE_PATH, a 404 error is reported.

### ISSUE THREAD

**Issue by lileltp** [langchain-ai/langchainjs#3573]
**Issue Description**

I encountered the following issue when using the AZURE_OPENAI_BASE_PATH parameter in langchain.js:
<img width="516" alt="image" src="https://github.com/langchain-ai/langchainjs/assets/4696657/a831dc9d-3e55-4009-8a70-e292b15ac0a0">

**Steps to Reproduce**

 azureOpenAIBasePath: "https://oai.hconeai.com",

**Related Information**

- langchain.js version: 0.0.202
- AZURE_OPENAI_BASE_PATH parameter value: https://oai.hconeai.com

**Attachments**

[llm/error] [1:llm:ChatOpenAI] [1.66s] LLM run errored with error: "404 Resource not found"

/Users/henry/Projects/sxrhea/new-lerna-workspace/node_modules/openai/src/error.ts:78
      return new NotFoundError(status, error, message, headers);

Thank you for your assistance!

**Comment by lileltp** [comment]
I am using the example provided in the documentation at https://docs.helicone.ai/getting-started/integration-method/azure
```
const model = new ChatOpenAI({
  azureOpenAIApiKey: "[AZURE_OPENAI_API_KEY]",
  azureOpenAIApiDeploymentName: "openai/deployments/gpt-35-turbo",
  azureOpenAIApiVersion: "2023-03-15-preview",
  azureOpenAIBasePath: "https://oai.hconeai.com",
  configuration: {
    organization: "[organization]",
    baseOptions: {
      headers: {
        "Helicone-Auth": `Bearer ${heliconeApiKey}`,
        "Helicone-OpenAI-Api-Base":
          "https://[YOUR_AZURE_DOMAIN].openai.azure.com",
      },
    },
  },
});
```
However, the program cannot run properly when configuring azureOpenAIBasePath and returns a 404 error. It's worth noting that there are records of the requests in Helicone. Additionally, I've observed that configuring the azureOpenAIBasePath value alone prevents the program from running correctly.

**Comment by h4r5h4** [comment]
Your screenshot indicates you are passing `flamingo-ai` for `azureOpenAIApiDeploymentName`
make sure it's `openai/deployments/flamingo-ai`
