### ISSUE TITLE
RecursiveCharacterTextSplit import on nodejs

### ISSUE THREAD

**Issue by ZakaCoding** [langchain-ai/langchainjs#3578]
> Import like this:
> 
> ```
> import {
>   RecursiveCharacterTextSplitter,
> } from "langchain/text_splitter";
> ```
> 
> Please reopen if that doesn't fix it!

I am already using that code, it still error. However when I just refactor my code from JavaScript into Typescript it **solved**

btw. If you guys can fix that on JavaScript with module system, it will be better

_Originally posted by @ZakaCoding in https://github.com/langchain-ai/langchainjs/issues/3566#issuecomment-1843789921_

**Comment by jayampathiadhikari** [comment]
@ZakaCoding Hi, you can import like this if its okay
`const { RecursiveCharacterTextSplitter } = require("langchain/text_splitter");`

**Comment by ZakaCoding** [comment]
> @ZakaCoding Hi, you can import like this if its okay
> `const { RecursiveCharacterTextSplitter } = require("langchain/text_splitter");`

I don't know this is work, btw I am using ES module on express project. 

But now i am already refactor my project into Typescript. And there no errors about this RecursiveTextSpillter
