### ISSUE TITLE
this.client.init is not a function

### ISSUE THREAD

**Issue by obadahalak** [langchain-ai/langchainjs#3613]
I get the following error when I use "CohereEmbeddings":
"TypeError: this.client.init is not a function"
`

let text=[];
try {  
  var data = fs.readFileSync(getPath, 'utf8');
  text=data.split("\n");

} catch(e) {
  console.log('Error:', e.stack);
}

const vectorstore = await MemoryVectorStore.fromTexts(
 text,
  [{ id: 1 }, { id: 2 }, { id: 3 }, { id: 4 }, { id: 5 }],
  new CohereEmbeddings({apiKey:"apiKey"})
);

const model = new ChatAnthropic({openAIApiKey:"openAIApiKey"});
const retriever = MultiQueryRetriever.fromLLM({
  llm: model,
  retriever: vectorstore.asRetriever(),
  verbose: true,
});

const query = "What is a programming languages?";
const retrievedDocs = await retriever.getRelevantDocuments(query);

console.log({retrievedDocs});
![image](https://github.com/langchain-ai/langchainjs/assets/69998512/cc371adc-eb79-4e86-bfbd-469893fa7f39)
`

note: I use the last version of cohere-ai   "^7.5.1"

**Comment by obadahalak** [comment]
in my current library, the "cohere" its JS not TS 

"node_modules\langchain\dist\embeddings\cohere.ts"

**Comment by Knordy** [comment]
Same issue here, using version `6.2.2` it still uses `init`, but it seems that from version `7.0.0` `init` is replaced by

```
import { CohereClient } from "cohere-ai";

const cohere = new CohereClient({
    apiKey: "YOUR_API_KEY",
});

or from `7.1.0`
```
import { CohereClient } from "cohere-ai";

const cohere = new CohereClient({
    token: "YOUR_API_KEY",
});
```

Either langchain needs to be capped to using Cohere 6.2.2 for using `init` or be updated to initialize the client the new way.

**Comment by jacoblee93** [comment]
@bracesproul Chroma has a new version out should now allow us to bump and update our Cohere dependency with your old PR.
