### ISSUE TITLE
Currently, it is not possible to pass headers when creating a RemoteRunnable

### ISSUE THREAD

**Issue by znat** [langchain-ai/langchainjs#3615]
Hi there,
In python I can set headers at `RemoteRunnable` instantiation time, but it doesn't seem possible in the js version.

https://github.com/langchain-ai/langchainjs/blob/00c7ff15957bf2a5223cfc62878f94bafe9ded22/langchain/src/runnables/remote.ts#L173

```
private async post<Body>(path: string, body: Body) {
    return await fetch(`${this.url}${path}`, {
      method: "POST",
      body: JSON.stringify(body),
      headers: {
        "Content-Type": "application/json",
      },
      signal: AbortSignal.timeout(this.options?.timeout ?? 5000),
    });
  }
  ```

**Comment by jacoblee93** [comment]
CC @bracesproul

**Comment by jacoblee93** [comment]
Ah sorry, this is now possible:

https://js.langchain.com/docs/ecosystem/langserve#configuration

Thank you!
