### ISSUE TITLE
Is it possible to use the OpenAI `response_format` with chains?

### ISSUE THREAD

**Issue by jgreens** [langchain-ai/langchainjs#3632]
See commented code, which breaks my implementation of the `ConversationalRetrievalQAChain`. The code runs as-is without the comment.
```typescript
  const model = new ChatOpenAI({
    temperature: 0,
    modelName: 'gpt-4-1106-preview',
  })
  // TODO: Want to add, but returns a runnable, not a model
  //   }).bind({
  //     response_format: {
  //       type: 'json_object',
  //     },
  //   });

  const extractionChain = ConversationalRetrievalQAChain.fromLLM(
    model, // Breaks if I uncomment above
    vectorStore.asRetriever()
    {
      qaTemplate: `You work in a famous pizzeria. Use JSON to output your pizzeria's secret recipe.

Question:
{question}

Document Context:
{context}
`,
      returnSourceDocuments: true,
    },
  );

  //Ask a question using chat history
  const response = await extractionChain.call({
    question: 'What are the exact ingredients?',
    chat_history: [],
  });
```

**Comment by jgreens** [comment]
Can you suggest which files I should modify to create a PR which adds the ability to set the response format of a QAChain call to JSON?

**Comment by jgreens** [comment]
@dosu-bot, which files I should modify to add the ability to set the response format of a `ConversationalRetrievalQAChain` call to JSON?

**Comment by jgreens** [comment]
@dosu-bot, I see it is not supported. I would need to make the same changes to `conversational_retrieval_chain.ts` that were made to `llm_chain.ts` here: https://github.com/langchain-ai/langchainjs/pull/3200

I will use a workaround, thanks!

**Comment by NajamShehzad** [comment]
I successfully got it to work by specifying the "response_format" as { type: "json_object" } within the modelKwargs key. Here's the JavaScript code I used:

```javascript
const model = new OpenAI({
  temperature: 0.9,
  openAIApiKey: OPENAI_API_KEY,
  modelName: "gpt-4-1106-preview",
  modelKwargs: {
    response_format: { type: "json_object" },
  },
});
 ```
I think its a good idea to add this as a top-level argument, considering its significance.
