### ISSUE TITLE
how to create a chat application using the bedrock llama 2 model in the starter template (LangChain + Next.js Starter Template)

### ISSUE THREAD

**Issue by raksrivastava** [langchain-ai/langchainjs#3651]
how to create a chat application using the bedrock llama 2 model in the starter template (LangChain + Next.js Starter Template)

**Comment by raksrivastava** [comment]
@dosu-bot  i want to use the bedrock chat model instead of openai . const model = new BedrockChat({
      model: "meta.llama2-70b-chat-v1",
      region: "us-east-1",
      endpointUrl: "https://bedrock-runtime.us-east-1.amazonaws.com",
      credentials: {
        accessKeyId: accessKeyId,
        secretAccessKey: secretAccessKey
      },
      modelKwargs: {},
    });

**Comment by jacoblee93** [comment]
You should be able to swap it in!

I've also got an example here in Cloudflare workers that uses Bedrock and Cloudflare workers AI:

https://github.com/langchain-ai/langchain-cloudflare-nuxt-template
