### ISSUE TITLE
Not being able to get table info when calling db.getTableInfo()

### ISSUE THREAD

**Issue by stestox** [langchain-ai/langchainjs#3658]
Hi, 

I am having trouble getting info for tables in my Azure SQL Database.

Below, I share the code and steps I undertake.

First, I configure the database connection:

const AppDataSource = new DataSource({
    type: "mssql", 
    host: process.env.AZURE_SQL_SERVER,
    database: process.env.AZURE_SQL_DATABASE,
    schema: "int",
    options: {
        encrypt: true,
        trustServerCertificate: true,
        },
    extra: {
        authentication: {
            type: process.env.AZURE_SQL_AUTHENTICATIONTYPE,
        },
    },
})
AppDataSource.initialize()
    .then(() => {
        console.log('\nData Source has been initialized!\n');
    })
    .catch((err) => {
        console.error('\nError during Data Source initialization:', err);
    });

As you can see above, I tried to pass the "int" value to a schema attribute because I want to work with the tables from the int schema in my Azure SQL database.

Then, I established the SQL database connection in LangChain:

const sqlDb = new SqlDatabase({
    appDataSource: AppDataSource,
    includesTables: ["table1"],
    sampleRowsInTableInfo: 10
})

console.log("\nConnection the Azure SQL database successfully established.\n")

As you can see above, I tried to include table1.

Then, I tried to get the table info by running the code below:

sqlDb.getTableInfo(["table1"]).then(tableInfo => {
  console.log(tableInfo);
}).catch(error => {
  console.error(error);
});

However, I ran into an error stating that there was no such table in my database. Apparently, LangChain didn't understand that I have tables in the int shema of my Azure SQL Database and that it had to look for my table1 in the int schema of my databases. It should have looked for [int].[table1].

Here is the error message: "Error: Wrong target table name: the table table1 was not found in the database".

Please, can you help me to get the program work, find and get the table info for the tables in the int schema of my Azure SQL database?

Thank you in advance!

**Comment by stestox** [comment]
Hello,

I had tried this many times, and it didn't work. 
I get the same error message:
Error: Wrong target table name: the table int.table1 was not found in the database.

Hi, @jacoblee93. I saw that you are a LangChainJS maintainer. Can you please have a look into this? I would appreciate your finding and proposing a solution to this issue.

I really appreciate any help you can provide. :)

**Comment by jacoblee93** [comment]
Hey sorry!

So we would basically need to add a `schema` parameter to the database connector?
