### ISSUE TITLE
Module not found: Can't resolve 'fs'

### ISSUE THREAD

**Issue by junruxiong** [langchain-ai/langchainjs#3668]
Hi, I try to use PDFLoader to parse pdfs, but when I initialise the PDFLoader, it shows the below error:

./node_modules/pdf-parse/lib/pdf.js/v1.10.100/build/pdf.js:17378:0
Module not found: Can't resolve 'fs'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/langchain/dist/document_loaders/fs/pdf.js
./node_modules/langchain/document_loaders/fs/pdf.js
./components/FileUploader.tsx
./components/UtilityBar.tsx
./components/LeftSidebar.tsx
./app/(protected)/layout.tsx

This is my code:
![image](https://github.com/langchain-ai/langchainjs/assets/44308338/5035fc80-2ba3-45f0-95a0-2b38e43fdab8)

**Comment by jacoblee93** [comment]
You will need to use the web version:

https://js.langchain.com/docs/integrations/document_loaders/web_loaders/pdf

The filesystem variants are all Node only.

**Comment by junruxiong** [comment]
Thanks for your swift reply. It is very helpful. I also noticed that only the pdf format has a web version loader. Are there any alternative methods for other file formats (docx, txt, ppt)?

**Comment by sujjeee** [comment]
> You will need to use the web version:
> 
> https://js.langchain.com/docs/integrations/document_loaders/web_loaders/pdf
> 
> The filesystem variants are all Node only.

hey @jacoblee93 im using same in nextjs but still getting same error `Module not found: Can't resolve 'fs'`

here is my code
```javascript
import { WebPDFLoader } from "langchain/document_loaders/web/pdf"

const blob = new Blob([modifiedPdfBytes], { type: "application/pdf" })
const loader = new WebPDFLoader(blob)
const documents = await loader.load()
console.log({ documents })
```

**Comment by jacoblee93** [comment]
Are you sure it's due to that import?

**Comment by sujjeee** [comment]
> Are you sure it's due to that import?

I guess yes please check this repo https://github.com/sujjeee/langchain-web

this is the Error im getting 
```
./node_modules/.pnpm/pdf-parse@1.1.1/node_modules/pdf-parse/lib/pdf.js/v1.10.100/build/pdf.js:17378:0
Module not found: Can't resolve 'fs'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/.pnpm/langchain@0.1.30_pdf-parse@1.1.1/node_modules/langchain/dist/document_loaders/web/pdf.js
./node_modules/.pnpm/langchain@0.1.30_pdf-parse@1.1.1/node_modules/langchain/document_loaders/web/pdf.js
./src/app/input-form.tsx
```

**Comment by jacoblee93** [comment]
Hmm I've been using it successfully here: https://github.com/jacoblee93/fully-local-pdf-chatbot/blob/main/app/worker.ts#L9

Anything different you see in any of the configs? Maybe tsconfig.json or package.json?

**Comment by sujjeee** [comment]
> Hmm I've been using it successfully here: https://github.com/jacoblee93/fully-local-pdf-chatbot/blob/main/app/worker.ts#L9
> 
> Anything different you see in any of the configs? Maybe tsconfig.json or package.json?

Thanks, it's working now. The issue is that we need to disable 'fs'. Get that fixed in the nextjs.config.js.

By the way, in the browser's console, it's showing:

`GET http://localhost:3001/_next/static/chunks/_app-pages-browser_node_modules_pnpm_pdf-parse_1_1_1_node_modules_pdf-parse_lib_pdf_js_v1_10_-9134c3.worker.js 404 (Not Found)`

and this warning:

`Warning: Setting up fake worker.`

Why is that?

**Comment by Gabu6872** [comment]
@sujjeee How have you disabled 'fs' and get that fixed in nextjs.config.js?

**Comment by sujjeee** [comment]
@Gabu6872 

Read more here: https://github.com/jacoblee93/fully-local-pdf-chatbot/blob/main/next.config.js

```javascript
/** @type {import('next').NextConfig} */
const nextConfig = {
  // (Optional) Export as a static site
  // See https://nextjs.org/docs/pages/building-your-application/deploying/static-exports#configuration
  output: 'export', // Feel free to modify/remove this option

  // Override the default webpack configuration
  webpack: (config, { isServer }) => {
      // See https://webpack.js.org/configuration/resolve/#resolvealias
      config.resolve.alias = {
          ...config.resolve.alias,
          "sharp$": false,
          "onnxruntime-node$": false,
      }
      config.experiments = {
        ...config.experiments,
        topLevelAwait: true,
        asyncWebAssembly: true,
      };
      config.module.rules.push({
        test: /\.md$/i,
        use: "raw-loader",
      });
      // Fixes npm packages that depend on `fs` module
      if (!isServer) {
        config.resolve.fallback = {
          ...config.resolve.fallback, // if you miss it, all the other options in fallback, specified
            // by next.js will be dropped. Doesn't make much sense, but how it is
          fs: false, // the solution
          "node:fs/promises": false,
          module: false,
          perf_hooks: false,
        };
      }
      return config;
  },
}

module.exports = nextConfig
```
