### ISSUE TITLE
Feature Request: Implement MMR Search in Qdrant Database for LangChain

### ISSUE THREAD

**Issue by Kubululo** [langchain-ai/langchainjs#3676]
**Title:** Add MMR Search Capability to Qdrant in LangChain

**Details:**
Requesting the implementation of Maximal Marginal Relevance (MMR) search within the Qdrant database framework in LangChain. MMR search, already present in other vector stores in LangChain, is currently missing in the Qdrant integration. This addition would enhance document retrieval capabilities by providing diverse and relevant results, bringing Qdrant's functionality in line with other supported vector stores in LangChain.

**Comment by Kubululo** [comment]
Any update?

**Comment by jstjoe** [comment]
I hope this can be reopened and implemented. It seems that Qdrant themselves support it with their client, and LangChain Python supports a number of different flavors of it too: https://api.python.langchain.com/en/latest/vectorstores/langchain_community.vectorstores.qdrant.Qdrant.html#langchain_community.vectorstores.qdrant.Qdrant.amax_marginal_relevance_search
