### ISSUE TITLE
promptLayerTrackRequest or PromptLayerTrackRequest not exported from langchain

### ISSUE THREAD

**Issue by ghost** [langchain-ai/langchainjs#3696]
### Overview
[Easily found in the repo](https://github.com/langchain-ai/langchainjs/blob/1794285a31b1430b0ced51a79188bd14dbbf0c54/langchain/src/util/prompt-layer.ts#L4), but throws an error on import. Tried all the combos I could think of - in the repo the directory is called util, not utils, the function is lowercase, but in the 

<img width="671" alt="Screenshot 2023-12-17 at 1 43 42 AM" src="https://github.com/langchain-ai/langchainjs/assets/151847225/a9fd04f9-f377-47be-80d7-3a3f87e84a6d">
<img width="672" alt="Screenshot 2023-12-17 at 1 43 53 AM" src="https://github.com/langchain-ai/langchainjs/assets/151847225/c84ec847-aadc-46d7-9e6d-132aa7aca561">
<img width="670" alt="Screenshot 2023-12-17 at 1 44 44 AM" src="https://github.com/langchain-ai/langchainjs/assets/151847225/5a02b65f-34f2-49a6-a48a-4726c7e6d1f4">

**Comment by jacoblee93** [comment]
We could add an entrypoint for it, but I don't believe it's meant to be called on its own. What's the use case?
