### ISSUE TITLE
ChatGoogleGenerativeAI: not call callbacks (_runManager?.handleLLMNewToken)

### ISSUE THREAD

**Issue by Nanyi-Jiang** [langchain-ai/langchainjs#3699]
### Context
When implementing Gemini with `ChatGoogleGenerativeAI`, I tried to use the `call` and `stream` functions with a callback function `handleLLMToken` which will write the response to my client side

- Expected: Can see the response from Gemini sent to the client
- Actual: Nothing was sent, and the `handleLLMToken` I passed in was not executed

### Investigation
I think it didn't call the callbacks (`_runManager?.handleLLMNewToken`) in the functions: `_generate` and `_streamResponseChunks` which caused the actual behavior to diverge from expected. 

Implementation of `ChatGoogleGenerativeAI` `_streamResponseChunks`:
https://github.com/langchain-ai/langchainjs/blob/1794285a31b1430b0ced51a79188bd14dbbf0c54/libs/langchain-google-genai/src/chat_models.ts#L298-L306

The implementation of other models: 
https://github.com/langchain-ai/langchainjs/blob/1794285a31b1430b0ced51a79188bd14dbbf0c54/langchain/src/chat_models/anthropic.ts#L302-L310

**Comment by jacoblee93** [comment]
CC @bracesproul

**Comment by jacoblee93** [comment]
Thank you for flagging!

**Comment by bracesproul** [comment]
hey @Nanyi-Jiang this will be patched in the next package release!
