### ISSUE TITLE
Is it possible to add streaming to a ConversationChain?

### ISSUE THREAD

**Issue by gzuuus** [langchain-ai/langchainjs#3704]
I currently have the following chain and I was wondering if it was possible to add stream for the llm response? I have checked docs and tried using chain.stream but it doesn't work, however if I use chat.stream it does stream the response well. Please can someone enlighten me on how to achieve this?
```typescript
const chat = new ChatOllama({
        baseUrl: "http://localhost:11434",
        model: "neural-chat",
        temperature: 0.5,
    });
const chain = new ConversationChain({
    memory: new BufferWindowMemory({ returnMessages: true, memoryKey: "history", k:3, chatHistory: new ChatMessageHistory(pastMessages) }),
    prompt: chatPrompt,
    llm: chat,
    });
```

**Comment by gzuuus** [comment]
@dosu-bot Thanks for providing these details, however modifying the call method doesn't make much sense since it would modify internal library files, and this is not desirable when updating, and your second example doesn't seem right either, I have not been able to set 'streaming: true' for my 'ChatOllama' or ' ConversationChain'  Currently my chain and model are as follows:
```typescript
const chat = new ChatOllama({
        baseUrl: "http://localhost:11434",
        model: "neural-chat",
        temperature: 0.5,
    });

const chain = new ConversationChain({
    memory: new BufferWindowMemory({ returnMessages: true, memoryKey: "history", k:3, chatHistory: new ChatMessageHistory(pastMessages) }),
    prompt: chatPrompt,
    llm: chat,
    });

const result = await chain.call({
            input: text,
          });
```

 As you can see there you have described all the configuration of my chain, what is the best way to add streaming to this case? At the moment I haven't found how to achieve this

**Comment by cfa532** [comment]
> @dosu-bot Thanks for providing these details, however modifying the call method doesn't make much sense since it would modify internal library files, and this is not desirable when updating, and your second example doesn't seem right either, I have not been able to set 'streaming: true' for my 'ChatOllama' or ' ConversationChain' Currently my chain and model are as follows:
> 
> ```ts
> const chat = new ChatOllama({
>         baseUrl: "http://localhost:11434",
>         model: "neural-chat",
>         temperature: 0.5,
>     });
> 
> const chain = new ConversationChain({
>     memory: new BufferWindowMemory({ returnMessages: true, memoryKey: "history", k:3, chatHistory: new ChatMessageHistory(pastMessages) }),
>     prompt: chatPrompt,
>     llm: chat,
>     });
> 
> const result = await chain.call({
>             input: text,
>           });
> ```
> 
> As you can see there you have described all the configuration of my chain, what is the best way to add streaming to this case? At the moment I haven't found how to achieve this

You can assign streaming=True in ChatOpenAI definition in Python. I am not sure about the ChatOllama.

**Comment by yhmjSky** [comment]
emm, you can try using LECL
``` ts
const chain = RunnableSequence.from([
    {
        question: (input: { question: string}) =>
        input.question,
    },
    prompt,
    model,
//  new StringOutputParser()
]);
    
const stream = await chain
.stream({ question: "hello" }, {
    callbacks: [{
        handleLLMNewToken(token: string) {
            console.log({ token });
        }
    }]
});
for await (const chunk of stream);
```

**Comment by steveruizok** [comment]
This took me a little while to piece together, but FWIW here's what I ended up with:

```ts
import { ChatOllama } from '@langchain/community/chat_models/ollama'
import { AIMessage, HumanMessage } from '@langchain/core/messages'
import { ChatPromptTemplate, MessagesPlaceholder } from '@langchain/core/prompts'
import { ConversationChain } from 'langchain/chains'
import { BufferMemory, ChatMessageHistory } from 'langchain/memory'

const model = new ChatOllama({
	baseUrl: 'http://localhost:11434', // Default value
	model: 'llama3:latest',
})

const prompt = ChatPromptTemplate.fromMessages([
	['system', 'You are a helpful chatbot'],
	new MessagesPlaceholder('history'),
	['human', '{input}'],
])

const memory = new BufferMemory({
	memoryKey: 'history',
	returnMessages: true,
	chatHistory: new ChatMessageHistory([]),
})

const chain = new ConversationChain({
	llm: model,
	prompt: prompt,
	memory: memory,
})

chain.stream(
	{ input: "What's the biggest moon in the solar system?" },
	{
		callbacks: [
			{
				handleLLMNewToken: (data) => {
					console.log(data)
				},
			},
		],
	}
).then(() => {
	console.log("done")
})
```

**Comment by cfa532** [comment]
The LECL is a great improvement from the old way. I happened to stumble upon a clean solution for streaming with LLMChain.
`
CHAT_LLM = ChatOpenAI(temperature=0.0, model="gpt-4",streaming=True)
chain = prompt | CHAT_LLM
async for chunk in chain.astream(query):
    print(chunk.content, end="|", flush=True)
    await websocket.send(json.dumps({"type": "stream", "data": chunk.content}))
`
The chunk is streamed content. Here I am using websocket to send streaming data to remote client.

**Comment by jeanfredd** [comment]
when i create a 

> The LECL is a great improvement from the old way. I happened to stumble upon a clean solution for streaming with LLMChain.
> 
> ```
> CHAT_LLM = ChatOpenAI(temperature=0.0, model="gpt-4",streaming=True)
> chain = prompt | CHAT_LLM
> async for chunk in chain.astream(query):
>     print(chunk.content, end="|", flush=True)
>     await websocket.send(json.dumps({"type": "stream", "data": chunk.content}))
> ```
> 
> The chunk is streamed content. Here I am using websocket to send streaming data to remote client.

do you still have a memory in this setting ?

**Comment by cfa532** [comment]
@jeanfredd No. I did not use memory in this simple chain. I read it some where that in LECL memory can be added in prompt. Now I prefer to keep chat history at client side. If I need memeory, I will compse a message with old memories and new query at client side and send it to the server. This approach is straight-forward and flexible. For example I am trying to compose a memory with only the past queries from human, I think it might be good enough to remind AI the context of the chat. It will save me a lot of tokens.

> when i create a
> 
> > The LECL is a great improvement from the old way. I happened to stumble upon a clean solution for streaming with LLMChain.
> > ```
> > CHAT_LLM = ChatOpenAI(temperature=0.0, model="gpt-4",streaming=True)
> > chain = prompt | CHAT_LLM
> > async for chunk in chain.astream(query):
> >     print(chunk.content, end="|", flush=True)
> >     await websocket.send(json.dumps({"type": "stream", "data": chunk.content}))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The chunk is streamed content. Here I am using websocket to send streaming data to remote client.
> 
> do you still have a memory in this setting ?

**Comment by TowhidKashem** [comment]
> This took me a little while to piece together, but FWIW here's what I ended up with:
> 
> ```ts
> import { ChatOllama } from '@langchain/community/chat_models/ollama'
> import { AIMessage, HumanMessage } from '@langchain/core/messages'
> import { ChatPromptTemplate, MessagesPlaceholder } from '@langchain/core/prompts'
> import { ConversationChain } from 'langchain/chains'
> import { BufferMemory, ChatMessageHistory } from 'langchain/memory'
> 
> const model = new ChatOllama({
> 	baseUrl: 'http://localhost:11434', // Default value
> 	model: 'llama3:latest',
> })
> 
> const prompt = ChatPromptTemplate.fromMessages([
> 	['system', 'You are a helpful chatbot'],
> 	new MessagesPlaceholder('history'),
> 	['human', '{input}'],
> ])
> 
> const memory = new BufferMemory({
> 	memoryKey: 'history',
> 	returnMessages: true,
> 	chatHistory: new ChatMessageHistory([]),
> })
> 
> const chain = new ConversationChain({
> 	llm: model,
> 	prompt: prompt,
> 	memory: memory,
> })
> 
> chain.stream(
> 	{ input: "What's the biggest moon in the solar system?" },
> 	{
> 		callbacks: [
> 			{
> 				handleLLMNewToken: (data) => {
> 					console.log(data)
> 				},
> 			},
> 		],
> 	}
> ).then(() => {
> 	console.log("done")
> })
> ```

This worked for me! But do you know if this is any less performant since it looks like we're triggering the "streaming" as a callback and not directly?
