### ISSUE TITLE
How to set proxy for ChatGoogleGenerativeAI in LangChain JavaScript

### ISSUE THREAD

**Issue by huotu** [langchain-ai/langchainjs#3713]
OpenAI can set proxy through configuration.httpAgent, but I can't find where to set proxy for ChatGoogleGenerativeAI

**Comment by haominglfs** [comment]
Same problem, waiting for solution

**Comment by yc-w-cn** [comment]
For ChatGoogleGenerativeAI, try this way:

```ts
import { setGlobalDispatcher, ProxyAgent } from 'undici';
const proxyAgent = new ProxyAgent({
  uri: 'http://172.16.5.147:30010'
});
setGlobalDispatcher(proxyAgent);
```

**Comment by wolpl** [comment]
The problem is still present, can we reopen this issue?
