### ISSUE TITLE
Support for AWS Bedrock agent?

### ISSUE THREAD

**Issue by codematters-pl** [langchain-ai/langchainjs#3716]
Hello,

I couldn't find any information about it, so it is the right place to ask about support for the AWS Bedrock agent. Not every region in AWS supports it (I'm using it within us-east-1)

Is there any possibility of using a predefined agent in Langchain? I can set up the endpoint
https://docs.aws.amazon.com/bedrock/latest/userguide/api-agent-invoke.html

But still, I have to set `agentAliasId`. API for the Bedrock Agent looks different, so I'm unsure if the current implementation will allow me to use it there.

Thank you in advance!

**Comment by xiaodiiii** [comment]
Any updates on this issue? I am also trying to bind bedrock built-in agents with my chatbot using langchain, but seems it is not supported in the latest release yet.
