### ISSUE TITLE
Does TogetherAI Support Callbacks, Signal, Timeout, etc.?

### ISSUE THREAD

**Issue by Chaddeus** [langchain-ai/langchainjs#3725]
```
const modelToCall = new TogetherAI({
    apiKey: '',
    modelName: '',
    streaming: true,
    callbacks: [{
        async handleLLMNewToken(token: string) {
            console.log(`Token: ${token}`)
        },
    }]
})
```

Nothing seems to be logged when trying this.

Also, when calling the model, there doesn't seem to be support for signal, timeout, etc. I use this so my user's can stop the stream when they notice the results are not what they expect. 

```
await modelToCall.call(prompt, { signal: controller.signal, timeout: 5000 })
```

I understand there is `model.stream()` but I use the callback method across multiple other models and imagine it should be standard across the board.

**Comment by jacoblee93** [comment]
CC @bracesproul
