### ISSUE TITLE
Calling the OpenAI Functions agent with an empty tool list returns an error

### ISSUE THREAD

**Issue by marius-ciocoiu** [langchain-ai/langchainjs#3726]
The agent should be run successfully and just not be able to use any tools if none are provided. This does happen if the functions parameter is not passed to the openai interface when its empty. So should be an easy fix:

1. Detect if the tools list is empty
2. Only pass the function parameter to the openai interface if its not empty.

The error is the following: `BadRequestError2: 400 [] is too short - 'functions'`

**Comment by marius-ciocoiu** [comment]
Dosu please reach to the humans that can take a look at this issue.

**Comment by jacoblee93** [comment]
Thanks for the issue! This should be filed on OpenAI, not much we can do unfortunately.
