### ISSUE TITLE
Return JSON output from OpenAI Tools Agent

### ISSUE THREAD

**Issue by garrettg123** [langchain-ai/langchainjs#3735]
I'm following https://js.langchain.com/docs/modules/agents/agent_types/openai_tools_agent exactly, and I'm wondering how one would get JSON output instead of a raw string from this new agent. Furthermore, is there a way to define the schema of the output, similar to the OpenAI Functions?

**Comment by sidgoel85** [comment]
Hello, Has this been resolved? I'm also having this issue where I'm unable to return json format from the agent, any help will be appreicated

**Comment by usersina** [comment]
This is how I did it using the `AgentExecutor` class. [It's in the docs](https://python.langchain.com/v0.2/docs/how_to/structured_output/#prompting-and-parsing-model-directly).

```python
class MyOutput(BaseClass):
    keywords: list[str] = Field(..., description="List of keywords relevant for the search")
    result: str = Field(..., description="The search result")

llm = ChatOpenAI()
tools = [TavilySearchResults(max_results=2)]

parser = PydanticOutputParser(pydantic_object=MyOutput)
prompt = ChatPromptTemplate.from_messages(
    [
        (
            "system",
            system_prompt
            + "\nWrap the output in `json` tags\n{format_instructions}",
        ),
        MessagesPlaceholder(variable_name="messages"),
        MessagesPlaceholder(variable_name="agent_scratchpad"),
    ]
).partial(format_instructions=parser.get_format_instructions())

agent = create_openai_tools_agent(llm, tools, prompt)

executor = AgentExecutor(agent=agent, tools=tools)   # type: ignore https://github.com/langchain-ai/langchain/issues/13075
```

It prints the response with json tags in the end, but you should be able to get a full json with [custom parsing](https://python.langchain.com/v0.2/docs/how_to/structured_output/#custom-parsing).
