### ISSUE TITLE
Using document loaders from an Electron Application. 

### ISSUE THREAD

**Issue by jwhenry28** [langchain-ai/langchainjs#3777]
As per [the LangChain JS docs](https://js.langchain.com/docs/integrations/document_loaders), most of the document loaders require NodeJS to run properly. 

Unfortunately, this seems to prevent their use in Electron application, which (while desktop applications) technically run via Chromium. For example, if I include the following code in an Electron application:
```
let infile = this.baseDir + "/TestFile.md";
this.loader = new TextLoader(infile);
const docs = await this.loader.load();
```

I get the following error:
```
Error: Failed to load fs/promises. TextLoader available only on environment 'node'. It appears you are running environment 'browser'. See https://<link to docs> for alternatives.
```

Looking in the source code, I can see this error triggered here: https://github.com/langchain-ai/langchainjs/blob/main/langchain/src/document_loaders/fs/text.ts#L88
```
try {
  const { readFile } = await import("node:fs/promises");
  return { readFile };
} catch (e) {
  console.error(e);
  throw new Error(
    `Failed to load fs/promises. TextLoader available only on environment 'node'. It appears you are running environment '${getEnv()}'. See https://<link to docs> for alternatives.`
  );
}
```

Is there a workaround that we can use to call `TextLoader` or similar document loaders from an Electron application?

And for reference:
```
$ npm list
...
├── langchain@0.0.211
...
```

**Comment by jwhenry28** [comment]
This solution above did not work. 

After looking closer at the LangChain source code for TextLoader, I found [a way to avoid the call](https://github.com/langchain-ai/langchainjs/blob/main/langchain/src/document_loaders/fs/text.ts#L46) to `readFile`:
```
if (typeof this.filePathOrBlob === "string") {
  const { readFile } = await TextLoader.imports();
  text = await readFile(this.filePathOrBlob, "utf8");
  metadata = { source: this.filePathOrBlob };
} else {
  text = await this.filePathOrBlob.text();
  metadata = { source: "blob", blobType: this.filePathOrBlob.type };
}
```

So if we pass in a `Blob` to the loader instead of a file name, it seems to work:
```
let infile = this.baseDir + "/TestFile.md";
const fileBlob = await fileToBlob(infile); // custom helper function to read a file as a Blob from Electron app
const fileText = await fileBlob.text();
this.loader = new TextLoader(fileBlob);
const docs = await this.loader.load();
```

Please let me know if there is a better solution.

**Comment by andrewnguonly** [comment]
I'm running into a similar issue with using the document loaders (e.g. `TextLoader`) in a Chrome extension. I'm trying to figure out how to get Webpack to build the extension. Will update this thread if I have a solution.

**Comment by Charles1713** [comment]
> This solution above did not work. 
> 
> After looking closer at the LangChain source code for TextLoader, I found [a way to avoid the call](https://github.com/langchain-ai/langchainjs/blob/main/langchain/src/document_loaders/fs/text.ts#L46) to `readFile`:
> ```
> if (typeof this.filePathOrBlob === "string") {
>   const { readFile } = await TextLoader.imports();
>   text = await readFile(this.filePathOrBlob, "utf8");
>   metadata = { source: this.filePathOrBlob };
> } else {
>   text = await this.filePathOrBlob.text();
>   metadata = { source: "blob", blobType: this.filePathOrBlob.type };
> }
> ```
> 
> So if we pass in a `Blob` to the loader instead of a file name, it seems to work:
> ```
> let infile = this.baseDir + "/TestFile.md";
> const fileBlob = await fileToBlob(infile); // custom helper function to read a file as a Blob from Electron app
> const fileText = await fileBlob.text();
> this.loader = new TextLoader(fileBlob);
> const docs = await this.loader.load();
> ```
> 
> Please let me know if there is a better solution. 

I just wanted to thank you for this solution. I'm about to test it later, but it gets rid of my fs error.
