### ISSUE TITLE
HNSW Lib does not work even after installing hnswlib-node

### ISSUE THREAD

**Issue by KaKashi1210** [langchain-ai/langchainjs#3782]
After Installing hnswlib-node the issue persists- 
![image](https://github.com/langchain-ai/langchainjs/assets/97914006/b60ce3c7-91f8-4c55-b1ce-9c74199fbd10)

**Comment by mo29cg** [comment]
same here

**Comment by jacoblee93** [comment]
It looks like you're using `bun` - can you try with just base `node`?

It might be worth opening an issue/PR on the HNSW package for `bun` support.

**Comment by KaKashi1210** [comment]
@jacoblee93  thanks for the idea much appreciated <3

**Comment by ddosakura** [comment]
use bun 1.1.0+

**Comment by cshaxu** [comment]
same here, but I am using Node 18.18.0 - any recommendations please?
