### ISSUE TITLE
How to use external links to load PDF files in nodejs, similar function OnlinePDFLoader is used in Python docs

### ISSUE THREAD

**Issue by araza110** [langchain-ai/langchainjs#3787]
### Load PDF from an external link

I want to use the `PDFLoader()` function, but instead of passing a file path, I want to pass an external PDF link, such as a link that is uploaded on S3. In Python, I have seen a function: `loader = OnlinePDFLoader("https://arxiv.org/pdf/2302.03803.pdf")`. However, I can't find this function in the JS/TS documentation. Is there an alternative way to achieve this?

**Comment by jacoblee93** [comment]
@dosubot is the approach I'd say - we could build it in but will close this for now.

**Comment by sohamsal** [comment]
Not sure if I'm doing something wrong but I keep getting this error with the code above
![image](https://github.com/langchain-ai/langchainjs/assets/34986453/1ff0dc86-dcba-45d0-ac2a-f4245eca02dc)
