### ISSUE TITLE
VectorStoreRetrieverInterface test issue

### ISSUE THREAD

**Issue by gkhngyk** [langchain-ai/langchainjs#3818]
Hi, 
I am fixing problems with types in the `/autogpt/prompt.ts`  file.  I am also creating a test script for `prompt.ts`.

I see that type of `memory` parameter of `formatMessages` function of `AutoGPTPrompt` class  is `VectorStoreRetrieverInterface`

I have added `/tests/prompt.test.ts` file and  I tried to create `mockMemory` for testing the formatMessages function.
```typescript
const mockMemory: VectorStoreRetrieverInterface = {
  getRelevantDocuments: async () => [
    { pageContent: "relevant content", metadata: {} },
  ],
}; 
```

The repo passes all tests but I get an error when I build it because the mockMemory gives the following error; 

```Type '{ getRelevantDocuments: () => Promise<{ pageContent: string; metadata: {}; }[]>; }' is missing the following properties from type 'VectorStoreRetrieverInterface<VectorStoreInterface>': vectorStore, addDocuments, lc_serializable, invoke, and 3 more.ts(2740)```

Do we have a fake VectorStoreRetrieverInterface or do you know a way to easily add the properties?

**Comment by gkhngyk** [comment]
@jacoblee93  I see you updated the relevant file last week. Maybe you can help 🙏

**Comment by jacoblee93** [comment]
Can you just type it as `any` if it's a mock?

**Comment by gkhngyk** [comment]
> Can you just type it as `any` if it's a mock?

Thanks for the answer, 
I solved it with any. You can close the Issue.

Happy new year
