### ISSUE TITLE
OpenAI functions and memory -- a 2nd question in same conversation is causing functions from 1st question to be called again

### ISSUE THREAD

**Issue by scottsuhy** [langchain-ai/langchainjs#3823]
I've been going back and forth with @dosu-bot on [the forum here](https://github.com/langchain-ai/langchainjs/discussions/3810) about this.

I moved it here as I am starting to wonder if this is by design, or I am doing something wrong, or is this a bug? 

Here is the issue--I am using an OpenAI functions agent and BufferMemory (I followed the example [here](https://js.langchain.com/docs/modules/agents/agent_types/openai_functions_agent))

In a conversation, when a user asks a question such as "get the stock price of Apple" the answer is returned fine by the agent using a GETSTOCKPRICE() function call to get the data for the agent to provide the answer.

However, when the user asks a second question, in that same conversation, such as "get the earnings call transcript for Apple for Q3 of 2023", for some reason the Agent calls the GETSTOCKPRICE() function again before calling the GETTRANSCRIPT() function. This is not what I want.

What I would prefer would be to have the previous answer in memory, and a second question would not cause the agent to call the first function again.

is this by design, if so, is there a workaround?

**Comment by scottsuhy** [comment]
the entire reason I am using BufferMemory is to have memory so why would I want to clear it?  

I have no problem with this: 

_"but rather a characteristic of how OpenAI's language models work. When you use BufferMemory, the entire conversation history is passed to the model each time you call it. This means that the model sees the entire conversation each time, and it may choose to respond to earlier parts of the conversation again."_  

what I have a problem with is that the agent is calling functions to past questions in the conversation again, when it already has the answer that it can use in memory.  Why would it be designed this way?  if you are paying for api calls to a third party vendor this could be a deal killer.

**Comment by jacoblee93** [comment]
That should be what's happening - are you using LangSmith? Can you share a trace?

**Comment by scottsuhy** [comment]
I just signed up for langsmith this am.  I am out of town until Sunday but will upload a trace when I return.

**Comment by scottsuhy** [comment]
@jacoblee93 here are both traces:
(first question) https://smith.langchain.com/public/950ca9da-542c-4e09-9b91-8de17019f484/r
(second question that repeats the first question) https://smith.langchain.com/public/99a9f295-837e-4191-901d-d5b574aa7e68/r
