### ISSUE TITLE
Getting "error TS2554: Expected 1-2 arguments, but got 3" error

### ISSUE THREAD

**Issue by vardamanpk** [langchain-ai/langchainjs#3825]
While doing `yarn run build` inside the examples folder getting 
```
src/indexes/vector_stores/vectara.ts:64:3 - error TS2554: Expected 1-2 arguments, but got 3.

64   true
```

**Comment by vardamanpk** [comment]
> _🤖_
> 
> Thanks for providing the error message, it's very helpful. However, I'm still missing some context to fully understand the issue. Could you please provide the following information:
> 
> * The version of langchainjs you're using.
> * The exact command you're running when you encounter this error.
> * The context around the line of code that's causing the error (a few lines before and after would be helpful).
> 
> This will help me better understand the problem and provide a more accurate solution.
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

I am trying to set up the repository locally and I am using `yarn run build` command after `yarn` command.

**Comment by medic-code** [comment]
Could you provide a few more details on your environment and your steps to reproduce this error ? i've just did a fresh pull and build and didn't come up against the error.
