### ISSUE TITLE
Custom prompt template VectorDBQAChain (non-english documents)

### ISSUE THREAD

**Issue by soukicz** [langchain-ai/langchainjs#384]
Hi,
I am trying to use langchainjs to create Q&A and it works really well! My only problem is language support. Input documents (and questions) are non-english but Q&A prompt is in english and that confuses OpenAI - it sometimes responds in english, sometimes in document language.

I have found source code that has hard-coded english prompt (https://github.com/hwchase17/langchain/blob/8e5c4ac8672b98b3c53884843a4fe57a0b79dcae/langchain/chains/vector_db_qa/prompt.py) but I can't figure out how to override it from langchainjs. Is that possible? Or should I just create my own chain? Is that even possible?

Thank you for any help

**Comment by r0man1337** [comment]
try this:
```
    const chain = ChatVectorDBQAChain.fromLLM(model, vectorStore, {
      returnSourceDocuments: true,
      qaTemplate: "Your prompt. {context} Question: {question}",
    });
```

But this parameter is available only for **ChatVectorDBQAChain**, not **VectorDBQAChain**

**Comment by soukicz** [comment]
> But this parameter is available only for **ChatVectorDBQAChain**, not **VectorDBQAChain**

Oh, I completely forgot that I can just use chat version (and qaTemplate didn't exist 5 days ago). It is basically the same if I only use it for single response.

Thank you, it works perfectly! I have just translated default prompt template, used qaTemplate and it works as expected.
