### ISSUE TITLE
Issue: OpenAI model does not use specified model. 

### ISSUE THREAD

**Issue by Dragos-P-Popa** [langchain-ai/langchainjs#3841]
LangChain 0.0.213 | Node v18.18.2

As described in the title, when creating an OpenAI model and specifying the `modelName` it seems like it is not respected.

```js
const model = new OpenAI({
  temperature: 0.6,
  openAIApiKey: OPENAI_KEY,
  modelName: 'gpt-4-1106-preview'
});
```

I have tried multiple models such as `gpt-4-1106-preview`,`gpt-3.5-turbo-1106` and `gpt-3.5-turbo` but I run into the same issue with all of them. The prompt I am passing is around 12k tokens, with every model I have tried using I run into the same error;
`This model's maximum context length is 8192 tokens, however you requested 12656 tokens (12656 in your prompt; 0 for the completion). Please reduce your prompt; or completion length.`

This is even the case when trying `gpt-3.5-turbo` which has a max context window of 4096 tokens.

**Comment by Dragos-P-Popa** [comment]
@dosu-bot you can specify the modelName. Here is an example taken from;  [https://js.langchain.com/docs/integrations/chat/openai#calling-fine-tuned-models](url)

```js
const modelForFunctionCalling = new ChatOpenAI({
  modelName: "gpt-4",
  temperature: 0,
});
```

**Comment by medic-code** [comment]
Please take my advice with a pinch of salt

Can you provide a minimal reproducible example that illustrates the bug/issue you're facing ? What I mean by that is that can you share a piece of code that is small enough to reproduce the problem you are facing.

Couple of things to keep in mind, context window refers to the total number of tokens, input, output and control tokens and has a fixed limit on how many output tokens. 

So in your example of gpt-3.5-turbo - you've provided 12k of tokens when the context window is 4096 tokens, so it will throw an error. 

Seems a little puzzling you're getting an error with 'gpt-4-1106-preview' when the context window is rather larger. This is why I've asked about a minimal viable example that illustrates it. 

Just some general  tips you can either take or leave, its always worth giving a minimum example that illustrates the problem, tell us what you think is going on yourself if you had to guess or what you've looked at, show what you've tried so far and where you are stuck or don't understand. Showing your work up front and writing about it will often give you knowledge or insights you didn't think about. 

Resources to consider
https://stackoverflow.com/help/minimal-reproducible-example
