### ISSUE TITLE
FewShotChatMessagePromptTemplate won't bring prefix and suffix into chain

### ISSUE THREAD

**Issue by casyalex** [langchain-ai/langchainjs#3851]
https://github.com/langchain-ai/langchainjs/blob/61f35dc569e56aef4df58a15f94e5d75b3a49137/langchain-core/src/prompts/few_shot.ts#L429

even though format method can print suffix and prefix.

But it won't take effect into a chat model.

**Comment by medic-code** [comment]
@casyalex do you have a minimal reproducible example to illustrate this ?

**Comment by casyalex** [comment]
Yes, it still exist
