### ISSUE TITLE
Runnable streaming: different types for streamed chunks and return values

### ISSUE THREAD

**Issue by davidfant** [langchain-ai/langchainjs#3880]
# Use Case
I want to use streaming for my custom runnable, and for the streamed chunks I want to have a _different_ type than the runnable return type. In my case I'd want:
```typescript
interface MyRunnable<RunInput, RunOutput> {
  ...
  stream(input: RunInput): AsyncGenerator<Partial<RunOutput>, RunOutput> {
    let progress = {};
    progress = yield { ...progress, first: 1 };
    progress = yield { ...progress, second: 2 };
    return { ...progress, third: 3 };
  }
}

// usage
const runnable = new MyRunnable(...);
const stream = runnable.stream(input);
while (true) {
  const next = await runnable.next();
  if (next.done) return next.value; // RunOutput
  else showPartialProgressToUser(next.value); // Partial<RunOutput>
}

```

# Problems
There are some problems with doing this:
1. In `RunnableInterface`, the stream function iterator needs to return `RunOutput`: https://github.com/langchain-ai/langchainjs/blob/6e5d02188bd29c7fe51ff1440a097150f88c547d/langchain-core/src/runnables/base.ts#L68-L71
That doesn't necessarily make sense. I haven't looked at how the LLM streaming works, but for e.g. OpenAI, the data returned from their streaming API isn't the same as for their non-streaming API.
Idea: add a new generic to `RunnableInterface` like:
```ts
export interface RunnableInterface<
  RunInput = any,
  RunOutput = any,
  StreamOutput= RunOutput,
  CallOptions extends RunnableConfig = RunnableConfig
> {
...

stream(
    input: RunInput,
    options?: Partial<CallOptions>
  ): Promise<IterableReadableStreamInterface<StreamOutput>>;
}
```
This makes it backwards compatible with the existing codebase since StreamOutput is defaulted to RunOutput.

2. I don't have much context on `IterableReadableStream`, but somehow it would need to have types similar to AsyncGenerator which has different types for yielded data and returned data. There are comments like `convention is to ignore final chunk value anyway`: https://github.com/langchain-ai/langchainjs/blame/6e5d02188bd29c7fe51ff1440a097150f88c547d/langchain-core/src/utils/stream.ts#L44. git blame says it's from @jacoblee93, but might have been someone else as it seems like those commits are related to a refactor.
So maybe what I want to do isn't conventional or how one should do it. In that case, please enlighten me on how I can accomplish my above goal!

**Comment by jacoblee93** [comment]
I think a final type parameter would be ok - might be tricky to implement though as you would need to pass it through in many places.

Is there no way to make the steamed output extend the invoked run output?

Iterable readable stream would just yield StreamOutput

**Comment by davidfant** [comment]
Reg making the streamed output extend the invoked output, I'm "streaming" partial updates of a more complex chain. E.g. 
```ts
interface Output {
  reasoning: string;
  toolId: string;
}
```

would stream:
```
yield { reasoning: "..." }
...
yield { reasoning: "...", toolId: "..." }
```

So the streamed output doesn't have the shape of Output. I'm currently casting all yielded output to `Partial<RunOutput>` where it's used, which works but makes me cast types in the implementation rather than define the correct types with the runnable class.
