### ISSUE TITLE
400 Error with Cohere Embed API: Invalid input_type with Model

### ISSUE THREAD

**Issue by TomsF1** [langchain-ai/langchainjs#3894]
### Environment:

Langchain Version: 0.0.214
Cohere SDK Version: 7.6.2

### Issue Description:
I'm encountering an issue when trying to use the CohereEmbeddings class with Cohere v7 SDK and v3 embeddings. The API is returning a 400 status code with an error message indicating an invalid input_type for the provided model. Despite various attempts to correctly format the inputType parameter, the error persists.

### Error Message:

`Status code: 400
Body: {
  "message": "invalid request: valid input_type must be provided with the provided model"
}
`
### Attempted Solutions:

I've tried various formats for the inputType parameter, including escaping double quotes, using Unicode representations, and wrapping the value with different types of quotes.

### Expected Behavior:
The API call should successfully process with the given inputType.

### Actual Behavior:
The API call fails with a 400 status code and an error message about an invalid input_type.

### Steps to Reproduce:

Instantiate a new CohereEmbeddings with the following parameters:

`new CohereEmbeddings(
    {
      model: "embed-multilingual-v3.0",
      batchSize: 48,
      inputType: '"search_query"',
      verbose: true,
      apiKey: [API key]
    }
)
`

**Comment by bracesproul** [comment]
@TomsF1 are you using the [`@langchain/cohere`](https://www.npmjs.com/package/@langchain/cohere) package or the [`langchain`](https://www.npmjs.com/package/langchain) package? 

In order to use `input_type` and the new models you must be using `@langchain/cohere`.

**Comment by ladrians** [comment]
@TomsF1 my 2 cents. Please make sure you have "@langchain/cohere": "^0.0.2". I had the same problem and could validate that with this version it worked. Previously it was working for ingesting data, but not querying using a `v3*` model.

**Comment by TomsF1** [comment]
@ladrians thanks I can confirm once updating to "@langchain/cohere": "^0.0.2" and removing the double quotations as below has resolved the issue.

`new CohereEmbeddings( { model: "embed-multilingual-v3.0", batchSize: 48, inputType: "search_query", verbose: true, apiKey: [API key] } ) `
 
 @bracesproul thanks for your contribution with integrating Cohere v7 SDK, has already solved a few issues with my own custom classes.
