### ISSUE TITLE
How to get Embedding used token?

### ISSUE THREAD

**Issue by mingxin-yang** [langchain-ai/langchainjs#3908]
```js
const { OpenAIEmbeddings } = require("langchain/embeddings/openai");

const embedModel = new OpenAIEmbeddings({
  openAIApiKey: _apiKey,
});

const vectorStore = await HNSWLib.fromDocuments(docs, embedModel);

const dir = Utils.createDir(id, md5Name);
const vectorDir = path.join(dir, "vector");
await vectorStore.save(vectorDir);

```
The above code uses OpenAIEmbeddings to store docs into HNSWLib. How to obtain the token consumed in this process?

**Comment by jacoblee93** [comment]
This currently isn't supported but would be good to look into.

**Comment by MJDeligan** [comment]
It would be very useful to have a callback for embeddings response data in general! Is there any news on this @jacoblee93 ?

**Comment by jacoblee93** [comment]
I think there was a PR a while back but it never got consensus - what's the use case for you?

**Comment by MJDeligan** [comment]
Thanks for getting back so quickly! We're keeping track of the cost of embeddings on a user basis. Currently we're estimating the cost, which works well enough, but ideally we would of course use the usage data that OpenAI send in their embeddings response. 

We're thinking about writing our own Embeddings class to allow us to pass a callback which can process the entire embeddings response, but we're not entirely sure about the exact behavior.

**Comment by jacoblee93** [comment]
I'll bring it up again today!

**Comment by esoler-sage** [comment]
@jacoblee93 Do you mean this one? https://github.com/langchain-ai/langchainjs/pull/1859
