### ISSUE TITLE
searchapi_google_news example does not implement Search Tools

### ISSUE THREAD

**Issue by tutuxxx** [langchain-ai/langchainjs#3923]
yarn run start ./src/tools/searchapi_google_news.ts

output:
{
  input: "What's happening in Ukraine today?",
  output: AIMessage {
    lc_serializable: true,
    lc_kwargs: {
      content: 'As of my last update in early 2023, I cannot provide real-time news updates or current events, including the situation in Ukraine. For the most recent information, please consult a reliable news source or a real-time news service. Here are some general points that might have been relevant up to early 2023...',
      additional_kwargs: [Object]
    },
    lc_namespace: [ 'langchain_core', 'messages' ],
    content: 'As of my last update in early 2023, I cannot provide real-time news updates or current events, including the situation in Ukraine. For the most recent information, please consult a reliable news source or a real-time news service. Here are some general points that might have been relevant up to early 2023...',
    name: undefined,
    additional_kwargs: { function_call: undefined, tool_calls: undefined }
  }
}

How to make SearchApi Tools work?

**Comment by medic-code** [comment]
Could you provide a minimal reproducible example that illustrates the problem ? What do you think is wrong and what have you tried ? Sorry to ask these questions but it will let people help you better!

**Comment by medic-code** [comment]
Do you have a valid searchapi api key ?

**Comment by tutuxxx** [comment]
> Do you have a valid searchapi api key ?

Yes, the following example is working fine:
const tool = new SearchApi(process.env.SEARCHAPI_API_KEY, {
  engine: "google_news", {
}); const res = await tool.call(

const res = await tool.call("What's happening in Ukraine today?");

console.log(res);
res ==> RFE/RL's Ukraine Live Briefing gives you the latest developments on Russia's ongoing invasion, Western military aid, global reaction,...


My guess is that the problem may be with AgentExecutor.fromAgentAndTools, which you can try by running https://github.com/langchain-ai/langchainjs/blob/main/examples/src/tools/searchapi_ google_news.ts and try
