### ISSUE TITLE
GraphQL Tool

### ISSUE THREAD

**Issue by ayalpani** [langchain-ai/langchainjs#394]
I am currently exploring the Agents API and could not find a GraphQL Tool. Are you planning to provide one?

(thanks for langchain!)

**Comment by Alw3ys** [comment]
This would be interesting, I could actually take it up the development.  - If you think we should implement it @nfcampos.

**Comment by nfcampos** [comment]
This is partially solved in #596 
But would be good to have a builtin tool that doesn't depend on an external api

**Comment by yalelev** [comment]
🧟  
Was anything ever merged in to support this feature? [596]( https://github.com/langchain-ai/langchainjs/pull/596 ) hasn't moved in almost a year.  The latest docs still don't show a JS tool or agent for handling graphQL calls (AFAIK). Are there known workarounds beyond switching to the Python version?
