### ISSUE TITLE
Creating a conversation agent with tools and history for Ollama

### ISSUE THREAD

**Issue by dmtrrk** [langchain-ai/langchainjs#3942]
I'm trying to create a simple test that can:
- use Ollama as the model
- use the agent with my custom tools to enrich the output
- history to store the conversation history

Based on examples, the code should look like this:

```
const llm = new ChatOllama(...);
const tools = [...];
const executor = await initializeAgentExecutorWithOptions(tools, llm, ...);
```

the compiler does not like `llm` parameter because
```
The argument of type 'ChatOllama' is not assignable to the parameter of type 'BaseLanguageModelInterface<any, BaseLanguageModelCallOptions>'
```
and this is the same for OpenAI llm as well.
I don't see this `BaseLanguageModelCallOptions` interface being used anywhere in the code. Is this the right way to use it?

**Comment by dmtrrk** [comment]
it looks like there is a disconnection between [BaseLanguageModelInterface](https://github.com/langchain-ai/langchainjs/blob/main/langchain-core/src/language_models/base.ts#L242) and [BaseChatModel](https://github.com/langchain-ai/langchainjs/blob/main/langchain-core/src/language_models/chat_models.ts#L96).

**Comment by jacoblee93** [comment]
What version of LangChain and LangChain core are you using?

This may have been related to #3918, which locking core to `0.1.10` should fix.

Also, keep in mind that agents generally require pretty powerful models, and may be beyond what you can run on local hardware (though you should definitely try!)

We also have a new method for creating agents in the later versions of LangChain:

https://js.langchain.com/docs/modules/agents/quick_start

**Comment by jacoblee93** [comment]
I believe the above fixes it, please comment and reopen if it does not!
