### ISSUE TITLE
ERR_INVALID_URL error for APIChain.fromLLMAndAPIDocs

### ISSUE THREAD

**Issue by echong112** [langchain-ai/langchainjs#3956]
when I try running this endpoint, I need getting "ERR_INVALID_URL" error after running the invoke method. 

https://github.com/echong112/jacob/blob/main/sports.ts

any thoughts on what might be causing this?

**Comment by rachfiandj07** [comment]
Hi im interested to fix this kind of bugs as first new-comers issue

**Comment by echong112** [comment]
@dosu-bot

where can i pass the URL for that method?
