### ISSUE TITLE
Quickstart Page Issue - the import statement needs to be fixed for the embedding model 

### ISSUE THREAD

**Issue by anshu707** [langchain-ai/langchainjs#3977]
In the [quickstart page](https://js.langchain.com/docs/get_started/quickstart), for the embedding model while trying to index the document in the vector store, 
the import is done from 
`@langchain/community/ollama/embeddings`
instead it should be from 
`@langchain/community/embeddings/ollama`

**Comment by jacoblee93** [comment]
Ah crud, thank you!
