### ISSUE TITLE
Declarations export missed in @langchain/core/index.d.ts

### ISSUE THREAD

**Issue by Brown000** [langchain-ai/langchainjs#3987]
## Environment
Node: v18.18.0
Nestjs: ^10.0.0
langchain: ^0.1.2

## tsconfig.json
``` json
"module": "commonJs",
"target": "ES2021"
```

## Issue
When trying to create a custom Embedding class implements EmbeddingsInterface, I found that interface was not exported. The "@langchain/core/index.d.ts" file exported declarations in "./dist/index.js", which does not exist. Is this will be fixed in the next release?

**Comment by jacoblee93** [comment]
This is exported from:
```
import {
  type EmbeddingsInterface,
  Embeddings,
} from "@langchain/core/embeddings";
```
There is no default entrypoint in `@langchain/core`.
