### ISSUE TITLE
Getting  error "Module not found: Can't resolve 'child_process'"  when using BedrockChat in langchainjs

### ISSUE THREAD

**Issue by raksrivastava** [langchain-ai/langchainjs#3988]
```
   import { BedrockChat } from "@langchain/community/chat_models/bedrock";
import { HumanMessage } from "@langchain/core/messages";
const model = new BedrockChat({
      model: "meta.llama2-13b-chat-v1",
      region: "us-east-1",
      credentials: {
        accessKeyId: `${process.env.AWS_CLIENT_CREDENTIALS_ACCESS_KEY}`,
        secretAccessKey: `${process.env.AWS_CLIENT_CREDENTIALS_SECRET_ACCESS_KEY}`,
      },
    });
    const res = await model.invoke([
      new HumanMessage({ content: "Tell me a joke" }),
    ]);
    console.log(res);
```

I am getting the below error on running the above code

Server Error
**Error: Module not found: Can't resolve 'child_process'

https://nextjs.org/docs/messages/module-not-found**

Import trace for requested module:
./node_modules/@aws-sdk/credential-provider-process/dist-es/fromProcess.js
./node_modules/@aws-sdk/credential-provider-process/dist-es/index.js
./node_modules/@aws-sdk/credential-provider-node/dist-es/defaultProvider.js
./node_modules/@aws-sdk/credential-provider-node/dist-es/index.js
./node_modules/@langchain/community/dist/chat_models/bedrock/index.js
./node_modules/@langchain/community/chat_models/bedrock.js
./app/api/chat/retrieval/route.ts
./node_modules/next/dist/build/webpack/loaders/next-edge-app-route-loader/index.js?

**Comment by jacoblee93** [comment]
Please reopen if the above doesn't fix it!
