### ISSUE TITLE
Can not locate HumanMessage and AIMessage

### ISSUE THREAD

**Issue by jessequartey** [langchain-ai/langchainjs#3989]
In langchainjs I used to get HumanMessage and AIMessage by  import { HumanMessage, AIMessage } from "langchain/schema";
now in the new update i have this in my console
[WARNING]: Importing from "langchain/schema" is deprecated.
Instead, please import from the appropriate entrypoint in "@langchain/core" or "langchain".
This will be mandatory after the next "langchain" minor version bump to 0.2.

i have checked these to modules and i am not finding Schema Module.

**Comment by bracesproul** [comment]
Hey @jessequartey you can import those from:
```typescript
import { AIMessage, HumanMessage } from "@langchain/core/messages";
```
