### ISSUE TITLE
@langchain/core not installed by default?

### ISSUE THREAD

**Issue by garmeeh** [langchain-ai/langchainjs#3990]
In the docs it states:

> The [@langchain/core](https://www.npmjs.com/package/@langchain/core) package contains base abstractions that the rest of the LangChain ecosystem uses, along with the LangChain Expression Language. It is automatically installed along with langchain, but can also be used separately.

But if I want to import a type, for example:

```
import type { VectorStoreRetriever } from '@langchain/core/vectorstores';

myRetriever(): VectorStoreRetriever<SupabaseVectorStore>
```

I need to install it separately.

**Comment by jacoblee93** [comment]
It is a dependency of all packages:

https://github.com/langchain-ai/langchainjs/blob/main/langchain/package.json#L1206

What is the error you're seeing?

**Comment by garmeeh** [comment]
For example, in a fresh project I installed `langchain` then I try import this package:

```
import { ChatOpenAI } from "@langchain/openai";
```

I get this errro:

```
Cannot find module '@langchain/openai' or its corresponding type declarations.
```

![CleanShot 2024-01-12 at 19 21 36@2x](https://github.com/langchain-ai/langchainjs/assets/13333582/92e61851-2ae3-4861-90ee-94f204090d56)

![CleanShot 2024-01-12 at 19 21 52@2x](https://github.com/langchain-ai/langchainjs/assets/13333582/983ec85f-5ea7-4a30-854d-2769c0280420)

**Comment by jacoblee93** [comment]
Could be some Typescript setting?

If you look in your node modules is it there? The fix for now is to just install them manually and possibly set overrides.

**Comment by JakubKontra** [comment]
I am facing same issue
