### ISSUE TITLE
Types of property generatePrompt are incompatible.

### ISSUE THREAD

**Issue by classfang** [langchain-ai/langchainjs#4003]
```
    const model = new ChatOpenAI({
      modelName: 'gpt-3.5-turbo',
      openAIApiKey: openaiConfig.key,
      configuration: {
        baseURL: openaiConfig.baseUrl
      }
    })
    const chain = RetrievalQAChain.fromLLM(model, vectorStore.asRetriever())
```

Vue: Argument of type ChatOpenAI<ChatOpenAICallOptions> is not assignable to parameter of type
BaseLanguageModelInterface<any, BaseLanguageModelCallOptions>
Types of property generatePrompt are incompatible.

**Comment by jacoblee93** [comment]
Which version of LangChain are you using? Could you try reinstalling latest if you're not on it yet?

Also, if you have the full typescript error, that would be really helpful.

**Comment by classfang** [comment]
**version info:**
```
"@langchain/community": "^0.0.17",
"@langchain/openai": "^0.0.12",
"langchain": "^0.1.3"
```

**type error:**
![WechatIMG708](https://github.com/langchain-ai/langchainjs/assets/27616248/bb4c3075-73bd-4f3e-8fad-5bde90aaf7e4)

**Comment by jacoblee93** [comment]
I will try to repro again today - thought we had fixed this sorry :(

**Comment by jacoblee93** [comment]
Do you have the `resolutions` (yarn) or `overrides` (npm) fields set?

https://js.langchain.com/docs/get_started/installation#installing-integration-packages

**Comment by OliverBeckwith** [comment]
@jacoblee93 my apologies, I had presumed that since I had `@langchain/core` installed as a regular dependency it would serve the same purpose as a resolution. I have specified it as a resolution and it fixed the type mismatches 🪄. 

Thanks for the assistance.
