### ISSUE TITLE
Docs: Typescript example not working. Needed a workaround (typing)

### ISSUE THREAD

**Issue by ed3899** [langchain-ai/langchainjs#4009]
At https://js.langchain.com/docs/modules/agents/how_to/custom_agent

The following example thrown a ts error.

```
import { formatToOpenAIFunction } from "langchain/tools";

const modelWithFunctions = model.bind({
  functions: tools.map((tool) => formatToOpenAIFunction(tool)),
});
```

The error:
```
Type 'Function' is not assignable to type 'FunctionDefinition'.
  Property 'parameters' is optional in type 'Function' but required in type 'FunctionDefinition'.ts(2322)
```

The likely cause: https://github.com/langchain-ai/langchainjs/blob/44b00c0d21b4faf15f78209339191a959077128f/langchain-core/src/language_models/base.ts#L202

Line 202

The params of FunctionDefinition:

```
 parameters: Record<string, unknown>;
```

Seem to cause the conflict with:
```
OpenAIClient.Chat.Completions.ChatCompletionCreateParams.Function
```

The workaround in the meantime:
```
formatToOpenAIFunction(this.customTool) as FunctionDefinition,
```

Just make the params in sync

**Comment by jacoblee93** [comment]
Hey sorry you're encountering this - what version of LangChain are you using?

**Comment by jacoblee93** [comment]
Never mind, I see the problem - you can fix this in the immediate term by switching the import to `@langchain/openai` but I will also patch this.

**Comment by jacoblee93** [comment]
New core methods are live in `@langchain/core` 0.1.13:

If you upgrade to latest langchain or just bump core you can do:

```ts
import { convertToOpenAIFunction } from "@langchain/core/utils/function_calling";

const modelWithFunctions = model.bind({
  functions: tools.map((tool) => convertToOpenAIFunction(tool)),
});
```

https://js.langchain.com/docs/modules/agents/how_to/custom_agent#bind-tools-to-llm
