### ISSUE TITLE
pdf parser not working compared to python version

### ISSUE THREAD

**Issue by zitongzhang098** [langchain-ai/langchainjs#4014]
Hi community:
I tried to parse a Chinese PDF by using PDFLoader but it returns a lot of random characters. I then tried pyparser in python and it worked as expected. Not sure what's the problem. I attached the pdf file and hope someone can help.

## Langchain version
    "langchain": "0.1.2"
## Code in typescript
```typescript
import { PDFLoader } from "langchain/document_loaders/fs/pdf";
import path from 'path';

const pdfParser = new PDFLoader(path.resolve(__dirname, './why.pdf'));
const docs = await pdfParser.load()
docs.map((doc) => {
    console.log(doc.pageContent)
}) 
```
## Result 
a lot of whitespace and 
!"# !!!!!!!!!!!!"

also a lot of warnings
- Warning: Unknown type 1 charstring command of "0"

## Code in python
```python
from langchain_community.document_loaders import PyPDFLoader

loader = PyPDFLoader("why.pdf")
pages = loader.load_and_split()
```

## Result Preview
[Document(page_content='新编\n十万个\n为什么\n第一册\n齐豫生徐茂魁主编\n台海出版社', metadata={'source': 'why.pdf', 'page': 1}),
 Document(page_content='编辑委员会\n主编：\n齐豫生徐茂魁\n副主编：\n丁华民王茁芝夏于全\n编委：\n殷奎光杨泰峰周兴华\n常桦潘国平田爽\n尹建军周广宇文玉俊\n訾慧敏张桦蒲昭虹\n雷玉东郭强张秀英\n章函谷许之山王咏竹\n郭鹏飞龙维智林家鹤\n蔡磊王冰怿冯文轩\n肇英王连军邹冬红\n印政廖海虹丁荣英\n郭晓溧白德力格尔玛', metadata={'source': 'why.pdf', 'page': 2}),
 Document(page_content='前言\n时间作为人类时空的第四维，它时钟的标尺已经指向了二\n!!!\n这个单纯然而振奋人心的数字。人们回头看时，人类的历\n史宛如浩瀚的烟波，里面的每一个水滴都饱含着人类双手操作与\n头脑思考而凝聚的精华。\n然而我们不需望洋兴叹，一部百科全书式的著作———《新编\n十万个为什么》在世纪钟声敲响之时，欣然付梓了。它尽其所能\n地对现有的自然与人文科学做了较全面的总结。可以说，这是人\n类献给自己的一份厚重的礼物。\n全书分为\n!"\n册，共近\n#$$\n万字，囊括了人类曾经面对和正\n在面对的各种问题。藉此，崇尚科学的人们，特别是求知若渴的\n青少年，可以———\n一、认识自己。\n在古希腊，就有人提出“认识你自己”的口号。人是万物的\n灵长，人类在具有反思能力之初，就确立了其智者的地位。人自\n身是个小宇宙，在这个宇宙中，作为物质基础的生理机制和作为\n上层建筑的灵魂世界融合为一。人体·保健卷中，你将认识到作\n为生命一员的人体的奥秘；而艺术卷则向你揭示了人的精神世\n界；教育·生活卷介绍了关于成长的烦恼，将一一为您解答从幼\n儿到长大成人过程中的一系列问题。\n二、认识他人。\n你中有我，我中有你，他人是自我的延伸。人群（人类社会\n及其历史）是自我的一面面明镜，照荣辱、映兴衰。文史卷和旅\n游·民俗卷，讲述了人类的精神和行动的轨迹。\n·\n!\n·\n"\n##########\n前言', metadata={'source': 'why.pdf', 'page': 3}),

pdf attached: 
[why.pdf](https://github.com/langchain-ai/langchainjs/files/13931810/why.pdf)

**Comment by Macbook-Specter** [comment]
@zitongzhang098 Hello, I have also encountered the same problem at present, so I would like to ask, have you solved it?
