### ISSUE TITLE
How to return in a streaming fashion instead of returning a whole readable stream with chatBaiduWenxin model 

### ISSUE THREAD

**Issue by YL2014** [langchain-ai/langchainjs#4034]
When using Wenxin Yiyin, how to return in a streaming fashion instead of returning a whole readable stream.
My code is as follows, please take a look.

```javascript
import { ChatBaiduWenxin } from '@langchain/community/chat_models/baiduwenxin';
import { ChatPromptTemplate } from '@langchain/core/prompts';

const getErnie = (
  apiKey,
  secretKey
) => {
  return new ChatBaiduWenxin({
    modelName: 'ERNIE-Bot-4',
    temperature: 0.8,
    baiduApiKey: apiKey,
    baiduSecretKey: secretKey,
    streaming: true
  });
};

const prompt = ChatPromptTemplate.fromMessages([['user', '{input}']]);

const chatModel = getErnie(apiKey, secretKey);
const chain = prompt.pipe(chatModel);
const res = await chain.stream({ input: '你好，请介绍下你自己，用程序员风格' });

console.log(res)

for await (const chunk of chunks) {
    console.log('-----', JSON.stringify(chunk));
 }
```

then the log is follows

```
ReadableStream { locked: false, state: 'readable', supportsBYOB: false }

----- {"lc":1,"type":"constructor","id":["langchain_core","messages","AIMessage"],"kwargs":{"content":"你好，我是一款基于人工智能技术的语言模型，我的中文名是文心一言，英文名是ERNIE Bot，可以协助你完成范围广泛的任务并提供有关各种主题的信息，比如回答问题，提供定义和解释及建议。如果你有任何问题，请随时向我提问。","additional_kwargs":{}}}
```

please take a look.

**Comment by YL2014** [comment]
```
Property 'on' does not exist on type 'IterableReadableStream<BaseMessageChunk>'
```

when I use the `data` event. How can i fix it?

**Comment by anurag-pandey-007** [comment]
@YL2014 I also facing this same issue 
did you find solution for this ?

**Comment by movila** [comment]
I got similar error as `Property 'values' is missing in type 'IterableReadableStream<BaseMessageChunk>' but required in type 'ReadableStream<any>'`

**Comment by andrewnguonly** [comment]
Based on the implementation of `ChatBaiduWenxin`, it doesn't seem like streaming response chunks is implemented correctly.

1. The `_generate()` function is simply awaiting for a `ChatCompletionResponse`: https://github.com/langchain-ai/langchainjs/blob/main/libs/langchain-community/src/chat_models/baiduwenxin.ts#L343
2. All of the "streaming" logic is implemented in `completionWithRetry()`: https://github.com/langchain-ai/langchainjs/blob/main/libs/langchain-community/src/chat_models/baiduwenxin.ts#L460

I would expect an implementation similar to [`ChatOllama`](https://github.com/langchain-ai/langchainjs/blob/main/libs/langchain-community/src/chat_models/ollama.ts#L276) and [`ChatOpenAI`](https://github.com/langchain-ai/langchainjs/blob/main/libs/langchain-openai/src/chat_models.ts#L477) where the method `*_streamResponseChunks()` is implemented and yields `ChatGenerationChunk` instances.
