### ISSUE TITLE
How to pass custom retrieved vector embeddings to the chain.

### ISSUE THREAD

**Issue by mubashirjamali101** [langchain-ai/langchainjs#4038]
What I want?

I have retrieved vector embeddings through a custom query using the Langchain integration with Pinecone DB. How can I pass those embeddings to the chain, to ask quesitons from it. Instead of the built-in `{context}` variable template?

**Comment by mubashirjamali101** [comment]
@dosu-bot

Ok, I have got the documents in `results`, but, How do I pass it to the chain? I want to pass the actual embeddings (array of numbers) not text.

**Comment by jacoblee93** [comment]
If you want the raw vectors, you will need to call the `similaritySearchWithScore` method on the vectorstore class directly:

https://api.js.langchain.com/classes/langchain_vectorstores_base.VectorStore.html#similaritySearchWithScore

This returns an array of tuples where the first item in each tuple is a document and the second is the vector.

Can I ask why you'd want to do this?

**Comment by mubashirjamali101** [comment]
Thanks for the reply.

But I am not looking to get raw vectors, I already have raw factors somehow in the similar manner you just told.

What I want is how can I pass those raw vectors into the context of the langchain (chatgpt model).

I want to do this, because, I have a document, of which I want to pass all raw vectors to the langchain and summarize them.

**Comment by jacoblee93** [comment]
> I am not looking to get raw vectors

> What I want is how can I pass those raw vectors into the context of the langchain

This seems contradictory but perhaps this section of the quickstart will be helpful?

https://js.langchain.com/docs/get_started/quickstart#retrieval-chain
