### ISSUE TITLE
langchain-google-genai handling of "system messages/prompt/context" broken

### ISSUE THREAD

**Issue by suchitpuri** [langchain-ai/langchainjs#4055]
Hi Team, 

In the current implementation of google-genai whenever the library encounters a system messages which is carrying additional context or a system wide prompt, it is concatenated into the user part. 
https://github.com/langchain-ai/langchainjs/blob/9adb2731bff5f741301f3a721588c474f9d73027/libs/langchain-google-genai/src/utils.ts#L134

This is resulting in a request which has multiple user parts and is not interpreted by the Gemeni pro model 

e.g 
``` json
{
  "generationConfig": {
    "candidateCount": 1,
    "stopSequences": [],
    "temperature": 0.1,
    "topP": 1,
    "topK": 1
  },
  "safetySettings": [],
  "contents": [
    {
      "role": "user",
      "parts": [
        {
          "text": "<System Prompt>"
        },{
          "text": "User Prompt"
        }

      ]
    }
  ]
}
```

This is specifically happening when we are using the libary in a chain e.g RetrievalQAChain with a retriever like an implementation of a MemoryVectorStore which is using the GoogleGenerativeAIEmbeddings

ideally for this to work we need to send the system prompt as a separate part and also add a model response to it ( as the model expects alternating user and model responses ) like shown below

``` json 
{
  "generationConfig": {
    "candidateCount": 1,
    "stopSequences": [],
    "temperature": 0.1,
    "topP": 1,
    "topK": 1
  },
  "safetySettings": [],
  "contents": [
    {
      "role": "user",
      "parts": [
        {
          "text": "<System Prompt>"
        }
      ]
    },
    {
      "role": "model",
      "parts": [
        {
          "text": "Understood, I will use these rules to answer the subsequent questions""
        }
      ]
    },
    {
      "role": "user",
      "parts": [
        {
          "text": "<User Prompt>"
        }
      ]
    }
  ]
}
```

For this to work 

We will have to change the method `convertBaseMessagesToContent` https://github.com/langchain-ai/langchainjs/blob/9adb2731bff5f741301f3a721588c474f9d73027/libs/langchain-google-genai/src/utils.ts#L93

We might have to update the case

``` js
if (acc.mergeWithPreviousContent) {
            const prevContent = acc.content[acc.content.length - 1];
            if (!prevContent) {
                throw new Error("There was a problem parsing your system message. Please try a prompt without one.");
            }
            // prevContent.parts.push(...parts);
           // Since this will be called after the system prompt is added add a model prompt and dont concatenate the parts
            acc.content.push({role:"model", parts:[{"text": "Understood, I will use these rules to answer the subsequent questions"}]});
            acc.content.push({role:"user", parts:parts});
            return {
                mergeWithPreviousContent: false,
                content: acc.content,
            };
        }
```

or when a system prompt is detected we can insert a new user param and not concatenate it with the other user one and also add a model response in the end which Signals that them model should follow these rules.

**Comment by alx13** [comment]
Hey Suchit,

Concatenating messages is just a workaround because Gemini is not supporting system messages at the moment.

I don't think that inserting artificial model responses into prompt as base functionality is a good idea.

If you want to do it this way you can implement it in your code, i.e. not push any system messages.
