### ISSUE TITLE
type error for tools when using agents

### ISSUE THREAD

**Issue by KeenanFernandes2000** [langchain-ai/langchainjs#4073]
TypeError: Cannot read properties of undefined (reading 'bind')
    at createOpenAIFunctionsAgent (file:///C:/Users/Keenan/Desktop/Work/newLangchain/node_modules/langchain/dist/agents/openai_functions/index.js:224:30
)
    at file:///C:/Users/Keenan/Desktop/Work/newLangchain/index.js:58:21
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

How do I fix this error, is it possible to run agents without typescript

**Comment by KeenanFernandes2000** [comment]
import { config } from "dotenv";
config();
import {
  AgentExecutor,
  createOpenAIFunctionsAgent,
  createReactAgent,
  createStructuredChatAgent,
} from "langchain/agents";
import { ChatOpenAI } from "langchain/chat_models/openai";
import { DynamicTool, SerpAPI } from "langchain/tools";
import { pull } from "langchain/hub";

console.log("\n\n\n\n\n\n\n\n\n\n");

const model = new ChatOpenAI({
  modelName: "gpt-4",
  temperature: 0,
});

const tools = [
  new SerpAPI(process.env.SERPAI_KEY, {
    location: "Dubai,United Arab Emirates",
    hl: "en",
    gl: "us",
  }),
];
const prompt = await pull("hwchase17/react");
const agent = await createReactAgent({
  model,
  tools,
  prompt,
});
const executor = new AgentExecutor({
  agent,
  tools,
});

const result = await executor.invoke({
  input: "hi",
});

console.log(result);



this is my code, and I still get the same error what can i do to get it to work

**Comment by MRanjith26** [comment]
this is my test agent do we need prompt for running

`import { ChatOpenAI } from "@langchain/openai";
import { AgentExecutor, createOpenAIToolsAgent } from "langchain/agents";
import dotenv from "dotenv";

dotenv.config();

const llm = new ChatOpenAI({
  modelName: "gpt-4",
  temperature: 0,
  openAIApiKey: process.env.OPENAI_API_KEY,
});

async function testAgent() {
  const tools = [];

  const agent = await createOpenAIToolsAgent({
    llm,
    tools,
  });

  const executor = new AgentExecutor({
    agent,
    tools,
    verbose: true,
  });

  const result = await executor.invoke({ input: "test" });
  console.log(result);
}

testAgent();
`
