### ISSUE TITLE
when tool_calls returns multiple tools, they are not called sequentially

### ISSUE THREAD

**Issue by tutuxxx** [langchain-ai/langchainjs#4075]
```javascript
const tools = [new SerpAPI(), new Calculator()]

const model = new ChatOpenAI({
  temperature: 0,
  maxTokens: 1000,
})

 const agent = await createOpenAIToolsAgent({
    llm: model,
    tools,
    prompt,
  });

  const agentExecutor = new AgentExecutor({
    agent,
    tools,
    // verbose: true
  });

agentExecutor.invoke(
      {
        input: 'What's the temperature in New York tomorrow plus 100?'
      })

```

openai api return:

![image](https://github.com/langchain-ai/langchainjs/assets/14323022/1958127e-7261-4cff-9253-72b7e8713d9f)

The expectation is that you can wait for the search tool to finish executing, and then execute the next tool after you get the search results, but in reality both tools will execute at the same time, and the problem seems to be: https://github.com/langchain-ai/langchainjs/blob/main/langchain/src/agents/executor.ts#L504

**Comment by jacoblee93** [comment]
This is the correct behavior - the intention is they are called in parallel:

https://platform.openai.com/docs/guides/function-calling

**Comment by tutuxxx** [comment]
> This is the correct behavior - the intention is they are called in parallel:
> 
> https://platform.openai.com/docs/guides/function-calling

Thank you, how to realize the above scenario which requires serial calls, do you have a relevant solution?
