### ISSUE TITLE
[ERROR] Could not resolve "@langchain/core/utils/function_calling"

### ISSUE THREAD

**Issue by stevenmilstein** [langchain-ai/langchainjs#4082]
After upgrading to v.0.1.4, I received the following error when running my build on Netlfy, which uses node v18.19.0 (npm v10.2.3).

```
11:02:24 PM: ✘ [ERROR] Could not resolve "@langchain/core/utils/function_calling"
11:02:24 PM:     node_modules/@langchain/openai/dist/chat_models.js:6:36:
11:02:24 PM:       6 │ ...onvertToOpenAITool } from "@langchain/core/utils/function_calling";
11:02:24 PM:         ╵                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
11:02:24 PM:   The path "./utils/function_calling" is not exported by package "@langchain/core":
11:02:24 PM:     node_modules/@langchain/core/package.json:86:13:
11:02:24 PM:       86 │   "exports": {
11:02:24 PM:          ╵              ^
11:02:24 PM:   You can mark the path "@langchain/core/utils/function_calling" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.
11:02:24 PM: ✘ [ERROR] Could not resolve "@langchain/core/utils/function_calling"
11:02:24 PM:     node_modules/@langchain/openai/dist/chat_models.js:6:36:
11:02:24 PM:       6 │ ...onvertToOpenAITool } from "@langchain/core/utils/function_calling";
11:02:24 PM:         ╵                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
11:02:24 PM:   The path "./utils/function_calling" is not exported by package "@langchain/core":
11:02:24 PM:     node_modules/@langchain/core/package.json:86:13:
11:02:24 PM:       86 │   "exports": {
11:02:24 PM:          ╵              ^
11:02:24 PM:   You can mark the path "@langchain/core/utils/function_calling" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.
11:02:24 PM: ✘ [ERROR] Could not resolve "@langchain/core/utils/function_calling"
11:02:24 PM:     node_modules/@langchain/openai/dist/utils/openai.js:3:62:
11:02:24 PM:       3 │ ...nvertToOpenAITool, } from "@langchain/core/utils/function_calling";
11:02:24 PM:         ╵                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
11:02:24 PM:   The path "./utils/function_calling" is not exported by package "@langchain/core":
11:02:24 PM:     node_modules/@langchain/core/package.json:86:13:
11:02:24 PM:       86 │   "exports": {
11:02:24 PM:          ╵              ^
11:02:24 PM:   You can mark the path "@langchain/core/utils/function_calling" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.
11:02:24 PM: ✘ [ERROR] Could not resolve "@langchain/core/utils/function_calling"
11:02:24 PM:     node_modules/@langchain/openai/dist/utils/openai.js:3:62:
11:02:24 PM:       3 │ ...nvertToOpenAITool, } from "@langchain/core/utils/function_calling";
11:02:24 PM:         ╵                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
11:02:24 PM:   The path "./utils/function_calling" is not exported by package "@langchain/core":
11:02:24 PM:     node_modules/@langchain/core/package.json:86:13:
11:02:24 PM:       86 │   "exports": {
11:02:24 PM:          ╵              ^
11:02:24 PM:   You can mark the path "@langchain/core/utils/function_calling" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.
```

I had similar errors when I upgraded to 0.1.x but could resolve them by finding the missing export (`convertToOpenAITool`) and replacing the import path. However, in this case, I'm not using `convertToOpenAITool.` 

I have the following versions installed:
- @langchain/community 0.0.18
- @langchain/core 0.1.5
- @langchain/openai 0.0.12

My package.json contains:
 "dependencies": {
    "@langchain/openai": "^0.0.12",
    "langchain": "^0.1.4",
     ...
  },
  "overrides": {
    "@langchain/core": "0.1.5"
  },

My local build works.

Any help would be greatly appreciated.

**Comment by jacoblee93** [comment]
Can you bump `@langchain/core` to the latest as well (`0.1.16`)?

Overrides are definitely a bit clunky...

**Comment by stevenmilstein** [comment]
I upgraded @langchain/core to  0.1.16, removed the `overrides` section from package.json and no longer see those errors.

[Is there a tool to help migrate to @langchain/core and @langhchain/community?](https://github.com/langchain-ai/langchain/discussions/15712#discussioncomment-8136347)

Thank you for the very timely  & helpful response!

**Comment by jacoblee93** [comment]
No, but there ought to be... Would make things like this easier.

Also, do you have any better suggestions for how to manage these overrides? I think I got a bit paranoid because I personally ran into issues where different packages ended up with different incompatible versions of core. I've worked to mitigate version compatibility a bit but it's still a work in progress.

**Comment by stevenmilstein** [comment]
@jacoblee93 Sorry, but my skillset prevents me from making any suggestions :-(

I can tell you that I had trouble upgrading and asked ChatGPT for help.

>how do i resolve :
npm ERR! code EOVERRIDE
npm ERR! Override for @langchain/core@^0.1.16 conflicts with direct dependency
>
>ChatGPT
The error message you're encountering, npm ERR! code EOVERRIDE, typically occurs when there's a conflict between an overridden package version and a direct dependency version in your project's package.json or when using npm install --legacy-peer-deps.
>
>Here's how you can resolve this issue:
>
>Remove the Override: If you have an override specified in your package.json for @langchain/core, you should consider removing it. Overriding package versions can lead to conflicts like the one you're encountering. Look for a section in your package.json that resembles this:
> ...

That's when I removed the overrides section.

I hope that helps a little bit & I anxiously wait for a migration tool that can, at the very least, list what I need to search for.

Thank you for your time!

**Comment by phpmac** [comment]
Same experience
