### ISSUE TITLE
How to combine String Output Parser and JSON Output Functions Parser into one stream pipline?

### ISSUE THREAD

**Issue by arvinxx** [langchain-ai/langchainjs#4095]
By using the default stream mode:

```ts
const langChainMessages = mapToLangChainMessages(messages);

const http = new HttpResponseOutputParser();

const stream = await model.pipe(http).stream(langChainMessages);

return new Response(stream);
```

it works well with default user content:

<img width="696" alt="image" src="https://github.com/langchain-ai/langchainjs/assets/28616219/ea51ec71-a957-4c7c-8a7e-d760bf96492c">

But when user try to call with OpenAI Function Call, the result is empty:

<img width="692" alt="image" src="https://github.com/langchain-ai/langchainjs/assets/28616219/b3d6e1b5-3070-4234-94ec-3e262af1c34a">

and I try to trace it in the LangSmith ([trace link](https://smith.langchain.com/public/1bf9b446-93d7-407a-b88f-0aafbc3a6359/r)):

<img width="969" alt="image" src="https://github.com/langchain-ai/langchainjs/assets/28616219/3d802155-63e4-4aea-8d6e-0a20d087f836">

we can see that the ai is responsing correct with tool_calls. But the `HttpResponseOutputParser` is result with empty output.

<img width="1003" alt="image" src="https://github.com/langchain-ai/langchainjs/assets/28616219/38684d6d-afd4-4832-9b44-6f56c28a5979">

And I have also try with implement like below:

```ts
const stream = await model
  .pipe(new StringOutputParser())
  .pipe(new JsonOutputFunctionsParser({ diff: true }))
  .stream(langChainMessages);
```

But it aslo not working. Here is the trace link: https://smith.langchain.com/public/971acb7b-1550-4377-aeb0-70e630d16c62/r

I think the `HttpResponseOutputParser` should support to parse both string content and function call, otherwise we can't use it in the real product.

**Comment by arvinxx** [comment]
@dosubot no, it's not useful. and I think is a bug

**Comment by arvinxx** [comment]
@jacoblee93  For your inference, the `ai` SDK support to streaming the function call result with pure string: https://sdk.vercel.ai/docs/guides/providers/openai-functions#recursive-function-calls

**Comment by jacoblee93** [comment]
Hey! Does the example on this page work for you?

https://js.langchain.com/docs/modules/model_io/output_parsers/types/http_response

**Comment by arvinxx** [comment]
@jacoblee93 I try with code below, it's not useful.

```ts
const http = new HttpResponseOutputParser({
  contentType: 'text/event-stream',
  outputParser: new JsonOutputFunctionsParser({ diff: true }),
});

const stream = await model.pipe(http).stream(langChainMessages);

return new Response(stream);
```

the default output is:

<img width="456" alt="image" src="https://github.com/langchain-ai/langchainjs/assets/28616219/5be84ed6-e671-4099-9076-76b96763a325">

my scene need two ability:

1. if assistant message is pure text output , response with text.
2. if assistant message is a function call result, also response it by pure text.

and the paser should combine both strategies.

**Comment by jacoblee93** [comment]
I see - you could define your own custom output parser by extending the base class:

https://github.com/langchain-ai/langchainjs/blob/main/langchain-core/src/output_parsers/string.ts#L21
https://github.com/langchain-ai/langchainjs/blob/main/langchain-core/src/output_parsers/transform.ts#L19

 but I can also see if we can make one that makes sense in the next few days!

**Comment by arvinxx** [comment]
I think an offical parser is a must  Because `default text response + function call response` is becoming more worldwide usage case when the community is exploring more potential of LLM other than only chat completion.

**Comment by arvinxx** [comment]
@jacoblee93 Hi, is this issue any update?

**Comment by jacoblee93** [comment]
Hey, not yet :( have been slammed but will try to get to it as soon as I can!

**Comment by arvinxx** [comment]
@jacoblee93 Thanks for your great work. I have blocked by this for about a week...

Actually I have try to write a custom output parser but failed to run as my expect.

There is few document about how to write the custom output parser (I don't know the process of methods like `parseResult` / `parse` / `parsePartialResult`), and the official parsers seem not good examples to follow...

**Comment by limcolin** [comment]
> Hey! Does something like the last example on this page work for you?
> 
> You can pass an internal parser to the `HttpResponseOutputParser`.
> 
> https://js.langchain.com/docs/modules/model_io/output_parsers/types/http_response
> 
> Let me know if it doesn't and we can figure something out. Thanks for all the feedback so far!

Can confirm that this works - specifically:
> Or pass a custom output parser to internally parse chunks for e.g. streaming function outputs:

`import { ChatOpenAI } from "@langchain/openai";
import {
  HttpResponseOutputParser,
  JsonOutputFunctionsParser,
} from "langchain/output_parsers";

const handler = async () => {
  const parser = new HttpResponseOutputParser({
    contentType: "text/event-stream",
    outputParser: new JsonOutputFunctionsParser({ diff: true }),
  });

  const model = new ChatOpenAI({ temperature: 0 }).bind({
    functions: [
      {
        name: "get_current_weather",
        description: "Get the current weather in a given location",
        parameters: {
          type: "object",
          properties: {
            location: {
              type: "string",
              description: "The city and state, e.g. San Francisco, CA",
            },
            unit: { type: "string", enum: ["celsius", "fahrenheit"] },
          },
          required: ["location"],
        },
      },
    ],
    // You can set the `function_call` arg to force the model to use a function
    function_call: {
      name: "get_current_weather",
    },
  });

  const stream = await model.pipe(parser).stream("Hello there!");

  const httpResponse = new Response(stream, {
    headers: {
      "Content-Type": "text/event-stream",
    },
  });

  return httpResponse;
};

await handler();`

https://js.langchain.com/docs/modules/model_io/output_parsers/types/http_response

Been racking my brain trying to get this to work for months now.

Thanks for your work @jacoblee93
