### ISSUE TITLE
Usage of SelfQueryRetriever with a Score threshold

### ISSUE THREAD

**Issue by ladrians** [langchain-ai/langchainjs#4104]
I need to use the `SelfQueryRetriever` with a Score threshold value.
Tried to implement a `ContextualCompressionRetriever` using `EmbeddingsFilter` like this

```typescript
        const baseCompressor = new EmbeddingsFilter({
          embeddings: getEmbedding(options?.embeddings),
          similarityThreshold: minScoreThreshold,
        });
        retriever = new ContextualCompressionRetriever({
          baseCompressor,
          baseRetriever: retriever,
        });

```

where `retriever` is a SelfQueryRetriever.

I could validate the `SelfQueryRetriever` is executed getting the filters and rephrasing the query, but the `ContextualCompressionRetriever` is not using the new query specified and should use the same filters, I could confirm the mismatch here in `ContextualCompressionRetriever` _getRelevantDocuments; query is the original one and does not take into account the changes.

```typescript
    async _getRelevantDocuments(query, runManager) {
        const docs = await this.baseRetriever.getRelevantDocuments(query, runManager?.getChild("base_retriever"));
        const compressedDocs = await this.baseCompressor.compressDocuments(docs, query, runManager?.getChild("base_compressor"));
        return compressedDocs;
    }

```

**Comment by jacoblee93** [comment]
So you basically want to filter by similarity to the intermediate value generated by `SelfQueryRetriever`?

**Comment by ladrians** [comment]
Yes, based on the new query generated by the `SelfQueryRetriever` with filters I would like to use a score threshold on it.
