### ISSUE TITLE
Any plan to support SharePoint source ?

### ISSUE THREAD

**Issue by aalev** [langchain-ai/langchainjs#4105]
hello,
thanks again for your work !
any plan to support SharePointLoader (https://python.langchain.com/docs/integrations/document_loaders/microsoft_sharepoint) ?

**Comment by TimSusa** [comment]
please support a sharepoint loader!

**Comment by Krishna-Chaurasia** [comment]
Please build a native SharePointLoader for LangChain JavaScript that uses the Graph API or anything to load files like PDFs, TXT, DOCX, and Excel, etc.. into standard LangChain Documents. This feature is already provided in the Python version (langchain_community), and having it in JavaScript would greatly help full-stack teams.
