### ISSUE TITLE
Feature request: support for UnstructuredExcelLoader

### ISSUE THREAD

**Issue by aalev** [langchain-ai/langchainjs#4106]
Hello,
thanks again for your great work !
Do you plan to add support for UnstructuredExcelLoader (https://python.langchain.com/docs/integrations/document_loaders/microsoft_excel)

**Comment by ali-faiz-brainx** [comment]
Any update on the xls loader?

**Comment by HazardCodeBolt** [comment]
I would like to have it too

**Comment by ronnyroeller** [comment]
This would be very helpful!
