### ISSUE TITLE
Is there a way to manually limit context window size? How to get token size stored inside memory?

### ISSUE THREAD

**Issue by AdiletBekmuratov** [langchain-ai/langchainjs#4109]
Hello, everyone! I want to manually limit the context window size for GPT models. For instance, the last GPT-4 model has 128K tokens, but I want to limit it to 32K. Is there any way to do so? How can we get token size stored inside memory?

Code example:
```typescript
  const memory = new BufferMemory({
    returnMessages: true,
    chatHistory: new RedisChatMessageHistory({
      sessionId: dto.sessionId,
      url: this.config.get('REDIS_URL'),
    }),
  });
  
  ...
  
  const chain = new ConversationChain({
  prompt: ChatPromptTemplate.fromMessages(messages),
  llm: langchain,
  memory,
});
      
```

packages versions:
"@langchain/community": "^0.0.18"
"@langchain/core": "^0.1.16"
"@langchain/openai": "^0.0.12"
"langchain": "^0.1.4",

**Comment by Yiannis128** [comment]
> _🤖_
> 
> To manually limit the context window size for GPT models to 32K, you can modify the `getModelContextSize` function in the `langchain-core/src/language_models/base.ts` file. This function determines the context size for different models. You can add a condition to limit the context size to 32K for the models you are interested in. Here's how you can do it:
> 
> ```ts
> export const getModelContextSize = (modelName: string): number => {
>   switch (getModelNameForTiktoken(modelName)) {
>     case "gpt-3.5-turbo-16k":
>       return 16384;
>     case "gpt-3.5-turbo":
>       return 4096;
>     case "gpt-4-32k":
>       return 32768; // This is already set to 32K
>     case "gpt-4":
>       return 8192;
>     // Add your model here and set the context size to 32K
>     case "your-model-name":
>       return 32768;
>     default:
>       return 4097;
>   }
> };
> ```
> 
> To determine the token size stored in memory, you can use the `getNumTokens` method of the `BaseLanguageModel` class. This method calculates the number of tokens in a given content. Here's how you can use it:
> 
> ```ts
> const model = new YourModelClass({ ...params });
> const content = "Your content here";
> const numTokens = await model.getNumTokens(content);
> console.log(`Number of tokens in memory: ${numTokens}`);
> ```
> 
> Please replace `YourModelClass` with the actual class of your model and `...params` with the actual parameters for your model. Replace `"Your content here"` with the actual content you want to calculate the token size for.
> 
> You can find more details in the [langchain-core/src/language_models/base.ts](https://github.com/langchain-ai/langchainjs/blob/main/langchain-core/src/language_models/base.ts) file.
> 
> Please note that modifying the `getModelContextSize` function will affect all instances where this function is used. If you want to limit the context size only for specific instances, you might need to create a new function or add a parameter to the existing function to specify the context size.
> 
> I hope this helps! If you have any other questions, feel free to ask.
> ## Sources
> 
>     * [langchain-core/src/language_models/base.ts](https://github.com/langchain-ai/langchainjs/blob/main/langchain-core/src/language_models/base.ts)
> 
>     * [langchain-core/src/language_models/tests/count_tokens.test.ts](https://github.com/langchain-ai/langchainjs/blob/main/langchain-core/src/language_models/tests/count_tokens.test.ts)
> 
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

This has really helped me! Aside from the OpenAI callback method, this method works really well!

**Comment by AdiletBekmuratov** [comment]
For the Anthropic and Mistral `getNumTokens` method gives such warning: `Failed to calculate number of tokens, falling back to approximate count Error: Unknown model`.
