### ISSUE TITLE
Bug: ChatGoogleGenerativeAI: Garbled Characters in Chinese Outputs

### ISSUE THREAD

**Issue by danny-avila** [langchain-ai/langchainjs#4113]
### What happened?

When using Chinese dialogue, and using the streaming method, some content is displayed as garbled characters, as shown below.

### Steps to Reproduce

This is the prompt I used:

> You are a helpful assistant. 你是一個樂於助人的助手。請你提供專業、有邏輯、內容真實、有價值的詳細回答，並以繁體中文台灣用語回覆。
> 
> 太陽能板是誰發明的

### Relevant Output

I get a result like this:

> 宫保鸡丁是一道著名的川菜，起源于清朝山东巡抚丁宝桢的家厨，以花生、黄瓜、胡萝卜、������、���丝等配料，再佐以干辣椒、花椒等调味料炒制而成。

**The text contains ���**

### Resolution

This issue may have been fixed by Google in the latest `@google/generative-ai` package, but not on `0.1.0`, which `@langchain/google-genai` is using: https://github.com/google/generative-ai-js/issues/35

A simple dependency update may resolve the issue.

### Code to Reproduce

```js
const { ChatGoogleGenerativeAI } = require('@langchain/google-genai');

// Text
const model = new ChatGoogleGenerativeAI({
  apiKey: process.env.GOOGLE_KEY,
  modelName: 'gemini-pro',
  maxOutputTokens: 2048,
});

// Batch and stream are also supported
(async () => {
  const res = await model.stream([
    [
      'human',
      `You are a helpful assistant. 你是一個樂於助人的助手。請你提供專業、有邏輯、內容真實、有價值的詳細回答，並以繁體中文台灣用語回覆。

    太陽能板是誰發明的`,
    ],
  ]);

  let reply = '';
  for await (const chunk of res) {
    reply += chunk.content;
  }

  console.log(reply);
})();

/*
太陽能板是許多人努力的成果，而不是由單一個人發明的���以下是一些在太陽能板發展中做出重大貢獻的人員與事件：

* 1839 年：法國物理學家���������爾 (Alexandre-Edmond Becquerel) 發現了光電效應，即光照射某些材料時會產生電流。
* 1873 年：英國工程師史密斯 ( Willoughby Smith) 製造了第一個太陽能電池，但效率極低。
* 1883 年：美國發明家查爾斯·弗里茨 (Charles Fritts) 製作了第一個使用硒半導體的太陽能電池，效率略高於史密斯的電池。
* 1904 年：愛因斯坦解釋了光電效應，這為太陽能電池的進一步發展奠定了理論基礎。
* 1918 年：波蘭物理學家揚·茨維利奇 (Jan Czochralski) 發明了茨維利奇法，這是一種生長單晶矽的方法，為現代太陽能電池的生產奠定了基礎。
* 1941 年：美國物理學家羅素·奧爾 (Russell Ohl) 發明了第一個現代太陽能電池，它使用矽半導體，效率約為 1%。
* 1954 年：美國貝爾實驗室的科學家達里爾·查平 (Daryl Chapin)、卡爾文·薩瑟蘭 (Calvin Souther) 和傑拉爾德·皮爾遜 (Gerald Pearson) 研製出第一個具有實用價值的太陽能電池，效率約為 6%。
* 1958 年：美國太空總署 (NASA) 開始使用太陽能電池為衛星供電。
* 1970 年代：石油危機導致對可再生能源的興趣激增，太陽能電池開始商業化生產。
* 1980 年代：太陽能電池的效率繼續提高，成本降低，開始在住宅和商業應用中使用。
* 21 世紀：太陽能電池的發展迅速，效率和成本都有了顯著提高，成為一種重要的可再生能源。

因此，太陽能板的發明並不是由單一個人���成的，而是許多科學家、工程師和企業共同努力的成果。
*/
```

### Screenshots

![11223dd33](https://github.com/danny-avila/LibreChat/assets/25527875/a19e5c3f-dbab-4b9f-ae00-66c6e6414f55)
![1122333](https://github.com/danny-avila/LibreChat/assets/25527875/61d2e817-de4c-467b-a99b-f94b1dcbe5bb)

**Comment by danny-avila** [comment]
@alx13 hopefully you can help!

**Comment by danny-avila** [comment]
@jacoblee93 I'm sure this can be fixed by bumping `@google/generative-ai` to latest, but not sure how. Any guidance so I can maybe open the PR myself?

**Comment by jacoblee93** [comment]
Hey thanks for flagging this!

You can clone the repo and go into `libs/langchain-google-genai/package.json`, update the SDK version there, then run `yarn` to update the lockfile. Then I will cut a release.

I can do this as well if you don't have time!

**Comment by danny-avila** [comment]
> Hey thanks for flagging this!
> 
> You can clone the repo and go into `libs/langchain-google-genai/package.json`, update the SDK version there, then run `yarn` to update the lockfile. Then I will cut a release.
> 
> I can do this as well if you don't have time!

Please feel free. I don't use yarn so there may be a bit of setup for me to do this

**Comment by jacoblee93** [comment]
Opened a PR but also the semver is locked to patch - you should be able to upgrade the SDK without this new PR.
