### ISSUE TITLE
How to use `FirestoreChatMessageHistory` to load memory from Firestore?

### ISSUE THREAD

**Issue by TowhidKashem** [langchain-ai/langchainjs#4114]
Hi,

I'm having trouble understanding what to use when instantiating the `FirestoreChatMessageHistory` class, according to the types this is the shape of the config object:

```
export interface FirestoreDBChatMessageHistory {
    collectionName: string;
    sessionId: string;
    userId: string;
    appIdx?: number;
    config?: AppOptions;
}
```

My firestore structure looks like this:

`chats -> [userId] -> bots -> [botId] -> messages -> [messageId] -> fields`

so does this mean I should use `chats/${USER_ID}/bots/${BOT_ID}/messages` for the `collectionName`?

and what exactly should I use for `sessionId` and `userId`? I'm trying to use this from an admin panel which has Firebase Admin SDK installed. So the user that I am is the master admin user. I'm not sure if I should be using my admin id or the user's id from whose collection I am trying to read messages?

also what do I need to pass for the config, where do I get that value? I was able to authenticate fine like this:

```
import admin from 'firebase-admin';
import { initializeApp } from 'firebase-admin/app';
import { getAuth } from 'firebase-admin/auth';
import { getFirestore } from 'firebase-admin/firestore';

const serviceAccountKey = require('./service-account-key.json');

if (admin.apps.length === 0) {
  initializeApp({
    projectId: process.env.FIREBASE_PROJECT_ID,
    credential: admin.credential.cert(serviceAccountKey)
  });
}

const auth = getAuth();
const firestore = getFirestore();
```

But what do I pass to `config`? Thanks for any help!

**Comment by bracesproul** [comment]
Hey @TowhidKashem I'm going to investigate this now, I should have an answer & better documentation up in a couple hours! I'll ping you once it's all in.

**Comment by bracesproul** [comment]
@TowhidKashem I just took a quick look, and it appears that the current implementation doesn't support nested collections, or dynamic collection names like in your case. I'll have a PR up today adding support for that, but it likely won't be released until tomorrow or the next day.

**Comment by bracesproul** [comment]
@TowhidKashem I've added the fix here #4122 and once this releases the docs will be updated to show examples for how you can achieve what you outlined in this issue.

**Comment by TowhidKashem** [comment]
@bracesproul thanks so much for the quick turnaround! I'll be happy to pull the changes and test when they're merged. Will update, thanks!

**Comment by bracesproul** [comment]
@TowhidKashem `@langchain/community` `v0.0.20` has been released with these fixes! See the new docs [here](https://js.langchain.com/docs/integrations/chat_memory/firestore) (might not be updated for a few min)
