### ISSUE TITLE
createRetrieverTool for chatting with my docs

### ISSUE THREAD

**Issue by KeenanFernandes2000** [langchain-ai/langchainjs#4130]
For the previous version of langchain I was able to use createRetrieverTool from langchain/agents/toolkits, however now that I updated langchain to 0.1.0 it shows that its deprecated. But on the documentation it still shows to use createRetrieverTool, so how can I build a Chat with my pdf using langchain?

**Comment by corintho** [comment]
I see that now there is a "createRetrieverTool" available from:  "langchain/tools/retriever"

**Comment by KeenanFernandes2000** [comment]
@corintho yeah I just tried that and it worked, regardless I already implemented another way of chatting with your docments without the retriever tool

**Comment by KeenanFernandes2000** [comment]
const model = new ChatOpenAI({ modelName: "gpt-4", temperature: 0 });
    const loader = new PDFLoader("path/to/file.pdf");
    const docs = await loader.load();
    const splitter = new RecursiveCharacterTextSplitter({
      chunkSize: 1000,
      chunkOverlap: 0,
    });

    const texts = await splitter.splitDocuments(docs);

    const vectorStore = await FaissStore.fromDocuments(
      texts,
      new OpenAIEmbeddings()
    );

    const retriever = vectorStore.asRetriever();

    const SYSTEM_TEMPLATE = `Use the following pieces of context to answer the question at the end. If you don't know the answer, just say that you don't know, don't try to make up an answer.
    ----------------
    {context}`;

    const messages = [
      SystemMessagePromptTemplate.fromTemplate(SYSTEM_TEMPLATE),
      HumanMessagePromptTemplate.fromTemplate("{question}"),
    ];

    const prompt = ChatPromptTemplate.fromMessages(messages);

    const chain = RunnableSequence.from([
      {
        context: retriever.pipe(formatDocumentsAsString),
        question: new RunnablePassthrough(),
      },
      prompt,
      model,
      new StringOutputParser(),
    ]);

    const result = await chain.invoke(msg);
