### ISSUE TITLE
Latency in AgentExecutor

### ISSUE THREAD

**Issue by humbertaco** [langchain-ai/langchainjs#4142]
Hi there! 

Recently, I started using LangSmith to better understand how my LangChain code works.

In the past days, I have been paying attention to the latency that the users of my system are experiencing, as it seems to be too high. By inspecting some traces in LangSmith, I noticed that much of the time is spent in _side_ tasks. Hereby an example:

![image](https://github.com/langchain-ai/langchainjs/assets/6461554/b2a1fa52-fa6e-4c9f-afd3-a18c4351fcaa)

In this trace, I see that the three steps marked with the red box took, in total, **10.67 seconds**. These steps correspond with the model deciding what tool to use, the execution of the tool and the model generating the final answer. However, the **total trace time is 16.34 seconds**, that is 53% higher than the expected time. By the way, the total time of the AgentExecutor does not match the individual times of each step, not sure why. 
By reviewing the rest of the trace, I can see that the 5.67 seconds difference with respect to the total must be due to other side tasks such as RunnableMaps, Prompts and Parsing. 

Are these normal execution times? Am I misreading these numbers? Is there any way in which I can improve the total time to get as close as possible to the 10.67 seconds mark?

Some complementary information:

I am using langchain 0.1.11, node 18.13.0 and GPT4-1106. I stream the final answer to my users, so they get a response as soon as the model starts generating it.

Thanks in advance!

**Comment by humbertaco** [comment]
The previous reply does not seem to address my issue.

- **Max concurrency** would be helpful to parallelize requests to OpenAI, but those _side_ tasks that I mentioned earlier would still take part of the whole time.
- **Optimizing documents** would be useful, indeed, but it does not address the problem that I posed. The trace that I attached in my first message does not use documents. The only thing that resembles of documents would be the prompt that the tool is returning. In any case, I understand that this would mainly affect the processing of my request to OpenAI. And yet, OpenAI says this in a post on how to [address latencies](https://platform.openai.com/docs/guides/production-best-practices/improving-latencies): 
> Intuition: Prompt tokens add very little latency to completion calls. Time to generate completion tokens is much longer, as tokens are generated one at a time. Longer generation lengths will accumulate latency due to generation required for each token.
- Using a **more powerful machine** would definitively improve the execution time. However, I am running my experiments on a M2 Pro chip, which I think is powerful enough.

**Comment by jacoblee93** [comment]
We block on callback execution by default to allow trace requests finishing serverless environments - you may find this helpful if that does not apply to you or you would prefer to just get the fastest possible output:

https://js.langchain.com/docs/modules/callbacks/how_to/background_callbacks

I know the LangSmith team is working hard to keep latency low in the future as well 👍
