### ISSUE TITLE
Error in chat route: BadRequestError: 400 Invalid value for 'content': expected a string, got null.

### ISSUE THREAD

**Issue by RedouanAssakali** [langchain-ai/langchainjs#4153]
Error in chat route: BadRequestError: 400 Invalid value for 'content': expected a string, got null.
    at APIError.generate (/Users/redouanassakali/Desktop/ahadai/backend/node_modules/openai/error.js:44:20)
    at OpenAI.makeStatusError (/Users/redouanassakali/Desktop/ahadai/backend/node_modules/openai/core.js:255:33)
    at OpenAI.makeRequest (/Users/redouanassakali/Desktop/ahadai/backend/node_modules/openai/core.js:297:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/redouanassakali/Desktop/ahadai/backend/node_modules/@langchain/openai/dist/chat_models.cjs:650:29
    at async RetryOperation._fn (/Users/redouanassakali/Desktop/ahadai/backend/node_modules/p-retry/index.js:50:12) {
  status: 400,

makechain.js: 
nst { OpenAI } = require('langchain/llms/openai');
const { PineconeStore } = require('langchain/vectorstores/pinecone');
const { ConversationalRetrievalQAChain } = require('langchain/chains');
const { BufferMemory } = require('langchain/memory'); // Import BufferMemory
const { FirestoreChatMessageHistory } = require('langchain/stores/message/firestore'); // Import FirestoreChatMessageHistory
const { PromptTemplate } = require("langchain/prompts");
const admin = require("firebase-admin");
const {ChatOpenAI} = require("@langchain/openai");
const path = require('path');
const dotenv = require('dotenv').config({path: path.resolve(__dirname, '../.env')})
const CONDENSE_PROMPT = `Given the following conversation and a follow up question, rephrase the follow up question to be a standalone question.

Chat History:
{chat_history}
Follow Up Input: {question}
Standalone question:

`;

const QA_PROMPT = `You are {author}. Use the following pieces of context to answer the question at the end.

{context}
Question: {question}
Helpful answer ALWAYS output in markdown!!!

`;

const makeChain = (vectorstore, sessionId, uid, chatbot) => {

    const firestoreConfig = {
        collectionName: "chathistory",
        sessionId: sessionId,
        userId: uid,
        config: { projectId: "unity-352c6" },
    };

    // Initialize the FirestoreChatMessageHistory for chat history
    // Here a new sub collection for messages was made
    const chatHistory = new FirestoreChatMessageHistory(firestoreConfig);

    console.log("chatHistory", chatHistory)
    // Create a BufferMemory instance with FirestoreChatMessageHistory
    const memory = new BufferMemory({
        chatHistory,
        memoryKey: "chat_history",
        inputKey: "question",
        outputKey: "text",
    });

    console.log("memory", memory);

    const model = new ChatOpenAI({
        temperature: 0.5,
        modelName: chatbot.activeModel,
        openAIApiKey: process.env.OPENAI_API_KEY

    });

    return ConversationalRetrievalQAChain.fromLLM(
        model,
        vectorstore.asRetriever(),
        {
            qaTemplate: QA_PROMPT.replace('{author}', chatbot.name),
            questionGeneratorTemplate: CONDENSE_PROMPT,
            returnSourceDocuments: true,
            memory,
        },
    );
};

module.exports = { makeChain };

agent.js:
const {OpenAI} = require('langchain/llms/openai');
const {initializeAgentExecutorWithOptions} = require('langchain/agents');

const {PineconeStore} = require('langchain/vectorstores/pinecone');
const {OpenAIEmbeddings} = require('langchain/embeddings/openai');
const admin = require("firebase-admin");
const {Pinecone} = require('@pinecone-database/pinecone');

const {BufferMemory, ChatMessageHistory} = require('langchain/memory'); // Import BufferMemory
const {FirestoreChatMessageHistory} = require('langchain/stores/message/firestore'); // Import FirestoreChatMessageHistory
const {PromptTemplate} = require("langchain/prompts");

const {ChainTool} = require("langchain/tools");
const {ConversationalRetrievalQAChain} = require('langchain/chains');
const {response} = require("express");
const {ChatOpenAI} = require("@langchain/openai");
const {makeChain} = require("./makechain");
const {MessagesPlaceholder} = require("@langchain/core/prompts");
const {OpenAIAgentTokenBufferMemory} = require("langchain/agents/toolkits");
const path = require('path');
const dotenv = require('dotenv').config({path: path.resolve(__dirname, '../.env')})

const runChatbot = async (vectorStore, sessionId, uid, chatbotData) => {

    const model = new ChatOpenAI({
        temperature: 0.5,
        modelName: chatbotData.activeModel,
        openAIApiKey: process.env.OPENAI_API_KEY

    });

    const firestoreConfig = {
        collectionName: "chathistory",
        sessionId: sessionId,
        userId: uid,
        config: {projectId: "unity-352c6"},
    };

    // Initialize the FirestoreChatMessageHistory for chat history
    // Here a new sub collection for messages was made
    const chatHistory = new FirestoreChatMessageHistory(firestoreConfig);

    const memory = new OpenAIAgentTokenBufferMemory({
        llm: model,
        chatHistory: chatHistory,
        memoryKey: 'chat_history',
        outputKey: 'output',
        inputKey: 'input'
    })
    // Create a conversational chain
    const retrievalChain = makeChain(vectorStore, sessionId, uid, chatbotData)

    const qaTool = new ChainTool({
        name: `qa_tool`,
        description: `Books of the ${chatbotData.name} QA - useful for when you need to ask questions about the opinion of ${chatbotData.name}.`,
        chain: retrievalChain,
        returnDirect: true,
        verbose: true
    })

    const tools = [qaTool]

    return await initializeAgentExecutorWithOptions(tools, model, {
        agentType: 'openai-functions',
        memory: memory,
        returnIntermediateSteps: true,
        agentArgs: {
            prefix:
                `You are ${chatbotData.name}  answering questions about ${chatbotData.name} you can use tools to read his books answer question with this information.`,
            memoryPrompts: [new MessagesPlaceholder("chat_history")],
        }
    })

}
module.exports = {runChatbot};

// Chat API Route
router.post('/chat-agent', async (req, res) => {
    // Handles incoming chat requests
    const {question, history, sessionId, uid, chatbot} = req.body;

    // Validate input
    if (!sessionId || !uid) {
        return res.status(400).json({message: 'No session id in the request'});
    }

    // Check if a question is provided
    if (!question) {
        return res.status(400).json({message: 'No question in the request'});
    }

    // Check if a chatbot is provided
    if (!chatbot) {
        return res.status(400).json({message: 'No chatbot in the request'});
    }

    // Sanitize the question
    const sanitizedQuestion = question.trim().replaceAll('\n', ' ');

    //Retrieve the chatbot from firestore
    const chatbotReference = await admin.firestore().collection('chatbots').doc(chatbot).get();
    const chatbotData = chatbotReference.data();

    history.forEach(msg => {
        console.log(`Type: ${msg.role}, Message: ${msg.content}`);
    });

    const transformedHistory = history.map(msg => {
        return msg.role === 'user'
            ? new CustomHumanMessage({ content: msg.content, name: "user", additional_kwargs: {} })
            : new CustomAIMessage({ content: msg.content, name: chatbotData.name, additional_kwargs: {} });
    });
    const jsonHistory = transformedHistory.map(msg => msg.toJSON());

    console.log('JSON Transformed History:', jsonHistory);

    console.log('Transformed History:', transformedHistory);

    try {
        // Pinecone setup and initialization
        const pinecone = new Pinecone({
            apiKey: process.env.PINECONE_API_KEY,
            environment: process.env.PINECONE_ENVIRONMENT,
        });

        const index = pinecone.Index(process.env.PINECONE_INDEX_NAME);

        // Create a vector store
        const vectorStore = await PineconeStore.fromExistingIndex(
            new OpenAIEmbeddings({}),
            {
                pineconeIndex: index,
                textKey: 'text',
                namespace: "marting_lings",
            }
        );
        // Create a conversational chain
        const executor = await runChatbot(vectorStore, sessionId, uid, chatbotData);

        // Query the chain
        const response = await executor.run(
            {
                author: chatbot,
                input: sanitizedQuestion,
                chat_history: jsonHistory
            },
        )

        console.log(response)
        // Send the response back to the client
        res.status(200).json(response);
    } catch (error) {
        console.error('Error in chat route:', error);
        res.status(500).json({error: error.message || 'Something went wrong'});
    }
});

**Comment by RedouanAssakali** [comment]
@dosu-bot i did what you said but still same error: router.post('/chat-agent', async (req, res) => {
    // Handles incoming chat requests
    const {question, history, sessionId, uid, chatbot} = req.body;


    // Validate input
    if (!sessionId || !uid) {
        return res.status(400).json({message: 'No session id in the request'});
    }

    // Check if a question is provided
    if (!question) {
        return res.status(400).json({message: 'No question in the request'});
    }

    // Check if a chatbot is provided
    if (!chatbot) {
        return res.status(400).json({message: 'No chatbot in the request'});
    }

    // Sanitize the question
    const sanitizedQuestion = question.trim().replaceAll('\n', ' ');

    //Retrieve the chatbot from firestore
    const chatbotReference = await admin.firestore().collection('chatbots').doc(chatbot).get();
    const chatbotData = chatbotReference.data();

    history.forEach(msg => {
        console.log(`Type: ${msg.role}, Message: ${msg.content}`);
    });
    history.forEach(msg => {
        if (typeof msg.content !== 'string') {
            msg.content = String(msg.content);
        }
    });

    const transformedHistory = history.map(msg => {
        return msg.role === 'user'
            ? new CustomHumanMessage({ content: msg.content, name: "user", additional_kwargs: {} })
            : new CustomAIMessage({ content: msg.content, name: chatbotData.name, additional_kwargs: {} });
    });
    const jsonHistory = transformedHistory.map(msg => msg.toJSON());

    console.log('JSON Transformed History:', jsonHistory);

    console.log('Transformed History:', transformedHistory);


    try {
        // Pinecone setup and initialization
        const pinecone = new Pinecone({
            apiKey: process.env.PINECONE_API_KEY,
            environment: process.env.PINECONE_ENVIRONMENT,
        });

        const index = pinecone.Index(process.env.PINECONE_INDEX_NAME);


        // Create a vector store
        const vectorStore = await PineconeStore.fromExistingIndex(
            new OpenAIEmbeddings({}),
            {
                pineconeIndex: index,
                textKey: 'text',
                namespace: "marting_lings",
            }
        );
        // Create a conversational chain
        const executor = await runChatbot(vectorStore, sessionId, uid, chatbotData);

        // Query the chain
        const response = await executor.run(
            {
                author: chatbot,
                input: sanitizedQuestion,
                chat_history: jsonHistory
            },
        )

        console.log(response)
        // Send the response back to the client
        res.status(200).json(response);
    } catch (error) {
        console.error('Error in chat route:', error);
        res.status(500).json({error: error.message || 'Something went wrong'});
    }
});



Error in chat route: BadRequestError: 400 Invalid value for 'content': expected a string, got null.
    at APIError.generate (/Users/redouanassakali/Desktop/ahadai/backend/node_modules/openai/error.js:44:20)
    at OpenAI.makeStatusError (/Users/redouanassakali/Desktop/ahadai/backend/node_modules/openai/core.js:255:33)
    at OpenAI.makeRequest (/Users/redouanassakali/Desktop/ahadai/backend/node_modules/openai/core.js:297:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/redouanassakali/Desktop/ahadai/backend/node_modules/@langchain/openai/dist/chat_models.cjs:650:29
    at async RetryOperation._fn (/Users/redouanassakali/Desktop/ahadai/backend/node_modules/p-retry/index.js:50:12) {
  status: 400,
  headers: {
    'access-control-allow-origin': '*',
    'alt-svc': 'h3=":443"; ma=86400',
    'cf-cache-status': 'DYNAMIC',
    'cf-ray': '84b08811dbe9669a-AMS',
    connection: 'keep-alive',
    'content-length': '189',
    'content-type': 'application/json',
    date: 'Thu, 25 Jan 2024 12:31:09 GMT',
    'openai-organization': 'user-77baunwvgvena6selz0lma0e',
    'openai-processing-ms': '10',
    'openai-version': '2020-10-01',
    server: 'cloudflare',
    'set-cookie': '__cf_bm=2p6.Dr1dBpQ_d4d2eJpBVklaOIJbOdBWRHTn2fEeZ9w-1706185869-1-AZvrUhDsrLScutSNxem4svxONz5h4Od9GXIyIuU8YdvsiI52CVPOD9sNw+Gzm2HGZboXbS1ZrpTCntTzggeRbDA=; path=/; expires=Thu, 25-Jan-24 13:01:09 GMT; domain=.api.openai.com; HttpOnly; Secure; SameSite=None, _cfuvid=WRmnLpxpYUj9cgIivgo88IMaYaRLfuqf01.xy6H0OZ0-1706185869364-0-604800000; path=/; domain=.api.openai.com; HttpOnly; Secure; SameSite=None',
    'strict-transport-security': 'max-age=15724800; includeSubDomains',
    'x-ratelimit-limit-requests': '5000',
    'x-ratelimit-limit-tokens': '160000',
    'x-ratelimit-remaining-requests': '4999',
    'x-ratelimit-remaining-tokens': '159183',
    'x-ratelimit-reset-requests': '12ms',
    'x-ratelimit-reset-tokens': '306ms',
    'x-request-id': 'e1901cac0e6e2a88fa71cd4d4a8e29b1'
  },
  error: {
    message: "Invalid value for 'content': expected a string, got null.",
    type: 'invalid_request_error',
    param: 'messages.[23].content',
    code: null
  },
  code: null,
  param: 'messages.[23].content',
  type: 'invalid_request_error',
  attemptNumber: 1,
  retriesLeft: 6
}

**Comment by RedouanAssakali** [comment]
@dosu-bot here my code: 

makechain.js:
nst { OpenAI } = require('langchain/llms/openai');
const { PineconeStore } = require('langchain/vectorstores/pinecone');
const { ConversationalRetrievalQAChain } = require('langchain/chains');
const { BufferMemory } = require('langchain/memory'); // Import BufferMemory
const { FirestoreChatMessageHistory } = require('langchain/stores/message/firestore'); // Import FirestoreChatMessageHistory
const { PromptTemplate } = require("langchain/prompts");
const admin = require("firebase-admin");
const {ChatOpenAI} = require("@langchain/openai");
const path = require('path');
const dotenv = require('dotenv').config({path: path.resolve(__dirname, '../.env')})
const CONDENSE_PROMPT = `Given the following conversation and a follow up question, rephrase the follow up question to be a standalone question.

Chat History:
{chat_history}
Follow Up Input: {question}
Standalone question:

`;

const QA_PROMPT = `You are {author}. Use the following pieces of context to answer the question at the end.

{context}
Question: {question}
Helpful answer ALWAYS output in markdown!!!

`;

const makeChain = (vectorstore, sessionId, uid, chatbot) => {

const firestoreConfig = {
    collectionName: "chathistory",
    sessionId: sessionId,
    userId: uid,
    config: { projectId: "unity-352c6" },
};

// Initialize the FirestoreChatMessageHistory for chat history
// Here a new sub collection for messages was made
const chatHistory = new FirestoreChatMessageHistory(firestoreConfig);

console.log("chatHistory", chatHistory)
// Create a BufferMemory instance with FirestoreChatMessageHistory
const memory = new BufferMemory({
    chatHistory,
    memoryKey: "chat_history",
    inputKey: "question",
    outputKey: "text",
});

console.log("memory", memory);



const model = new ChatOpenAI({
    temperature: 0.5,
    modelName: chatbot.activeModel,
    openAIApiKey: process.env.OPENAI_API_KEY

});


return ConversationalRetrievalQAChain.fromLLM(
    model,
    vectorstore.asRetriever(),
    {
        qaTemplate: QA_PROMPT.replace('{author}', chatbot.name),
        questionGeneratorTemplate: CONDENSE_PROMPT,
        returnSourceDocuments: true,
        memory,
    },
);

};

module.exports = { makeChain };

agent.js:
const {OpenAI} = require('langchain/llms/openai');
const {initializeAgentExecutorWithOptions} = require('langchain/agents');

const {PineconeStore} = require('langchain/vectorstores/pinecone');
const {OpenAIEmbeddings} = require('langchain/embeddings/openai');
const admin = require("firebase-admin");
const {Pinecone} = require('@pinecone-database/pinecone');

const {BufferMemory, ChatMessageHistory} = require('langchain/memory'); // Import BufferMemory
const {FirestoreChatMessageHistory} = require('langchain/stores/message/firestore'); // Import FirestoreChatMessageHistory
const {PromptTemplate} = require("langchain/prompts");

const {ChainTool} = require("langchain/tools");
const {ConversationalRetrievalQAChain} = require('langchain/chains');
const {response} = require("express");
const {ChatOpenAI} = require("@langchain/openai");
const {makeChain} = require("./makechain");
const {MessagesPlaceholder} = require("@langchain/core/prompts");
const {OpenAIAgentTokenBufferMemory} = require("langchain/agents/toolkits");
const path = require('path');
const dotenv = require('dotenv').config({path: path.resolve(__dirname, '../.env')})

const runChatbot = async (vectorStore, sessionId, uid, chatbotData) => {

const model = new ChatOpenAI({
    temperature: 0.5,
    modelName: chatbotData.activeModel,
    openAIApiKey: process.env.OPENAI_API_KEY

});

const firestoreConfig = {
    collectionName: "chathistory",
    sessionId: sessionId,
    userId: uid,
    config: {projectId: "unity-352c6"},
};

// Initialize the FirestoreChatMessageHistory for chat history
// Here a new sub collection for messages was made
const chatHistory = new FirestoreChatMessageHistory(firestoreConfig);


const memory = new OpenAIAgentTokenBufferMemory({
    llm: model,
    chatHistory: chatHistory,
    memoryKey: 'chat_history',
    outputKey: 'output',
    inputKey: 'input'
})
// Create a conversational chain
const retrievalChain = makeChain(vectorStore, sessionId, uid, chatbotData)

const qaTool = new ChainTool({
    name: `qa_tool`,
    description: `Books of the ${chatbotData.name} QA - useful for when you need to ask questions about the opinion of ${chatbotData.name}.`,
    chain: retrievalChain,
    returnDirect: true,
    verbose: true
})


const tools = [qaTool]

return await initializeAgentExecutorWithOptions(tools, model, {
    agentType: 'openai-functions',
    memory: memory,
    returnIntermediateSteps: true,
    agentArgs: {
        prefix:
            `You are ${chatbotData.name}  answering questions about ${chatbotData.name} you can use tools to read his books answer question with this information.`,
        memoryPrompts: [new MessagesPlaceholder("chat_history")],
    }
})

}
module.exports = {runChatbot};
// Chat API Route
router.post('/chat-agent', async (req, res) => {
    // Handles incoming chat requests
    const {question, history, sessionId, uid, chatbot} = req.body;


    // Validate input
    if (!sessionId || !uid) {
        return res.status(400).json({message: 'No session id in the request'});
    }

    // Check if a question is provided
    if (!question) {
        return res.status(400).json({message: 'No question in the request'});
    }

    // Check if a chatbot is provided
    if (!chatbot) {
        return res.status(400).json({message: 'No chatbot in the request'});
    }

    // Sanitize the question
    const sanitizedQuestion = question.trim().replaceAll('\n', ' ');

    //Retrieve the chatbot from firestore
    const chatbotReference = await admin.firestore().collection('chatbots').doc(chatbot).get();
    const chatbotData = chatbotReference.data();

    history.forEach(msg => {
        console.log(`Type: ${msg.role}, Message: ${msg.content}`);
    });

    const transformedHistory = history.map(msg => {
        return msg.role === 'user'
            ? new CustomHumanMessage({ content: msg.content, name: "user", additional_kwargs: {} })
            : new CustomAIMessage({ content: msg.content, name: chatbotData.name, additional_kwargs: {} });
    });
    const jsonHistory = transformedHistory.map(msg => msg.toJSON());

    console.log('JSON Transformed History:', jsonHistory);

    console.log('Transformed History:', transformedHistory);


    try {
        // Pinecone setup and initialization
        const pinecone = new Pinecone({
            apiKey: process.env.PINECONE_API_KEY,
            environment: process.env.PINECONE_ENVIRONMENT,
        });

        const index = pinecone.Index(process.env.PINECONE_INDEX_NAME);


        // Create a vector store
        const vectorStore = await PineconeStore.fromExistingIndex(
            new OpenAIEmbeddings({}),
            {
                pineconeIndex: index,
                textKey: 'text',
                namespace: "marting_lings",
            }
        );
        // Create a conversational chain
        const executor = await runChatbot(vectorStore, sessionId, uid, chatbotData);

        // Query the chain
        const response = await executor.run(
            {
                author: chatbot,
                input: sanitizedQuestion,
                chat_history: jsonHistory
            },
        )

        console.log(response)
        // Send the response back to the client
        res.status(200).json(response);
    } catch (error) {
        console.error('Error in chat route:', error);
        res.status(500).json({error: error.message || 'Something went wrong'});
    }
});
same error:Error in chat route: BadRequestError: 400 Invalid value for 'content': expected a string, got null.
    at APIError.generate (/Users/redouanassakali/Desktop/ahadai/backend/node_modules/openai/error.js:44:20)
    at OpenAI.makeStatusError (/Users/redouanassakali/Desktop/ahadai/backend/node_modules/openai/core.js:255:33)
    at OpenAI.makeRequest (/Users/redouanassakali/Desktop/ahadai/backend/node_modules/openai/core.js:297:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/redouanassakali/Desktop/ahadai/backend/node_modules/@langchain/openai/dist/chat_models.cjs:650:29
    at async RetryOperation._fn (/Users/redouanassakali/Desktop/ahadai/backend/node_modules/p-retry/index.js:50:12) {
  status: 400,
  headers: {

**Comment by NasirSadeeq** [comment]
hi,
i am working in .net Blazor App and i am getting the same error. any one can help me to sort out.this is my code.
   var messages = new[]
            {
                new CustomChatMessage
                {
                   Role = "user",
                    content = $"Give me answer \n {searchText}\n context {context}"
                }
            };
            Console.WriteLine($"Final Message Content: {messages[0].content}");

            var chatOptions = new ChatCompletionsOptions("gpt-4o", messages)
            {
                MaxTokens = 1000,
                Temperature = 0.4f,
                NucleusSamplingFactor = 0.9f
            };
            var completion = await _openAIClient.GetChatCompletionsAsync(chatOptions);
           
           i am getting this error
            Azure.RequestFailedException: Invalid value for 'content': expected a string, got null.
      Status: 400 (model_error)

      Content:
      {
  "error": {
    "message": "Invalid value for 'content': expected a string, got null.",
    "type": "invalid_request_error",
    "param": "messages.[0].content",
    "code": null
  }
}

      Headers:
      x-ms-region: REDACTED
      apim-request-id: REDACTED
      x-ratelimit-remaining-requests: REDACTED
      x-ms-rai-invoked: REDACTED
      X-Request-ID: REDACTED
      ms-azureml-model-error-reason: REDACTED
      ms-azureml-model-error-statuscode: REDACTED
      x-ms-client-request-id: f8a2dbaa-5584-424f-9277-9ab528a33d97
      Strict-Transport-Security: REDACTED
      azureml-model-session: REDACTED
      X-Content-Type-Options: REDACTED
      x-ratelimit-remaining-tokens: REDACTED
      Date: Thu, 25 Jul 2024 14:52:44 GMT
      Date: Thu, 25 Jul 2024 14:52:44 GMT
      Content-Length: 187
      Content-Type: application/json

         at Azure.Core.HttpPipelineExtensions.ProcessMessageAsync(HttpPipeline pipeline, HttpMessage message, RequestContext requestContext, CancellationToken cancellationToken)
         at Azure.AI.OpenAI.OpenAIClient.GetChatCompletionsAsync(ChatCompletionsOptions chatCompletionsOptions, CancellationToken cancellationToken)
         at BlazorChatBot.controller.AISearchController.Search(String searchText) in C:\Users\TripleK Tech\OneDrive - TripleK\Desktop\OpenAI\BlazorChatBot\controller\AISearchController.cs:line 106
      Date: Thu, 25 Jul 2024 14:52:44 GMT
      Content-Length: 187
      Content-Type: application/json

         at Azure.Core.HttpPipelineExtensions.ProcessMessageAsync(HttpPipeline pipeline, HttpMessage message, RequestContext requestContext, CancellationToken cancellationToken)
      Date: Thu, 25 Jul 2024 14:52:44 GMT
      Content-Length: 187
      Content-Type: application/json

      Date: Thu, 25 Jul 2024 14:52:44 GMT
      Content-Length: 187
      Content-Type: application/json
      Date: Thu, 25 Jul 2024 14:52:44 GMT
      Content-Length: 187
      Date: Thu, 25 Jul 2024 14:52:44 GMT
      Content-Length: 187
      Content-Type: application/json

         at Azure.Core.HttpPipelineExtensions.ProcessMessageAsync(HttpPipeline pipeline, HttpMessage message, RequestContext requestContext, CancellationToken cancellationToken)
         at Azure.AI.OpenAI.OpenAIClient.GetChatCompletionsAsync(ChatCompletionsOptions chatCompletionsOptions, CancellationToken cancellationToken)
         at BlazorChatBot.controller.AISearchController.Search(String searchText) in C:\Users\TripleK Tech\OneDrive - TripleK\Desktop\OpenAI\BlazorChatBot\controller\AISearchController.cs:line 106
