### ISSUE TITLE
Generics params in AgentExecutor and friends

### ISSUE THREAD

**Issue by functorism** [langchain-ai/langchainjs#4155]
It would be really great if these had generic type params such that the prompt param would forward the type information of the prompt to the invoke call.

https://github.com/langchain-ai/langchainjs/blob/43a710d74d0fb0339105996186d6a53b72bb9c3b/langchain/src/agents/openai_tools/index.ts#L24

https://github.com/langchain-ai/langchainjs/blob/43a710d74d0fb0339105996186d6a53b72bb9c3b/langchain/src/agents/openai_tools/index.ts#L98-L102

https://github.com/langchain-ai/langchainjs/blob/43a710d74d0fb0339105996186d6a53b72bb9c3b/langchain/src/agents/executor.ts#L330

This especially nice when using `ParamsFromFString` with the PromptTemplate and also extra utilities like:

```typescript
type Param<L extends string> = `{${L}}`;

type InferFormatParams<S> = S extends `${string}${Param<infer L>}${infer T}`
  ? { [k in L]: string } & InferFormatParams<T>
  : {};

type ObjectTupleIntersection<A, T extends [...unknown[]]> = T['length'] extends 0
  ? A
  : ObjectTupleIntersection<A & T[0], T extends [unknown, ...infer R] ? R : []>;

export const messageTemplate = <M extends [...Array<[string, string] | MessagesPlaceholder>]>(
  ...messages: M
): ChatPromptTemplate<
  ObjectTupleIntersection<
    {},
    {
      [I in keyof M]: M[I] extends [string, infer S]
        ? S extends string
          ? InferFormatParams<S>
          : {}
        : {};
    }
  >
> => ChatPromptTemplate.fromMessages(messages);
```

**Comment by functorism** [comment]
I could work on this if you approve

**Comment by functorism** [comment]
@jacoblee93 This should be possible to fix without any breaking changes I think.

**Comment by jacoblee93** [comment]
Yes this would be awesome! If you are willing to take a crack at it that would be super helpful but I will queue it up as well.
