### ISSUE TITLE
Documentation issue https://js.langchain.com/docs/expression_language/get_started

### ISSUE THREAD

**Issue by JadenSWang** [langchain-ai/langchainjs#4158]
The documentation here: https://js.langchain.com/docs/expression_language/get_started says to run `pnpm add @langchain/openai @langchain/community` but it's missing: @langchain/core/prompts and @langchain/core/output_parsers. Installing @langchain/core seems to help.

**Comment by jacoblee93** [comment]
@langchain/core is installed as a result of installing the other packages - what is erroring for you?

**Comment by jacoblee93** [comment]
It's right here:

https://github.com/langchain-ai/langchainjs/blob/7e16af24dd4ee28e8536e30e9db7ffab0e26a69b/langchain/package.json#L1212

It seemed to work when I tried it with pnpm?
