### ISSUE TITLE
Agent streaming final response

### ISSUE THREAD

**Issue by humbertaco** [langchain-ai/langchainjs#4167]
I have been streaming the final response of an agent by using the callback system (`handleLLMNewToken`). This works just fine. I recently started using LangSmith in my porject and I started facing some issues. It seems that sometimes, the request to LangSmith takes a bit longer and results in the callback not being able to stream the new tokens. I assume that this is because the callbacks are awaited, and therefore my custom callback has to wait for the other to finish.

Looking for a solution, I ended up implementing the one proposed in this article: https://js.langchain.com/docs/modules/agents/how_to/streaming#streaming-tokens. The recommended solution is to use the `streamLog` and check the operations and values. This solution works fine too, but it is a bit cumbersome and difficult to read and understand imho.
In the same page, there is another section that talks about the `stream` method of the `AgentExecutor`. However, such method only returns the chunks after they have been completely received, that is, completely generated. This sounds a bit counterintuitive to me, since other `stream` methods, such as in the chat models (https://js.langchain.com/docs/modules/model_io/chat/streaming#using-stream) and the LLMs (https://js.langchain.com/docs/modules/model_io/llms/streaming_llm#using-stream) seem to indeed provide the tokens as soon as they come.

Wouldn't it make more sense that the `stream` method in the `AgentExecutor` yielded, at least, the tokens that the underlying model generates? It could even be generalized to stream both tokens and intermediate steps, and it would be up to the reader of the stream to decide what to do in each case: do something about the AgentStep or process the new token.

What do you think?

Thanks in advance!

**Comment by jacoblee93** [comment]
Yes I agree that the default behavior of `.stream()` isn't super intuitive - I'll be lobbying to change that in a future release.

In the meantime, we're planning to add a more accessible version of `streamLog` to LangChain.js. This is what it looks like in Python: https://github.com/langchain-ai/langchain/pull/16172

Does that look like a reasonable middle ground?

**Comment by humbertaco** [comment]
I gave a glance at the changes in python and it looks sensible. I think it's a reasonable compromise for the moment.

IMO, a more unified version of `stream` would indeed be beneficial to everyone. So thanks for keeping an eye on that in the future.

Closing the issue now. 
Cheers!
