### ISSUE TITLE
LlamaCpp - Electron Vite - Import/Require Issues

### ISSUE THREAD

**Issue by drevkin** [langchain-ai/langchainjs#4181]
i wanted to test out using LlamaCpp in an electron vite app that I have been working on and ran into module/esm issue with the LlamaCpp .cjs file. Currently when trying to run any LlamaCpp models I get the following error:

Error [ERR_REQUIRE_ESM]: require() of ES Module ../node_modules/node-llama-cpp/dist/index.js from ../node_modules/@langchain/community/dist/utils/llama_cpp.cjs not supported.
Instead change the require of index.js in ../node_modules/@langchain/community/dist/utils/llama_cpp.cjs to a dynamic import() which is available in all CommonJS modules.

Is there something that I am doing wrong on my end? Or is this potentially a bug when using this inside of Electron Vite? I was able to get the LlamaCpp object working in a standalone environment. Any advice would be greatly appreciated.

**Comment by jacoblee93** [comment]
I think `node-llama-cpp` has trouble with MJS - can you use CJS instead?

Will dig in a bit and see what I can do as well

**Comment by drevkin** [comment]
Yeah looking into it deeper realize its actually a node-cpp thing. their package is esm only. Have to figure out something on that end.

**Comment by jacoblee93** [comment]
I will open an issue on their end and see if I can do something clever in the meantime 👍
