### ISSUE TITLE
ChatCohere memory doesn't work with RunnableWithMessageHistory

### ISSUE THREAD

**Issue by imjwang** [langchain-ai/langchainjs#4186]
I'm using ChatCohere with RunnableWithMessageHistory and ChatMessageHistory

When I introduce myself and ask for my name back it doesn't remember.

trace shows that the messages were sent but response doesn't seem right.
https://smith.langchain.com/public/234db893-cec2-41f6-8964-13f0714061e3/r

I was able to fix and will submit a pr.

**Comment by BIGDADDYNISH** [comment]
Matrix2.0
