### ISSUE TITLE
Cassandra Chat Memory TypeError, indicating that "Contacts points are not defined."

### ISSUE THREAD

**Issue by natapol2547** [langchain-ai/langchainjs#4190]
Description:
The Langchain JS [Cassandra Chat Memory documentation](https://js.langchain.com/docs/integrations/chat_memory/cassandra#astra-db) specifies a configuration for connecting to Cassandra using the cassandra-driver. However, when attempting to use this configuration, it results in a TypeError, indicating that "Contacts points are not defined." I am using [Astra DB](https://www.datastax.com/)

Code to Reproduce:
```ts
const configConnection = {
  serviceProviderArgs: {
    astra: {
      token: "<your Astra Token>" as string,
      endpoint: "<your Astra Endpoint>" as string,
    },
  },
};

const memory = new BufferMemory({
  chatHistory: new CassandraChatMessageHistory({
    ...configConnection,
    keyspace: "langchain",
    table: "message_history",
    sessionId: "<some unique session identifier>",
  }),
});
```

Error Log:
```
TypeError: Contacts points are not defined.
    at Object.extend (C:\Users\...\node_modules\.pnpm\cassandra-driver@4.7.2\node_modules\cassandra-driver\lib\client-options.js:120:13)
    at new Client (C:\Users\...\node_modules\.pnpm\cassandra-driver@4.7.2\node_modules\cassandra-driver\lib\client.js:402:32)
    at new CassandraChatMessageHistory (file:///C:/Users/.../node_modules/.pnpm/@langchain+community@0.0.20_@datastax+astra-db-ts@0.1.4_@pinecone-database+pinecone@2.0.1_cas_jikza335ii3jk2j2qigxowhicm/node_modules/@langchain/community/dist/stores/message/cassandra.js:85:23)
...
```

Additional Information:
Langchain JS version: 0.1.9
cassandra-driver version: 4.7.2

**Comment by natapol2547** [comment]
On the other hand, I should ask for a feature request for integration with Astra DB Chat Memory like Langchain Python has [Link](https://python.langchain.com/docs/integrations/memory/astradb_chat_message_history).
It would use the astra-db-ts library instead.
It would be awesome if we have that 😊

**Comment by nicoloboschi** [comment]
@natapol2547 

AstraDB is supported by `CassandraChatMessageHistory` and it works for me. 
I'm using LangChain community @0.0.32

```
            const configConnection = {
                serviceProviderArgs: {
                    astra: {
                        token: "AstraCS:zzz",
                        endpoint: "https://fxxx.apps.astra.datastax.com"
                    },
                },
            };

            const chatHistory = new CassandraChatMessageHistory({
                ...configConnection,
                keyspace: "default_keyspace",
                table: "message_history",
                sessionId: "yyy",
            })
            chatHistory.addMessage(new AIMessage("test?"))
```

Agreed about the having AstraDB integration! But the current cassandra is still compatible

**Comment by mfortman11** [comment]
@natapol2547  `AstraDBChatMessageHistory` was added as part of [0.1.21](https://github.com/langchain-ai/langchainjs/releases/tag/0.1.21)

**Comment by natapol2547** [comment]
@mfortman11 Ohh Thank you so much for mentioning me! I'll close this issue now. 😊
