### ISSUE TITLE
createStuffDocumentsChain doesn't spread meta_data

### ISSUE THREAD

**Issue by codinginflow** [langchain-ai/langchainjs#4195]
The `createStuffDocumentsChain` has a `documentProp` argument with the following description:

> @param documentPrompt
Prompt used for formatting each document into a string. Input variables can be "page_content" or any metadata keys that are in all documents. "page_content" will automatically retrieve the Document.page_content, **and all other inputs variables will be automatically retrieved from the Document.metadata dictionary.** Default to a prompt that only contains Document.page_content.

However, this function doesn't actually add the metadata to the template and the values are not available.

**Comment by jacoblee93** [comment]
Thanks for the heads up - will patch ASAP!
