### ISSUE TITLE
System Template and ChatPromptTemplate never makes it into the ChatVectorDB

### ISSUE THREAD

**Issue by OmriNach** [langchain-ai/langchainjs#422]
<img width="801" alt="Screen Shot 2023-03-21 at 11 58 43 PM" src="https://user-images.githubusercontent.com/32659330/226798844-f5b4beb1-61d9-43f8-bf10-067422025a28.png">

I noticed this as i created identical templates in python and javascript and they were giving different behaviors. Followed the python guide for creating ChatVectorDB, then did the same format for javascript. Digging into the definitions of my chain I dont ever see the system message template

**Comment by OmriNach** [comment]
<img width="453" alt="image" src="https://user-images.githubusercontent.com/32659330/226799412-e7a86958-7754-4fe8-ac28-8d1e5c5172f6.png">
<img width="1015" alt="image" src="https://user-images.githubusercontent.com/32659330/226799455-9c00230c-1b5a-4fe5-93d9-fcff9ed4c2b5.png">

**Comment by OmriNach** [comment]
above is javascript, below is python. The 'messages' variable is not even included in the javascript version

**Comment by OmriNach** [comment]
FIXES:
in chat_vector_db_chain.js: changed qa_prompt line 
static fromLLM(llm, vectorstore, options = {}) {
        const { questionGeneratorTemplate, qaTemplate, ...rest } = options;
        const question_generator_prompt = PromptTemplate.fromTemplate(questionGeneratorTemplate || question_generator_template);
        const qa_prompt = qaTemplate || PromptTemplate.fromTemplate(qa_template);
        const qaChain = loadQAStuffChain(llm, { prompt: qa_prompt });
        const questionGeneratorChain = new LLMChain({
            prompt: question_generator_prompt,
            llm,
        });
        const instance = new this({
            vectorstore,
            combineDocumentsChain: qaChain,
            questionGeneratorChain,
            ...rest,
        });
        return instance;
    }

in qa_answering load.js: changed prompt definition line:

export const loadQAStuffChain = (llm, params = {}) => {
    const { prompt } = params;
    const actualPrompt = prompt || QA_PROMPT_SELECTOR.getPrompt(llm);
    const llmChain = new LLMChain({ prompt: actualPrompt, llm });
    const chain = new StuffDocumentsChain({ llmChain });
    return chain;
};

**Comment by hwchase17** [comment]
the signature of `fromLLM` does not currently allow for this. see the function defintion below:

```
static fromLLM(
    llm: BaseLanguageModel,
    vectorstore: VectorStore,
    options: {
      inputKey?: string;
      outputKey?: string;
      k?: number;
      returnSourceDocuments?: boolean;
      questionGeneratorTemplate?: string;
      qaTemplate?: string;
    } = {}
  ): ChatVectorDBQAChain
```

however, the `fromLLM` method is just a classmethod. you can initialize the chain more explicitly to have more control. see the code thats inside the `fromLLM` method

```
const { questionGeneratorTemplate, qaTemplate, ...rest } = options;
    const question_generator_prompt = PromptTemplate.fromTemplate(
      questionGeneratorTemplate || question_generator_template
    );
    const qa_prompt = PromptTemplate.fromTemplate(qaTemplate || qa_template);

    const qaChain = loadQAStuffChain(llm, { prompt: qa_prompt });
    const questionGeneratorChain = new LLMChain({
      prompt: question_generator_prompt,
      llm,
    });
    const instance = new this({
      vectorstore,
      combineDocumentsChain: qaChain,
      questionGeneratorChain,
      ...rest,
    });
    return instance;
  }
```

if you wanted to use your own CUSTOM_PROMPT as the question-answering prompt, you could use that code but using CUSTOM_PROMPT, ala:

```
const { questionGeneratorTemplate, qaTemplate, ...rest } = options;
    const question_generator_prompt = PromptTemplate.fromTemplate(
      questionGeneratorTemplate || question_generator_template
    );
    const qa_prompt = PromptTemplate.fromTemplate(qaTemplate || qa_template);

    const qaChain = loadQAStuffChain(llm, { prompt: qa_prompt });
    const questionGeneratorChain = new LLMChain({
      prompt: CUSTOM_PROMPT,
      llm,
    });
    const instance = new this({
      vectorstore,
      combineDocumentsChain: qaChain,
      questionGeneratorChain,
      ...rest,
    });
    return instance;
  }
```

**Comment by toonverbeek** [comment]
@hwchase17 thanks for explaining, that makes sense!

**Comment by TimPietrusky** [comment]
@hwchase17 are there any plans to change the logic here so that it's more easy (like in Python) to have a custom prompt? Or is it as strict like this for a specific reason?
