### ISSUE TITLE
No streaming with HuggingFace

### ISSUE THREAD

**Issue by andreasjoensson** [langchain-ai/langchainjs#4221]
Hi i am testing out a model using HuggingFace, but it seems that streaming is not available when using huggingface. I have just switched from a OpenAI model to this instead. 

But there is nothing returned in the callback functions.

`    return executor.invoke(
      {
        input: input
      },
      {
        callbacks: [
          {
            handleLLMNewToken(token: string) {
              console.log('New token:', token)
              res.write(token)
            }
          }
        ]
      }
    )
  } catch (error) {
    console.error('Error occurred:', error)
    throw error
  }
}`

**Comment by hinthornw** [comment]
@andreasjoensson it looks like you're using JavaScript? Could you please open this issue in https://github.com/langchain-ai/langchainjs instead so we can better track issues?
