### ISSUE TITLE
Streaming tokens does not work

### ISSUE THREAD

**Issue by rednebmas** [langchain-ai/langchainjs#4230]
The documentation on how to do streaming is here https://js.langchain.com/docs/modules/agents/how_to/streaming

If I follow this, streaming still does not work. I've created an example repo https://github.com/rednebmas/langchain-streaming-bug

**Comment by rednebmas** [comment]
@dosubot seems unlikely the model is not actually streaming as requested, the tell me a story chunk is very long.

**Comment by jacoblee93** [comment]
Thank you for the reproducible example - I think this is a regression. Will dive in and fix 👍

**Comment by jacoblee93** [comment]
Actually, it was a regression :( caused by #4083

Fix will be live soon.

**Comment by jacoblee93** [comment]
Upgrading @langchain/core to 0.1.21 should fix this!

**Comment by bkamapantula** [comment]
I was able to reproduce the original reported bug.

Thanks for the quick fix, Jacob!
