### ISSUE TITLE
HuggingFace Inference - Not removing stop tokens.

### ISSUE THREAD

**Issue by RussellCanfield** [langchain-ai/langchainjs#4233]
Hi, I am experiencing an issue where the HuggingFaceInference is not removing stop sequences/tokens and has no clear way to specify what they should be.

**Packages used:**
 "@langchain/community": "0.0.24",
"langchain": "0.1.11",
"@huggingface/inference": "2.6.4",

**Usage**
```typescript
const model = new HuggingFaceInference({
    model: 'mistralai/Mixtral-8x7B-Instruct-v0.1',
    temperature: 0.8
  });

const chunks = await model.stream("my question");
```

This works great, streaming works great, but I always get text that ends with "< / s >"

**Comment by jacoblee93** [comment]
I ran into this too - I think unfortunately they work a bit differently from OpenAI's style :(

Could you flag the issue to them?

**Comment by RussellCanfield** [comment]
> I ran into this too - I think unfortunately they work a bit differently from OpenAI's style :(
> 
> Could you flag the issue to them?

Thanks for replying! 

So what's interesting is if you use the HF REST API directly you don't get that special token. I also noticed LangChain passes the stop sequences but there is no support for that in their REST API. It definitely feels like it's coming from their inference NPM package though. I will open an issue there.

**Comment by RussellCanfield** [comment]
@jacoblee93 - this is not reproducible using the @huggingface/inference package directly. Must be processing after the response chunk comes back into LangChain

**Comment by jacoblee93** [comment]
Could be the SDK version? I will try again tomorrow.

**Comment by Gr33nLight** [comment]
Bumping, this issue happens with TogetherAI LLM as well. 
Tested with this configuration (also with LLAMA2 70b): 

```
TogetherAI({
  modelName: 'mistralai/Mixtral-8x7B-Instruct-v0.1',
  streaming: true,
  temperature: 0,
});

```
