### ISSUE TITLE
Types have separate declarations of a private property 'apiKey'

### ISSUE THREAD

**Issue by gadogado** [langchain-ai/langchainjs#4242]
```
Type 'import("/Users/foo/Code/bar/node_modules/langsmith/dist/client").Client' is not assignable to type 'import("/Users/foo/Code/bar/node_modules/@langchain/core/node_modules/langsmith/dist/client").Client'.

Types have separate declarations of a private property 'apiKey'.
```

This suggests that two different instances of the langsmith package are being used – one directly in my project and another contained in @langchain/core.  Any ideas on how to resolve?  Here's my implementation:

```
import { Client } from 'langsmith';

const client = new Client({ apiKey: env.LANGCHAIN_API_KEY });
const exampleId = uuid4();
const tracer = new LangChainTracer({
  projectName: 'foo',
  exampleId,
  client,
});

```
    "langchain": "^0.1.11",
    "langsmith": "^0.0.63",
    "typescript": "4.9.5",
```

**Comment by gadogado** [comment]
This might be problematic considering `yarn add langsmith` currently points to the released version, `0.0.63`

https://www.npmjs.com/package/langsmith

Any idea on the discrepancy here?

**Comment by gadogado** [comment]
@dosu-bot This might be problematic considering `yarn add langsmith` currently has version, `0.0.63`

https://www.npmjs.com/package/langsmith

**Comment by jacoblee93** [comment]
You can set the resolutions field to the latest version (instructions similar to: https://js.langchain.com/docs/get_started/installation#installing-integration-packages)

We will look into ways to make this and other shared dependencies more robust against this 👍
