### ISSUE TITLE
 ConversationalRetrievalQAChain: Full Response Instead of Tokens in Streaming

### ISSUE THREAD

**Issue by anurag-pandey-007** [langchain-ai/langchainjs#4257]
Hi everyone,

I'm new in LangChain currently I'm working on a LangChain project using ConversationalRetrievalQAChain and OpenAI to achieve token-based incremental processing. The goal is to process each generated token as it's written for custom formatting and sentiment analysis. Unfortunately, I'm encountering an issue where I only receive the entire response at the end, instead of individual tokens as expected.

I'm building a chatbot application that utilizes ConversationalRetrievalQAChain to provide responses based on a conversation history and a user query.
I'm trying to implement token-based streaming to process each generated token individually for sentiment analysis and dynamic response formatting.

**here is my code snippets** 

```
const model = new OpenAI({
  temperature: 0,
  modelName: 'gpt-4',
  streaming: true,
  callbacks: [
    {
      handleLLMNewToken(token) {
        console.log("Token response",token);
        
        return token;
      },
    },
  ],
});

const chain = ConversationalRetrievalQAChain.fromLLM(
  model,
  vectorstore.asRetriever({ k: 6 }),
  ... // relevant chain options like qaTemplate and questionGeneratorTemplate
);

const response = await chain.stream({ question: "Sample question", chat_history: "Previous conversation..." });

for await (const data of responseStream) {
  console.log("Expected to iterate over individual tokens, but only receiving full response object.");
  console.log("Token response:",token);  
}

```
### Expected Behavior:

The handleLLMNewToken callback should be triggered for each generated token, allowing me to process them individually.
The for await loop should iterate over individual tokens, enabling access and processing for each token separately.

### Observed Behavior:

The handleLLMNewToken callback only logs the token based response
The for await loop iterates over a single full response object instead of individual tokens.

### Questions:

1. What configuration or setting am I missing to enable token-based incremental processing within the chain's stream method?
2. Is there a specific approach I should be using to access individual tokens during streaming, instead of the current setup?
3. Are there any potential limitations with ConversationalRetrievalQAChain or OpenAI in providing token-based streaming responses?

### Additional Information:

LangChain version: langchain@0.1.7
Operating system: Ubuntu 22.04 (jammy)
Code dependencies: langchain@0.1.7

**Any help or suggestions would be greatly appreciated!**

**Comment by anurag-pandey-007** [comment]
@dosu-bot 
does I need to use something else instead of ConversationalRetrievalQAChain for achieving same functionality ?

**Comment by imjwang** [comment]
Hey, I don't think streaming is implemented for `ConversationalRetrievalQAChain` yet. If you still want to use the same chain you can try to mimic the behavior by tokenizing.

```shell
npm install tiktoken-js
```

```typescript
import { encodingForModel } from 'js-tiktoken'
const enc = encodingForModel('gpt-3.5-turbo-0125')
const tokenizedResponse = enc.encode(response)
for (const token of tokenizedResponse) {
  console.log(enc.decode([token]))
}
```

**Comment by jasonunderstood** [comment]
Try using the `streamLog` method instead; you'll have to do some parsing, since it returns a PatchObject for each token. There's also `streamEvents` in beta, though I haven't used it.

https://js.langchain.com/docs/expression_language/interface#stream-log
https://js.langchain.com/docs/expression_language/interface#stream-events

**Comment by andrewnguonly** [comment]
For context, I believe the issue described in this [Discord thread](https://discord.com/channels/1038097195422978059/1076182741374214285/1218768991275712582) is the same issue (or related).
