### ISSUE TITLE
Getting [ERR_PACKAGE_PATH_NOT_EXPORTED] on execution

### ISSUE THREAD

**Issue by Doug-Bowen** [langchain-ai/langchainjs#4269]
Running npx ts-node chains/preparation.langChain.ts results in:

`user@number repoName % npx ts-node chains/preparation.langChain.ts
^[[AError [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './utils/function_calling' is not defined by "exports" in /Users/doug.bowen/Documents/Repos/repoName-AI/node_modules/@langchain/openai/node_modules/@langchain/core/package.json
    at new NodeError (node:internal/errors:405:5)
    at exportsNotFound (node:internal/modules/esm/resolve:362:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:698:9)
    at resolveExports (node:internal/modules/cjs/loader:567:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:636:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1063:27)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/Users/user/Documents/Repos/repoName/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'`

**Comment by jacoblee93** [comment]
What version of `@langchain/core` do yo uhave installed?

**Comment by Doug-Bowen** [comment]
I did an npm install langchain so it must have pulled the latest.  I believe it's 0.0.13 but that's from memory.

Do I need to pull langchain, community, and core? Or is it enough to only pull langchain via npm?

**Comment by jacoblee93** [comment]
Sometimes package managers don't resolve things in a good way - can you try setting core to the latest version like this?

https://js.langchain.com/docs/get_started/installation#installing-integration-packages

**Comment by Doug-Bowen** [comment]
Still not working.  I've cleared my node_modules and repulled all dependancies.  

This is my package.json:

`{
  "name": "---",
  "version": "0.1.0",
  "description": "Repo for ---",
  "repository": {
    "type": "git",
    "url": "https://github.com/---"
  },
  "author": {
    "name": "---"
  },
  "contributors": [],
  "scripts": {
    "aws:login": "aws sso login",
  },
  "private": true,
  "license": "UNLICENSED",
  "dependencies": {
    "@aws-sdk/client-secrets-manager": "^3.491.0",
    "@langchain/openai": "^0.0.14",
    "@octokit/rest": "^20.0.2",
    "@tsconfig/node18": "^18.2.2",
    "@types/node": "^20.11.2",
    "@types/uuid": "^9.0.7",
    "axios": "^1.6.5",
    "config": "^3.3.10",
    "gh": "^2.8.9",
    "langchain": "^0.1.12",
    "octokit": "^3.1.2",
    "openai": "^4.24.7",
    "reflect-metadata": "^0.2.1",
    "tsoa": "^6.0.1",
    "typescript": "^5.3.3",
    "uuid": "^9.0.1"
  },
  "devDependencies": {
    "ts-node": "^10.9.2"
  },
  "overrides": {
    "@langchain/core": "0.1.12"
  }
}
`

This is my tsconfig:
`{
  "extends": "@tsconfig/node18/tsconfig.json",
  "compilerOptions": {
    "target": "ES2022",
    "module": "nodenext",
    "sourceMap": true,
    "types": ["node", "reflect-metadata"],
    "strict": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": true,
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "allowJs": true,
    "strictPropertyInitialization": false
  },
  "include": ["swarms/*", "agents/*"]
}`

**Comment by jacoblee93** [comment]
Your overrides field has core set to 0.1.12

**Comment by Doug-Bowen** [comment]
Is this not correct?

**Comment by Doug-Bowen** [comment]
oh weird.  I see the example shows "@langchain/core": "0.1.5"

ill fix that and try

**Comment by Doug-Bowen** [comment]
still same outcome

`  "dependencies": {
    "@aws-sdk/client-secrets-manager": "^3.491.0",
    "@langchain/openai": "^0.0.14",
    "@octokit/rest": "^20.0.2",
    "@tsconfig/node18": "^18.2.2",
    "@types/node": "^20.11.2",
    "@types/uuid": "^9.0.7",
    "axios": "^1.6.5",
    "config": "^3.3.10",
    "gh": "^2.8.9",
    "langchain": "^0.1.12",
    "octokit": "^3.1.2",
    "openai": "^4.24.7",
    "reflect-metadata": "^0.2.1",
    "tsoa": "^6.0.1",
    "typescript": "^5.3.3",
    "uuid": "^9.0.1"
  },
  "devDependencies": {
    "ts-node": "^10.9.2"
  },
  "overrides": {
    "@langchain/core": "0.1.5"
  }`

**Comment by jacoblee93** [comment]
Set to latest

**Comment by Doug-Bowen** [comment]
I'll set it to 0.1.22

**Comment by Doug-Bowen** [comment]
that fixed it.  thanks!
