### ISSUE TITLE
Agents with streaming executing twice!

### ISSUE THREAD

**Issue by zakariamehbi** [langchain-ai/langchainjs#4272]
I have an issue with the agents. I'm using agents + streaming with the web browser.
Let's say I ask the following prompt: `Summarize: https://js.langchain.com/docs/guides/deployment/`

The agents will start executing with `"arguments": "{"input": "https://js.langchain.com/docs/guides/deployment/,/"%7D" }` then stream the answer, but also run a second time with the following argument:  `"arguments": "{"input": "https://js.langchain.com/docs/guides/deployment/,summary/"%7D"}`. 

Meaning I end up with 2 summaries. Any ideas, please?

This is my implementation: 

```
const agents = [...]

agents.push(
    new WebBrowser({
        model: LLM,
        embeddings: new OpenAIEmbeddings({
            verbose: debug,
            openAIApiKey: Env.get('OPENAI_API_KEY'),
            modelName: 'text-embedding-ada-002',
            timeout: 60,
        }),
    })
)

const customPrompt = ChatPromptTemplate.fromMessages([
    new SystemMessage(computedSystemPrompt),
    ...pastMessages,
    new MessagesPlaceholder('chat_history'),
    ...(agents.length > 0 ? [new MessagesPlaceholder('agent_scratchpad')] : []),
    ['human', '{input}'],
])

if (agents.length) {
    const agent = await createOpenAIToolsAgent({
    // @ts-ignore
    llm: LLM,
    tools: agents,
    prompt: customPrompt,
})

const agentExecutor = new AgentExecutor({
    agent,
    tools: agents,
    verbose: debug,
    returnIntermediateSteps: false,
    maxIterations: 1 + agents.length * 2,
})

agentExecutor.invoke({
    input: computedContextPrompt,
    chat_history: pastMessages,
    verbose: debug,
})
```

**Comment by zakariamehbi** [comment]
By the way, I'm using callbacks, so handleLLMEnd gets called twice with each web-browser call!

**Comment by jacoblee93** [comment]
It looks like the first tool response isn't enough to answer the query, so it is trying again.

**Comment by zakariamehbi** [comment]
@jacoblee93 But it's actually enough and it's streaming the first answer, then the second. Any ideas? Do you need more logs? Thank you

**Comment by ahm750** [comment]
@zakariamehbi Did you figure this out? I'm having a similar issue. For me, it happens only when chat history is provided.
