### ISSUE TITLE
[Feature Request] Upstash Vector VectorStore

### ISSUE THREAD

**Issue by samlaycock** [langchain-ai/langchainjs#4281]
Upstash has launched [Upstash Vector](https://upstash.com/docs/vector/overall/whatisvector). It would be great to have this added as a Vector Store option in the community package.

I'm happy to take a crack at this if there's appetite for it to be added. Just wanted to file the issue first.

**Comment by fahreddinozcan** [comment]
Hey! We're currently working on the integration PR #4288 and we'll finalize it real soon(hopefully tomorrow). We'd love to hear your feedback!

**Comment by Gr33nLight** [comment]
@fahreddinozcan Hello I saw you resolved my issue on metadata filtering in the upstash repo, thank you! Would it be possible to also implement the filtering it in the langchain abstraction (if not already in the plans)? I can give it a crack if its needed. Also I can create a separate issue to track this.

**Comment by fahreddinozcan** [comment]
@Gr33nLight Yes, this seems pretty important for the Langchain. I will make sure it's prioritized. Thanks for the heads up here. I hope to send a PR this week.
