### ISSUE TITLE
specifying commit hash in `hub.pull` is not working

### ISSUE THREAD

**Issue by CNSeniorious000** [langchain-ai/langchainjs#4289]
# Description

For example, these two should be different:

```js
import { pull } from "langchain/hub"

await pull("langchain-ai/chain-of-density")
await pull("langchain-ai/chain-of-density:ba34ae10")
```

But the result is the same.

## A simple reproduction

```js
> (await pull("langchain-ai/chain-of-density:ba34ae10")).promptMessages[0].prompt.template === (await pull("langchain-ai/chain-of-density")).promptMessages[0].prompt.template
// true
```

---

Note that the python SDK is working, but in the JavaScript SDK it seems specifying a commit hash is useless. I don't know why.

**Comment by bracesproul** [comment]
Hmm I'm seeing this issue too, not good. Will investigate now!

**Comment by bracesproul** [comment]
I've identified a fix and it will be released soon! I'll update you here once we update the `langchain` package with it!
