### ISSUE TITLE
Module not found: Can't resolve 'string_decoder'

### ISSUE THREAD

**Issue by mikesprague** [langchain-ai/langchainjs#4290]
As of the latest release of `@langchain/core` (`v0.1.23`) Next.js/Webpack builds are failing with the following error:

```shell
Failed to compile.

./node_modules/sax/lib/sax.js:234:17
Module not found: Can't resolve 'string_decoder'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/@langchain/core/dist/output_parsers/xml.js
./node_modules/@langchain/core/dist/output_parsers/index.js
./node_modules/@langchain/core/output_parsers.js
./app/api/langchain/route.ts
```

When the version of `@langchain/core` is reverted to `v0.1.22` it builds as expected.

At this point, that's all the info I have on this.

**Comment by mikesprague** [comment]
Versions

- Next.js: v14.1.0
- Node.js: v20.11.0
- Webpack: v5.86.0 (based on `package.json` for Next.js [here](https://github.com/vercel/next.js/blob/89e68377baf3ea6d2bf09e0ae694f57ec5c8ea93/packages/next/package.json#L314))
- Operating System: MacOS Sonoma/GitHub Actions Runners/Linux (latest Alpine and Ubuntu via Docker)

Custom Config

- N/A - No custom config, this is entire `next.config.js`:
  ```js
  /** @type {import('next').NextConfig} */
  const nextConfig = {
    typescript: {
      ignoreBuildErrors: true,
    },
  };
  
  module.exports = nextConfig;
  ```

Please let me know if I can provide any additional details.

**Comment by ElectricCodeGuy** [comment]
Same issue after updating the core

**Comment by ElectricCodeGuy** [comment]
I have the same issue. It seems to be the new XML parser
import { XMLOutputParser } from "../xml.js" and the edge runtime that might not be compatible

**Comment by mikesprague** [comment]
This seems to be resolved in `0.1.24` of `@langchain/core`.

**Comment by mikesprague** [comment]
I spoke too soon... local dev runs fine but production builds still produce same error.

**Comment by jacoblee93** [comment]
Hey, really sorry, am on this now!

**Comment by jacoblee93** [comment]
Core release 0.1.25 should fix this in a few minutes.

**Comment by mikesprague** [comment]
My Next.js app seems to be building successfully again using `0.1.25`. Thank you!
