### ISSUE TITLE
[Feature Request] Done: Implement SQLite RecordManager

### ISSUE THREAD

**Issue by jasonnathan** [langchain-ai/langchainjs#4320]
Currently there is a postgres and memory implementation for RecordManager. While I was working on the chat_langchain repository, I noticed that the python version of ingest.py supports sqlite for a RecordManager so I implemented one in the JS library as well. 

PR is ready, but wanted to open an issue first

**Comment by jasonnathan** [comment]
@jacoblee93 okay to close this? The implementation is based on the existing PostgresRecordManager class.
This is so I can push some updates to the chat-langchain repo as well

**Comment by jacoblee93** [comment]
I will have a look today!
