### ISSUE TITLE
[Feature request]  Azure OpenAI Assistants

### ISSUE THREAD

**Issue by tsuzaki430** [langchain-ai/langchainjs#4338]
Hi, Microsoft has released Assistants API on Azure.
I hope it will be supported on langchain.

https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/openai/openai-assistants/README.md
https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/assistants

**Comment by tsuzaki430** [comment]
Hi,

I found get it works in Azure OpenAI Assistant Api with 'openai' package.

https://github.com/openai/openai-node/issues/701
This issue's comversation about azure assistant API in openai package example.

So I close this issue and thank you for langchain.js every contributors.

**Comment by MNorgren** [comment]
Any update on this? I am still not seeing support for Azure OpenAI Assistants. Anyone else?

**Comment by halimb** [comment]
Same here, it's the main limitation keeping me from migrating to LangChain
