### ISSUE TITLE
 I seem to have found a code error?

### ISSUE THREAD

**Issue by likaiqiang** [langchain-ai/langchainjs#4342]
At https://github.com/langchain-ai/langchainjs/blob/0.1.16/langchain-core/src/vectorstores.ts#L274 location and https://github.com/langchain-ai/langchainjs/blob/0.1.16/langchain-core/src/vectorstores.ts#L289  location, the similaritySearchVectorWithScore method is called with three arguments, but at https://github.com/langchain-ai/langchainjs/blob/0.1.16/libs/langchain-community/src/vectorstores/faiss.ts#L130 location, only two arguments are received. Where is the filter argument?

**Comment by bracesproul** [comment]
Hmm, this does look wrong. Will look into it, thank you for reporting!
