### ISSUE TITLE
OpenAIAssistantRunnable do not return answer from LLM if thread is more than 20 messages

### ISSUE THREAD

**Issue by 1g0rrr** [langchain-ai/langchainjs#4352]
After 20 messages in the thread this code:
```
    agentResponse = await agentExecutor.invoke({
        threadId: threadId,
        content: textMessage,
    });
    console.log("agentResponse", agentResponse);
```
return empty output:
`agentResponse { output: '' }`

It seems that the reason of this is "asc" tag inside this file "langchainjs/langchain/src/experimental/openai_assistant
/index.ts"
so script tries to look for new messages only at the beginnign of the thread.

Here is the prblematic code part:
```
...
    if (run.status === "completed") {
      const messages = await this.client.beta.threads.messages.list(threadId, {
        order: "asc",
      });
      const newMessages = messages.data.filter((msg) => msg.run_id === runId);
      if (!this.asAgent) {
        return newMessages;
      }
      const answer = newMessages.flatMap((msg) => msg.content);
...
```

I can make pr and fix and test this if you don't mind.

**Comment by Cirmiir** [comment]
Hello,

Are there any updates about this issue?
It seems like the order and limit parameters for request are not configurable externally.

Could It be any simple solution that can help with updating current settings for request?

Thanks!
