### ISSUE TITLE
Syntax error in human_in_the_loop.mdx after quatro processing

### ISSUE THREAD

**Issue by jasonnathan** [langchain-ai/langchainjs#4360]
This is a bug in quatro. human_in_the_loop.ipynb is causing an error with the docs build. Somehow the correct syntax in the ipynb file:
```mdx
import CodeBlock from "@theme/CodeBlock";
import HumanFeedback from "@examples/use_cases/human_in_the_loop/accept-feedback.ts";
```
is wrongly interpreted as:
```mdx
import CodeBlock from “(**theme/CodeBlock?**)”; import HumanFeedback
from “(**examples/use_cases/human_in_the_loop/accept-feedback.ts?**)”;
```

**Comment by jasonnathan** [comment]
I think in this one-off case, it would be simpler to just use `examples/use_cases/human_in_the_loop/accept-feedback.ts` content directly in the ipynb but if this is going to be common practice like other mdx files then it should be looked into

**Comment by jacoblee93** [comment]
@bracesproul can you have a look?

**Comment by bracesproul** [comment]
Hmm this is weird.

How were you able to produce this? The builds are working fine in Vercel & locally (on my mac).

Are you running windows?

**Comment by jasonnathan** [comment]
Nope Mac too. Happens right after quattro is done.anf the docs build fails

**Comment by jasonnathan** [comment]
Just in case you hadn't noticed, that's a “ not a " as well and only for this one file

**Comment by jasonnathan** [comment]
Maybe try without cache on your end?

**Comment by bracesproul** [comment]
Even with no cache I'm still unable to reproduce this error. There is a script which handles this bad quote (`“` ), are you sure your code is up to date with the latest `main`?

Also cc @jacoblee93 are you able to reproduce?

**Comment by jacoblee93** [comment]
I updated the docs build - can you pull main and try again? Reopen if it reoccurs
