### ISSUE TITLE
Cannot specify the number of shards or replicas when using OpenSearch vector store

### ISSUE THREAD

**Issue by ansnoussi** [langchain-ai/langchainjs#4373]
## Issue
- Currently it's not possible to specify the number of shards/replicas when working with OpenSerach vector store.
- This is problematic when using Langchain with OpenSearch in a multi-tenant setting, where we want to have data segregation but still use the same OpenSearch cluster => one tenant per index.
- This setting hits rapidly the `max_shards_per_node` limit of OpenSearch cluster.
- PS: it is possible to modify the `max_shards_per_node` for an OpenSearch cluster, but having the flexibility when using Langchain is also necessary (+ in our case number of documents per tenant is quite low, so one shard is more than enough).

### Pull request made for this : 
- Already made a simple PR to allow for this modification : 
https://github.com/langchain-ai/langchainjs/pull/4372

**Comment by jacoblee93** [comment]
PR merged, will be live in the next community release!
