### ISSUE TITLE
WebPDFLoader issue - `No PDFJS.workerSrc specified`

### ISSUE THREAD

**Issue by shizheng-rlfresh** [langchain-ai/langchainjs#4383]
I am trying to run the `WebPDFLoader` [example](https://js.langchain.com/docs/integrations/document_loaders/web_loaders/pdf) using `pdf-parse`, and I encountered an issue in the browser:
```bash
Uncaught (in promise) Error: No PDFJS.workerSrc specified
    at getWorkerSrc (pdf-BRXZUBMI.js?v=065e5d97:48456:23)
    at PDFWorker2.PDFWorker_initialize [as _initialize] (pdf-BRXZUBMI.js?v=065e5d97:48516:38)
    at new PDFWorker2 (pdf-BRXZUBMI.js?v=065e5d97:48494:22)
    at getDocument (pdf-BRXZUBMI.js?v=065e5d97:47898:72)
    at WebPDFLoader.load (langchain_document_loaders_web_pdf.js?v=065e5d97:62:29)
    at async test (vectorstore.js:9:19)
```
I don't see anything using LangChainJS complained about this issue, and it seems as an issue of `pdf-parse`? Do you have any recommendation resolving this issue? THANKS!

Note: I am also using `SvelteKit` for this exercise.

**Comment by davkorss** [comment]
I solved it this way

```sh
npm install pdfjs-dist --save
```

```js
import { WebPDFLoader } from "langchain/document_loaders/web/pdf"

const pdfjs = await import("pdfjs-dist/legacy/build/pdf.min.mjs")
const pdfjsWorker = await import("pdfjs-dist/legacy/build/pdf.worker.min.mjs")
pdfjs.GlobalWorkerOptions.workerSrc = pdfjsWorker

const pdfResponse = await fetch(pdfUrl)
const pdfBlob = await pdfResponse.blob()
const pdfLoader = new WebPDFLoader(pdfBlob, {
    parsedItemSeparator: "",
    pdfjs: () => pdfjs
})
```

may not be the best solution, but it works as long as a better one comes along.

**Comment by jacoblee93** [comment]
Thanks @davkorss - I've mostly tested this in Next.js environments. Would be worth documenting at any rate if something like this were required in the browser.

**Comment by shizheng-rlfresh** [comment]
Thanks @davkorss! It works for me!
