### ISSUE TITLE
Trying to create a basic PDFLoader in Deno fails with

### ISSUE THREAD

**Issue by mcgear** [langchain-ai/langchainjs#4386]
I am trying to use PDFLoader from a test in DenoJS, to start getting a feel for it, but am stuck almos immediately.

Getting the following error when running the test
```
C:\Users\micha_8ygdgy8\Fathym\OpenSource\fathym-deno\everything-as-code>deno task test
Task test deno test -A --unstable-kv --allow-env .env tests/tests.ts --coverage=cov
Check file:///C:/Users/micha_8ygdgy8/Fathym/OpenSource/fathym-deno/everything-as-code/tests/tests.ts
error: Uncaught Error: Unable to load C:\Users\micha_8ygdgy8\AppData\Local\deno\npm\registry.npmjs.org\langchain\0.1.17\src\types\pdf-parse.d.ts: The system cannot find the path specified. (os error 3)
    at Object.getSourceFile (ext:deno_tsc/99_main_compiler.js:575:28)
    at findSourceFileWorker (ext:deno_tsc/00_typescript.js:121195:25)
    at findSourceFile (ext:deno_tsc/00_typescript.js:121115:22)
    at ext:deno_tsc/00_typescript.js:121064:24
    at getSourceFileFromReferenceWorker (ext:deno_tsc/00_typescript.js:121033:28)
    at processSourceFile (ext:deno_tsc/00_typescript.js:121062:7)
    at ext:deno_tsc/00_typescript.js:121334:9
    at forEach (ext:deno_tsc/00_typescript.js:55:24)
    at processReferencedFiles (ext:deno_tsc/00_typescript.js:121333:7)
    at findSourceFileWorker (ext:deno_tsc/00_typescript.js:121244:11)
```

Test is here:
https://github.com/fathym-deno/everything-as-code/blob/feature/thinky/tests/workshop/bench.ts

Dependencies defined here:
https://github.com/fathym-deno/everything-as-code/blob/feature/thinky/tests/test.deps.ts

Trying to import pdf-parse instead of npm install (it fails even if i run `npm install pdf-parse`):
import "npm:pdf-parse";

How can i get this working in deno?

**Comment by jacoblee93** [comment]
I had success in a Deno notebook like this:

```ts
// Peer dependency
import * as parse from "pdf-parse";
import { PDFLoader } from "langchain/document_loaders/fs/pdf";

const loader = new PDFLoader("./static/docs/MachineLearning-Lecture01.pdf");

const rawCS229Docs = await loader.load();
```

https://github.com/jacoblee93/dlai-langchainjs/blob/main/02_loading_and_preparing_data.ipynb

Where my import map in `deno.json` looked like this:

https://github.com/jacoblee93/dlai-langchainjs/blob/main/deno.json

Could you try that exact syntax and let me know?

**Comment by mcgear** [comment]
I tried that "exact" code... The only difference i think is that the PDFLoader is used within a test (not sure if maybe that is the issue?). But i really need it working in a test first.

I am on Deno version: Deno 1.40.4

I updated my commits so that my code is reflected in the repos i provided:
https://github.com/fathym-deno/everything-as-code/blob/feature/thinky/deno.jsonc
https://github.com/fathym-deno/everything-as-code/blob/feature/thinky/tests/workshop/bench.ts

**Comment by mcgear** [comment]
I did try something with a direct call, outside of a test, and i get an error about not finding the file... so that is promising as it does get past the issue with not resolving pdf-parse

**Comment by mcgear** [comment]
Just pushed a fix to bench direct, and it does work outside of the deno test

**Comment by mcgear** [comment]
deno run -A ./tests/workshop/bench-direct.ts

**Comment by mcgear** [comment]
Working to bring the communities together, i added a bug in deno for this as well:
https://github.com/denoland/deno/issues/22399

**Comment by jacoblee93** [comment]
Thank you for diving in here! Will keep an eye on that issue.

**Comment by mcgear** [comment]
Thank you for the help. I'll see if the code you provided works from a Deno fresh api tomorrow, at least then i can move forward, and if it doesn't work there, then we'll have some more knowledge to go by.

**Comment by mcgear** [comment]
I wanted to provide a little more information as we work through this. I wanted to try and remove the importMaps for deno, in order to be able to follow the needs for a library and was able to trim down the code so that there were no import maps and just the following:
```
import * as parse from "npm:pdf-parse";
import { PDFLoader } from "npm:langchain/document_loaders/fs/pdf";

const loader = new PDFLoader("./training/azure/data-explorer/azure-data-explorer.pdf", {
  splitPages: false,
});
    
const docs = await loader.load();

console.log(docs);
```
That seems to work just fine when run as a deno run command, but not in a test. Just trying to help us remove some variables from the possible issue. The same within a test fails:
```
import * as parse from "npm:pdf-parse";
import { PDFLoader } from "npm:langchain/document_loaders/fs/pdf";

Deno.test('Workshop Bench', async (t) => {
//   const model = new AzureChatOpenAI({
//     modelName: 'gpt-4',
//     temperature: 0.7,
//     // maxTokens: 1000,
//     maxRetries: 5,
//     verbose: true,
//   });

  await t.step('Invoke Test', async () => {
    const loader = new PDFLoader("./training/azure/data-explorer/azure-data-explorer.pdf", {
      splitPages: false,
    });
        
    const docs = await loader.load();
    
    console.log(docs);
  });

  // await awaitAllCallbacks();
});
```
 I did try to move the test code out of a step and into the root test, and that still failed.

**Comment by mcgear** [comment]
Sorry for letting this go stale, but i finally got back into some more RAG stuff that i am trying to test... And can confirm that i am still getting this issue.

**Comment by jacoblee93** [comment]
Sorry yeah still need to have a look at this!
