### ISSUE TITLE
Why is `id` not a field on the `Document` interfaces?

### ISSUE THREAD

**Issue by omikader** [langchain-ai/langchainjs#4395]
I imagine most vectorstore providers have the concept of a unique identifier to represent a particular vector in the database. Given that, should that identifier explicitly be part of the definition for [`Document`](https://github.com/langchain-ai/langchainjs/blob/bdf707e2d90508c7ca23d8825c59c449382e663c/langchain-core/src/documents/document.ts), e.g.

```
export interface DocumentInterface<
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  Metadata extends Record<string, any> = Record<string, any>
> {
  // Proposing we add this
  id: string;

  pageContent: string;

  metadata: Metadata;
}
```

This would make manipulating vectors by ID (e.g. update, delete) that were retrieved using the `similaritySearch` methods much simpler because we wouldn't need to index `id` as a separate metadata attribute

```
const results = await pineconeStore.similaritySearch(query, 2);

// Would be great if this worked
await pineconeStore.delete({ ids: results.map((document) => document.id) });

// But instead we have to index the document ID as a separate metadata attribute and do this
await pineconeStore.delete({ id: results.map((document) => document.metadata.id });
```

And in some cases, `id` is autogenerated by Langchain which means it is unavailable on `metadata` making having it available on retrieval more important

Linking this similar issue that was closed before: https://github.com/langchain-ai/langchainjs/issues/2704

**Comment by jacoblee93** [comment]
This has come up a few times - the issue is not every provider implements the concept of an id. We've got plans to refactor things around retrieval though (possibly introducing a new "Indexing" abstraction) and I would be in favor of adding it.

**Comment by omikader** [comment]
Yes, I think this issue is still relevant 🙂

**Comment by jacoblee93** [comment]
We are planning a refactor of the retrieval interfaces after 0.2!
