### ISSUE TITLE
Running eval multiple times to reduce LLM randomness

### ISSUE THREAD

**Issue by davidfant** [langchain-ai/langchainjs#4421]
Not sure where to put this as it's related to both LangChain and LangSmith, but...

I want to run evals (`runOnDataset`) multiple times over my dataset, and see all of those samples as part of one eval (aka I don't want X different eval runs). Ideally the scores in LangSmith would be averaged. For example, I have an eval that passes 3/10 times. If I don't sample, my overall eval result is highly unreliable. Ideally I'd see this as `{evaluator key}: 0.3` in LangSmith

**Comment by davidfant** [comment]
@jacoblee93 I found myself needing this again today. What do you think directionally of this solution?
1. `RunOnDatasetParams`: add option `n` or similar for how many times to run the eval
2. Around https://github.com/langchain-ai/langchainjs/blob/ddc44821b6c1e81c827332cf20468a9a9b19e719/langchain/src/smith/runner_utils.ts#L706, wrap `wrappedRunnable` in `RunnableEach` to run `n` times per sample
3. I don't really get how `runExtractors` works or how it gets its data, but I'm guessing from step 2 it would now get runs with an array of results rather than the result directly
4. Around https://github.com/langchain-ai/langchainjs/blob/ddc44821b6c1e81c827332cf20468a9a9b19e719/langchain/src/smith/runner_utils.ts#L546-L547 make the evaluator run `n` times for each result, and then average the score across those evals

Not sure how much time I'll have, but if you can guide me and point me to how you'd build this, I might be able to take a stab at it

**Comment by jacoblee93** [comment]
CC @hinthornw would this make sense?

**Comment by jacoblee93** [comment]
Ok, I have been told:

```
That's how we first implemented it, but it makes comparison view weird.

I think it makes sense to add if we can unblock the backend /UI for it.
```

I can't promise a timeline on this on their end but it's on their radar!

**Comment by davidfant** [comment]
FYI this is how we currently do it 🙈
![image](https://github.com/langchain-ai/langchainjs/assets/17096641/7a09deb1-457f-46e1-bc81-e62409690301)
