### ISSUE TITLE
TypeError: Invalid state: Writer has been released 

### ISSUE THREAD

**Issue by TommasoBendinelli** [langchain-ai/langchainjs#4429]
Hello I am getting the following error here:

const res = await fetch(`${this.apiUrl}/commits/${repoFullName}/?limit=${limit}&offset=${offset}`, { headers: this._getHeaders() });
(client.cjs)
```
Exception has occurred: TypeError [ERR_INVALID_STATE]: Invalid state: Writer has been released
  at new NodeError (node:internal/errors:405:5)
    at lazyWritableReleasedError (node:internal/webstreams/writablestream:94:19)
    at writableStreamDefaultWriterRelease (node:internal/webstreams/writablestream:998:30)
    at finalize (node:internal/webstreams/readablestream:1280:5)
    at node:internal/webstreams/readablestream:1313:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by TommasoBendinelli** [comment]
I also think you have an issue here:
```
function parseOwnerRepoCommit(identifier) {
    let ownerRepo = identifier;
    let commit;
    if (identifier.includes(":")) {
        [ownerRepo, commit] = identifier.split(":", 1);
    }
    if (!ownerRepo.includes("/")) {
        throw new Error(`Invalid identifier ${identifier}. Identifier must be in the format of 'owner/repo:commit' or 'owner/repo'.`);
    }
    const [owner, repo] = ownerRepo.split("/");
    return [owner, repo, commit];
}
```

identifier.split(":", 1); -> Should be identifier.split(":", 2);

**Comment by bracesproul** [comment]
> I also think you have an issue here:
> 
> ```
> function parseOwnerRepoCommit(identifier) {
>     let ownerRepo = identifier;
>     let commit;
>     if (identifier.includes(":")) {
>         [ownerRepo, commit] = identifier.split(":", 1);
>     }
>     if (!ownerRepo.includes("/")) {
>         throw new Error(`Invalid identifier ${identifier}. Identifier must be in the format of 'owner/repo:commit' or 'owner/repo'.`);
>     }
>     const [owner, repo] = ownerRepo.split("/");
>     return [owner, repo, commit];
> }
> ```
> 
> identifier.split(":", 1); -> Should be identifier.split(":", 2);
> 
> (Though this not solve the previous issue)

Hey, what version of [`langchainhub`](https://www.npmjs.com/package/langchainhub) are you on? The latest version `0.0.8` does do this.

**Comment by TommasoBendinelli** [comment]
@bracesproul  Thanks for the reply. Yes you are right. I have upgrade langchain to latest, and this has been solved. 
However this: Exception has occurred: TypeError [ERR_INVALID_STATE]: Invalid state: Writer has been released is still being triggered. 
One workaround I found is to set global.fetch = require('node-fetch'). But I don't know whether is a proper solution
