### ISSUE TITLE
PDFLoader is not working - Cannot find package 'pdf-parse'

### ISSUE THREAD

**Issue by kulaone** [langchain-ai/langchainjs#445]
When loading the library the PDFLoader won't work unless runing a npm install inside the library. 
This is because the package: "pdf-parse": "^1.1.1", is not found. 

`Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'pdf-parse' imported from /home/runner/LangChain/node_modules/langchain/dist/document_loaders/pdf.js`

Can we add it to the "dependencies" area in package.json?

**Comment by nfcampos** [comment]
Hi, you can fix this by installing `pdf-parse`, by running `npm i pdf-parse` or `yarn add pdf-parse` in your project. pdf-parse is set as a peer dependency because not everyone using langchain needs it.

**Comment by kulaone** [comment]
Hi @nfcampos,
Hi, thanks for your response. I understand that pdf-parse is set as a peer dependency, it would be helpful to have that information documented somewhere. As someone who may not be familiar with all the dependencies required for LangChain, it would be helpful to know what I need to install in order for each part of the library to work properly.

**Comment by nfcampos** [comment]
We're actively working on improving the docs, will make sure to include this, thanks for letting us know

**Comment by MrRoiz** [comment]
Hey I have a similar issue here, but I do have that dependency installed 
`Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'pdf-parse' imported from /var/task/index.js`

It is running inside a lambda container using yarn in a monorepo the package is installed in a package that is used by the parent app of the monorepo. I also tried to install it in the parent app but got the same error, should it be installed globally or something similar?

**Comment by MrRoiz** [comment]
> Hey I have a similar issue here, but I do have that dependency installed `Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'pdf-parse' imported from /var/task/index.js`
> 
> It is running inside a lambda container using yarn in a monorepo the package is installed in a package that is used by the parent app of the monorepo. I also tried to install it in the parent app but got the same error, should it be installed globally or something similar?

Nevermind, i just figured out that it needs to be `^1.1.1` as the main issue said, in the docs it shows a command that install the latest version of `pdf-parse` [here](https://docs.langchain.com/oss/javascript/integrations/document_loaders/file_loaders/pdf#installation)
