### ISSUE TITLE
Workaround due to lack of IN filtering in PgVector?

### ISSUE THREAD

**Issue by gon-martinam** [langchain-ai/langchainjs#4456]
Hi 👋

The chain I want to create is:
I perform a query on an LLM -> I extract some values from the output of the LLM (the output is an array of strings) -> These values will help me filter a VectorDB (specifically PgVector), but I need to perform a search in the VectorDB with the same input query that was passed to the LLM for each value extracted from the output of the LLM (remember that it is an array of strings) as filter for let's say the metadata field "project" -> I have a method that joins together in a specific way the N calls to the VectorDB with M documents and returns a string that will be used as a context for an LLM -> The LLM receives the context and the initial query and outputs an output.

I have thought about using a RunnableSequence. The problem is that I don't know if it is possible to assign the strings within the array extracted from the output of the first call to the LLM as a VectorDB/retriever filter.

Once I have obtained the N responses with M VectorDB documents, I would like to reorder them using the score and keep a maximum of X documents.

I have to do this workaround because the current implementation of PgVector does not allow to filter by metadata by using IN on a list of values.

Thanks in advance 😄

**Comment by gon-martinam** [comment]
@dosu-bot

`VectorDBQAChain` is deprecated. What other approach can I use?

**Comment by gon-martinam** [comment]
@dosu-bot

Is there any way to change `retriever` (`vectordb.asRetriever()`) parameters in runtime? For example, change the filter or any of the values within the filter.

**Comment by gon-martinam** [comment]
@dosu-bot

Can I access a distance/score/similarity value in the returned documents by the retriever if I do retriever.map()?

**Comment by MJDeligan** [comment]
There's a PR to implement this feature: #3745 . @bracesproul has this assigned to himself, maybe this can be completed, so you won't need a workaround. 

_Possible Workaround_: The VercelPostgres vector store integration does have IN-filtering. As far as I can tell there's nothing stopping us from providing a standard pool instance from node-postgres. By installing the `@vercel/postgres` package and doing some "convincing", typescript should allow you to pass a pg Pool as the `pool` parameter in the config. I don't see anything in the implementation of the VercelPostgres vector store that suggests that it wouldn't work with a normal pool connecting to a PGVector database. I tried locally and successfully saved some embeddings to a pgvector db running in docker using the VercelPostgres vector store. This way you could use IN-filtering, although it is of course not ideal long-term, but might help until the implementation for PGVector is merged.

Cheers

**Comment by jacoblee93** [comment]
Merged in #3745
