### ISSUE TITLE
GoogleGenerativeAIError: [400 Bad Request] * BatchEmbedContentsRequest.requests: at most 100 requests can be in one batch

### ISSUE THREAD

**Issue by ajaykrupalk** [langchain-ai/langchainjs#4491]
How do I resolve this error when using Google Gemini Pro along with GithubRepoLoader?

GoogleGenerativeAIError: [400 Bad Request] * BatchEmbedContentsRequest.requests: at most 100 requests can be in one batch

**Comment by ajaykrupalk** [comment]
@dosu-bot these are the changes I implemented yet I am seeing the error:

 const embeddings = new GoogleGenerativeAIEmbeddings({
        modelName: "embedding-001", // 768 dimensions
        taskType: TaskType.RETRIEVAL_DOCUMENT,
        title: "Retrieval Document",
        maxBatchSize: 100
    });

**Comment by RitikSinha** [comment]
I have also faced this issue @ajaykrupalk . I used a little hack to bypass this issue.
I created a processBatch function.
`async function processBatch(batch, i) {
  console.log("processing " + i);

  try {
    // connecting to database
    const sbApiKey = process.env.SB_API_KEY;
    const sbUrl = process.env.SB_URL;
    const client = createClient(sbUrl, sbApiKey);
    const embeddings = new GoogleGenerativeAIEmbeddings({
      modelName: "embedding-001", // 768 dimensions
      taskType: TaskType.RETRIEVAL_DOCUMENT,
      title: "data",
    });
    //vector store
    const vector = await SupabaseVectorStore.fromDocuments(batch, embeddings, {
      client,
      tableName: "documents",
    });
    console.log(vector);
  } catch (err) {
    console.log(err);
  }
}`
then I processed the array by this function
`export const processArray = async (array) => {
  const batchSize = 50;
  const delayInMilliseconds = 60 * 1000; // 1 minute in milliseconds
  for (let i = 0; i < array.length; i += batchSize) {
    const batch = array.slice(i, i + batchSize);

    await processBatch(batch, i);

    if (i + batchSize < array.length) {
      // Delay for 1 minute before processing the next batch
      await new Promise((resolve) => setTimeout(resolve, delayInMilliseconds));
    }
  }
};`
This worked for me.

**Comment by RitikSinha** [comment]
hello @ajaykrupalk, I have also faced this issue. I used a little hack to bypass the issue. I processed the texts in batches. and we hit API every minute for one batch. 

- The code is designed to process an array of items in batches asynchronously.

- ```processArray``` divides the input array into smaller batches and processes each batch using processBatch.

- ```processBatch ```handles the actual processing logic, which includes database operations (connecting, creating clients), generating embeddings, and logging the generated vectors.

- There's also a delay between processing batches to throttle the rate of processing.

- This approach helps manage resource consumption and prevents overwhelming external services like databases or APIs by limiting the number of simultaneous requests.

```
async function processBatch(batch, i) {
  console.log("processing " + i);

  try {
    // connecting to the database
    const sbApiKey = process.env.SB_API_KEY;
    const sbUrl = process.env.SB_URL;
    const client = createClient(sbUrl, sbApiKey);
    const embeddings = new GoogleGenerativeAIEmbeddings({
      modelName: "embedding-001", // 768 dimensions
      taskType: TaskType.RETRIEVAL_DOCUMENT,
      title: "data",
    });
    //vector store
    const vector = await SupabaseVectorStore.fromDocuments(batch, embeddings, {
      client,
      tableName: "documents",
    });
    console.log(vector);
  } catch (err) {
    console.log(err);
  }
}

export const processArray = async (array) => {
  const batchSize = 50;
  const delayInMilliseconds = 60 * 1000; // 1 minute in milliseconds
  for (let i = 0; i < array.length; i += batchSize) {
    const batch = array.slice(i, i + batchSize);

    await processBatch(batch, i);

    if (i + batchSize < array.length) {
      // Delay for 1 minute before processing the next batch
      await new Promise((resolve) => setTimeout(resolve, delayInMilliseconds));
    }
  }
};



```

**Comment by ajaykrupalk** [comment]
Hey @RitikSinha thank you, this will be really helpful.

**Comment by ajaykrupalk** [comment]
This can be fixed using the following code. The below code is used to send 50 documents at a time to the vector store. 

```js
const batchSize = 50;
    const totalDocuments = documents.length;

    for (let i = 0; i < totalDocuments; i += batchSize) {
        const batch = documents.slice(i, i + batchSize);
        await vectorstore.addDocuments(batch);
    }```
