### ISSUE TITLE
PDF document loader (JS) issue - `readFile is not a function`

### ISSUE THREAD

**Issue by knoah23** [langchain-ai/langchainjs#4496]
I am trying to run the `PDFLoader` [[example](https://js.langchain.com/docs/integrations/document_loaders/web_loaders/pdf)] using pdf-parse, and I encountered an issue in the browser:

```
Uncaught (in promise) TypeError: readFile is not a function
  at PDFLoader.load (langchain_document_l…js?v=2ceaa6ca:38:22)
  at async loadAndSplitDoc (ResultPage.jsx:35:17)
```

Going through others who shared similar issues, all i could get from it was that it could be related to `fs` module but i don't know. I'm still relatively new to Javascript and Langchain so this could be a dumb question (sorry in advance if it is)

Here's my code and my file structure for context:

```
const loadAndSplitDoc = async () => {
    const loader = new PDFLoader("doc.pdf");
    const doc = await loader.load();
    console.log(doc);

    const textSplitter = new RecursiveCharacterTextSplitter({
      chunkSize: 1000,
    });
    const docsSummary = await textSplitter.createDocuments([doc]);

    return docsSummary;
  };
```

**Comment by gab1rel** [comment]
@dosu-bot I am having the same issue, when i try the following code inside a "jest" test.

```ts
const loader = new PDFLoader("doc.pdf");
const doc = await loader.load();
```
Here's my jest config:

```js
module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  collectCoverageFrom: [
    'src/**/*.{ts,tsx}',
    '!**/node_modules/**',
    '!**/vendor/**',
  ],
  moduleDirectories: ["node_modules", 'src'],
  moduleFileExtensions: ["ts", "tsx", "js", "jsx", "json", "cjs", "mjs"],
  verbose: true,
  moduleNameMapper: {
    "fs/promises": "<rootDir>/node_modules/fs-extra/lib/fs"
  },
  transform: {}
};
```

Here's how i start the tests : `node --experimental-vm-modules node_modules/jest/bin/jest.js`
