### ISSUE TITLE
Abort when using RunnableSequence

### ISSUE THREAD

**Issue by SergioCarrascosaSanchez** [langchain-ai/langchainjs#4513]
I want to abort the token generation with de AbortController when I call abortController.abort(). I could’t find the way to do it with my current implementation of a RunnableSequence.

```
const model = new ChatOpenAI({…});

const abortController = new AbortController();
model.bind({ signal: abortController.signal });

const chatMessageHistory = new ChatMessageHistory(chatHistory);
const chatHistoryMemory = new BufferMemory({chatHistory: chatMessageHistory,…})

const promptCustomTemplate = ChatPromptTemplate.fromMessages([…])

const newChain = new ConversationChain({
        memory: chatHistoryMemory,
        prompt: promptCustomTemplate,
        llm: model,
});
const runnableConversation = RunnableSequence.from([
      {
        input: (params: { question: string }) => { return question },
        ainame: () => { return name },
        guidelines: () => { return guidelines },
        personality: () => { return personality },
        context: (params: { question: string }) => { … }
       },
      (chatConversationParams: any) => {
        newchain.invoke(chatConversationParams);
      }
    ]);

await runnableConversation.invoke({
      question: input
 });`
```

**Comment by SergioCarrascosaSanchez** [comment]
@dosu-bot So, there is no way yet to cancel the token generation of a RunnableSequence?

**Comment by andrewnguonly** [comment]
@SergioCarrascosaSanchez, this might be a regression with `ChatOpenAI`, but I'm not 100% sure. I'm also not sure if the `AbortController` is intended to be used for non-streaming invocations.

1. The `ChatOpenAI` non-streaming (i.e. `invoke()`) invocation logic does not implement abort signal handling.
    a. The signal is passed to the method `completionWithRetry()` [here](https://github.com/langchain-ai/langchainjs/blob/main/libs/langchain-openai/src/chat_models.ts#L590).
    b. But the implementation of `completionWithRetry()` doesn't do anything with it (see [here](https://github.com/langchain-ai/langchainjs/blob/main/libs/langchain-openai/src/chat_models.ts#L769)).
1. In contrast, the `ChatAnthropic` class does implement abort signal handling for non-streaming invocation logic.
    a. The signal is passed to the method `completionWithRetry()` [here](https://github.com/langchain-ai/langchainjs/blob/main/libs/langchain-anthropic/src/chat_models.ts#L422).
    b. Inside the implementation of `completionWithRetry()`, the signal is passed to the class's `AsyncCaller` where it's handled in the `callWithOptions()` method (see [here](https://github.com/langchain-ai/langchainjs/blob/main/langchain-core/src/utils/async_caller.ts#L131)).

**Comment by DanielZhui** [comment]
@SergioCarrascosaSanchez  Hello, can you solver it? I encountered the same problem,

**Comment by LeoAnt02** [comment]
+1 
Would love a solution for this 
Currently using a simple invoke can be canceled with a signal (https://js.langchain.com/v0.1/docs/modules/model_io/chat/cancelling_requests/) 

but doesnt work with a `ConversationChain` and `RunnableSequence`
