### ISSUE TITLE
ChatMistralAI has error: Failed to execute 'decode' on 'TextDecoder': The provided value is not of type '(ArrayBuffer or ArrayBufferView)'

### ISSUE THREAD

**Issue by logancyang** [langchain-ai/langchainjs#4526]
Trying to use this ChatMistralAI for streaming from this instruction https://js.langchain.com/docs/integrations/chat/mistral but got error

```
TypeError: Failed to execute 'decode' on 'TextDecoder': The provided value is not of type '(ArrayBuffer or ArrayBufferView)'.
    at MistralClient.eval [as chatStream] 
    at async ChatMistralAI._streamResponseChunks 
    at async ChatMistralAI._streamIterator 
    at async ChatMistralAI.transform 
    at async RunnableBinding.transform 
    at async RunnableSequence._streamIterator 
    at async Object.pull 
```

**Comment by jacoblee93** [comment]
CC @bracesproul

**Comment by bracesproul** [comment]
Hey @logancyang could you provide some more context as to how you got that error? I'm unable to produce when I run the example code exactly. If you could send all the code and your environment information that would be very helpful!

Also just to confirm, you should be running [`@langchain/mistralai`](https://www.npmjs.com/package/@langchain/mistralai) v0.0.7

**Comment by logancyang** [comment]
Hi @bracesproul, thanks for the reply. I've linked the branch above. Trying to add it to my Obsidian plugin alongside other models. If you take a look at the repo you'll see all the other chat models work fine having the same code path for streaming in `runChain`.

The way to reproduce it is to set that branch up locally in Obsidian, pick Mistral AI in the model dropdown and chat with it. 

Or perhaps you can pinpoint the issue just by looking at the code and see why other chat models work this one but not this mistral one https://github.com/logancyang/obsidian-copilot/blob/1668d5801249a7991a203dc842781a7b7dfc9e0f/src/LLMProviders/chainManager.ts#L241

**Comment by bracesproul** [comment]
@logancyang I just did an entire search of the codebase and it doesn't look like `@langchain/mistralai` is installed. I would assume that's your issue.

**Comment by logancyang** [comment]
@bracesproul what do you mean? All packages are in node_modules and not tracked by git. I have `@langchain/mistralai` installed.

**Comment by bracesproul** [comment]
> @bracesproul what do you mean? I have `@langchain/mistralai` installed.
> 
> 
> 
> You can see it in the package.json https://github.com/logancyang/obsidian-copilot/pull/318/files

Maybe I'm not following how this repo works. When I looked in the package.json it wasn't listed, and when I searched for the package there were no instances of it. How are you importing that module?

**Comment by logancyang** [comment]
@bracesproul The link I shared is a PR based on the branch `add-mistralai`, not master, were you looking at this branch?

![Screenshot 2024-02-26 at 9 20 43 PM](https://github.com/langchain-ai/langchainjs/assets/4860545/3c56d2f4-f85d-45a3-b285-a75d438fd5df)

**Comment by bracesproul** [comment]
@logancyang ah no I did not see that. Trying to run the app now but the `dev` script doesn't start a web server at port 3000, and it's not obvious from the readme how to start it locally. Could you:
Provide more context as to where exactly in the codebase this is erroring from
Send me instructions on how to setup the app locally

**Comment by logancyang** [comment]
@bracesproul It's described in the dev setup section here: https://github.com/logancyang/obsidian-copilot/blob/master/CONTRIBUTING.md#how-to-set-up-dev-environment

Make sure you are on the correct branch before running `npm run dev`

After that you should be able to see the plugin under your community plugin in Obsidian's settings.
<img width="1178" alt="SCR-20240227-qvcd" src="https://github.com/langchain-ai/langchainjs/assets/4860545/36f777ec-9198-488f-9be9-a1d9b1fc9f10">

And you should be able to see the Mistral API key section collapsed below OpenAI and Google API. Put in a Mistral API key, 
<img width="893" alt="SCR-20240227-qwob" src="https://github.com/langchain-ai/langchainjs/assets/4860545/9eaedf57-3d77-4f22-ad2e-fd0f1d05e116">

and select MistralAI in the Copilot Chat side panel model dropdown menu, start a chat. 
<img width="1016" alt="SCR-20240227-qwps" src="https://github.com/langchain-ai/langchainjs/assets/4860545/73de19fc-4fc7-489e-b859-afad27750b30">
