### ISSUE TITLE
NotFoundError: 404 status code (no body) error, when hosted inference URL is used inside OpenAI

### ISSUE THREAD

**Issue by BakingBrains** [langchain-ai/langchainjs#4542]
```import { OpenAI } from "@langchain/openai";


const model = new OpenAI({
    temperature: 0.9,
    openAIApiKey: "xyz",
    configuration: {
      baseURL: "http://localhost:PORT/v1",
    },
});


const res = await model.call(
  "Tell me a story about a boy"
);
console.log({ res });```


**ERROR facing**

```NotFoundError: 404 status code (no body)
    at APIError.generate (file:///D:/pycharmprojects/API_SERVICES/DUMP/node_modules/openai/error.mjs:49:20)
    at OpenAI.makeStatusError (file:///D:/pycharmprojects/API_SERVICES/DUMP/node_modules/openai/core.mjs:256:25)
    at OpenAI.makeRequest (file:///D:/pycharmprojects/API_SERVICES/DUMP/node_modules/openai/core.mjs:299:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///D:/pycharmprojects/API_SERVICES/DUMP/node_modules/@langchain/openai/dist/llms.js:472:29
    at async RetryOperation._fn (D:\pycharmprojects\API_SERVICES\DUMP\node_modules\p-retry\index.js:50:12)```


Any suggestions here?

Thank you

**Comment by BakingBrains** [comment]
I am using huggingface text-generation inference endpoints. so the URL is "http://x.x.x.x:PORT/v1"

**Comment by jesshermes14-art** [comment]
https://api.thebitcoincompany.com/auth/auth47/verify&e=1769528347&r=https://api.thebitcoincompany.com/auth/auth47/verifyba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015add80d5857c298852c4085476461e4d346475e5d9a31bea7cbe7615d0363c19c0a620d175ae672d0c36e8f2e54ce306ad661c0c7b7e70dfa5db725bda9bbcb581de70cd48aee1b9390e831dec8b918de9211eb06f28497a43700025d9308dfb30f40854764614085476461abc620d175aauth47://5a52d6ac863be940a72a4a70c8d8de2008e663f3045011c539b9b8dbb8b0fa76?c=https://api.thebitcoincompany.com/auth/auth47/verify&e=1769528347&r=https://api.thebitcoincompany.com/auth/auth47/verifybc1qntzc8a54vquevd5re943yq2xre8cccssnhg0wtba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015add80d5857c298852c4085476461e4d346475e5d9a31bea7cbe7615d0363c19c0a620d175ae672d0c36e8f2e54ce306ad661c0c7b7e70dfa5db725bda9bbcb581de70cd48aee1b9390e831dec8b918de9211eb06f28497a43700025d9308dfb30f40854764614085476461abc620d175ae672d0c36e8f2e54ce306ad661c0c7b7e70dfa5db725bda9bbcb581dbitcoin:BC1Q0WU0TQP2U3RTUNJL0H0RSL9PVF86ACY6SEP63ST0LP7LGG67YKZQEQ89PN

<img width="720" height="1604" alt="Image" src="https://github.com/user-attachments/assets/648d0ec8-a916-4dc7-8200-15555d5ae43d" />
