### ISSUE TITLE
How to use JSON MODE from OpenAI in Python

### ISSUE THREAD

**Issue by jung0072** [langchain-ai/langchainjs#4555]
I'm aware that in JS you can bind chain call with "response_format" to get JSON type from openAI. But I couldn't find anything about python. Can somebody give an example code that does the trick please?

**Comment by jung0072** [comment]
Hey bot thanks for the answer but what you suggested is using openAI library not LangChain library.

**Comment by gpminsuk** [comment]
This worked for me
```
    chat_openai = ChatOpenAI(
        model="gpt-4-0125-preview",
        model_kwargs={"response_format": {"type": "json_object"}},
    )
```

**Comment by andrewnguonly** [comment]
@jung0072, here are two pages from LangChain's Python documentation that may be helpful:

1. [Function Calling](https://python.langchain.com/docs/modules/model_io/chat/function_calling): This page shows how to bind functions to a model, which is needed to retrieve structured responses from OpenAI (i.e. JSON mode).
2. [OpenAI Tools > JsonOutputToolsParser](https://python.langchain.com/docs/modules/model_io/output_parsers/types/openai_tools#jsonoutputtoolsparser): This page shows a full example in Python of how to retrieve structured responses from OpenAI.

To clarify, this question may be more appropriate for [LangChain's Python repository](https://github.com/langchain-ai/langchain).

**Comment by jacoblee93** [comment]
Thanks all!
