### ISSUE TITLE
vLLM Compatibility

### ISSUE THREAD

**Issue by PeytonCleveland** [langchain-ai/langchainjs#4557]
Our team deploys vLLM servers on AWS and we make use of the OpenAI compatible API. Looking through the Python docs I see this is supported but can't seem to find it in the Js docs: https://python.langchain.com/docs/integrations/llms/vllm

I also didn't see anything on NPM. Can someone confirm this doesn't exist yet for the langchainjs? If it doesn't our team would be interested in contributing to make it happen, so I'd appreciate some pointers on how to tackle it as well. Thanks!

**Comment by ajainghub** [comment]
@dosu-bot
Is this vLLM support/compatibility available now? Any ongoing projects? I could not find much details. 
Mainly looking for nodejs/typescript for https://python.langchain.com/docs/integrations/chat/vllm/
