### ISSUE TITLE
OpenAiEmbeddings not able to use Open ai credentials, only accept Azure

### ISSUE THREAD

**Issue by GitQuist** [langchain-ai/langchainjs#4563]
I'm receiving this error when trying to use my OpenAi api key with the OpenAiEmbeddings class.

I followed the example for Prisma implementation in the docs: https://js.langchain.com/docs/integrations/vectorstores/prisma

Error:
```
⨯ node_modules/@langchain/openai/dist/embeddings.js (143:22) @ new OpenAIEmbeddings
 ⨯ Error: Azure OpenAI API instance name not found
```

Code:
```
import { PrismaVectorStore } from "@langchain/community/vectorstores/prisma";
import { OpenAIEmbeddings } from "@langchain/openai";
import prisma from "@/lib/prisma";
import { Prisma, Embeddings } from "@prisma/client";

export const testEmbeddings = async () => {
  // Use the `withModel` method to get proper type hints for `metadata` field:
  const vectorStore = PrismaVectorStore.withModel<Embeddings>(prisma).create(
    new OpenAIEmbeddings({
      openAIApiKey: process.env.OPENAI_API_KEY,
      modelName: "text-embedding-3-large",
    }),
    {
      prisma: Prisma,
      tableName: "Embeddings",
      vectorColumnName: "vector",
      columns: {
        id: PrismaVectorStore.IdColumn,
        content: PrismaVectorStore.ContentColumn,
      },
    },
  );

  const texts = boverketData.Resources.flatMap((resource) =>
    JSON.stringify(resource),
  );

  await vectorStore.addModels(
    await prisma.$transaction(
      texts.map((category) =>
        prisma.embeddings.create({ data: { content: category } }),
      ),
    ),
  );

  const resultOne = await vectorStore.similaritySearch("Fasadskruv", 1);

  console.log(resultOne);
};
```

For reference this is a nextjs app so the above if done in a server action. I have no problem when using for example MistralEmbeddings.

Thanks!

**Comment by nicoloboschi** [comment]
@GitQuist is it possible that you're passing empty string `""` to `openAIApiKey` ?

**Comment by GitQuist** [comment]
> @GitQuist is it possible that you're passing empty string `""` to `openAIApiKey` ?

No, it's correct. It just seems as the OpenAiEmbeddings doesn't support OpenAi credentials?

**Comment by jacoblee93** [comment]
Hey sorry you're running into this - is there any way you have `process.env.AZURE_OPENAI_API_KEY` set?

The check in code looks like this:

```ts
    if (this.azureOpenAIApiKey) {
      if (!this.azureOpenAIApiInstanceName && !this.azureOpenAIBasePath) {
        throw new Error("Azure OpenAI API instance name not found");
      }
      if (!this.azureOpenAIApiDeploymentName) {
        throw new Error("Azure OpenAI API deployment name not found");
      }
      if (!this.azureOpenAIApiVersion) {
        throw new Error("Azure OpenAI API version not found");
      }
      apiKey = apiKey ?? "";
    }
```

**Comment by GitQuist** [comment]
> Hey sorry you're running into this - is there any way you have `process.env.AZURE_OPENAI_API_KEY` set?
> 
> The check in code looks like this:
> 
> ```ts
>     if (this.azureOpenAIApiKey) {
>       if (!this.azureOpenAIApiInstanceName && !this.azureOpenAIBasePath) {
>         throw new Error("Azure OpenAI API instance name not found");
>       }
>       if (!this.azureOpenAIApiDeploymentName) {
>         throw new Error("Azure OpenAI API deployment name not found");
>       }
>       if (!this.azureOpenAIApiVersion) {
>         throw new Error("Azure OpenAI API version not found");
>       }
>       apiKey = apiKey ?? "";
>     }
> ```

Ahhh, that actually might be the problem! 

I will test and get back here but sure looks like it since I migrated to using Azure endpoints due to region reasons.

Thanks!
