### ISSUE TITLE
How to import prompts and parsers without warning?

### ISSUE THREAD

**Issue by lukasugar** [langchain-ai/langchainjs#4565]
I'm importing `ChatPromptTemplate` and `StringOutputParser` like this:
```
import { ChatPromptTemplate } from 'langchain/prompts';
import { StringOutputParser } from 'langchain/schema/output_parser';
```
I get this warning:
```
[WARNING]: Importing from "langchain/prompts" is deprecated.
@thenarrative/api:dev: 
@thenarrative/api:dev: Instead, please import from "@langchain/core/prompts".
@thenarrative/api:dev: 
@thenarrative/api:dev: This will be mandatory after the next "langchain" minor version bump to 0.2.
@thenarrative/api:dev: [WARNING]: Importing from "langchain/schema/output_parser" is deprecated.
@thenarrative/api:dev: 
@thenarrative/api:dev: Instead, please import from "@langchain/core/output_parsers".
```

If I change the way I import to:
```
import {ChatPromptTemplate} from '@langchain/core/prompts'
import {StringOutputParser} from '@langchain/core/output_parsers'
```
I get the following error: `Cannot find module '@langchain/core/output_parsers' or its corresponding type declarations.`
<img width="767" alt="image" src="https://github.com/langchain-ai/langchainjs/assets/22435018/dabf7a6f-2fc6-4b4b-a6c1-a4fb35fb8a80">

I've installed langchain with pnpm, my `package.json` looks like this:
```
{
...
"dependencies":{
  "@langchain/openai": "^0.0.15",
  ...
  "langchain": "^0.1.23",
  }
  "overrides": {
    "@langchain/core": "0.1.5"
  },
```

Why can't I import them the "recommended" way?

**Comment by bracesproul** [comment]
hey @lukasugar if you try manually installing it via `npm install @langchain/core` or `yarn add @langchain/core` does this error still persist?

**Comment by lukasugar** [comment]
@bracesproul if inside the `packages.json` I specify both langchain and langchain/core, there're no errors:
```
"langchain": "^0.1.25",
"@langchain/core": "0.1.41",
```

**Comment by bracesproul** [comment]
> @bracesproul if inside the `packages.json` I specify both langchain and langchain/core, there're no errors:
> 
> ```
> "langchain": "^0.1.25",
> "@langchain/core": "0.1.41",
> ```

Nice! I'm going to close this issue now, let me know if there's anything else that's giving you a problem.
