### ISSUE TITLE
Ollama Class Issue: loadSummarizationChain in langchain js doesn't support Ollama class

### ISSUE THREAD

**Issue by pacozaa** [langchain-ai/langchainjs#4567]
The error message is
```
Argument of type 'Ollama' is not assignable to parameter of type 'BaseLanguageModel<any, BaseLanguageModelCallOptions>'.
  Type 'Ollama' is missing the following properties from type 'BaseLanguageModel<any, BaseLanguageModelCallOptions>': CallOptions, _patchConfig
```

**Comment by andrewnguonly** [comment]
@pacozaa, which versions of `langchain`, `@langchain/core`, and `@langchain/community` do you have installed?

I can't reproduce the error with `"@langchain/community": "^0.0.32"` and `"langchain": "^0.1.21"`. I'm able to pass an `Ollama` instance to `loadSummarizationChain()` without any TypeScript error.

**Comment by pacozaa** [comment]
@andrewnguonly  Thank you Andrew, Let me try it!
