### ISSUE TITLE
Chat Models example throws Module not found

### ISSUE THREAD

**Issue by DavidGOrtega** [langchain-ai/langchainjs#4569]
👋 

I'm working in a project that is purely js (no python). 
I have my own LLM and Im implementing the custom interfaces. However testing them with the OpenAI counterpart I have seen that at least [this example](https://js.langchain.com/docs/modules/model_io/chat/quick_start#lcel) is wrong

```js
import { HumanMessage, SystemMessage } from "langchain/chat_models/messages";

const messages = [
  new SystemMessage("You're a helpful assistant"),
  new HumanMessage("What is the purpose of model regularization?"),
];

await chatModel.invoke(messages);
```

```sh
Module not found: Error: Package path ./chat_models/messages is not exported from package EDITEDPATH/node_modules/langchain (see exports field in EDITEDPATH/node_modules/langchain/package.json)
```

**Comment by DavidGOrtega** [comment]
I have traced back that those classes have been moved to `@langchain/core`. Docs might need that change. 

```js
import { HumanMessage, SystemMessage } from '@langchain/core/messages';
```

**Comment by jacoblee93** [comment]
Thanks for flagging!
