### ISSUE TITLE
I would like to add a DallE image API Wrapper to LangChain

### ISSUE THREAD

**Issue by davidfekke** [langchain-ai/langchainjs#4575]
I would like to help by contributing a DallE image API Wrapper to the JavaScript version of this framework. Should I talk to someone at LangChain about becoming a contribute.

**Comment by bracesproul** [comment]
Hey! Yes we would love this. I'd recommend adding it as a tool, look in [this dir](https://github.com/langchain-ai/langchainjs/tree/main/libs/langchain-community/src/tools) for inspiration

**Comment by davidfekke** [comment]
> Hey! Yes we would love this. I'd recommend adding it as a tool, look in [this dir](https://github.com/langchain-ai/langchainjs/tree/main/libs/langchain-community/src/tools) for inspiration

I am planning on using the `Tool` TypeScript interface so it can be used as a tool in the chain.

**Comment by SebastianStehle** [comment]
I don't get this to work. OpenAI always changes my URL and `returnDirect` does not seem to work with toolsAgent.

**Comment by davidfekke** [comment]
SebastianStehle,  Is it possible for to create an example of how you are using the Dall-E tool? I can take a look at this.

**Comment by SebastianStehle** [comment]
For example: https://gist.github.com/SebastianStehle/6f9c79c580fa33a553c1ff1c81ee4fa7

**Comment by davidfekke** [comment]
Thanks, I will take a look at this.

**Comment by davidfekke** [comment]
> For example: https://gist.github.com/SebastianStehle/6f9c79c580fa33a553c1ff1c81ee4fa7

I ran your example locally, and I got the following result:

```json
{
  input: "Create the image of a dog",
  output: "Here is the image of a cute dog sitting in a garden:\n![Dog Image](https://oaidalleapiprodscus.blob.core.windows.net/private/org-tuodfGudlqa04FtBvQQ8m6RA/user-8kd4LSh02iTWZwsew4lGuS6P/img-4bkPnIVGblq0qSZoIGNEIz37.png)",
  __run: undefined,
}
```

I tried to open the image, but I could not download it because it was marked as private.

**Comment by SebastianStehle** [comment]
Yes, because it is not complete. DALL-e adds query parameters which are removed by openai and I also could not find a solution to Bypass open ai

**Comment by davidfekke** [comment]
I will take a look into the stripping issue. In the meantime you might want
to create a new Github issue. I would try to use a workaround right now to
separate the tool invoking from your main chain so you can pass the final
prompt to Dall-e.

**Comment by SebastianStehle** [comment]
I need to use tools. I am not sure if you should actually do something, because it looks like an architectural flaw.
