### ISSUE TITLE
Bedrock not working with Claude 3

### ISSUE THREAD

**Issue by jarib** [langchain-ai/langchainjs#4617]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```js
import { BedrockChat } from '@langchain/community/chat_models/bedrock'

async function main() {
    try {
        const model = new BedrockChat({
            model: 'anthropic.claude-3-sonnet-20240229-v1:0'
        });

        const result = await model.invoke('Tell me a story');
        console.log(result);
    } catch (error) {
        console.error(error);
        process.exit(1);
    }
}

main()
```

### Error Message and Stack Trace (if applicable)

```
Error: Error 400: "claude-3-sonnet-20240229" is not supported on this API. Please use the Messages API instead.
    at BedrockChat._call (file:///Users/user/src/langchain-repro/node_modules/@langchain/community/dist/chat_models/bedrock/web.js:230:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BedrockChat._generate (file:///Users/user/src/langchain-repro/node_modules/@langchain/core/dist/language_models/chat_models.js:347:22)
    at async Promise.allSettled (index 0)
    at async BedrockChat._generateUncached (file:///Users/user/src/langchain-repro/node_modules/@langchain/core/dist/language_models/chat_models.js:110:25)
    at async BedrockChat.invoke (file:///Users/user/src/langchain-repro/node_modules/@langchain/core/dist/language_models/chat_models.js:50:24)
    at async main (file:///Users/user/src/langchain-repro/test.js:9:24)
```

### Description

These two issues from Python also apply to the JS version:

https://github.com/langchain-ai/langchain/issues/18513
https://github.com/langchain-ai/langchain/issues/18514

### System Info

Platform: Mac
Node: v20.11.0
Yarn version: 1.22.19

**Comment by hertzfelt** [comment]
ValidationException: "claude-3-sonnet-20240229" is not supported on this API. Please use the Messages API instead.
   
```
    // Ask Claude for a streaming chat completion given the prompt
    const bedrockResponse = await bedrockClient.send(
      new InvokeModelWithResponseStreamCommand({
        modelId: 'anthropic.claude-3-sonnet-20240229-v1:0',
        contentType: 'application/json',
        accept: 'application/json',
        body: JSON.stringify({
          prompt: experimental_buildAnthropicPrompt(messages),
          max_tokens_to_sample: 300,
```

**Comment by jacoblee93** [comment]
Will patch this tonight! Thanks for flagging.

**Comment by jacoblee93** [comment]
Hey so this is actually going to take me a bit longer as I don't have access to the model on Bedrock :(

Will aim to get it as soon as I can and then work on this.

**Comment by crileyy** [comment]
Looks like it's going to be added soon 👀 https://github.com/run-llama/llama_index/pull/11663

**Comment by jarib** [comment]
It's definitely already available:

```console
$ aws bedrock list-foundation-models --region 'us-east-1' | jq '.modelSummaries[].modelId' | grep claude-3-sonnet

"anthropic.claude-3-sonnet-20240229-v1:0"
```

But yes, you need to apply for access.

**Comment by jacoblee93** [comment]
Finished a PR, will merge and ship shortly!

**Comment by bioshazard** [comment]
Really appreciate the turnaround on this!!!

**Comment by crileyy** [comment]
@jacoblee93 Does your PR also fix this for using claude 3 with the Bedrock client (not the BedrockChat)? `import { Bedrock } from 'langchain/llms/bedrock'`

**Comment by jacoblee93** [comment]
Claude-3 is messages only :( you'll need to use the chat model. It should be pretty interchangeable though?

**Comment by naity2** [comment]
Hi @jacoblee93, I was wondering if `BedrockChat` can be used for chains like LLMChain and ConversationalRetrievalChain, similar to `langchain.llms.Bedrock`. Thank you!
