### ISSUE TITLE
[Agent][createXmlAgent] DynamicStructuredTool Received tool input did not match expected schema

### ISSUE THREAD

**Issue by fvisticot** [langchain-ai/langchainjs#4635]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

arg passed to the tool is correct but in String format instead of object.

{
  "to": "test@test.com",
  "subject": "je vais bien",
  "body": ""
}

```
const agent = await createXmlAgent({
            llm: this.llm,
            tools: this.tools,
            prompt: this.prompt,
        });

        const agentExecutor = new AgentExecutor({
            agent,
            tools: this.tools,
            returnIntermediateSteps: true,
            verbose: false
        });

        const result = await agentExecutor.invoke({
            input: question,
            chat_history: this.chatMessageHistory
        });
```

```
const emailTool = new DynamicStructuredTool({
    name: "EmailService",
    description:
        "Used to send email to user. to is user email, subject is email subject, body is email boday",
    schema: z.object({
        to: z.string().describe("to is email destination"),
        subject: z.string().describe("subject is email title"),
        body: z.string().describe("body is email body"),
    }),
    func: async ({to, subject, body}) => {
        console.log(`Email params: ${to}, ${subject}`);
        await sendEmail(to, subject, body);
        return "OK"
    }
});
```

### Error Message and Stack Trace (if applicable)

{
  "issues": [
    {
      "code": "invalid_type",
      "expected": "object",
      "received": "string",
      "path": [],
      "message": "Expected object, received string"
    }
  ],
  "name": "ZodError"
}

### Description

arg passed to the tool is correct but in String format instead of object.

### System Info

0.1.22

**Comment by fvisticot** [comment]
The automatic answer is not correct.
I can not have a question with this format:
Any other advice ?


```
const question = {
    to: "test@test.com",
    subject: "je vais bien",
    body: ""
};
```

**Comment by mnofrizal** [comment]
any update ? i got same error
