### ISSUE TITLE
Errors when loading @langchain/core/messages in a typescript ES module

### ISSUE THREAD

**Issue by marc-weber1** [langchain-ai/langchainjs#4645]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```typescript
import { BaseMessage, ChatMessage } from '@langchain/core/messages';
```

tsconfig:
```json
{
	"compilerOptions": {
		"module": "Node16",
		"target": "ES2022",
		"outDir": "out",
		"lib": [
			"ES2022",
			"dom"
		],
		"sourceMap": true,
		"rootDir": "src",
		"strict": true
	}
}
```

### Error Message and Stack Trace (if applicable)

@langchain/core/messages.d.cts:
The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("./dist/messages/index.js")' call instead.

### Description

Trying to make a VSCode extension, but can't with the required settings and langchain's cjs dependencies.

### System Info

langchain@0.1.25 | MIT | deps: 18 | versions: 255
Typescript bindings for langchain
https://github.com/langchain-ai/langchainjs/tree/main/langchain/

keywords: llm, ai, gpt3, chain, prompt, prompt engineering, chatgpt, machine learning, ml, openai, embeddings, vectorstores

dist
.tarball: https://registry.npmjs.org/langchain/-/langchain-0.1.25.tgz
.shasum: afd0faf2eadfb5e6e1d57bb3bbc5731918e62135
.integrity: sha512-sfEChvr4H2CklHdSByNBbytwBrFhgtA5kPOnwcBrxuXGg1iOaTzhVxQA0QcNcQucI3hZrsNbZjxGp+Can1ooZQ==
.unpackedSize: 4.0 MB

dependencies:
@anthropic-ai/sdk: ^0.9.1     js-tiktoken: ^1.0.7           openapi-types: ^12.1.3
@langchain/community: ~0.0.33 js-yaml: ^4.1.0               p-retry: 4
@langchain/core: ~0.1.36      jsonpointer: ^5.0.1           uuid: ^9.0.0
@langchain/openai: ~0.0.14    langchainhub: ~0.0.8          yaml: ^2.2.1
binary-extensions: ^2.2.0     langsmith: ~0.1.7             zod-to-json-schema: ^3.22.3       
expr-eval: ^2.0.2             ml-distance: ^4.0.0           zod: ^3.22.4

maintainers:
- nfcampos <nuno@boringbits.io>
- jacoblee93 <jacoblee93@gmail.com>
- davidduong <david@duong.cz>
- hwchase17 <hw.chase.17@gmail.com>
- basproul <braceasproul@gmail.com>

dist-tags:
latest: 0.1.25     next: 0.1.19-rc.2

published 5 days ago by basproul <braceasproul@gmail.com>

Windows 10 Pro
npm v10.2.4
NodeJS v20.11.1

**Comment by jacoblee93** [comment]
Hey @marc-weber1, can you share your `package.json` file too?

**Comment by marc-weber1** [comment]
https://github.com/marc-weber1/langchain-vscode/blob/master/package.json

entire source code is on github, master branch as is should reproduce the error, may need vscode installed

**Comment by jacoblee93** [comment]
Sat`"type": "module"` in package JSON or use `require`

https://blog.logrocket.com/commonjs-vs-es-modules-node-js/

**Comment by marc-weber1** [comment]
BaseMessage and ChatMessage are types, and I can't convert a VSCode extension to an ES6 module; How am I supposed to import types with a require statement?

**Comment by marc-weber1** [comment]
https://github.com/microsoft/vscode/issues/201935 - looks like they will fix this soon, but maybe include some documentation about either CommonJS not being supported or how to use it

**Comment by jacoblee93** [comment]
Oh hmm interesting. How do people usually require types in CJS? Haven't worked with it in a long time.

Would something like this work?

```ts
const { ChatPromptTemplate, LengthBasedExampleSelectorInput } = await import("langchain/prompts");
```
