### ISSUE TITLE
LlamaCpp Not available for some models 

### ISSUE THREAD

**Issue by kanghohyeong** [langchain-ai/langchainjs#4674]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

The following code : 
```typescript 
const squeeze = async (text: string): Promise<string> => {
  const llm = await import('@langchain/community/chat_models/llama_cpp')
  const model = new llm.ChatLlamaCpp({ modelPath: modelPath })
  // const llm = await import('@langchain/community/llms/llama_cpp')
  // const model = new llm.LlamaCpp({ modelPath: modelPath })
  console.log('model ok')
  const response = await model.invoke([
    new HumanMessage({ content: `please summary this : ${text}` })
  ])
  console.log(response)
  return response.content as string
}
```

### Error Message and Stack Trace (if applicable)

There is no error message. Just terminate process after this log.
```
llama_new_context_with_model: n_ctx      = 4096
llama_new_context_with_model: freq_base  = 10000.0
llama_new_context_with_model: freq_scale = 1
ggml_metal_init: allocating
ggml_metal_init: found device: Apple M1
ggml_metal_init: picking default device: Apple M1
ggml_metal_init: default.metallib not found, loading from source
ggml_metal_init: GGML_METAL_PATH_RESOURCES = nil
ggml_metal_init: loading '~~'
ggml_metal_init: GPU name:   Apple M1
ggml_metal_init: GPU family: MTLGPUFamilyApple7  (1007)
ggml_metal_init: GPU family: MTLGPUFamilyCommon3 (3003)
ggml_metal_init: GPU family: MTLGPUFamilyMetal3  (5001)
ggml_metal_init: simdgroup reduction support   = true
ggml_metal_init: simdgroup matrix mul. support = true
ggml_metal_init: hasUnifiedMemory              = true
ggml_metal_init: recommendedMaxWorkingSetSize  = 11453.25 MB
```

I try debug and interrupt point is here
LlamaCpp > constructor
```javascript
this.maxTokens = inputs?.maxTokens;
this.temperature = inputs?.temperature;
this.topK = inputs?.topK;
this.topP = inputs?.topP;
this.trimWhitespaceSuffix = inputs?.trimWhitespaceSuffix;
this._model = createLlamaModel(inputs);
this._context = createLlamaContext(this._model, inputs); // << here
this._session = null;
```

### Description

I'm trying to use langchain community > llamacpp
when i use `mistral-7b.Q4_K_M.gguf` it works well.
However i try to use `llama-2-7b.Q4_K_M.gguf` , it didn't work.
There is no error message, just interrupted.
Same as chat_model and llm

It is not issue of `node-llama-cpp` library because this works well. `npx --no node-llama-cpp chat --model ./resources/llama-2-7b.Q4_K_M.gguf`

### System Info

"@langchain/community": "^0.0.34",
"langchain": "^0.1.25",
"node-llama-cpp": "^2.8.8"

mac m1
node : v21.6.2

**Comment by kanghohyeong** [comment]
Oh,, As rubber duck debugging,, maybe it is issue of `node-llama-cpp` library. I try debugging more

**Comment by jacoblee93** [comment]
Thanks for the report. I will try to give it a look as soon as I can! Sorry you're running into it.

**Comment by kanghohyeong** [comment]
My application is using electron, and it seems to be a problem between electron and node-llama-cpp. I will close the issue. Thank you.
