### ISSUE TITLE
0.0 to 0.1 Migration Script fails to run, logs are polluted with import warnings

### ISSUE THREAD

**Issue by Crizzooo** [langchain-ai/langchainjs#4676]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```typescript

import { updateEntrypointsFrom0_0_xTo0_1_x } from '@langchain/scripts/migrations';

const migrateLangchain = async () => {
  await updateEntrypointsFrom0_0_xTo0_1_x({
    localLangChainPath: "my local path to a cloned langchainjs repo",
    codePath: 'local path to our yarn workspace',
  });
};
```

### Error Message and Stack Trace (if applicable)

node:internal/modules/cjs/loader:1078
  throw err;
  ^

Error: Cannot find module './dist/migrations/index.cjs'
Require stack:
- /Users/crizzo/Titan/titan-api/node_modules/@langchain/scripts/migrations.cjs
- /Users/crizzo/Titan/titan-api/packages/legacy/dist/bin/tools/random-c.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Hook.Module.require (/Users/crizzo/Titan/titan-api/node_modules/dd-trace/packages/dd-trace/src/ritm.js:51:29)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/Users/crizzo/Titan/titan-api/node_modules/@langchain/scripts/migrations.cjs:1:18)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at Hook.Module.require (/Users/crizzo/Titan/titan-api/node_modules/dd-trace/packages/dd-trace/src/ritm.js:72:33)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/Users/crizzo/Titan/titan-api/packages/legacy/src/tools/random-c.ts:1177:51)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/crizzo/Titan/titan-api/node_modules/@langchain/scripts/migrations.cjs',
    '/Users/crizzo/Titan/titan-api/packages/legacy/dist/bin/tools/random-c.js'
  ]
}

### Description

Ive installed `langchain/scripts`.

Our repo is filled with warnings on app run such as 

```
[WARNING]: Importing from "langchain/tools/google_custom_search" is deprecated.

Instead, please add the "@langchain/community" package to your project with e.g.

    $ npm install @langchain/community

and import from "@langchain/community/tools/google_custom_search".
```

However, we do not import google_custom_search in our own code.

I was hoping Id be able to run the migration script to resolve these issues, but the script fails to run with the above stack trace.

We recently upgraded from ""langchain": "=0.0.96" to "0.1.25", and were overwhelmed with above warnings.

These also exist in package.json:

 "@langchain/community": "^0.0.35",
    "@langchain/core": "^0.1.43",
    "@langchain/openai": "^0.0.18",
    "@langchain/scripts": "^0.0.5"
    
Any help would be appreciated to:

   A) Get the migration script to run
   or
   B) Fix all warnings, even if we arent requiring those paths ourselves

## Other Thoughts

The error message says it cannot find `./dist/migrations/index.cjs`. I opened up that folder, and I dont see this file existing.

Here is a `pwd` and an `ls` of the dist folder inside langchain/scripts.

```
  migrations git:(chris/update-langchain-deps) ✗ pwd
/Users/crizzo/Titan/titan-api/node_modules/@langchain/scripts/dist/migrations
```

```
 migrations git:(chris/update-langchain-deps) ✗ ls -la
total 48
drwxr-xr-x   6 crizzo  staff   192 Mar  8 14:23 .
drwxr-xr-x  21 crizzo  staff   672 Mar  8 16:17 ..
-rw-r--r--   1 crizzo  staff  1596 Mar  8 14:23 0_1.d.ts
-rw-r--r--   1 crizzo  staff  9805 Mar  8 14:23 0_1.js
-rw-r--r--   1 crizzo  staff    26 Mar  8 14:23 index.d.ts
-rw-r--r--   1 crizzo  staff    26 Mar  8 14:23 index.js
```

As the .cjs file doesn't exist, I felt this would be worthy of an issue and is possibly an issue on the package building side?

### System Info

└─ langchain@npm:0.1.25
   ├─ Instances: 1
   ├─ Version: 0.1.25
   │
   └─ Dependencies
      ├─ @anthropic-ai/sdk@npm:^0.9.1 → npm:0.9.1
      ├─ @langchain/community@npm:~0.0.33 → npm:0.0.34
      ├─ @langchain/core@npm:~0.1.36 → npm:0.1.40
      ├─ @langchain/openai@npm:~0.0.14 → npm:0.0.14
      ├─ binary-extensions@npm:^2.2.0 → npm:2.2.0
      ├─ expr-eval@npm:^2.0.2 → npm:2.0.2
      ├─ js-tiktoken@npm:^1.0.7 → npm:1.0.7
      ├─ js-yaml@npm:^4.1.0 → npm:4.1.0
      ├─ jsonpointer@npm:^5.0.1 → npm:5.0.1
      ├─ langchainhub@npm:~0.0.8 → npm:0.0.8
      ├─ langsmith@npm:~0.1.7 → npm:0.1.8
      ├─ ml-distance@npm:^4.0.0 → npm:4.0.0
      ├─ openapi-types@npm:^12.1.3 → npm:12.1.3
      ├─ p-retry@npm:4 → npm:4.6.2
      ├─ uuid@npm:^9.0.0 → npm:9.0.0
      ├─ yaml@npm:^2.2.1 → npm:2.2.1
      ├─ zod-to-json-schema@npm:^3.22.3 → npm:3.22.4
      └─ zod@npm:^3.22.4 → npm:3.22.4
      
      
      Node: v18.15.0

**Comment by Crizzooo** [comment]
Confirming all packages were removed, reinstalled, and the same issue persists.

**Comment by jacoblee93** [comment]
CC @bracesproul can you look into this?

**Comment by bracesproul** [comment]
Hey @Crizzooo sorry about that! I believe I've identified a fix [here](https://github.com/langchain-ai/langchainjs/pull/4679). If you update to `0.0.6` it should work.

**Comment by bracesproul** [comment]
No these will only fix migration warnings from your codebase. Could you send me a list of langchain imports which have "nested" import warnings?
