### ISSUE TITLE
 Bedrock not working with Mistal (mistral.mixtral-8x7b-instruct-v0:1)

### ISSUE THREAD

**Issue by fvisticot** [langchain-ai/langchainjs#4683]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```
return new Bedrock({
                    verbose: false,
                    model: 'mistral.mixtral-8x7b-instruct-v0:1',
                    region: 'us-west-2',
                    temperature: 0,
                    stop_sequences: [],
                    top_k: 10,
                    top_p: 0.5,
                    max_tokens: 4000,
                });
```

### Error Message and Stack Trace (if applicable)

Error: Unknown model: 'mistral.mixtral-8x7b-instruct-v0:1', only these are supported: ai21,anthropic,amazon,cohere,meta

### Description

I tried to use mistral model with Bedrock

### System Info

"langchain": "^0.1.25",

**Comment by jacoblee93** [comment]
Yeah, need to fix this... Thanks for flagging!

**Comment by jacoblee93** [comment]
Should be fixed!
