### ISSUE TITLE
StringOutputParser does not handle non-string BaseMessage content

### ISSUE THREAD

**Issue by afirstenberg** [langchain-ai/langchainjs#4695]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

The following code is based on code in https://js.langchain.com/docs/expression_language/get_started but expanded with comments and using `ChatGoogle` instead of OpenAI.

```javascript
import { ChatGoogle } from "@langchain/google-gauth";
import { ChatPromptTemplate } from "@langchain/core/prompts";
import { StringOutputParser } from "@langchain/core/output_parsers";

async function getJoke(topic){
  // Setup the prompt template
  const template = "Tell me a short joke about {topic}.";
  const prompt = ChatPromptTemplate.fromMessages([
    ["human", template],
  ]);

  // Setup our model
  const model = new ChatGoogle();

  // The output of a chat model contains a lot of additional information,
  // so we will need to convert it to a string.
  const outputParser = new StringOutputParser();

  // Create (but don't run) the chain
  const chain = prompt.pipe(model).pipe(outputParser);

  // Run the chain, providing it the values to put into the template.
  const response = await chain.invoke({
    topic,
  });
  return response;
}

console.log(await getJoke("ice cream"));
```

### Error Message and Stack Trace (if applicable)

The output of this code is

```text
[{"type":"text","text":"What do you call an ice cream that's always in trouble?\n\nA"}]
```

(ie - a text block of JSON)

If I remove the output parser from the chain, the output becomes

```text
AIMessageChunk {
  lc_serializable: true,
  lc_kwargs: { content: [ [Object] ], additional_kwargs: {} },
  lc_namespace: [ 'langchain_core', 'messages' ],
  content: [
    {
      type: 'text',
      text: "What do you call an ice cream that's always sad?\n\nA blue moon."
    }
  ],
  name: undefined,
  additional_kwargs: {}
}
```

### Description

Looking at the code for `BaseTransformOutputParser._transform()`, which is the parent of `StringOutputParser`, when it gets a chunk of type BaseMessage it looks at the `content` field.. If `content` is a string, it handles it. If it is of type MessageContentComplex[], it just uses JSON.stringify() to create a string, ignoring what the potential size or elements of the array are.

It looks like the `AIMessageChunk` generated from Google has an array, so it goes through JSON.stringify.

It seems reasonable that we could go through the array and, at least for the text types, turn them into a string.

If there are no objections to making this change - please assign it to me.

### System Info

langchain 0.1.25
@lanchain/core 0.1.44
@lanchain/google-common 0.0.1

**Comment by jacoblee93** [comment]
Should definitely fix - thanks for flagging!

What do we do if there's an image returned though? Probably throw?

**Comment by afirstenberg** [comment]
That's a good question. Throw? Skip? Insert URL if available? Turn it into "[IMG]"?

My gut feeling is that it _shouldn't_ throw, no matter what. It should always return a string of some sort.

I'm leaning towards ignoring non-text MessageContent objects and making it so people can create subclasses that handle it however they want.

(Tho I'm also having trouble figuring out exactly where to make these fixes.)
