### ISSUE TITLE
Anthropic-AI sdk version upgrade for Issue: Unexpected End of JSON input

### ISSUE THREAD

**Issue by sunnyunde-xooa** [langchain-ai/langchainjs#4716]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```js
const llm = new ChatAnthropic({
  modelName: "claude-2",
  anthropicApiKey: "ANTHROPIC_API_KEY",
  clientOptions: {
    baseURL: "https://anthropic.hconeai.com/",
    defaultHeaders: {
      "Helicone-Auth": `Bearer HELICONE_API_KEY`,
    }
  }
});
```

### Error Message and Stack Trace (if applicable)

[3/12/2024 2:58:05 PM] @anthropic-ai/sdk/streaming.js:64 Could not parse message into JSON: 
[3/12/2024 2:58:05 PM] @anthropic-ai/sdk/streaming.js:65 From chunk: [ 'event: content_block_delta' ]
[3/12/2024 2:58:05 PM] dist/tracers/console.cjs:157 [llm/error] [1:chain:LLMChain > 2:llm:ChatAnthropic] [864ms] LLM run errored with error: "Unexpected end of JSON input"

### Description

I am trying to use Helicone with Anthropic as per the documentation mentioned in the Helicone.
Here I am frequently getting this message on further investigation I found that it was the issue of the Anthropic-sdk which has been fixed in the latest version:
Issue link: https://github.com/anthropics/anthropic-sdk-typescript/issues/292

### System Info

- langchain: v1.22.19
- Node Version: v.18.13.0
- @langchain/anthropic: 0.1.5

**Comment by jacoblee93** [comment]
Will patch this today, thanks for the heads up!
