### ISSUE TITLE
`error unhandledRejection: Error [TypeError]`: text.replace is not a function

### ISSUE THREAD

**Issue by DaveOkpare** [langchain-ai/langchainjs#4736]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

import {
  RunnableSequence,
  RunnablePassthrough,
} from "@langchain/core/runnables";
import { StringOutputParser } from "@langchain/core/output_parsers";
import { Configuration, OpenAIApi } from 'openai-edge'
import { Pinecone } from "@pinecone-database/pinecone";
import { PineconeStore } from '@langchain/pinecone'
import { OpenAIEmbeddings, ChatOpenAI } from "@langchain/openai";
import { formatDocumentsAsString } from "langchain/util/document";
import { PromptTemplate } from '@langchain/core/prompts'
import { QA_PROMPT } from '../../config/prompts'

const pinecone = new Pinecone({
          apiKey: PINECONE_API_KEY,
        })
      
  // Set Pinecone index name
  const pineconeIndex = pinecone.Index(PINECONE_INDEX_NAME)

  // Get the vectorstore
  const vectorStore = await PineconeStore.fromExistingIndex(
    new OpenAIEmbeddings(),
    {
      pineconeIndex: pineconeIndex,
            textKey: 'text',
            namespace: PINECONE_NAME_SPACE,
          }
        )

const retreiver = vectorStore.asRetriever()
        const prompt = PromptTemplate.fromTemplate(QA_PROMPT)
        const llm = new ChatOpenAI({ modelName: "gpt-3.5-turbo", temperature: 0 });

        const ragChain = RunnableSequence.from([
              {
                context: retreiver.pipe(formatDocumentsAsString),
                question: new RunnablePassthrough(),
              },
              prompt,
              llm,
              new StringOutputParser(),
            ]);
          

        const response = ragChain.invoke({question})

### Error Message and Stack Trace (if applicable)

- error unhandledRejection: Error [TypeError]: text.replace is not a function
    at OpenAIEmbeddings.embedQuery (file:///workspaces/flow-chatbot/node_modules/@langchain/openai/dist/embeddings.js:203:46)
    at PineconeStore.similaritySearch (file:///workspaces/flow-chatbot/node_modules/@langchain/core/dist/vectorstores.js:104:90)
    at VectorStoreRetriever._getRelevantDocuments (file:///workspaces/flow-chatbot/node_modules/@langchain/core/dist/vectorstores.js:68:33)
    at VectorStoreRetriever.getRelevantDocuments (file:///workspaces/flow-chatbot/node_modules/@langchain/core/dist/retrievers.js:67:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RunnableSequence.invoke (file:///workspaces/flow-chatbot/node_modules/@langchain/core/dist/runnables/base.js:1016:33)
    at async file:///workspaces/flow-chatbot/node_modules/@langchain/core/dist/runnables/base.js:1195:31
    at async Promise.all (index 0)
    at async RunnableMap.invoke (file:///workspaces/flow-chatbot/node_modules/@langchain/core/dist/runnables/base.js:1194:13)
    at async RunnableSequence.invoke (file:///workspaces/flow-chatbot/node_modules/@langchain/core/dist/runnables/base.js:1016:33) {
  digest: undefined
}

### Description

I'm trying to do RAG using LCEL but keep running into this error using all the code examples from the docs. My goal is to also return the source documents and stream.

### System Info

version: '0.1.27',
  type: 'module',
  engines: {
    node: '>=18'
  },
  main: './index.js',
  types: './index.d.ts',
  \

**Comment by jacoblee93** [comment]
The input to `ragChain` in your case there will be passed directly to `retreiver.pipe(formatDocumentsAsString)` and `new RunnablePassthrough()`. Retrievers take string input. Thus, you should invoke your chain like this:

```
    const ragChain = RunnableSequence.from([
          {
            context: retreiver.pipe(formatDocumentsAsString),
            question: new RunnablePassthrough(),
          },
          prompt,
          llm,
          new StringOutputParser(),
        ]);
      

  // No brackets around question
    const response = ragChain.invoke(question);
```

Alternatively, you could update your chain to look like this:

```
    const ragChain = RunnableSequence.from([
          {
            context: RunnableLambda.from((input) => input.question).pipe(retreiver.pipe(formatDocumentsAsString)),
            question: new RunnablePassthrough(),
          },
          prompt,
          llm,
          new StringOutputParser(),
        ]);
      

  // No brackets around question
    const response = ragChain.invoke(question);
```

**Comment by fromatlantis** [comment]
> The input to `ragChain` in your case there will be passed directly to `retreiver.pipe(formatDocumentsAsString)` and `new RunnablePassthrough()`. Retrievers take string input. Thus, you should invoke your chain like this:
> 
> ```
>     const ragChain = RunnableSequence.from([
>           {
>             context: retreiver.pipe(formatDocumentsAsString),
>             question: new RunnablePassthrough(),
>           },
>           prompt,
>           llm,
>           new StringOutputParser(),
>         ]);
>       
> 
>   // No brackets around question
>     const response = ragChain.invoke(question);
> ```
> 
> Alternatively, you could update your chain to look like this:
> 
> ```
>     const ragChain = RunnableSequence.from([
>           RunnableLambda.from((input) => input.question),
>           {
>             context: retreiver.pipe(formatDocumentsAsString),
>             question: new RunnablePassthrough(),
>           },
>           prompt,
>           llm,
>           new StringOutputParser(),
>         ]);
>       
> 
>   // Now you can put it in an object
>     const response = ragChain.invoke({ question });
> ```

How to add chat_history memory? Thanks.

**Comment by emmadao** [comment]
hi
Someone can help me how to add chat history with postgres
Here my code: 
```
const retriever = vectorstore.asRetriever();
   
      const chain = RunnableSequence.from([
        RunnableLambda.from((input) => input.question),
          {
            context: retriever.pipe((docs) => docs[0].pageContent),
            question: new RunnablePassthrough(),
            chat_history: new RunnablePassthrough(), 
          },
          promptTemplate2,
          llm,
          new StringOutputParser(),
      ]);


      const chainWithMessageHistory = new RunnableWithMessageHistory({
        runnable: chain,
        getMessageHistory: async (sessionId) => {
          const chatHistory = new PostgresChatMessageHistory({
            sessionId,
            pool,
          });
          return chatHistory;
        },
        inputMessagesKey: "question",
        historyMessagesKey: "chat_history"
      });

      const chainResult = await chainWithMessageHistory.invoke({
        question: question,
      },
      { configurable: { sessionId: "langchain-test-1" } }
      ); 
```

But the chat_history doesn't work.

**Comment by codeshoel** [comment]
@dosubot Thanks, to anyone who is having the "text.replace is not a function" error, kindly convert the message payload to string(e.g., messageVariable.toString())
