### ISSUE TITLE
Neo4j similaritySearchWithScore crashes on undefined

### ISSUE THREAD

**Issue by faileon** [langchain-ai/langchainjs#4752]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Description

Trying to get similarity results with score like this:
```ts
    const result = await vectorStore.similaritySearchWithScore('What is foo?', 6);
```
Produces the following error in the `removeLuceneChars` function:
> modifiedText = modifiedText.split(char).join(' ');
> TypeError: Cannot read properties of undefined (reading 'split')

The problem is that is trying to process the query, that is not passed from the base class. To my understanding it is not needed. Calling `similaritySearchWithScore` just preprocesses the query into vector and passing it to `similaritySearchVectorWithScore`.

The workaround I implemented currently is creating the vector myself, calling `similaritySearchVectorWithScore` directly and passing empty query:
```ts
const queryVector = await embeddings.embedQuery('What is foo?');
const result = await vectorStore.similaritySearchVectorWithScore(queryVector, 6, '');
```

https://github.com/langchain-ai/langchainjs/blob/37d68a5b1a2ab1039e1459cd6a35c43ae8e3ddd6/libs/langchain-community/src/vectorstores/neo4j_vector.ts#L618

### System Info

pnpm  8.6.2
node 20.10.0
"@langchain/community": "^0.0.37",
 "@langchain/core": "^0.1.45",
 "@langchain/openai": "^0.0.19",
"langchain": "^0.1.27",

**Comment by jacoblee93** [comment]
Thanks for the heads up - @tomasonjo if you're around could you have a quick look? Otherwise I can try later.

**Comment by tomasonjo** [comment]
The lucene query is there for hybrid search. It seems we need to allow null values if it is called directly or just add a single if clause for removing lucene characters if not null. I'm travelling, but maybe @easwee can add a PR
