### ISSUE TITLE
streamEvents from langchain js not working with python back-end

### ISSUE THREAD

**Issue by Blubberblub** [langchain-ai/langchainjs#4779]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

const remoteChain = new RemoteRunnable({
  url: "http://localhost:8000/",
});

const response = await remoteChain.streamEvents(
  {
    "input": "How are you?",
    "chat_history": []
  },
  { version: "v1" }
);

for await (const event of response) {
  const eventType = event.event;
  console.log(eventType);
}

### Error Message and Stack Trace (if applicable)

@langchain_core_runn….js?v=66f463cc:4644 Uncaught (in promise) TypeError: Cannot set properties of undefined (setting '-')
    at Object.add (@langchain_core_runn…?v=66f463cc:4644:14)
    at applyOperation (@langchain_core_runn…?v=66f463cc:4825:52)
    at applyPatch (@langchain_core_runn…?v=66f463cc:4850:18)
    at _RunLog.fromRunLogPatch (@langchain_core_runn…?v=66f463cc:5201:20)
    at RemoteRunnable.streamEvents (@langchain_core_runn…?v=66f463cc:6365:25)
    at async Proxy.sendMessageToServer (Chat.vue:335:24)

### Description

I set up a langserve python back-end that is called from a javascript front-end application. Both are running on localhost for now. Using the streamLog function everything works fine but when using the streamEvents function the back-end generates a response but i get an error when "looping" through the response in the front-end (see code above).

### System Info

JavaScript
LangChain.js==0.1.28
Python
langchain==0.1.12
langserve==0.0.51

**Comment by jacoblee93** [comment]
`streamEvents` isn't supported yet in `RemoteRunnable` - I really need to get that done!

**Comment by Blubberblub** [comment]
@jacoblee93 Thanks for the quick reply, having this would be a huge improvement! Since i am more familiar with python version i probably can't contribute much here, but tell me if there is something i could look into. I will use streamLog for now. How far do you think this feature is on the roadmap?

**Comment by jacoblee93** [comment]
No worries - I've said "this week" for about three weeks now so I don't want to hard commit but I do really want to get it done...

**Comment by jumski** [comment]
@jacoblee93 is regular `stream` supported for js RemoteRunnable? it works only if i call 'strream' directly on the RemoteRunnable, but if i compose it with prompt and call 'stream' on whole chain it downgrades to invoke

**Comment by jacoblee93** [comment]
Yes it should be, sounds like it might be an issue with your chain? Downgrade to a gather + invoke flow is what happens if you have a step blocking the end.

**Comment by Blubberblub** [comment]
Thanks! Working great. Do you by any means know how i can get the run_id from the logs? I want to send feedback data to langsmith but the run_id in the events are allways empty...

**Comment by jacoblee93** [comment]
Oh hmm let me look into it a bit more!
