### ISSUE TITLE
`JsonOutputFunctionsParser` cannot handle irregular json return from Fn Call

### ISSUE THREAD

**Issue by YukiDayDreamer** [langchain-ai/langchainjs#4798]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```javascript
import dotenv from "dotenv";
dotenv.config();

// This is an example from official documentation:
// https://api.js.langchain.com/functions/langchain_chains_openai_functions.createOpenAIFnRunnable.html

import { createOpenAIFnRunnable } from "langchain/chains/openai_functions";
import { ChatOpenAI } from "@langchain/openai";
import { ChatPromptTemplate } from "@langchain/core/prompts";
import { JsonOutputFunctionsParser } from "langchain/output_parsers";

const openAIFunction = {
  name: "get_person_details",
  description: "Get details about a person",
  parameters: {
    title: "Person",
    description: "Identifying information about a person.",
    type: "object",
    properties: {
      name: { title: "Name", description: "The person's name", type: "string" },
      age: { title: "Age", description: "The person's age", type: "integer" },
      fav_food: {
        title: "Fav Food",
        description: "The person's favorite food",
        type: "string",
      },
    },
    required: ["name", "age"],
  },
};

const model = new ChatOpenAI();
const prompt = ChatPromptTemplate.fromMessages([
  ["human", "Human description: {description}"],
]);
const outputParser = new JsonOutputFunctionsParser();

const runnable = createOpenAIFnRunnable({
  functions: [openAIFunction],
  llm: model,
  prompt,
  enforceSingleFunctionUsage: true, // Default is true
  outputParser
});
const response = await runnable.invoke({
  description:
    "My name's John Doe and I'm 30 years old. My favorite kind of food are chocolate chip cookies.",
});

console.log(response);

// { name: 'John Doe', age: 30, fav_food: 'chocolate chip cookies' }

```

### Error Message and Stack Trace (if applicable)

undefined:2
  name: "John Doe",
  ^

SyntaxError: Expected property name or '}' in JSON at position 4
    at JSON.parse (<anonymous>)
    at JsonOutputFunctionsParser.parse (file:///Users/foo/node_modules/langchain/dist/output_parsers/openai_functions.js:138:35)
    at JsonOutputFunctionsParser.parseResult (file:///Users/foo/node_modules/langchain/dist/output_parsers/openai_functions.js:135:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

### Description

- I tried to print out the return string before applying `JSON.parse`. The output was the same as the documentation example stated, but it was not a valid json format because the keys were not wrapped in double quotes:
```json
{
  name: "John Doe",
  age: 30,
  fav_food: "chocolate chip cookies"
}
```
- I tried to change AI model but the same output and error message
- I tried to use `createStructuredOutputRunnable` with the example from: https://api.js.langchain.com/functions/langchain_chains_openai_functions.createStructuredOutputRunnable.html, but I received the same results

### System Info

yarn info v1.22.19
Platform: mac
Node version: v20.9.0
yarn version v1.22.19

**Comment by YukiDayDreamer** [comment]
I think `JsonOutputFunctionsParser` does its job, but somehow the functional call from openai is not a valid string that can be pasted into json format.

**Comment by jacoblee93** [comment]
This is odd - looks like a bug.

In the meantime, we've added a newer way to do this called `withStructuredOutput()` - would you be willing to give that a try?

https://js.langchain.com/docs/integrations/chat/openai#withstructuredoutput--

**Comment by YukiDayDreamer** [comment]
Yes, this `withStructuredOutput` works well. After updating the previous example with `withStructuredOutput`, it also works. Thanks for sharing.
