### ISSUE TITLE
Anthropic Tools doesn't make function call

### ISSUE THREAD

**Issue by elie222** [langchain-ai/langchainjs#4807]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

The following code should make a function call but doesn't.

```typescript
import { ChatAnthropicTools } from "@langchain/anthropic/experimental";
import { HumanMessage } from "@langchain/core/messages";
import { ToolDefinition } from "@langchain/core/language_models/base";

export async function anthropicChatCompletionTools(
  messages: Array<{
    role: "assistant" | "user";
    content: string;
  }>,
  tools: ToolDefinition[],
) {
  const anthropic = new ChatAnthropicTools({
    modelName: "claude-3-opus-20240229",
    anthropicApiKey: env.ANTHROPIC_API_KEY,
  });

  anthropic.bind({
    tools,
    // You can set the `function_call` arg to force the model to use a function
    tool_choice: {
            type: "function",
            function: {
              name: tools[0].function.name,
            },
          }
  });

  const response = await anthropic.invoke([
    new HumanMessage({
      content: messages.map((m) => m.content).join("\n\n"),
    }),
  ]);

// bug: responds with content instead of function call
  console.log(response);

  return response;
}
```

### Error Message and Stack Trace (if applicable)

import { ChatAnthropicTools } from "@langchain/anthropic/experimental";
import { HumanMessage } from "@langchain/core/messages";
import { ToolDefinition } from "@langchain/core/language_models/base";

### Description

* I'm trying to use `@langchain/anthropic/experimental` to make function calls with LangChain
* I'm expect it to call the function I've provided in `tool_choice`
* It isn't calling the function. It's simply responding with plain text content

### System Info

node v18.19.0
pnpm 8.15.4

"@langchain/anthropic": "^0.1.8",
    "@langchain/core": "^0.1.48",

**Comment by jacoblee93** [comment]
What is the actual logged response?

And could you share the tool schemas?

**Comment by sessycode** [comment]
ChatAnthropicTools is deprecated. 
Use ChatAnthropic instead.
see. https://js.langchain.com/docs/integrations/chat/anthropic/

**Comment by elie222** [comment]
> ChatAnthropicTools is deprecated. Use ChatAnthropic instead. see. [js.langchain.com/docs/integrations/chat/anthropic](https://js.langchain.com/docs/integrations/chat/anthropic/)

Thanks. Seems like this also has issues:

```
Object literal may only specify known properties, and 'tools' does not exist in type 'Partial<BaseLanguageModelCallOptions>'.ts(2353)
```

Code:

```ts
const calculatorSchema = z.object({
  operation: z
    .enum(["add", "subtract", "multiply", "divide"])
    .describe("The type of operation to execute."),
  number1: z.number().describe("The first number to operate on."),
  number2: z.number().describe("The second number to operate on."),
});

const tool = {
  name: "calculator",
  description: "A simple calculator tool",
  input_schema: zodToJsonSchema(calculatorSchema),
};

const model = new ChatAnthropic({
  anthropicApiKey: '',
  modelName: "claude-3-haiku-20240307",
}).bind({
  tools: [tool],
});
```

![CleanShot 2024-04-09 at 00 49 15@2x](https://github.com/langchain-ai/langchainjs/assets/3090527/7fe7448f-6194-414f-a336-a59c340f1ec6)

May just be a types issues.

**Comment by sessycode** [comment]
I updated all the dependencies for using new released ChatAnthropic. 

Here is mine.

  "dependencies": {
    "@langchain/anthropic": "^0.1.10",
    "@langchain/community": "^0.0.44",
    "@langchain/core": "^0.1.54",
    "@langchain/google-vertexai": "^0.0.2",
    "langchain": "^0.1.31",
    "ts-node": "^10.9.2",
    "zod": "^3.22.4",
    "zod-to-json-schema": "^3.22.5"
  }

**Comment by elie222** [comment]
Working now! Thanks! Think I needed to do a TS restart. Weird because almost certain I did yesterday.

**Comment by elie222** [comment]
> Working now! Thanks! Think I needed to do a TS restart. Weird because almost certain I did yesterday.

Hmm.. Seems to be having the same issues of not actually making the function calls. Even though the TypeScript error was fixed.
