### ISSUE TITLE
The `timeout` and `maxRetries` are not passed to the Mistral client

### ISSUE THREAD

**Issue by sneko** [langchain-ai/langchainjs#4809]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```ts
    this.mistralaiClient = new ChatMistralAI({
      ...
      maxRetries: 1,
    });
```

and

```ts
    const chain = new LLMChain({
      llm: this.mistralaiClient
        .bind({
          timeout: 10 * 1000
        }),
       ...
     });
```

### Description

Despite those configuration the underlying Mistral client will always use its default:
* Timeout: 120 seconds
* Max retries : 5

Which is really frustrating when it blocks a batch of processing or something else.

Note: I know the documentation speaks about `timeout` being available for OpenAI, but the typings should prevent prevent having them listed whereas they are not used.

Thank you,

### System Info

-

**Comment by jacoblee93** [comment]
Thanks for the report!

@bracesproul could you have a look?

**Comment by sneko** [comment]
@ity-alex I had to patch the underlying library: https://github.com/mistralai/client-js/issues/5#issuecomment-2003801102

But it seems they archived the library in place of a new one. So I advise you to look at it, maybe they have done some improvements 👍
