### ISSUE TITLE
LlamaCpp not working for some models and for Chinese Characters

### ISSUE THREAD

**Issue by vodkaslime** [langchain-ai/langchainjs#4812]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

Check out my example code:

https://github.com/vodkaslime/test-server/blob/main/index.js#L66-L67

Initiate the server by doing

```
yarn install
```

and then ***play by just commenting/uncommenting the highlighted two lines of code to switch between using langchain-wrapped-version and raw-version `node-llama-cpp`***

### Error Message and Stack Trace (if applicable)

Will be explicited below in ***Description***

### 1. Not running properly with some models
The raw `node-llama-cpp` works well with `Qwen` model, e.g. from https://huggingface.co/Qwen/Qwen1.5-7B-Chat-GGUF/blob/main/qwen1_5-7b-chat-q4_k_m.gguf smoothly. However the langchain wrapped version won't work. Sometimes the stream does not output anything.

### 2.Not running properly with Chinese characters even with working models
Even when running with canonical `llama2-7b` model, the server won't work with Chinese characters in langchain-wrapped mode.
e.g. input: "去成都的话怎么走" (How to travel to Chengdu city), the output goes as:
```
去成都的话，���可以������以下���个方式： 1. ���机：成都������中国大������地相对���近，
可以���������机到成都。 2. 高���：成都������中国大������地相对���近，可以������高
���到成都。 3. ������：可以������������到成都，需要注意的是，���需要在��...
```

### 3. Triggering LlamaCpp crashes
After trying several times, I even got crash of LlamaCpp under the hood.
```
GGML_ASSERT: /Users/runner/work/node-llama-cpp/node-llama-cpp/llama/llama.cpp/ggml-backend.c:206: offset + size <= ggml_nbytes(tensor) && "tensor read out of bounds"
```

***Notice: all problems only happen with langchain wrapped, not when running with raw node-llama-cpp***

I see similar issue reports about langchain not available for some models https://github.com/langchain-ai/langchainjs/issues/4674 in electron, but in my case this is also problem even in raw `node` environment. 

A rough guess based on the three issues above is that maybe there are some special character handling issues (compared to normal English alphabet) in the langchain wrapper?

### System Info

@langchain/community: ^0.0.40
platform: MacOS
Node version v20.11.0
yarn version v1.22.21

**Comment by jacoblee93** [comment]
Thanks for the heads up - might be some bad config. I'll try to get some time to repro soon.

**Comment by vodkaslime** [comment]
> Thanks for the heads up - might be some bad config. I'll try to get some time to repro soon.

Sure thanks! @jacoblee93

**Comment by nigel-daniels** [comment]
The underlying `node-llama-cpp` module has some up-coming changes when v3.0.0 is released that will provide some other missing facilities around vectors, I'll make sure to include add some tests with hanzi to ensure this issue is looked at.

**Comment by vodkaslime** [comment]
> The underlying `node-llama-cpp` module has some up-coming changes when v3.0.0 is released that will provide some other missing facilities around vectors, I'll make sure to include add some tests with hanzi to ensure this issue is looked at.

Sure thanks @nigel-daniels ! Btw please note that I think it's not the problem with the `node-llama-cpp`, since right now `node-llama-cpp` is already working well with `Qwen` model and with `hanzi`. I bet the issue is perhaps about our langchainjs wrapper layer.

**Comment by nigel-daniels** [comment]
@vodkaslime understood, currently LlamaCpp is not using the `node-llama-cpp` wrappings as they did not fit well with the LangChain JS way of doing things. I'm aware one of the expected changes in the v3.0.0 is to make it easier to reuse the existing wrappings. This was something I wanted to incorporate into the LlamaCpp update to make it a more complete representation of `node-llama-cpp`.

**Comment by vodkaslime** [comment]
> @vodkaslime understood, currently LlamaCpp is not using the `node-llama-cpp` wrappings as they did not fit well with the LangChain JS way of doing things. I'm aware one of the expected changes in the v3.0.0 is to make it easier to reuse the existing wrappings. This was something I wanted to incorporate into the LlamaCpp update to make it a more complete representation of `node-llama-cpp`.

Got it. So basically you are waiting for `node-llama-cpp v3.0.0` to come out and then on top of that you are going to make a big change/refactor to langchainjs here accordingly, and thus you wanna have this model/character support issue solved altogether within that one-off effort, right? That makes total sense. Go ahead if that's your roadmap.

But just a bit curious do you have any updates from `node-llama-cpp` team about when they plan to launch `v3.0.0`? Asking cuz look at https://github.com/withcatai/node-llama-cpp/pull/105 wow what a long effort what a big PR 🤣

**Comment by nigel-daniels** [comment]
@vodkaslime correct, I already have #3626 waiting for the v3.0.0 release, using the API I thought the `embedding` flag supported the generation of embeddings but I need to await v3.0.0 for this to work. Chatting with the maintainer I learned that v3.0.0 will require a rewrite of the LlamaCpp module but that it should enable a simplification of the code and enable use of the different model wrappings... As for a release date I'm not sure, it looks like v3.0.0 will be significant drop and I've been awaiting this since Dec time. My hope is they are close to completion.

**Comment by vodkaslime** [comment]
@nigel-daniels Cool! Thanks and looking forward to the new impl.
