### ISSUE TITLE
Malformed formatting instructions

### ISSUE THREAD

**Issue by baloodevil** [langchain-ai/langchainjs#4813]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

none

### Description

The following files have a prompt instruction that is malformed.  They each have two extra braces `}}` at the end.
[structured_parser.ts](https://github.com/langchain-ai/langchainjs/blob/ebe6bf806ce724775755b8f456e51fd1858353ba/examples/src/prompts/structured_parser.ts#L34)
[prompt.ts](https://github.com/langchain-ai/langchainjs/blob/ebe6bf806ce724775755b8f456e51fd1858353ba/langchain/src/agents/structured_chat/prompt.ts#L23)
[structured_parser_sequence.ts](https://github.com/langchain-ai/langchainjs/blob/ebe6bf806ce724775755b8f456e51fd1858353ba/examples/src/prompts/structured_parser_sequence.ts#L27)
[structured_parser_zod_sequence.ts](https://github.com/langchain-ai/langchainjs/blob/ebe6bf806ce724775755b8f456e51fd1858353ba/examples/src/prompts/structured_parser_zod_sequence.ts#L33)
[combining.test.ts](https://github.com/langchain-ai/langchainjs/blob/ebe6bf806ce724775755b8f456e51fd1858353ba/langchain/src/output_parsers/tests/combining.test.ts#L27)
[structured.ts](https://github.com/langchain-ai/langchainjs/blob/ebe6bf806ce724775755b8f456e51fd1858353ba/langchain-core/src/output_parsers/structured.ts#L84)
[structured_chat_runnable.ts](https://github.com/langchain-ai/langchainjs/blob/ebe6bf806ce724775755b8f456e51fd1858353ba/examples/src/agents/structured_chat_runnable.ts#L74)
[structured.test.ts](https://github.com/langchain-ai/langchainjs/blob/ebe6bf806ce724775755b8f456e51fd1858353ba/langchain-core/src/output_parsers/tests/structured.test.ts#L22)

Hard to say if it negatively affects prompts responses but it would be good to rule it out.

### System Info

Present in 0.1.28

**Comment by jacoblee93** [comment]
Thanks for reporting!

That's how you escape curly brackets `{` in the templating language. Otherwise, they denote variables.

**Comment by baloodevil** [comment]
Shouldn't they be matched?  i.e.: every opening bracket should have a closing bracket.  The last two right curly braces in the lines I cited do not have matching pairs.  And looking at the generated text that goes to the LLM (presumably after template replacement) has those unmatched brackets.

**Comment by jacoblee93** [comment]
Could you please open a PR with the proposed fix?
