### ISSUE TITLE
BedrockChat not supported by LLMChain

### ISSUE THREAD

**Issue by crileyy** [langchain-ai/langchainjs#4831]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```
import { recommenderPrompt } from '../prompts/recommenderPrompt';
import { LLMChain } from 'langchain/chains';
import { BedrockChat } from "@langchain/community/chat_models/bedrock";

const claude3Client = new BedrockChat({
  model: 'anthropic.claude-3-sonnet-20240229-v1:0',
  region: "us-east-1",
  maxTokens: 3000,
  temperature: 0.25
});

export const recommenderChain =  new LLMChain({ 
  llm: claude3Client, 
  prompt: recommenderPrompt, 
  outputKey: "recommend",
})
```

### Error Message and Stack Trace (if applicable)

```
Type 'BedrockChat' is missing the following properties from type 'BaseLanguageModel<any, BaseLanguageModelCallOptions>': CallOptions, _patchConfigts(2739)
llm_chain.d.ts(16, 5): The expected type comes from property 'llm' which is declared here on type 'LLMChainInput<string, BaseLanguageModel<any, BaseLanguageModelCallOptions>>'
(property) LLMChainInput<string, BaseLanguageModel<any, BaseLanguageModelCallOptions>>.llm: BaseLanguageModel<any, BaseLanguageModelCallOptions>
LLM Wrapper to use
```

### Description

I was using the `Bedrock` client with claude 2.1 in the LLMChain in the code above. In order to switch to claude 3, I have to use the `BedrockChat` client instead. However, I am getting an error that BedrockChat is not supported in the LLMChain. Is there a way it can be supported or is there something equivalent to LLMChain that supports the BedrockChat client? My codebase uses multiple LLMChains, so it'd be nice to not have rewrite the whole thing just to upgrade to claude 3 😅 

### System Info

Platform: Mac
Node: v20.9.0
Yarn version: v1.22.19

**Comment by andrewnguonly** [comment]
Similar or same issue: https://github.com/langchain-ai/langchainjs/issues/4567

Which versions of `langchain`, `@langchain/core`, and `@langchain/community` do you have installed?

I can't reproduce the error with `"@langchain/community": "^0.0.37"` and `"langchain": "^0.1.27"`. I'm able to pass a `BedrockChat` instance to `LLMChain` without any TypeScript error.

**Comment by crileyy** [comment]
Updating to the latest versions of langchain and lanchain/community fixed the issue.
