### ISSUE TITLE
Langsmith Hub Javascript Inline doesn't work

### ISSUE THREAD

**Issue by Mosquid** [langchain-ai/langchainjs#4915]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```
const prompt = ChatPromptTemplate.fromMessages([
    ['system', 'You are a helpful assistant'],
    ['placeholder', '{chat_history}'],
    ['human', '{input}'],
    ['placeholder', '{agent_scratchpad}'],
  ]);
  ```

### Description

https://smith.langchain.com/hub/hwchase17/openai-functions-agent
The code in "Javascript Inline" here is broken.

This is the code provided on the template page:
```
import { ChatPromptTemplate } from "@langchain/core/prompts";

const prompt = ChatPromptTemplate.fromMessages(
  ["system", "You are a helpful assistant"],
  ["placeholder", "{chat_history}"],
  ["human", "{input}"],
  ["placeholder", "{agent_scratchpad}"],
)
```

It gives an error: "Expected 1-2 arguments, but got 4". 

Based on the langchain docs, it should look like this:
```
const prompt = ChatPromptTemplate.fromMessages([
  ["system", "You are a helpful assistant"],
  ["placeholder", "{chat_history}"],
  ["human", "{input}"],
  ["placeholder", "{agent_scratchpad}"],
])
```

But with this modification, it gives a different error: "Missing value for input variable `{chat_history}`"

### System Info

[info.txt](https://github.com/langchain-ai/langchainjs/files/14791120/info.txt)

**Comment by jacoblee93** [comment]
`["placeholder", "{agent_scratchpad}"],` isn't supported yet - @rahilvora this would be a good one to add!
