### ISSUE TITLE
"TypeError: stream.getReader is not a function" while invoking Ollama model

### ISSUE THREAD

**Issue by anamrzv** [langchain-ai/langchainjs#4939]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```typescript
const ollama = new Ollama({
    baseUrl: "http://localhost:11434",
    model: "gemma:2b",
});

const result = await ollama.stream('hello, who are you'); //also tried .invoke('hello, who are you');
```
or
```typescript
const ollama = new Ollama({
    baseUrl: "http://localhost:11434",
    model: "gemma:2b",
});

const useCasePrompt = new PromptTemplate({
        template: `...`,
        inputVariables: ["name"]
    });

const useCaseChain = new LLMChain({ // also tried creating chains with RunnableSequence.from and createRetrievalChain
        llm: ollama,
        prompt: useCasePrompt
});

const result = await useCaseChain.invoke({ // also tried .call
         name: 'name'
});
```

### Error Message and Stack Trace (if applicable)

TypeError: stream.getReader is not a function
at IterableReadableStream.fromReadableStream (/node_modules/@langchain/core/dist/utils/stream.cjs:71:31)
at createOllamaStream (/node_modules/@langchain/community/dist/utils/ollama.cjs:39:52)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async createOllamaGenerateStream (/node_modules/@langchain/community/dist/utils/ollama.cjs:57:5)
at async Ollama._streamResponseChunks (/node_modules/@langchain/community/dist/llms/ollama.cjs:346:26)
at async Ollama._call (/node_modules/@langchain/community/dist/llms/ollama.cjs:376:26)
at async Promise.all (index 0)
at async Ollama._generate (/node_modules/@langchain/core/dist/language_models/llms.cjs:322:29)
at async Ollama._generateUncached (/node_modules/@langchain/core/dist/language_models/llms.cjs:138:22)
at async LLMChain._call (/node_modules/langchain/dist/chains/llm_chain.cjs:157:37)
at async LLMChain.invoke (/node_modules/langchain/dist/chains/base.cjs:58:28)

### Description

I'm trying to call Ollama model with LangChain, but every time the error TypeError: stream.getReader is coming up.
Seems related to the topic node-fetch and fetch https://stackoverflow.com/questions/57664058/response-body-getreader-is-not-a-function

### System Info

Node 20, also tried 18
langchain: ~0.1.30
@langchain/core: 0.1.52 (overrides)

**Comment by jacoblee93** [comment]
Can you share your `package.json`? And are you 1000% sure you're not on Node 16?

You can try this:

https://js.langchain.com/docs/get_started/installation#unsupported-nodejs-16

**Comment by Sergeant61** [comment]
https://github.com/ollama/ollama-js/issues/62

**Comment by Sergeant61** [comment]
I provided a solution with https://github.com/langchain-ai/langchainjs/pull/8396 pr with a usage like this.

```js

  async function customFetch(input, init) {
    const response = await fetch(input, init)
    const nodeStream = response.body

    if (nodeStream instanceof Readable && typeof nodeStream.getReader !== 'function') {
      nodeStream.getReader = () => {
        const iterator = nodeStream[Symbol.asyncIterator]()

        return {
          read: async () => {
            const result = await iterator.next()
            return {
              done: result.done ?? false,
              value: result.value ?? undefined,
            }
          },
          releaseLock: () => {},
          cancel: () => Promise.resolve(),
        }
      }
    }

    return response
  }

  const model = new ChatOllama({
    baseUrl: 'http://localhost:11434',
    model: 'gemma3:1b',
    fetch: customFetch,
  })

  const response = await model.invoke('2 plus 2')

  console.log(response)
```
