### ISSUE TITLE
Potential confusion on using OPENAI_API_KEY and AZURE_OPENAI_API_KEY together

### ISSUE THREAD

**Issue by castroalves** [langchain-ai/langchainjs#4951]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

How to reproduce it:

- In your .env, define both OPENAI_API_KEY and AZURE_OPENAI_API_KEY

Try to run and you should see the message "Azure OpenAI API instance name not found".

### Error Message and Stack Trace (if applicable)

Azure OpenAI API instance name not found

### Description

Hey guys, I'm using langchain on my NextJS project. I'm using 0.0.202 version, but I've also face the same issue when bumping to the latest version (0.1.30 as of now).

After investigating the issue, I realized that using AZURE_OPENAI_API_KEY, you automatically assign that value to the this.azureOpenAIApiKey property ([see here](https://github.com/langchain-ai/langchainjs/blob/c1e95236a0d3dcdf8c695411210df9041c98d4a2/libs/langchain-openai/src/llms.ts#L179)).

On production, we are using OPENAI_API_KEY and it's working as expected.

We have a preview branch where we are testing something else. When doing requests to OpenAI, it's not working and returning the error message `Azure OpenAI API instance name not found`.

However, we have a another preview branch where we are implementing Azure, but it's still being tested and reviewed by our team. Therefore, we have AZURE_OPENAI_API_KEY defined.

Because of that, looks like there is a conflict on both envs and the Azure one takes priority once it's defined. And so I'm getting the error `Azure OpenAI API instance name not found`.

Important: I use langchain for almost one year and wasn't aware of this behavior. 😅 

### System Info

System info:

langchain version: 0.0.202 (also tested on 0.1.30)
Platform: macOS Ventura 13.0
Node version: v21.4.0
pnpm version: 8.10.2

**Comment by oliviermills** [comment]
The only work around when having both env vars,  to solve this, is to use different env names for the keys and only set and unset the AZURE_OPENAI_API_KEY when needed.

Please prioritize this. 

## Solution idea
use an additional explicit `service` property in the constructor for `OpenAIEmbeddings` and `OpenAI` classes with options `'openai' | 'azure'` defaulting to `azure` to reflect current behaviour

### Why
Both classes are already opinionated with Azure and Open keys, so might as well provide a non

### Effects on code base
Limited as default behaviour is to prioritize Azure.

**Comment by johnnyoshika** [comment]
I created this repo to easily reproduce this: https://github.com/johnnyoshika/langchain-azure-openai-collision

Indeed the only way around this right now is to use a different environment variable from the default recommended one, `AZURE_OPENAI_API_KEY`, if you want to use both OpenAI and Azure OpenAI in the same project.
