### ISSUE TITLE
Attempt to connect to Azure openai through @langchain/azure-openai failed

### ISSUE THREAD

**Issue by Johnsonliuz** [langchain-ai/langchainjs#4955]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

I followed your code example for using @langchain/azure-openai in javascript:
```js
const { AzureChatOpenAI } = require("@langchain/azure-openai");
const { HumanMessage } = require("@langchain/core/messages");

const model = new AzureChatOpenAI({
  azureOpenAIEndpoint: 'https://testjohnson0402.openai.azure.com/',
  azureOpenAIApiKey: '34ff84a9e38346f99903c3c1e2de2ef1',
  azureOpenAIApiDeploymentName: 'gpt-35-turbo',
  modelName: 'gpt-35-turbo'
});

async function doSomething() {
  try {
    console.log(new HumanMessage("Hello world!"));
    const response = await model.invoke(new HumanMessage("Hello world!"));
    console.log(response);
    return response

  } catch (error) {
    console.log(error);
    throw error;
  }
}

module.exports = {
  doSomething
};
```

### Error Message and Stack Trace (if applicable)

Unable to connect successfully and got the following error response
```
Error: [object Object]
    at /Users/liuqiangsen/Documents/company/useLangChain/node_modules/@langchain/core/dist/utils/async_caller.cjs:98:23
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RetryOperation._fn (/Users/liuqiangsen/Documents/company/useLangChain/node_modules/p-retry/index.js:50:12) {
  attemptNumber: 7,
  retriesLeft: 0
}
```

### Description

Please help debug or provide correct examples,thanks！

### System Info

Node.js V.20.11.0,
platform: macos
"@langchain/azure-openai": "^0.0.5",
"@langchain/core": "^0.1.52",

**Comment by jacoblee93** [comment]
CC @sinedied would you be able to look into this? We should at least surface the error better.

**Comment by Johnsonliuz** [comment]
Let me correct it. When I don't use HumanMessage and throw the question directly, I will get the above error.
```
const response = await model.invoke("Hello world!");
 ---------
**get error**
Error: [object Object]
    at /Users/johnson/Documents/useLangChain/node_modules/@langchain/core/dist/utils/async_caller.cjs:98:23
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RetryOperation._fn (/Users/johnson/Documents/useLangChain/node_modules/p-retry/index.js:50:12) {
  attemptNumber: 7,
  retriesLeft: 0
}
```
If using HumanMessage, the error I get is as follows
```
const { HumanMessage } = require("@langchain/core/messages");

const response = await model.invoke(new HumanMessage("Hello world!"));
 ---------
**get error**
TypeError: promptValue.toChatMessages is not a function
```

**Comment by sinedied** [comment]
Hi @Johnsonliuz , thanks for reporting the issue! I could reproduce it and traced the issue where we're handling API key, a fix will be sent soon.
Meanwhile, you can use use the environment variable `AZURE_OPENAI_API_KEY` instead of providing the `azureOpenAIApiKey` parameter, ie:

Make sure to export in your environment the key with something like `export AZURE_OPENAI_API_KEY=xxxx`
then in your code just omit the parameter:

```ts
const model = new AzureChatOpenAI({
  azureOpenAIEndpoint: 'https://testjohnson0402.openai.azure.com/',
  azureOpenAIApiDeploymentName: 'gpt-35-turbo',
  modelName: 'gpt-35-turbo'
});
```

BTW, if the Azure OpenAI key your posted is real you should rotate it ASAP to avoid malicious usage!

**Comment by Johnsonliuz** [comment]
> 你好@Johnsonliuz，感謝您回報問題！我可以重現它並追蹤我們處理 API 金鑰的問題，很快就會發送修復程式。 同時，您可以使用環境變數`AZURE_OPENAI_API_KEY`來代替提供`azureOpenAIApiKey`參數。
> 
> 確保在您的環境中匯出類似`export AZURE_OPENAI_API_KEY=xxxx` 程式碼中的金鑰，只需省略參數：
> 
> ```ts
> const model = new AzureChatOpenAI({
>   azureOpenAIEndpoint: 'https://testjohnson0402.openai.azure.com/',
>   azureOpenAIApiDeploymentName: 'gpt-35-turbo',
>   modelName: 'gpt-35-turbo'
> });
> ```
> 
> 順便說一句，如果您發布的 Azure OpenAI 金鑰是真實的，您應該盡快輪換它以避免惡意使用！

@sinedied Thank you for your reminder. Because it is still under testing, it has not been extracted into variables, and the api endpoint and api key are not real.

**Comment by Johnsonliuz** [comment]
> Hi @Johnsonliuz , thanks for reporting the issue! I could reproduce it and traced the issue where we're handling API key, a fix will be sent soon. Meanwhile, you can use use the environment variable `AZURE_OPENAI_API_KEY` instead of providing the `azureOpenAIApiKey` parameter.
> 
> Make sure to export in your environment the key with something like `export AZURE_OPENAI_API_KEY=xxxx` then in your code just omit the parameter:
> 
> ```ts
> const model = new AzureChatOpenAI({
>   azureOpenAIEndpoint: 'https://testjohnson0402.openai.azure.com/',
>   azureOpenAIApiDeploymentName: 'gpt-35-turbo',
>   modelName: 'gpt-35-turbo'
> });
> ```
> 
> BTW, if the Azure OpenAI key your posted is real you should rotate it ASAP to avoid malicious usage!

@sinedied  Thank you for your reminder. Because it is still under testing, it has not been extracted into variables, and the api endpoint and api key are not real.
