### ISSUE TITLE
ChatVertexAI example always returns a truncated response

### ISSUE THREAD

**Issue by svengau** [langchain-ai/langchainjs#4968]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```
import { ChatVertexAI } from "@langchain/google-vertexai";
// Or, if using the web entrypoint:
// import { ChatVertexAI } from "@langchain/google-vertexai-web";

const model = new ChatVertexAI({
  temperature: 0.7,
  modelName: "gemini-1.0-pro",
});

const response = await model.invoke("Why is the ocean blue?");
console.log(response);
/*
AIMessageChunk {
  content: [{ type: 'text', text: 'The ocean' }], // <===== ONLY FIRST CHUNK
  additional_kwargs: {},
  response_metadata: {}
}
 */
```

### Error Message and Stack Trace (if applicable)

N/A

### Description

I've tried the provided example [in the doc](https://js.langchain.com/docs/integrations/chat/google_vertex_ai), and the `invoke` method always returns the first chunk of what could be a stream. 

As a workaround, I use:
```
const stream = await (llm as any).stream("...");
  let response = "";
  for await (const chunk of stream) {
    console.log(chunk.lc_kwargs.content);
    response += chunk?.lc_kwargs?.content?.toString();
  }
```

### System Info

langchain: 0.1.30
@langchain/community: 0.0.44
@langchain/core: 0.1.53
@langchain/google-vertexai: 0.0.2
@langchain/openai: 0.0.25
MacOS Sonoma 14.2.1 / Apple M1 Pro
node: 20.10.0
yarn: 1.22.1

**Comment by afirstenberg** [comment]
Hmmm... that almost seems consistent, since Vertex only has streaming, but it should have combined things. And it probably shoudln't be returning a chunk.

@jacoblee93 - Please assign this to me.

**Comment by afirstenberg** [comment]
(For the record, I think this was fixed when we implemented real non-streaming mode.)
