### ISSUE TITLE
How to enable streaming output in OpenAIAssistantRunnable?

### ISSUE THREAD

**Issue by chizm** [langchain-ai/langchainjs#4976]
### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

How to enable streaming output in OpenAIAssistantRunnable?

**Comment by sebdodt** [comment]
Hi @chizm, have you been able to resolve this? Would love to hear if you managed to stream with the `OpenAIAssistantRunnable`.

**Comment by ebikandi** [comment]
Interested. After struggling for some time I've come to the conclusion that currently OpenAIAssistantRunnable only handles polling queries
