### ISSUE TITLE
AzureAISearch hardcoded content, metadata & embedding key

### ISSUE THREAD

**Issue by sunnyunde-xooa** [langchain-ai/langchainjs#4986]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

// Create Azure AI Search instance
`
    const vectorStore = new AzureAISearchVectorStore(this.embedding, config);
    
    const docs = []; /// create documents using document loader
   const ids = vectorSotre.addDocuments(docs);
    
    `

### Error Message and Stack Trace (if applicable)

Error: Azure AI Search uploadDocuments batch failed: RestError: The request is invalid. Details: The property 'content' does not exist on type 'search.documentFields'. Make sure to only use property names that are defined by the type.
    at EventEmitter.<anonymous> (/home/xooa/Xooa/thaleslabs-ai/packages/backend/node_modules/@langchain/community/dist/vectorstores/azure_aisearch.cjs:225:19)
    at EventEmitter.emit (node:events:513:28)
    at EventEmitter.emit (node:domain:489:12)
    at SearchIndexingBufferedSender.submitDocuments (/home/xooa/Xooa/thaleslabs-ai/node_modules/@azure/search-documents/dist/index.js:4371:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SearchIndexingBufferedSender.internalFlush (/home/xooa/Xooa/thaleslabs-ai/node_modules/@azure/search-documents/dist/index.js:4318:17)
    at async AzureAISearchVectorStore.addVectors (/home/xooa/Xooa/thaleslabs-ai/packages/backend/node_modules/@langchain/community/dist/vectorstores/azure_aisearch.cjs:228:9)
    at async AzureAISearchVectorStore.addDocuments (/home/xooa/Xooa/thaleslabs-ai/packages/backend/node_modules/@langchain/community/dist/vectorstores/azure_aisearch.cjs:201:25)

### Description

`const entities: AzureAISearchDocument[] = documents.map((doc, idx) => ({
      id: ids[idx],
      content: doc.pageContent,
      content_vector: vectors[idx],
      metadata: {
        source: doc.metadata?.source,
        attributes: doc.metadata?.attributes ?? [],
      },
    }));
    `
    
    
    Here is the code which creates the document before uploading the doucment in the Azure AI Search
    As the content, metadata and content_vector keys are hardcoded any instance created previously with other keys are not possible to use this code.

### System Info

yarn info v1.22.19

**Comment by sunnyunde-xooa** [comment]
The issue is with hard coded values of content, metadata and embedding key as they can be dynamic as per the creators need they should not be hard coded
along with that the metadata key's value are also hard coded rather they should be open as I might need to pass extra or none of the key

**Comment by petergoldstein** [comment]
@sunnyunde-xooa I'm also running into this issue.  I'm not sure why these key values are being treated as constants.

Maintainers, I'm happy to submit a patch that allows the creator to set these field name values.  One easy, backwards compatible approach would be extending the `AzureAISearchConfig` type to include additional optional fields for these types.  The class could then replace the use of the constants (DEFAULT_...) with instance variables that would be set to either the value passed in as part of the config and default to the existing constants.

Would the above proposal be acceptable as an approach?  If not, do you have other suggestions?

**Comment by petergoldstein** [comment]
Unfortunately this initial approach doesn't work, at least as I originally envisioned it, because of Typescript issues.  The underlying Azure SearchClient expects a parameterized type, and then uses that type's keys to determine the set of allowed fields in the underlying schema.  This makes the whole thing very inflexible - the fields need to be specified at build time, not run time.  Which means, for example, passing in a configuration that specifies the fields in an environment variable isn't possible.

This is, to put it mildly, a little inconvenient.  The idea of passing in a configuration for a search store seems pretty basic.  I'm going to spend some time poking around and looking at alternative approaches.

**Comment by sunnyunde-xooa** [comment]
@petergoldstein for now I had solved this issue by creating a custom class which inherits the `AzureAISearchVectorStore` and overides the method `hybridSearchVectorWithScore` and I am keeping the content key, content vector key and metadata key dynamic by passing those value while intializing the class and later using in the function.

**Comment by patst** [comment]
This is a really annoying issue and it would be great to have some possibility to configure the metadata fields.

@sunnyunde-xooa  not sure if you are still here, but if so it would be great if you can reopen the issue to find a better solution than overriding the methods
