### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'transcriptBodyRenderer') using YoutubeLoader

### ISSUE THREAD

**Issue by Annahcj** [langchain-ai/langchainjs#4994]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```typescript
const loader = YoutubeLoader.createFromUrl(url, {
  language: 'en',
  addVideoInfo: true,
});

return loader.load();
```

### Error Message and Stack Trace (if applicable)

```
Error: Failed to get YouTube video transcription: [YoutubeTranscript] 🚨 TypeError: Cannot read properties of undefined (reading 'transcriptBodyRenderer')
    at YoutubeLoader.load (/Users/annaan/Documents/JS/langchain2/server/node_modules/langchain/dist/document_loaders/web/youtube.cjs:100:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Description

I'm using the `YoutubeLoader` from LangChain to load Youtube transcripts into documents.
Getting this error with any youtube URL.
This issue comes from the library `youtube-transcript` which is used under the hood - https://github.com/Kakulukian/youtube-transcript/issues/19
I believe Youtube's API has changed

### System Info

Platform: Mac
Node version: `18.18.2`
npm version: `9.8.1`
langchain: `^0.1.31`
youtube-transcript: `^1.1.0`
youtubei.js: `^9.2.0`

**Comment by tonymanh-dev** [comment]
Same issue here. **youtube-transcript** or **youtubei.js** just released a new version and they might change something in their API structure.

**Comment by siddharthd0** [comment]
having the same issue

**Comment by pjsofts** [comment]
Same here

**Comment by olefirenko** [comment]
Same here

**Comment by alejandrochacinortega** [comment]
Having the same issue here as well.

**Comment by sinedied** [comment]
For a temporary workaround until this is fixed upstream, you can:

```sh
npm i https://github.com/sinedied/youtube-transcript\#a10a073ac325b3b88018f321fa1bc5d62fa69b1c
```

This will use my fork that use a compatible drop-in code replacement from https://github.com/Kakulukian/youtube-transcript/issues/19, all the code credits goes to the folks there.

When the issue is fixed upstream, you can simply:

```sh
npm rm youtube-transcript
```

and it will return to the upstream version.

**Comment by prash-murali** [comment]
Same issue here with youtube-transcript

**Comment by SahilPulikal** [comment]
> For a temporary workaround until this is fixed upstream, you can:
> 
> ```shell
> npm i https://github.com/sinedied/youtube-transcript\#a10a073ac325b3b88018f321fa1bc5d62fa69b1c
> ```
> 
> This will use my fork that use a compatible drop-in code replacement from [Kakulukian/youtube-transcript#19](https://github.com/Kakulukian/youtube-transcript/issues/19), all the code credits goes to the folks there.
> 
> When the issue is fixed upstream, you can simply:
> 
> ```shell
> npm rm youtube-transcript
> ```
> 
> and it will return to the upstream version.

Thank you so much @sinedied , it worked.
