### ISSUE TITLE
ChatVertexAI with gemini-pro cannot have more than one tool via createOpenAIToolsAgent. It causes 400 Error when invoke.

### ISSUE THREAD

**Issue by sessycode** [langchain-ai/langchainjs#4998]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```typescript
// Using ChatVertexAI instead ChatOpenAI
// I modified original source code from tutorial
// see:
// - https://js.langchain.com/docs/modules/agents/tools/dynamic
// - https://js.langchain.com/docs/integrations/chat/google_vertex_ai

// import { ChatOpenAI } from '@langchain/openai'
import { ChatVertexAI } from '@langchain/google-vertexai'

import type { ChatPromptTemplate } from '@langchain/core/prompts'
import { createOpenAIToolsAgent, AgentExecutor } from 'langchain/agents'
import { pull } from 'langchain/hub'

import { z } from 'zod'
import { DynamicTool, DynamicStructuredTool } from '@langchain/core/tools'

export default async function TryVertexAIAgent() {
  console.log('===================tryVertexAIAgent()=======================')

  /**
   * Use ChatVertexAI instead ChatOpenAI
   */
  // const llm = new ChatOpenAI({
  //   modelName: 'gpt-3.5-turbo',
  //   temperature: 0,
  // })
  const llm = new ChatVertexAI({
    modelName: 'gemini-1.0-pro',
    temperature: 0,
  })

  const prompt = await pull<ChatPromptTemplate>('hwchase17/openai-tools-agent')
  const currentWeatherTool = new DynamicStructuredTool({
    name: 'get_current_weather',
    description: 'Get the current weather in a given location',
    schema: z.object({
      location: z
        .string()
        .describe('The city and state, e.g. San Francisco, CA'),
    }),
    func: async (param: { location: string }) =>
      Promise.resolve(
        JSON.stringify({ location: param.location, temperature: '28 °C' })
      ),
    // '28 °C',
  })
  const tools = [
    /**
     * Addition tool
     */
    new DynamicStructuredTool({
      name: 'add_two_numbers',
      description: `get result of adding two numbers'`,
      schema: z.object({
        x: z.number().describe('one of two numbers to be added'),
        y: z.number().describe('one of two numbers to be added'),
      }),
      func: async (param: { x: number; y: number }) => {
        return JSON.stringify({
          result: param.x + param.y,
        })
      },
    }),
    /**
     * Multiplying tool
     */
    new DynamicStructuredTool({
      name: 'multiply_two_numbers',
      description: `get result of multiplying two numbers'`,
      schema: z.object({
        x: z.number().describe('one of two numbers to be multiplied'),
        y: z.number().describe('one of two numbers to be multiplied'),
      }),
      func: async (param: { x: number; y: number }) => {
        return JSON.stringify({
          result: param.x * param.y,
        })
      },
    }),
  ]

  // Get the prompt to use - you can modify this!\
  // If you want to see the prompt in full, you can at:
  // https://smith.langchain.com/hub/hwchase17/openai-functions-agent
  // const prompt = await pull<ChatPromptTemplate>(
  //   'hwchase17/openai-functions-agent'
  // )

  const agent = await createOpenAIToolsAgent({
    llm,
    tools,
    prompt,
  })

  const agentExecutor = new AgentExecutor({
    agent,
    tools,
  })

  const result = await agentExecutor.invoke({
    input: '1 + 1 = ?',
    // input: '(1 + 1) + (1 + 1) = ?',
    // input: `What is the weather like in Seoul?`,
    // input: 'What is the name of foo?',
  })

  console.log(`Got output ${result.output}`)
}

// Run
TryVertexAIAgent() 
```

### Error Message and Stack Trace (if applicable)

===================tryVertexAIAgent()=======================
call to gauth.request {
  "response": {
    "config": {
      "url": "https://......hidden...",
      "method": "POST",
      "headers": {
        "User-Agent": "langchain-js/0-ChatConnection google-api-nodejs-client/8.9.0",
        "Authorization": "hidden............",
        "x-goog-api-client": "gl-node/20.10.0",
        "Content-Type": "application/json"
      },
      "data": {
        "contents": [
          {
            "role": "user",
            "parts": [
              {
                "text": "You are a helpful assistant"
              }
            ]
          },
          {
            "role": "model",
            "parts": [
              {
                "text": "Ok"
              }
            ]
          },
          {
            "role": "user",
            "parts": [
              {
                "text": "1 + 1 = ?"
              }
            ]
          }
        ],
        "generationConfig": {
          "temperature": 0,
          "topK": 40,
          "topP": 0.8,
          "maxOutputTokens": 1024,
          "stopSequences": []
        },
        "tools": [
          {
            "functionDeclarations": [
              {
                "name": "add_two_numbers",
                "description": "get result of adding two numbers'",
                "parameters": {
                  "type": "object",
                  "properties": {
                    "x": {
                      "type": "number",
                      "description": "one of two numbers to be added"
                    },
                    "y": {
                      "type": "number",
                      "description": "one of two numbers to be added"
                    }
                  },
                  "required": [
                    "x",
                    "y"
                  ]
                }
              }
            ]
          },
          {
            "functionDeclarations": [
              {
                "name": "multiply_two_numbers",
                "description": "get result of multiplying two numbers'",
                "parameters": {
                  "type": "object",
                  "properties": {
                    "x": {
                      "type": "number",
                      "description": "one of two numbers to be multiplied"
                    },
                    "y": {
                      "type": "number",
                      "description": "one of two numbers to be multiplied"
                    }
                  },
                  "required": [
                    "x",
                    "y"
                  ]
                }
              }
            ]
          }
        ]
      },
      "responseType": "stream",
      "body": "{\"contents\":[{\"role\":\"user\",\"parts\":[{\"text\":\"You are a helpful assistant\"}]},{\"role\":\"model\",\"parts\":[{\"text\":\"Ok\"}]},{\"role\":\"user\",\"parts\":[{\"text\":\"1 + 1 = ?\"}]}],\"generationConfig\":{\"temperature\":0,\"topK\":40,\"topP\":0.8,\"maxOutputTokens\":1024,\"stopSequences\":[]},\"tools\":[{\"functionDeclarations\":[{\"name\":\"add_two_numbers\",\"description\":\"get result of adding two numbers'\",\"parameters\":{\"type\":\"object\",\"properties\":{\"x\":{\"type\":\"number\",\"description\":\"one of two numbers to be added\"},\"y\":{\"type\":\"number\",\"description\":\"one of two numbers to be added\"}},\"required\":[\"x\",\"y\"]}}]},{\"functionDeclarations\":[{\"name\":\"multiply_two_numbers\",\"description\":\"get result of multiplying two numbers'\",\"parameters\":{\"type\":\"object\",\"properties\":{\"x\":{\"type\":\"number\",\"description\":\"one of two numbers to be multiplied\"},\"y\":{\"type\":\"number\",\"description\":\"one of two numbers to be multiplied\"}},\"required\":[\"x\",\"y\"]}}]}]}"
    },
    "data": "[{\n  \"error\": {\n    \"code\": 400,\n    \"message\": \"Request contains an invalid argument.\",\n    \"errors\": [\n      {\n        \"message\": \"Request contains an invalid argument.\",\n        \"domain\": \"global\",\n        \"reason\": \"badRequest\"\n      }\n    ],\n    \"status\": \"INVALID_ARGUMENT\"\n  }\n}\n]",
    "headers": {
      "alt-svc": "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000",
      "cache-control": "private",
      "content-encoding": "gzip",
      "content-type": "application/json; charset=UTF-8",
      "date": "Sun, 07 Apr 2024 14:21:09 GMT",
      "server": "scaffolding on HTTPServer2",
      "transfer-encoding": "chunked",
      "vary": "Origin, X-Origin, Referer",
      "x-content-type-options": "nosniff",
      "x-frame-options": "SAMEORIGIN",
      "x-xss-protection": "0"
    },
    "status": 400,
    "statusText": "Bad Request",
    "request": {
      "responseURL": "hidden...."
    }
  },
  "config": {
    "url": "https://hidden.................",
    "method": "POST",
    "headers": {
      "User-Agent": "langchain-js/0-ChatConnection google-api-nodejs-client/8.9.0",
      "Authorization": "hidden...............",
      "x-goog-api-client": "gl-node/20.10.0",
      "Content-Type": "application/json"
    },
    "data": {
      "contents": [
        {
          "role": "user",
          "parts": [
            {
              "text": "You are a helpful assistant"
            }
          ]
        },
        {
          "role": "model",
          "parts": [
            {
              "text": "Ok"
            }
          ]
        },
        {
          "role": "user",
          "parts": [
            {
              "text": "1 + 1 = ?"
            }
          ]
        }
      ],
      "generationConfig": {
        "temperature": 0,
        "topK": 40,
        "topP": 0.8,
        "maxOutputTokens": 1024,
        "stopSequences": []
      },
      "tools": [
        {
          "functionDeclarations": [
            {
              "name": "add_two_numbers",
              "description": "get result of adding two numbers'",
              "parameters": {
                "type": "object",
                "properties": {
                  "x": {
                    "type": "number",
                    "description": "one of two numbers to be added"
                  },
                  "y": {
                    "type": "number",
                    "description": "one of two numbers to be added"
                  }
                },
                "required": [
                  "x",
                  "y"
                ]
              }
            }
          ]
        },
        {
          "functionDeclarations": [
            {
              "name": "multiply_two_numbers",
              "description": "get result of multiplying two numbers'",
              "parameters": {
                "type": "object",
                "properties": {
                  "x": {
                    "type": "number",
                    "description": "one of two numbers to be multiplied"
                  },
                  "y": {
                    "type": "number",
                    "description": "one of two numbers to be multiplied"
                  }
                },
                "required": [
                  "x",
                  "y"
                ]
              }
            }
          ]
        }
      ]
    },
    "responseType": "stream",
    "body": "{\"contents\":[{\"role\":\"user\",\"parts\":[{\"text\":\"You are a helpful assistant\"}]},{\"role\":\"model\",\"parts\":[{\"text\":\"Ok\"}]},{\"role\":\"user\",\"parts\":[{\"text\":\"1 + 1 = ?\"}]}],\"generationConfig\":{\"temperature\":0,\"topK\":40,\"topP\":0.8,\"maxOutputTokens\":1024,\"stopSequences\":[]},\"tools\":[{\"functionDeclarations\":[{\"name\":\"add_two_numbers\",\"description\":\"get result of adding two numbers'\",\"parameters\":{\"type\":\"object\",\"properties\":{\"x\":{\"type\":\"number\",\"description\":\"one of two numbers to be added\"},\"y\":{\"type\":\"number\",\"description\":\"one of two numbers to be added\"}},\"required\":[\"x\",\"y\"]}}]},{\"functionDeclarations\":[{\"name\":\"multiply_two_numbers\",\"description\":\"get result of multiplying two numbers'\",\"parameters\":{\"type\":\"object\",\"properties\":{\"x\":{\"type\":\"number\",\"description\":\"one of two numbers to be multiplied\"},\"y\":{\"type\":\"number\",\"description\":\"one of two numbers to be multiplied\"}},\"required\":[\"x\",\"y\"]}}]}]}"
  },
  "code": "400"
}
call to gauth.request opts= {
  "url": "https://hidden...............",
  "method": "POST",
  "headers": {
    "User-Agent": "langchain-js/0-ChatConnection google-api-nodejs-client/8.9.0",
    "Authorization": "hidden........................",
    "x-goog-api-client": "gl-node/20.10.0"
  },
  "data": {
    "contents": [
      {
        "role": "user",
        "parts": [
          {
            "text": "You are a helpful assistant"
          }
        ]
      },
      {
        "role": "model",
        "parts": [
          {
            "text": "Ok"
          }
        ]
      },
      {
        "role": "user",
        "parts": [
          {
            "text": "1 + 1 = ?"
          }
        ]
      }
    ],
    "generationConfig": {
      "temperature": 0,
      "topK": 40,
      "topP": 0.8,
      "maxOutputTokens": 1024,
      "stopSequences": []
    },
    "tools": [
      {
        "functionDeclarations": [
          {
            "name": "add_two_numbers",
            "description": "get result of adding two numbers'",
            "parameters": {
              "type": "object",
              "properties": {
                "x": {
                  "type": "number",
                  "description": "one of two numbers to be added"
                },
                "y": {
                  "type": "number",
                  "description": "one of two numbers to be added"
                }
              },
              "required": [
                "x",
                "y"
              ]
            }
          }
        ]
      },
      {
        "functionDeclarations": [
          {
            "name": "multiply_two_numbers",
            "description": "get result of multiplying two numbers'",
            "parameters": {
              "type": "object",
              "properties": {
                "x": {
                  "type": "number",
                  "description": "one of two numbers to be multiplied"
                },
                "y": {
                  "type": "number",
                  "description": "one of two numbers to be multiplied"
                }
              },
              "required": [
                "x",
                "y"
              ]
            }
          }
        ]
      }
    ]
  },
  "responseType": "stream"
}
call to gauth.request message: [{
  "error": {
    "code": 400,
    "message": "Request contains an invalid argument.",
    "errors": [
      {
        "message": "Request contains an invalid argument.",
        "domain": "global",
        "reason": "badRequest"
      }
    ],
    "status": "INVALID_ARGUMENT"
  }
}
]
GaxiosError: [{
  "error": {
    "code": 400,
    "message": "Request contains an invalid argument.",
    "errors": [
      {
        "message": "Request contains an invalid argument.",
        "domain": "global",
        "reason": "badRequest"
      }
    ],
    "status": "INVALID_ARGUMENT"
  }
}
]
... 

### Description

I try to make a agent using ChatVertexAI and createOpenAIToolsAgent.
It is introduced in official langchainjs website. 
- https://js.langchain.com/docs/integrations/chat/google_vertex_ai
- https://js.langchain.com/docs/modules/agents/tools/dynamic

When I put only one tool to agent, It is OK.
But two tools, it makes an error, 400 Bad Request.

### System Info

It is my package.json
{
  "name": "ts-boilerplate",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "ts-node ./src/test.ts"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@types/node": "^20.12.5",
    "dotenv": "^16.4.5",
    "eslint": "^8.57.0",
    "eslint-config-prettier": "^9.1.0",
    "prettier": "^3.2.5",
    "typescript": "^5.4.4"
  },
  "dependencies": {
    "@langchain/anthropic": "^0.1.10",
    "@langchain/community": "^0.0.44",
    "@langchain/core": "^0.1.54",
    "@langchain/google-vertexai": "^0.0.2",
    "langchain": "^0.1.31",
    "ts-node": "^10.9.2",
    "zod": "^3.22.4",
    "zod-to-json-schema": "^3.22.5"
  }
}

platform: windows11
node version: v20.10.0

**Comment by sessycode** [comment]
Each of tools has no problem. Error happens only tools are together.

**Comment by jacoblee93** [comment]
CC @bracesproul

**Comment by sessycode** [comment]
I decide to use 'createToolCallingAgent' which solves multiple tools issue.
It works perfect with vertexai(gemini)

I think the offifial document, (https://js.langchain.com/docs/integrations/chat/google_vertex_ai#vertexai-tools-agent), should be updated or removed.

Thanks!

**Comment by jacoblee93** [comment]
Great! Thanks for your patience. We've updated the doc.
