### ISSUE TITLE
Why is the documentation for the TS version inconsistent with python?

### ISSUE THREAD

**Issue by jameslun** [langchain-ai/langchainjs#5003]
### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

agent 

### Idea or request for content:

For example, the TS agent section is different from python

**Comment by jacoblee93** [comment]
Thanks for raising this - have plans to revisit the TS docs soon!

**Comment by jacoblee93** [comment]
Closing for now with the latest refactor
