### ISSUE TITLE
PGVectorStore creates pg-client, Never uses it

### ISSUE THREAD

**Issue by MJDeligan** [langchain-ai/langchainjs#5029]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

\Na

### Error Message and Stack Trace (if applicable)

\Na

### Description

The PGVectorStore uses the node-postgres library to handle queries to the postgres database. It is not recommended to check out clients from the pool unless a transaction is needed, which, in this case, it is not ([docs](https://node-postgres.com/features/pooling#checkout-use-and-return)). The client is created when the vector store is initialized and only released when the vector store is ended. 

This has a couple of problems:
1. The client is never used. Instead the pool is used everywhere to send queries.
2. The connection of a client is persistent, contributing to the maximum number of connections to the server. This means that for the duration that the vector store is used, one connection is constantly open, whether it is currently being used or not. This makes it inappropriate for applications that may have many vector stores active at the same time.
3. Despite the client never being used, it must still be released in the end. This means that we must have a reference to either the vector store or the client itself in order to properly shut down the connections. Without the client, providing a pool, we can end all connections by closing the pool without having to think about releasing clients. This is also a major issue since not releasing the client will make the call to close the pool hang until the client is released, meaning we could bleed connections and memory.

I suggest removing the initializing of the client. The client property and its release could be left alone, since it may cause issues with backwards compatibility, although in a breaking release, those should also be removed. 

I'll be opening a PR to address this issue.

### System Info

\Na

**Comment by MJDeligan** [comment]
Fixing this in a breaking change would probably be better, since there's really no good way to achieve this in a non-breaking manner without cluttering the interface.

**Comment by palashk92** [comment]
is this something that has been prioritized? We ran into this issue recently, and it is a quite significant blocker for us to use in production

**Comment by ladrians** [comment]
@MJDeligan not sure if this issue advanced? based on this comments there is no reasonable solution for using a pool for pgvector for the current implementation?

In my case I got the error `XX000 Max client connections reached` and cannot completely remove it, when using a chain I do `await vectorStore.end();` but as some chains are long-term the connection is kept until the whole process finishes.

**Comment by MJDeligan** [comment]
@ladrians It was tweaked but the problem was not fixed. vectorStore.end() now releases the client, which it originally didn't, but as you've noted, when using multiple stores this does not help. A quick and dirty way to prevent max connection issues could be to release the client immediately after initialization. Otherwise you could extend PGVectorStore and overwrite the initialize method to not check out the client. 

Fixing this in langchainjs itself would be a breaking change. I haven't been keeping up with the library, so I'm unsure if any are planned.

**Comment by jacoblee93** [comment]
We could make this a separate partner package and do a breaking change - how bad is this issue?
