### ISSUE TITLE
ZhipuAIEmbeddings  bug

### ISSUE THREAD

**Issue by ychengke** [langchain-ai/langchainjs#5037]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

import { ZhipuAIEmbeddings } from "@langchain/community/embeddings/zhipuai";

const model = new ZhipuAIEmbeddings({});
const res = await model.embedQuery(
  "What would be a good company name a company that makes colorful socks?"
);
console.log({ res });

### Error Message and Stack Trace (if applicable)

 throw new Error(`Error getting embeddings from ZhipuAI. ${JSON.stringify(await fetchResponse.json(), null, 2)}`); ^ Error: Error getting embeddings from ZhipuAI. { "error": { "code": "1000", "message": "身份验证失败。" } } 

### Description

 throw new Error(`Error getting embeddings from ZhipuAI. ${JSON.stringify(await fetchResponse.json(), null, 2)}`); ^ Error: Error getting embeddings from ZhipuAI. { "error": { "code": "1000", "message": "身份验证失败。" } } 

### System Info

    "@langchain/community": "^0.0.41",
    "@langchain/core": "^0.1.49",
    "langchain": "^0.1.28",

**Comment by shan-mx** [comment]
@ychengke hi, I encountered same issue when using ChatZhipuAI. I found some information in the official document: https://open.bigmodel.cn/dev/api#nosdk

It seems that it's required to generate a jwt token before calling their api, if not using their official sdk in python/java.

**Comment by jeasonnow** [comment]
To address this issue, JWT tokens can be generated dynamically when a request is made, and caching can be used to prevent re-generating tokens that are still valid. You can review the details in my pull request.
