### ISSUE TITLE
`maxRetries` not properly passed to `ChatOpenAI` in tracing

### ISSUE THREAD

**Issue by lukasugar** [langchain-ai/langchainjs#5061]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

I have this code for creating a chain with ChatOpenAI client:
```typescript
const chain  = RunnableSequence.from([
            chatPrompt, // prompt defined above
            new ChatOpenAI({
              modelName: 'gpt-4-0125-preview',
              temperature: 0.1,
              maxRetries: 3,
              modelKwargs: { response_format: { type: 'json_object' } },
            }),
            suggestionsParser, // some parser defined above
          ]);
```
I invoke the chain like this:
```typescript
const response = await chain.invoke({ document_to_review: docContent }, { tags: ['suggestions'] });
```

### Description

The openai call returned an error but no retries were made.
OpenAI error:
```
400 You requested a model that is not compatible with this engine. Please contact us through our help center at help.openai.com for further questions.

Error: 400 You requested a model that is not compatible with this engine. Please contact us through our help center at help.openai.com for further questions.
    at APIError.generate (/app/node_modules/.pnpm/openai@4.32.2/node_modules/openai/error.js:44:20)
    at OpenAI.makeStatusError (/app/node_modules/.pnpm/openai@4.32.2/node_modules/openai/core.js:263:33)
    at OpenAI.makeRequest (/app/node_modules/.pnpm/openai@4.32.2/node_modules/openai/core.js:306:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/node_modules/.pnpm/@langchain+openai@0.0.26/node_modules/@langchain/openai/dist/chat_models.cjs:684:29
    at async RetryOperation._fn (/app/node_modules/.pnpm/p-retry@4.6.2/node_modules/p-retry/index.js:50:12)
```

The langsmith logs show that retries parameter is present in the metadata passed
```
{
  "id": [
    "langchain",
    "chat_models",
    "openai",
    "ChatOpenAI"
  ],
  "kwargs": {
    "max_retries": 3,
    "model": "gpt-4-0125-preview",
    "model_kwargs": {
      "response_format": {
        "type": "json_object"
      }
    },
    "openai_api_key": {
      "id": [
        "OPENAI_API_KEY"
      ],
      "lc": 1,
      "type": "secret"
    },
    "temperature": 0.1
  },
  "lc": 1,
  "type": "constructor"
}
```
But when looking at invocation metadata in LangSmith, the retry parameter isn't present:
<img width="520" alt="image" src="https://github.com/langchain-ai/langchainjs/assets/22435018/0d828460-545c-48d6-9baf-8fc316c44f95">

How to properly pass `maxRetries` parameter to ChatOpenAI?
I want to specify a specific number, but does not specifying it at all **really** default to a 6 time retry with exponential backoff?

### System Info

Running on an ec2 instance with linux

Langchain versions:
- "@langchain/core": "0.1.53",
- "@langchain/openai": "^0.0.26",
- "langchain": "^0.1.31",

**Comment by lukasugar** [comment]
I'm passing `maxRetries` exactly as in the docs: https://js.langchain.com/docs/modules/model_io/chat/dealing_with_api_errors

**Comment by lukasugar** [comment]
Should this line be changed from 0 to 6 to match the documentation: https://github.com/langchain-ai/langchainjs/blob/main/libs/langchain-openai/src/chat_models.ts#L916
```
const endpoint = getEndpoint(openAIEndpointConfig);
      const params = {
        ...this.clientConfig,
        baseURL: endpoint,
        timeout: this.timeout,
        maxRetries: 0, // change to 6
      };
```

**Comment by rahilvora** [comment]
@lukasugar Thanks for reporting this. 

@jacoblee93 can you help me with the review

**Comment by lukasugar** [comment]
@rahilvora thanks you for picking it up. I hope this fix gets shipped soon :)
I hope @jacoblee93 will have time to review the PR soon, in the meantime I added a small comment there :)

**Comment by jacoblee93** [comment]
Hey @lukasugar! We only retry certain types of errors - things like 400s will not be retried (it wouldn't make sense to retry something like `You requested a model that is not compatible with this engine. Please contact us through our help center at help.openai.com for further questions.` because it would never succeed).

We could look into adding `maxRetries` to the traced `invocationParams` in LangSmith though.
