### ISSUE TITLE
google-common [feature]: Support JSON Mode for Gemini

### ISSUE THREAD

**Issue by afirstenberg** [langchain-ai/langchainjs#5071]
### Privileged issue

- [X] I am a LangChain maintainer, or was asked directly by a LangChain maintainer to create an issue here.

### Issue Content

See documentation for `responseMimeType` at https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/gemini#request_body

See https://github.com/langchain-ai/langchain-google/issues/144

**Comment by JackFener** [comment]
already managed to add it. would you like to assign it to me?
I'll add some test and then open a pull request

**Comment by rossanodr** [comment]
How can I use it ChatGoogleGenerativeAI?

**Comment by hongkongkiwi** [comment]
The docs show this as missing from this provider still?
