### ISSUE TITLE
createToolCallingAgent + ChatVertexAI(gemini-1.0-pro) + Empty Tools ==> 400 Bad Request.  (Empty tools should be allowed in VertexAI as ChatAntrhopic does)

### ISSUE THREAD

**Issue by sessycode** [langchain-ai/langchainjs#5079]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```typescript /**
 * Note:
 * - ChatAthropic allows empty tools. e.g. tools = [].
 * - But ChatVertexAI causes 400 error with empty tools!!
 *
 * TODO:
 * - ChatVertexAI must allow empty tools
 */

import { ChatAnthropic } from '@langchain/anthropic'
import { ChatVertexAI } from '@langchain/google-vertexai'
import { createToolCallingAgent } from 'langchain/agents'
import { ChatPromptTemplate } from '@langchain/core/prompts'
import { AgentExecutor } from 'langchain/agents'
import { StructuredToolInterface } from '@langchain/core/tools'

export default async function test_tools_agent() {
  const prompt = ChatPromptTemplate.fromMessages([
    ['system', 'You are a helpful assistant.'],
    // ['placeholder', '{chat_history}'],
    ['human', '{input}'],
    ['placeholder', '{agent_scratchpad}'],
  ])

  /**
   * Note:
   * ChatAnthropic is OK with empty tools
   */
  // const llm = new ChatAnthropic({
  //   model: 'claude-3-sonnet-20240229',
  //   temperature: 0,
  // })

  /**
   * Note:
   * ChatVertexAI cauese error with empty tools
   */
  const llm = new ChatVertexAI({
    model: 'gemini-1.0-pro',
    temperature: 0,
  })

  // Test Empty Tools
  const tools: StructuredToolInterface[] = []

  const agent = await createToolCallingAgent({
    llm,
    tools,
    prompt,
  })

  const agentExecutor = new AgentExecutor({
    agent,
    tools,
  })

  const result = await agentExecutor.invoke({
    input: 'Hi!',
  })

  console.log(result)
}

// Run test
test_tools_agent()
```

### Error Message and Stack Trace (if applicable)

call to gauth.request {
  "response": {
    "config": {
      "url": "hidden",
      "method": "POST",
      "headers": {
        "User-Agent": "langchain-js/0-ChatConnection google-api-nodejs-client/8.9.0",
        "Authorization": "hidden",
        "x-goog-api-client": "gl-node/20.10.0",
        "Content-Type": "application/json"
      },
      "data": {
        "contents": [
          {
            "role": "user",
            "parts": [
              {
                "text": "You are a helpful assistant."
              }
            ]
          },
          {
            "role": "model",
            "parts": [
              {
                "text": "Ok"
              }
            ]
          },
          {
            "role": "user",
            "parts": [
              {
                "text": "Hi!"
              }
            ]
          }
        ],
        "generationConfig": {
          "temperature": 0,
          "topK": 40,
          "topP": 0.8,
          "maxOutputTokens": 1024,
          "stopSequences": []
        },
        "tools": [
          {
            "functionDeclarations": []
          }
        ]
      },
      "responseType": "stream",
      "body": "{\"contents\":[{\"role\":\"user\",\"parts\":[{\"text\":\"You are a helpful assistant.\"}]},{\"role\":\"model\",\"parts\":[{\"text\":\"Ok\"}]},{\"role\":\"user\",\"parts\":[{\"text\":\"Hi!\"}]}],\"generationConfig\":{\"temperature\":0,\"topK\":40,\"topP\":0.8,\"maxOutputTokens\":1024,\"stopSequences\":[]},\"tools\":[{\"functionDeclarations\":[]}]}"
    },
    "data": "[{\n  \"error\": {\n    \"code\": 400,\n    \"message\": \"Request contains an invalid argument.\",\n    \"errors\": [\n      {\n        \"message\": \"Request contains an invalid argument.\",\n        \"domain\": \"global\",\n        \"reason\": \"badRequest\"\n      }\n    ],\n    \"status\": \"INVALID_ARGUMENT\"\n  }\n}\n]",
    "headers": {
      "alt-svc": "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000",
      "cache-control": "private",
      "content-encoding": "gzip",
      "content-type": "application/json; charset=UTF-8",
      "date": "Fri, 12 Apr 2024 08:00:13 GMT",
      "server": "scaffolding on HTTPServer2",
      "transfer-encoding": "chunked",
      "vary": "Origin, X-Origin, Referer",
      "x-content-type-options": "nosniff",
      "x-frame-options": "SAMEORIGIN",
      "x-xss-protection": "0"
    },
    "status": 400,
    "statusText": "Bad Request",
    "request": {
      "responseURL": "hidden"
    }
  },
  "config": {
    "url": "hidden",
    "method": "POST",
    "headers": {
      "User-Agent": "langchain-js/0-ChatConnection google-api-nodejs-client/8.9.0",
      "Authorization": "hidden",
      "x-goog-api-client": "gl-node/20.10.0",
      "Content-Type": "application/json"
    },
    "data": {
      "contents": [
        {
          "role": "user",
          "parts": [
            {
              "text": "You are a helpful assistant."
            }
          ]
        },
        {
          "role": "model",
          "parts": [
            {
              "text": "Ok"
            }
          ]
        },
        {
          "role": "user",
          "parts": [
            {
              "text": "Hi!"
            }
          ]
        }
      ],
      "generationConfig": {
        "temperature": 0,
        "topK": 40,
        "topP": 0.8,
        "maxOutputTokens": 1024,
        "stopSequences": []
      },
      "tools": [
        {
          "functionDeclarations": []
        }
      ]
    },
    "responseType": "stream",
    "body": "{\"contents\":[{\"role\":\"user\",\"parts\":[{\"text\":\"You are a helpful assistant.\"}]},{\"role\":\"model\",\"parts\":[{\"text\":\"Ok\"}]},{\"role\":\"user\",\"parts\":[{\"text\":\"Hi!\"}]}],\"generationConfig\":{\"temperature\":0,\"topK\":40,\"topP\":0.8,\"maxOutputTokens\":1024,\"stopSequences\":[]},\"tools\":[{\"functionDeclarations\":[]}]}"
  },
  "code": "400"
}
call to gauth.request opts= {
  "url": "hidden",
  "method": "POST",
  "headers": {
    "User-Agent": "langchain-js/0-ChatConnection google-api-nodejs-client/8.9.0",
    "Authorization": "hidden",
    "x-goog-api-client": "gl-node/20.10.0"
  },
  "data": {
    "contents": [
      {
        "role": "user",
        "parts": [
          {
            "text": "You are a helpful assistant."
          }
        ]
      },
      {
        "role": "model",
        "parts": [
          {
            "text": "Ok"
          }
        ]
      },
      {
        "role": "user",
        "parts": [
          {
            "text": "Hi!"
          }
        ]
      }
    ],
    "generationConfig": {
      "temperature": 0,
      "topK": 40,
      "topP": 0.8,
      "maxOutputTokens": 1024,
      "stopSequences": []
    },
    "tools": [
      {
        "functionDeclarations": []
      }
    ]
  },
  "responseType": "stream"
}
call to gauth.request message: [{
  "error": {
    "code": 400,
    "message": "Request contains an invalid argument.",
    "errors": [
      {
        "message": "Request contains an invalid argument.",
        "domain": "global",
        "reason": "badRequest"
      }
    ],
    "status": "INVALID_ARGUMENT"
  }
}
]
GaxiosError: [{
  "error": {
    "code": 400,
    "message": "Request contains an invalid argument.",
    "errors": [
      {
        "message": "Request contains an invalid argument.",
        "domain": "global",
        "reason": "badRequest"
      }
    ],
    "status": "INVALID_ARGUMENT"
  }
}
]
    at Gaxios._request (C:\WORK\IVY_PROJECT\IVY_NEW\node_modules\.pnpm\gaxios@5.1.3\node_modules\gaxios\src\gaxios.ts:169:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async JWT.requestAsync (C:\WORK\IVY_PROJECT\IVY_NEW\node_modules\.pnpm\google-auth-library@8.9.0\node_modules\google-auth-library\build\src\auth\oauth2client.js:382:18)
    at async GAuthClient.request (C:\WORK\IVY_PROJECT\IVY_NEW\node_modules\.pnpm\@langchain+google-gauth@0.0.5_zod@3.22.4\node_modules\@langchain\google-gauth\dist\auth.cjs:32:25)
    at async RetryOperation._fn (C:\WORK\IVY_PROJECT\IVY_NEW\node_modules\.pnpm\p-retry@4.6.2\node_modules\p-retry\index.js:50:12) {
  response: {
    config: {
      url: 'hidden',
      method: 'POST',
      headers: [Object],
      data: [Object],
      responseType: 'stream',
      paramsSerializer: [Function: paramsSerializer],
      body: '{"contents":[{"role":"user","parts":[{"text":"You are a helpful assistant."}]},{"role":"model","parts":[{"text":"Ok"}]},{"role":"user","parts":[{"text":"Hi!"}]}],"generationConfig":{"temperature":0,"topK":40,"topP":0.8,"maxOutputTokens":1024,"stopSequences":[]},"tools":[{"functionDeclarations":[]}]}',
      validateStatus: [Function: validateStatus]
    },
    data: '[{\n' +
      '  "error": {\n' +
      '    "code": 400,\n' +
      '    "message": "Request contains an invalid argument.",\n' +
      '    "errors": [\n' +
      '      {\n' +
      '        "message": "Request contains an invalid argument.",\n' +
      '        "domain": "global",\n' +
      '        "reason": "badRequest"\n' +
      '      }\n' +
      '    ],\n' +
      '    "status": "INVALID_ARGUMENT"\n' +
      '  }\n' +
      '}\n' +
      ']',
    headers: {
      'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000',
      'cache-control': 'private',
      'content-encoding': 'gzip',
      'content-type': 'application/json; charset=UTF-8',
      date: 'Fri, 12 Apr 2024 08:00:13 GMT',
      server: 'scaffolding on HTTPServer2',
      'transfer-encoding': 'chunked',
      vary: 'Origin, X-Origin, Referer',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'SAMEORIGIN',
      'x-xss-protection': '0'
    },
    status: 400,
    statusText: 'Bad Request',
    request: {
      responseURL: 'hidden'
    }
  },
  config: {
    url: 'hidden',
    method: 'POST',
    headers: {
      'User-Agent': 'langchain-js/0-ChatConnection google-api-nodejs-client/8.9.0',
      Authorization: 'hidden',
      'x-goog-api-client': 'gl-node/20.10.0',
      'Content-Type': 'application/json'
    },
    data: { contents: [Array], generationConfig: [Object], tools: [Array] },
    responseType: 'stream',
    paramsSerializer: [Function: paramsSerializer],
    body: '{"contents":[{"role":"user","parts":[{"text":"You are a helpful assistant."}]},{"role":"model","parts":[{"text":"Ok"}]},{"role":"user","parts":[{"text":"Hi!"}]}],"generationConfig":{"temperature":0,"topK":40,"topP":0.8,"maxOutputTokens":1024,"stopSequences":[]},"tools":[{"functionDeclarations":[]}]}',
    validateStatus: [Function: validateStatus]
  },
  code: '400',
  attemptNumber: 1,
  retriesLeft: 6
}

### Description

 * I am trying to make toolCalllingAgent by createToolCallingAgent()
 * 
 * Note:
 * - ChatAthropic allows empty tools. e.g. tools = [].
 * - But ChatVertexAI causes 400 error with empty tools!!
 *
 * TODO:
 * - ChatVertexAI must allow empty tools

### System Info

  "dependencies": {
    "@langchain/anthropic": "^0.1.14",
    "@langchain/community": "^0.0.47",
    "@langchain/core": "^0.1.57",
    "@langchain/google-vertexai": "^0.0.5",
    "langchain": "^0.1.33",
    "ts-node": "^10.9.2",
    "zod": "^3.22.4",
    "zod-to-json-schema": "^3.22.5"
  }

platform: windows11
Node: v20.10.0
pnpm

**Comment by jacoblee93** [comment]
Oh jeez. Thanks for flagging, will have a look.

**Comment by jacoblee93** [comment]
Will push the fix later. You will need to update your dependencies since `@langchain/google-common` is a dependency of a dependency.
