### ISSUE TITLE
Error: Module not found: Can't resolve 'duck-duck-scrape'

### ISSUE THREAD

**Issue by yuripourre** [langchain-ai/langchainjs#5091]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```ts
export const duckDuckGoSearch = new DuckDuckGoSearch();
```

### Error Message and Stack Trace (if applicable)

```
./node_modules/@langchain/community/dist/tools/duckduckgo_search.js:2:0
Module not found: Can't resolve 'duck-duck-scrape'
```

### Description

When I import the `DuckDuckGoSearch` to my code, I get the error:

```
./node_modules/@langchain/community/dist/tools/duckduckgo_search.js:2:0
Module not found: Can't resolve 'duck-duck-scrape'
```

I believe is because the dependency `duck-duck-scrape` is not included in the package.json.

Should I go ahead and create a PR including it?
Or this is on purpose?
If it's by design, is there a way to get a warning instead of breaking the compilation?

### System Info

Platform: Linux
Node: v18.20.0

**Comment by jacoblee93** [comment]
It is a peer dependency - you will have to install it separately:

https://js.langchain.com/docs/integrations/tools/duckduckgo_search

This is to prevent unnecessary installs for folks who aren't using it.

**Comment by yuripourre** [comment]
@jacoblee93 thanks for the reply! I will include in my project.
