### ISSUE TITLE
unable to find callkeys

### ISSUE THREAD

**Issue by hemanth** [langchain-ai/langchainjs#5094]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```js
import { LLMChain } from "npm:langchain/chains";

import { BufferMemory } from "npm:langchain/memory";

const llmMemory = new BufferMemory({ memoryKey: "chat_history" });

const chatChain = new LLMChain({
  model,
  prompt,
  verbose: true,
  memory: llmMemory,
});
await chatChain.invoke({ question: "My name is Hemanth HM?" });
```

### Error Message and Stack Trace (if applicable)

```
Stack trace:
TypeError: Cannot use 'in' operator to search for 'callKeys' in undefined
    at LLMChain.getCallKeys (file:///deno/npm/registry.npmjs.org/langchain/0.1.30/dist/chains/llm_chain.js:103:37)
    at LLMChain._selectMemoryInputs (file://deno/npm/registry.npmjs.org/langchain/0.1.30/dist/chains/llm_chain.js:109:31)
    at LLMChain._formatValues (file:///deno/npm/registry.npmjs.org/langchain/0.1.30/dist/chains/base.js:128:74)
    at LLMChain.invoke (file:///deno/npm/registry.npmjs.org/langchain/0.1.30/dist/chains/base.js:50:39)
    at <anonymous>:3:17
  ```

### Description

Unable to use memory with gemma

### System Info

`v0.1.30`
`osx`
`deno`

It is bombing at `const callKeys = "callKeys" in this.llm ? this.llm.callKeys : [];`

**Comment by jacoblee93** [comment]
I believe the property name is `llm`:

```ts
const chatChain = new LLMChain({
  llm: model,
  prompt,
  verbose: true,
  memory: llmMemory,
});
```
