### ISSUE TITLE
Langchain Redis integration library has not been package/built despite changes being made

### ISSUE THREAD

**Issue by leejona16** [langchain-ai/langchainjs#5106]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

N/A

### Description

Apologies for using a bug for this as Im not sure how else to raise this issue, but the langchain-redis library has not been packaged despite having changes made to it last month. I tried raising this issue in the discussions section here:

https://github.com/langchain-ai/langchainjs/discussions/4881

but received no response. Is this something that can be resolved soon?

### System Info

N/A

**Comment by jacoblee93** [comment]
Sorry about that!
