### ISSUE TITLE
Next.js build failing after version 14.2 with ConversationChain

### ISSUE THREAD

**Issue by TheOrcDev** [langchain-ai/langchainjs#5235]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

The followind code: 
```
import { ChatOpenAI } from "@langchain/openai";
import { BufferMemory } from "langchain/memory";
import { ConversationChain } from "langchain/chains";

const model = new ChatOpenAI({
  modelName: process.env.GPT_MODEL,
  openAIApiKey: process.env.GPT_API_KEY,
  temperature: parseFloat(process.env.GPT_TEMPERATURE ?? "0.8"),
  maxTokens: parseInt(process.env.GPT_MAX_TOKENS ?? "1048"),
});

const memory = new BufferMemory();

const chain = new ConversationChain({
  llm: model,
  memory,
  verbose: true,
});
```

### Error Message and Stack Trace (if applicable)

Error message on build only:

```
./node_modules/.pnpm/langchain@0.1.36/node_modules/langchain/dist/chains/analyze_documents_chain.js + 5 modules
Cannot get final name for export 'getEncoding' of ./node_modules/.pnpm/@langchain+core@0.1.61_openai@4.38.5/node_modules/@langchain/core/utils/tiktoken.js

./node_modules/.pnpm/langchain@0.1.36/node_modules/langchain/dist/memory/entity_memory.js + 3 modules
Cannot get final name for export 'Serializable' of ./node_modules/.pnpm/@langchain+core@0.1.61_openai@4.38.5/node_modules/@langchain/core/load/serializable.js

./node_modules/.pnpm/langchain@0.1.36/node_modules/langchain/dist/output_parsers/openai_functions.js + 1 modules
Cannot get final name for export 'compare' of ./node_modules/.pnpm/@langchain+core@0.1.61_openai@4.38.5/node_modules/@langchain/core/utils/json_patch.js
```

### Description

Everything is working locally, only build is failing, so deployment is not possible.

### System Info

```
"langchain": "^0.1.36",
"next": "^14.2.3",
```

**Comment by hnykda** [comment]
It's very similar to what I saw in the past with https://github.com/langchain-ai/langchainjs/issues/2335 . 

We have production building fine, but now due to totally unrelated changes (really just some FE stuff and some DB comm) on a different feature branch, the build fails.

**Comment by TheOrcDev** [comment]
> It's very similar to what I saw in the past with #2335 .
> 
> We have production building fine, but now due to totally unrelated changes (really just some FE stuff and some DB comm) on a different feature branch, the build fails. The bot stuff are not helpful.
> 
> For us, it's the:
> 
> ```
> Failed to compile.
> 
> ./node_modules/langchain/dist/output_parsers/openai_functions.js + 1 modules
> Cannot get final name for export 'compare' of ./node_modules/@langchain/core/utils/json_patch.js
> ```
> 
> Anyway, I tried a similar fix as in that other PR, adding an import to somewhere in our codebase, and it works 🤦 :
> 
> ```
> // hacks.ts, import somewhere in your codebase
> import { compare } from '@langchain/core/utils/json_patch';
> const DoNotRemove = compare;
> ```

This weird eye hurting fix left me with two build problems :D

```
./node_modules/.pnpm/langchain@0.1.36/node_modules/langchain/dist/chains/analyze_documents_chain.js + 5 modules
Cannot get final name for export 'getEncoding' of ./node_modules/.pnpm/@langchain+core@0.1.61_openai@4.38.5/node_modules/@langchain/core/utils/tiktoken.js

./node_modules/.pnpm/langchain@0.1.36/node_modules/langchain/dist/memory/entity_memory.js + 3 modules
Cannot get final name for export 'Serializable' of ./node_modules/.pnpm/@langchain+core@0.1.61_openai@4.38.5/node_modules/@langchain/core/load/serializable.js
```

**Comment by hnykda** [comment]
You "just" have to hurt yourself a bit more by figuring out where from you could import those two `getEncoding` and `Serializable`.

**Comment by TheOrcDev** [comment]
> You _just_ have to hurt yourself a bit more by figuring out where from you could import those two `getEncoding` and `Serializable` and do the same shenanigas

Here is the fix, prepare yourself.

```
import { compare } from "@langchain/core/utils/json_patch";
import { Serializable } from "@langchain/core/load/serializable";
import { getEncoding } from "@langchain/core/utils/tiktoken";
import { RecursiveCharacterTextSplitter } from "langchain/text_splitter";

const DoNotRemoveCompare = compare;
const DoNotRemovegetEncoding = getEncoding;
const DoNotRemoveSerializable = Serializable;
const DoNotRemoveRecursiveCharacterTextSplitter = RecursiveCharacterTextSplitter;
```

That's all I can do before the actual fix. Thanks @hnykda !

**Comment by fsa317** [comment]
I'm also have this issue using next 14.2.* (if I downgrade to 14.1 it works)

**Comment by jacoblee93** [comment]
Hi folks, apologies for missing this - will dig in as soon as I can.

**Comment by jacoblee93** [comment]
It seems to work ok here (with 0.2.x):

https://github.com/langchain-ai/langchain-nextjs-template

I wonder if it's some shenanigans with multiple core versions? Could you check which version(s) are installed and try setting resolutions/overrides as shown here?

https://js.langchain.com/v0.2/docs/how_to/installation/#installing-integration-packages

**Comment by nagamejun** [comment]
In my case, this worked for me.

next.config.js
```
  experimental: {
    serverComponentsExternalPackages: ["langchain", "@langchain/core"],
  },
```
