### ISSUE TITLE
`functions` is deprecated and should be replaced with `tools`

### ISSUE THREAD

**Issue by jordanparker6** [langchain-ai/langchainjs#5237]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

Langchain.ts is using the deprecated function call API.

The following response body is sent by langchain.ts when using a tutorial example of function calling.

The `functions` option is deprecated and replaced by `tools` under the OpenAI spec.

```json
{
    "frequency_penalty": 0,
    "functions": [
        {
            "description": "Extracts the relevant information from the passage.",
            "name": "information_extraction",
            "parameters": {
                "properties": {
                    "info": {
                        "items": {
                            "properties": {
                                "description": "the persons name",
                                "title": "name",
                                "type": "string"
                            },
                            "type": "object"
                        },
                        "type": "array"
                    }
                },
                "required": [
                    "info"
                ],
                "type": "object"
            }
        }
    ],
    "messages": [
        {
            "content": "Extract and save the relevant entities mentioned in the following passage together with their properties.\n\nPassage:\nMy name is Jordan and I am a rocket scientist.\n",
            "role": "user"
        }
    ],
    "model": "gpt-3.5-turbo",
    "n": 1,
    "presence_penalty": 0,
    "stream": false,
    "temperature": 1,
    "top_p": 1
}
```

Some providers have completely dropped `functions` so this is creating compatibility issues.

### Error Message and Stack Trace (if applicable)

Fails to call function

### Description

The `functions` parameter is deprecated in favour of `tools`.

### System Info

any

**Comment by bracesproul** [comment]
This is true openai has deprecated it, however not all providers have as because of this we will not deprecate it on our end.
