### ISSUE TITLE
DOC: Broken text splitter API links

### ISSUE THREAD

**Issue by jjspace** [langchain-ai/langchainjs#5281]
### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

There are a handful of links to the API under the Text Splitters category that 404 and seem to point to an old version of the API docs

- https://js.langchain.com/docs/modules/data_connection/document_transformers/code_splitter
    - `RecursiveCharacterTextSplitter` Points to https://api.js.langchain.com/classes/langchain_text_splitter.RecursiveCharacterTextSplitter.html
    - instead of https://api.js.langchain.com/classes/langchain_textsplitters.RecursiveCharacterTextSplitter.html
    - Same with `SupportedTextSplitterLanguages`
- Similar issues with https://js.langchain.com/docs/modules/data_connection/document_transformers/recursive_text_splitter

It seems `langchain_text_splitter` should be replaced with `langchain_textsplitters`. probably good to do a documentation wide serch for that

**Comment by bracesproul** [comment]
Thank you for flagging this, I'l get to it soon!
