### ISSUE TITLE
getEnvironmentVariable utility always return undefined on Cloudflare Workers

### ISSUE THREAD

**Issue by davkorss** [langchain-ai/langchainjs#5303]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

https://github.com/langchain-ai/langchainjs/blob/main/langchain-core/src/utils/env.ts#L77
```typescript
export function getEnvironmentVariable(name: string): string | undefined {
  // Certain Deno setups will throw an error if you try to access environment variables
  // https://github.com/langchain-ai/langchainjs/issues/1412
  try {
    return typeof process !== "undefined"
      ? // eslint-disable-next-line no-process-env
        process.env?.[name]
      : undefined;
  } catch (e) {
    console.error(e);
    return undefined;
  }
}
```

### Description

Greetings!

In Cloudflare Workers, the use of the API process requires to be imported, and the compatibility flag “nodejs_compat” must be used.

https://developers.cloudflare.com/workers/runtime-apis/nodejs/process/

However, in the utilities the “node:process” module is not imported, so referencing the API process generates an error and undefined is returned from the catch.
This problem doesn't allow LangSmith to be used from Cloudflare Workers.
I've been trying several solutions since I don't think it's a good idea to solve the problem by importing the “node:process” module, since that would force everyone to add the compatibility flag “nodejs_compat” in their workers.
Maybe the model constructor could receive some tracing props, in the same way as the verbose property, which can also be obtained from environment variables, something like that:
```typescript
const llm = new ChatOpenAI({
  tracing: true,
  tracingProjectName: this.env.LANGCHAIN_PROJECT,
  tracingApiKey: this.env.LANGCHAIN_API_KEY,
  tracingApiUrl: this.env.LANGCHAIN_ENDPOINT,
  streaming: false,
  openAIApiKey: this.env.OPENAI_API_KEY,
  modelName: model,
  callbacks: [callbackHandlers],
  verbose: true,
  temperature: 0,
  configuration: {
    baseURL: this.env.CLOUDFLARE_AI_GATEWAY_OPENAI_ENDPOINT,
  },
});
```
If you have any idea how we can solve this, I can create the feature!

### System Info

platform Cloudflare Workers

**Comment by jacoblee93** [comment]
The other thing you could try (suggested by @efriis) is to manually set `process.env` from the passed in environment:

https://developers.cloudflare.com/workers/runtime-apis/nodejs/process/#processenv

**Comment by davkorss** [comment]
I understand that manually defining `process.env` will not change the fact that the `getEnvironmentVariable` utility will continue to return undefined from the catch, since in Cloudflare Workers the use of the process API must be explicitly imported `import * as process from 'node:process';` as shown in the docs.
I will try to manually pass the tracer, thank you very much for your time!

**Comment by jacoblee93** [comment]
Would this work?

```ts
import * as process from 'node:process';
process.env = env;
// tracing code
```

**Comment by davkorss** [comment]
Implementing that piece of code in the utility https://github.com/langchain-ai/langchainjs/blob/main/langchain-core/src/utils/env.ts would solve the problem. However, if I implement it myself in my project, it wouldn't solve anything, since using the `getEnvironmentVariable` function inside langchain, it would still have the same wrong behavior returning always undefined.
In short, it doesn't matter if I define `process.env` in my project, since langchain internally won't be able to retrieve its values when running in Cloudflare Workers.

**Comment by jeasonnow** [comment]
To address this issue, we cannot simply adjust `getEnvironmentVariable`. Instead, we need to follow these steps:
- Inject external environment variables into the global configuration.
- When `getEnvironmentVariable` retrieves environment variables, it should obtain them from both the external environment variables and `process.env`, according to priority.
This approach might help resolve the issue. I expect that the usage could be like this in the future:
```typescript
const llm = new ChatOpenAI({
  …otherOptions,
  configuration: {
    baseURL: this.env.CLOUDFLARE_AI_GATEWAY_OPENAI_ENDPOINT,
    externalEnvs: env, // env is the environment variables injected into their runtime environment by other platforms (cloudflare, vercel)
  },
});
```

(The externalEnvs parameter is one that I randomly named, but if possible, it could be replaced with a better name.)

**Comment by davkorss** [comment]
I like it, it looks much cleaner than what I suggested before, thank you very much!

**Comment by Mexassi** [comment]
I was having the same issue. Looks like a better nodejs compat is in the works at Cloudflare https://developers.cloudflare.com/workers/configuration/compatibility-flags/#nodejs-compatibility-flag.  Just adding the `compatibility_flags = ["experimental:nodejs_compat_v2"]` allows to support the import of `process` without the `node:` prefix. It still requires manually defining the vars in `process.env`. It's still experimental so I am sticking with manual tracing for now, however it's good to know it's coming.

**Comment by mattallty** [comment]
@Mexassi @davkorss 

There is a new flag (`nodejs_compat_populate_process_env`) available for Cloudflare workers that will auto populate `process.env` with the Cloudflare env vars/secrets.

You basically need to set the `nodejs_compat` flag **and** the `nodejs_compat_populate_process_env` flag.

See:
- https://developers.cloudflare.com/workers/runtime-apis/nodejs/process/#processenv
- https://developers.cloudflare.com/workers/configuration/compatibility-flags/#enable-auto-populating-processenv
