### ISSUE TITLE
AgentExcecutor Chains Are Deleting the Run Name

### ISSUE THREAD

**Issue by spencermize** [langchain-ai/langchainjs#5332]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```typescript 
  const agentExecutor = new AgentExecutor({
    agent,
    tools,
  }).withConfig({ runName: 'Hi test!' })

 const eventStream = agentExecutor.streamEvents(params, {
      version: 'v1',
 })
```

### Description

I've dug a bit though the source, and have found the following: 

In the `patchConfig.js` file, we have 
```javascript
        /**
         * If we're replacing callbacks we need to unset runName
         * since that should apply only to the same run as the original callbacks
         */
        delete newConfig.runName;
```
which is where my `Hi test` goes to die!

Interestingly, the `name` parameter is right in the actual stream events. I've tried to hit the Langsmith endpoint directly to set the run name, but that messes up other things (the output never gets filled out...?)

The name that ultimately gets logged to Langsmith is `AgentExecutor`.

### System Info

```
└─ langchain@npm:0.1.36
   ├─ Instances: 1
   ├─ Version: 0.1.36
   │ 
   └─ Dependencies
      ├─ @anthropic-ai/sdk@npm:^0.9.1 → npm:0.9.1
      ├─ @langchain/community@npm:~0.0.47 → npm:0.0.49
      ├─ @langchain/core@npm:~0.1.60 → npm:0.1.62
      ├─ @langchain/openai@npm:~0.0.28 → npm:0.0.28
      ├─ @langchain/textsplitters@npm:~0.0.0 → npm:0.0.0
      ├─ binary-extensions@npm:^2.2.0 → npm:2.2.0
      ├─ js-tiktoken@npm:^1.0.7 → npm:1.0.10
      ├─ js-yaml@npm:^4.1.0 → npm:4.1.0
      ├─ jsonpointer@npm:^5.0.1 → npm:5.0.1
      ├─ langchainhub@npm:~0.0.8 → npm:0.0.8
      ├─ langsmith@npm:~0.1.7 → npm:0.1.22
      ├─ ml-distance@npm:^4.0.0 → npm:4.0.1
      ├─ openapi-types@npm:^12.1.3 → npm:12.1.3
      ├─ p-retry@npm:4 → npm:4.6.2
      ├─ uuid@npm:^9.0.0 → npm:9.0.1
      ├─ yaml@npm:^2.2.1 → npm:2.4.1
      ├─ zod-to-json-schema@npm:^3.22.3 → npm:3.23.0
      └─ zod@npm:^3.22.4 → npm:3.23.7

**Comment by bracesproul** [comment]
Thanks for flagging this! Very strange error, it looks like it only happens when calling `.stream` or `.streamEvents`

I'll look into this and push a fix asap!
