### ISSUE TITLE
support for azureADTokenProvider in AzureChatOpenAI

### ISSUE THREAD

**Issue by ladrians** [langchain-ai/langchainjs#5410]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

Is there a chance to start supporting the `azureADTokenProvider` value?
Based on this update for [v4.41.1](https://github.com/openai/openai-node/compare/v4.41.0...v4.41.1) it is available to be used with the `AzureOpenAI` class.

### Error Message and Stack Trace (if applicable)

Not specified, the element is not present to be used.

### Description

The request is to add support for the `azureADTokenProvider` value provided by AzureChatOpenAI; [this example](https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/managed-identity) from Ms doc on how to use it, it is python but just as an exaple on its usage.

### System Info

langchain: 0.1.37

**Comment by jacoblee93** [comment]
CC @sarangan12 I think your last PR added this?

**Comment by jacoblee93** [comment]
I believe this was added in latest, please reopen if not!
