### ISSUE TITLE
Using Llama CPP locally an error occurs after many questions:

### ISSUE THREAD

**Issue by pironev** [langchain-ai/langchainjs#5481]
Using Llama CPP locally an error occurs after many questions:
```
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^
[Error: could not find a KV slot for the batch (try reducing the size of the batch or increase the context)]
```
The error occurs always when the generated responses exceed approximately 3500 Tokens circa 16000 Characters.
The context is probably too big. How to adjust this? I don't want to enlarge the context but rather have a context only on the last the last 1 or 2 questions.
The error can be simply reproduced by doing something like this:

 ```
const model  = new ChatLlamaCpp({ modelPath: llamaPath}) 
 const response_1 = await model.stream("Tell me a long story about a cat");
  for await (const chunk of response_1) {
      console.log(chunk.content);
  }
  //----------many other questions here--------------
  const response_7 = await model.stream("Tell me a long story about a horse");
  for await (const chunk of response_7) {
      console.log(chunk.content);
  }
```
PC used - Apple M1 Max, 32Gb

_Originally posted by @pironev in https://github.com/langchain-ai/langchainjs/discussions/5298_

**Comment by jeasonnow** [comment]
https://github.com/withcatai/node-llama-cpp/issues/136

This is an issue with the old version of node-llama-cpp that cannot automatically expand the `context`. Upgrading your node-llama-cpp to the latest `beta` version might solve the problem. Would you like to try that?

**Comment by pironev** [comment]
Thank you!
