### ISSUE TITLE
withStructuredOutput is not a function on ChatGoogleGenerativeAI

### ISSUE THREAD

**Issue by yharaskrik** [langchain-ai/langchainjs#5484]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```typescript
const genAi = new ChatGoogleGenerativeAI({});

console.log(genAi.withStructuredOutput); <-- yields undefined, calling it on the call results in below
```

### Error Message and Stack Trace (if applicable)

```
}).withStructuredOutput(schema);
   ^

TypeError: (intermediate value).withStructuredOutput is not a function
```

### Description

The `ChatGoogleGenerativeAI` class has the `withStructuredOutput` function on it, but it is `undefined`. If it is not implemented for this model then it should not be on the types.

```package.json
        "@langchain/community": "^0.2.0",
        "@langchain/core": "^0.2.0",
        "@langchain/google-genai": "^0.0.14",
        "@langchain/openai": "^0.0.33",
        "@langchain/redis": "^0.0.5",
        "langchain": "^0.2.0",
```

### System Info

Mac
yarn 1.22.7
node 18.20.2

**Comment by yharaskrik** [comment]
Oh I see the `withStructuredOutput` function is optional on the abstract `BaseLanguageModel` class. My IDE was not reflecting that, so the `ChatGoogleGenerativeAI` is not implementing it and that is why it is undefined.

**Comment by bracesproul** [comment]
The `withStructuredOutput` isn't implemented (or normal tool calling) in the `@langchain/google-genai` package. It's on my list to implement both sometime this week though! I'll use this issue as a tracker for when that goes in.

**Comment by yharaskrik** [comment]
Amazing thank you Brace! That's pretty much what I determined as well. I
went to try and do it myself but only got so far as copying the code from
the common package for those functions. I'm sure there's a better way just
not familiar with the structure of all the packages!

Thanks!

**Comment by bracesproul** [comment]
> g

That's how I was planning on going about it as well! If you want to take a stab at it, I wouldn't start until tmro. So if you can put up a PR before tmro morning I would love to use your implementation!

**Comment by bitsnaps** [comment]
The same applies for huggingface inference API, I'm getting the error `TypeError: llm.withStructuredOutput is not a function` even with models supporting function calling.

**Comment by jason-allen-oneal** [comment]
same with groq

**Comment by pndtr** [comment]
Are there anyone is facing the issue that using withStructuredOutput not calling tool

**Comment by Moe03** [comment]
same with me sometimes works sometimes doesn't on groq

**Comment by sstraus** [comment]
Same on Ollama

**Comment by ashishkujoy** [comment]
any update on this?
