### ISSUE TITLE
Anthropic default max tokens is less than Anthropic allows (4096 should be max, but restricted to 2048)

### ISSUE THREAD

**Issue by meyer9** [langchain-ai/langchainjs#5488]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

n/a

### Description

https://github.com/langchain-ai/langchainjs/blob/05c4c761464d43d76ffaf9ff2703395c0933fbcc/libs/langchain-anthropic/src/chat_models.ts#L453

Restricts max_tokens to 2048.

Anthropic says max tokens for all models is 4096: https://docs.anthropic.com/en/docs/models-overview#model-comparison

### System Info

n/a

**Comment by jacoblee93** [comment]
Thanks for the issue!

It's definitely a bit arbitrary but you can set it manually, and different models may have different max tokens so it's a losing battle to try to tie it to any specific number.

**Comment by jacoblee93** [comment]
IIRC Anthropic had very low limits (like 128 tokens) at some point in the past - I'm not sure if that's changed but I don't have a problem with the default as it currently is
