### ISSUE TITLE
Unable to obtain the streaming transmission method, it always returns only after receiving the entire text

### ISSUE THREAD

**Issue by liuhuapiaoyuan** [langchain-ai/langchainjs#5508]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

code :
```
let model =  new ChatZhipuAI({
    model: "glm-3-turbo", // Available models:
  })
for await (const chunk of await model.stream("hello , canyou  help me")) {
    console.log("|", chunk.content);
  }
```

### Error Message and Stack Trace (if applicable)

The message is received once, and I cannot obtain the streaming results

### Description

The message is received once, and I cannot obtain the streaming results

### System Info

langchain@0.2.0 | MIT | deps: 16 | versions: 271
Typescript bindings for langchain
https://github.com/langchain-ai/langchainjs/tree/main/langchain/

keywords: llm, ai, gpt3, chain, prompt, prompt engineering, chatgpt, machine learning, ml, openai, embeddings, vectorstores

dist
.tarball: https://registry.npmjs.org/langchain/-/langchain-0.2.0.tgz
.shasum: 555d84538962720cd7223f6c3ca4bd060978ebf3
.integrity: sha512-8c7Dg9OIPk4lFIQGyfOytXbUGLLSsxs9MV53cLODspkOGzaUpwy5FGBie30SrOxIEFJo+FDaJgpDAFO3Xi4NMw==
.unpackedSize: 3.4 MB

dependencies:
@langchain/core: ~0.2.0          binary-extensions: ^2.2.0        jsonpointer: ^5.0.1              ml-distance: ^4.0.0              uuid: ^9.0.0                     zod: ^3.22.4
@langchain/openai: ~0.0.28       js-tiktoken: ^1.0.12             langchainhub: ~0.0.8             openapi-types: ^12.1.3           yaml: ^2.2.1
@langchain/textsplitters: ~0.0.0 js-yaml: ^4.1.0                  langsmith: ~0.1.7                p-retry: 4                       zod-to-json-schema: ^3.22.3

maintainers:
- nfcampos <nuno@boringbits.io>
- jacoblee93 <jacoblee93@gmail.com>
- andrewnguonly <andrewnguonly@gmail.com>
- davidduong <david@duong.cz>
- hwchase17 <hw.chase.17@gmail.com>
- basproul <braceasproul@gmail.com>

dist-tags:
latest: 0.2.0  next: 0.2.0

**Comment by liuhuapiaoyuan** [comment]
When I use `ChatOpenAI`, I can get streaming transmission, while `import { ChatZhipuAI } from "@langchain/community/chat_models/zhipuai`;
`Unable to obtain

**Comment by liuhuapiaoyuan** [comment]
I think it should be `chain.stream` unable to pass the streaming parameter to the corresponding ChatZhipuAI.

**Comment by jeasonnow** [comment]
Since `ChatZhipuAI` has not yet implemented a custom `chain.stream`, I can provide an implementation. Please wait for the `PR`.

**Comment by liuhuapiaoyuan** [comment]
Okay, I think this should form a demand

**Comment by jacoblee93** [comment]
Thank you @jeasonnow!
