### ISSUE TITLE
Chroma vectorstore.similarity search is not returning results when chroma client is directly

### ISSUE THREAD

**Issue by justinlevi** [langchain-ai/langchainjs#5519]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

Here is my code: 

```typescript 
import { ChromaClient, DefaultEmbeddingFunction } from "chromadb";
import { ChatOpenAI, OpenAIEmbeddings } from "@langchain/openai";
import { Chroma } from "@langchain/community/vectorstores/chroma";

const url = "http://localhost:8010";
const query = "What is this library about?";

// THIS DOES NOT WORK
async function fetchDocumentsWithLangchain() {
  try {
    const vectorStore = new Chroma(new OpenAIEmbeddings(), {
      url,
    });

    // Perform a similarity search
    const response = await vectorStore.similaritySearch(query, 2);

    // Log and send the response
    console.log("Retrieved Documents:", response);
  } catch (error) {
    console.error("Error fetching Langchain vectors:", error);
  }
}

// THIS WORKS
const fetchDocumentsWithChromaDBClient = async () => {
  const client = new ChromaClient({
    path: url,
  });

  const collections = await client.listCollections();
  console.log("🚀 ~ collections", collections);

  const ef = new DefaultEmbeddingFunction();

  const collection = await client.getCollection({
    name: "pyansys",
    embeddingFunction: ef,
  });

  console.log(JSON.stringify(collection, null, 2));

  const results = await collection.query({
    queryTexts: [query],
    nResults: 2,
    // where: {"metadata_field": "is_equal_to_this"}, // optional filter
    // whereDocument: {"$contains":"search_string"} // optional filter
  });

  console.log("🚀 ~ results", results);
};


async function run() {
  // This works
  fetchDocumentsWithChromaDBClient()

  // This does not work
  fetchDocumentsWithLangchain()
}

run();
```

results in the following output:

```
🚀 ~ collections [
  {
    name: 'langchain-b636db29-3d63-47c0-a822-e345b88035df',
    id: '687b22a5-81e3-4d77-9b4b-a4e865445bac',
    metadata: null,
    tenant: 'default_tenant',
    database: 'default_database'
  },
  {
    name: 'langchain-b532f2ca-54ce-4d29-ba6f-95b9356a42ad',
    id: '868be5d2-9122-4418-bc41-4e6c199e48bd',
    metadata: null,
    tenant: 'default_tenant',
    database: 'default_database'
  },
  {
    name: 'pyansys',
    id: 'cb1b5a68-ce47-431d-b2db-0210dfedcc76',
    metadata: null,
    tenant: 'default_tenant',
    database: 'default_database'
  },
  {
    name: 'langchain-4ca4e812-cb89-4ef0-935b-27993cf98d4b',
    id: 'd96ba9df-44f0-453d-98a3-101ae772db61',
    metadata: null,
    tenant: 'default_tenant',
    database: 'default_database'
  }
]
{
  "name": "pyansys",
  "id": "cb1b5a68-ce47-431d-b2db-0210dfedcc76",
  "metadata": null,
  "api": {
    "basePath": "http://localhost:8010",
    "configuration": {
      "basePath": "http://localhost:8010"
    },
    "options": {}
  },
  "embeddingFunction": {
    "model": "Xenova/all-MiniLM-L6-v2",
    "revision": "main",
    "quantized": false,
    "progress_callback": null
  }
}
Retrieved Documents: []
🚀 ~ results {
  ids: [
    [
      'ad3b38b2-17a6-11ef-9997-f2d13e4e5577',
      '3349b7e6-17aa-11ef-9997-f2d13e4e5577'
    ]
  ],
  distances: [ [ 1.4828091937878527, 1.4828091937878527 ] ],
  metadatas: [ [ [Object], [Object] ] ],
  embeddings: null,
  documents: [
    [
      '{"page_content": "PyDPF-Core \\u2014 XXX-Core\\n\\nprint(model)  \\nHere is how you plot XX results:  \\[] OMITTED Languages", "XXX", "XX-X"]}, "type": "Document"}'
    ]
  ],
  uris: null,
  data: null,
  included: [ 'metadatas', 'documents', 'distances' ]
}

```

Note that using the ChromaClient directly results in documents being returned whereas the Langchain Chroma class returns zero results. 

The following python code works as expected as well: 

```Python
from langchain_chroma import Chroma
import chromadb
from chromadb.config import Settings
from IPython.display import Markdown
from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import PromptTemplate
from langchain_openai import ChatOpenAI
from langchain_openai import OpenAIEmbeddings

llm = ChatOpenAI(model='gpt-4-turbo', temperature=0, verbose=True)
embeddings = OpenAIEmbeddings()
query = "What library about?"
client = chromadb.HttpClient(host="localhost", port=8010, settings=Settings(allow_reset=True))
persistent_client = chromadb.PersistentClient()
db = Chroma(client=persistent_client, collection_name="pyansys", embedding_function=embeddings)


# Retrieve and generate using the relevant snippets of the blog.
retriever2 = db.as_retriever()
# prompt = hub.pull("rlm/rag-prompt")
prompt = PromptTemplate.from_template("""
You are an assistant for question-answering tasks. Use the following pieces of retrieved context to answer the question. If you don't know the answer, just say that you don't know. Try to keep the answer concise. If the answer has code, ensure you provide the code in a markdown code block format. Add the source URLs provided in the context at the end of the answer. 
Question: {question} 
Context: {context} 
Answer:
""")

def format_docs(docs):
    return "\n\n".join(doc.page_content for doc in docs)


rag_chain2 = (
    {"context": retriever2 | format_docs, "question": RunnablePassthrough()}
    | prompt
    | llm
    | StrOutputParser()
)

display(rag_chain2.invoke(query))
```

### Error Message and Stack Trace (if applicable)

None

### Description

I'm just trying to get a basic RAG example working with the chroma db vectorstore

### System Info

"yarn info langchain"
  "dependencies": {
    "@langchain/community": "^0.2.1",
    "@langchain/openai": "^0.0.33",
    "@types/node": "^20.12.12",
    "chromadb": "1.7.3-beta5",
    "chromadb-default-embed": "^2.13.2",
    "langchain": "^0.2.0",
    "typescript": "^5.4.5"
  },

langchain-ts-project  🚀 node --version          
v21.7.1

Mac

**Comment by jeasonnow** [comment]
Did you pass the `model` field for `embedding`? If not, please try again:
```typescript
const embeddings = new OpenAIEmbeddings({
  model: "text-embedding-3-large",
});
```

**Comment by justinlevi** [comment]
<img width="1556" alt="image" src="https://github.com/langchain-ai/langchainjs/assets/1117989/81bfd74e-7a75-4531-8b74-b51c50339ded">

Same result. Querying the chroma db vectorstore collection directly with the chromadb.ChromaClient works as expected. Querying the vectorstore through the langchain Chroma class via the similarity search returns zero results. 

// This still returns zero results
```Typescript
    const vectorStore = new Chroma(
      new OpenAIEmbeddings({ model: "text-embedding-3-large"}),
      {
        url,
      }
    );

```

**Comment by jeasonnow** [comment]
Please wait for this `PR` to be merged. In the meantime, you can try upgrading your `chromadb` to the latest version to resolve this issue.

**Comment by jeasonnow** [comment]
Perhaps my guess was incorrect. After carefully examining all the implementations, the current code is actually consistent with `langchain python`. I don't need to add an `embedding function` additionally. In `chromadb`, it only takes effect when using `queryTexts`. However, I found an issue with your code.
```typescript
const vectorStore = new Chroma(new OpenAIEmbeddings(), {
      url,
      collectionName: 'pyansys'
});
```
Maybe you should specify the `collection` you are querying. If you don't specify it, `langchain` will automatically generate a brand new `collection` and perform the query.
Your implementation in `python` is correct:
```python
llm = ChatOpenAI(model='gpt-4-turbo', temperature=0, verbose=True)
embeddings = OpenAIEmbeddings()
query = "What library about?"
client = chromadb.HttpClient(host="localhost", port=8010, settings=Settings(allow_reset=True))
persistent_client = chromadb.PersistentClient()
db = Chroma(client=persistent_client, collection_name="pyansys", embedding_function=embeddings)
```

**Comment by justinlevi** [comment]
Yes, I also noticed that bug in my code as well. After fixing that, I created a simplified repo to try and more clearly identify the issue.

https://github.com/justinlevi/ts-langchain-chromadb

After setting this up, I noticed that each time I was seeding the database, I'd see a chroma folder getting created on my host machine each time I was trying to seed the database. It seems that something I was doing was perhaps creating two client connections, one to the remote as well as a new one locally???

This version of my python code now seems to work as expected:

```
client = chromadb.HttpClient(host="localhost", port=8000, settings=Settings(allow_reset=True))
collection = client.get_or_create_collection("demo")
embeddings_function = OpenAIEmbeddings()

Chroma().from_documents(
    docs, embeddings_function, client=client, collection_name="demo"
)
```

This just removes the `persistent_client`. 

I can now run my typescript code with the latest versions of langchain and get documents returned from the remote chromadb connection. 

What is very strange though is that now my chroma db client fails with the following error: 

```
🚀 ~ results { error: 'InvalidDimension' }
```

I was not getting this error with ` "chromadb": "1.7.3-beta5",`?? My goal was to get this to work with langchain js though so I guess I'm just going to let this go as a mystery for now. This remaining issue also seems more related to the chromadb nodejs client library at this point so no need to dive in further in this issue. 

@jeasonnow appreciate you diving into this with me. Hopefully that github repo will help someone else in the future

**Comment by jacoblee93** [comment]
Hey apologies for losing track of this!

There were a few issues with the Chroma JS library in the past, and as a result we set the peer dependency to `*` until we could add a separately installable integration package to avoid breaking the broader `@langchain/community` package.

Will prioritize that and update this issue when that's done ready!
