### ISSUE TITLE
Memory module is export as /memory/index

### ISSUE THREAD

**Issue by chunf** [langchain-ai/langchainjs#5525]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

import { ConversationSummaryBufferMemory } from 'langchain/memory'

### Error Message and Stack Trace (if applicable)

Error: Package subpath './memory' is not defined by "exports" in node_modules\langchain\package.json

### Description

I am trying to use ConversationSummaryBufferMemory by importing it from 'langchain/memory'. The issue is fix if I modify line 1233 of package.json of langchain to 
  "./memory": {
      "types": {
        "import": "./memory/index.d.ts",
        "require": "./memory/index.d.cts",
        "default": "./memory/index.d.ts"
      },
      "import": "./memory/index.js",
      "require": "./memory/index.cjs"
    },

### System Info

Node v20.9.0
        "langchain": "^0.2.1",

**Comment by jacoblee93** [comment]
Very sorry about that, just shipped a fix to readd the old entrypoint.
