### ISSUE TITLE
modules not working correctly

### ISSUE THREAD

**Issue by Pratham271** [langchain-ai/langchainjs#5540]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

import { PremEmbeddings } from "@langchain/community/embeddings/premai";
import { Pinecone } from '@pinecone-database/pinecone';
import { PineconeStore } from "@langchain/pinecone";

export async function getVectorStore(){
    const embeddings = new PremEmbeddings({
        // In Node.js defaults to process.env.PREM_API_KEY
        apiKey: process.env.PREM_API_KEY,
        // In Node.js defaults to process.env.PREM_PROJECT_ID
        project_id: 1744,
        model: "text-embedding-3-large", // The model to generate the embeddings
      });
      
    const pineconeClient = new Pinecone({
        apiKey: process.env.PINECONE_API_KEY!
    });

    const index = pineconeClient.Index(process.env.PINECONE_INDEX_NAME!);

    const vectorStore = await PineconeStore.fromExistingIndex(embeddings, {
        pineconeIndex: index,
        textKey: 'text',
      });
    
    return vectorStore
}

### Error Message and Stack Trace (if applicable)

Package path ./structured_query is not exported from package /Users/prathamchauhan/Documents/Next-Projects/pratham-portfolio/node_modules/@langchain/core (see exports field in /Users/prathamchauhan/Documents/Next-Projects/pratham-portfolio/node_modules/@langchain/core/package.json)

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/@langchain/pinecone/dist/index.js
./node_modules/@langchain/pinecone/index.js
./src/lib/pineconedb.ts
./src/actions/chat.ts
./src/app/layout.tsx

### Description

I am trying to get the pinecone db vector store to query the data that I saved by running a different ts script.
Not only this it is giving me error with neon vector store 
Cannot find module '@langchain/community/vectorstores/neon' or its corresponding type declarations.
Even though I have gone through docs and github discussions

### System Info

npm version 10.7.0

**Comment by jacoblee93** [comment]
Sorry you're running into this - what version of `@langchian/core` do you have installed?

**Comment by Pratham271** [comment]
{
  "name": "pratham-portfolio",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@datastax/astra-db-ts": "^1.2.0",
    "@emailjs/browser": "^4.3.3",
    "@langchain/cohere": "^0.0.10",
    "@langchain/community": "^0.2.2",
    "@langchain/core": "^0.2.0",
    "@langchain/pinecone": "^0.0.6",
    "@pinecone-database/pinecone": "^2.2.1",
    "@radix-ui/react-label": "^2.0.2",
    "@react-three/drei": "^9.103.0",
    "@react-three/fiber": "^8.16.1",
    "@tabler/icons-react": "^3.1.0",
    "@tsparticles/engine": "^3.3.0",
    "@tsparticles/react": "^3.0.0",
    "@tsparticles/slim": "^3.3.0",
    "@upstash/redis": "^1.31.2",
    "@vercel/analytics": "^1.2.2",
    "@vercel/speed-insights": "^1.0.10",
    "ai": "^3.1.14",
    "clsx": "^2.1.0",
    "cohere-ai": "^7.10.1",
    "framer-motion": "^11.0.23",
    "langchain": "^0.2.2",
    "mini-svg-data-uri": "^1.4.4",
    "next": "14.1.4",
    "nodemailer": "^6.9.13",
    "openai": "^4.47.1",
    "react": "^18",
    "react-dom": "^18",
    "react-icons": "^5.0.1",
    "tailwind-merge": "^2.2.2",
    "ts-node": "^10.9.2"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "autoprefixer": "^10.0.1",
    "eslint": "^8",
    "eslint-config-next": "14.1.4",
    "postcss": "^8",
    "tailwindcss": "^3.3.0",
    "typescript": "^5"
  }
}
this is my package.json

**Comment by jacoblee93** [comment]
Hey @Pratham271, based on the error you somehow have a 0.1.x version of core installed, possibly from one of the integration packages you have. The `@langchain/pinecone` package relies on a core entrypoint only available in 0.2.0, but had deps that mistakenly hinted it would work with 0.1.0.

I've opened a PR fixing that, but the better solution to ensure that your package manager pulls in the right version is to set `resolutions`/`overrides` for `@langchain/core` depending on your package manager. Follow these directions:

https://js.langchain.com/v0.2/docs/how_to/installation/#installing-integration-packages

Can you try that and let me know if it works?

**Comment by Pratham271** [comment]
Hey @jacoblee93, thanks for the help it worked and also I understood the issue.

**Comment by jacoblee93** [comment]
Glad to hear that! Thanks for your patience.
