### ISSUE TITLE
Error: error: { code: '404', message: 'Resource not found' },

### ISSUE THREAD

**Issue by Abhicurio** [langchain-ai/langchainjs#5550]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

const model = new OpenAI({

  

  temperature: 0.9,
  apiKey: process.env.AZURE_OPENAI_API_KEY,
  azureOpenAIApiVersion: process.env.OPENAI_API_VERSION,
  azureOpenAIApiInstanceName: process.env.AZURE_API_INSTANCE,
  azureOpenAIApiDeploymentName: process.env.AZURE_DEPOYMENT_NAME,

});

### Error Message and Stack Trace (if applicable)

Error: Azure OpenAI API instance name not found
    at new OpenAIEmbeddings (/Users/abhijeet/Workspace/Node/UserBackend/node_modules/@langchain/openai/dist/embeddings.cjs:162:23)
    at new AzureOpenAIEmbeddings (/Users/abhijeet/Workspace/Node/UserBackend/node_modules/@langchain/openai/dist/azure/embeddings.cjs:16:9)
    at Object.getAns (/Users/abhijeet/Workspace/Node/UserBackend/lib/modules/v3/chatbot/facade.js:52:7)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Azure OpenAI API instance name not found
    at new OpenAIEmbeddings (/Users/abhijeet/Workspace/Node/UserBackend/node_modules/@langchain/openai/dist/embeddings.cjs:162:23)
    at new AzureOpenAIEmbeddings (/Users/abhijeet/Workspace/Node/UserBackend/node_modules/@langchain/openai/dist/azure/embeddings.cjs:16:9)
    at Object.getAns (/Users/abhijeet/Workspace/Node/UserBackend/lib/modules/v3/chatbot/facade.js:52:7)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

### Description

When I am trying initialization the azure open instance it throws error 

Error: Azure OpenAI API instance name not found
    at new OpenAIEmbeddings (/Users/abhijeet/Workspace/Node/UserBackend/node_modules/@langchain/openai/dist/embeddings.cjs:162:23)
    at new AzureOpenAIEmbeddings (/Users/abhijeet/Workspace/Node/UserBackend/node_modules/@langchain/openai/dist/azure/embeddings.cjs:16:9)
    at Object.getAns (/Users/abhijeet/Workspace/Node/UserBackend/lib/modules/v3/chatbot/facade.js:52:7)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Azure OpenAI API instance name not found
    at new OpenAIEmbeddings (/Users/abhijeet/Workspace/Node/UserBackend/node_modules/@langchain/openai/dist/embeddings.cjs:162:23)
    at new AzureOpenAIEmbeddings (/Users/abhijeet/Workspace/Node/UserBackend/node_modules/@langchain/openai/dist/azure/embeddings.cjs:16:9)
    at Object.getAns (/Users/abhijeet/Workspace/Node/UserBackend/lib/modules/v3/chatbot/facade.js:52:7)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

### System Info

"@langchain/openai": "^0.0.33",

**Comment by jacoblee93** [comment]
Can you try the Dosu comment above?

Docs here: https://js.langchain.com/v0.2/docs/integrations/chat/azure

**Comment by Abhicurio** [comment]
@jacoblee93 Please check below code which i am trying with 
  const model = new AzureOpenAI({
    azureOpenAIApiKey: process.env.AZURE_OPENAI_API_KEY,
    azureOpenAIApiInstanceName: process.env.AZURE_API_INSTANCE,
    azureOpenAIApiVersion: process.env.AZURE_API_VERSION,
    azureOpenAIApiDeploymentName: process.env.AZURE_DEPLOYMENT_NAME,
    temperature: 0.9,
  });
<img width="860" alt="Screenshot 2024-05-26 at 9 45 24 PM" src="https://github.com/langchain-ai/langchainjs/assets/104524640/2eec0291-b0cc-4cc9-9b4a-8f0ba6b2269d">

and getting error Error: Azure OpenAI API deployment name not found
    at new OpenAI (/Users/abhijeet/Workspace/Node/UserBackend/node_modules/@langchain/openai/dist/llms.cjs:311:23)
    at new AzureOpenAI (/Users/abhijeet/Workspace/Node/UserBackend/node_modules/@langchain/openai/dist/azure/llms.cjs:22:9)
    at Object.getAns (/Users/abhijeet/Workspace/Node/UserBackend/lib/modules/v3/chatbot/facade.js:39:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Help me with what I am doing wrong

**Comment by jacoblee93** [comment]
How are you importing the module? Are you using the AD provider? And can you share your `package.json`?

I wonder if this is related to #5521

**Comment by Abhicurio** [comment]
The issue is i am not using the same key name which langchain provide in docs in .env file .
when I add same key in .env this error gone 
now I am getting 404 resource not found error 
NotFoundError: 404 Resource not found
    at APIError.generate (/Users/abhijeet/Workspace/Node/UserBackend/node_modules/openai/error.js:54:20)
    at AzureOpenAI.makeStatusError (/Users/abhijeet/Workspace/Node/UserBackend/node_modules/openai/core.js:263:33)
    at AzureOpenAI.makeRequest (/Users/abhijeet/Workspace/Node/UserBackend/node_modules/openai/core.js:306:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/abhijeet/Workspace/Node/UserBackend/node_modules/@langchain/openai/dist/azure/embeddings.cjs:67:29
    at async RetryOperation._fn (/Users/abhijeet/Workspace/Node/UserBackend/node_modules/p-retry/index.js:50:12) {
  status: 404,
  headers: {
    'apim-request-id': '739b8e6f-715c-4446-8150-60c63c4cb311',
    'content-length': '56',
    'content-type': 'application/json',
    date: 'Sun, 26 May 2024 16:51:03 GMT',
    'strict-transport-security': 'max-age=31536000; includeSubDomains; preload',
    'x-content-type-options': 'nosniff'
  },
  request_id: undefined,
  error: { code: '404', message: 'Resource not found' },
  code: '404',
  param: undefined,
  type: undefined,
  attemptNumber: 1,
  retriesLeft: 6
}
I am providing correct API key, instance name , API version correctly I double check it
@jacoblee93 Please help

**Comment by jacoblee93** [comment]
I'm so confused. Can you answer my questions above?

**Comment by Abhicurio** [comment]
[package.json](https://github.com/langchain-ai/langchainjs/files/15448484/package.json)
[facade.txt](https://github.com/langchain-ai/langchainjs/files/15448487/facade.txt)
@jacoblee93 I am attaching my project pakage.json file along with langchain function file please check and help

**Comment by jeasonnow** [comment]
Your issue is related to #5521  , but you can easily resolve it by changing the environment variable names to those conventionally used within `langchainjs`. @Abhicurio 

`AZURE_API_INSTANCE` -> `AZURE_OPENAI_API_INSTANCE_NAME`
`AZURE_DEPOYMENT_NAME` -> `AZURE_OPENAI_API_EMBEDDINGS_DEPLOYMENT_NAME` | `AZURE_OPENAI_API_DEPLOYMENT_NAME`

And use like this.

```typescript
const model = new OpenAI({
  temperature: 0.9,
});
```

**Comment by Abhicurio** [comment]
> Your issue is related to #5521 , but you can easily resolve it by changing the environment variable names to those conventionally used within `langchainjs`. @Abhicurio
> 
> `AZURE_API_INSTANCE` -> `AZURE_OPENAI_API_INSTANCE_NAME` `AZURE_DEPOYMENT_NAME` -> `AZURE_OPENAI_API_EMBEDDINGS_DEPLOYMENT_NAME` | `AZURE_OPENAI_API_DEPLOYMENT_NAME`
> 
> And use like this.
> 
> ```ts
> const model = new OpenAI({
>   temperature: 0.9,
> });
> ```

Hi @jeasonnow 
I've updated the text to make it clearer:

"I changed the environment variable to fix the issue, but now I'm getting an error: { code: '404', message: 'Resource not found' }. When I try to access the Azure URL directly, it works, but when I use the langchain module, it throws a 404 resource not found error. I've attached my code file and package.json file. Can you take a look and see what mistake I'm making?"

**Comment by jeasonnow** [comment]
> > Your issue is related to #5521 , but you can easily resolve it by changing the environment variable names to those conventionally used within `langchainjs`. @Abhicurio
> > `AZURE_API_INSTANCE` -> `AZURE_OPENAI_API_INSTANCE_NAME` `AZURE_DEPOYMENT_NAME` -> `AZURE_OPENAI_API_EMBEDDINGS_DEPLOYMENT_NAME` | `AZURE_OPENAI_API_DEPLOYMENT_NAME`
> > And use like this.
> > ```ts
> > const model = new OpenAI({
> >   temperature: 0.9,
> > });
> > ```
> 
> Hi @jeasonnow I've updated the text to make it clearer:
> 
> "I changed the environment variable to fix the issue, but now I'm getting an error: { code: '404', message: 'Resource not found' }. When I try to access the Azure URL directly, it works, but when I use the langchain module, it throws a 404 resource not found error. I've attached my code file and package.json file. Can you take a look and see what mistake I'm making?"

Okay, I understand. Could you please provide the specific details of the request you made through the `azure REST API`? A `curl` command would help me better analyze the issue.

**Comment by Abhicurio** [comment]
> > > Your issue is related to #5521 , but you can easily resolve it by changing the environment variable names to those conventionally used within `langchainjs`. @Abhicurio
> > > `AZURE_API_INSTANCE` -> `AZURE_OPENAI_API_INSTANCE_NAME` `AZURE_DEPOYMENT_NAME` -> `AZURE_OPENAI_API_EMBEDDINGS_DEPLOYMENT_NAME` | `AZURE_OPENAI_API_DEPLOYMENT_NAME`
> > > And use like this.
> > > ```ts
> > > const model = new OpenAI({
> > >   temperature: 0.9,
> > > });
> > > ```
> > 
> > 
> > Hi @jeasonnow I've updated the text to make it clearer:
> > "I changed the environment variable to fix the issue, but now I'm getting an error: { code: '404', message: 'Resource not found' }. When I try to access the Azure URL directly, it works, but when I use the langchain module, it throws a 404 resource not found error. I've attached my code file and package.json file. Can you take a look and see what mistake I'm making?"
> 
> Okay, I understand. Could you please provide the specific details of the request you made through the `azure REST API`? A `curl` command would help me better analyze the issue.
> 
> > Do not leak your critical information: `apiKey` `instanceName`

@jeasonnow I am using langchain npm module 
const {
  AzureOpenAI,
} = require("@langchain/openai");

  const model = new AzureOpenAI({
    temperature: 0.9,
  });

**Comment by jeasonnow** [comment]
Did you use `AZURE_OPENAI_BASE_PATH`? @Abhicurio

**Comment by Abhicurio** [comment]
> AZURE_OPENAI_BASE_PATH

Yes i used , it is in my .env file 
here below are the keys is in .env file AZURE_OPENAI_API_KEY="6e520664d61349b082f6ef4588d4ddd6"
AZURE_OPENAI_API_VERSION=
AZURE_OPENAI_API_INSTANCE_NAME=
AZURE_OPENAI_API_DEPLOYMENT_NAME= 
AZURE_OPENAI_BASE_PATH=
@jeasonnow

**Comment by jeasonnow** [comment]
https://github.com/langchain-ai/langchainjs/blob/ed1f3fbcafdb494e7807f60d5ede74cf75f57b4b/libs/langchain-openai/src/utils/azure.ts#L32-L65

If you used `AZURE_OPENAI_BASE_PATH`, it will generate a `baseURL` that matches your configuration. Please first confirm that your `basePath` is accessible.

**Comment by Abhicurio** [comment]
@jeasonnow 
<img width="860" alt="Screenshot 2024-05-27 at 3 06 32 PM" src="https://github.com/langchain-ai/langchainjs/assets/104524640/d848ca88-f0f0-4d7e-b36d-eeae7dc4d742">
I have put the console for .env file and I am able to access the baseurl

**Comment by jeasonnow** [comment]
> .openai.azure.com/openai/deployments

Please check the source code I sent. If you declare `AZURE_OPENAI_BASE_PATH` here, your `baseURL` will be `${AZURE_OPENAI_BASE_PATH}/${AZURE_OPENAI_API_DEPLOYMENT_NAME}`, which is **clearly incorrect**. If you want to ensure normal usage, please remove `AZURE_OPENAI_BASE_PATH` or set `AZURE_OPENAI_BASE_PATH` to `https://dev-curio.openai.azure.com/openai/deployments`.

**Comment by Abhicurio** [comment]
@jeasonnow Thanks you so much it is working now 
issue is azure providing the baseUrl that need openai/deployments after that 

Thanks a lot @jeasonnow

**Comment by brja** [comment]
@jeasonnow

I confirm that appending the postfix '/openai/deployments' to the AZURE_OPENAI_BASE_PATH resolves the issue. However, I am wondering if the Python version is more resilient when this postfix is omitted.
``` python
from langchain_openai import AzureChatOpenAI

llm = AzureChatOpenAI(
    ...
    azure_endpoint="NOTE THAT THIS DOES NOT NEED THE 'openai/deployments' POSTFIX"
    ...
)
```
