### ISSUE TITLE
500 Error when invoking AstraDBVectorStore from API route in Next.js 14

### ISSUE THREAD

**Issue by Kiran-Wicksteed** [langchain-ai/langchainjs#5552]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

const astraConfig: AstraLibArgs = {
  token,
  endpoint,
  collection: collectionVar,
  collectionOptions: {
    vector: {
      dimension: 1536,
      metric: "cosine",
    },
  },
};

export async function getVectorStore() {
  return AstraDBVectorStore.fromExistingIndex(
    new OpenAIEmbeddings({ modelName: "text-embedding-3-small" }),
    astraConfig
  );
}

//API Route Invokation
  const retriever = (await getVectorStore()).asRetriever();

### Error Message and Stack Trace (if applicable)

Error: Error loading the fetch-h2 client for the DataAPIClient... try setting httpOptions.client to 'fetch'

### Description

I'm getting an error when attempting to invoke my AstraDBVectorStore instance from an API route in Next.js 14.

Invoking this function elsewhere in my application works fine.

 

### System Info

macOS 14.5
Node **v20.6.1**

**Comment by Kiran-Wicksteed** [comment]
@dosu, no luck with your approach

**Comment by jacoblee93** [comment]
Hey sorry you're running into this - have you set your route to run in a Node env? The integration is Node-only:

https://js.langchain.com/v0.2/docs/integrations/vectorstores/astradb

If you have, CC @mfortman11

**Comment by Sandeepreddyr12** [comment]
hey @Kiran-Wicksteed , i'm facing same issue in with current project, cloned but perfectly working from previous project https://github.com/Sandeepreddyr12/My-Portfolio,

please let me know if u had any solution , thank u.
