### ISSUE TITLE
DOC:  How to merge or use multiple retrievers?

### ISSUE THREAD

**Issue by djaffer** [langchain-ai/langchainjs#5554]
### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Idea or request for content:

The documentation misses this use case. Based of search seems python has the merger_retriever but js doesn't

**Comment by jeasonnow** [comment]
The function `merge_retrievers` similar to Python's has not been implemented yet, but I can submit a PR to achieve this.

**Comment by djaffer** [comment]
@jeasonnow the new function is now invoke instead of get relevant documents.

**Comment by jeasonnow** [comment]
I believe this applies to all `retriever` instances. You can try using my code locally to see how it works; the usage is consistent with Python's approach.
@djaffer
