### ISSUE TITLE
Type 'ChatOpenAI<ChatOpenAICallOptions>' is not assignable to type 'RunnableLike<any, any>'

### ISSUE THREAD

**Issue by bianbianzhu** [langchain-ai/langchainjs#5565]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

The following code: 
```typescript
  const model = new ChatOpenAI({
    model: "gpt-4o",
  });

  const chain = RunnableSequence.from([
    model,
  ]);
```

### Error Message and Stack Trace (if applicable)

Type 'ChatOpenAI<ChatOpenAICallOptions>' is not assignable to type 'RunnableLike<any, any>'.
  Type 'ChatOpenAI<ChatOpenAICallOptions>' is not assignable to type 'RunnableMapLike<any, any>'.
    Index signature for type 'string' is missing in type 'ChatOpenAI<ChatOpenAICallOptions>'.ts(2322)

### Description

Simply use any examples from the Langchain js official website. 
It seams that the `ChatOpenAI<ChatOpenAICallOptions>` class from OpenAI is not assignable to `Runnable`

### System Info

"langchain": "^0.2.2"
"typescript": "^5.4.5"
Node: v20.12.1
yarn: 1.22.22

tsconfig:
```JSON
{
  "compilerOptions": {
    /* Language and Environment */
    "target": "ES2022",
    "moduleDetection": "force",

    /* Modules */
    "module": "commonjs",
    "rootDir": "src",
    "resolveJsonModule": true,

    /* JavaScript Support */
    "allowJs": true,

    /* Emit */
    "sourceMap": true,
    "outDir": "dist",

    /* Interop Constraints */
    "isolatedModules": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    /* Type Checking */
    "strict": true,
    "noImplicitAny": true,
    "useUnknownInCatchVariables": true,
    // "noUnusedLocals": true,
    // "noUnusedParameters": true,
    "noUncheckedIndexedAccess": true,
    "skipLibCheck": true
  }
}
```

**Comment by logemann** [comment]
Just wanted to report the same bug. The AI answer mentions a deprecated API so i wont dig deeper into this solution....

But for more context in that problem space. The alternative to RunnableSequence would be to use pipe which also has type problems. So this doesnt work either:

`const chain = prompt.pipe(model).pipe(outputParser);`

But back to RunnableSequence. When leaving out the outputParser (HttpResponseOutputParser()) this is ok for the compiler:

```
    const chainX = RunnableSequence.from([prompt, new ChatOpenAI({
      model: "gpt-4",
    })]);
```

And now the super weird thing, this isnt:

```
    const model2 = new ChatOpenAI({
      model: "gpt-4",
    })
    const chainX = RunnableSequence.from([prompt, model2]);
```

At this point i thought my TS compiler must be broken because i ve never seen a difference between inlining and non-inlining when it comes to compiling / linting.

**Comment by bianbianzhu** [comment]
I've managed to fix this issue by completely removing all the dependencies and reinstalling them. Caching issue maybe? 😖😖😖

**Comment by leitdeux** [comment]
Like @bianbianzhu I also had to *manually remove* (`npm rm ...`) each langchain dependency and only then attempt to re-install them. Simply deleting `node_modules` and running `npm i` didn't have an effect. Once I removed and re-installed each package, the TS compiler errors disappeared (ones such as ``ChatPromptTemplate` is not assignable to `Runnable``).

**Comment by bracesproul** [comment]
hey @bianbianzhu [this doc](https://js.langchain.com/v0.2/docs/how_to/installation#installing-integration-packages) should have the answer you're looking for. This issue should be fixed when you set overrides/resolutions/the proper field for your pkg manager for `@langchain/core`

I also suggest installing `@langchain/core` as a hard dependency, along with your other LangChain packages.

**Comment by IgorHalfeld** [comment]
> I've managed to fix this issue by completely removing all the dependencies and reinstalling them. Caching issue maybe? 😖😖😖

@bianbianzhu it worked here
