### ISSUE TITLE
ChatBaiduWenxin stream mode doesn't work as expected

### ISSUE THREAD

**Issue by Robert-ZLF** [langchain-ai/langchainjs#5567]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```typescript     
const model = new ChatBaiduWenxin({
    model: "ERNIE-Bot", // Available models are shown above
    streaming: true,
    temperature: 1,
    baiduApiKey: BAIDU_API_KEY, // In Node.js defaults to process.env.BAIDU_API_KEY
    baiduSecretKey: BAIDU_SECRET_KEY, // In Node.js defaults to process.env.BAIDU_SECRET_KEY
});

const stream = await model.stream("Hello! Tell me about yourself.");
const chunks = [];
for await (const chunk of stream) {
   chunks.push(chunk);
   console.log(`${chunk.content}|`);
}
```

### Error Message and Stack Trace (if applicable)

Current output is return the entire final results
<img width="1755" alt="image" src="https://github.com/langchain-ai/langchainjs/assets/42110848/9ae1dcfb-1f50-4b84-a7a6-f6080887e608">
it should be streaming mode return like this
```
|
Hello|
!|
 I'm|
 an|
 AI|
 language|
 model|
 created|
 by|
 Open|
...
```

### Description

When using ChatBaiduWenxin, how to return in a streaming fashion instead of returning a whole readable stream.

### System Info

langchain 0.2.2
mac

**Comment by jeasonnow** [comment]
`ChatBaiduWenxin` does not implement `ChatBaiduWenxin.stream`; it will default to calling the parent class and return data in non-streaming mode. If you want to use the `stream` mode, you can try this:
```typescript
let result = ''
const model = new ChatBaiduWenxin({
    model: "ERNIE-Bot", // Available models are shown above
    streaming: true,
    temperature: 1,
    baiduApiKey: BAIDU_API_KEY, // In Node.js defaults to process.env.BAIDU_API_KEY
    baiduSecretKey: BAIDU_SECRET_KEY, // In Node.js defaults to process.env.BAIDU_SECRET_KEY,
    callbacks: [
      {
        async handleLLMNewToken(token: string) {
          result += token;
          console.log(`${token}|`);
        },
      },
    ],
});
```
@Robert-ZLF
