### ISSUE TITLE
Missing apiUrl documentation for running UnstructuredLoader locally

### ISSUE THREAD

**Issue by andrewdoro** [langchain-ai/langchainjs#5579]
### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

I followed the setup for Unstructured from 
https://js.langchain.com/v0.2/docs/integrations/document_loaders/file_loaders/unstructured/#usage

I had a problem getting the error `"API key is malformed, please type the API key correctly in the header."`. I thought I was running unstructured locally but it seems like the default option was their API instead of localhost.
https://github.com/langchain-ai/langchainjs/blob/61d69f4a97807fe42fbbdcaddc0342bf286666ff/langchain/src/document_loaders/fs/unstructured.ts#L142

### Idea or request for content:

I think adding this to the local setup section should be enough.
```ts
 const unstructuredOptions = {
    apiUrl: "http://localhost:8000/general/v0/general",
  };
  ```

**Comment by bracesproul** [comment]
You're still required to provide an API key even if running locally. Sign up for one [here](https://unstructured.io/api-key) (free), and they'll send you an email with a key.

**Comment by andrewdoro** [comment]
I understand that I need the key to use their API.

 For the local instance I was able to run it locally **without** an API Key by using the docker setup. 
 
 ```ts
  const loader = new UnstructuredLoader(`pdfs/${randomName}.pdf`, {
    apiUrl: "http://localhost:8000/general/v0/general",
    apiKey: "stuff",
    strategy: "hi_res",
  });
 ```

This issue was related to the local setup of Unstructured. According to docs you can run this docker command  to start a local instance.
```
docker run -p 8000:8000 -d --rm --name unstructured-api quay.io/unstructured-io/unstructured-api:latest --port 8000 --host 0.0.0.0
```
To actually consume this instance you also have to add the apiUrl. I'm proposing adding to the docs for people wanting to run unstructured locally:
    `apiUrl: "http://localhost:8000/general/v0/general",`
