### ISSUE TITLE
Update Unstructured Docker Image Reference in Documentation

### ISSUE THREAD

**Issue by sarfudheen** [langchain-ai/langchainjs#5621]
### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

The current documentation at https://js.langchain.com/v0.2/docs/integrations/document_loaders/file_loaders/unstructured/#setup instructs users to run the Unstructured API locally using the following Docker command:
`docker run -p 8000:8000 -d --rm --name unstructured-api quay.io/unstructured-io/unstructured-api:latest --port 8000 --host 0.0.0.0
`

However, the updated link for the Unstructured API (https://github.com/Unstructured-IO/unstructured-api#dizzy-instructions-for-using-the-docker-image) suggests a different command: 
`docker run -p 8000:8000 -d --rm --name unstructured-api downloads.unstructured.io/unstructured-io/unstructured-api:latest
`

### Idea or request for content:

To ensure users have the most accurate information, please update the documentation at https://js.langchain.com/v0.2/docs/integrations/document_loaders/file_loaders/unstructured/#setup with the following revised Docker command:

`docker run -p 8000:8000 -d --rm --name unstructured-api downloads.unstructured.io/unstructured-io/unstructured-api:latest`

**Comment by jacoblee93** [comment]
Thanks for flagging!

Up for making a PR?

**Comment by sarfudheen** [comment]
Ok I will make a PR
