### ISSUE TITLE
ChatWebLLM Initialization Failure Due To @mlc-ai/web-llm Refactoring

### ISSUE THREAD

**Issue by kaiwinut** [langchain-ai/langchainjs#5648]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

The following code:

```typescript
import { ChatWebLLM } from '@langchain/community/chat_models/webllm';

webllmModel = new ChatWebLLM({
	model: 'Phi2-q4f32_1',
	chatOptions: {
		temperature: 0.1
	}
});
await webllmModel.initialize();
```

### Error Message and Stack Trace (if applicable)

Uncaught (in promise) TypeError: (void 0) is not a constructor
    at ChatWebLLM.initialize (@langchain_community_chat_models_webllm.js?v=b8d3d037:13507:19)
    at worker.ts:156:22

### Description

I'm trying to use ChatWebLLM via web workers following the [documentation](https://js.langchain.com/v0.1/docs/integrations/chat/web_llm/) and the [end-to-end example](https://github.com/jacoblee93/fully-local-pdf-chatbot/blob/main/app/worker.ts) referenced in the docs.

I expect the web llm engine to be initialized when I call `ChatWebLLM.initialize`; however, the error above occurs instead.

After studying the source code, I figured that in a [recent commit](https://github.com/mlc-ai/web-llm/commit/1d7c39b2414973c456c056bb6e487d58a71c6bbb), the developers of web-llm renamed the `Engine` class to `MLCEngine`. This results in a failed constructor call on this line:
https://github.com/langchain-ai/langchainjs/blob/77601f7417eb44e10c60fa8b436f2c3e52fa1740/libs/langchain-community/src/chat_models/webllm.ts#L73

Fixing the web-llm version to `0.2.35` (where the class was not renamed yet) works for now.

### System Info

Node version: `v22.1.0`
langchain version: `0.2.4`
@langchain/community version: `0.2.5`
@mlc-ai/web-llm version: `0.2.41`

**Comment by kaiwinut** [comment]
Sorry, just figured that there's already a related [PR](https://github.com/langchain-ai/langchainjs/pull/5637)...

**Comment by jacoblee93** [comment]
Merged that one, will ship community today!

**Comment by jacoblee93** [comment]
Live in community 0.2.6

**Comment by kaiwinut** [comment]
Thanks a lot for the great work! 
I found out some other tiny issues in the code and example. 
Just created a PR #5671 to fix them.
