### ISSUE TITLE
Swapping ChatOpenAI with AzureChatOpenAI fails when streaming

### ISSUE THREAD

**Issue by johnnyoshika** [langchain-ai/langchainjs#5663]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```typescript
  const useAzure = true; // Set this to false and it will work

  const chatModel = useAzure
    ? new AzureChatOpenAI({
        azureOpenAIApiKey: process.env.AZURE_OPENAI_KEY,
        azureOpenAIApiInstanceName: process.env.AZURE_OPENAI_ENDPOINT,
        azureOpenAIApiDeploymentName: AZURE_OPENAI_DEPLOYMENT,
        azureOpenAIApiVersion: AZURE_OPENAI_VERSION,
        temperature: 0.4,
        streaming: true,
      })
    : new ChatOpenAI({
        model: 'gpt-4o',
        temperature: 0.4,
        streaming: true,
      });

  // It hangs here when using azure.
  // .stream() never returns.
  const stream = await chatModel
    .withConfig({
      runName: 'Chat Demo',
      metadata: {
        conversation_id: 'id-123',
      },
    })
    .stream([['user', 'Hello']]);

  for await (const chunk of stream) {
    console.log('chunk', chunk);
  }
```

### Error Message and Stack Trace (if applicable)

None, it just hangs when calling `AzureChatOpenAI`'s `stream`. I've also tried `AzureOpenAI` and the result is the same.

### Description

Trying to stream chat results from azure. It works fine when using openai's `ChatOpenAI`, but switching to azure just hangs when calling `AzureChatOpenAI`'s `stream` (see code sample above). I've also tried `AzureOpenAI` and the result is the same.

A similar setup using `@azure/openai` worked fine for streaming results from Azure using the same api key and deployment, but I'm trying to switch to langchain to send traces to langsmith.

### System Info

langchain@0.2.4
Windows 11
Node 18.19.0
NPM 10.8.0

**Comment by johnnyoshika** [comment]
Quick update. The request is properly being sent to LangSmith, but a response never appears as can be seen in this screenshot:

![image](https://github.com/langchain-ai/langchainjs/assets/504505/99d720df-d733-4f03-8059-81df03d637f8)

**Comment by jacoblee93** [comment]
Hey, giving this a look now

**Comment by jacoblee93** [comment]
Could you share that LangSmith trace or any of the non-private deployment details you sent? I just tried successfully with version `2024-05-01-preview`.

**Comment by johnnyoshika** [comment]
Here's the trace for the first run in the screenshot (the one that timed out): https://smith.langchain.com/public/daca436b-9929-451a-b313-bde9ac5d7556/r

Here's the trace for the second run in the screenshot (the one that's still spinning): https://smith.langchain.com/public/7b4b7b2c-4aa5-40a1-a7d7-b337630a7451/r

That's interesting that it worked for you. Where can I find version `2024-05-01-preview`? Thx

**Comment by jeasonnow** [comment]
https://github.com/langchain-ai/langchainjs/blob/0c82d55e309727690208141f1538587d72eb2d86/libs/langchain-openai/src/utils/azure.ts#L32-L65

I noticed in langchainSmith that your `azure_openai_api_instance_name` is set to `https://examind-web-openai-local.openai.azure.com/`, whereas it should be `examine-web-openai-local`. You can refer to the source code I sent for more details (it's used to generate the final request URL).

@johnnyoshika

**Comment by johnnyoshika** [comment]
@jeasonnow oh wow, thank you. I'll give that a try tomorrow and report back 🙏

**Comment by johnnyoshika** [comment]
@jeasonnow that was exactly it. Thank you so much!

Closing issue.

**Comment by jacoblee93** [comment]
Thank you @jeasonnow!!!!
