### ISSUE TITLE
LangChain 0.2 adds LangChain 0.1 to node_modules

### ISSUE THREAD

**Issue by davidfant** [langchain-ai/langchainjs#5682]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

langchain@^0.2 depends on "@langchain/textsplitters" "~0.0.0" which depends on "@langchain/core" "~0.1"

### Description

-

### System Info

yarn info v1.22.17
{
  name: 'godmode',
  description: 'packs all html dependecies in one html page',
  'dist-tags': {
    latest: '0.1.0'
  },
  versions: [
    '0.1.0'
  ],
  maintainers: [
    {
      name: 'megatolya',
      email: 'forgetthisbox@gmail.com'
    }
  ],
  time: {
    modified: '2022-06-18T13:15:47.980Z',
    created: '2013-04-19T22:16:29.314Z',
    '0.1.0': '2013-04-19T22:16:32.442Z'
  },
  author: {
    name: 'Anatoliy Ostrovskiy'
  },
  repository: {
    type: 'git',
    url: 'git://github.com/megatolya/godmode.git'
  },
  users: {
    bcoe: true
  },
  version: '0.1.0',
  main: 'lib/godmode.js',
  scripts: {
    test: 'echo "Error: no test specified" && exit 1'
  },
  keywords: [
    'html',
    'js',
    'css',
    'pack',
    'package'
  ],
  license: 'BSD',
  readmeFilename: 'README.md',
  gitHead: '4f00249322c763d993c7097e2d5d0e05ffd97f58',
  dist: {
    shasum: '7f89c00ecf3c780f3ebd7789c086498d3d25a064',
    tarball: 'https://registry.npmjs.org/godmode/-/godmode-0.1.0.tgz',
    integrity: 'sha512-Sd9d2NnzLunA61rFe4oWlXtD6CJX3mqs5ixH3JhX7iLgA4T+IWGw4lTvVXVAqHffAgCJwEQ8Tjy7lVnXdqnwsw==',
    signatures: [
      {
        keyid: 'SHA256:jl3bwswu80PjjokCgh0o2w5c2U4LhQAE57gj9cz1kzA',
        sig: 'MEYCIQCcgIEBnuGOBCaw6aubMLfb3LQeLpm7o3+ElG4WXCPHNAIhAOqeosGsdbfbTAYijU/IHfO1XOXUJeguc70FE6p0D8a6'
      }
    ]
  }
}
Done in 0.67s.

**Comment by jacoblee93** [comment]
Hey @davidfant, is this upgrading an existing project? The latest `@langchain/textsplitters` should support either version of core: (`>0.1.0  <0.3.0`) - we could push a new version that expects only > 0.2 but for now could you also try Dosu's suggested fix above?

More on resolutions here:

https://js.langchain.com/v0.2/docs/how_to/installation/#installing-integration-packages
