### ISSUE TITLE
Ability to set vector IDs through PineconeStore.fromDocuments

### ISSUE THREAD

**Issue by stephenasuncionDEV** [langchain-ai/langchainjs#571]
It may be worth considering adding the ability to set vector IDs through `PineconeStore.fromDocuments`. Currently, it is impossible to fetch vectors from Pinecone's dashboard without knowing the ID. Upon inspection, it appears that if the IDs parameter is undefined, the system generates an ID from UUIDv4 (https://github.com/hwchase17/langchainjs/blob/main/langchain/src/vectorstores/pinecone.ts#L52). However, as it stands, there is no way to pass an ID array from `fromDocuments` to `addDocuments`, so it will always be undefined for the `fromDocuments` function.

A simple fix would be to add an "ids" field in `dbConfig:PineconeLibArgs` and pass it to `addDocuments`.

**Comment by moghwan** [comment]
same issue here with Supabase, we can specify a table name with `.fromText()` but not with `.fromDocuments`

**Comment by evannorstrand-mp** [comment]
Bumping this, as it should be a high priority

**Comment by 8times4** [comment]
Same issue for Milvus, only a few params can be set via MilvusLibArgs. 
I.e `autoId` and others like:
```
    indexCreateParams: {
        index_type: string;
        metric_type: string;
        params: string;
    }; 
```
can't be.

Thanks!

**Comment by ElodieComte** [comment]
Anyone who could check on this ? that would really help to pass ids through `fromDocuments` function.....

**Comment by mowliv** [comment]
Ug. Still a problem AFAIK. Frustrating not to be able to set ID's with fromDocuments. Is there a workaround?

See [this Pinecone RAG doc](https://docs.pinecone.io/guides/data/manage-rag-documents) for justification.

**Comment by jacoblee93** [comment]
Yeah we should fix this. Will take a look, thanks for bumping

**Comment by mowliv** [comment]
Thanks very much!

**Comment by mowliv** [comment]
BTW, is there a workaround? I tried `PineconeStore.fromExistingIndex()` but that also doesn't seem to be able to set IDs.
