### ISSUE TITLE
DOC: <Issue related to /v0.2/docs/tutorials/summarization>

### ISSUE THREAD

**Issue by Arian-Akbari** [langchain-ai/langchainjs#5710]
### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

the dosumnetaion is deceprated .
pls update it 
Summarize Text
https://js.langchain.com/v0.2/docs/tutorials/summarization

### Idea or request for content:

explain more about different templates we create.
why do we have 2 types of templates ?
how many are there?

**Comment by jacoblee93** [comment]
Yes, need to update this.
