### ISSUE TITLE
Gemini failing due to missing API Key, even if provided 

### ISSUE THREAD

**Issue by albertodeavila** [langchain-ai/langchainjs#5712]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

We have the following code: 
``` typescript 
    const llm = new ChatGoogleGenerativeAI({
		apiKey: apiKey,
		modelName: 'gemini-pro',
		maxOutputTokens: 2048,
		safetySettings: [
			{
				category: HarmCategory.HARM_CATEGORY_HARASSMENT,
				threshold: HarmBlockThreshold.BLOCK_LOW_AND_ABOVE,
			},
		],
	})
			
        const chain = new ConversationChain({llm, memory} as unknown as LLMChainInput)
	await chain.call({
		input: model === [['human', prompt]],
		callbacks: [
			{
				handleLLMNewToken(token: string) {
					aiOutput += token
					responseStream.write(token)
				},
			}
		]
	})
```

### Error Message and Stack Trace (if applicable)

The stack trace is the following: 
```
Error during prompt execution GoogleGenerativeAIError: [403 Forbidden] Method doesn't allow unregistered callers (callers without established identity). Please use API Key or other form of API consumer identity to call this API.
    at _makeRequestInternal 
    at process.processTicksAndRejections 
    at async countTokens 
    at async executePrompt 
    at async Runtime.handler 
    at async Runtime.handleOnceStreaming )

```

### Description

Trying to get a response from Gemini using `ChatGoogleGenerativeAI` is failing due to, looks like, a missing API Key. But I've ensured that the api key is set and is working from a curl request. 

Also defining a GOOGLE_API_KEY env var doesn't make it work it. 

Thanks for your help! 

### System Info

```
    "@langchain/community": "^0.2.9",
    "@langchain/google-genai": "^0.0.17",
    "langchain": "^0.2.5",
```

```
node -v
v18.16.0
```

```
yarn -v
1.22.22
```

**Comment by scottforte** [comment]
Same is happening for Open AI. It was not happening Thursday last week.

**Comment by bracesproul** [comment]
Hey, could you provide another way of reproducing this issue? I just tried this:
```typescript
import { ChatGoogleGenerativeAI } from "@langchain/google-genai";
import "dotenv/config";

const llm = new ChatGoogleGenerativeAI({
  apiKey: process.env.GOOGLE_API_KEY,
  modelName: 'gemini-pro',
  maxOutputTokens: 2048,
})

const response = await llm.invoke('Hello, how are you?');
console.log(response);
```

And it executed successfully. 
Although I suspect the issue is related to your API key issue, as per the error message.

**Comment by albertodeavila** [comment]
I generated new API Keys to check that it wasn't the problem, and we get the same error. With your example it's working fine. We were using that way to:

1. Be able to use a chat base memory.
2. And being able to get an stream for the responses.

As also @scottforte was mentioning, this was working fine, but not now. 

Is there any other way to achieve that? 

Thanks!

**Comment by albertodeavila** [comment]
Finally it wasn't an issue. I was trying to count tokens with: 

``` 
await (new GoogleGenerativeAI(getEnvVar('GOOGLE_AI_API_KEY')).getGenerativeModel({ model: 'gemini-pro'}).countTokens(aiOutput))

```

without an API KEY 🤦 and that was causing the error.  

Sorry for the inconveniences.
