### ISSUE TITLE
Example Code No Longer Works:  ZodTypeAny, { ...; }, { ...; }>>' is not assignable to type 'Record<string, unknown>'

### ISSUE THREAD

**Issue by radiantone** [langchain-ai/langchainjs#5772]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

/**
 * Note that the descriptions here are crucial, as they will be passed along
 * to the model along with the class name.
 */
const calculatorSchema = z.object({
  operation: z
    .enum(["add", "subtract", "multiply", "divide"])
    .describe("The type of operation to execute."),
  number1: z.number().describe("The first number to operate on."),
  number2: z.number().describe("The second number to operate on."),
});

const calculatorTool = new DynamicStructuredTool({
  name: "calculator",
  description: "Can perform mathematical operations.",
  schema: calculatorSchema,
  func: async ({ operation, number1, number2 }) => {
    // Functions must return strings
    if (operation === "add") {
      return `${number1 + number2}`;
    } else if (operation === "subtract") {
      return `${number1 - number2}`;
    } else if (operation === "multiply") {
      return `${number1 * number2}`;
    } else if (operation === "divide") {
      return `${number1 / number2}`;
    } else {
      throw new Error("Invalid operation.");
    }
  },
});

const llmWithTools = llm.bindTools([calculatorTool]);

const res = await llmWithTools.invoke("What is 3 * 12");

console.log(res.tool_calls);

### Error Message and Stack Trace (if applicable)

tools.ts:43:37 - error TS2322: Type 'DynamicStructuredTool<ZodObject<{ operation: ZodEnum<["add", "subtract", "multiply", "divide"]>; number1: ZodNumber; number2: ZodNumber; }, "strip", ZodTypeAny, { ...; }, { ...; }>>' is not assignable to type 'Record<string, unknown> | StructuredToolInterface<ZodObject<any, any, any, any, { [x: string]: any; }>>'.
  Type 'DynamicStructuredTool<ZodObject<{ operation: ZodEnum<["add", "subtract", "multiply", "divide"]>; number1: ZodNumber; number2: ZodNumber; }, "strip", ZodTypeAny, { ...; }, { ...; }>>' is not assignable to type 'Record<string, unknown>'.
    Index signature for type 'string' is missing in type 'DynamicStructuredTool<ZodObject<{ operation: ZodEnum<["add", "subtract", "multiply", "divide"]>; number1: ZodNumber; number2: ZodNumber; }, "strip", ZodTypeAny, { ...; }, { ...; }>>'.

43 const llmWithTools = llm.bindTools([calculatorTool]);
                                       ~~~~~~~~~~~~~~

    at createTSError (/home/darren/git/visualagents-ai/visualagents/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/home/darren/git/visualagents-ai/visualagents/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/home/darren/git/visualagents-ai/visualagents/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/home/darren/git/visualagents-ai/visualagents/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/home/darren/git/visualagents-ai/visualagents/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Object.require.extensions.<computed> [as .ts] (/home/darren/git/visualagents-ai/visualagents/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1024:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12) {
  diagnosticCodes: [ 2322 ]
}

### Description

Tried running the example code found here: https://js.langchain.com/v0.2/docs/how_to/tool_calling/#passing-tools-to-llms

This worked before latest updates

### System Info


langchain@0.2.5 | MIT | deps: 16 | versions: 277
Typescript bindings for langchain
https://github.com/langchain-ai/langchainjs/tree/main/langchain/

keywords: llm, ai, gpt3, chain, prompt, prompt engineering, chatgpt, machine learning, ml, openai, embeddings, vectorstores

dist
.tarball: https://registry.npmjs.org/langchain/-/langchain-0.2.5.tgz
.shasum: fc23848c20244a1d0a3dd5dd4663af9a41017ccb
.integrity: sha512-H5WL0NanCdQ+tzoeEt7Fyz9YGdR3wbfDvfQrJvxAO95istKo5JraRh24dzyvqxM9439xwRMNaMIpMwsyqtWDtQ==
.unpackedSize: 4.0 MB

dependencies:
@langchain/core: ~0.2.0
@langchain/openai: ~0.1.0
@langchain/textsplitters: ~0.0.0
binary-extensions: ^2.2.0
js-tiktoken: ^1.0.12
js-yaml: ^4.1.0
jsonpointer: ^5.0.1
langchainhub: ~0.0.8
langsmith: ~0.1.30
ml-distance: ^4.0.0
openapi-types: ^12.1.3
p-retry: 4
uuid: ^9.0.0
yaml: ^2.2.1
zod-to-json-schema: ^3.22.3
zod: ^3.22.4

maintainers:
- nfcampos <nuno@boringbits.io>
- jacoblee93 <jacoblee93@gmail.com>
- andrewnguonly <andrewnguonly@gmail.com>
- davidduong <david@duong.cz>
- hwchase17 <hw.chase.17@gmail.com>
- basproul <braceasproul@gmail.com>

dist-tags:
latest: 0.2.5
next: 0.2.3-rc.0

published a week ago by jacoblee93 <jacoblee93@gmail.com>

**Comment by jacoblee93** [comment]
Thanks for reporting!

This seemed ok to me when I checked - sometimes errors like this can manifest as a result of package managers resolving multiple versions of `@langchain/core`.

Can you try the instructions here to ensure this isn't the case?

https://js.langchain.com/v0.2/docs/how_to/installation/#installing-integration-packages

**Comment by matzkoh** [comment]
https://github.com/langchain-ai/langchainjs/blob/b76ead9e0539752501b5fc023fb177f52e7c7d69/langchain-core/src/tools.ts#L16

should be

```ts
type ZodAny = z.ZodObject<any, any, any, any, any>;
```

**Comment by leitdeux** [comment]
I'm also seeing the same TS error messages of `DynamicStructuredTool<ZodObject<{ ... }> ...> is not assignable to type DynamicStructuredTool<ZodAny>` when I construct a `DynamicStructuredTool`, following the examples in the Langchain.js documentation. 

It seems that from `@langchain/core v0.2.7` onward the error appears.
