### ISSUE TITLE
Google Vertex AI and Gen AI models not returning usage information even though HTTP response has them

### ISSUE THREAD

**Issue by chreds** [langchain-ai/langchainjs#5774]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```
const googleModel = new ChatVertexAI({
...
callbacks: [{
  handleLLMEnd(output) {
    console.log("llmOutput " + JSON.stringify(output, null, 2))
  }
}]
```

The output includes an empty ` "llmOutput": {} `

```
const googleModel = new ChatGoogleGenerativeAI({
...
callbacks: [{
  handleLLMEnd(output) {
    console.log("llmOutput " + JSON.stringify(output, null, 2))
  }
}]
```

The output includes safety information but no usageMetadata

### Description

No matter what I try I can't seem to get access to the usageMetadata on the Google APIs.

I tried HTTPOutputParser and other ways to get access to the raw HTTP which would have the usage information but it's just passing through the response messages.

Endpoint is northamerica-northeast1-aiplatform.googleapis.com but I've used the default us-central as well with the same problem.

I just tried with the ChatGoogleGenerativeAI model as well and it's showing the safety information but not the usage information in the callback. When I do a raw HTTP request to https://generativelanguage.googleapis.com/v1/models/gemini-1.5-flash:generateContent?key=[redacted] I get a response that includes:

```
{
    "candidates": [
       ...
    ],
    "usageMetadata": {
        "promptTokenCount": 12,
        "candidatesTokenCount": 144,
        "totalTokenCount": 156
    }
}
```

How can I get access to this info? I'd rather have access to it from the output of the invoke instead of through a callback with the way my app is structured, but I'm sure I can make it work wherever it is.

### System Info

    "@langchain/google-genai": "^0.0.17",
    "@langchain/google-vertexai": "^0.0.18",
    "langchain": "^0.2.5",

**Comment by chreds** [comment]
Thanks @dosu bot some helpful info there.
I'm still getting undefined for usageMetadata. Tried taking out the ChatPromptTemplate code and calling with model.invoke() without any of the piping and the result still has usageMetadata undefined.

```AIMessage {
  lc_serializable: true,
  lc_kwargs: {
    content: ...,
    tool_calls: [],
    additional_kwargs: { finishReason: 'STOP', index: 0, safetyRatings: [Array] },
    invalid_tool_calls: [],
    response_metadata: {}
  },
  lc_namespace: [ 'langchain_core', 'messages' ],
  content: ...,
  name: undefined,
  additional_kwargs: {
    finishReason: 'STOP',
    index: 0,
    safetyRatings: [ [Object], [Object], [Object], [Object] ]
  },
  response_metadata: {
    finishReason: 'STOP',
    index: 0,
    safetyRatings: [ [Object], [Object], [Object], [Object] ]
  },
  tool_calls: [],
  invalid_tool_calls: [],
  **usage_metadata: undefined**
```

**Comment by chreds** [comment]
@dosu, I didn't have streamUsage set on the model so it should be defaulting to true. I tried explicitly setting it to true and the results are the same. Is there anything else that could be causing it to be undefined?

**Comment by chreds** [comment]
@dosu maybe I need to wait for https://github.com/langchain-ai/langchainjs/pull/5763 to be released before your suggestions will work. I'll probably have to wait for the next release to get that functionality.

**Comment by jacoblee93** [comment]
Should be live now - closing but please reopen if not fixed in latest.

**Comment by chreds** [comment]
Thanks @jacoblee93. I've got it pass through usage now with a custom json output parser. Is this the best practices way of accessing?

```
export type JsonAndUsageOutput = {
    json?: Record<string, any>, 
    tokens?: {
        input_tokens: number, 
        output_tokens: number 
    }
}

export class JsonAndUsageOutputParser extends JsonOutputParser {
    static lc_name() {
        return "JsonAndUsageOutputParser";
    }

    lc_namespace = ["langchain_core", "output_parsers"];
    lc_serializable = true;

    async parseResult(generations: ChatGeneration[] & { message: AIMessage }[], callbacks?: any) : Promise<JsonAndUsageOutput> {
        let input_tokens = 0
        let output_tokens = 0
        
        for(const generation of generations) {
            input_tokens += (generation.message.usage_metadata.input_tokens || 0)
            output_tokens += (generation.message.usage_metadata.output_tokens || 0)
            logger.debug(generation.message.usage_metadata)
        }

        const result = { json: await super.parseResult(generations, callbacks), tokens: { input_tokens, output_tokens } }
        return result
    }
}
```

**Comment by chreds** [comment]
I guess a better option might be to use RunnableParallel with JsonOutputParser and a CustomUsageOutputParser instead so it's not tightly coupled with the JsonOutputParser.

**Comment by chreds** [comment]
Yeah, this is much cleaner:

```
        const jsonParser = new JsonOutputParser()
        const usageParser = RunnableLambda.from((message: AIMessage) : UsageMetadata => {
            return message.usage_metadata
        })
    
        const mapChain = RunnableMap.from({
            json: jsonParser,
            usage: usageParser,
        })

        const chainResult = await prompt.pipe(model).pipe(mapChain).invoke({data: invokeWith})
```
