### ISSUE TITLE
TypeError: getDefaultAgent is not a function

### ISSUE THREAD

**Issue by guidev** [langchain-ai/langchainjs#5816]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

1. git clone https://github.com/guidev/nonworking/tree/node20

2. npm run start 

### Error Message and Stack Trace (if applicable)

```
TypeError: getDefaultAgent is not a function
    at OpenAI.buildRequest (file:///Users/name/Progetti/nonworking/node_modules/openai/core.mjs:208:66)
    at OpenAI.makeRequest (file:///Users/name/Progetti/nonworking/node_modules/openai/core.mjs:279:44)
    at async file:///Users/name/Progetti/nonworking/node_modules/@langchain/openai/dist/chat_models.js:796:29
    at async RetryOperation._fn (/Users/name/Progetti/nonworking/node_modules/p-retry/index.js:50:12)

Node.js v22.3.0

```

### Description

When using openai-node with langchain and datadog, ESM, I get the following error:

### System Info

		"@langchain/openai": "^0.1.3",
		"dd-trace": "^5.17.0",
		"dotenv": "^16.4.5",
		"express": "^4.19.2",
		"langchain": "0.2.5"

**Comment by guidev** [comment]
Also opened an issue at https://github.com/openai/openai-node/issues/903

**Comment by guidev** [comment]
@dosu 

Here's the full code: 


`import './config/datadog.js';
import express from 'express';
import {ChatOpenAI} from "@langchain/openai";
import {PromptTemplate} from "@langchain/core/prompts";
import {JsonOutputParser} from "@langchain/core/output_parsers";
import dotenv from "dotenv";

dotenv.config();


const app = express();

const prompt = PromptTemplate.fromTemplate(`Return a JSON object with a 'text' field containing a joke`);

const llm = new ChatOpenAI({modelName: "gpt-4o", verbose: true, apiKey: "doesntmatter"})
    .bind({
        response_format: {
            type: "json_object",
        },
    });

const parser = new JsonOutputParser();

const chain = prompt.pipe(llm).pipe(parser);

console.log(await chain.invoke({}));

app.listen(process.env.PORT || 3000);`

**Comment by nakatsuka-k** [comment]
@guidev
I was able to resolve the issue by modifying it to make the request using Fetch as shown below.

```typescript
      const openAiApiUrl = "https://api.openai.com/v1/chat/completions";
      
      const response = await fetch(openAiApiUrl, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${appConfig.openAiKey}`,
        },
        body: JSON.stringify({
          model: "gpt-3.5-turbo",
          messages: [...messages],
          max_tokens: 256,
        }),
      });
```
