### ISSUE TITLE
Implement callbackManager hook for request retries

### ISSUE THREAD

**Issue by loui7** [langchain-ai/langchainjs#587]
Description:
> LangChain provides a callback system that allows you to hook into the various stages of your LLM application. This is useful for logging, [monitoring](https://js.langchain.com/docs/production/tracing), [streaming](https://js.langchain.com/docs/modules/models/llms/additional_functionality#streaming-responses), and other tasks. 

https://js.langchain.com/docs/production/callbacks

It would be nice to have a hook that would run when `exponential-backoff` retries an API request. This would give developers more visibility into intermittent errors there application is hitting when making API calls, for example rate limits or other issues.

This could be implemented via the [retry](https://www.npmjs.com/package/exponential-backoff#:~:text=retry%3F%3A%20(e%3A%20any%2C%20attemptNumber%3A%20number)%20%3D%3E%20boolean%20%7C%20Promise%3Cboolean%3E) parameter available in `exponential-backoff`. Errors that are causing a retry are passed to this method, and then the retry occurs.

**Comment by agola11** [comment]
Good idea, thanks!

**Comment by qcgm1978** [comment]
Is this feat implemented? I meet the problem when my openai account `exceeded your current quota`. The `langchain/chat_models/openai` tries about seven times and failed. It's too long

**Comment by qcgm1978** [comment]
Sorry I haven't focus on the problem for a while.
