### ISSUE TITLE
DOC: Use TypeScript syntax on /v0.2/docs/tutorials/chatbot/ code block

### ISSUE THREAD

**Issue by mattnorris** [langchain-ai/langchainjs#5872]
### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

The code block on [this page](https://js.langchain.com/v0.2/docs/tutorials/chatbot/#quickstart) uses Python syntax rather than TS.

```js
const model = new ChatOpenAI(model="gpt-3.5-turbo");
```

### Idea or request for content:

Update it to:

```js
const model = new ChatOpenAI({ model: "gpt-3.5-turbo" });
```

**Comment by jacoblee93** [comment]
Thanks, fixed!
