### ISSUE TITLE
DOC: <Issue related to /v0.2/docs/how_to/tool_calling/>

### ISSUE THREAD

**Issue by joshpitzalis** [langchain-ai/langchainjs#5875]
### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

Found a minor typo on the following page https://js.langchain.com/v0.2/docs/how_to/tool_calling/

- "since you can pass responses to **caled** tools back to" > "since you can pass responses to called tools back to"

**Comment by nick-w-nick** [comment]
FYI this looks to have already been fixed via changes to that page since the issue was created.
