### ISSUE TITLE
Invalid Maximum context length error when we use model: gpt-4o,gpt-4-1106-preview, etc

### ISSUE THREAD

**Issue by adeenrabbani1** [langchain-ai/langchainjs#5888]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

NA

### Error Message and Stack Trace (if applicable)

 400 This model's maximum context length is 16385 tokens. However, your messages resulted in 38551 tokens. Please reduce the length of the messages.
0|ga-core  | 2024-06-25 07:24 +00:00:     at Function.generate (/home/ubuntu/grantassistant-backend/node_modules/openai/src/error.ts:70:14)
0|ga-core  | 2024-06-25 07:24 +00:00:     at OpenAI.makeStatusError (/home/ubuntu/grantassistant-backend/node_modules/openai/src/core.ts:397:21)
0|ga-core  | 2024-06-25 07:24 +00:00:     at OpenAI.makeRequest (/home/ubuntu/grantassistant-backend/node_modules/openai/src/core.ts:460:24)
0|ga-core  | 2024-06-25 07:24 +00:00:     at processTicksAndRejections (node:internal/process/task_queues:95:5)
0|ga-core  | 2024-06-25 07:24 +00:00:     at /home/ubuntu/grantassistant-backend/node_modules/@langchain/openai/dist/chat_models.cjs:816:29
0|ga-core  | 2024-06-25 07:24 +00:00:     at RetryOperation._fn (/home/ubuntu/grantassistant-backend/node_modules/p-retry/index.js:50:12) {
0|ga-core  | 2024-06-25 07:24 +00:00:   status: 400,
0|ga-core  | 2024-06-25 07:24 +00:00:   headers: {
0|ga-core  | 2024-06-25 07:24 +00:00:     'alt-svc': 'h3=":443"; ma=86400',
0|ga-core  | 2024-06-25 07:24 +00:00:     'cf-cache-status': 'DYNAMIC',
0|ga-core  | 2024-06-25 07:24 +00:00:     'cf-ray': '899337ec0d200608-IAD',
0|ga-core  | 2024-06-25 07:24 +00:00:     connection: 'keep-alive',
0|ga-core  | 2024-06-25 07:24 +00:00:     'content-length': '282',
0|ga-core  | 2024-06-25 07:24 +00:00:     'content-type': 'application/json',
0|ga-core  | 2024-06-25 07:24 +00:00:     date: 'Tue, 25 Jun 2024 07:24:32 GMT',
0|ga-core  | 2024-06-25 07:24 +00:00:     'openai-organization': 'grantassistant-ai',
0|ga-core  | 2024-06-25 07:24 +00:00:     'openai-processing-ms': '157',
0|ga-core  | 2024-06-25 07:24 +00:00:     'openai-version': '2020-10-01',
0|ga-core  | 2024-06-25 07:24 +00:00:     server: 'cloudflare',
0|ga-core  | 2024-06-25 07:24 +00:00:     'set-cookie': '__cf_bm=tVMKqE5Q8tsS7R6jmOPD43n.yHrEM5Lt4mgAN.hxjy8-1719300272-1.0.1.1-Sj9kAgIm8nurKYdvwoyw88_8_9UrcoX.WvO4YZ5rq_HSIXC095mJ3_3xFvbZR1PVC8tdF6VQtM5mKMGpYEzDGQ; path=/; expires=Tue, 25-Jun-24 07:54:32 GMT; domain=.api.openai.com; HttpOnly; Secure; SameSite=None, _cfuvid=fyQLt9mxbiCZh6Mn7154P52LXADZV03kv762KD_aZVU-1719300272391-0.0.1.1-604800000; path=/; domain=.api.openai.com; HttpOnly; Secure; SameSite=None',
0|ga-core  | 2024-06-25 07:24 +00:00:     'strict-transport-security': 'max-age=31536000; includeSubDomains',
0|ga-core  | 2024-06-25 07:24 +00:00:     'x-ratelimit-limit-requests': '10000',
0|ga-core  | 2024-06-25 07:24 +00:00:     'x-ratelimit-limit-tokens': '5000000',
0|ga-core  | 2024-06-25 07:24 +00:00:     'x-ratelimit-remaining-requests': '9999',
0|ga-core  | 2024-06-25 07:24 +00:00:     'x-ratelimit-remaining-tokens': '4947877',
0|ga-core  | 2024-06-25 07:24 +00:00:     'x-ratelimit-reset-requests': '6ms',
0|ga-core  | 2024-06-25 07:24 +00:00:     'x-ratelimit-reset-tokens': '625ms',
0|ga-core  | 2024-06-25 07:24 +00:00:     'x-request-id': '2170dd3aae4508dfe5ea89c72f351263'
0|ga-core  | 2024-06-25 07:24 +00:00:   },
0|ga-core  | 2024-06-25 07:24 +00:00:   request_id: '2170dd3aae4508dfe5ea89c72f351263',
0|ga-core  | 2024-06-25 07:24 +00:00:   error: {
0|ga-core  | 2024-06-25 07:24 +00:00:     message: "This model's maximum context length is 16385 tokens. However, your messages resulted in 38551 tokens. Please reduce the length of the messages.",

### Description

I updated my langchain.js to version 0.2.6 to use Open AIs latest model, i.e gpt-4o
However, when I try to use it, it gives the invalid maximum content length error as above, even though the context length for that model is 128k tokens.

### System Info

windows.
node v18.17.0
langchain 0.2.6

**Comment by adeenrabbani1** [comment]
The maximun context len for these models is 128k tokens, and I am pretty sure that Iam not going beyond that. but if you read the error langchain is throwing carefully, you would see that it says "Maximum context length for the model is 16k. which is invalid as the open AI documentation

**Comment by adeenrabbani1** [comment]
![image](https://github.com/langchain-ai/langchainjs/assets/52000430/61c0e005-9366-4494-8665-00c6c07c788e)


Above is the reference for the token limit on OPEN AI documentation

**Comment by mikewuu** [comment]
what was the fix?

**Comment by sushant-samespace** [comment]
Any updates?

**Comment by stevenolay** [comment]
Why hasn't this been addressed. I'm very confused

**Comment by dingyi222666** [comment]
Error still persists. Suggest reopening this issue for further discussion.
