### ISSUE TITLE
Unable to get streaming response from BedrockChat in a custom agent

### ISSUE THREAD

**Issue by MrHertal** [langchain-ai/langchainjs#5917]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```typescript
  const llm = new BedrockChat({
    model: "anthropic.claude-3-sonnet-20240229-v1:0",
    modelKwargs: {
      temperature: 0,
    },
    streaming: true,
    callbacks: [
      {
        async handleLLMNewToken(token) {
          console.log({ token });
        },
      },
    ],
  });

  const memory = new BufferMemory({
    chatHistory: new DynamoDBChatMessageHistory({
      tableName: memoryTable,
      partitionKey: "SessionId",
      sessionId,
    }),
    returnMessages: true,
    memoryKey: "chat_history",
    outputKey: "output",
  });

  const agent = createToolCallingAgent({
    llm,
    tools,
    prompt,
  });

  const agentExecutor = new AgentExecutor({
    agent,
    tools,
    memory,
  });

  const result = await agentExecutor.invoke({
    input: message,
  });
```

### Description

Hi,

I'm following this example: https://github.com/langchain-ai/langchainjs/blob/main/examples/src/agents/streaming.ts
to enable streaming in an agent response.

I'm using BedrockChat as the model with the following options:

```typescript
  const llm = new BedrockChat({
    model: "anthropic.claude-3-sonnet-20240229-v1:0",
    modelKwargs: {
      temperature: 0,
    },
    streaming: true,
    callbacks: [
      {
        async handleLLMNewToken(token) {
          console.log({ token });
        },
      },
    ],
  });
```

I'm expecting to see a response from the agent streaming in the console, token by token.
But i always get a single token with the full response:

```
{
  token: "the full response..."
}
```

Am I missing something?

### System Info

```
{
  name: 'langchain',
  description: 'Typescript bindings for langchain',
  'dist-tags': {
    next: '0.2.3-rc.0',
    latest: '0.2.7'
  },
  version: '0.2.7',
  ...
}
```

```
yarn -v
1.22.22
node -v
v20.11.0
```

**Comment by MrHertal** [comment]
Sorry @dosu but this is not helping.

I'm using BedrockChat in the context of a custom agent, so I don't run the model directly.
This is done by the agent after `executor.invoke`

**Comment by MrHertal** [comment]
By default `streamRunnable` is set to `true`
I tried to explicitly set it to `true` without success

**Comment by jeasonnow** [comment]
> By default `streamRunnable` is set to `true` I tried to explicitly set it to `true` without success

Can you try the following code?
```typescript
const result = await agentExecutor.stream({
  input: message,
});
```

**Comment by MrHertal** [comment]
@jeasonnow thanks but it was not working.

I finally made it work by implementing this solution: https://github.com/aws-samples/langchain-agents/tree/main/bedrock/langchain-js-stream-agent
