### ISSUE TITLE
input_documents not working

### ISSUE THREAD

**Issue by Achalogy** [langchain-ai/langchainjs#597]
Hi, I'm trying to use this package and I created this:

```js

const { HNSWLib } = await import("langchain/vectorstores");
const { OpenAIEmbeddings } = await import("langchain/embeddings");

const vectorStore = await HNSWLib.fromTexts(
  texts,
  {},
  new OpenAIEmbeddings({
    openAIApiKey: this.openAIApiKey,
  })
);

this.Documents = vectorStore;

const relevantDocuments = await this.Documents.similaritySearch(query);

const llm = new OpenAIChat({
  openAIApiKey: this.openAIApiKey,
  temperature: 0,
  maxTokens: 1000,
});

const chain = loadQAStuffChain(llm, {
  prompt: await this.getChatPrompt(),
});

const res = await chain.call({
  input_documents: relevantDocuments,
  question: query,
  chat_history: memory,
});

```

The response doesn't seem to be based on the input documents. I attempted to pass `relevantDocuments` to the `chatPromptTemplate` in plain text as system input, but that solution did not work effectively:

```
const chatPrompt = ChatPromptTemplate.fromPromptMessages([
  ...
  SystemMessagePromptTemplate.fromTemplate(
    "Tienes esta inforamción base: {doc}"
  ),
  ...
]);
```

**Comment by MaximeThoonsen** [comment]
Hey @Achalogy, can you provide some example of `texts`, `query` and what does the `this.getChatPrompt()` return ?

Did you try to not pass any prompt to the chain like: `const chain = loadQAStuffChain(llm);` ?

**Comment by siddarthvader** [comment]
instead of using `OpenAIChat`  use `OpenAI` and it shall work. @Achalogy 

	const stuffllm = new OpenAI();

**Comment by siddarthvader** [comment]
@Achalogy happening with me also, did you find a solution?
