### ISSUE TITLE
functionDeclarations should be function_declarations - call to ChatVertexAI with a tool will fail with 400 error

### ISSUE THREAD

**Issue by da5idb** [langchain-ai/langchainjs#5974]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

This is actually pretty bad since it is quite hard to figure out what is not working - and the REST examples in Google Docs are a bit hidden: 

From google docs: https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/function-calling?source=post_page-----9b7fd8ae031b--------------------------------#rest

Click on **First Model Request** to expand
```json
"tools": [
  {
    "function_declarations": [
      {
        "name": "find_movies",
        "description": "find movie titles currently playing in theaters based on any description, genre, title words, etc.",
        "parameters": {
          "type": "object",
          "properties": {
            "location": {
              "type": "string",
              "description": "The city and state, e.g. San Francisco, CA or a zip code e.g. 95616"
            },
            "description": {
              "type": "string",
              "description": "Any kind of description including category or genre, title words, attributes, etc."
            }
          },
          "required": [
            "description"
          ]
        }
      }
]
```

Able to verify with example code from: https://js.langchain.com/v0.2/docs/integrations/chat/google_vertex_ai/#vertexai-tools-agent

```typescript
import { z } from "zod";

import { DynamicStructuredTool } from "@langchain/core/tools";
import { AgentExecutor, createToolCallingAgent } from "langchain/agents";

import { ChatPromptTemplate } from "@langchain/core/prompts";
import { ChatVertexAI } from "@langchain/google-vertexai";
// Uncomment this if you're running inside a web/edge environment.
// import { ChatVertexAI } from "@langchain/google-vertexai-web";

const llm: any = new ChatVertexAI({
  temperature: 0,
});

// Prompt template must have "input" and "agent_scratchpad input variables"
const prompt = ChatPromptTemplate.fromMessages([
  ["system", "You are a helpful assistant"],
  ["placeholder", "{chat_history}"],
  ["human", "{input}"],
  ["placeholder", "{agent_scratchpad}"],
]);

const currentWeatherTool = new DynamicStructuredTool({
  name: "get_current_weather",
  description: "Get the current weather in a given location",
  schema: z.object({
    location: z.string().describe("The city and state, e.g. San Francisco, CA"),
  }),
  func: async () => Promise.resolve("28 °C"),
});

const agent = await createToolCallingAgent({
  llm,
  tools: [currentWeatherTool],
  prompt,
});

const agentExecutor = new AgentExecutor({
  agent,
  tools: [currentWeatherTool],
});

const input = "What's the weather like in Paris?";
const { output } = await agentExecutor.invoke({ input });

console.log(output);
```

### Error Message and Stack Trace (if applicable)
```json
{
  "error": {
    "code": 400,
    "message": "Request contains an invalid argument.",
    "errors": [
      {
        "message": "Request contains an invalid argument.",
        "domain": "global",
        "reason": "badRequest"
      }
    ],
    "status": "INVALID_ARGUMENT"
  }
}
```
### Description

I thought that maybe the conversion from CamelCase to snake_case happens somewhere before the prompt is sent to Google but seems like that is not happening. I adjusted the code in libs/langchain-google-common/src/chat_models.ts:170 and the problem is gone.
https://github.com/langchain-ai/langchainjs/blob/main/libs/langchain-google-common/src/chat_models.ts#L170C7-L170C27

### System Info

Do not think this is relevant to the issue - but I will include my versions from package-lock

@langchain/core: "0.2.12",
@langchain/google-common: "0.0.19",
 langchain: "0.2.4",

**Comment by afirstenberg** [comment]
This seems really really odd. Digging into this further to see if I can figure out what is going on.

The API gateway that Google has accepts parameters in either snake_case or camelCase. Most of their documentation shows things using camelCase (the paragraph you linked to, for example, shows it as "functionDeclarations", tho the example shows it as "function_declarations").

I've tested this sending raw JSON directly - and I can't duplicate the problem.

What model are you using?

**Comment by afirstenberg** [comment]
See also the API documentation at https://cloud.google.com/vertex-ai/docs/reference/rest/v1/Tool

**Comment by da5idb** [comment]
Ok I will try to narrow it down tomorrow 👍

**Comment by da5idb** [comment]
> What model are you using?

I am using Gemini 1.5 pro in eu west

**Comment by da5idb** [comment]
Sorry @afirstenberg  - I found the issue: It was not the camelcase in the functionDeclarations but rather the tool name I used that had spaces in the name. I did not know that name should be a string without any spaces - of course now I see it everywhere 🤦 

Sorry for the work I caused - I was just very sure that this was the issue... - since I could make it work in-between - not sure how that happened?

**Comment by da5idb** [comment]
I will close this ticket 👍

**Comment by afirstenberg** [comment]
Glad you figured this out!
Might be useful to make sure names are valid, especially if the error it returns is so vague.
