### ISSUE TITLE
Still can't return direct with multi-action agent

### ISSUE THREAD

**Issue by zAlweNy26** [langchain-ai/langchainjs#5977]
I'm still getting this error even after [this discussion](https://github.com/langchain-ai/langchainjs/discussions/4631) was solved.

Am I doing something wrong?
This is my snippet of code
```ts
const agent = RunnablePassthrough.assign({
	agent_scratchpad: x => generatedScratchpad((x.intermediateSteps ?? []) as AgentStep[]),
}).pipe(prompt).pipe(this.verboseRunnable).pipe(currentLLM).pipe(new ProceduresOutputParser())

const agentExecutor = AgentExecutor.fromAgentAndTools({
	agent,
	tools,
	returnIntermediateSteps: true,
	maxIterations: 5,
})
```
that throws the error:
https://github.com/langchain-ai/langchainjs/blob/ed1f3fbcafdb494e7807f60d5ede74cf75f57b4b/langchain/src/agents/executor.ts#L433

_Originally posted by @zAlweNy26 in https://github.com/langchain-ai/langchainjs/discussions/4631#discussioncomment-9563797_

**Comment by zAlweNy26** [comment]
@dosu but in the discussion the maintainer said it was an oversight and that the tools with `returnDirect` set to `true` should work with multi-action agents.

**Comment by jeasonnow** [comment]
https://github.com/langchain-ai/langchainjs/pull/4643#issuecomment-1986677391

The reason for not removing this detection mechanism in `RunnableMultiActionAgent` is that if you want to bypass this restriction, you can use `RunnableSingleActionAgent`. You can try the code below:
```typescript
const agent = AgentRunnableSequence.fromRunnables(
  [
    RunnablePassthrough.assign({
      agent_scratchpad: x => generatedScratchpad((x.intermediateSteps ?? []) as AgentStep[]),
    }),
    prompt,
    this.verboseRunnable,
    currentLLM,
    new ProceduresOutputParser(),
  ],
  {
    name: “YourAgentName",
    streamRunnable,
    singleAction: true,
  }
);
```

**Comment by zAlweNy26** [comment]
@jeasonnow thanks for the reply, I'll try it!

**Comment by zAlweNy26** [comment]
@jeasonnow it seems that the `AgentRunnableSequence` is not exported in the [index.ts](https://github.com/langchain-ai/langchainjs/blob/main/langchain/src/agents/index.ts#L1) file of the agents.
Also, based on the TODO on the class, it seems deprecated, do you know what is the new alternative to it?

**Comment by jeasonnow** [comment]
> @jeasonnow it seems that the `AgentRunnableSequence` is not exported in the [index.ts](https://github.com/langchain-ai/langchainjs/blob/main/langchain/src/agents/index.ts#L1) file of the agents. Also, based on the TODO on the class, it seems deprecated, do you know what is the new alternative to it?

Try this
```
import { RunnableSequence } from "@langchain/core/runnables"
```

**Comment by jeasonnow** [comment]
Try this

```typescript
import { RunnableSequence } from "@langchain/core/runnables”;

const agent = RunnableSequence.from([
    RunnablePassthrough.assign({
      agent_scratchpad: x => generatedScratchpad((x.intermediateSteps ?? []) as AgentStep[]),
    }),
    prompt,
    this.verboseRunnable,
    currentLLM,
    new ProceduresOutputParser(),
  ], ‘YourAgentName');
agent.singleAction = true;
```

**Comment by zAlweNy26** [comment]
@jeasonnow the `singleAction` property does not seem to exist in `RunnableSequence` class

**Comment by jacoblee93** [comment]
> @jeasonnow it seems that the `AgentRunnableSequence` is not exported in the [index.ts](https://github.com/langchain-ai/langchainjs/blob/main/langchain/src/agents/index.ts#L1) file of the agents. Also, based on the TODO on the class, it seems deprecated, do you know what is the new alternative to it?

Alternative in general is [LangGraph](https://langchain-ai.github.io/langgraphjs/)

Will still try to look into this as it seems like a thorn for lots of folks but we generally see LangGraph as the more flexible future.
