### ISSUE TITLE
AgentExecutor.fromAgentAndTools can never resolved

### ISSUE THREAD

**Issue by wulucxy** [langchain-ai/langchainjs#5981]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```
const prompt = await pull<ChatPromptTemplate>('hwchase17/openai-tools-agent');
  const agent = await createOpenAIToolsAgent({
    llm,
    tools,
    prompt,
  });
  const agentExecutor = AgentExecutor.fromAgentAndTools({
    agent,
    tools,
    verbose: true,
    // maxIterations: 2,
  });

  const result = await agentExecutor.invoke({
    input: task,
  });
```

### Description

https://github.com/langchain-ai/langchainjs/blob/db9e35242abbb77a1dbf5f8f84ad80d6ab55f819/langchain/src/agents/openai_tools/output_parser.ts#L75

```javascript
 if (message.additional_kwargs.tool_calls) {
// ...
```

should be:

```
 if (message.additional_kwargs.tool_calls && message.additional_kwargs.tool_calls.length > 0) {
```

### System Info

langchainjs: v0.2.6

**Comment by bracesproul** [comment]
For now, you should just use:
```typescript
  const agentExecutor = new AgentExecutor({
    agent,
    tools,
    verbose: true,
    // maxIterations: 2,
  });

```

**Comment by wulucxy** [comment]
@bracesproul 

https://github.com/langchain-ai/langchainjs/blob/db9e35242abbb77a1dbf5f8f84ad80d6ab55f819/langchain/src/agents/openai_tools/output_parser.ts#L75

I think the assertion of this line is not correct

```javascript
if (message.additional_kwargs.tool_calls)
```

it should be ```javascript
if (message.additional_kwargs.tool_calls && message.additional_kwargs.tool_calls.length > 0)
```

**Comment by wulucxy** [comment]
> For now, you should just use:
> 
> ```ts
>   const agentExecutor = new AgentExecutor({
>     agent,
>     tools,
>     verbose: true,
>     // maxIterations: 2,
>   });
> ```



> AgentExecutor

https://github.com/langchain-ai/langchainjs/blob/ef201d0ee85ee4049078270a0cfd7a1767e624f8/langchain/src/agents/executor.ts#L448

these two methods call just the same

**Comment by djaffer** [comment]
This agent never works.
