### ISSUE TITLE
tavily search api is not reliable

### ISSUE THREAD

**Issue by wulucxy** [langchain-ai/langchainjs#5982]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

// ===tavily request===
{
  query: '"{\\"input\\":\\"2023 NBA final winner\\"}"',
  max_results: 1,
  api_key: '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'
}

// ===tavily response=== 
{
  query: '"{\\"input\\":\\"2023 NBA final winner\\"}"',
  follow_up_questions: null,
  answer: null,
  images: null,
  results: [],
  response_time: 1.28
}

### Description

https://github.com/langchain-ai/langchainjs/blob/1fddf296f922dcaa362a90c8fe90b4bfd84b6c3e/libs/langchain-community/src/retrievers/tavily_search_api.ts#L97

the return of tavily search api always empty array

### System Info

@langchain/community": "^0.2.13"

**Comment by jacoblee93** [comment]
CC @rotemweiss57

**Comment by rotemweiss57** [comment]
Hey @wulucxy! Please try to insert "2023 NBA final winner" instead of '"{\"input\":\"2023 NBA final winner\"}"' as it creates limitations. Hope it helps (:

**Comment by wulucxy** [comment]
@rotemweiss57 I don't think so.

`{"input":"2023 NBA final winner"}` was inferenced by model，as the schema defined by the `tavily_search`.

so you have to be think the implement of the tool

https://github.com/langchain-ai/langchainjs/blob/f5f2cf41c279a356cf702656a757413e1ae76732/libs/langchain-community/src/tools/tavily_search.ts#L45

**Comment by wulucxy** [comment]
@rotemweiss57 now I have been blocked here for a while, do you have any plan to improve this?

**Comment by wulucxy** [comment]
@rotemweiss57 what's the progress here?

**Comment by carl-vbn** [comment]
Hey, I don't think this is an issue with Tavily. You are passing JSON into the query field, which won't get you any good results, the same way typing JSON into google or bing won't work. You have to pass the input value itself.
Also, make sure to keep your Tavily API key private.

**Comment by wulucxy** [comment]
@carl-vbn the json was generated by AI，depend on the schema description by Tavily。

I mean Tavily should cover this situation
