### ISSUE TITLE
ChatPromptTemplate `.partial` should not be async

### ISSUE THREAD

**Issue by alvarosevilla95** [langchain-ai/langchainjs#6023]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```typescript
const prompt = ChatPromptTemplate.fromMessages<{ date: string; query: string }>([
  [
    "system",
    "The current date is {date}",
  ],
  ["human", "{query}"],
]).partial({ date: () => new Date().toISOString() })

// const prompt: Promise<ChatPromptTemplate<InputValues<"query">, any>>
```

### Description

Having `.partial()` be async means the prompt value now must be awaited before using. This is particularly problematic if I want to have the prompt definition be at the top level of a commonjs file, where top level await is not allowed. Looking at the code for `.partial()`, it doesn't seem like there's any need for the async coloring on the function, as it just sets the values of the partial variables, but of course doesn't execute its inner functions. If you want to have an async function as the partial value that's ok because they will be evaluated during `invoke` if I'm not mistaken.

Alternatively, it would be nice to modify `fromMessages` to be able to take `inputVariables` and `partialVariables` fields, as these cannot be specified if using the message array format, so you need to set the generic constraint manually to ensure the variable typings are captured. And then you can set the partialVariables directly without the need of awaiting or modifying the existing `.partial()` api. So the above code could look like this instead:

```typescript
const prompt = ChatPromptTemplate.fromMessages([
  [
    "system",
    "The current date is {date}",
  ],
  ["human", "{query}"],
  { inputVariables: ["query"], partialVariables: { date: () => new Date().toISOString() } },
])

// const prompt: ChatPromptTemplate<InputValues<"query">, any>
```

### System Info

```
$ pnpm info langchain

langchain@0.2.9 | MIT | deps: 16 | versions: 281
```
macos
node v21.5.0

**Comment by jacoblee93** [comment]
Agreed - there were some niche use-cases back in the day but I think this would be nice to make sync. CC @nfcampos
