### ISSUE TITLE
Caching gives wrong hits for complex messages (i.e., with images and text prompt)

### ISSUE THREAD

**Issue by septagram** [langchain-ai/langchainjs#6024]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```typescript
    const model = new AzureChatOpenAI({
      openAIApiKey: this.configService.get<string>('AI_API_KEY'),
      azureOpenAIBasePath: LLM_URL,
      azureOpenAIApiDeploymentName: `${LLM_DEPLOYMENT_PREFIX}/${model}`,
      openAIApiVersion: '2024-05-01-preview',
      model,
      temperature: LLM_GPT_TEMPERATURE,
      cache: true,
    });
...
const prompt = ChatPromptTemplate.fromMessages([
      [
        'human',
        [
          {
            type: 'text',
            text: 'Find all {object_name} on the provided image', // Just an example; different unless the same operation is being run
          {
            type: 'image_url',
            image_url: '{imageUrl}', // Different images every time unless the same operation is being run
          },
        ],
      ],
    ]);
...
    const objects = ['cats', 'dogs'];
    const chain = RunnableSequence.from([prompt, model]);
    const responses = Promise.all(objects.map((object_name, index) => {
       await new Promise(resolve => setTimeout(resolve, 30000 * index));
       const values = { object_name };
       await chain.invoke(values);
    }));
    console.log(responses); //second response would be the same as the first
```

### Description

When caching is enabled, regular text messages are handled fine, but the messages that contain both text and image are giving cache hits for every invocation after the first one is completed. Tapping into `InMemoryCache.lookup()`, it appears that the messages are converted into the string like `"Human: [object Object],[object Object]"`. This `.toString()` transformation happens before the `lookup()` function is called, so other types of cache should be affected as well.

**Expected result:**

Full content from all parts of the complex message (including image content) should be used, and for that matter, the entire history of messages should be used, in case chat history is being used (not 100% sure this is not the case; at a glance it seemed like only the last message is used for lookup).

This happens at least in `AzureChatOpenAI`, tested with `langchain@0.2.9`.

**Comment by septagram** [comment]
@dosu A most reasonable suggestion, my artificially intelligent friend (and from a very quick glance it checks out; I've seen the function in question). But these changes have to be done within LangChain. I could try making a PR, if a member of a dev team confirms that such a change would be merged. I feel we still would need human intervention here.

**Comment by bracesproul** [comment]
Thank you for flagging this, and sorry you're experiencing this issue! I'm pushing up a fix now, and will flag you once it's released.
