### ISSUE TITLE
[ConversationalRetrievalQAChain] Reusing LLM for questionGeneratorChain causes unwanted stream data

### ISSUE THREAD

**Issue by colintoh** [langchain-ai/langchainjs#603]
**Problem**
If we set `streaming:true` for `ConversationalRetrievalQAChain.fromLLM`, the question generated from `questionGeneratorChain` will be streamed to the frontend. 

**Expected behavior**
We actually only want the stream data from `combineDocumentsChain`.

**Why does this problem exist**
This is because the `model` parameter is passed down and reused for both `loadQAStuffChain` and `questionGeneratorChain`. 
See: https://github.com/hwchase17/langchainjs/blob/main/langchain/src/chains/conversational_retrieval_chain.ts#L149

**Fix**
Allow a custom `questionGeneratorLLM` to be passed via the `options` field.

```typescript
const { questionGeneratorTemplate, qaTemplate, questionGeneratorLLM, ...rest } = options;
    .......
    const questionGeneratorChain = new LLMChain({
      prompt: question_generator_prompt,
      llm: questionGeneratorLLM || new OpenAIChat({ temperature: 0 }),
    });
    .......
    return instance;
```

**Comment by delivey** [comment]
Seems like the same issue is present for `ChatVectorDBQAChain` as well.

**Comment by nfcampos** [comment]
The immediate fix for this issue is to do the following

```typescript
// construct your chain as before
const chain = ConversationalRetrievalQAChain.fromLLM(new ChatOpenAI({streaming: true, ...}), ...)
// after creating the chain override the LLM in the inner `questionGeneratorChain`
chain.questionGeneratorChain.llm = new ChatOpenAI()

// use the chain
```

We're working on a better solution

**Comment by iPanchalShubham** [comment]
> The immediate fix for this issue is to do the following
> 
> ```ts
> // construct your chain as before
> const chain = ConversationalRetrievalQAChain.fromLLM(new ChatOpenAI({streaming: true, ...}), ...)
> // after creating the chain override the LLM in the inner `questionGeneratorChain`
> chain.questionGeneratorChain.llm = new ChatOpenAI()
> 
> // use the chain
> ```
> 
> We're working on a better solution

WIth the current version of langchain, this snippet in my use-case works great, please have a look

`
  const chain = ConversationalRetrievalQAChain.fromLLM(
    streamingModel,
    (await vectorStore).asRetriever(),

    {
      qaChainOptions: {
        prompt: customPromptTemplate,
        type: "stuff",
        verbose: true,
      },

      verbose: true,
      memory: new BufferMemory({
        returnMessages: true,

        // k: 1, //remember the most recent  conversation
        chatHistory: new ChatMessageHistory(getPastMessages(pastMessages)),
        memoryKey: "chat_history", // Must be set to "chat_history"
        inputKey: "question", // The key for the input to the chain
        outputKey: "text", // The key for the final conversational output of the chain
      }),
      returnSourceDocuments: true,
      questionGeneratorChainOptions: {
        llm: nonStreamingModel,
      },
    }
  );
` 
fromLLM method check whether you have passed an LLM for generating question if yes it would use that, if not it will use the streaming model which will cause great issues.  
Refrence: https://github.com/hwchase17/langchainjs/blob/525fe837b4e67e5247038e25e8a261740e182a23/langchain/src/chains/conversational_retrieval_chain.ts#L226
