### ISSUE TITLE
Max token exceed error not handled for anthropic models

### ISSUE THREAD

**Issue by safi7** [langchain-ai/langchainjs#6033]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

Error response for large content:

The system encountered an unexpected error during processing. Try your request again.
    at BedrockChat._streamResponseChunks (D:\development\xxx\dddd-api\node_modules\@langchain\community\dist\chat_models\bedrock\web.cjs:530:31)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

### Error Message and Stack Trace (if applicable)

The system encountered an unexpected error during processing. Try your request again.
    at BedrockChat._streamResponseChunks (D:\development\xxx\dddd-api\node_modules\@langchain\community\dist\chat_models\bedrock\web.cjs:530:31)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

### Description

Hello,

I have been using langchain js since a while. I use BedrockChat class to interact with bedrock models such as llama, mistral, sonnet 3.5 and opus. Recently, I implemented error handling for max token exceeded however, it is only working for llama and mistral now, anthropic models such as sonnet and opus returns general error. I would like to know what is the reason and how to fix. I did update the npm package and stuff. I guess there might be updates from bedrock or anthropic.

### System Info

using latest @langchain/community in latest nodejs project

**Comment by jacoblee93** [comment]
Thanks for flagging - will try to look as soon as I can.
