### ISSUE TITLE
Issue on using model = OpenAI() in Langchain RunnableSequence method 

### ISSUE THREAD

**Issue by Baiyang66666666** [langchain-ai/langchainjs#6034]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

        const model = new AzureChatOpenAI({
            azureOpenAIApiInstanceName: "viva-ai",
            azureOpenAIApiKey: "xxxx",
            azureOpenAIApiDeploymentName: "xxx-gpt4",
            azureOpenAIApiVersion: "2023-05-15",
            // baseURL: `https://gateway.ai.cloudflare.com/v1//${env.cloudflareAccountId}/${organization.toLowerCase()}-gateway/azure-openai/viva-ai/vivacity-gpt4`,
        })
        
        const resource = 'viva-ai';
        const modelname = 'vivacity-gpt4';
        const apiVersion = '2023-05-15';
        const apiKey = 'xxxx';

        const model2 = new OpenAI({
            apiKey,
            baseURL: `https://gateway.ai.cloudflare.com/v1/xxx/xxx/azure-openai/viva-ai/vivacity-gpt4`,
            defaultQuery: { 'api-version': apiVersion },
            defaultHeaders: { 'api-key': apiKey },
          });
          
        console.log("model3 type:", typeof model3);
        console.log("model3 instance:", model3);        

        const store = await getStore(env, organization);
        const storeRetriever = store.asRetriever();

        const prompt_temp = PromptTemplate.fromTemplate(`Answer the question based only on the following context:
            {context}
            
            Question: {question}`);

        const chain = RunnableSequence.from([
            {
                context: storeRetriever.pipe(formatDocumentsAsString),
                question: new RunnablePassthrough(),
            },
            prompt_temp,
            model2,
        ]);
        const res = await chain.pipe(new HttpResponseOutputParser({ contentType: "text/event-stream" })).stream(prompt);

### Error Message and Stack Trace (if applicable)

[wrangler:inf] POST /cf-ai/translate 500 Internal Server Error (554ms)
Error in translateController: Error: Expected a Runnable, function or object.                                                                                                   
Instead got an unsupported type.                                                                                                                                                
    at _coerceToRunnable (file:///C:/Users/baiya/OneDrive/%E6%A1%8C%E9%9D%A2/VIVACITY/cf-ai-workers/.wrangler/tmp/dev-6LO4HO/index.js:35345:11)                                 
    at _coerceToRunnable (file:///C:/Users/baiya/OneDrive/%E6%A1%8C%E9%9D%A2/VIVACITY/cf-ai-workers/.wrangler/tmp/dev-6LO4HO/index.js:35339:24)
    at _coerceToRunnable (file:///C:/Users/baiya/OneDrive/%E6%A1%8C%E9%9D%A2/VIVACITY/cf-ai-workers/.wrangler/tmp/dev-6LO4HO/index.js:35339:24)
    at RunnableSequence.from (file:///C:/Users/baiya/OneDrive/%E6%A1%8C%E9%9D%A2/VIVACITY/cf-ai-workers/.wrangler/tmp/dev-6LO4HO/index.js:36477:17)
    at translateController (file:///C:/Users/baiya/OneDrive/%E6%A1%8C%E9%9D%A2/VIVACITY/cf-ai-workers/.wrangler/tmp/dev-6LO4HO/index.js:48446:36)
    at async Object.fetch (file:///C:/Users/baiya/OneDrive/%E6%A1%8C%E9%9D%A2/VIVACITY/cf-ai-workers/.wrangler/tmp/dev-6LO4HO/index.js:40185:33)
    at async drainBody (file:///C:/Users/baiya/OneDrive/%E6%A1%8C%E9%9D%A2/VIVACITY/cf-ai-workers/.wrangler/tmp/dev-6LO4HO/index.js:50145:12) {
  stack: Error: Expected a Runnable, function or object.
In…rkers/.wrangler/tmp/dev-6LO4HO/index.js:50145:12),
  message: Expected a Runnable, function or object.
Instead got an unsupporte

### Description

I want to use Azure OpenAI gpt4 model here, while the first model shown here(const model = new AzureChatOpenAI) works well with Langchain RunnableSequence method, but can not connect to Cloudflare AI gateway. So I tried to build the model2 ( const model2 = new OpenAI() following the official guidance to make AI Gateway works. However, when using the model2, there is always an unsupported type issue.

I print the info of model2:
model2 type: object
model2 instance: OpenAI {                                                                                                                                                       
  baseURL: https://gateway.ai.cloudflare.com/v1/30480d77542bf…48c/iq-gateway/azure-openai/viva-ai/vivacity-gpt4,                                                                
  maxRetries: 2,                                                                                                                                                                
  timeout: 600000,
  httpAgent: undefined,
  fetch: Proxy(Function)
  ...
}

Could you please give me advice how to make it work well both on Langchain RunnableSequence method and Cloudflare AI gateway? Got stuck here for a long time. Important to me, thank you so much.

### System Info

windows

    "@cloudflare/ai": "^1.0.39",
    "@langchain/cloudflare": "^0.0.6",
    "langchain": "^0.2.7",
    "openai": "^4.47.1",

**Comment by bracesproul** [comment]
`OpenAI` is the LLM integration, did you mean to import [`ChatOpenAI`](https://v02.api.js.langchain.com/classes/langchain_openai.ChatOpenAI.html)?

**Comment by Baiyang66666666** [comment]
> `OpenAI` is the LLM integration, did you mean to import [`ChatOpenAI`](https://v02.api.js.langchain.com/classes/langchain_openai.ChatOpenAI.html)?

Thanks for reply, here is the package I am using:
import {OpenAI} from "@langchain/openai";

So the issue is that the model created in this way 
    const model2 = new OpenAI({
        apiKey,
        baseURL: `https://gateway.ai.cloudflare.com/v1/xxx/xxx/azure-openai/viva-ai/vivacity-gpt4`,
        defaultQuery: { 'api-version': apiVersion },
        defaultHeaders: { 'api-key': apiKey },
      });
cannot be used in Langchain RunnableSequence method.

**Comment by jacoblee93** [comment]
Does this work locally?

Echoing what Brace said, `gpt-4` is a chat model, you probably want to use the `ChatOpenAI` class:

https://js.langchain.com/v0.2/docs/concepts#chat-models
https://js.langchain.com/v0.2/docs/integrations/chat/openai

**Comment by dmitry-brazhenko** [comment]
@jacoblee93 seems that the issue is that ChatOpenAI class does not accept defaultHeaders parameter. But OpenAI does

**Comment by dmitry-brazhenko** [comment]
@jacoblee93  is it possible to pass defaultheaders to ChatOpenAI class?

**Comment by jacoblee93** [comment]
Try this:

```ts
const model2 = new OpenAI({
  apiKey,
  // Pass extra client-specific params here:
  configuration: {
    baseURL: https://gateway.ai.cloudflare.com/v1/xxx/xxx/azure-openai/viva-ai/vivacity-gpt4,
    defaultQuery: { 'api-version': apiVersion },
    defaultHeaders: { 'api-key': apiKey },
  }
});
```
