### ISSUE TITLE
ChatBedrockConverse - https://langchain-ai.github.io/langgraphjs/#example

### ISSUE THREAD

**Issue by MarcoLooy** [langchain-ai/langchainjs#6052]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

import {HumanMessage} from "@langchain/core/messages";
import {DynamicStructuredTool} from "@langchain/core/tools";
import {z} from "zod";
// import {ChatAnthropic} from "@langchain/anthropic";
import {ChatBedrockConverse} from "@langchain/aws";
import {END, START, StateGraph, MemorySaver} from "@langchain/langgraph";
import {ToolNode} from "@langchain/langgraph/prebuilt";

// Define the graph state
const graphState = {
  messages: {
    value: (x, y) => x.concat(y),
    default: () => [],
  },
};

// Define the tools for the agent to use
const searchTool = new DynamicStructuredTool({
  name: "weather",
  description: "Get the weather information for a city.",
  schema: z.object({
    query: z.string().describe("The query to use in your search."),
  }),
  func: async ({query}) => {
    // This is a placeholder for the actual implementation
    if (
      query.toLowerCase().includes("sf") ||
      query.toLowerCase().includes("san francisco")
    ) {
      return "It's 60 degrees and foggy.";
    }
    return "It's 90 degrees and sunny.";
  },
});

const tools = [searchTool];
const toolNode = new ToolNode(tools);

const model = new ChatBedrockConverse({
  model: "anthropic.claude-3-5-sonnet-20240620-v1:0",
  region: "us-east-1",
  temperature: 0,
}).bindTools(tools);

// Define the function that determines whether to continue or not
function shouldContinue(state) {
  const messages = state.messages;
  const lastMessage = messages[messages.length - 1];
  // If the LLM makes a tool call, then we route to the "tools" node
  if (lastMessage.tool_calls?.length) {
    return "tools";
  }
  // Otherwise, we stop (reply to the user)
  return END;
}

// Define the function that calls the model
async function callModel(state) {
  const messages = state.messages;
  const response = await model.invoke(messages);
  // We return a list, because this will get added to the existing list
  return {messages: [response]};
}

// Define a new graph
const workflow = new StateGraph({channels: graphState})
  .addNode("agent", callModel)
  .addNode("tools", toolNode)
  .addEdge(START, "agent")
  .addConditionalEdges("agent", shouldContinue)
  .addEdge("tools", "agent");

// Initialize memory to persist state between graph runs
const checkpointer = new MemorySaver();

// Finally, we compile it!
// This compiles it into a LangChain Runnable.
// Note that we're (optionally) passing the memory when compiling the graph
const app = workflow.compile({checkpointer});

// Use the Runnable
(async () => {
  const finalState = await app.invoke(
    {messages: [new HumanMessage("what is the weather in sf")]},
    {configurable: {thread_id: "42"}}
  );
  console.log(finalState.messages[finalState.messages.length - 1].content);
})();

### Error Message and Stack Trace (if applicable)

/home/ubuntu/chat-bedrock-converse/node_modules/@aws-sdk/client-bedrock-runtime/dist-cjs/index.js:1082
  const exception = new ValidationException({
                    ^

ValidationException: The model returned the following errors: Your API request included an `assistant` message in the final position, which would pre-fill the `assistant` response. When using tools, pre-filling the `assistant` response is not supported.
    at de_ValidationExceptionRes (/home/ubuntu/chat-bedrock-converse/node_modules/@aws-sdk/client-bedrock-runtime/dist-cjs/index.js:1082:21)
    at de_CommandError (/home/ubuntu/chat-bedrock-converse/node_modules/@aws-sdk/client-bedrock-runtime/dist-cjs/index.js:937:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/ubuntu/chat-bedrock-converse/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20
    at async /home/ubuntu/chat-bedrock-converse/node_modules/@smithy/core/dist-cjs/index.js:165:18
    at async /home/ubuntu/chat-bedrock-converse/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38
    at async /home/ubuntu/chat-bedrock-converse/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:34:22
    at async ChatBedrockConverse._generateNonStreaming (file:///home/ubuntu/chat-bedrock-convers/node_modules/@langchain/aws/dist/chat_models.js:219:26)
    at async Promise.allSettled (index 0)
    at async ChatBedrockConverse._generateUncached (file:///home/ubuntu/chat-bedrock-converse/node_modules/@langchain/core/dist/language_models/chat_models.js:173:29) {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 400,
    requestId: '687b34bb-1b95-44d8-b2d2-5376e1058bc3',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  }
}

Node.js v18.18.0

### Description

The @langchain/aws **ChatBedrockConverse** implementation does not work with the standard Langgraph example. 

https://langchain-ai.github.io/langgraphjs/#example

### System Info

Node.js v18.18.0

  "dependencies": {
    "@aws-sdk/credential-provider-node": "^3.609.0",
    "@langchain/aws": "^0.0.1",
    "@langchain/core": "^0.2.14",
    "@langchain/langgraph": "^0.0.26",
    "zod": "^3.23.8"
  }

**Comment by bracesproul** [comment]
Fixed by https://github.com/langchain-ai/langchainjs/pull/6043

This code will be released sometime today, then you'll have access to the fix. Thank you for your patience with this.

**Comment by MarcoLooy** [comment]
@bracesproul super cool. Thanks a lot for fixing the issue, very much appreciated!
