### ISSUE TITLE
create appendChain to switch between Chains

### ISSUE THREAD

**Issue by Lionardo** [langchain-ai/langchainjs#606]
how can I change from ChatVectorDBQAChain to ConversationChain in langchainjs?
It would be great to have something like  **AppendChain** contruct that allows to add multiple chains. e.g.

```
const qaChain = new ChatVectorDBQAChain({
    vectorstore,
    combineDocumentsChain: docChain,
    questionGeneratorChain: questionGen,
    returnSourceDocuments: false,
    k: 1,
  }

  const convChain = new ConversationChain({
      llm: model,
      outputKey: "text",
    });

//The idea here is that if the response of the chain has a string of "Can't find in the documents..." 
// then  it will continue with the conversationalChain

const finalChain = new AppendChain([
  {chain: qaChain, passThroughCondition: "Can't find" },
  {chain: convChain, passthrough condition: "" },
], defaultChain: qaChain)

``` 

Is there a different approach to solving this requirement that is already available?

**Comment by pax-k** [comment]
I was looking for the same thing. Maybe you're referring to `QA_PROMPT` :) 
I fixed the prompt instead, telling it `If you can't find the answer, say "I don't have the right data, but from my knowledge" and continue to provide an answer based on your training data`

**Comment by Lionardo** [comment]
@pax-k Can't get it to answer outside of the embeddings even if I change the QA_PROMPT. Did you do any other changes?
