### ISSUE TITLE
error when I was making build process with nextjs 14

### ISSUE THREAD

**Issue by momensalama** [langchain-ai/langchainjs#6103]
hello @dosu,

I tried to run `npm run build` and this error popped up.

<img width="1149" alt="Screenshot 2024-07-17 at 12 07 08 PM" src="https://github.com/user-attachments/assets/5ea698a5-e50a-4d37-8011-7d9aecdb8907">

here are my `next.config.js` configurations:
<img width="639" alt="Screenshot 2024-07-17 at 12 07 58 PM" src="https://github.com/user-attachments/assets/1b501e99-3ee2-4ba6-96f9-11a11ed0a0f4">

_Originally posted by @momensalama in https://github.com/langchain-ai/langchainjs/issues/5161#issuecomment-2232820942_

**Comment by momensalama** [comment]
@dosu

I tried to follow your steps and this did not solve the problem.

here are the imports from Langchain 

<img width="883" alt="Screenshot 2024-07-17 at 1 42 44 PM" src="https://github.com/user-attachments/assets/42a97d8a-4442-4462-8619-23f553375393">

and here is my package.js

<img width="872" alt="Screenshot 2024-07-17 at 1 49 42 PM" src="https://github.com/user-attachments/assets/3f595cb6-314e-4eb3-b38e-12d5ecee0bf0">

also here is the Updated Webpack Configuration in my `next.config.mjs`

<img width="940" alt="Screenshot 2024-07-17 at 1 51 02 PM" src="https://github.com/user-attachments/assets/7c3f172f-d6c0-4206-be72-2c25edcc8433">

**Comment by momensalama** [comment]
@dosu

Unfortunately, all your steps did not work.

**Comment by momensalama** [comment]
@dosu

also did not work ):

**Comment by momensalama** [comment]
@jacoblee93 could you help me with this error?

**Comment by momensalama** [comment]
@dosu 
@jacoblee93 

I tried this solution https://github.com/vercel/next.js/issues/60807#issuecomment-2087055777 and it works

**Comment by jacoblee93** [comment]
Ah ok good to hear!

**Comment by debsouryadatta** [comment]
> @dosu @jacoblee93
> 
> I tried this solution [vercel/next.js#60807 (comment)](https://github.com/vercel/next.js/issues/60807#issuecomment-2087055777) and it works

Thanks @momensalama , I was searching the fix for a long time, it did resolve🙌
