### ISSUE TITLE
DallEAPIWrapper returns only one image url even though n > 1

### ISSUE THREAD

**Issue by mya03** [langchain-ai/langchainjs#6151]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

The code that where I use DallEAPIWrapper looks something similar to this:
```typescript
import { ChatOpenAI, DallEAPIWrapper } from "@langchain/openai"; 

async generateImage(params: ImageDto){
        const {prompt, numImages, model} = params;
        
        const tool = new DallEAPIWrapper({
            apiKey: API_KEY,
            model,
           n: numImages //numImages = 2 for example
        });
       
       const result = tool.invoke({prompt});
       return result;
```

### Description

I am trying to generate multiple images using the DallEAPIWrapper tool in my project but I think it currently only returns the first image url even though I set n to be 2.

### System Info

"langchain": "^0.2.10"
 "@langchain/openai": "^0.2.2"

**Comment by bracesproul** [comment]
hey @mya03 thanks for flagging this. I just put up a PR which allows for passing `n > 1`, and returning a list of [`MessageContentImageUrl`](https://v02.api.js.langchain.com/types/langchain_core_messages.MessageContentImageUrl.html) objects containing either the image URLs or the base64 strings.
