### ISSUE TITLE
Cannot npm install @langchain/ollama because wrong version of @langchain/core dependency is defined

### ISSUE THREAD

**Issue by ruckerzerg** [langchain-ai/langchainjs#6159]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```json
{
  "name": "@langchain/ollama",
  "version": "0.0.1",
  "description": "Ollama integration for LangChain.js",
  ...
  "dependencies": {
    "@langchain/core": ">0.2.17 <0.3.0",
    "ollama": "^0.5.6",
    "uuid": "^10.0.0"
  },
  ...
```

### Error Message and Stack Trace (if applicable)

```
npm error code ETARGET
npm error notarget No matching version found for @langchain/core@>0.2.17 <0.3.0.
npm error notarget In most cases you or one of your dependencies are requesting
npm error notarget a package version that doesn't exist.
```

### Description

Dependency `"@langchain/core": ">0.2.17 <0.3.0"` is wrong, as it requires version greater than `0.2.17` but `0.2.17` is currently the latest.

### System Info

.

**Comment by bracesproul** [comment]
Sorry you're experiencing this! I just pushed a fix on version `0.0.2`. If you're still experiencing the issue, please let me know.
