### ISSUE TITLE
No reference from /v0.2/docs/how_to page to /v0.2/docs/how_to/structured_output

### ISSUE THREAD

**Issue by tikolakin** [langchain-ai/langchainjs#6162]
### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

The link to can be found on https://js.langchain.com/v0.2/docs/concepts#structured-output. 
Specifically
"For more information, check out this [how-to guide](https://js.langchain.com/v0.2/docs/how_to/structured_output/#the-.withstructuredoutput-method)."

However, the link to the documentation page https://js.langchain.com/v0.2/docs/how_to/structured_output cannot be found on https://js.langchain.com/v0.2/docs/how_to page

There are other examples like it - https://js.langchain.com/v0.2/docs/how_to/streaming/#using-stream
maybe more, but difficult to discover all missed. 

Can all how to guide pages be referenced from https://js.langchain.com/v0.2/docs/how_to page ?

Thanks

**Comment by bracesproul** [comment]
Hey @tikolakin the [Structured Output page](https://js.langchain.com/v0.2/docs/how_to/structured_output/) can be found on the [How To index page](https://js.langchain.com/v0.2/docs/how_to/) in two places:
- The `Chat Models` section, under `How to: get models to return structured output`
- The `Key features` section, under `How to: return structured data from an LLM`
