### ISSUE TITLE
DOC: Need improvement in langchain js docs V 0.2

### ISSUE THREAD

**Issue by juzarantri** [langchain-ai/langchainjs#6178]
### URL

https://js.langchain.com/v0.2/docs/integrations/retrievers/vectorstore

### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

With the new version of doc V 0.2 in langchain JS its getting hard to find the exact infomation regarding the stuff developer are looking for. The version V0.1 was pretty handly and it contained the description of all the retrievers and everything. But finding the context in V0.2 is very difficult. Please update the content or website to make it handy.

Else the overall functionality is awesome

### Idea or request for content:

I am mainly focusing to improve the description part of every aspects on langchain V0.2

**Comment by jacoblee93** [comment]
This is not great - thank you for raising this. Will have a look (CC @bracesproul as well)

**Comment by juzarantri** [comment]
@jacoblee93 I want to get help contributing to langchain community. I have few question if you can guide me through it.

Questions:
1. There are many issues listed on the langchain repository. How do I know which issue to pick up and solve? bcz the issue might have been generated by the user who might have made a mistake while running the code.
2. If I start working on any of the issue then and add some lines of code how do I ensure that it is working or not breaking the existing code.

Still there will be more question as I dig deep in. I will love to hear back from you. Also let me know if this is the right way to communicate with you or there is any other medium. 

Thanks

**Comment by jacoblee93** [comment]
Hey @juzarantri sorry for missing your message!

We need to do a bit better with labelling - at the moment the best thing to do is try your own projects with LangChain. If you then have issues we'd love for you to open issues.

You can then check out the docs here for more on opening PRs:

https://js.langchain.com/v0.2/docs/contributing
