### ISSUE TITLE
Forced function calling not supported in ChatVertexAI

### ISSUE THREAD

**Issue by DevDeepakBhattarai** [langchain-ai/langchainjs#6190]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```typescript
let modelObject = new ChatVertexAI({
        model: "gemini-1.5-flash-001",
        authOptions: {
          credentials: {
            auth_provider_x509_cert_url: env.GOOGLE_AUTH_PROVIDER_X509_CERT_URL,
            auth_uri: env.GOOGLE_AUTH_URI,
            client_email: env.GOOGLE_CLIENT_EMAIL,
            client_id: env.GOOGLE_VERTEX_CLIENT_ID,
            client_x509_cert_url: env.GOOGLE_CLIENT_X509_CERT_URL,
            private_key: env.GOOGLE_PRIVATE_KEY,
            private_key_id: env.GOOGLE_PRIVATE_KEY_ID,
            project_id: env.GOOGLE_PROJECT_ID,
            token_uri: env.GOOGLE_TOKEN_URI,
            type: "service_account",
          },
        },
        temperature: 0,
      });

modelObject= modelObject.bindTools(tools, {tool_choice:"any"})  // tool_choice cannot be passed 
```

### Description

I am trying to build a multi agent architecture with Langgraph using the Gemini API from Vertex AI. In the first step of multiagent system in langgraph , forced function calling is very much necessary but it seems `ChatVertexAI` does not have an option to pass `tool_choice` parameter. 

The forced function calling is supported in Gemini ([here](https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/function-calling#tool-config)).  But it seems langchain is lacking this feature

The other provider like `ChatOpenAI` `ChatAnthropic` `ChatGroq` have the option to pass the `tool_choice` parameter when binding the tool.

It would be really helpful if this was implemented

### System Info

pnpm 9.4.0
windows 10 
node 18

**Comment by bracesproul** [comment]
Thanks for flagging this, will work on adding it today!

**Comment by afirstenberg** [comment]
See #5072
