### ISSUE TITLE
google-common [minor]: Custom events containing request/response JSON

### ISSUE THREAD

**Issue by afirstenberg** [langchain-ai/langchainjs#6207]
### Privileged issue

- [X] I am a LangChain maintainer, or was asked directly by a LangChain maintainer to create an issue here.

### Issue Content

It would be useful, particularly for debugging purposes, if there were custom callback events that include the JSON of the exact request and response, and possibly other attributes such as the endpoint sent to, response code, etc.

See https://js.langchain.com/v0.2/docs/how_to/callbacks_custom_events/

**Comment by meliadamian17** [comment]
@afirstenberg Is it possible to provide an example with an expected outcome?

**Comment by afirstenberg** [comment]
This is actually addressed in #6999 
(I had forgotten this was still open.)
