### ISSUE TITLE
Unable to use CSVLoader on cloudflare page/worker

### ISSUE THREAD

**Issue by yhmjSky** [langchain-ai/langchainjs#6224]
### Checked other resources

- [ ] I added a very descriptive title to this issue.
- [x] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

// this is a simple example on cf worker
``` ts
import { CharacterTextSplitter } from "langchain/dist/text_splitter";
import {CSVLoader} from 'langchain/document_loaders/fs/csv'

export interface Env {
// no content
}

export default {
	async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
		const url = new URL(request.url);

		switch (request.method) {
		  case "GET":
			return new Response('Please use the post form!');
		  
		  case "POST":
			const form = await request.formData();
			let file = form.get("file") as unknown as File;
			const loader = new CSVLoader(file);
			const docs = await loader.load();
			const res = Response.json(docs);
			res.headers.set("Access-Control-Allow-Origin", "*");
			return res;
			// return Response.json(documents)
		  default:
			return new Response("Method Not Allowed", {
			  status: 405,
			  headers: {
				Allow: "GET, POST"
			  }
			});
		}

	},
};
```

### Error Message and Stack Trace (if applicable)

``` log
[mf:err] EvalError: Code generation from strings disallowed for this context
    at [object Object]
    at objectConverter (D:\WebstormProjects\cf-worker\file-csv-worker\.wrangler\node_modules\d3-dsv\src\dsv.js:8:10)
    at null.<anonymous> (D:\WebstormProjects\cf-worker\file-csv-worker\.wrangler\node_modules\d3-dsv\src\dsv.js:67:62)
    at parseRows (D:\WebstormProjects\cf-worker\file-csv-worker\.wrangler\node_modules\d3-dsv\src\dsv.js:115:23)
    at Object.parse (D:\WebstormProjects\cf-worker\file-csv-worker\.wrangler\node_modules\d3-dsv\src\dsv.js:65:34)
    at CSVLoader.parse (D:\WebstormProjects\cf-worker\file-csv-worker\.wrangler\node_modules\langchain\dist\document_loaders\fs\csv.js:46:28)
    at async CSVLoader.load (D:\WebstormProjects\cf-worker\file-csv-worker\.wrangler\node_modules\langchain\dist\document_loaders\fs\text.js:60:24)
    at async Object.fetch (D:\WebstormProjects\cf-worker\file-csv-worker\.wrangler\src\worker.ts:46:17)
    at async jsonError (D:\WebstormProjects\cf-worker\file-csv-worker\.wrangler\node_modules\wrangler\templates\middleware\middleware-miniflare3-json-error.ts:22:10)
```

### Description

I'm working on a svelte project and need to use a document splitter to process csv files. In the local development environment, CSVLoader works fine, but when I deploy to cloudflare page, it shows: 
```
"message": [
  "EvalError: Code generation from strings disallowed for this context"
],
"level": "error",
```
Cloudflare worker does not seem to allow running eval? I can't confirm if the problem is with within d3-dsv.

### System Info

platform: Windows
node: v18.17.0
npm: 9.6.7

*more*
langchain@0.2.11
d3-dsv@2

**Comment by yhmjSky** [comment]
Sorry, I have located the problem to a function in d3-dsv dsv.js:
![image](https://github.com/user-attachments/assets/9bc249da-a90a-469a-b12c-3b57bdbe0c4c)

This is a reference [d3-dsv #94](https://github.com/d3/d3-dsv/issues/94)
I can only rewrite it now.

**Comment by TowhidKashem** [comment]
i think you get a similar error when trying to use handlebars templates on workers cause it uses eval and/or requires direct file system access using fs module which isn't available in a worker env (only node). So someone made this lib `hbs-async-render` to get around that but it's not as performant. Anyway for ur issue maybe try enabling node on the worker:

`compatibility_flags = ["nodejs_compat"] # add this to ur wrangler.toml`

and see if that helps. If not, not sure what the solution would be.

**Comment by yhmjSky** [comment]
> 我认为在尝试在 Worker 上使用 Handlebars 模板时会遇到类似的错误，因为它使用 eval 和/或需要使用 fs 模块直接访问文件系统，这在 worker env（仅节点）中不可用。所以有人制作了这个库来解决这个问题，但它的性能不如现在。无论如何，对于您的问题，可以尝试在工作器上启用节点：`hbs-async-render`
> 
> `compatibility_flags = ["nodejs_compat"] # add this to ur wrangler.toml`
> 
> 看看是否有帮助。如果没有，不确定解决方案是什么。

Node compatibility does not solve the problem. 
I currently copy a CSVLoader and edit default import.
![image](https://github.com/user-attachments/assets/ae0cc940-9f48-4f85-9f0a-3b97f4a50f18)
This can only be a temporary solution,

**Comment by yhmjSky** [comment]
Enabling compatibility has no effect
Currently I copied a copy of CSVLoader and changed the default import to the modified d3-dsv
