### ISSUE TITLE
Import Error: 'isOpenAITool' is not exported from '@langchain/core/language_models/base'

### ISSUE THREAD

**Issue by rossanodr** [langchain-ai/langchainjs#6256]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

import { isOpenAITool } from '@langchain/core/language_models/base';

### Error Message and Stack Trace (if applicable)

Next.js 14.2.3
  - Environments: .env.production, .env
  - Experiments (use with caution):
    · esmExternals

   Creating an optimized production build ...
Failed to compile.

./node_modules/langchain/dist/agents/structured_chat/index.js
Attempted import error: 'isOpenAITool' is not exported from '@langchain/core/language_models/base' (imported as 'isOpenAITool').

Import trace for requested module:
./node_modules/langchain/dist/agents/structured_chat/index.js
./node_modules/langchain/dist/agents/index.js
./node_modules/langchain/agents.js

./node_modules/langchain/dist/tools/render.js
Attempted import error: 'isOpenAITool' is not exported from '@langchain/core/language_models/base' (imported as 'isOpenAITool').

Import trace for requested module:
./node_modules/langchain/dist/tools/render.js
./node_modules/langchain/dist/agents/structured_chat/index.js
./node_modules/langchain/dist/agents/index.js
./node_modules/langchain/agents.js

./node_modules/langchain/dist/tools/render.js
Attempted import error: 'isOpenAITool' is not exported from '@langchain/core/language_models/base' (imported as 'isOpenAITool').

Import trace for requested module:
./node_modules/langchain/dist/tools/render.js
./node_modules/langchain/dist/agents/structured_chat/index.js
./node_modules/langchain/dist/agents/index.js
./node_modules/langchain/agents.js

> Build failed because of webpack errors.

### Description

I'm trying to build a Next.js application using the langchain library. During the production build (yarn build), I encounter the following error:

Attempted import error: 'isOpenAITool' is not exported from '@langchain/core/language_models/base' (imported as 'isOpenAITool').
he issue seems to be related to the isOpenAITool import in several files within the langchain package.

Expected behavior:

The build should complete successfully without import errors.
Actual behavior:

The build fails with the aforementioned import error.

### System Info

yarn info langchain
└─ langchain@npm:0.2.11
   ├─ Instances: 1
   ├─ Version: 0.2.11
   │
   └─ Dependencies
      ├─ @langchain/core@npm:0.2.6 → npm:0.2.6
      ├─ @langchain/openai@npm:>=0.1.0 <0.3.0 → npm:0.2.5
      ├─ @langchain/textsplitters@npm:~0.0.0 → npm:0.0.3
      ├─ binary-extensions@npm:^2.2.0 → npm:2.3.0
      ├─ js-tiktoken@npm:^1.0.12 → npm:1.0.12
      ├─ js-yaml@npm:^4.1.0 → npm:4.1.0
      ├─ jsonpointer@npm:^5.0.1 → npm:5.0.1
      ├─ langchainhub@npm:~0.0.8 → npm:0.0.11
      ├─ langsmith@npm:~0.1.30 → npm:0.1.32
      ├─ ml-distance@npm:^4.0.0 → npm:4.0.1
      ├─ openapi-types@npm:^12.1.3 → npm:12.1.3
      ├─ p-retry@npm:4 → npm:4.6.2
      ├─ uuid@npm:^10.0.0 → npm:10.0.0
      ├─ yaml@npm:^2.2.1 → npm:2.4.5
      ├─ zod-to-json-schema@npm:^3.22.3 → npm:3.23.1
      └─ zod@npm:^3.22.4 → npm:3.23.8

**Comment by bracesproul** [comment]
If you update to the latest version of core `0.2.18` do you still experience this issue?

**Comment by rossanodr** [comment]
> If you update to the latest version of core `0.2.18` do you still experience this issue?

Same error with the following dependencies: 
"dependencies": {
"@langchain/community": "^0.2.10",
        "@langchain/core": "^0.2.18",
        "@langchain/google-genai": "0.0.19",
        "@langchain/google-vertexai": "^0.0.17",
        "@langchain/google-vertexai-web": "^0.0.17",
        "@langchain/langgraph": "^0.0.25",
        "@langchain/openai": "^0.2.5",
         "langchain": "^0.2.11",
}
   "resolutions": {
            "@langchain/core": "0.2.6"
    },

**Comment by bracesproul** [comment]
If you set `resolutions` that will override the version in your `dependency` object. Bump the `resoultions.@langchain/core` version and it should be good.

**Comment by bracesproul** [comment]
Going to close this issue now. Let me know if you experience more issues with this!

**Comment by rossanodr** [comment]
> If you set `resolutions` that will override the version in your `dependency` object. Bump the `resoultions.@langchain/core` version and it should be good.

thanks. It worked after i deleted the node modules folder and bumped the resolutions
