### ISSUE TITLE
Allow Auth w/ Chroma

### ISSUE THREAD

**Issue by justinlevi** [langchain-ai/langchainjs#6296]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

I do not see any way to add auth via the chroma wrapper here:
https://github.com/langchain-ai/langchainjs/blob/993ce7a822bd11e125419bff84a9951bd58e66e5/langchain/src/vectorstores/chroma.ts#L109C1-L112C8

### Description

The following issue was closed, but doesn't seem like it was ever fixed
https://github.com/langchain-ai/langchainjs/issues/3441

### System Info

mac, osx, latest version of node, etc...

**Comment by justinlevi** [comment]
In Python I can do this:

```
from pathlib import Path
import json
from langchain_core.documents import Document
from langchain_openai import OpenAIEmbeddings
from langchain_chroma import Chroma
import chromadb
from chromadb.config import Settings

# credentials for basic auth
credentials = f"{username}:{hashed_password}"

host = "https://chroma-remote-host.business.com"
port = 8010
collection_name = "my_collection_name"

# Create client with authentication
client = chromadb.HttpClient(
    host=host,
    port=port,
    settings=Settings(
        allow_reset=True,
        chroma_client_auth_provider="basic",
        chroma_client_auth_credentials=credentials
    )
)

```

I don't see anywhere in the docs or in the code how I can do this with nodejs

**Comment by justinlevi** [comment]
In Typescript

```
import { Chroma } from '@langchain/community/vectorstores/chroma';

const host = 'https://chroma-remote-host.business.com'
const collectionName = 'my_collection_name';

const vectorStore = new Chroma(new OpenAIEmbeddings(), {
  url: host,
  collectionName: collectionName,
});

```

There is no auth object on `ChromaLibArgs`

```
export type ChromaLibArgs = {
    url?: string;
    numDimensions?: number;
    collectionName?: string;
    filter?: object;
    collectionMetadata?: CollectionMetadata;
} | {
    index?: ChromaClientT;
    numDimensions?: number;
    collectionName?: string;
    filter?: object;
    collectionMetadata?: CollectionMetadata;
};
```

whereas the `ChromaClient` has an `auth` property on the `ChromaClientParams`, this is not passed along in the langchain js Chroma wrapper class

```
type AuthOptions = {
    provider: ClientAuthProvider | string | undefined;
    credentialsProvider?: ClientAuthCredentialsProvider<any> | undefined;
    configProvider?: ClientAuthConfigurationProvider<any> | undefined;
    credentials?: any | undefined;
    providerOptions?: any | undefined;
};
```

**Comment by jeasonnow** [comment]
Hey, maybe you can give this a try? Right now, the version of chroma that langchainjs depends on is too old and doesn't support this configuration yet.
```typescript
Import the ChromaClient from 'chromadb';
Import Chroma from '@langchain/community/vectorstores/chroma';
const client = new ChromaClient({
  path: host,
  auth: {
    provider: 'basic',
    credentials: '${username}:${password}'
  }
});
const vectorStore = new Chroma(new OpenAIEmbeddings(), {
  index: client,
  collectionName: collectionName,
});
```

**Comment by justinlevi** [comment]
this seems to work. thank you
