### ISSUE TITLE
ChatOpenAI() isn't a BaseLLM and therefore cannot use in ConversationalRetrievalQAChain

### ISSUE THREAD

**Issue by clbarrell** [langchain-ai/langchainjs#636]
I'm trying to use the ConversationalRetrievalQAChain with GPT3.5 because it's cheaper than GPT3.

But when I try to use `new ChatOpenAI()` as the model for `ConversationalRetrievalQAChain` it gives an error because it doesn't have the properties of `name` and `_generateUncached` that are present in `BaseLLM`.

Is there anything I can do to resolve this for now?

```js
const chatModel = new ChatOpenAI();

const chain = ConversationalRetrievalQAChain.fromLLM(
  chatModel, // << TYPE ERROR
  vectorStore.asRetriever(),
  { returnSourceDocuments: true }
);
```

**Comment by nsantos16** [comment]
I suggest use 
```
const chatModel = new OpenAI({
      model: CHAT_GPT_MODEL
    });
```

**Comment by Achalogy** [comment]
Try importing this `const { OpenAIChat } = await import("langchain/llms");` instead of `ChatOpenAI`

**Comment by Achalogy** [comment]
I made it work with this:

```ts
class FixedBaseLLM extends BaseLLM {
      _generate(
        prompts: string[],
        stop?: string[] | undefined
      ): Promise<LLMResult> {
        throw new Error("Method not implemented.");
      }
      _llmType(): string {
        throw new Error("Method not implemented.");
      }
    }

    const llm: FixedBaseLLM = new OpenAIChat({
      openAIApiKey: ...,
    });
    
    const chain = ConversationalRetrievalQAChain.fromLLM(
      llm,
      this.Documents.asRetriever()
    );
```

**Comment by Achalogy** [comment]
```ts

class FixedBaseLLM extends BaseLLM {
  _generate(
    prompts: string[],
    stop?: string[] | undefined
  ): Promise<any> {
    throw new Error("Method not implemented.");
  }
  _llmType(): string {
    throw new Error("Method not implemented.");
  }
}

const llm: FixedBaseLLM = new OpenAIChat({
  openAIApiKey: ...,
});

const chain = ConversationalRetrievalQAChain.fromLLM(
  llm,
  this.Documents.asRetriever()
);

```

**Comment by ShantanuNair** [comment]
Wow, I didn't realize that openAI() was using GPT 3 instead of 3.5. Please, please make this more obvious in docs as it's not intuitive that the older, 10x more expensive model is the default. Unless for legacy reasons it stayed the same, but I'd imagine things are already moving too fast to be concerned with legacy right now.


@clbarrell @Achalogy @nsantos16 Have you got this working better than if you just called OpenAI() with modelName gpt-3.5-turbo ??

**Comment by Achalogy** [comment]
I think it won't work because completion and chat completion have different api endpoints.

**Comment by ShantanuNair** [comment]
@Achalogy looks like the constructor just calls chatOpenAI if the model name is gpt-3.5 turbo or gpt 4

**Comment by nelsonjchen** [comment]
https://github.com/hwchase17/langchainjs/blob/440500d81516ef9260e5da7a0c09a1d3a936ff4c/langchain/src/llms/openai.ts#L108

Done here. 

Anyway, swapping this makes things just work indeed!
