### ISSUE TITLE
google-common [bug]: Gemini response with no parts triggers error

### ISSUE THREAD

**Issue by afirstenberg** [langchain-ai/langchainjs#6371]
### Privileged issue

- [X] I am a LangChain maintainer, or was asked directly by a LangChain maintainer to create an issue here.

### Issue Content

I am occasionally getting the following error during processing:
```
>  /Users/prisoner/Documents/project/functions/node_modules/@langchain/google-common/dist/utils/gemini.cjs:504
>                  generationInfo: ret[ret.length - 1].generationInfo,
>                                                      ^
>
>  TypeError: Cannot read properties of undefined (reading 'generationInfo')
>      at responseToChatGenerations (/Users/prisoner/Documents/project/functions/node_modules/@langchain/google-common/dist/utils/gemini.cjs:504:53)
>      at responseToChatResult (/Users/prisoner/Documents/projectfunctions/node_modules/@langchain/google-common/dist/utils/gemini.cjs:562:25)
>      at safeResponseTo (/Users/prisoner/Documents/project/functions/node_modules/@langchain/google-common/dist/utils/gemini.cjs:374:25)
>      at safeResponseToChatResult (/Users/prisoner/Documents/projectfunctions/node_modules/@langchain/google-common/dist/utils/gemini.cjs:570:12)
>      at ChatGoogle._generate (/Users/prisoner/Documents/project/functions/node_modules/@langchain/google-common/dist/chat_models.cjs:270:62)
```

Looking at the code, I'm guessing that the earlier call
```
const parts = responseToParts(response);
```
is returning an empty array, which is legitimate, but usually only happens when the safety handler would be triggered, so the safety handler should have caught it first.

Several things need to be addressed:
* `ret[ret.length - 1].generationInfo` should have a optional property accessor
  * We should probably just short circuit if no parts are returned
* Evaluate the `DefaultSafetyHandler` to see if other finish reasons should trigger a problem. (Perhaps as part of another issue)

Platform: Vertex AI
Models: 
* gemini-1.5-pro-001
* gemini-1.5-flex-001

@jacoblee93 and @bracesproul - Please assign this to me

**Comment by afirstenberg** [comment]
The `DefaultSafetyHandler` appears to be working as designed.

The problem seems to be that https://github.com/langchain-ai/langchainjs/blame/e8da74b02822b197fe12d75a83e9eb32fbc0816a/libs/langchain-google-common/src/utils/gemini.ts#L487 assumes that the response can still be converted safely, even with missing fields.

The bug in the optional property accessor is preventing this. Fixing this is the best solution.

It might also make sense to have `DefaultSafetyHandler` check for missing parts as well, since that can't be a good thing, and clean it up before evaluating or throwing an exception.

Workaround is to use a `MessageGeminiSafetyHandler` which will return valid response data.

If we want an exception to be thrown, it gets messier.

**Comment by pksharmapokhrel** [comment]
Hi @afirstenberg,

The condition `ret.every((item) => typeof item.message.content === "string")` currently evaluates to true even when `ret` is empty. To address this, we could add a check for `ret.length > 0` alongside the existing condition.

This issue is impacting our production service, and we've implemented a retry logic as a temporary workaround. Could you please provide an update on any progress?

Thank you.

**Comment by afirstenberg** [comment]
> we've implemented a retry logic as a temporary workaround.

Just to be clear - even when this is fixed, you may need to implement retry logic. (Or handle this elsehow.)

All the cases I've seen of this are when Gemini is triggering a SAFETY issue. So even when this is fixed - a `GoogleAISafetyError` will be thrown by default.

If you just want it to return a message such as "I'm sorry, but I can't talk about that." when a SAFETY issue is triggered, then you can use the `MessageGeminiSafetyHandler` when creating your model. This creates a synthetic part and works around the issue. You can do this with something like this (but I haven't tested this specific code):

```
  const safetyHandler = new MessageGeminiSafetyHander({
    msg: "I'm sorry, but I can't talk about that.",
  });
  const model = new ChatGoogle({
    safetyHandler,
  });
```

**Comment by afirstenberg** [comment]
> Could you please provide an update on any progress?

As for this part - @jacoblee93, can we get the conditional test that @pksharmapokhrel outlined in place at https://github.com/langchain-ai/langchainjs/blame/96bba4bafeb67e79cbf266ed40ca93bec96d166c/libs/langchain-google-common/src/utils/gemini.ts#L598 ?
