### ISSUE TITLE
ChatOllama doesn't return content when calling tools.

### ISSUE THREAD

**Issue by ATypescriptEnjoyer** [langchain-ai/langchainjs#6375]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```typescript
import { tool } from "@langchain/core/tools";
import { ChatOllama } from "@langchain/ollama";
import { z } from "zod";

const weatherTool = tool((_) => "Da weather is weatherin", {
  name: "get_current_weather",
  description: "Get the current weather in a given location",
  schema: z.object({
    location: z.string().describe("The city and state, e.g. San Francisco, CA"),
  }),
});

// Define the model
const llmForTool = new ChatOllama({
  model: "llama3-groq-tool-use",
});

// Bind the tool to the model
const llmWithTools = llmForTool.bindTools([weatherTool]);

const resultFromTool = await llmWithTools.invoke(
  "What's the weather like today in San Francisco? Ensure you use the 'get_current_weather' tool."
);

console.log(resultFromTool);
```

### Error Message and Stack Trace (if applicable)

No error messages

### Description

In the langchain docs for ollama + tools, it even shows that no content is returned when tools are in use. I thought this was just an inconsistency in the docs so I tried to implement tools locally, and whenever tools are called no data gets returned. I am using ollama 0.3.3 with the recommended model for tooling, but  i've also tried llama3.1 with the same result.

### System Info

Linux Fedora
Node 20/Bun 1.1.21 (Tried both)
1.22.22

Ollama version 0.3.3
@langchain/ollama 0.0.2

**Comment by jacoblee93** [comment]
Hey @ATypescriptEnjoyer! Could you log what you see as a result?

CC @bracesproul

**Comment by bracesproul** [comment]
Hey @ATypescriptEnjoyer I just tried locally & logged the exact output from Ollama before any LangChain processing, and the only message data it returned was:
```
{
  role: 'assistant',
  content: '',
  tool_calls: [
    {
      function: {
        name: 'get_current_weather',
        arguments: { location: 'San Francisco, CA' }
      }
    }
  ]
}
```

**Comment by ATypescriptEnjoyer** [comment]
@jacoblee93 Hi, I see exactly what the result in the guide shows:

```
AIMessage {
  "content": "",
  "additional_kwargs": {},
  "response_metadata": {
    "model": "llama3-groq-tool-use",
    "created_at": "2024-08-01T18:43:13.2181Z",
    "done_reason": "stop",
    "done": true,
    "total_duration": 2311023875,
    "load_duration": 1560670292,
    "prompt_eval_count": 177,
    "prompt_eval_duration": 263603000,
    "eval_count": 30,
    "eval_duration": 485582000
  },
  "tool_calls": [
    {
      "name": "get_current_weather",
      "args": {
        "location": "San Francisco, CA"
      },
      "id": "c7a9d590-99ad-42af-9996-41b90efcf827",
      "type": "tool_call"
    }
  ],
  "invalid_tool_calls": [],
  "usage_metadata": {
    "input_tokens": 177,
    "output_tokens": 30,
    "total_tokens": 207
  }
}
```

Is this expected and am I misunderstanding what the `content` should be? I would expect the content to use the value that it's returned from the tool call, but maybe i'm mistaken?

**Comment by ATypescriptEnjoyer** [comment]
@bracesproul Is it expected that it wouldn't use the value returned from the tools function call? Maybe i'm misunderstanding how the tooling is used to help ollama generate accurate results

**Comment by jacoblee93** [comment]
Ah, yes you are mistaken. The canonical value is in `tool_calls` - it's a separate field.

But @bracesproul what's the actual response from Ollama look like?

**Comment by ATypescriptEnjoyer** [comment]
So if I provide the example tool, and the tool gets used in the tool chain (getting the weather) where can I expect the response?

**Comment by jacoblee93** [comment]
`tool_calls`:

https://js.langchain.com/v0.2/docs/how_to/tool_calling/
