### ISSUE TITLE
BadRequestError: 400 Invalid value for 'content': expected a string, got null when i use retrieverTool

### ISSUE THREAD

**Issue by KedAyAyA** [langchain-ai/langchainjs#6377]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

import { TavilySearchResults } from "@langchain/community/tools/tavily_search";
import * as dotenv from 'dotenv';

import { RecursiveCharacterTextSplitter } from "langchain/text_splitter";
import { CheerioWebBaseLoader } from "@langchain/community/document_loaders/web/cheerio";
import { MemoryVectorStore } from "langchain/vectorstores/memory";
import { ChatOpenAI, OpenAIEmbeddings } from "@langchain/openai";
import { ChatPromptTemplate } from "@langchain/core/prompts";
import { createOpenAIFunctionsAgent, AgentExecutor } from 'langchain/agents';
import { createRetrieverTool } from "langchain/tools/retriever";
import { pull } from "langchain/hub";

dotenv.config();

// const searchTool = new TavilySearchResults();
const model = new ChatOpenAI({
    model: "gpt-4o-mini",
    temperature: 0
});

// const toolResult = await searchTool.invoke("what is the weather in SF?");

// console.log(toolResult);

const loader = new CheerioWebBaseLoader(
    "https://docs.smith.langchain.com/user_guide"
);
const rawDocs = await loader.load();

const splitter = new RecursiveCharacterTextSplitter({
    chunkSize: 1000,
    chunkOverlap: 200,
});
const docs = await splitter.splitDocuments(rawDocs);

const vectorstore = await MemoryVectorStore.fromDocuments(
    docs,
    new OpenAIEmbeddings()
);
const retriever = vectorstore.asRetriever();

const retrieverResult = await retriever.invoke("how to upload a dataset");
const retrieverTool = createRetrieverTool(retriever, {
    name: "langsmith_search",
    description:
      "Search for information about LangSmith. For any questions about LangSmith, you must use this tool!",
});
console.log(retrieverResult[0]);

const tools = [retrieverTool];

const prompt = await pull(
    "hwchase17/openai-functions-agent"
);

// const prompt = ChatPromptTemplate.fromMessages([
//     ['system', 'You are a helpful assistant'],
//     ['placeholder', '{chat_history}'],
//     ['human', '{input}'],
//     ['placeholder', '{agent_scratchpad}']
// ]);

const agent = await createOpenAIFunctionsAgent({
    llm: model,
    tools,
    prompt,
});

const agentExecutor = new AgentExecutor({
    agent,
    tools,
});

// const result1 = await agentExecutor.invoke({
//     input: "hi!",
// });
  
// console.log(result1);

const result2 = await agentExecutor.invoke({
    input: "how can langsmith help with testing?",
});

console.log(result2);

### Error Message and Stack Trace (if applicable)

BadRequestError: 400 Invalid value for 'content': expected a string, got null. (request id: 202408051300533003481493n4ownvM)
    at APIError.generate (file:///Users/kedaya/Documents/demo/langchain-demo/node_modules/.pnpm/openai@4.54.0/node_modules/openai/error.mjs:41:20)
    at OpenAI.makeStatusError (file:///Users/kedaya/Documents/demo/langchain-demo/node_modules/.pnpm/openai@4.54.0/node_modules/openai/core.mjs:268:25)
    at OpenAI.makeRequest (file:///Users/kedaya/Documents/demo/langchain-demo/node_modules/.pnpm/openai@4.54.0/node_modules/openai/core.mjs:311:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///Users/kedaya/Documents/demo/langchain-demo/node_modules/.pnpm/@langchain+openai@0.2.5_langchain@0.2.12/node_modules/@langchain/openai/dist/chat_models.js:840:29
    at async RetryOperation._fn (/Users/kedaya/Documents/demo/langchain-demo/node_modules/.pnpm/p-retry@4.6.2/node_modules/p-retry/index.js:50:12) {
  status: 400,
  headers: {
    'content-length': '201',
    'content-type': 'application/json; charset=utf-8',
    date: 'Mon, 05 Aug 2024 13:00:53 GMT',
    'req-arrive-time': '1722862853299',
    'req-cost-time': '398',
    'resp-start-time': '1722862853698',
    server: 'istio-envoy',
    'x-envoy-upstream-service-time': '398',
    'x-oneapi-request-id': '202408051300533003481493n4ownvM'
  },
  request_id: undefined,
  error: {
    message: "Invalid value for 'content': expected a string, got null. (request id: 202408051300533003481493n4ownvM)",
    type: 'invalid_request_error',
    param: 'messages.[2].content',
    code: null
  },
  code: null,
  param: 'messages.[2].content',
  type: 'invalid_request_error',
  attemptNumber: 1,
  retriesLeft: 6
}

### Description

I try this code from your tutorials. In this case https://js.langchain.com/v0.2/docs/tutorials/agents，and the code get request error  BadRequestError: 400 Invalid value for 'content': expected a string, got null.

I debug and find in the second request to openai, the messages will show like this
<img width="1412" alt="image" src="https://github.com/user-attachments/assets/3e25e7a0-e04f-4712-92a2-d4779f946f54">

the assistant message is null.

I think it's a bug for add error message to messages array, I need help for solve this problem, thank you.

### System Info

"@langchain/community": "^0.2.23",
    "@langchain/core": "^0.2.20",
    "@langchain/openai": "^0.2.5",
    "langchain": "^0.2.12"

mac

node: v18.20.4
pnpm: 7.13.3

**Comment by jacoblee93** [comment]
Hey @KedAyAyA, sorry you're running into this - are you able to verify whether that your retriever is returning any documents?

As a quick fix, could you try creating the tool without using that helper method like this?

```ts
import { z } from "zod";
import { tool } from "@langchain/core/tools";

const retrieverInputSchema = z.object({
  query: z.string(),
});
const retrieverTool = tool(
  async (input): Promise<string> => {
    const result = await retriever.invoke(input.query);
    return JSON.stringify(result);
  },
  {
    name: "langsmith_search",
    description: "Search for information about LangSmith. For any questions about LangSmith, you must use this tool!",
    schema: retrieverInputSchema,
  }
);

await retrieverTool.invoke({ a: 1, b: 2 });
```

https://js.langchain.com/v0.2/docs/how_to/custom_tools

**Comment by KedAyAyA** [comment]
Thank you for your reply。
I think my retriever return some documents. You can see this langSmith trace for sure https://smith.langchain.com/public/f8bf55cf-5d94-4950-80b8-21651cabad2c/r/06199256-847b-4c7d-b07d-852e6bd1caae.

Maybe it's a chat history added bug?

**Comment by jacoblee93** [comment]
Oh hmm that's interesting - thanks for sharing the trace

OpenAI has technically deprecated function calling in favor of tool calling:

https://platform.openai.com/docs/api-reference/chat/create#chat-create-functions

Could you try switching to `createToolCallingAgent` as a drop-in replacement instead?

https://js.langchain.com/v0.2/docs/how_to/agent_executor#create-the-agent

We also have generally been recommending people use LangGraph for increased customizability:

https://langchain-ai.github.io/langgraphjs/

**Comment by KedAyAyA** [comment]
Thank you, it will helpful. 
And more, I think the tutorial https://js.langchain.com/v0.2/docs/tutorials/agents/ need update, i get this demo code from here and then get the bad case ~

**Comment by jacoblee93** [comment]
Oh dear - thanks for the heads up. Will update that tomorrow.
