### ISSUE TITLE
read ECONNRESET when trying to stream GPT response with a PTU deployment

### ISSUE THREAD

**Issue by sallahbaksh** [langchain-ai/langchainjs#6405]
### Checked other resources

- [x] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

import { AzureChatOpenAI } from "@langchain/openai";

const model = new AzureChatOpenAI({
    model: modelName,
    openAIApiKey: apiKey,
    openAIBasePath: endpoint,
    openAIApiVersion: apiVersion,
    deploymentName: deploymentName,
    azureOpenAIApiInstanceName: instanceName,
    streaming: true,
  });
  
const response = await model.invoke(messageText);

### Error Message and Stack Trace (if applicable)

    read ECONNRESET

### Description

I am getting an "read ECONNRESET" error while attempting to stream the GPT response within the PTU deployment environment. Some of the content sent to GPT includes png images that have been converted into a base64 string. It works correctly without any errors when I am using a non-PTU deployment environment. 

### System Info

Node version 20.12.2

**Comment by sallahbaksh** [comment]
Using the code given by dosubot, I am getting the below error.
Streaming error: Error: read ECONNRESET                                                                                                     
        at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
        at TLSWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
      errno: -4077,
      code: 'ECONNRESET',
      syscall: 'read'
    }

**Comment by jacoblee93** [comment]
Hey @sallahbaksh!

What is a PTU deployment? Does it work if you omit the `streaming: true` param?

**Comment by sallahbaksh** [comment]
Hi! A PTU lets you to specify the amount of throughput you require in a deployment. Here's more information on it - https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/provisioned-throughput

I tried omitting the streaming: true param but still get the same error.

**Comment by Stadly** [comment]
Were you able to find a solution, @sallahbaksh?

I'm not using PTU, but I (or rather my users) randomly get an `ECONNRESET` error once every few days. I've got no idea why. I have not been able to figure out a way to catch the error and resend the request. Any ideas?
