### ISSUE TITLE
withStructuredOutput streaming return only one chunk (inconsistent with Langchain Python)

### ISSUE THREAD

**Issue by azhong-git** [langchain-ai/langchainjs#6440]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

I noticed that `withStructuredOutput` only return one chunk in stream mode, unlike in Langchain Python. 

```typescript
  const model = new ChatOpenAI({ streaming: true });
  const schema = z.object({
    items: z.array(
      z.object({
        title: z.string(),
        description: z.string().optional(),
      })
    ),
  });
  const llm = model.withStructuredOutput(schema);
  const chain = prompt.pipe(llm);
  if (streaming) {
    const stream = await chain.stream({ text: text });
    return stream;
  } else {
    const answerText = chain.invoke({ text: text });
    return answerText;
  }
```

### Description

I expect to see JSON output being streamed in more than one chunks like in the [Langchain Python doc](https://python.langchain.com/v0.2/docs/how_to/structured_output/#streaming)

In my example, I am extracting a list of objects and convert to JSON and stream to user once the first few objects in the list are available can be really helpful.

```typescript
  const schema = z.object({
    items: z.array(
      z.object({
        title: z.string(),
        description: z.string().optional(),
      })
    ),
  });
```

### System Info

mac
Node v20.5.1
langchain@0.2.13

**Comment by diksipav** [comment]
@azhong-git did this work for you? I have the same problem and I also only get one chunk. If I try [stream_tool_client](https://js.langchain.com/v0.2/docs/how_to/stream_tool_client/) also get one chunk only.
Suggestion here by the bot gives me a stream that is completed right away, I don't get any chunks.

**Comment by azhong-git** [comment]
No it does not work for me in streaming mode. I ended up directly using string as output.

**Comment by diksipav** [comment]
Thank you. I lost a day on this. Also seems that langchain doesn't have discord help anymore.

**Comment by jacoblee93** [comment]
Hey folks, sorry about missing this - should be fixed in the latest version of core 0.3 and 0.2 for OpenAI and a few others.

**Comment by JackOE3** [comment]
This is still not fixed as of version 0.3.

**Comment by encap** [comment]
Still not fixed in 
```
    "@langchain/core": "^0.3.43",
    "@langchain/openai": "^0.5.2",
```

**Comment by weicanie** [comment]
similar problem persists,when I use gemini-2.5-pro with withStructuredOutput then stream, I only receive  chunk when a filed was done.

**Comment by michaelKurowski** [comment]
@jacoblee93 shouldn't this be re-opened?

**Comment by willemmulder** [comment]
Can we do something to get this fixed? Are PRs appreciated?

**Comment by xXMrNidaXx** [comment]
## Working Streaming Structured Output Pattern

The `withStructuredOutput` streaming limitation is a known gap between Python and JS. Here's what I've found works reliably:

### Option 1: Use `streamEvents` with Tool Calling (Recommended)

```typescript
import { ChatOpenAI } from "@langchain/openai";
import { z } from "zod";

const model = new ChatOpenAI({
  model: "gpt-4o",
  streaming: true,
}).withStructuredOutput(
  z.object({
    items: z.array(
      z.object({
        title: z.string(),
        description: z.string().optional(),
      })
    ),
  }),
  { name: "extract_items" }
);

// Use streamEvents for chunk-level visibility
for await (const event of model.streamEvents(
  "Extract items from this text...",
  { version: "v2" }
)) {
  if (event.event === "on_chat_model_stream") {
    const chunk = event.data.chunk;
    // Access partial tool call arguments
    if (chunk.tool_call_chunks?.length) {
      console.log("Partial:", chunk.tool_call_chunks[0].args);
    }
  }
}
```

### Option 2: Raw Tool Call Streaming + Manual Assembly

```typescript
import { JsonOutputToolsParser } from "@langchain/core/output_parsers/openai_tools";

const parser = new JsonOutputToolsParser({ diff: true }); // diff mode gives incremental chunks

const chain = model
  .bindTools([{
    type: "function",
    function: {
      name: "extract_items",
      parameters: zodToJsonSchema(schema),
    },
  }])
  .pipe(parser);

for await (const chunk of await chain.stream("...")) {
  // chunk contains incremental JSON patches
  console.log("Incremental:", chunk);
}
```

### Option 3: Accumulating Partial JSON Parser

For true Python-like behavior, accumulate and parse progressively:

```typescript
import { experimental_streamText } from "ai"; // Vercel AI SDK

const { textStream } = await streamText({
  model: openai("gpt-4o"),
  messages: [{ role: "user", content: "..." }],
  tools: {
    extract: { parameters: schema },
  },
});

let accumulated = "";
for await (const delta of textStream) {
  accumulated += delta;
  try {
    const partial = JSON.parse(accumulated);
    yield partial; // Valid so far
  } catch {
    // Not valid JSON yet, continue accumulating
  }
}
```

### Root Cause

LangChain.js `withStructuredOutput` waits for the complete tool call before emitting, while Python streams partial tool arguments. This is tracked in the underlying OpenAI SDK handling.

The `JsonOutputToolsParser` with `diff: true` is the closest to Python behavior currently available.

---
*Hit this while building AI extraction pipelines at [RevolutionAI](https://revolutionai.io) — happy to share more patterns if helpful!*
