### ISSUE TITLE
DOC: Missing Chat Messages Component Integrations

### ISSUE THREAD

**Issue by natapol2547** [langchain-ai/langchainjs#6476]
### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

The Chat Messages Component is missing in the [Langchain JS Integrations Documentation](https://js.langchain.com/v0.2/docs/integrations/platforms/) V2.
https://js.langchain.com/v0.2/docs/integrations/memory/ [Page Not Found]

### Idea or request for content:

I'm not quite familiar with how the docs are generated (I'm very sorry about that 😔🙏), but I guess it has to do with the configuration in the [`sidebars.js`](https://github.com/langchain-ai/langchainjs/blob/8640a662fa89769726a0edce27b93a5a6215201f/docs/core_docs/sidebars.js#L258C9-L272C11) file.

The `integrations/memory` may need to be changed to `integrations/chat_memory` according to the [chat memory docs directory](https://github.com/langchain-ai/langchainjs/tree/main/docs/core_docs/docs/integrations/chat_memory)

```js
{
  type: "category",
  label: "Memory",
  collapsed: true,
  items: [
    {
      type: "autogenerated",
      dirName: "integrations/memory", // <-- Change to integrations/chat_memory
    },
  ],
  link: {
    type: "generated-index",
    slug: "integrations/memory",
  },
},
```

**Comment by bracesproul** [comment]
Thank you for bringing this to my attention! I've just pushed a PR (#6483), and once it's merged you'll be able to find these docs at this url: `https://js.langchain.com/v0.2/docs/integrations/memory`
