### ISSUE TITLE
Unable to use the newly launched Structured Outputs feature of OpenAI, `response_format: { type: "json_schema", json_schema: {"strict": true, "schema": ...} }`

### ISSUE THREAD

**Issue by ianva** [langchain-ai/langchainjs#6477]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [x] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

``` typescript
 const TranslationSchema = z.object({
  translatedText: z.string(),
  entities: z.array(
    z.object({
      ner: z.string(),
      label: z.string(),
      translated: z.string().optional(),
    })
  ),
});
 ...
 
    return RunnableSequence.from([
      {
        sourceLanguage: () => formattingObject.sourceLanguage,
        targetLanguage: () => formattingObject.targetLanguage,
        genre: () => formattingObject.genre,
        textToTranslate: () => formattingObject.textToTranslate,
        untranslatedNerEntities: () => formattingObject.untranslatedNerEntities,
      },
      prompt,
      (promptValue: any) => {
        const boundModel = this.model.bind({
          response_format: zodResponseFormat(TranslationSchema, "translation"),
        });
        return boundModel.invoke(promptValue);
      },
    ]);

### Error Message and Stack Trace (if applicable)

_No response_

### Description

Unable to use the newly launched Structured Outputs feature of OpenAI, `response_format: { type: "json_schema", json_schema: {"strict": true, "schema": ...} }`

The type of response_format does not support json_schema, and the return value does not contain the JSON data defined by json_schema

### System Info

osx/bun

**Comment by ikalachy** [comment]
I bet the answer is not correct.  It should be smth like 
`.withStructuredOutput(TranslationSchema, {
  name: "translate",
});
`

And again with latest 3.1 update and tooling it seems to me functionality is broken somehow. I cant make model to generate appropriate content

**Comment by ianva** [comment]
Is the encapsulation of the ChatOpenAI class too complex, making it difficult to expand certain fields? 
Could there be some configurations that allow for merging when new fields are added?

**Comment by bracesproul** [comment]
Updating the `response_format` type to allow 
```typescript
{
  type: "json_schema",
  json_schema: { ... }
}
```
is simple, however OpenAI added a new beta endpoint for making requests with this new json schema response format, as well as some utils for converting Zod schemas to their expected JSON schema format. Due to this, it's not as simple as expending the type, and actual code logic changes are required to make it work as intended.

**Comment by ianva** [comment]
Thanks for your work,  looking forward to this update arriving soon

**Comment by david8z** [comment]
I am curious shouldn't `withStructureOuput` directly implement this whe calling OpenAI?

**Comment by bracesproul** [comment]
@david8z We can't make `withStructuredOutput` call with `json_schema` mode by default as that would technically be a breaking change (any change to default behavior = "breaking" change). I believe we are planning on making `withStructuredOutput` pass `strict: true` by default when we bump minor versions next.
