### ISSUE TITLE
Zod to JSONSchema conversion doesn't use openai custom logic for openai

### ISSUE THREAD

**Issue by airhorns** [langchain-ai/langchainjs#6479]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

OpenAI's new structured output support requires compiling zod to JSONSchema, which is something that LangChain already knows how to do. However -- OpenAI's code client uses a specialized, forked version of `zod-to-json-schema` internally to do this conversion in order to improve the compatibility of the generated JSON schemas with what is supported server side in their API. Specifically, they don't use relative references, which LangChain does, because they aren't supported server side. OpenAI's client also handles nullability differently.

You can see their custom converter here: https://github.com/openai/openai-node/blob/cc13af9fa7e76e774d3132bba2427bb0176bd622/src/helpers/zod.ts#L11-L19

and some commits that added the custom logic:  https://github.com/openai/openai-node/commit/fc22483173b521b0b194264e6d975c3517c06216 and https://github.com/openai/openai-node/commit/fc22483173b521b0b194264e6d975c3517c06216

As it stands now, LangChain's conversation of tool or structured output schemas doesn't use this fancy logic, and breaks in many more cases. If you re-use a chunk of schema within a bigger, outer schema, LangChain triggers an OpenAI 400 error, and the OpenAI client doesn't.

It'd be great if LangChain could be a client of OpenAI's `zodResponseFormat` or `zodFunction` helpers instead of doing its own conversion, or something like that.

### Description

I'm trying to use LangChain to a call a tool with the same inner bit of Zod schema repeated more than once, and it fails with OpenAI's new `strict: true` parameter when OpenAI's client doesn't.

### System Info

`@langchain/core 0.2.21`
`openai 4.55.3`
`node v22.2.0`
`pnpm v8.12.0`

**Comment by bracesproul** [comment]
Hey, we're implementing this in #6438

**Comment by airhorns** [comment]
Great! That looks like it addresses the response format for top-level structured output, but there's the same problem for function calling too for the function's input schema. Is that on y'alls radar as well?

**Comment by bracesproul** [comment]
Ah interested, I wasn't aware they made other changes to how they handle schemas for normal tool calling. This is now on my radar and I'll get it in soon (likely sometime next week). Thank you!

**Comment by airhorns** [comment]
Can we keep this open until tool calling supports the feature as well? For me at least that's the important one because it allows selection among multiple tools!

**Comment by airhorns** [comment]
ping @bracesproul sorry to bother but I do think there's a missing bit for proper support for strict OpenAI functions using their zod helpers for their special handling!

**Comment by bracesproul** [comment]
@airhorns what is the missing feature you're referring to?

**Comment by airhorns** [comment]
OpenAI uses a special zod-to-json-schema converter for both top-level model structured outputs as well as tool calling. AFAICT, Langchain now uses OpenAI's `zodResponseFormat` to do this conversion for top level `.withStructuredOutput` calls, but it doesn't use OpenAI's `zodFunction` for tool calls. That breaks for various tools in strict mode because langchain's internal zod-to-json-schema behaves differently and emits JSON schemas that aren't compatible with OpenAI.

**Comment by bracesproul** [comment]
@airhorns we are using OpenAIs `zodFunction` util to convert tools passed in if they contain a Zod schema. See the `_convertToOpenAITool` function which is called from the `_convertChatOpenAIToolTypeToOpenAITool` function.

Could you provide me with some code to reproduce the error you're referencing?

**Comment by airhorns** [comment]
Ah, sorry I missed that, I only saw the other PR! Never mind me then, thanks!
