### ISSUE TITLE
DOC: Redirect to api.js.langchain.com is wrong on Tools section

### ISSUE THREAD

**Issue by kevenleone** [langchain-ai/langchainjs#6504]
### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

The current doc: https://js.langchain.com/v0.2/docs/how_to/custom_tools/#tool-function

The link present on the text:

> The [tool](https://api.js.langchain.com/classes/langchain_core_tools.tool.html) wrapper function is a convenience method for turning a JavaScript function into a tool. It requires the function itself along with some additional arguments that define your tool. The most important are:

Is wrong

I was checking the doc and I found the following link: https://api.js.langchain.com/classes/langchain_core_tools.Tool.html instead of https://api.js.langchain.com/classes/langchain_core_tools.tool.html

### Idea or request for content:

The redirect link is wrong

**Comment by bracesproul** [comment]
Thank you for flagging this, will fix it asap!
