### ISSUE TITLE
stream_options should not be set by-default for ChatOpenAI request

### ISSUE THREAD

**Issue by yangcao77** [langchain-ai/langchainjs#6533]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code
```
      const openAIApi = new ChatOpenAI({
        apiKey:"sk-no-key-required",
        model: "instructlab/granite-7b-lab",
        stream: true,
        configuration: { 
          baseURL: <my custom server>
        }
        });
  
await openAIApi.invoke([
      new HumanMessage(
        "Translate this sentence from English to French: I love programming."
      ),
    ]))
```

### Error Message and Stack Trace (if applicable)

got 400 Bad Request (no body) error:
```
file:///Users/stephanie/Documents/RHDH/backstage/0627-backstage/backstage/plugins/test/node_modules/openai/error.mjs:41
            return new BadRequestError(status, error, message, headers);
                   ^

BadRequestError: 400 status code (no body)
    at APIError.generate (file:///Users/stephanie/Documents/RHDH/backstage/0627-backstage/backstage/plugins/test/node_modules/openai/error.mjs:41:20)
    at OpenAI.makeStatusError (file:///Users/stephanie/Documents/RHDH/backstage/0627-backstage/backstage/plugins/test/node_modules/openai/core.mjs:268:25)
    at OpenAI.makeRequest (file:///Users/stephanie/Documents/RHDH/backstage/0627-backstage/backstage/plugins/test/node_modules/openai/core.mjs:311:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///Users/stephanie/Documents/RHDH/backstage/0627-backstage/backstage/plugins/test/node_modules/@langchain/openai/dist/chat_models.js:877:29
    at async RetryOperation._fn (/Users/stephanie/Documents/RHDH/backstage/0627-backstage/backstage/node_modules/p-retry/index.js:50:12)
```

### Description

I'm using langchain/openai to create chatbot, and calling my own custom llm server using model: instructlab/granite-7b-lab which support openai API . 

after debugging, it's this line causing the issue: 
https://github.com/langchain-ai/langchainjs/blob/d1d91a0a860760bc6c802937c5716edc5a74b609/libs/langchain-openai/src/chat_models.ts#L1049-L1051

I modified the `chat_models`, and make the completions API call with the following openapi code, I ran with no issues:
```
                request = {
                    messages: [
                      {
                        role: 'system',
                        content:
                          'You are a helpful assistant that can answer question in Red Hat Developer Hub.',
                      },
                      { role: 'user', content: "Translate this sentence from English to French: I love programming." },
                    ],
                    model: 'instructlab/granite-7b-lab',
                    stream: true,
                  };
                const res = await this.client.chat.completions.create(
                    request,
                    requestOptions
                  );
                return res;
```

the only difference is the `stream_options` is set in langchain by default when `streaming: true`. but openai's API does not force setting the `stream_options`. 

langchain should do the same for `stream_options`, by-default set it to undefined. 

Not all custom server has token usage restriction and even understands that option, it will break the usage if it understands that option . 
I want to set `stream=true`, and there is no workaround !!!!!

### System Info

has nothing to do with my system configuration. see the above description

latest langchain has this issue.

**Comment by yangcao77** [comment]
@jacoblee93 @bracesproul  PTAL. I think it is a blocker bug, but easy to fix.

**Comment by jacoblee93** [comment]
Hey @yangcao77,

Will have a look - we can't remove the setting without a breaking change, but I can at least make it possible to unset it if it's not already possible.

**Comment by jacoblee93** [comment]
Oh ok, so you should be able to do this:

```js
    const openAIApi = new ChatOpenAI({
        apiKey:"sk-no-key-required",
        model: "instructlab/granite-7b-lab",
        stream: true,
        streamUsage: false,
        configuration: { 
          baseURL: <my custom server>
        }
      });
```

Aware this isn't a great fix - hopefully third-parties will be less strict in the future. Can also add docs.
