### ISSUE TITLE
Deprecated Ollama Embeddings Work (path "@langchain/community/embeddings/ollama") , but the "@langchain/ollama" import don't Work

### ISSUE THREAD

**Issue by Rafael-Julio-2242** [langchain-ai/langchainjs#6564]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

I was testing the embeddings for a future project that i need to create, and i have found out that the newer version of the class "OllamaEmbeddings" don't quite work.

The following code:

```typescript

import { OllamaEmbeddings } from "@langchain/ollama";

(async () => {


  const model = new OllamaEmbeddings({
   model: "nomic-embed-text",
   onFailedAttempt: (err: any) => {
    console.log("[Error]: ", err);
   }
  });

  const embededText = await model.embedQuery("test");

  console.log(embededText);

})();
```
This Returns an Not Found error, it tries to connect to the Ollama API but it says it don't find.

The error:

```
ResponseError: 404 page not found
    at checkOk (/Users/user/Documents/projetos/testProject/node_modules/ollama/dist/shared/ollama.384eb0a9.cjs:72:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async post (/Users/user/Documents/projetos/testProject/node_modules/ollama/dist/shared/ollama.384eb0a9.cjs:119:3)
    at async Ollama.embed (/Users/user/Documents/projetos/testProject/node_modules/ollama/dist/shared/ollama.384eb0a9.cjs:392:22)
    at async RetryOperation._fn (/Users/user/Documents/projetos/testProject/node_modules/p-retry/index.js:50:12) {
  error: '404 page not found',
  status_code: 404,
  attemptNumber: 7,
  retriesLeft: 0
}
```

But when i use axios or the older version, everthing works just fine.

Same code, but using the older version (the code that works Ok):

```typescript

import { OllamaEmbeddings } from "@langchain/community/embeddings/ollama";

(async () => {


  const model = new OllamaEmbeddings({
   model: "nomic-embed-text",
   onFailedAttempt: (err: any) => {
    console.log("[Error]: ", err);
   }
  });

  const embededText = await model.embedQuery("test");

  console.log(embededText);

})();
```

The test that i have made with "axios" works, and it ends up being a simple test:

```typescript
import axios from "axios";
import { OllamaEmbeddings } from "@langchain/ollama";

(async () => {


  const res = await axios.post('http://localhost:11434/api/embeddings', {
   "model": "nomic-embed-text",
   "prompt": "testing"
  }, {
   validateStatus: () => true // Don't want axios to throw errors
  });

  if (res.status !== 200 && res.status !== 201) {

   console.log('[ERROR]: ', res.data);
   return;
  }

  console.log(res.data);

})();
```

### Description

It says in the docs and in the code that the version of "@langchain/community/embeddings/ollama" is deprecated, but that version is working and the other version is not actually working. 

### System Info

node version v22.6.0
npm version 10.8.2
Mac

Package.json file:

```json
{
  "name": "test",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "dev": "ts-node src/index.ts"
  },
  "devDependencies": {
    "typescript": "^5.5.4"
  },
  "dependencies": {
    "@langchain/community": "^0.2.28",
    "@langchain/core": "^0.2.27",
    "@langchain/ollama": "^0.0.4",
    "@langchain/openai": "^0.2.7",
    "@types/node": "^22.4.0",
    "axios": "^1.7.4",
    "cheerio": "^1.0.0",
    "langchain": "^0.2.16"
  }
}
```

**Comment by jacoblee93** [comment]
Apologies for missing this, this should now be present!

**Comment by chaostracker** [comment]
I still have this exact same issue with 0.1.0.

**Comment by bracesproul** [comment]
@chaostracker what version of `ollama` do you have installed? You can check via:

```bash
ollama -v
```

I have version `0.3.11` installed, and it's working properly.

**Comment by chaostracker** [comment]
It was ollama version 0.2.1.
I upgraded to 0.3.11 and now it works as expected, so thanks.
