### ISSUE TITLE
Token usage is not available when using `stream` or `streamEvents`

### ISSUE THREAD

**Issue by Stadly** [langchain-ai/langchainjs#6583]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```ts
const prompt = HumanMessagePromptTemplate.fromTemplate(
  'Just respond with "test".',
);
const streamingChain = RunnableSequence.from([
  prompt,
  new ChatOpenAI({
    modelName: "gpt-4",
    streaming: true,
  }),
]);
const nonStreamingChain = RunnableSequence.from([
  prompt,
  new ChatOpenAI({
    modelName: "gpt-4",
    streaming: false,
  }),
]);
{
  const response = await nonStreamingChain.invoke({});
  // Token usage is reported when using invoke and non-streaming.
  console.log(
    response.usage_metadata, // { input_tokens: 13, output_tokens: 1, total_tokens: 14 }
    response.response_metadata, // { tokenUsage: { completionTokens: 1, promptTokens: 13, totalTokens: 14 } }
  );
}
{
  const response = await streamingChain.invoke({});
  // Token usage is estimated when using invoke and streaming.
  console.log(
    response.usage_metadata, // undefined
    response.response_metadata, // { prompt: 0, completion: 0, estimatedTokenUsage: { promptTokens: 13, completionTokens: 1, totalTokens: 14 } }
  );
}
{
  const stream = await nonStreamingChain.stream({});
  // No token usage when using stream, regardles of streaming/non-streaming.
  for await (const chunk of stream) {
    console.log(
      chunk.usage_metadata, // undefined
      chunk.response_metadata // { prompt: 0, completion: 0 }
    );
  }
}
{
  const eventStream = nonStreamingChain.streamEvents({}, { version: "v2" });
  // No token usage when using eventStream, regardles of streaming/non-streaming.
  for await (const event of eventStream) {
    if (event.data.output)
      console.log(
        event.data.output.usage_metadata, // undefined
        event.data.output.response_metadata, // { prompt: 0, completion: 0 }
      );
    if (event.data.chunk)
      console.log(
        event.data.chunk.usage_metadata, // undefined
        event.data.chunk.response_metadata, // { prompt: 0, completion: 0 }
      );
  }
}
```

### Description

I'm trying to get the token usage when using `streamEvents`. I understand that token usage is not reported when streaming with OpenAI. Langchain therefore [estimates the token usage](https://github.com/langchain-ai/langchainjs/pull/2891) when calling `invoke` on a streaming model.

I would expect the same estimation to be done when calling `stream` or `streamEvents`, making the estimated token usage available in the result.

Related issues: https://github.com/langchain-ai/langchainjs/issues/2623 and https://github.com/langchain-ai/langchainjs/issues/6106

### System Info

```
@langchain/core@0.2.27
@langchain/openai@0.2.7
Platform: linux
Node.js v20.16.0
NPM v10.8.1
```

**Comment by wlyh514** [comment]
Hi, again sorry for the long wait. 

I understand you want to extract token usage when invoking `ChatOpenAI` with `.stream` or `.eventStream`, this could mean two things:
a) You want to know the total token usage of an invocation right after the stream ends, or
b) You want to know the token usage of each chunk/event in real time as they are being generated. 

If a) suffices in your use case, OpenAI now supports [streaming token usage report](https://platform.openai.com/docs/api-reference/chat/streaming#chat/streaming-usage). When `include_usage` is set to true, openai will send an extra chunk of usage info after all contents have been streamed. 

In langchain, you can set this flag either in the llm constructor or at invocation. 

```typescript
 const llm = new ChatOpenAI({
      modelName: "gpt-4",
      streaming: true,
      streamUsage: true,
    });
// or
const stream = await streamingChain.stream({
      stream_options: {
         include_usage: true, 
       }
    });
```
You can then expect the usage information to be in the last chunk/event of the chain
```typescript
for await (const chunk of stream) {
    if (chunk.usage_metadata) {
        console.log(chunk.usage_metadata);
    }
}
// or
for await (const event of eventStream) {
    if (event.data.output && event.data.output.usage_metadata) {
        console.log(event.data.output.usage_metadata);
    }
}

// {
//     input_tokens: 20,
//     output_tokens: 9,
//     total_tokens: 29,
//     input_token_details: { audio: undefined, cache_read: 0 },
//     output_token_details: { audio: undefined, reasoning: 0 }
// }
```

If b) is what you are expecting, then that is indeed not implemented yet and I will create a PR for that. 

Please lmk your thoughts :)

**Comment by Stadly** [comment]
I was looking for a), so then your instructions covers it. Thanks! 😊
