### ISSUE TITLE
`lc_secrets` is missing from `ChatMistralAI`, potentially leaking API keys

### ISSUE THREAD

**Issue by jeanpaul** [langchain-ai/langchainjs#6627]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```javascript
const llm = new ChatMistralAI({apiKey: "foobar"});
console.log(llm);
```

### Description

When printing an instance of `ChatMistralAI`, the API key is included in plaintext in the output. Other LLMs seem to hide the credentials using `lc_secrets`, and it appears this is missing.

- The API key is included in the output
- Expected, similar to other model implementations, to see something like `MISTRAL_API_KEY`

Output from the example code:

```
ChatMistralAI {
...
  apiKey: 'foobar',
...
}
```

### System Info

```
$ pnpm info langchain

langchain@0.2.17 | MIT | deps: 14 | versions: 289
Typescript bindings for langchain
https://github.com/langchain-ai/langchainjs/tree/main/langchain/

keywords: llm, ai, gpt3, chain, prompt, prompt engineering, chatgpt, machine learning, ml, openai, embeddings, vectorstores

dist
.tarball: https://registry.npmjs.org/langchain/-/langchain-0.2.17.tgz
.shasum: c408d5f70e817f335511f79ad53db2addfadb278
.integrity: sha512-wFn7wo+XGzqYrv3KJLmMZ1M6BHx12C3YUSASOa03rcDsBzRL5onxhKAC/g4xAIqlAHrJYgU6Jb/T/S6uJ6UdkQ==
.unpackedSize: 5.4 MB

dependencies:
@langchain/core: >=0.2.21 <0.3.0  @langchain/textsplitters: ~0.0.0  js-tiktoken: ^1.0.12              jsonpointer: ^5.0.1               openapi-types: ^12.1.3            uuid: ^10.0.0                     zod-to-json-schema: ^3.22.3
@langchain/openai: >=0.1.0 <0.3.0 binary-extensions: ^2.2.0         js-yaml: ^4.1.0                   langsmith: ~0.1.40                p-retry: 4                        yaml: ^2.2.1                      zod: ^3.22.4

maintainers:
- nfcampos <nuno@boringbits.io>
- jacoblee93 <jacoblee93@gmail.com>
- andrewnguonly <andrewnguonly@gmail.com>
- davidduong <david@duong.cz>
- hwchase17 <hw.chase.17@gmail.com>
- basproul <braceasproul@gmail.com>

dist-tags:
latest: 0.2.17    next: 0.2.3-rc.0

published 3 days ago by basproul <braceasproul@gmail.com>

$ node --version
v22.6.0

$ pnpm --version
9.6.0
```

Platform: mac

**Comment by bracesproul** [comment]
Pushed a fix [here](https://github.com/langchain-ai/langchainjs/pull/6630). Thanks for flagging this!

**Comment by bracesproul** [comment]
@jeanpaul fix released [here](https://github.com/langchain-ai/langchainjs/pull/6632)

**Comment by jeanpaul** [comment]
Thank you for your quick fix!

Full disclosure, this was raised here: https://community.n8n.io/t/mistral-api-keys-being-leaked-with-langchain-code-node/44609
