### ISSUE TITLE
Gmail functionality is not working

### ISSUE THREAD

**Issue by kknono** [langchain-ai/langchainjs#6653]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code
``` typescript
 const model = new OpenAI({
        temperature: 0,
        apiKey: '',
    });

 const gmailParams = {
        credentials: {
            clientEmail: 'xxx@gmail.com',
            privateKey: 'AIzaSyAbMZXxzNNWdfLpT-xxxxxx',



        },
        scopes: ["https://gmail.googleapis.com"],
    };

 const tools: StructuredTool[] = [
        // new GmailCreateDraft(gmailParams),
        new GmailGetMessage(gmailParams),
        new GmailGetThread(gmailParams),
        new GmailSearch(gmailParams),
        // new GmailSendMessage(gmailParams),
    ];

 const searchInput = `Query my last email`;
    const searchResult = await gmailAgent.invoke({ input: searchInput });

    const messageId = searchResult?.output?.[0]?.id;

    if (!messageId) {
        console.error("error");
        return;
    }

```

logs:
  "tool": "gmail_get_thread",
  "toolInput": {
    "threadId": "unique_thread_id_string"
  },
  "log": " We can now use the gmail_get_thread tool to retrieve the thread ID of the first unread email message.\n\nAction:\n```json\n{\n  \"action\": \"gmail_get_thread\",\n  \"action_input\": {\n    \"threadId\": \"unique_thread_id_string\"\n  }\n}\n```\n\n\n\n\n\n"
}
[tool/start] [1:chain:AgentExecutor > 46:tool:GmailGetThread] Entering Tool run with input: "{"threadId":"unique_thread_id_string"}"

[chain/end] [1:chain:AgentExecutor] [36.68s] Exiting Chain run with output: {
  "output": "Agent stopped due to max iterations."
}

### Error Message and Stack Trace (if applicable)

[tool/error] [1:chain:AgentExecutor > 46:tool:GmailGetThread] [2ms] Tool run errored with error: "error:1E08010C:DECODER routines::unsupported\n\nError: error:1E08010C:DECODER routines::unsupported\n    at Sign.sign (node:internal/crypto/sig:128:29)\n    at Object.sign (xxxxx/node_modules/.pnpm/jwa@2.0.0/node_modules/jwa/index.js:152:45)\n    at Object.jwsSign [as sign] (xxxxxnode_modules/.pnpm/jws@4.0.0/node_modules/jws/lib/sign-stream.js:32:24)\n    at GoogleToken._GoogleToken_requestToken (xxxx/node_modules/.pnpm/gtoken@7.1.0/node_modules/gtoken/build/src/index.js:235:27)\n    at GoogleToken._GoogleToken_getTokenAsyncInner (xxxx/node_modules/.pnpm/gtoken@7.1.0/node_modules/gtoken/build/src/index.js:180:97)\n    at GoogleToken._GoogleToken_getTokenAsync (xxxx/node_modules/.pnpm/gtoken@7.1.0/node_modules/gtoken/build/src/index.js:160:173)\n    at GoogleToken.getToken (xxxx/node_modules/.pnpm/gtoken@7.1.0/node_modules/gtoken/build/src/index.js:110:102)\n    at JWT.refreshTokenNoCache (xxxnode_modules/.pnpm/google-auth-library@9.14.0/node_modules/google-auth-library/build/src/auth/jwtclient.js:173:36)\n    at JWT.refreshToken (xxx/node_modules/.pnpm/google-auth-library@9.14.0/node_modules/google-auth-library/build/src/auth/oauth2client.js:187:24)\n    at JWT.getRequestMetadataAsync (xxx/node_modules/.pnpm/google-auth-library@9.14.0/node_modules/google-auth-library/build/src/auth/oauth2client.js:333:28)\n    at JWT.getRequestMetadataAsync (xxxx/node_modules/.pnpm/google-auth-library@9.14.0/node_modules/google-auth-library/build/src/auth/jwtclient.js:95:26)\n    at JWT.requestAsync (xxxx/node_modules/.pnpm/google-auth-library@9.14.0/node_modules/google-auth-library/build/src/auth/oauth2client.js:418:34)\n    at JWT.request (xxxxx/node_modules/.pnpm/google-auth-library@9.14.0/node_modules/google-auth-library/build/src/auth/oauth2client.js:412:25)\n    at createAPIRequestAsync (xxxx/node_modules/.pnpm/googleapis-common@7.2.0/node_modules/googleapis-common/build/src/apirequest.js:303:31)\n    at createAPIRequest (/xxx/node_modules/.pnpm/googleapis-common@7.2.0/node_modules/googleapis-common/build/src/apirequest.js:52:16)\n    at Resource$Users$Threads.get (xxxx/node_modules/.pnpm/googleapis@143.0.0/node_modules/googleapis/build/src/apis/gmail/v1.js:2574:65)"

### Description

 
I followed the instructions on the [LangChain Gmail integration documentation](https://js.langchain.com/v0.2/docs/integrations/tools/gmail/) and set up the API key in the Gmail backend. However, I am unable to use the Gmail functionality, and I am encountering an error。

please help more

### System Info

 "@langchain/community": "^0.2.31",
    "@langchain/core": "^0.2.30",
    "@langchain/openai": "^0.2.8",
"googleapis": "^143.0.0",

platform: mac
node：20.x

**Comment by kknono** [comment]
@dosu

Where can I obtain the privateKey: \-----BEGIN PRIVATE KEY----- YOUR_PRIVATE_KEY_HERE -----END PRIVATE KEY-----`?

**Comment by kknono** [comment]
I encountered an issue when using the Gmail API with LangchainJS. The following code works correctly outside of LangchainJS:
``` typescript
 const jwtClient = new google.auth.JWT({
        email: credentials.client_email,
        key: credentials.private_key,
        scopes: ['https://www.googleapis.com/auth/gmail.readonly', 'https://www.googleapis.com/auth/cloud-platform'],  
 
        subject: 'xxxx@xxx.com'  

    });
  
    const gmail = google.gmail({ version: 'v1', auth: jwtClient });

```

This code allows me to log in and query Gmail successfully. However, when I try to run similar code within LangchainJS, I encounter the following error:

``` typescript
 const model = new OpenAI({
        temperature: 0,
        apiKey: '',
    });

 const gmailParams = {
        credentials: {
            clientEmail: 'xxx@gmail.com',
            privateKey: 'AIzaSyAbMZXxzNNWdfLpT-xxxxxx',



        },
        scopes: ["https://gmail.googleapis.com"],
    };

 const tools: StructuredTool[] = [
        // new GmailCreateDraft(gmailParams),
        new GmailGetMessage(gmailParams),
        new GmailGetThread(gmailParams),
        new GmailSearch(gmailParams),
        // new GmailSendMessage(gmailParams),
    ];

 const searchInput = `Query my last email`;
    const searchResult = await gmailAgent.invoke({ input: searchInput });

    const messageId = searchResult?.output?.[0]?.id;

    if (!messageId) {
        console.error("error");
        return;
    }
```

[tool/error] [1:chain:AgentExecutor > 7:tool:GmailGetMessage] [512ms] Tool run errored with error: "Invalid id value\n\nError: Invalid id value\n    at Gaxios._request (/xxx/node_modules/.pnpm/gaxios@6.7.1/node_modules/gaxios/src/gaxios.ts:146:15)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async JWT.requestAsync (/xxx/node_modules/.pnpm/google-auth-library@9.14.0/node_modules/google-auth-library/build/src/auth/oauth2client.js:429:18)\n    at async GmailGetMessage._call (/xxxxx/node_modules/.pnpm/@langchain+community@0.2.31_@spider-cloud+spider-client@0.0.68_@zilliz+milvus2-sdk-node@2.4.6_opiqvsst5hqml352zh6enpkpxe/node_modules/@langchain/community/dist/tools/gmail/get_message.cjs:33:25)\n    at async GmailGetMessage.call (/xxxx/node_modules/.pnpm/@langchain+core@0.2.30_langchain@0.2.17/node_modules/@langchain/core/dist/tools/index.cjs:111:22)\n    at async /xxxxx/node_modules/.pnpm/langchain@0.2.17_@langchain+community@0.2.31_assemblyai@4.7.0_axios@1.7.5_cheerio@1.0.0_d3-ds_4c7epgug2kknocuqq7fr2pruqy/node_modules/langchain/dist/agents/executor.cjs:479:27\n    at async Promise.all (index 0)\n    at async AgentExecutor._call (/xxxx/node_modules/.pnpm/langchain@0.2.17_@langchain+community@0.2.31_assemblyai@4.7.0_axios@1.7.5_cheerio@1.0.0_d3-ds_4c7epgug2kknocuqq7fr2pruqy/node_modules/langchain/dist/agents/executor.cjs:471:30)\n    at async AgentExecutor.invoke (/xxxx/node_modules/.pnpm/langchain@0.2.17_@langchain+community@0.2.31_assemblyai@4.7.0_axios@1.7.5_cheerio@1.0.0_d3-ds_4c7epgug2kknocuqq7fr2pruqy/node_modules/langchain/dist/chains/base.cjs:58:28)\n     


@dosu

**Comment by kknono** [comment]
The privateKey is correct, and when I call new google.auth.JWT independently, it works perfectly.

**Comment by kknono** [comment]
Is there someone available to help?

**Comment by jasonnathan** [comment]
What model are you using. It feels like the model isn't following your instructions properly. Try with a better model or use OpenAI to see if your integration works. I don't think your problem is with the Gmail tool. 

Another think you can try to do is to paste the error stack in ChatGPT and ask it to explain to you what the problem is.
