### ISSUE TITLE
OpenAI types outdated

### ISSUE THREAD

**Issue by tomfrenken** [langchain-ai/langchainjs#6663]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```ts
import { OpenAI } from '@langchain/openai';
```

### Description

The types you are currently providing seem not to align with the OpenAI API spec.
It seems that far more parameters are required than the API spec would suggest.
Feel free to take a look at the latest API and [your current types](https://github.com/langchain-ai/langchainjs/blob/main/libs/langchain-openai/src/types.ts).

### System Info

Irrelevant

**Comment by bracesproul** [comment]
It's possible to instantiate `ChatOpenAI` without passing any parameters. What exactly is the issue you have here? And if you could provide code examples that would be great.

**Comment by tomfrenken** [comment]
Hi @bracesproul the issue arizes when you try to extend the default implementation, in our case we have a client which uses the types aligned with the latest openai API spec, when we now try combine the two, the types are clashing.

Every property that is not model or prompt shouldn't be required according to the API you reference [here](https://platform.openai.com/docs/api-reference/completions/create ).

Two examples of this are [here](https://github.com/langchain-ai/langchainjs/blob/main/libs/langchain-openai/src/types.ts#L36) and [here](https://github.com/langchain-ai/langchainjs/blob/main/libs/langchain-openai/src/types.ts#L27C3-L27C7).

**Comment by bracesproul** [comment]
I'm still not sure I understand, can you provide code which you've implemented that has this issue? If I extend the class like this:

```typescript
import { ChatOpenAI, ChatOpenAIFields } from "@langchain/openai";

interface ChatOpenAIFieldsExtended extends ChatOpenAIFields {
  // Add custom fields here
}

class OpenAIExtended extends ChatOpenAI {
  constructor(fields: ChatOpenAIFieldsExtended) {
    super(fields);
  }
}
```

I still do not need to provide extra fields, and can invoke the model simply by passing a list of messages to `.invoke`

If what you're saying is internals API in `ChatOpenAI` require additional fields, then I agree with this statement. However, we can't change this only so it matches the OpenAI spec.

**Comment by tomfrenken** [comment]
I see how this can be confusing.
The issue arises not when you do add custom fields but rather have clashing types, e.g., both interfaces contain the same field but with a different type.

This would cause issues:
```ts
import { ChatOpenAI, ChatOpenAIFields } from "@langchain/openai";

interface ChatOpenAIFieldsExtended extends ChatOpenAIFields {
  n: string | undefined // <---- ChatOpenAIFields declared this as string already, which is not matching the actual OpenAI API
}

class OpenAIExtended extends ChatOpenAI {
  constructor(fields: ChatOpenAIFieldsExtended) {
    super(fields);
  }
}
```

**Comment by bracesproul** [comment]
Ah, this is because the actual implementation wraps the `ChatOpenAIFields` in a partial tag, hence why all those fields are required. Try doing this instead:

```typescript
interface ChatOpenAIFieldsUpdated extends Partial<ChatOpenAIFields> {
  n: number | undefined
}
```

**Comment by tomfrenken** [comment]
Ah, I see that makes sense.
How do you ensure you pass all the necessary fields when you declare the entire interface as Partial though?
I would always be afraid to break the super class

**Comment by bracesproul** [comment]
We have internal methods `invocationParams` which are always called before hitting the model provider API which put together the full object with all options to send through. Also, these classes aren't optimized to be subclassed, so there are most certainly are areas which could be improved for this.

I'm going to close this issue now, please tag me if there's anything else you need!
