### ISSUE TITLE
ParsedChatCompletion not found in 'openai/resources/beta/chat/completions.mjs'

### ISSUE THREAD

**Issue by gognjanovski** [langchain-ai/langchainjs#6670]
### Example Code

I get the following error ```node_modules/@langchain/openai/dist/chat_models.d.ts:9:38 - error TS7016: Could not find a declaration file for module 'openai/resources/beta/chat/completions.mjs'.```
for ```import { ParsedChatCompletion } from "openai/resources/beta/chat/completions.mjs";```

### Description

I'm trying to build my nodejs project that includes the langchain package

### System Info

Using:
node v20.13.1
npm 10.5.2
"langchain": "^0.2.17"
"openai": "4.57.0"

**Comment by jacoblee93** [comment]
Hey, sorry for the delay here!

I see where this is happening - it seems OpenAI removed the import in a patch/minor version. Will update.

**Comment by jacoblee93** [comment]
Live in `@langchain/openai@0.2.10`!
