### ISSUE TITLE
Expose error infos from chatgpt response

### ISSUE THREAD

**Issue by arronKler** [langchain-ai/langchainjs#670]
in `axios-fetch-adapter.js` file, we compared content-type in stageOne with EventStreamContentType. Throw error when it is  undesired.
There are many situations can make the error happen. Most of all, openai api returned some error informations which will response with `application/json` type. I think we should output what openai says in the response as a detailed information.

```javascript
async function getResponse(request, config) {
    let stageOne;
    try {
        stageOne = await fetch(request);
    }
    catch (e) {
        return createError("Network Error", config, "ERR_NETWORK", request);
    }
    const response = {
        ok: stageOne.ok,
        status: stageOne.status,
        statusText: stageOne.statusText,
        headers: new Headers(stageOne.headers),
        config,
        request,
    };
    if (stageOne.status >= 200 && stageOne.status !== 204) {
        if (config.responseType === "stream") {
            const contentType = stageOne.headers.get("content-type");
            if (!contentType?.startsWith(EventStreamContentType)) {
              // should give more detail information about the error
                throw new Error(`Expected content-type to be ${EventStreamContentType}, Actual: ${contentType}`);
            }
            await getBytes(stageOne.body, getLines(getMessages(config.onmessage)));
        }
        else {
```

I deployed my app but got errors. I debug the response by modify this code in node_modules, the experience is bad!

**Comment by meetyan** [comment]
Same here. I just got an error that said:

`Error: Expected content-type to be text/event-stream, Actual: application/json`

Couldn't find a solution until now. It was a token limit error from OpenAI.

**Comment by shixin-guo** [comment]
Same here.
