### ISSUE TITLE
DOC: <Issue related to /v0.2/docs/tutorials/chatbot>

### ISSUE THREAD

**Issue by Verten** [langchain-ai/langchainjs#6722]
### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

in document 
https://js.langchain.com/v0.2/docs/tutorials/chatbot#managing-conversation-history

In this code sample, `withMessageHistory2` it should be create with runnable `chain2`

see highlight in below screenshot

![image](https://github.com/user-attachments/assets/2eca678a-21c2-48b6-85d3-a5a6c9e53e36)

**Comment by jacoblee93** [comment]
Thanks for flagging!
