### ISSUE TITLE
PineconeStore.fromDocuments and other methods don't work

### ISSUE THREAD

**Issue by simon2652** [langchain-ai/langchainjs#6735]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

The following code : PineconeStore.fromDocuments([chunk], embeddings, {
                pineconeIndex,
                namespace: createdFile.id,
              }), is blocking and doesn't retrieve any information from my pineconeIndex. The same is true for PineconeStore.fromExistingIndex method.

Do any maintenance is ongoing right now on your side ?
              
              

### Description

The following code : PineconeStore.fromDocuments([chunk], embeddings, {
                pineconeIndex,
                namespace: createdFile.id,
              }), is blocking and doesn't retrieve any information from my pineconeIndex. The same is true for PineconeStore.fromExistingIndex method.

Do any maintenance is ongoing right now on your side ?
              
              

### System Info

Node.js v21.4.0.
pnpm 8.12.1

**Comment by simon2652** [comment]
@dosu you're right, i'm trying to create a new index and insert vector inside.

This issue is occuring in each of my procedures trying to connect to my pineconeIndex. The code was working great this morning, and without changes, the problem is now occuring. So I really wonder if there is an issue of my part or there are some maintenance operations on your side.

**Comment by simon2652** [comment]
i've just tried without Langchain and the code works. So definetely the problem is coming from Lanchain method. I'm using 
"langchain": "^0.1.7",
"@langchain/pinecone": "^0.0.2",
"@langchain/community": "^0.0.17",
"@langchain/google-genai": "^0.0.7",

**Comment by jacoblee93** [comment]
Hey @simon2652 sorry you're running into this - you're on some pretty old versions. Can you try bumping to latest? There have been a lot of changes on Pinecone and LangChain since then.

**Comment by simon2652** [comment]
Hi Jacob,
Indeed I've updated the version and it works. Thanks for your help

Le jeu. 12 sept. 2024 à 03:53, Jacob Lee ***@***.***> a
écrit :

**Comment by jacoblee93** [comment]
Great news! Thanks for engaging on this.
