### ISSUE TITLE
Update @langchain/core/messages/ToolCall [DEPRECATED] type to OpenAIToolCall

### ISSUE THREAD

**Issue by SantoshKumarRavi** [langchain-ai/langchainjs#6740]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```
import {
  BaseMessageChunk,
  OpenAIToolCall,
} from '@langchain/core/messages';



  async function  function1(
    response: BaseMessageChunk){
       const toolCalls = response.additional_kwargs.tool_calls;
    function2(toolCalls[0]);
    }
    
        async function function2(
       toolCall: OpenAIToolCall){
    }
```

### Error Message and Stack Trace (if applicable)

Argument of type 'ToolCall' is not assignable to parameter of type 'OpenAIToolCall'.
  Property 'index' is missing in type 'ToolCall' but required in type '{ index: number; }'.ts(2345)
base.d.ts(117, 5): 'index' is declared here.

### Description

I cross verified with latest doc (https://v02.api.js.langchain.com/classes/_langchain_core.messages_tool.ToolMessageChunk.html) too.
ToolCall is deprecated.
It is not updated with openAIToolCall in baseMessageChunk tool_calls.
I know that i can override type as temporary fix but it would be great if we update the type in main source.

### System Info

Node.js: v20.10.0
npm: v10.2.3
OS: Windows 10 Pro

**Comment by SantoshKumarRavi** [comment]
@dosu
not sure about your response will solve issue or not
but i think we need to update the BaseMessageFields tool_calls

export type BaseMessageFields = {
    content: MessageContent;
    name?: string;
    additional_kwargs?: {
        function_call?: FunctionCall;
        tool_calls?: ToolCall[];
        [key: string]: unknown;
    };
    /** Response metadata. For example: response headers, logprobs, token counts. */
    response_metadata?: Record<string, any>;
};

**Comment by jacoblee93** [comment]
Hey @SantoshKumarRavi, you can import this from `@langchain/messages/tool`:

```ts
import { ToolCall } from "@langchain/core/messages/tool";
```

I'll be removing this in 0.3!
