### ISSUE TITLE
Cannot install langchain package using npm: TypeError: Cannot read properties of null (reading 'edgesOut')

### ISSUE THREAD

**Issue by kareldonk** [langchain-ai/langchainjs#6792]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

None

### Error Message and Stack Trace (if applicable)

npm http fetch GET 200 https://registry.npmjs.org/youtubei.js 6ms (cache hit)
npm verbose stack TypeError: Cannot read properties of null (reading 'edgesOut')
npm verbose stack     at #loadPeerSet (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:1286:38)
npm verbose stack     at async #buildDepStep (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:901:11)
npm verbose stack     at async Arborist.buildIdealTree (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:181:7)
npm verbose stack     at async Promise.all (index 1)
npm verbose stack     at async Arborist.reify (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:131:5)
npm verbose stack     at async Install.exec (C:\Program Files\nodejs\node_modules\npm\lib\commands\install.js:150:5)
npm verbose stack     at async Npm.exec (C:\Program Files\nodejs\node_modules\npm\lib\npm.js:207:9)
npm verbose stack     at async module.exports (C:\Program Files\nodejs\node_modules\npm\lib\cli\entry.js:74:5)
npm error Cannot read properties of null (reading 'edgesOut')
npm verbose cwd C:\Dev\test
npm verbose os Windows_NT 10.0.19045
npm verbose node v20.17.0
npm verbose npm  v10.8.2
npm notice

### Description

In a new node.js project with no dependencies, I try to install langchain using the following command:

```
npm i langchain
```

Then I eventually get the following error:

```
npm http fetch GET 200 https://registry.npmjs.org/youtubei.js 6ms (cache hit)
npm verbose stack TypeError: Cannot read properties of null (reading 'edgesOut')
npm verbose stack     at #loadPeerSet (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:1286:38)
npm verbose stack     at async #buildDepStep (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:901:11)
npm verbose stack     at async Arborist.buildIdealTree (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:181:7)
npm verbose stack     at async Promise.all (index 1)
npm verbose stack     at async Arborist.reify (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:131:5)
npm verbose stack     at async Install.exec (C:\Program Files\nodejs\node_modules\npm\lib\commands\install.js:150:5)
npm verbose stack     at async Npm.exec (C:\Program Files\nodejs\node_modules\npm\lib\npm.js:207:9)
npm verbose stack     at async module.exports (C:\Program Files\nodejs\node_modules\npm\lib\cli\entry.js:74:5)
npm error Cannot read properties of null (reading 'edgesOut')
npm verbose cwd C:\Dev\test
npm verbose os Windows_NT 10.0.19045
npm verbose node v20.17.0
npm verbose npm  v10.8.2
npm notice
```

### System Info

Windows_NT 10.0.19045
node v20.17.0
npm  v10.8.2

**Comment by BeRecursive22** [comment]
@kareldonk I tried to install it and been thrown same errors.

**Comment by kareldonk** [comment]
For some reason adding the `--legacy-peer-deps` CLI argument makes it work.

```
npm i langchain --legacy-peer-deps
```

**Comment by WanielDeiss** [comment]
I get the same error, even with older langchain versions. I have the latest Node & NPM version and want to install it in a fresh project without other dependencies. Here is a screenshot.

![image](https://github.com/user-attachments/assets/244bc8ea-b531-47f9-8c36-8aa964aac5a3)

Node: 22.8.0
NPM: 10.8.3
macOS Sonoma 14.2.1

**Comment by brianpursley** [comment]
Same problem here on Ubuntu 22.04.5.

I also tried a few previous npm versions with no success.

By the way, `yarn add langchain` works, so I guess this problem is specific to npm somehow.

**Comment by pablobesada** [comment]
same problem here in multiple linux versions.
working fine on macos

**Comment by BeRecursive22** [comment]
MacOs M1 Air

same problem. Not even able to navigate the code...it's freezing my terminal probably due to the size of the project.

**Comment by Valeriamelly** [comment]
@kareldonk true, I had the same error, then I tried your suggest
![image](https://github.com/user-attachments/assets/d19d3a40-94b2-407d-ab7f-7f8abcdd5120)
![image](https://github.com/user-attachments/assets/39b3b0f4-c44f-4e6c-9b55-a993f726f5cf)

**Comment by danstarns** [comment]
+1 

Error log: 

```
833 verbose stack TypeError: Cannot read properties of null (reading 'edgesOut')
833 verbose stack     at #loadPeerSet (/Users/danielstarns/.nvm/versions/node/v22.4.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1286:38)
833 verbose stack     at async #buildDepStep (/Users/danielstarns/.nvm/versions/node/v22.4.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:901:11)
833 verbose stack     at async Arborist.buildIdealTree (/Users/danielstarns/.nvm/versions/node/v22.4.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:181:7)
833 verbose stack     at async Promise.all (index 1)
833 verbose stack     at async Arborist.reify (/Users/danielstarns/.nvm/versions/node/v22.4.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:131:5)
833 verbose stack     at async Install.exec (/Users/danielstarns/.nvm/versions/node/v22.4.1/lib/node_modules/npm/lib/commands/install.js:150:5)
833 verbose stack     at async Npm.exec (/Users/danielstarns/.nvm/versions/node/v22.4.1/lib/node_modules/npm/lib/npm.js:207:9)
833 verbose stack     at async module.exports (/Users/danielstarns/.nvm/versions/node/v22.4.1/lib/node_modules/npm/lib/cli/entry.js:74:5)
834 error Cannot read properties of null (reading 'edgesOut')
```

Running with --legacy-peer works:

```
npm i langchain --legacy-peer-deps
```

**Comment by jacoblee93** [comment]
Hey folks, looking into this - this is quite odd!

**Comment by jacoblee93** [comment]
So I initially thought this was related to 0.3.0, but I can run:

```
$ npm i @langchain/core@0.1.28
```

But not:

```
$ npm i @langchain/core@0.1.29
```

Investigating why this suddenly started failing...

**Comment by jacoblee93** [comment]
Ok, it seems `npm` changed something with how they handle peer dependencies internally - we have a circular peer dependency in a subpackage on `@langchain/core`, and hard-locking it to a version before the circular peer dep works.

As a workaround, try @danstarns' comment:

```bash
npm i langchain --legacy-peer-deps
```

Or switch to `yarn`/`pnpm`.

**Comment by jacoblee93** [comment]
Hey folks, have just cut `@langchain/core@0.3.1` and `langchain@0.3.1` - can you try again and let me know if that fixes it?

I'll also cut new 0.2 versions of the above packages shortly in case you don't want to update to latest.

**Comment by tro9999** [comment]
clean install 0.3.2 works ok

**Comment by WanielDeiss** [comment]
> Hey folks, have just cut `@langchain/core@0.3.1` and `langchain@0.3.2` - can you try again and let me know if that fixes it?
> 
> I'll also cut new 0.2 versions of the above packages shortly in case you don't want to update to latest.

works for me now! thanks

**Comment by danstarns** [comment]
Fixed in `0.3.2`. Thanks @jacoblee93 <3

**Comment by jacoblee93** [comment]
Thanks for reporting all! This was a super bizarre coincidence with 0.3.

**Comment by Valeriamelly** [comment]
It works too. Thankss @jacoblee93
