### ISSUE TITLE
RunnableWithFallbacks doesn't support `.bindTools`

### ISSUE THREAD

**Issue by airhorns** [langchain-ai/langchainjs#6869]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

The following code:

```typescript
import { ChatOpenAI } from "@langchain/openai";
import { webSearchTool } from "./src/tools/webSearch";

export const gpt4o = new ChatOpenAI({
  model: "gpt-4o",
});

export const gpt4oMini = new ChatOpenAI({
  model: "gpt-4o-mini",
});


const model = gpt4oMini.withFallbacks([gpt4o]);
await model.bindTools([webSearchTool]).invoke("what's the weather in ottawa?");
```

throws errors when run

### Error Message and Stack Trace (if applicable)

```
TypeError: model.bindTools is not a function
    at Object.<anonymous> (/Users/airhorns/Code/gadget/packages/data-science/scratch.ts:10:12)
    at Module._compile (node:internal/modules/cjs/loader:1434:14)
    at Object.require.extensions.<computed> [as .ts] (/Users/airhorns/Code/gadget/node_modules/.pnpm/wds@0.19.0_@swc+helpers@0.5.12/node_modules/wds/src/child-process-registration.ts:78:16)
    at Module.load (node:internal/modules/cjs/loader:1249:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1065:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:158:12)
    at node:internal/main/run_main_module:30:49
```

### Description

I'm trying to manage API rate limits from the underlying LLM providers. My Runnable uses tools. I tried to swap out the base `ChatOpenAI` model for a Runnable produced by calling `.withFallbacks`, but the returned fallback runnable doesn't allow me to bind new tools. I think it should -- I think that would satisfy the Liskov substitutability principle and be very convenient. Otherwise, we must bind all the source models to tools manually, and then construct the fallback chain, which is annoying and hard to do across a whole complicated system with a wide variety of tools.

### System Info

```
> pnpm info langchain

langchain@0.3.2 | MIT | deps: 12 | versions: 297
Typescript bindings for langchain
https://github.com/langchain-ai/langchainjs/tree/main/langchain/

keywords: llm, ai, gpt3, chain, prompt, prompt engineering, chatgpt, machine learning, ml, openai, embeddings, vectorstores

dist
.tarball: https://registry.npmjs.org/langchain/-/langchain-0.3.2.tgz
.shasum: aec3e679d3d6c36f469448380affa475c92fbd86
.integrity: sha512-kd2kz1cS/PIVrLEDFlrZsAasQfPLbY1UqCZbRKa3/QcpB33/n6xPDvXSMfBuKhvNj0bjW6MXDR9HZTduXjJBgg==
.unpackedSize: 2.9 MB

dependencies:
@langchain/openai: >=0.1.0 <0.4.0        js-tiktoken: ^1.0.12                     jsonpointer: ^5.0.1                      openapi-types: ^12.1.3                   uuid: ^10.0.0                            zod-to-json-schema: ^3.22.3
@langchain/textsplitters: >=0.0.0 <0.2.0 js-yaml: ^4.1.0                          langsmith: ^0.1.56-rc.1                  p-retry: 4                               yaml: ^2.2.1                             zod: ^3.22.4

maintainers:
- nfcampos <nuno@boringbits.io>
- jacoblee93 <jacoblee93@gmail.com>
- andrewnguonly <andrewnguonly@gmail.com>
- davidduong <david@duong.cz>
- hwchase17 <hw.chase.17@gmail.com>
- basproul <braceasproul@gmail.com>

dist-tags:
latest: 0.3.2                              next: 0.3.2-rc.0                           tag-for-publishing-older-releases: 0.2.20

published a week ago by jacoblee93 <jacoblee93@gmail.com>
```

**Comment by bracesproul** [comment]
You'll need to call `.bindTools` on the chat model class directly, as the `.bindTools` method does not exist on the base `Runnable` class (which is what `. withFallbacks` returns). Then after binding the tools, you can call `.withFallbacks`

**Comment by airhorns** [comment]
Right -- I am saying that is really annoying, and seems like an artificial limitation. If you have a big system set up, it seems wise to set up a bunch of base models with shared API keys and retry configs and all the other options you find out you need over time, and then have all the different bits of your graph or agent that might want to use those models bind their own tools. That lets you share all the retry configs and API keys and model versions among all your spots so you're not duplicating them over and over.

But, if we have to bind the tools before doing any fallbacks, that means that every place where we bind a tool has to become "fallback aware". It has to import all the models it might want to use, bind each of the tools, then create the fallback chain. You *can't* share fallback configs like you can all the other stuff. Why not? It seems perfectly reasonable to say "I always want to fall back to gpt-4o from gpt-4o-mini" and set up one base model that does that, and then bind tools to that. If we could just set up the base models that everywhere imported to have their own fallbacks, then all the downstream callers wouldn't need to adjust. 

IMO this is a violation of the Liskov Substitutability Principle, which more-or-less states "it's really surprising when a subtype doesn't work the same way as a super type". It seems like `withFallbacks` doesn't *need* to change the interface, it just happens to do so today.

**Comment by bracesproul** [comment]
@airhorns I hear you on this, and yes in a way it is an "artificial limitation". We decided to not add `bindTools` to the `Runnable` class because many components which tools are not relevant to (e.g retrievers, prompt templates, etc) extend the `Runnable` class. Therefore being able to call `bindTools` on a retriever wouldn't make sense. I hope this helped you understand a little better what's going on, and please ping me if you run into an issue.

**Comment by airhorns** [comment]
I get that -- it definitely doesn't make sense to call `bindTools` on a retriever. But, my fallback chain doesn't have any retrievers in it -- I know for certain I can bind tools to each of them. Right from the LangChain homepage:

> Want to change your model? Future-proof your application by incorporating vendor optionality into your LLM infrastructure design.

If the point of the library is provide nice abstractions over the nuances of the inner models, or of retrievers etc, it seems like this substitutibilty thing is *important*. Do you agree that it would be desirable if there were a design that allowed for binding tools to fallback chains?

**Comment by Arunprakaash** [comment]
Hi everyone,

In the meantime, here’s a Python-based workaround that lets you bind tools onto a RunnableWithFallbacks and avoid the model.bindTools error.

```import json
from typing import (
    Annotated,
    Any,
    Sequence,
    TypedDict, 
    Union,
    cast
)
from pydantic import BaseModel
from langgraph.graph.message import add_messages
from langchain_core.messages import ToolMessage, SystemMessage, BaseMessage
from langchain_core.runnables import RunnableWithFallbacks, RunnableConfig
from langchain_core.output_parsers import PydanticOutputParser
from langgraph.graph import StateGraph, END

from app.services.prompts import web_search_system_prompt
from app.core.tools import web_search

StructuredResponse = Union[dict, BaseModel]
StructuredResponseSchema = Union[dict, type[BaseModel]]
tools = [web_search]

class AgentState(TypedDict):
    messages: Annotated[Sequence[BaseMessage], add_messages]
    structured_response: StructuredResponse

def _get_state_value(state: AgentState, key: str, default: Any = None) -> Any:
    return (
        state.get(key, default)
        if isinstance(state, dict)
        else getattr(state, key, default)
    )

def create_websearch_agent(
    model: RunnableWithFallbacks,
    response_format: Union[StructuredResponseSchema, tuple[str, StructuredResponseSchema]]
):
    tools_by_name = {tool.name: tool for tool in tools}

    def generate_structured_response(state: AgentState, config: RunnableConfig) -> AgentState:
        messages = _get_state_value(state, "messages")
        structured_response_schema = response_format
        if isinstance(response_format, tuple):
            system_prompt, structured_response_schema = response_format
            messages = [SystemMessage(content=system_prompt)] + list(messages)

        model_with_structured_output = model.with_structured_output(
            cast(StructuredResponseSchema, structured_response_schema)
        )
        response = model_with_structured_output.invoke(messages, config)
        return {"structured_response": response}

    def tool_node(state: AgentState):
        outputs = []
        for tool_call in state["messages"][-1].tool_calls:
            tool_result = tools_by_name[tool_call["name"]].invoke(tool_call["args"])
            outputs.append(
                ToolMessage(
                    content=json.dumps(tool_result),
                    name=tool_call["name"],
                    tool_call_id=tool_call["id"],
                )
            )
        return {"messages": outputs}
    
    def call_model(state: AgentState, config: RunnableConfig):
        parser = PydanticOutputParser(pydantic_object=response_format)
        format_instructions = (
            f"Answer the user query. Wrap the output in `json` tags\n"
            f"{parser.get_format_instructions()}"
        )
        system_prompt = SystemMessage(web_search_system_prompt + format_instructions)
        response = model.invoke([system_prompt] + state["messages"], config)
        return {"messages": [response]}
    
    def should_continue(state: AgentState):
        last = state["messages"][-1]
        return "tools" if last.tool_calls else "generate_structured_response"

    workflow = StateGraph(AgentState)
    workflow.add_node("agent", call_model)
    workflow.add_node("tools", tool_node)
    workflow.add_node("generate_structured_response", generate_structured_response)
    workflow.set_entry_point("agent")
    workflow.add_conditional_edges(
        "agent",
        should_continue,
        {"tools": "tools", "generate_structured_response": "generate_structured_response"},
    )
    workflow.add_edge("tools", "agent")
    workflow.add_edge("generate_structured_response", END)

    return workflow.compile()
```
