### ISSUE TITLE
Chroma local persistence supported in Python but not in JS

### ISSUE THREAD

**Issue by softwarerockstar** [langchain-ai/langchainjs#687]
In Python version we can provide `persist_directory` parameter in the `from_documents` method to persist the index to disk. This parameter is missing from the JS version.

Python example:

`Chroma.from_documents(texts, embeddings, persist_directory='/path/to/index/folder')`

JS signature of the same function:

`Chroma.fromDocuments(docs: Document[], embeddings: Embeddings, dbConfig: {
    collectionName?: string;
    url?: string;
}): Promise<Chroma>`

**Comment by kwkr** [comment]
It looks like the persisting logic is currently [not available](https://github.com/chroma-core/chroma/blob/abdf9b56d2fd4da45862faa1940a99cd2298ea03/clients/js/src/index.ts#L378) on the JS Chroma client that this library uses.

**Comment by kknono** [comment]
same issue, any help?

**Comment by zuffik** [comment]
I mean, boys, can't we just do `fs.writeFileSync` and `fs.readFileSync`?
