### ISSUE TITLE
DOC: Fix incorrect Ollama integration example in LangChain.js documentation

### ISSUE THREAD

**Issue by byungchan0725** [langchain-ai/langchainjs#6897]
### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

I discovered an inconsistency between the documentation and the actual behavior while implementing function calling functionality using the ChatOllama class in LangChain.js.
Link: [Class ChatOllama](https://v03.api.js.langchain.com/classes/_langchain_ollama.ChatOllama.html)

<br>

When executing this code:
```
const llmWithTools = llm.bindTools(
  [...],
  {
    tool_choice: "auto",
  }
);
```
It results in the following error:
```
$ Error: "Tool choice is not supported for ChatOllama."
```

<br>

However, when including the tool_choice: "auto" option in the ChatOllama constructor, it works as expected:
```js 
const llm = new ChatOllama({
  model: 'llama3.1',
  temperature: 0,
  tool_choice: 'auto',
});
```

<br>

Expected Behavior:
According to the documentation, it should be possible to pass the tool_choice: "auto" option as the second argument to the bindTools() method.

Actual Behavior:
The tool_choice: "auto" option only works when placed in the ChatOllama constructor and throws an error when used in the bindTools() method.

<br>

Here's the complete code:
```js
const { z } = require('zod');
const { ChatOllama } = require('@langchain/ollama');

const llm = new ChatOllama({
  model: 'llama3.1',
  temperature: 0,
  tool_choice: 'auto', // Moved from bindTools()
});

const GetLocation = {
  name: 'GetLocation',
  description: 'Extract the location name from user input',
  schema: z.object({
    location: z.string().describe('The city and state, e.g. San Francisco, CA'),
  }),
};

const llmWithTools = llm.bindTools([GetLocation]);

async function test() {
  const aiMsg = await llmWithTools.invoke(
    'What is the weather like in Seoul today?'
  );
  console.log(aiMsg.tool_calls);
}

test();
```

### Idea or request for content:

You can modify the document as follows:
```js 
// When calling `.bind`, call options should be passed via the first argument
const llmWithArgsBound = llm.bind({
  stop: ["\n"],
  tools: [...],
});

// When calling `.bindTools`, call options should be passed via the second argument
const llmWithTools = llm.bindTools(
  [...],
);
```

```js 
import { ChatOllama } from '@langchain/ollama';

const llm = new ChatOllama({
  model: "llama-3.1:8b",
  temperature: 0,
  tool_choice: "auto",
  // other params...
});
```
<br>

This is my first time creating issues for Langchain, so I hope I'm doing it correctly.

**Comment by byungchan0725** [comment]
@dosu  Then isn't the example in this link incorrect?
link: https://v03.api.js.langchain.com/classes/_langchain_ollama.ChatOllama.html

<img width="500" alt="image" src="https://github.com/user-attachments/assets/beb3d98e-b6b9-4255-9b0c-d731d5691379">

**Comment by byungchan0725** [comment]
@dosu Then, shouldn't we modify the docs?

**Comment by jacoblee93** [comment]
@bracesproul we should support this as a bound parameter as well I think?

**Comment by byungchan0725** [comment]
Thanks!
