### ISSUE TITLE
YoutubeLoader does not work on production environment. 

### ISSUE THREAD

**Issue by DevDeepakBhattarai** [langchain-ai/langchainjs#6915]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```typescript
"use server";
import "server-only";
import { db } from "@/server/db";
import { z } from "zod";
import { auth } from "@/server/auth";
import { YoutubeLoader } from "@langchain/community/document_loaders/web/youtube";
import { SitemapLoader } from "@langchain/community/document_loaders/web/sitemap";
import { env } from "@/env";
import { RecursiveCharacterTextSplitter } from "@langchain/textsplitters";
import { PineconeStore } from "@langchain/pinecone";
import { Pinecone } from "@pinecone-database/pinecone";
import { OpenAIEmbeddings } from "@langchain/openai";
import { CheerioWebBaseLoader } from "@langchain/community/document_loaders/web/cheerio";

const YoutubeSchema = z.object({
  url: z.string().url(),
  type: z.literal("youtube"),
});

const webPageSchema = z.object({
  url: z.string().url(),
  type: z.literal("webpage"),
});

const siteMapSchema = z.object({
  url: z.string().url(),
  type: z.literal("sitemap"),
});

const schema = z.union([YoutubeSchema, webPageSchema, siteMapSchema]);

export async function addKnowledgeFormExternalSource(
  dbiId: string,
  data: z.infer<typeof schema>,
) {

  const parsedData = await schema.safeParseAsync(data);

  if (!parsedData.success) {
    throw new Error("Invalid data");
  }

  const { url, type } = parsedData.data;

  let loader: YoutubeLoader | CheerioWebBaseLoader | SitemapLoader;
  switch (type) {
    case "youtube":
      loader = YoutubeLoader.createFromUrl(url, {
        language: "en",
        addVideoInfo: true,
      });
      break;
    case "webpage":
      // loader = new FireCrawlLoader({
      //   url: url,
      //   apiKey: env.FIRECRAWL_API_KEY,
      //   mode: "scrape",
      // });
      loader = new CheerioWebBaseLoader(url);
      break;
    case "sitemap":
      loader = new SitemapLoader(url);
      break;
  }
  const docs = await loader.load();

  console.log(docs.length, docs);

  if (docs.length < 1) {
    throw new Error("No docs found");
  }

  const embedding = new OpenAIEmbeddings();

  const fileName =
    type === "youtube"
      ? (docs[0]!.metadata?.title as string)
      : type === "webpage"
        ? (docs[0]!.metadata?.source as string)
        : (docs[0]?.metadata?.title as string);

  const fileId = await createFileRecord(fileName, dbiId);
  const pinecone = new Pinecone({
    apiKey: env.PINECONE_API_KEY,
  });
  const pineconeIndex = pinecone.Index("allweone");
  const splitter = new RecursiveCharacterTextSplitter({
    chunkSize: 1000,
    chunkOverlap: 200,
  });

  const splitDocs = await splitter.splitDocuments(docs);
  const splitDocsWithMetadata = splitDocs.map((doc) => ({
    ...doc,
    metadata: {
      ...doc.metadata,
      fileId,
    },
  }));

  const store = await PineconeStore.fromDocuments([], embedding, {
    pineconeIndex,
    namespace: `${userId}-${dbiId}`,
  });

  await store.addDocuments(splitDocsWithMetadata, {
    ids: splitDocsWithMetadata.map((_, index) => `${fileId}#${index}`),
  });
}
```

### Error Message and Stack Trace (if applicable)

Error: Failed to get YouTube video transcription: [YoutubeTranscript] 🚨 Transcript is disabled on this video (ejVMXu-u1hs)
    at IW.load (/var/task/.next/server/chunks/6531.js:365:290354)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async y (/var/task/.next/server/chunks/1201.js:97:6103)
    at async /var/task/.next/server/chunks/6531.js:368:24443
    at async eg (/var/task/.next/server/chunks/6531.js:368:24270)
    at async /var/task/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.5_@opentelemetry+api@1.9.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:418
    at async rR (/var/task/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.5_@opentelemetry+api@1.9.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:15:7978)
    at async r7 (/var/task/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.5_@opentelemetry+api@1.9.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:18:1144)
    at async es (/var/task/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.5_@opentelemetry+api@1.9.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:16:26324)
    at async en.responseCache.get.routeKind (/var/task/node_modules/.pnpm/next@14.2.5_@babel+core@7.24.5_@opentelemetry+api@1.9.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:17:1026) {
  digest: '2995320257'
}

### Description

I am using Next JS and Langchain JS. And hosting my app on Vercel.

I am trying to build a rag app where I can also upload data form youtube videos. But I am facing one issue right now. 
When ever I run this code on my local server it works and I can successfully get the transcript data from youtube. But whenever I try do the same things in the production server than I get the above error. 

The same video works in development and not on the production. 

There is no any environment variable that is required for this so I don't think there is any difference between production and development. 

So what is the issue here. 
Can anyone help me ?

### System Info

Next Js 14.2.5
Vercel 

Local Server : Windows 11
Node 20.10.0

**Comment by DevDeepakBhattarai** [comment]
@dosu No, that is not the issue because in the development environment I can get the transcript using the same video. So transcript is not disabled.

**Comment by jacoblee93** [comment]
Scraping is generally a bit janky unfortunately - perhaps Vercel's IP is getting blocked?

**Comment by DevDeepakBhattarai** [comment]
Thanks @jacoblee93.
I figured that was the case but now I am clear.
