### ISSUE TITLE
update @pinecone-database/pinecone dependency to "^3.0.3"

### ISSUE THREAD

**Issue by ladrians** [langchain-ai/langchainjs#6970]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

We experienced Pinecone timeout connection issues on a stress test, similar to this output

```
[cause]: ConnectTimeoutError: Connect Timeout Error (attempted addresses: <ips>)
```

We were using "@langchain/pinecone": "^0.0.9" updated to "@langchain/pinecone": "^0.1.1" with similar results.

Finally checking some internal dependencies and links decided to directly add and update the dependency `@pinecone-database/pinecone` dependency to "^3.0.3" and started working.

Not sure what was the internal change [there](https://github.com/pinecone-io/pinecone-ts-client), maybe related to [fetching](https://github.com/nodejs/undici/issues/1248).

### Error Message and Stack Trace (if applicable)

The log details

```
[cause]: ConnectTimeoutError: Connect Timeout Error (attempted addresses: <ips>)
```

### Description

Update the internal dependency for the pinecone store

### System Info

node v18.18.2
"@langchain/pinecone": "^0.0.9"

**Comment by kodychik** [comment]
Hi can I work on this issue?
Thanks

**Comment by ladrians** [comment]
yes please! it seems to be simple to update the dependency and check on your side the CI/CD cases works fine for pinecone.

**Comment by jacoblee93** [comment]
We've bumped to support Pinecone 4.x here: https://github.com/langchain-ai/langchainjs/pull/7175
