### ISSUE TITLE
SerpAPI Configurable Search Results

### ISSUE THREAD

**Issue by paulnovacovici** [langchain-ai/langchainjs#701]
Is it by design that the SERP API and Bing API only take into account the first SERP result from the search query response? If not I can create a PR to make it configurable so developers can pull in more context from a search.

https://github.com/hwchase17/langchainjs/blob/7d7e79c75d2da1dad5707a0d7b2594a96e3281d8/langchain/src/agents/tools/serpapi.ts#L368

**Comment by nfcampos** [comment]
@agola11 @hwchase17 thoughts here? Sounds reasonable to me let people configure this, as long as the several results are stringified into one single string?
