### ISSUE TITLE
how to handle stream when use agent? 

### ISSUE THREAD

**Issue by mengjian-github** [langchain-ai/langchainjs#702]
when use agent, handleLLMNewToken will receive json，how can i receive the real output from stream？

**Comment by nfcampos** [comment]
Hi @mengjian-github can you let me know more about your use case, what do you want to take from the original output of the openai stream?

**Comment by mengjian-github** [comment]
@nfcampos I want to create a chatbot and would like to leverage the abilities of tools, but I have found that I cannot use the streamable API. Waiting for a response takes too long, and using stream rendering like real-time chat tools would provide a better user experience.

**Comment by mengjian-github** [comment]
I want to get the real text after "Final Answer: "，but there is no such streaming callback to handle now

**Comment by nfcampos** [comment]
cc @agola11

**Comment by agola11** [comment]
Thanks for bringing this up @mengjian-github -- this is something we are actively looking to improve. In the meantime, this isn't ideal, but you might be able to get away with saving some state of the previously seen tokens and only start streaming to a client once the previously seen token string ends with "Final Answer: "

Will keep this issue open as we investigate a better solution

**Comment by shawnesquivel** [comment]
Hi @agola11 (or anyone else). I'm also having the same issue. How would I return the last part of the chain as you have mentioned? The `response.body` is a readable stream.

```
  const input =
    "Who is Olivia Wildes Boyfriend?"

  console.log(`Executing with input "${input}"...`);

  const result = agent.call({ input: input });

  return result;
```

```

[chain/end] [1:chain:agent_executor > 8:chain:llm_chain] [2.96s] Exiting Chain run with output: {
  "text": " I now know the final answer.\nFinal Answer: Harry Styles is Olivia Wilde's boyfriend and his current age raised to the 0.23 power is 2.1156502324195268."
}
[chain/end] [1:chain:agent_executor] [19.49s] Exiting Chain run with output: {
  "output": "Harry Styles is Olivia Wilde's boyfriend and his current age raised to the 0.23 power is 2.1156502324195268."
}

```

**Comment by waptik** [comment]
I also faced this issue and opened #1048 sometime ago. So i had to disable streaming for my telegram bot

**Comment by DanielhCarranza** [comment]
Anyone managed to stream the final output of an Agent ?

**Comment by Tolu-Mals** [comment]
> Anyone managed to stream the final output of an Agent ?

I was able to

```typescript
const tempTokens = "";

...

{
    handleLLMNewtoken(token){
       if(tempTokens.includes("Final Answer:")){
            console.log(token); //write to stream
       } else {
          tempToken += token;
       }
    }
}
```

**Comment by waptik** [comment]
> > Anyone managed to stream the final output of an Agent ?
> 
> I was able to
> 
> ```ts
> const tempTokens = "";
> 
> ...
> 
> {
>     handleLLMNewtoken(token){
>        if(tempTokens.includes("Final Answer:")){
>             console.log(token); //write to stream
>        } else {
>           tempToken += token;
>        }
>     }
> }
> ```
> 
> Then when agent ends, set `tempTokens` back to an empty string, or the logic will break for future calls.
> 
> ```ts
> executor.call().then(() => {
>  tempTokens = "";
> })
> ```

I thought you can't mutate a `const` value, so how did it work for you?? Also, where did you define `tempTokens` ?

**Comment by Tolu-Mals** [comment]
> > > Anyone managed to stream the final output of an Agent ?
> > 
> > 
> > I was able to
> > ```ts
> > const tempTokens = "";
> > 
> > ...
> > 
> > {
> >     handleLLMNewtoken(token){
> >        if(tempTokens.includes("Final Answer:")){
> >             console.log(token); //write to stream
> >        } else {
> >           tempToken += token;
> >        }
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then when agent ends, set `tempTokens` back to an empty string, or the logic will break for future calls.
> > ```ts
> > executor.call().then(() => {
> >  tempTokens = "";
> > })
> > ```
> 
> I thought you can't mutate a `const` value, so how did it work for you?? Also, where did you define `tempTokens` ?

My bad that should have been a `let`. It's a nextjs api route in the app directory, placed it above the handler function.

**Comment by waptik** [comment]
Alright! I'll give it a try a see how it fairs

**Comment by Penggeor** [comment]
There has any progress？ 🥹 @agola11

**Comment by Robert-ZLF** [comment]
Any updates?

**Comment by Tolu-Mals** [comment]
Add the handleNewLLMToken() handler when creating the instance of the LLM to access LLM tokens as they're being generated, you can then write the answers to a Writable stream. For streaming agent actions,s et the  `callbacks` property in the options argument for initializeAgentExecutorWithOptions, you can access the data in the callback and do whatever you want from there

**Comment by MichelFR** [comment]
Also waiting for updates here, would be nice to know if something can be done.
