### ISSUE TITLE
ChatDeepInfra does not implement bindTools

### ISSUE THREAD

**Issue by maharifu** [langchain-ai/langchainjs#7020]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

Following the quickstart tutorial [here](https://langchain-ai.github.io/langgraphjs/tutorials/quickstart/#customizing-agent-behavior), but replacing `ChatOpenAI` with `ChatDeepInfra` like this:
```
const model = new ChatDeepInfra({
  model: 'meta-llama/Meta-Llama-3-70B-Instruct',
  temperature: 0,
  apiKey: 'XXXXX',
}).bindTools(tools);
```

### Error Message and Stack Trace (if applicable)

TypeError: (intermediate value).bindTools is not a function

### Description

* I'm trying to to build an agent using `ChatDeepInfra` with tools
* I would expect it to implement `bindTools`, like the [python version](https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/chat_models/deepinfra.py#L479)
* Instead I get an error

### System Info

```
npm info langchain

langchain@0.3.2 | MIT | deps: 12 | versions: 297
Typescript bindings for langchain
https://github.com/langchain-ai/langchainjs/tree/main/langchain/

keywords: llm, ai, gpt3, chain, prompt, prompt engineering, chatgpt, machine learning, ml, openai, embeddings, vectorstores

dist
.tarball: https://registry.npmjs.org/langchain/-/langchain-0.3.2.tgz
.shasum: aec3e679d3d6c36f469448380affa475c92fbd86
.integrity: sha512-kd2kz1cS/PIVrLEDFlrZsAasQfPLbY1UqCZbRKa3/QcpB33/n6xPDvXSMfBuKhvNj0bjW6MXDR9HZTduXjJBgg==
.unpackedSize: 2.9 MB

dependencies:
@langchain/openai: >=0.1.0 <0.4.0        openapi-types: ^12.1.3
@langchain/textsplitters: >=0.0.0 <0.2.0 p-retry: 4
js-tiktoken: ^1.0.12                     uuid: ^10.0.0
js-yaml: ^4.1.0                          yaml: ^2.2.1
jsonpointer: ^5.0.1                      zod-to-json-schema: ^3.22.3
langsmith: ^0.1.56-rc.1                  zod: ^3.22.4

maintainers:
- nfcampos <nuno@boringbits.io>
- jacoblee93 <jacoblee93@gmail.com>
- andrewnguonly <andrewnguonly@gmail.com>
- davidduong <david@duong.cz>
- hwchase17 <hw.chase.17@gmail.com>
- basproul <braceasproul@gmail.com>

dist-tags:
latest: 0.3.2                              tag-for-publishing-older-releases: 0.2.20
next: 0.3.2-rc.0

published a month ago by jacoblee93 <jacoblee93@gmail.com>
```

```
node --version
v20.10.0
```

Platform: Linux

**Comment by taariq** [comment]
Hey there @ovuruska. Would you be able to help here from the Deep Infra side?

**Comment by MirrorLimit** [comment]
Hi, we're a group of students from the University of Toronto and we can take a look at this and see what we can do?
