### ISSUE TITLE
DOC: /docs/integrations/text_embedding/tensorflow uses the v0.1 import style which doesn't work

### ISSUE THREAD

**Issue by kikoncuo** [langchain-ai/langchainjs#7113]
### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

https://js.langchain.com/docs/integrations/text_embedding/tensorflow/

It uses v0.1 notation for the import and installations
```
import { TensorFlowEmbeddings } from "langchain/embeddings/tensorflow";
```
Should be 

```
import { TensorFlowEmbeddings } from "@langchain/community/embeddings/tensorflow";
```

### Idea or request for content:

Update 
```
import { TensorFlowEmbeddings } from "langchain/embeddings/tensorflow";
```
to

```
import { TensorFlowEmbeddings } from "@langchain/community/embeddings/tensorflow";
```

**Comment by kikoncuo** [comment]
This was a real problem I found and I can create a PR if anyone wants.
I don't want to do it without a confirmation because it may be considered a spam PR.

**Comment by jacoblee93** [comment]
Opened a PR, thanks for flagging!
