### ISSUE TITLE
Where is the SequentialChain exported from ?

### ISSUE THREAD

**Issue by vpaul18** [langchain-ai/langchainjs#720]
Hi !

I'm trying to convert the python implementation of Langchain to JS, yet I cannot seem to find where the `SequentialChain` is exported from in this repo. Or is it not supported yet?

Thanks!

**Comment by hyuraku** [comment]
https://github.com/hwchase17/langchainjs/pull/834 will add `SequentialChain`

**Comment by nfcampos** [comment]
This was just merged today #834 will release in a few hours

**Comment by nfcampos** [comment]
Ah yes quite right @kwkr my mistake. If you want to contribute that it would be great, but no pressure

**Comment by nfcampos** [comment]
Yea just start, we can use this issue, I've reopened it

**Comment by vpaul18** [comment]
@nfcampos @kwkr Thanks guys!
