### ISSUE TITLE
Cache token callbacks not available in Anthropic streaming

### ISSUE THREAD

**Issue by julian-shalaby** [langchain-ai/langchainjs#7262]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

Set the Anthropic constructor's prompt caching beta header, send a message with at least 2048 tokens to claude 3.5 haiku in streaming, and with the last message's content block containing cache_control: { type: "ephemeral" }

Log literally anything, and there is no mention of cache token reads or writes. This is available when using invoke, and apparently available in the Anthropic API with streaming (https://docs.anthropic.com/en/docs/build-with-claude/prompt-caching#tracking-cache-performance)

### Description

I want to see my cached token reads and writes in Langchain, for streaming Anthropic calls. It seems to exist in the direct anthropic api, but not in langchain's callbacks anywhere

### System Info

Most recent langchain versions on npm

**Comment by jacoblee93** [comment]
Hey, apologies for missing this!

I've pushed a fix in #7368

**Comment by julian-shalaby** [comment]
Awesome! Thank you so much!!

**Comment by jacoblee93** [comment]
It should be live in `@langchain/anthropic@0.3.10` (latest)

**Comment by julian-shalaby** [comment]
Yep! Can confirm its in there!
