### ISSUE TITLE
the createToolCallingAgent cant use with the gemini?

### ISSUE THREAD

**Issue by neilzhangpro** [langchain-ai/langchainjs#7275]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

the following code:
```
async testAgents(@Request() req ){
    //tools
    const searchTool = tool(
      async (query) => {
        const searchOnline = new TavilySearchResults({
          apiKey: this.configService.get<string>('TAVILY_KEY'),
        });
        // This is a placeholder, but don't tell the LLM that...
        return await searchOnline.invoke({ query: query });
      },
      {
        name: 'search',
        description: 'Call to surf the web.',
        schema: z.object({
          query: z.string().describe('The query to use in your search.'),
        }),
      },
    );
    const tools = [searchTool];
    const prompt = ChatPromptTemplate.fromMessages([
      ['system', 'You are a useful assistant and you can use relevant tools to answer questions. The user's questions are as follows:'],
      ['human','{input}'],
      ['placeholder', '{agent_scratchpad}'],
    ]);
    const agent = await createToolCallingAgent({
      llm: this.googleLLMService.llm,
      tools,
      prompt: prompt,
    });
    const agentExecutor = new AgentExecutor({
      agent,
      tools,
    });
    const result = await agentExecutor.invoke({input:"How is the weather in Beijing today?"});
    return result;
  }
```

### Error Message and Stack Trace (if applicable)

The result is :
```
{
  "input": "How is the weather in Beijing today?",
  "output": "Sorry, I can't get the weather information for Beijing today. You can try to check the latest weather conditions through the weather app or website."
}
```

### Description

i have readed the doc:https://js.langchain.com/docs/integrations/chat/google_generativeai#tool-calling
There is no instance of agents, **so i dont know how to set a agent with gemini and make sure it can use tools?**

### System Info

langchain 0.3.6
gemini-1.5-flash

**Comment by neilzhangpro** [comment]
by the way, i used those packages below:
 @langchain/google-genai 0.1.4
 this.googleLLMService.llm is defined like this:
 ```
 this.llm = new ChatGoogleGenerativeAI({
      model: 'gemini-1.5-flash',
      temperature: 0,
      apiKey: this.configService.get<string>('ALL_IN_ONE_KEY'),
      baseUrl: `${this.configService.get<string>('PROXY_URL')}/google`,
    });
   ```

**Comment by neilzhangpro** [comment]
> Hey @neilzhangpro! I'm here to help you out with any bugs, questions, or contributions you have regarding LangChain.js. Let's dive into this issue together!
> 
> To set up a `createToolCallingAgent` with Gemini in LangChain.js and ensure it can use tools, you need to follow these steps:
> 
> 1. **Ensure the Prompt is Correct**: The prompt must include an input variable named `agent_scratchpad`. This is crucial for the agent to function properly.
>    ```ts
>    const prompt = ChatPromptTemplate.fromMessages(
>      [
>        ["system", "You are a helpful assistant"],
>        ["human", "{input}"],
>        ["placeholder", "{agent_scratchpad}"],
>      ]
>    );
>    ```
> 2. **Check the LLM for `bindTools` Method**: The language model (LLM) should support the `bindTools` method. If it doesn't, you will encounter an error. Ensure that the LLM you are using is compatible.
>    ```ts
>    if (_isBaseChatModel(llm)) {
>      if (llm.bindTools === undefined) {
>        throw new Error(
>          `This agent requires that the "bind_tools()" method be implemented on the input model.`
>        );
>      }
>      modelWithTools = llm.bindTools(tools);
>    } else {
>      modelWithTools = llm;
>    }
>    ```
> 3. **Define the Tools**: Make sure you have defined the tools that the agent will have access to. For example, you can use `TavilySearchResults` for search capabilities.
>    ```ts
>    const tools = [new TavilySearchResults({ apiKey: 'your_api_key_here' })];
>    ```
> 4. **Create the Agent**: Use the `createToolCallingAgent` function to create the agent with the LLM, tools, and prompt.
>    ```ts
>    const agent = await createToolCallingAgent({ llm, tools, prompt });
>    ```
> 5. **Execute the Agent**: Use the `AgentExecutor` to invoke the agent with the desired input.
>    ```ts
>    const agentExecutor = new AgentExecutor({ agent, tools });
>    const result = await agentExecutor.invoke({ input: "How is the weather in Beijing today?" });
>    ```
> 6. **Handle Streaming Events**: If you want to handle streaming events, you can use the `streamEvents` method.
>    ```ts
>    const eventStream = agentExecutor.streamEvents(
>      { input: "How is the weather in Beijing today?" },
>      { version: "v2" }
>    );
>    
>    for await (const event of eventStream) {
>      const eventType = event.event;
>      if (eventType === "on_chat_model_stream") {
>        // Handle the event data
>      }
>    }
>    ```
> 
> Additionally, ensure that the `TavilySearchResults` tool is correctly configured with an API key, either set as an environment variable `TAVILY_API_KEY` or passed directly as a parameter [[1]](https://github.com/langchain-ai/langchainjs/blob/main/langchain/src/agents/tool_calling/index.ts)[[2]](https://github.com/langchain-ai/langchainjs/blob/main/langchain/src/util/testing/tools/tavily_search.ts).
> 
> I found similar discussions that might be relevant:
> 
> * [Function calling not working in ChatGoogleGenerativeAI with gemini-1.5-pro or gemini-1.5-flash](https://github.com/langchain-ai/langchainjs/discussions/6048) [[3]](https://github.com/langchain-ai/langchainjs/discussions/6048).
> * [Gemini is responding with empty text content as well as tool_call](https://github.com/langchain-ai/langchainjs/discussions/5996) [[4]](https://github.com/langchain-ai/langchainjs/discussions/5996).
> 
> These discussions are unsolved, but they might provide additional insights into similar issues.
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

Its not wrok for me robot! any one lived can help me ?

**Comment by neilzhangpro** [comment]
anyone can help me?

**Comment by jacoblee93** [comment]
Hey @neilzhangpro!

Does it work with OpenAI/Anthropic? If so, you may just need to try prompting a bit differently

For example, you may want to mention in your tool's description that it can `access the current weather`

Also, we generally suggest people use LangGraph.js for agents rather than anything with `AgentExecutor`:

https://langchain-ai.github.io/langgraphjs/how-tos/#prebuilt-react-agent

Please reopen if the above doesn't help!
