### ISSUE TITLE
DOC: opensearch vectorstore example code imports from incorrect path 

### ISSUE THREAD

**Issue by caroline717** [langchain-ai/langchainjs#7308]
### Checklist

- [X] I added a very descriptive title to this issue.
- [X] I included a link to the documentation page I am referring to (if applicable).

### Issue with current documentation:

https://js.langchain.com/docs/integrations/vectorstores/opensearch/
The current example code incorrectly imports ```OpenSearchVectorStore``` from ```"langchain/vectorstores/opensearch";```. The package does not exist there

### Idea or request for content:

The code should be corrected to 
```import { OpenSearchVectorStore } from "@langchain/community/vectorstores/opensearch";```

**Comment by jacoblee93** [comment]
Thanks for flagging!
