### ISSUE TITLE
google-common: Verify REST compatibility for Gemini 2.0

### ISSUE THREAD

**Issue by afirstenberg** [langchain-ai/langchainjs#7345]
### Privileged issue

- [X] I am a LangChain maintainer, or was asked directly by a LangChain maintainer to create an issue here.

### Issue Content

https://developers.googleblog.com/en/the-next-chapter-of-the-gemini-era-for-developers/

@jacoblee93 - Please assign this to me

**Comment by liorshk** [comment]
Also add update model name in these for making them eligible for multimodality

**Comment by afirstenberg** [comment]
> Also add update model name in these for making them eligible for multimodality

Can you clarify what you mean by this? The bi-directional realtime Multimodality is opened as #7346 since it requires changes to use websockets. Do you mean something else?

**Comment by liorshk** [comment]
The regular gemini flash 2.0 also [supports multimodality](https://github.com/google-gemini/cookbook/blob/main/gemini-2/get_started.ipynb), but currently [there is an error](https://github.com/langchain-ai/langchainjs/blob/fd433fd41a60d604247d55c99872ef4f5b62a869/libs/langchain-google-genai/src/utils/common.ts#L138) that the model doesn't support multi modality

**Comment by afirstenberg** [comment]
> The regular gemini flash 2.0 also [supports multimodality](https://github.com/google-gemini/cookbook/blob/main/gemini-2/get_started.ipynb), but currently [there is an error](https://github.com/langchain-ai/langchainjs/blob/fd433fd41a60d604247d55c99872ef4f5b62a869/libs/langchain-google-genai/src/utils/common.ts#L138) that the model doesn't support multi modality

That error is against the `google-genai` module. Try switching to `google-gauth` which doesn't use Google's library, but still supports API Keys. I've also opened an issue to update the `google-genai` module and noted this there as well.

**Comment by afirstenberg** [comment]
Testing so far looks pretty good, but see https://issuetracker.google.com/issues/384752742
