### ISSUE TITLE
Cohere rerank exception: invalid request: list of documents must not be empty

### ISSUE THREAD

**Issue by ahm750** [langchain-ai/langchainjs#7370]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

```
const retriever = vectorstore.asRetriever();

const cohereRerank = new CohereRerank({
    apiKey: COHERE_API_KEY,
    model: "rerank-v3.5",
    topN: 3,
});

const contextualCompressionRetriever = new ContextualCompressionRetriever({
    baseCompressor: cohereRerank,
    baseRetriever: retriever,
});

const stream = await ragChain.stream({
    chat_history: chatHistoryParsedArray,
    input: sanitizedText,
});
```

### Error Message and Stack Trace (if applicable)

BadRequestError
Status code: 400
Body: {
  "message": "invalid request: list of documents must not be empty"
}
/node_modules/langchain/dist/chains/combine_documents/base.js:8
    const formattedDocs = await Promise.all(documents.map((document) => documentPrompt
                                                      ^

TypeError: Cannot read properties of undefined (reading 'map')
    at formatDocuments (/node_modules/langchain/dist/chains/combine_documents/base.js:8:55)
    at RunnableLambda.func (/node_modules/langchain/dist/chains/combine_documents/stuff.js:27:90)
    at /node_modules/@langchain/core/dist/runnables/base.js:1735:44
    at MockAsyncLocalStorage.run (/node_modules/@langchain/core/dist/singletons/async_local_storage/index.js:10:16)
    at AsyncLocalStorageProvider.runWithConfig (/node_modules/@langchain/core/dist/singletons/async_local_storage/index.js:53:24)
    at output (/node_modules/@langchain/core/dist/runnables/base.js:1733:53)
    at new Promise (<anonymous>)
    at RunnableLambda._transform (/node_modules/@langchain/core/dist/runnables/base.js:1732:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RunnableLambda._transformStreamWithConfig (/node_modules/@langchain/core/dist/runnables/base.js:301:30)

### Description

I'm using the Cohere reranker, and it throws an exception when the retriever has empty documents. This prevents the AI for generating a response.

The ideal behavior should be to return an empty list so that the AI can generate a response based on the instructions we've given it.

Edit: this issue is similar to the ones reported in the Java and Python versions of Langchain, which were fixed a long time ago:

https://github.com/langchain4j/langchain4j/issues/770
https://github.com/langchain-ai/langchain/issues/5304

### System Info

Package versions:
"langchain": "^0.3.7"
"@langchain/cohere": "^0.3.1"
"@langchain/core": "^0.3.23"

**Comment by ahm750** [comment]
P.S: This is similar to the issues reported in the Java and Python versions of Langchain, which were fixed:
- https://github.com/langchain4j/langchain4j/issues/770
- https://github.com/langchain-ai/langchain/pull/5306

**Comment by ahm750** [comment]
Below are the two issues that are causing this error and the proposed fixes:

1. In the ```formatDocuments``` methods in ```langchain/dist/chains/combine_documents/base.js```, an empty string should be returned if ```documents``` is empty or null. Since this check is not implemented, it throws an exception when ```documents.map()``` is called.

Example:

```
export async function formatDocuments({ documentPrompt, documentSeparator, documents, config, }) {
    // PROPOSED FIX
    if (documents == null || documents.length == 0) {
        return "";
    }

    const formattedDocs = await Promise.all(documents.map((document) => documentPrompt
        .withConfig({ runName: "document_formatter" })
        .invoke({ ...document.metadata, page_content: document.pageContent }, config)));
    return formattedDocs.join(documentSeparator);
}
```

2. In ```compressDocuments``` method in ```langchain/dist/rerank.js```, when ```documents``` is empty, it should return an empty array.

Example:

```
    async compressDocuments(documents, query) {
        // PROPOSED FIX
        if (documents == null || documents.length == 0) {
            return [];
        }
        const _docs = documents.map((doc) => doc.pageContent);
        const { results } = await this.client.rerank({
            model: this.model,
            query,
            documents: _docs,
            topN: this.topN,
            maxChunksPerDoc: this.maxChunksPerDoc,
        });
        const finalResults = [];
        for (let i = 0; i < results.length; i += 1) {
            const result = results[i];
            const doc = documents[result.index];
            doc.metadata.relevanceScore = result.relevanceScore;
            finalResults.push(doc);
        }
        return finalResults;
    }
```

**Comment by ahm750** [comment]
Created PRs to address this issue. Please review. Thanks!

**Comment by sdan41517** [comment]
I'm having this issue as well
