### ISSUE TITLE
VertexAIEmbeddings don't work with europe-west9 location

### ISSUE THREAD

**Issue by Seigneurhol** [langchain-ai/langchainjs#7390]
### Checked other resources

- [X] I added a very descriptive title to this issue.
- [X] I searched the LangChain.js documentation with the integrated search.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I am sure that this is a bug in LangChain.js rather than my code.
- [X] The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).

### Example Code

``` typescript
  const embedder = new VertexAIEmbeddings({
    model: 'text-multilingual-embedding-002',
    location: 'europe-west9',
    authOptions: {
      keyFilename: config.vector_store_key_filename,
      scopes: [config.vector_store_scopes],
    },
  });
```

### Error Message and Stack Trace (if applicable)

GaxiosError: Publisher Model `projects/${projectId}/locations/europe-west9/publishers/unknown/models/text-multilingual-embedding-002` not found.

### Description

After updating when I use europe-west8 or  europe-west9 I have the GaxiosError with unknown publisher. But it work with us-central1 or europe-west1.

### System Info

node : v21.7.2
MacOS : 15.1.1

**Comment by afirstenberg** [comment]
Interesting. https://cloud.google.com/vertex-ai/generative-ai/docs/learn/locations suggests it should work in europe-west8 and europe-west9. Offhand this sounds like a problem with Google, not with LangChain, but let me see what I can find out.

**Comment by Seigneurhol** [comment]
Thank you for the doc I was trying to find the same data !
I asked there because the url was malformed with unknown for publisher : projects/${projectId}/locations/europe-west9/publishers/unknown/models/text-multilingual-embedding-002
So this is not an url build on langchain side ?
If not I will ask Google for more information on embedding on europe-west9

**Comment by afirstenberg** [comment]
Yeah, I was digging in deeper, and I think I see that we do have an issue on the LangChain.js side.

I'll try to take care of this in the next day or so.

@jacoblee93 - Please assign this to me.

**Comment by jacoblee93** [comment]
Thank you @afirstenberg
