### ISSUE TITLE
Supabase Index/Retriever - custom fields & filter

### ISSUE THREAD

**Issue by ShantanuNair** [langchain-ai/langchainjs#773]
1) In order to partition/index effectively, say by tenant, we would need to be able to pass in additional fields to the embeddings table. If exposed, we could pass those in as args and ensure that addVectors(vectors, documents) takes in a third arg that passes in those extra fields to update on the table.

2) In order retrieve filtered embeddings effectively, we would need to pass in filter.
 In VectorStore class: 
 ```
 async similaritySearchWithScore(query, k = 4, filter = undefined) {
        return this.similaritySearchVectorWithScore(await this.embeddings.embedQuery(query), k, filter);
    }
 ```
 we have support for that last filter arg, but in supabaseVectorStore implementation it is not used anywhere:
 ```
 async similaritySearchVectorWithScore(query, k) {
        ...
        ...
        return result;
    }
```

I can potentially work on adding these or help out some, given I have free time, but I'm also having issues making this work for us since we are on supabase v1, and the peer deps are already causing us difficulties.

**Comment by mishkinf** [comment]
Threw out a PR for this https://github.com/hwchase17/langchainjs/pull/905
