### ISSUE TITLE
OpenAPIChat can't get the usage from LLMResult

### ISSUE THREAD

**Issue by YikaJ** [langchain-ai/langchainjs#776]
```js
const callbackManager = CallbackManager.fromHandlers({
  handleLLMEnd: async (output: LLMResult) => {
    console.log(JSON.stringify(output, null, 2));
  },
  handleLLMError: async (err: Error) => {
    console.error(err);
  },
})
```

```js
new OpenAIChat({
  // ...other
  callbackManager
});
```

when I look at console, not return `llmOutputs`
<img width="425" alt="image" src="https://user-images.githubusercontent.com/8725110/231778076-643fe1c2-98bf-4c84-a250-8633aded1136.png">

It's seem had been fixed it #332 , BUT not works in latest version.

**Comment by YikaJ** [comment]
EXPECTED:
<img width="575" alt="image" src="https://user-images.githubusercontent.com/8725110/231780471-208d058e-af30-4c84-b0f1-453da158a8a8.png">

**Comment by suyingtao** [comment]
OpenAIChat and ChatOpenAI are diffrent:
- OpenAIChat is a language model.
- ChatOpenAI is a chat model. (Chat models use language models under the hood).
I think only ChatOpenAi added this feature.
