### ISSUE TITLE
Error when streaming tokens from server side in Next.JS

### ISSUE THREAD

**Issue by peps212** [langchain-ai/langchainjs#779]
Context: 
I'm trying to stream a response from my Next.js API route to the frontend.  I'm trying to use Server-Sent Events to accomplish that,  but im getting the following error : 

> error - TypeError: stream.getReader is not a function

Here's my server-side code, forgive me for how ugly and not functional it is, but I've been losing sleep over this

`

      class MyCallBackHandler extends CallbackManager{
          constructor(res) {
              super()
          }
          async handle(action) {
              console.log(action.token)
              //this.res.write(`data: ${action.token}\n\n`)
          }
      }

    export default async function handler(req, res) {
 

    res.setHeader('Content-Type', 'text/event-stream');
    res.setHeader('Cache-Control', 'no-cache');
    res.setHeader('Connection', 'keep-alive');

    const callbackManager = new MyCallBackHandler(res)

    const body = req.body

    const model = new ChatOpenAI({ 
        openAIApiKey: KEY,
        temperature: 0,
        streaming: true,
        callbackManager: callbackManager

    },
        {basePath: "https://oai.helicone.com/v1"});

    const tools = [new SerpAPI(serpKEY)];
   
    const executor = await initializeAgentExecutor(
      tools,
      model,
      "chat-conversational-react-description",
      true
    );

    executor.memory = new BufferMemory({
      returnMessages: true,
      memoryKey: "chat_history",
      inputKey: "inputF",
    });

    const input = new HumanChatMessage(body)
    const resp = await executor.call({input: input})

    try {

        console.log(resp)
        res.write(`data: ${JSON.stringify(resp)}\n\n`)
        //res.status(200).json({ output: "test" })
    } catch (e) {
        console.log(e)
    } finally {
        res.end()
    }
}`

**Comment by nsoticek** [comment]
Looks like this is a duplicate of [#548](https://github.com/hwchase17/langchainjs/issues/548)

From my point of view, the langchain function getBytes() calls a function that is not available in nodejs, see https://github.com/hwchase17/langchainjs/issues/548
