### ISSUE TITLE
Can we only import `node:fs/promises` if `filePathOrBlob` is a `string`

### ISSUE THREAD

**Issue by pkhyuk** [langchain-ai/langchainjs#784]
I'm trying to load a PDF in the format of a `Blob` (not in local fs) using `PDFLoader`, but I'm running into an issue trying to import the following on the client-side (that doesn't run NodeJS). 
```javascript
import { PDFLoader } from "langchain/document_loaders/fs/pdf"
```
Error msg:
```bash
error - node:fs/promises
Module build failed: UnhandledSchemeError: Reading from "node:fs/promises" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
Import trace for requested module:
node:fs/promises
./node_modules/langchain/dist/document_loaders/fs/buffer.js
./node_modules/langchain/dist/document_loaders/fs/pdf.js
./node_modules/langchain/document_loaders/fs/pdf.js
./lib/embeddings.ts
```

The issue seems to be this [line](https://github.com/hwchase17/langchainjs/blob/44b1ded0267445e1cbc54abe067fe820eb84840a/langchain/src/document_loaders/fs/buffer.ts#L1) that imports from `node:fs/promises` regardless of whether the object to load is a `string` (i.e. a file path in local fs) or a `Blob` (i.e. an object in memory).
https://github.com/hwchase17/langchainjs/blob/44b1ded0267445e1cbc54abe067fe820eb84840a/langchain/src/document_loaders/fs/buffer.ts#L1

Would it make sense to move the import here to be a [Dynamic Imports on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import) that only triggers if the `filePathOrString` is a `string` in the following `if` statement? https://github.com/hwchase17/langchainjs/blob/44b1ded0267445e1cbc54abe067fe820eb84840a/langchain/src/document_loaders/fs/buffer.ts#L19

**Comment by dmtrs** [comment]
There is also this comment on only node supported as it seems:
https://github.com/hwchase17/langchainjs/blob/44b1ded0267445e1cbc54abe067fe820eb84840a/langchain/src/document_loaders/fs/buffer.ts#L41

@pkhyuk did you manage to resolve the issue? I presume you trying to use langchain in browser?

**Comment by pkhyuk** [comment]
@dmtrs -- did exactly what you suggested. We ended up ripping the `PDFLoader` and removing the `fs` dependency.

**Comment by dmtrs** [comment]
Hey, thanks for getting back on this. Did had to fork the library? or was it possible by implementating some interface `*Loader` like?

**Comment by mannybatth** [comment]
I run into the same problem importing PDFLoader on a Next Edge function since it runs on V8 and doesnt come with node:fs/promises
