### ISSUE TITLE
LLMChain losing context

### ISSUE THREAD

**Issue by shoptacle** [langchain-ai/langchainjs#804]
The quickstart example for [Model + Prompt = LLMChain](https://js.langchain.com/docs/getting-started/guide-chat#model--prompt--llmchain), which should demonstrate message accumulation, isn't remembering (or at least not referencing) the previous input.  

Not sure whether I'm doing something wrong or it's a regression. I've copied this excerpt from the doc example linked above:

```javascript
  import { OpenAI } from 'langchain/llms/openai';
  import { PromptTemplate } from 'langchain/prompts';
  import { LLMChain } from 'langchain';

  const chat = new ChatOpenAI({ temperature: 0 });

  const translationPrompt = ChatPromptTemplate.fromPromptMessages([
    SystemMessagePromptTemplate.fromTemplate(
      'You are a helpful assistant that translates {input_language} to {output_language}.'
    ),
    HumanMessagePromptTemplate.fromTemplate('{text}'),
  ]);

  const chain = new LLMChain({
    prompt: translationPrompt,
    llm: chat,
  });

  const responseD = await chain.call({
    input_language: 'English',
    output_language: 'French',
    text: 'hi from London, how are you doing today',
  });
  console.log('responseD', JSON.stringify(responseD, null, 2));

  const responseE = await chain.call({
    input_language: 'English',
    output_language: 'French',
    text: 'Do you know where I am?',
  });
  console.log('responseE', JSON.stringify(responseE, null, 2));
```

**EXPECTED OUTPUT (or similar reference to London):** Yes, you mentioned that you are from London. However, as an AI language model, I don't have access to your current location unless you provide me with that information.

**ACTUAL OUTPUT**: I'm sorry, but as an AI language model, I don't have access to your location information. Is there anything else I can assist you with?

I've tried other references to information with similar results. Any ideas what I'm doing wrong here?

**Comment by ucanlendit** [comment]
+1 same
