### ISSUE TITLE
MarkdownTextSplitter API looks like it's not working as document expected

### ISSUE THREAD

**Issue by CongHaoYang** [langchain-ai/langchainjs#840]
![image](https://user-images.githubusercontent.com/55088950/232431374-9a71176d-e950-4e92-a56b-84152bd0be20.png)

![image](https://user-images.githubusercontent.com/55088950/232431315-98b4e94e-9f69-4602-9b1e-13b2dc91e803.png)

the document example as follow:
 
<img width="866" alt="image" src="https://user-images.githubusercontent.com/55088950/232431829-a59cf592-d484-401b-884b-fa5bbfabb9ac.png">

**Comment by acliyang** [comment]
Same reslult in my testing. Not separate by header.

**Comment by carlonicora** [comment]
Has this been updated in the meantime? I ah trying to use the MarkdownTextSplitter and it still does not split by headers.

**Comment by alivres** [comment]
Still doesn't work in latest version...
