### ISSUE TITLE
Motorhead memory example broken

### ISSUE THREAD

**Issue by azcoffeehabit** [langchain-ai/langchainjs#894]
The memory example for Motorhead Memory is broken.  Appears to be pre 58 but also has syntax errors.  Fixing the errors in the code to bring to 58 version allows the compilation but the the example code fails to run.  

$ yarn run start ./src/memory/buffer_motorhead.ts
/mnt/c/workspace/llm/langchainjs/examples/src/index.ts:35
  throw new Error(`Could not load example ${exampleName}: ${e}`);
        ^

Error: Could not load example ./src/memory/buffer_motorhead.ts: TypeError: fetch failed
    at <anonymous> (/mnt/c/workspace/llm/langchainjs/examples/src/index.ts:35:9)

**Comment by azcoffeehabit** [comment]
code example

`import { ConversationChain } from "langchain/chains";
import { ChatOpenAI } from "langchain/chat_models/openai";
import { MotorheadMemory } from "langchain/memory";
import { ChatPromptTemplate, SystemMessagePromptTemplate, HumanMessagePromptTemplate } from "langchain/prompts";

const model = new ChatOpenAI({});
const memory = new MotorheadMemory({
  returnMessages: true,
  memoryKey: "history",
  sessionId: "user-id",
  motorheadURL: "localhost:8080",
});

await memory.init(); // loads previous state from Motörhead 🤘
const context = memory.context
  ? `
Here's previous context: ${memory.context}`
  : "";

const chatPrompt = ChatPromptTemplate.fromPromptMessages([
  SystemMessagePromptTemplate.fromTemplate(
    `The following is a friendly conversation between a human and an AI. The AI is talkative and provides lots of specific details from its context. If the AI does not know the answer to a question, it truthfully says it does not know.${context}`
  ),
  HumanMessagePromptTemplate.fromTemplate("{input}"),
]);

const chain = new ConversationChain({
  memory,
  prompt: chatPrompt,
  llm: model,
});

const res1 = await chain.call({ input: "Hi! I'm Jim." });
console.log({ res1 });`

**Comment by Czechh** [comment]
Hey @azcoffeehabit here's a working example https://github.com/getmetal/motorhead/tree/main/examples/chat-js
