### ISSUE TITLE
CSV Loader - Get only 2 rows when queried

### ISSUE THREAD

**Issue by perfectpluto** [langchain-ai/langchainjs#899]
Hi there, 

Thank you for an awesome library.. I have been reading through it and is very impressed.. Also it is evolving extremely rapidly..

I am trying to read a CSV file (a list of 100 trump tweets) for analysis. When I try to read the docs loaded by the CSVLoader, I get 100 docs. I add them to a MemoryVectorStore and I can see it has 100 docs in that as well. However whenI try to use the VectorStore with OpenAI LLM Model and issue a simple query, I always get "2 rows". I get the same response even after I reduce the number of tweets in the CSV file from 100 to 50. 

Can you please let me know what is it that I am doing wrong?

Here is the relevant part of the code that matters:
```

import { OpenAI } from "langchain/llms/openai";
import { CSVLoader } from "langchain/document_loaders/fs/csv";
import { MemoryVectorStore } from "langchain/vectorstores/memory";

const OPENAI_API_KEY = 'sk-xxxxxxxxxxxxxxx';

const model = new OpenAI({
  openAIApiKey: OPENAI_API_KEY,
  temperature: 0.9
}); 
const loader = new CSVLoader("documents/trumptweets.csv");
const docs = await loader.load();
console.log(docs); //Prints 100 

const vectorStore = await MemoryVectorStore.fromDocuments(docs, new OpenAIEmbeddings({openAIApiKey: OPENAI_API_KEY}));
console.log("\n\nVectorStore created from the docs", vectorStore.memoryVectors.length); //Prints 100

const chain = RetrievalQAChain.fromLLM(model, vectorStore.asRetriever());

async function askQuestion(q: string) {
  console.log("\n\nQ) ", q);
  await chain.call({query: q, chat_history: []});
  console.log();
}

await askQuestion("How many rows are in the dataset?");
```

_Q)  How many rows are in the dataset?
 There are two rows in the dataset._

Surprisingly, I can ask questions about a tweet that is not part of this "2 rows" dataset and I get a right answer.

Q)  What did Trump say about his birthday?
 Trump said "Thanks to all for your thoughtful birthday wishes" on June 16, 2009.

**Comment by homanp** [comment]
I don't think a vectorstore is the correct way of doing it. At least not storing each row as a separate entity. The python lib has CSV agent which should do a better job but It's not added to the TS implementation of Langchin yet.
