### ISSUE TITLE
Redis is not available as a vectorstore

### ISSUE THREAD

**Issue by mmoraisTRT** [langchain-ai/langchainjs#903]
Hello everybody.

  I've been using Redis as a vectorstore in the python version of Langchain. Isn't it possible to use it also in the JS version?

If not, does anyone have any suggestions for an alternative that could be deployed with equal simplicity in a docker environment?

Thanks in advance.

**Comment by actengage** [comment]
You'd have to write an adapter. It shouldn't be hard to do. An alternative, checkout Milvus. It's open source, and ships with a docker setup. 

https://milvus.io/
https://js.langchain.com/docs/modules/indexes/vector_stores/integrations/milvus

**Comment by mmoraisTRT** [comment]
Thanks for the reply, @actengage.

I'm flirting with Pinecone, but I have an institutional constraint here that prevents me from storing the vectors/contents outside of our private infrastructure.

I'm going to study Milvus...thanks for the tip.

I'm also thinking of contributing to langchainjs by implementing an integration with Redis as vectorstore. It doesn't seem like a big technical challenge to me. Do you think it's worth it?

**Comment by tommoor** [comment]
Absolutely worth it

**Comment by mvaker** [comment]
hi @mmoraisTRT , @tommoor , @actengage , Redis is now available as a VectorStore since [Release 0.0.76](https://github.com/hwchase17/langchainjs/releases/tag/0.0.76)

**Comment by mmoraisTRT** [comment]
Great news, @mvaker. Thanks for letting us know.
