### ISSUE TITLE
Support for HTTP files? 

### ISSUE THREAD

**Issue by m10rten** [langchain-ai/langchainjs#947]
eg https://exampl.co/static/file1.pdf in the PDFLoader, or can we create an HTTPLoader and then infer from response or request url eg `.pdf`.

Looking for a `./web/http.ts`, any ideas for this file?

**Comment by m10rten** [comment]
So how would a pdf be fetched from a url?

**Comment by jacoblee93** [comment]
You could always just call `fetch(pdfUrl)`, parse the response, and pass it to the loader?
