### ISSUE TITLE
How do I add prompts in VectorDBQAChain?

### ISSUE THREAD

**Issue by Rishab1207** [langchain-ai/langchainjs#963]
I'm using `PineconeStore` and `VectorDBQAChain` for giving answers to users questions by looking up in the pinecone vector database but now i want to add prompts to my bot. How do I add it? I tried looking up in the documentation and the typescript types but couldn't find anything

**Comment by ddeerdevil** [comment]
You can pass the param `combineDocumentsChain` with your custom prompt

**Comment by MaximeThoonsen** [comment]
Hey @Rishab1207 did it work for you?

With a bit of code if you are still struggling:

```typescript  
  const llmChain = new LLMChain({ llm: model, prompt: promptTemplateBot })
  const stuffChain = new StuffDocumentsChain({ llmChain })

  const chain = new VectorDBQAChain({
    vectorstore: vectorStore,
    combineDocumentsChain: stuffChain,
    returnSourceDocuments: true,
    k: 4,
  })
```

**Comment by MaximeThoonsen** [comment]
Hey @Rishab1207 , I just finished an entire [presentation on it](https://docs.google.com/presentation/d/1TMfaJwXg50n6aCT8wdee9hOMqgoLOoCWLJJ405bqBbk/edit?pli=1#slide=id.g249d4435930_0_381) 
Maybe this code will help you as well:

````typescript 
const model = new OpenAI({ modelName: 'gpt-3.5-turbo' })
 const promptTemplateBot = /*#__PURE__*/ new PromptTemplate({
   template:
     'You act as if you were Maxime Thoonsen a CTO of a digital service ...' +
     'Context:\n\n{context}\n\nQuestion: {question}\nHelpful Answer:"',
   inputVariables: ['context', 'question'],
 })

 const llmChain = new LLMChain({ llm: model, prompt: promptTemplateBot })
 const stuffChain = new StuffDocumentsChain({ llmChain })

 const vectorStore = new SupabaseVectorStore(new OpenAIEmbeddings(), {
   client,
   tableName: 'documents',
   queryName: 'match_documents',

 })

 const chain = new VectorDBQAChain({
   vectorstore: vectorStore,
   combineDocumentsChain: stuffChain,
   k: 4,
 })

 const result = await chain.call({ query: question })

**Comment by MaximeThoonsen** [comment]
@Rishab1207 I have reread your question. You don't need to pass the {context} and {question} manually. The context is pull during the processing of the chain and the question when you call the chain `await chain.call({ query: question })`.
Hope it helps

**Comment by Rishab1207** [comment]
Thanks @MaximeThoonsen.

**Comment by Rishab1207** [comment]
@MaximeThoonsen Can you also tell me how can I use memory/chat history along with `VectorDBQAChain`. 

Here's what I tried:

```ts
router.post("/api/gpt/get-response", async (req, res) => {
	const { userQuery } = JSON.parse(req.body);

	res.setHeader("Transfer-Encoding", "chunked");
	res.setHeader("Cache-Control", "no-cache");

	try {
		// some pinecone initialisation code
		const pineconeIndex = client.Index("my index");

		const vectorStore = await PineconeStore.fromExistingIndex({some variables});

		// Model
		const streamedModel = new ChatOpenAI({
			// some required parameters
			streaming: true,
		});

		const promptTemplateBot = new PromptTemplate({
			template: `my prompt`,
			inputVariables: ["context", "question"],
		});

		const llmChain = new LLMChain({
			llm: streamedModel,
			prompt: promptTemplateBot,
			memory,
		});

		const stuffChain = new StuffDocumentsChain({ llmChain });

		const chain = new VectorDBQAChain({
			vectorstore: vectorStore,
			combineDocumentsChain: stuffChain,
			k: 4,
		});

		await chain.call({ query: userQuery });
	} catch (error: any) {
		console.log({ error: error.message });
	}
});
```

```ts
const memory = new BufferMemory({
	chatHistory: new UpstashRedisChatMessageHistory({
		sessionId: "test", // Or some other unique identifier for the conversation
		config: {
			url: "some_url", // Override with your own instance's URL
			token: "abcd", // Override with your own instance's token
		},
	}),
	returnMessages: true,
	inputKey: "test-input-key",
	memoryKey: "history",
});
```

Few questions:
1. When I'm using `console.log({ memory: await memory.loadMemoryVariables({}) });` I'm only getting AI responses in the memory not my questions in that. Here's a screenshot of my redis db

![image](https://github.com/hwchase17/langchainjs/assets/46566471/da87991e-e6ef-43c9-b976-01ecc65bab76)

2. How the prompt variables are automatically pulled in? I want to pass the conversation/conversation summary as context, how do I do it?
3. What's input/output key that we pass in the memory object?
4. How can I check the value of promptTemplateBot once the variables are passed in it?

**Comment by MaximeThoonsen** [comment]
hey @Rishab1207,
I haven't played much with history so I can't answer you.
> How the prompt variables are automatically pulled in? I want to pass the conversation/conversation summary as context, how do I do it?
I think you reach a point where you should look at the code, you'll understand how it works. The context comes from the result in the search from your database. The question, it's you who give it to the chain (your userQuery)
> What's input/output key that we pass in the memory object?
I haven't played much with memory..
> How can I check the value of promptTemplateBot once the variables are passed in it?
Maybe with the verbose mode or with intermediate_steps. Or you extend the class and you add console.log where you need them :)

**Comment by miracsengonul** [comment]
> @MaximeThoonsen Can you also tell me how can I use memory/chat history along with `VectorDBQAChain`.
> 

Have you found how to use memory/chat history in combination with `VectorDBQAChain`?

**Comment by MaximeThoonsen** [comment]
I haven't tried it

**Comment by Rishab1207** [comment]
@miracsengonul Check this https://discord.com/channels/1038097195422978059/1114547577736667249/1118236755993301023

**Comment by miracsengonul** [comment]
> @miracsengonul Check this https://discord.com/channels/1038097195422978059/1114547577736667249/1118236755993301023

Thank you but I can't access the link
