### ISSUE TITLE
How to get token count, callbacks work but just for ChatOpenAI but not for RetrievalQAChain

### ISSUE THREAD

**Issue by theTechGoose** [langchain-ai/langchainjs#965]
I am trying to get a token count for a process, I am passing callbacks to the class initialization like this

```typescript
let finalTokens = 0
const initPayload = {
  openAIApiKey: process.env['OPEN_AI_KEY'],
  temperature: 1.5,
  callbacks: [
    {
      handleLLMEnd: (val) => {
        try {
          const tokens = val.llmOutput.tokenUsage.totalTokens
          finalTokens += tokens
          console.log({tokens, finalTokens})
        } catch {
          console.log(val.generations[0])
        }
      },
    },
  ],
};
```

However all of the calls from a RetrievalQAChain end up in the catch portion of that try-catch block as 'tokenUsage' does not exist for those calls. Can someone point me in the right direction?

**Comment by miekassu** [comment]
I'm having a similar issue.
When I define `gpt-3.5-turbo` as the model for `OpenAI` construct, `llmOutput` is missing `tokenUsage` object.

Using the same construct, but not defining the model returns `token usage` as part of `llmOutput`

Not working:
```
  const model = new OpenAI({
    openAIApiKey: openAISecret,
    modelName: 'gpt-3.5-turbo',
    callbacks: [
      {
        handleLLMEnd: async (output: LLMResult) => {
          logger.info('output', { output })
          logger.info('tokenUsage', { tokenUsage: output.llmOutput })
          // tokenUsage: UNDEFINED
        },
      },
    ],
  })
```

Working:
```
  const model = new OpenAI({
    openAIApiKey: openAISecret,
    callbacks: [
      {
        handleLLMEnd: async (output: LLMResult) => {
          logger.info('output', { output })
          logger.info('tokenUsage', { tokenUsage: output.llmOutput })
          // tokenUsage: found
        },
      },
    ],
  })
```

**Comment by ibrahimyaacob92** [comment]
still waiting for the solution on this

**Comment by pond918** [comment]
tested with azure API:
```shell
curl -X POST -H 'Content-type: application/json' -H 'User-Agent: OpenAI/NodeJS/3.3.0' -H 'api-key: xxxxx' -H --data '{"model":"gpt-3.5-turbo","temperature":0.7,"top_p":1,"frequency_penalty":0,"presence_penalty":0,"n":1,"stream":false,"messages":[{"role":"user","content":"!"}]}' https://{azureApiInstanceName}.openai.azure.com/openai/deployments/{azureOpenAIApiDeploymentName}/chat/completi ns\?api-version=2023-05-15
```
**stream=false** gets usage data, works as expected.
**stream=true** result "usage":null

**Comment by j1philli** [comment]
I am also running into this. There doesn’t seem to be anyway to grab cost or at least token usage when calling chains or agents. Having and output after a chain or agent finishes with total usage would be great

**Comment by nikorter** [comment]
same problem here, when streaming is set to true it doesn't return token usage. Any idea for workaround?

**Comment by mchalapuk** [comment]
Hello everyone,

I recently started working on a stealth startup, and I'm using langchainjs as a core component of our tech stack. I must say, I've been impressed with the work done here! Thank you so much for all your hard work on this project, and for providing tools that startups like mine can rely on!

While integrating the library, I noticed the problem of lack of token statistics when using ChatOpenAi in streaming mode. I did some digging in the code and I believe I found the source of the problem.

In [`_generate`](https://github.com/hwchase17/langchainjs/blob/65e59d669889ef07a564c5ec8fd23e21ed1aa68a/langchain/src/chat_models/openai.ts#L471) method of ChatOpenAi class it's expected that [`data.usage`](https://github.com/hwchase17/langchainjs/blob/65e59d669889ef07a564c5ec8fd23e21ed1aa68a/langchain/src/chat_models/openai.ts#L631) contains `completion_tokens`, `prompt_tokens`, and `total_tokens` fields which are later copied to `tokenUsage`. When ChatOpenAi is instantiated with `streaming: false`, [`response.data` field](https://github.com/hwchase17/langchainjs/blob/65e59d669889ef07a564c5ec8fd23e21ed1aa68a/langchain/src/chat_models/openai.ts#L752) from the call to `OpenAIApi.createChatCompletion` is returned as data. `response.data` is an instance of [`Completion`](https://github.com/openai/openai-node/blob/3ec43ee790a2eb6a0ccdd5f25faa23251b0f9b8e/src/resources/completions.ts#L32) which indeed contains [`usage`](https://github.com/openai/openai-node/blob/3ec43ee790a2eb6a0ccdd5f25faa23251b0f9b8e/src/resources/completions.ts#L94) with the required fields. That's why token usage works with `streaming: false`. When ChatOpenAi is instantiated with `streaming: true`, `response` object is not created by the OpenAIApi but in the code of `_generate` instead. This branch of the implementation [doesn't set the `usage` field](https://github.com/hwchase17/langchainjs/blob/65e59d669889ef07a564c5ec8fd23e21ed1aa68a/langchain/src/chat_models/openai.ts#L540) at all.

I believe that adding the required fields, using the [.getNumTokensFromMessages(...)](https://github.com/hwchase17/langchainjs/blob/65e59d669889ef07a564c5ec8fd23e21ed1aa68a/langchain/src/chat_models/openai.ts#L666) might address this.

**Comment by MirzaHasnat** [comment]
Did anyone find issue for this?

**Comment by ankitruong** [comment]
I think the reason is that the GPT-3.5-turbo model can only be used for Chat models.

```shell
curl https://api.openai.com/v1/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer ...." \
  -d '{
    "model": "gpt-3.5-turbo",         
    "prompt": "Say this is a test",
    "max_tokens": 7,
    "temperature": 0
  }'
{
  "error": {
    "message": "This is a chat model and not supported in the v1/completions endpoint. Did you mean to use v1/chat/completions?",
    "type": "invalid_request_error",
    "param": "model",
    "code": null
  }
}'
``` 

I had to update my old code from 'OpenAI' to 'ChatOpenAI', and that fixed the issue.
```typescript
// old
// const model = new OpenAI({ temperature: 0, openAIApiKey: KEY, modelName: "gpt-3.5-turbo" });
// new 
const model = new ChatOpenAI({ temperature: 0, openAIApiKey: KEY, modelName: "gpt-3.5-turbo" });

const prompt = PromptTemplate.fromTemplate(
  "What is a good name for a company that makes {product}?"
);

const chain = new LLMChain({ llm: model, prompt }); 

const resA2 = await chain.run("colorful socks", {callbacks: [{
  handleLLMEnd: (output, runId, parentRunId?, tags?) => { // comment 
    const { completionTokens, promptTokens, totalTokens } =
      output.llmOutput?.tokenUsage; // undefined
    console.log(completionTokens ?? 0);
    console.log(promptTokens ?? 0);
    console.log(totalTokens ?? 0);
  },
}]});

```

**Comment by liowalex** [comment]
I managed to count tokens for `streaming: true` by using callbacks:

    ```js
const model = new ChatOpenAI({ modelName: "gpt-3.5-turbo", streaming: true });
    const chain = new LLMChain({ llm: model, prompt })
    const { text: assistantResponse } = await chain.call({
      query: query,
    }, {
      callbacks: [
        {
          handleChatModelStart: async (llm, messages) => {
            const tokenCount = tokenCounter(messages[0][0].content);
            // The prompt is available here: messages[0][0].content
          },
          handleChainEnd: async (outputs) => {
            const { text: outputText } = outputs;
            // outputText is the response from the chat call
            const tokenCount = tokenCounter(outputText);
          }
        }
      ]
    });
```

**Comment by jwilger** [comment]
> I managed to count tokens for `streaming: true` by using callbacks:
> 
> ```js
> const model = new ChatOpenAI({ modelName: "gpt-3.5-turbo", streaming: true });
> const chain = new LLMChain({ llm: model, prompt })
> const { text: assistantResponse } = await chain.call({
>     query: query,
>   }, {
>     callbacks: [
>       {
>         handleChatModelStart: async (llm, messages) => {
>           const tokenCount = tokenCounter(messages[0][0].content);
>           // The prompt is available here: messages[0][0].content
>         },
>         handleChainEnd: async (outputs) => {
>           const { text: outputText } = outputs;
>           // outputText is the response from the chat call
>           const tokenCount = tokenCounter(outputText);
>         }
>       }
>     ]
>   }
> );
> ```

Doesn't that only account for the initial prompt and the final response (not any intermediate calls for functions, etc)?

**Comment by girithodu** [comment]
> I think the reason is that the GPT-3.5-turbo model can only be used for Chat models.
> 
> ```shell
> curl https://api.openai.com/v1/completions \
>   -H "Content-Type: application/json" \
>   -H "Authorization: Bearer ...." \
>   -d '{
>     "model": "gpt-3.5-turbo",         
>     "prompt": "Say this is a test",
>     "max_tokens": 7,
>     "temperature": 0
>   }'
> {
>   "error": {
>     "message": "This is a chat model and not supported in the v1/completions endpoint. Did you mean to use v1/chat/completions?",
>     "type": "invalid_request_error",
>     "param": "model",
>     "code": null
>   }
> }'
> ```
> 
> I had to update my old code from 'OpenAI' to 'ChatOpenAI', and that fixed the issue.
> 
> ```ts
> // old
> // const model = new OpenAI({ temperature: 0, openAIApiKey: KEY, modelName: "gpt-3.5-turbo" });
> // new 
> const model = new ChatOpenAI({ temperature: 0, openAIApiKey: KEY, modelName: "gpt-3.5-turbo" });
> 
> const prompt = PromptTemplate.fromTemplate(
>   "What is a good name for a company that makes {product}?"
> );
> 
> const chain = new LLMChain({ llm: model, prompt }); 
> 
> const resA2 = await chain.run("colorful socks", {callbacks: [{
>   handleLLMEnd: (output, runId, parentRunId?, tags?) => {
>     const { completionTokens, promptTokens, totalTokens } =
>       output.llmOutput?.tokenUsage; 
>     console.log(completionTokens ?? 0);
>     console.log(promptTokens ?? 0);
>     console.log(totalTokens ?? 0);
>     
> // "llmOutput": {
> //     "tokenUsage": {
> //       "completionTokens": 3,
> //       "promptTokens": 20,
> //       "totalTokens": 23
> //     }
> //   }
>   },
> }]});
> ```

This solved the issue for me too!

**Comment by rutwikpulseenergy** [comment]
Hi Thread, I am using typescript sdk of langchain. I am still receiving 0 token count. Can you please here ?

**Comment by rutwikpulseenergy** [comment]
@jacoblee93

**Comment by rutwikpulseenergy** [comment]
@hwchase17 @nfcampos @bracesproul @sullivan-sean  Any help here ?

**Comment by davkorss** [comment]
If you set `streaming` property to false from ChatOpenAI constructor, the token count will work again

**Comment by gkhngyk** [comment]
> Yes I'm experimenting the same issue here, the token counter it seems not to be working for agents, I'm getting all token counts on 0 here I paste the code I'm using and the log I'm getting back
> 
> **Package Version**: 1.36.0 V8 and Chromium: Node: 20.9.0; Chromium: 122
> 
> ```
> import { ChatOpenAI } from "@langchain/openai";
> import { ChatPromptTemplate, MessagesPlaceholder } from 'langchain/prompts';
> import { TavilySearchResults } from "@langchain/community/tools/tavily_search";
> import { AgentExecutor, createOpenAIToolsAgent } from "langchain/agents";
> 
> 
> // Define the tools the agent will have access to.
> const tools = [new TavilySearchResults({ maxResults: 1, apiKey: 'MY-API-KEY' })];
> 
> const llm = new ChatOpenAI({
>   modelName: "gpt-4-turbo",
>   temperature: 0.15,
>   maxRetries: 3,
>   timeout: 30000,
>   callbacks: [
>     {
>       handleLLMEnd(output) {
>         console.log(output)
>         output.generations.map(generation => {
>           generation.map(g => {
>             // console.log(g.message.response_metadata.tokenUsage)
>           })
>         })
>       },
>     }
>   ]
> });
> 
> const prompt = ChatPromptTemplate.fromMessages([
>         [
>             'system',
>             `You are a virtual agent`,
>         ],
>         new MessagesPlaceholder({
>             variableName: 'chat_history',
>             optional: true,
>         }),
>         ['user', '{input}'],
>         new MessagesPlaceholder({
>             variableName: 'agent_scratchpad',
>             optional: false,
>         }),
>     ]);
> 
> const agent = await createOpenAIToolsAgent({
>   llm,
>   tools,
>   prompt,
> });
> 
> const agentExecutor = new AgentExecutor({
>   agent,
>   tools,
> });
> 
> const result = await agentExecutor.invoke({
>   input: "what is LangChain?, describe it in a sentence",
> });
> 
> console.log(result);
> ```
> 
> The output
> 
> ```
> {
>   generations: [
>     [
>       ChatGenerationChunk {
>         text: 'LangChain is a software library designed to facilitate the development of applications that integrate language models, providing tools and frameworks to streamline the process of building AI-powered language understanding and generation features.',
>         generationInfo: {
>           prompt: 0,
>           completion: 0,
>           finish_reason: 'stop'
>         },
>         message: AIMessageChunk {
>           lc_serializable: true,
>           lc_kwargs: {
>             content: 'LangChain is a software library designed to facilitate the development of applications that integrate language models, providing tools and frameworks to streamline the process of building AI-powered language understanding and generation features.',
>             additional_kwargs: {},
>             response_metadata: {
>               prompt: 0,
>               completion: 0,
>               finish_reason: 'stop'
>             },
>             tool_call_chunks: [],
>             tool_calls: [],
>             invalid_tool_calls: []
>           },
>           lc_namespace: [ 'langchain_core', 'messages' ],
>           content: 'LangChain is a software library designed to facilitate the development of applications that integrate language models, providing tools and frameworks to streamline the process of building AI-powered language understanding and generation features.',
>           name: undefined,
>           additional_kwargs: {},
>           response_metadata: {
>             prompt: 0,
>             completion: 0,
>             finish_reason: 'stop'
>           },
>           tool_calls: [],
>           invalid_tool_calls: [],
>           tool_call_chunks: []
>         },
>         __proto__: {
>           constructor: ƒ ChatGenerationChunk(),
>           concat: ƒ concat()
>         }
>       }
>     ]
>   ]
> }
> ```

same issue

**Comment by gkhngyk** [comment]
@bracesproul Brace, I think the 0 token issue is a very serious problem, any chance you can look into it?

**Comment by clovisrodriguez** [comment]
Hey community I create this counter, it might not be perfect, but I tested againts Langsmith and it gets a pretty close count, if you have any ideas to improve it everyone are more than welcome to improve it, I hope you find it useful:

```js
import { encodingForModel } from 'js-tiktoken';

export class TokenCounter {
    private _totalTokens: number = 0;
    private _promptTokens: number = 0;
    private _completionTokens: number = 0;
    private _enc: any;

    constructor(model) {
        this._enc = encodingForModel(model);
    }

    encodeAndCountTokens(text: string): number {
        return this._enc.encode(text).length;
    }

    handleLLMEnd(result: any) {
        result.generations.forEach((generation: any) => {
            const content = generation[0]?.message?.text || '';
            const calls = generation[0]?.message?.additional_kwargs || '';
            console.log('Calls & Content:', {
                calls,
                content,
            });
            const output = JSON.stringify(calls, null, 2);
            const tokens = this.encodeAndCountTokens(content + output);
            this._completionTokens += tokens;
        });
        console.log('Tokens for this LLMEnd:', this._completionTokens);
    }

    handleChatModelStart(_, args) {
        args[0].forEach((arg) => {
            const content = arg?.content || '';
            const calls = arg?.additional_kwargs || '';

            const tokens = this.encodeAndCountTokens(
                content + JSON.stringify(calls, null, 2),
            );
            this._promptTokens += tokens;
            console.log('content:', content, calls);
        });

        console.log('Tokens for this ChatModelStart:', this._promptTokens);
    }

    modelTracer() {
        return {
            handleChatModelStart: this.handleChatModelStart.bind(this),
            handleLLMEnd: this.handleLLMEnd.bind(this),
        };
    }

    sumTokens() {
        this._totalTokens = this._promptTokens + this._completionTokens;
        console.log('Total Tokens:', this._totalTokens);
    }
}
```

**Comment by jacoblee93** [comment]
Yes, will fix this as OpenAI recently added support. There is an open PR here https://github.com/langchain-ai/langchainjs/pull/5485

**Comment by zaiddabaeen** [comment]
Hey @jacoblee93. I just tested Release 0.2.4 and it still does not show the token usage when using `RunnableSequence`.

The code:

```
const chain = RunnableSequence.from([
    {
      sourceDocuments: RunnableSequence.from([
        (input) => input.question,
        vectorStoreRetriever,
      ]),
      question: (input) => input.question,
    },
    {
      sourceDocuments: (previousStepResult) => previousStepResult.sourceDocuments,
      question: (previousStepResult) => previousStepResult.question,
      context: (previousStepResult) =>
        formatDocumentsAsString(previousStepResult.sourceDocuments),
    },
    {
      result: prompt.pipe(llm).pipe(new StringOutputParser()),
      sourceDocuments: (previousStepResult) => previousStepResult.sourceDocuments,
    },
  ]);

  return await chain.stream({question: question}, {
    callbacks: [
      {
        handleLLMEnd(output: LLMResult, runId: string, parentRunId?: string, tags?: string[]): any {
          output.generations.map((g) => console.log(JSON.stringify(g, null, 2)));
        }
      }
    ]
  });
```

The output is as follows:

```
 [
   {
     "text": "<the loooong answer goes here>",
     "generationInfo": {
       "prompt": 0,
       "completion": 0,
       "finish_reason": "stop"
     },
     "message": {
       "lc": 1,
       "type": "constructor",
       "id": [
         "langchain_core",
         "messages",
         "AIMessageChunk"
       ],
       "kwargs": {
         "content": "<the loooong answer goes here>",
         "additional_kwargs": {},
         "response_metadata": {
           "prompt": 0,
           "completion": 0,
           "finish_reason": "stop"
         },
         "tool_call_chunks": [],
         "tool_calls": [],
         "invalid_tool_calls": []
       }
     }
   }
 ]

```

Am I looking for the token count in the wrong place? Or has it not been implemented yet to provide the token count at `handleLLMEnd` callback?

**Comment by jacoblee93** [comment]
Can you verify you're on latest version of core and LangChain OpenAI?

https://js.langchain.com/v0.2/docs/how_to/installation/#installing-integration-packages

Otherwise will check tomorrow

**Comment by zaiddabaeen** [comment]
Yes definitely:

```

  "dependencies": {
    "@langchain/community": "^0.2.5",
    "@langchain/core": "^0.2.5",
    "@langchain/openai": "^0.1.1",
    "langchain": "^0.2.4",
    ...
  },
```

All these packages are on latest.

**Comment by niztal** [comment]
Guys I see openai had just released this new update, can someone please integrate that?

http://url3243.email.openai.com/ls/click?upn=u001.IQLfsj4kk-2BK7JhymNusRMuGyvjSP8F93-2FQOfuyaC8cFZAn1DaY5ErGzWy1jZTm3mqplM9w7wsDIWXusl9Q626lzyBhdwNecguXmHCqJ7-2Fr9qxlZxrzvg9Afy4fpV8iDo-2BDpV-2Fzgl9nQv1rg9Seau7O-2FKKYRaAO7RhkwiDnavvOgwgGJa-2FvMSQXIS9QIeI9WrHjFZ_csrxeQslN6VkrtzRBvJlmMvJpK3BKAOrSrK22mDXH6tlliZtD6XUKdQyRE7sbWmMMrBbkj1A14zNL-2FtyGx0EiR4kKRHUjkljOnFgB0ciY25pwct0zRZT5lQqXSqfxR9wrk0qBJRCRiAGtzeDGrj-2BTRStrWH3a4QWbVWb8Q5jSdjM7aHpXpMGvP692AY9ilW55VWZkN7cAGY2i5j-2FlP2cz9vpuEEwBGiGPvKSUiCqxJD2C9UUUcuMH7fQ-2BhLecy82cgJgizLI44F1ABAVvP-2FLqpxvJI-2BAEhxFD4Ah4N116u-2BZBReW3lpKPx3zNAJkd7lDwlSFsD5xJHt1ehUOLoHCY-2F-2F-2FVPyb-2BWq8-2BXuym466uNMcyAo9Bx9IbmSOOnpO1xINZBewhx-2B4wkd4ZoNNM-2FcWHfAUQoFqEDNfX2lPvzBiuFwkhiXjHcuu-2Fls-2BWHp9WnmN4PVxD3Gmb-2FGQoHIi8Ly8JdWi7qEHAMZoEC1oYH1-2BPKkSK6Hc2I6Nxl4Dg0LeP1gS6WIM-2FthQD2-2Fum2hut7zGVmUJDGwxaq67mgy9gp-2FGf8XCGndKk0kwG49vm-2Fi4DD24egBDXlgU37O4jcKYp-2FneBBK74gdoTegQPej2CbdWpC87YUDX2yU1LOsmhmaOxwSiAOH-2BFlUl6-2B4pitY7BbV2e446GbSCZ9Pci6g2WTpGsUCeucvg21Up9zpDLqWQfZ-2Bis4IcU5BJYPk-2FwAXT-2BQcBCRqY3f1o8gVEm82lTS3i5PwjzR6CY6vv9Z-2F9tajfn4UnZMsQxkR3n8jM38UA3ldzfU3K3OH3whF26trNHtx-2F6dSd-2Fnrj-2FrO-2FYWJ8T2rXB-2F5fXkQOZeIWWOr5aVL9dW4o5jl1Z7LOrfSlBglFgXM0XiKrTrkBO-2F3-2Bz5-2BTJ7VPqt5BmTDJP-2F4pYBLDfJFFoFk-2B0xgxe1WKKL8V9P9m9BKgKrB-2BKHOQhVFvO-2Fu9oMmHqAYP

**Comment by niztal** [comment]
I see openai just released an update for that 

https://cookbook.openai.com/examples/how_to_stream_completions#4-how-to-get-token-usage-data-for-streamed-chat-completion-response

**Comment by rrichc** [comment]
Unfortunately I am also the latest packages, and get a 0 token count even for the last chunk that is supposed to contain usages. Zero counts happening for both `.streamEvents` and `.invoke` 

```
{
  "generations": [
    [
      {
        "text": "Hi there! How can I assist you today?",
        "generationInfo": {
          "prompt": 0,
          "completion": 0,
          "finish_reason": "stop"
        },
        "message": {
          "lc": 1,
          "type": "constructor",
          "id": [
            "langchain_core",
            "messages",
            "AIMessageChunk"
          ],
          "kwargs": {
            "content": "Hi there! How can I assist you today?",
            "additional_kwargs": {},
            "response_metadata": {
              "prompt": 0,
              "completion": 0,
              "finish_reason": "stop"
            },
            "tool_call_chunks": [],
            "tool_calls": [],
            "invalid_tool_calls": []
          }
        }
      }
    ]
  ]
}
```

```
{
  "generations": [
    [
      {
        "text": "removed for readability",
        "generationInfo": {
          "prompt": 0,
          "completion": 0,
          "finish_reason": "stop"
        },
        "message": {
          "lc": 1,
          "type": "constructor",
          "id": [
            "langchain_core",
            "messages",
            "AIMessageChunk"
          ],
          "kwargs": {
            "content": "removed for readability",
            "additional_kwargs": {},
            "response_metadata": {
              "prompt": 0,
              "completion": 0,
              "finish_reason": "stop"
            },
            "tool_call_chunks": [],
            "tool_calls": [],
            "invalid_tool_calls": []
          }
        }
      }
    ]
  ]
}
```

```
  ├── @langchain/community@0.2.9
  ├── @langchain/core@0.2.6
  ├── @langchain/openai@0.1.2
    ├── langchain@0.2.5
```

**Comment by jacoblee93** [comment]
Ah @rrichc, @zaiddabaeen, @gkhngyk and others, you'll need to pass `stream_options` like this:

```ts
  const response = await model.stream("Hello, how are you?", {
    stream_options: {
      include_usage: true,
    },
  });
```

You can also `bind` it to the model like this:

```ts
  const model = model.bind({
    stream_options: {
      include_usage: true,
    },
  });
```

```ts
import { StringOutputParser } from "@langchain/core/output_parsers";
import { ChatPromptTemplate } from "@langchain/core/prompts";
import { RunnableSequence } from "@langchain/core/runnables";
import { ChatOpenAI, OpenAIEmbeddings } from "@langchain/openai";
import { formatDocumentsAsString } from "langchain/util/document";
import { MemoryVectorStore } from "langchain/vectorstores/memory";

const llm = new ChatOpenAI({ modelName: "gpt-3.5-turbo", temperature: 0.0 }).bind({
  stream_options: {
    include_usage: true
  }
});
const vectorStore = await MemoryVectorStore.fromTexts([], [], new OpenAIEmbeddings());
const vectorStoreRetriever = vectorStore.asRetriever();

const SYSTEM_TEMPLATE = `You are a pro at responding to questions.`;
const prompt = ChatPromptTemplate.fromMessages([
  ["system", SYSTEM_TEMPLATE],
  ["human", "{question}"],
]);

const chain = RunnableSequence.from([
{
  sourceDocuments: RunnableSequence.from([
    (input) => input.question,
    vectorStoreRetriever,
  ]),
  question: (input) => input.question,
},
{
  sourceDocuments: (previousStepResult) => previousStepResult.sourceDocuments,
  question: (previousStepResult) => previousStepResult.question,
  context: (previousStepResult) =>
    formatDocumentsAsString(previousStepResult.sourceDocuments),
},
{
  result: prompt.pipe(llm).pipe(new StringOutputParser()),
  sourceDocuments: (previousStepResult) => previousStepResult.sourceDocuments,
},
]);

const stream = await chain.stream({question: "Who is this about?"}, {
  callbacks: [
    {
      handleLLMEnd(output: any, runId: string, parentRunId?: string, tags?: string[]): any {
        output.generations.map((g: any) => console.log(JSON.stringify(g, null, 2)));
        /*
          [
            {
              "text": "I'm here to provide information and assistance on a wide range of topics. Feel free to ask me anything you'd like to know more about!",
              "generationInfo": {
                "prompt": 0,
                "completion": 0,
                "finish_reason": "stop"
              },
              "message": {
                "lc": 1,
                "type": "constructor",
                "id": [
                  "langchain_core",
                  "messages",
                  "AIMessageChunk"
                ],
                "kwargs": {
                  "content": "I'm here to provide information and assistance on a wide range of topics. Feel free to ask me anything you'd like to know more about!",
                  "additional_kwargs": {},
                  "response_metadata": {
                    "prompt": 0,
                    "completion": 0,
                    "finish_reason": "stop"
                  },
                  "tool_call_chunks": [],
                  "usage_metadata": {
                    "input_tokens": 25,
                    "output_tokens": 29,
                    "total_tokens": 54
                  },
                  "tool_calls": [],
                  "invalid_tool_calls": []
                }
              }
            }
          ]
        */
      }
    }
  ]
});

for await (const chunk of stream) {
  // console.log(chunk);
}
```

We don't pass this through by default - maybe we should reconsider CC @ccurme.

We should also fix that misleading blank `response_metadata` field.

**Comment by jacoblee93** [comment]
Ah, never mind. That data does not refer to usage. Will close this, please reopen if the above setting doesn't fix.

Docs are here: https://js.langchain.com/v0.2/docs/how_to/chat_token_usage_tracking#openai-2

**Comment by rrichc** [comment]
@jacoblee93  Is there a proper way to pass `stream_options` to `streamEvents`? Like
```
      const eventStream = await this.agent.streamEvents(
        {
          input: input,
          chat_history: await this.zepMemory.chatHistory.getMessages(),
          signal: signal,
          stream_options: {
            include_usage: true,
          },
        },
        {
          version: "v1",
          callbacks: agentCallbacks,
        }
      );
```

I'd also like to use the `model.bind` way, but after binding I'm left with a runnable which I can't feed into `createToolCallingAgent` which expects a `BaseChatModel`, since I'm still using `AgentExecutor` and haven't been able to migrate to LCEL yet

**Comment by jacoblee93** [comment]
Oh dear. Yeah I will fix that typing - sorry about this!

**Comment by deranga** [comment]
@jacoblee93, I've just created a PR as mentioned above.

**Comment by akmaldira** [comment]
> AgentExe

Have you solve this?

and btw that provide a breakdown of token usage for each step in an Agent Executor?
